### ISSUE TITLE
add ftp visit support

### ISSUE THREAD

**Issue by cclu** [phuslu/goproxy#1006]
When we visit ftp://sourceware.org/pub/libffi/ , it fails and looks like:

> I0801 20:04:19.914026    5852 autoproxypac.go:146] start updater for https://raw
> .githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt, expiry=24h0m0s, durat
> ion=1h0m0s
> I0801 20:04:20.064035    5852 httpproxy.go:82] ListenAndServe("Default") on [::]
> :8087
> I0801 20:04:22.182156    5852 multidialer.go:232] MULTIDIALER DialTLS2("tcp", "a
> cer3820tg01.appspot.com:443") with good_addrs=0, bad_addrs=0
> I0801 20:04:22.734187    5852 gae.go:478] 127.0.0.1:12043 "GAE FETCH GET ftp://s
> ourceware.org/pub/libffi HTTP/1.1" 502 164

**Comment by jzp820927** [comment]
GAE 不知道 ftp 协议吧，只能 http 和 https

**Comment by phuslu** [comment]
gae 实现不了。

**Comment by cclu** [comment]
thx.

2016-08-01 20:17 GMT+08:00 Phus Lu <notifications@github.com>:

**Comment by jzp820927** [comment]
不过你可以试试 XX 的 X_tunnel 应该没问题
