### ISSUE TITLE
申请免费VPS翻墙的最新教程

### ISSUE THREAD

**Issue by kang000feng** [phuslu/goproxy#1009]
最新的免费VPS申请教程, 用来搭建goproxy-vps 和Shadowsocks , 请大家帮忙转发给身边朋友, 大家一起翻墙.﻿  https://plus.google.com/114529348026050003265/posts/ew5Hb8ppqDx

**Comment by jzp820927** [comment]
长期有效麽

**Comment by sypopo** [comment]
这几天到处都是推广这个的！楼主的邀请链接注册的vultr的同学们越多，楼主得到的回扣就越多

**Comment by jzp820927** [comment]
确实，其实推广是其次，邀请才是主要目的。不过有教程学习一下也不错。

**Comment by dapao9999** [comment]
卖推广拿提成的，跟传销一样。

**Comment by hcym** [comment]
挣钱传销不如五毛靠谱

**Comment by phuslu** [comment]
楼主只是一发而已，而且不是硬广也没有人肉顶贴。

没必要口诛太过。
