### ISSUE TITLE
大批红黄字，求解决 .

### ISSUE THREAD

**Issue by LawrencePage** [phuslu/goproxy#1011]

**Comment by LawrencePage** [comment]
W0803 13:08:49.634305    6308 gae.go:465] 127.0.0.1:50752 "GAE DIRECT POST https://clients4.google.com/chrome-sync/dev/experimentstatus HTTP/1.1" error: http2.StreamError(stream error: stream ID 9; STREAM_CLOSED)
E0803 13:08:49.636305    6308 handler.go:97] 127.0.0.1:50752 Filter RoundTrip *gae.Filter error: stream error: stream ID 9; STREAM_CLOSED

**Comment by jzp820927** [comment]
没遇到过。

**Comment by LawrencePage** [comment]
跟ip没关系，用之前的版本都不会出现这个错误.

**Comment by jzp820927** [comment]
禁用 http2 试试

**Comment by phuslu** [comment]
试下 https://github.com/phuslu/goproxy/issues/1013
