### ISSUE TITLE
奇怪, 中国谷歌彻底被封

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1025]
中国谷歌彻底被封?
居然都不能ping通, 只有203.208.42.0/24这种doc证书的可以

**Comment by phuslu** [comment]
我这边正常，如图
![2016-08-07_232316](https://cloud.githubusercontent.com/assets/195836/17463338/fe055e90-5cf5-11e6-97e9-33b69e584be7.png)

**Comment by jasonliul** [comment]
看来是网络暂时故障, 近几天中国谷歌不通, GP速度也差.

**Comment by blob2015** [comment]
这会儿，俺这边超级差……

**Comment by jasonliul** [comment]
刚刚又好了一会儿...

**Comment by jzp820927** [comment]
我这边中国 gg 也没问题

**Comment by yangchangyz** [comment]
中国政策己经放宽，准生二胎！！

**Comment by jzp820927** [comment]
跑题了

**Comment by yaoguaishou** [comment]
这些天运营商加强了，无论何时都会向用户分配内网IP

**Comment by jzp820927** [comment]
没遇到过，分配内网IP的情况

**Comment by MeABc** [comment]
@phuslu  社长，往你邮箱里发一封关于 “dialer” 的邮件，请查收。

**Comment by phuslu** [comment]
@MeABc 非常感谢，r950 已经修复。

**Comment by MeABc** [comment]
社长辛苦！我这边试了，没有问题，感谢社长！

又，从r943起到现在的r951，GoProxy 的 HTTP/2 已经能正常使用。你那边再试下，如果没有问题，建议是不是默认开启。

**Comment by blob2015** [comment]
@MeABc 
利好消息？感谢老兄，感谢社长
