### ISSUE TITLE
Goproxy的RegionFilters没有过滤本地局域网ip

### ISSUE THREAD

**Issue by codexss** [phuslu/goproxy#1028]
比如
192.168/16
10/8
等等……

**Comment by codexss** [comment]
在autoproxy.user.json中RegionFilters的Rules下面添加上这一行问题解决。
"局域网": "direct",

**Comment by phuslu** [comment]
谢谢 https://github.com/phuslu/goproxy/commit/5a36a32b5a11e056452edf139b1aefd91f3e0f54
