### ISSUE TITLE
r904无法在宽带拨号使用pac模式。系统是win10 64位。显示为goodip为0，但选全局马上15个goodip

### ISSUE THREAD

**Issue by 5fu** [phuslu/goproxy#1040]
goproxy版本最新的r904。服务器端2016/08/09版本，也重新上传了所有的app。现在是在宽带拨号的情况下无法使用pac模式，显示为goodip为0；同样在宽带拨号模式下选择全局模式马上就可以访问国外了，但同时国内网站也使用了GAE，造成浪费啊。

I0811 13:58:08.812437    1264 autoproxy_pac.go:149] start updater for https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt, expiry=24h0m0s, duration=1h0m0s
I0811 13:58:08.950029    1264 httpproxy.go:82] ListenAndServe("Default") on 127.0.0.1:8087
I0811 13:58:16.938137    1264 multidialer.go:242] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=0, bad_addrs=0
I0811 13:58:35.165425    1264 autoproxy.go:290] 127.0.0.1:55195 "AUTOPROXY ProxyPac GET /proxy.pac HTTP/1.1" - -
I0811 13:58:41.044741    1264 autoproxy.go:290] 127.0.0.1:55195 "AUTOPROXY ProxyPac GET /proxy.pac HTTP/1.1" - -

**Comment by jzp820927** [comment]
这个不科学啊，是浏览器插件试试？

**Comment by 5fu** [comment]
@jzp820927 谢谢回复！现在好像又正常了。好像是用记事本把autoproxy.jeon的编码改成ASCI什么的就正常了。原来的编码是utf8的

**Comment by jzp820927** [comment]
怎么这么多编码问题
