### ISSUE TITLE
现在不能用改autorange的方式下大于32M的视频了

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#1041]
无论是现在还是过去的版本，r900+、r700+、r600+，我都试过，在autorange加入
 "*.clipconverter.cc",
"*.googlevideo.com",

只会变成无法识别的0B
![360 20160811135057182](https://cloud.githubusercontent.com/assets/15207080/17580190/4d0a5546-5fcf-11e6-905a-58cbfdabf911.jpg)

推测应该不是社长改了，而是google有变动。

**Comment by jzp820927** [comment]
autorange 都还没完成

**Comment by drg78rnvgh** [comment]
@jzp820927 
以前可以的，前几天还下了800M的视频。
推测是google发生变动，社长没有跟进

**Comment by jzp820927** [comment]
这段时间感觉 google 的服务器是有点变化，我这边的感觉是 http/2 完全不能用了，不禁用的话，都会报错。所以观察段时间看看吧，有可能真是 google 服务器的问题

**Comment by Kisesy** [comment]
应该没问题，要不然换一个浏览器试一下
![20160811203143](https://cloud.githubusercontent.com/assets/5843694/17588739/78f528f0-6003-11e6-838d-442b127003a0.png)
![20160811203714](https://cloud.githubusercontent.com/assets/5843694/17588738/78e5bb22-6003-11e6-9d78-f76f8bb5e010.png)

**Comment by darkwolf99** [comment]
http2确实好像不能用了，早前几个版本默认已经强制关闭了

**Comment by jzp820927** [comment]
不知道是被 gfw 特征识别了，还是 google 服务器本身 http/2 有问题。
