### ISSUE TITLE
手机使用局域网中电脑PAC代理总是连不上网。

### ISSUE THREAD

**Issue by melos2016** [phuslu/goproxy#1043]
刚开GOP能用，过个几分钟就不能用了。

**Comment by phuslu** [comment]
不能重现。

其实我在家一直都是这么用的。。。

**Comment by inkdie** [comment]
成功: 已终止 PID 为 6628 的进程。


------------------------------------------------------
GoProxy Version    : r906 (go/f9ae6fc http2/f6f1b74 windows/amd64)
GoProxy Profile    : Default
Listen Address     : [fe80::a0b9:9f42:4b80:9578]:8087
Enabled Filters    : autoproxy,stripssl,autorange|autoproxy,gae,direct|autorange
Pac Server         : http://[fe80::a0b9:9f42:4b80:9578]:8087/proxy.pac
----------------------------------------------------

**Comment by inkdie** [comment]
现在怎么变这样了

**Comment by inkdie** [comment]
我现在手机能打开YouTube但无法播放

**Comment by jzp820927** [comment]
证书导入了没？浏览器应该没问题，apps 就说不定了。

**Comment by inkdie** [comment]
自动升级证书没换啊  推特网页可用。YouTube可以打开可以搜索页面打开除了不能播放视频没其他问题

**Comment by jzp820927** [comment]
是浏览器？还是 app

**Comment by MeABc** [comment]
> Pac Server : http://[fe80::a0b9:9f42:4b80:9578]:8087/proxy.pac

`fe80::a0b9:9f42:4b80:9578` 这个不是 ipv6 的本机地址吗？相当于 127.0.0.1 ，怎么能共享？

另，对 ipv6 不是很了解，还得等大神解释。

**Comment by inkdie** [comment]
@jzp820927 俩情况一样

**Comment by MeABc** [comment]
我上面说错了。

https://zh.wikipedia.org/wiki/IPv6

![11](https://cloud.githubusercontent.com/assets/18194126/17591973/03f9b4de-6013-11e6-939b-c6858e0b8366.png)

**Comment by hcym** [comment]
麻烦

**Comment by jzp820927** [comment]
PC 上试试有没有问题，PC 没问题，可能就是手机的问题了

**Comment by inkdie** [comment]
@jzp820927 PC没事

**Comment by MeABc** [comment]
> 监听IP设为[::]，跟ipv4 0.0.0.0一样

这个我了解。

**Comment by inkdie** [comment]
{
	"Default": {
		"Enabled": true,
		"Address": "0.0.0.0:8087",
	},
}


@melos2016 我设置准确

**Comment by phuslu** [comment]
当监听 IP 留空的时候，默认是优先显示本地 IPv6 的地址。

r910 已经改为优先显示 IPv4 地址了，请更新。

**Comment by phuslu** [comment]
不过这个修复只是修复显示信息的问题，和楼主遇到的问题关系不大。楼主的问题估计和自己的环境有关。

**Comment by inkdie** [comment]
@phuslu 并没有910

**Comment by phuslu** [comment]
travis-ci 在晚上一般都比较慢，请稍待片刻即可。

**Comment by riumiyama** [comment]
我這裡 Mac r909很難連上  YouTube無法播放  是不是IP問題 怎樣獲取可用IP 謝謝

**Comment by inkdie** [comment]
@phuslu 您说这个显示与youtube无法播放无关，但是更新完了bug消失了

**Comment by phuslu** [comment]
@inkdie ...

更新内容 commit history 可查。
相关性不是因果性。

不过能解决就好，这个本来就是个案。

**Comment by MeABc** [comment]
@riumiyama 

![55](https://cloud.githubusercontent.com/assets/18194126/17593358/3174f5cc-6018-11e6-8c2e-20caa2ce28f1.png)

**Comment by inkdie** [comment]
------------------------------------------------------
GoProxy Version    : r910 (go/f9ae6fc http2/f6f1b74 windows/amd64)
GoProxy Profile    : Default
Listen Address     : 192.168.75.1:8087
Enabled Filters    : autoproxy,stripssl,autorange|autoproxy,gae,direct|autorange
Pac Server         : http://192.168.75.1:8087/proxy.pac
------------------------------------------------------





奇怪，我的局域网是172.76.1.1，虽然显示错误但不影响使用

**Comment by melos2016** [comment]
@phuslu 更新之后显示虚拟网卡IP了

![abc](https://cloud.githubusercontent.com/assets/19543043/17593542/ce92e292-6018-11e6-8a01-d46b389a44e1.jpg)

**Comment by inkdie** [comment]
我看了一下情况跟楼上一样也是虚拟机网卡

**Comment by hcym** [comment]
我的能用

就是没看网址

**Comment by riumiyama** [comment]
@MeABc  感謝  抱歉我懶惰了

**Comment by phuslu** [comment]
啊，排序有误，请更新到 r911

**Comment by riumiyama** [comment]
wwwwwww

**Comment by melos2016** [comment]
@phuslu 还是标题中那个问题，192.168..31.243是手机IP，217是电脑IP
![image](https://cloud.githubusercontent.com/assets/19543043/17612517/569062ca-6085-11e6-9081-40f1d09a2bd3.png)

**Comment by jzp820927** [comment]
是不是 IP 的问题，PC能正常用麽

**Comment by melos2016** [comment]
IP正常，电脑能用。
刚才发现ESET有SSL/TLS协议过滤，关掉了
再观察观察

**Comment by melos2016** [comment]
![image](https://cloud.githubusercontent.com/assets/19543043/17615782/f30296ba-60a2-11e6-9dab-0abc540f24c8.png)
出现这个日志之后手机上不去网

**Comment by Lynchie** [comment]
同问手机连不上，需要导入证书吗？IOS怎么导入？

**Comment by phuslu** [comment]
安卓和 iOS 都需要导入。

浏览器输入 http://<PC机器IP>:8087/ 就能看到这样的界面
![image](https://cloud.githubusercontent.com/assets/195836/17616055/db085cbe-60a4-11e6-9b0c-ae884c6ce1ac.png)

**Comment by melos2016** [comment]
我手机的网络设置
![image](https://cloud.githubusercontent.com/assets/19543043/17616321/83adcb28-60a6-11e6-91bf-a7a36f6c88c3.png)
下面是出问题
![image](https://cloud.githubusercontent.com/assets/19543043/17616243/114a0d80-60a6-11e6-826d-749617bd7675.png)
![image](https://cloud.githubusercontent.com/assets/19543043/17616296/5ff34faa-60a6-11e6-8bd9-ca7bb0fd677a.png)

**Comment by jzp820927** [comment]
看你的图，意思是，打不开那个 index of / 页面？

**Comment by Lynchie** [comment]
我手机浏览器打不开http://<PC机器IP>:8087/

**Comment by jzp820927** [comment]
@ Lynchie
应该是：
http://<PC机器IP>:8087/ 
不是：
http://:8087/

**Comment by Lynchie** [comment]
http://192.168.2.101:8087/proxy.pac 应该没问题吧

**Comment by Lynchie** [comment]
电脑上打开没问题，就是safari打不开

**Comment by jzp820927** [comment]
不科学啊，手机的IP，是在 192.168.2 这个段嘛

**Comment by Lynchie** [comment]
手机是192.168.2.100

**Comment by jzp820927** [comment]
那是在一个网段上的，应该没问题啊，是不是浏览器的问题，试试 chrome？

**Comment by Lynchie** [comment]
我换了路由器可以了，不知道怎么回事，谢了！

**Comment by jzp820927** [comment]
那肯定是你路由器的问题了。

**Comment by Lynchie** [comment]
路由器不知道哪里需要设置，平常上网都没问题啊--

**Comment by jzp820927** [comment]
既然换了路由器，问题解决了，就不管他了吧

**Comment by riumiyama** [comment]
我這裡twitter&facebook Apps 打不開不行只有YouTube  Apps 能看

**Comment by phuslu** [comment]
Facebook 和 Twitter 会拒绝 goproxy 签发的证书，搞不定。

只能用浏览器打开 Facebook 或 Twitter 了。

**Comment by riumiyama** [comment]
原來如此
