### ISSUE TITLE
部署新版 goproxy 服务端碰到的问题

### ISSUE THREAD

**Issue by wenliyang** [phuslu/goproxy#1044]
下载 phuslu-goproxy-8a6a43f.zip 并部署时碰到一点问题

运行后，显示这样一行字：

_警告：建议先启动 GoProxy 客户端或者 VPN 然后再上传，如果您的 VPN 已经打开的话，
请按回车键继续。_

按回车继续并输入APPID（这儿我随意输入了一个名为test的APPID），则显示：

_GoProxy 服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用_

_请输入您的appid, 多个appid请用|号隔开
注意：appid 请勿包含 ios/android/mobile 等字样，否则可能被某些网站识别成移动设备
。
APPID:test
11:48 AM Application: test
11:48 AM Host: appengine.google.com
11:48 AM Rolling back the update._

然后就不动了，并没有弹出浏览器窗口

我在用 Shadowsocks，并想通过它来部署，不成功；以前因为某些原因更改过 goproxy 的本地端口，不成功；都是象上面这样停住不动

而只有当我用 goproxy 并且使用默认的本地 8087 端口时，才会弹出浏览器窗口继续部署

换句话说，只能开着 goproxy 并且使用默认的本地 8087 端口的情况下可以成功部署了，而我记得以前的版本不是这样的，通过 Shadowsocks 也是可以的

**Comment by yhyhnk** [comment]
以前部署服务端可以设置密码, 新版在哪里设置密码?

**Comment by phuslu** [comment]
是的，上传时候请打开 goproxy 并使用默认 8087 端口。

这块一直没变啊。

**Comment by wenliyang** [comment]
@phuslu 原来如此，看来我记错了，以前用 Shadowsocks 部署成功的时候同时开着 goproxy 并且是默认端口

**Comment by phuslu** [comment]
谢谢，已经加上 https://github.com/phuslu/goproxy/commit/b28c34fd6036330ca661f7b3dd3e62fd216a5446

**Comment by jzp820927** [comment]
@yhyhnk 密码可以修改下面文件：
server.gae/gae/gae.go
这个文件中的
Password = ""

**Comment by yhyhnk** [comment]
@jzp820927 谢谢! 我真是眼大无神,看了好几遍居然没找到.
