### ISSUE TITLE
非常遗憾的自己竟然没有下载保存goagent最后版本。想到下载时关了。遗憾遗憾！！！

### ISSUE THREAD

**Issue by tylokfree** [phuslu/goproxy#105]
谁有最后的小版本，给个链接，先谢。

**Comment by wzdnzd** [comment]
https://github.com/wzdnzd/goagent

**Comment by RobertYan** [comment]
https://github.com/phuslu/goagent/tree/v3.2.3

**Comment by CNMan** [comment]
@RobertYan 不是最后的版本:)

**Comment by xyuanmu** [comment]
GoAgent已经一个多月没有更新了，最后的版本就是那个支持gvs的版本。

**Comment by xyuanmu** [comment]
翻墙论坛有人给出了最后版本的链接，下载检查了下确实是 [goagent.zip](https://github.com/phuslu/goagent/tree/985cbd55e232833a859e7f2940b54f7dcb6cdb14)

**Comment by johnsonz** [comment]
项目为啥关了？release里面有的

**Comment by tylokfree** [comment]
多谢xyuanmu兄，自己一直用3.1.25修改版。现在又多一个备选。
