### ISSUE TITLE
ubuntu 16.04 lts 下的使用报错

### ISSUE THREAD

**Issue by ftwcpc** [phuslu/goproxy#1050]
运行goprox.sh start 后，chrome浏览器打开google时后台有如下错误

E0814 21:28:06.874416    6334 handler.go:72] 127.0.0.1:36180 Filter Request *stripssl.Filter error: open cache/.google.com.crt: permission denied

**Comment by jzp820927** [comment]
权限问题，查看 cache 目前是不是没有权限。可以试试 chmod 777 cache

**Comment by hcym** [comment]
没用过sh脚本

终端里直接./goproxy完事

**Comment by phuslu** [comment]
如 @jzp820927 所说，可能是权限问题，r927 做了修复。

**Comment by ftwcpc** [comment]
@phuslu  @jzp820927  @hcym 谢谢各位，确实忽略了用户权限问题，不再报错，但是chrome爆不是私密连接，方了

**Comment by ftwcpc** [comment]
@phuslu  确认是chrome权限导入问题，导致不是私密链接的报错，goagent老用户感谢多年来的免费使用

**Comment by jzp820927** [comment]
私密连接，是证书问题，你没导入证书

**Comment by ftwcpc** [comment]
@jzp820927  谢谢提醒，已经修正，目前无障碍
