### ISSUE TITLE
Release里面goproxy-vps_linux_amd64-r27.tar的源码问题？

### ISSUE THREAD

**Issue by jostyee** [phuslu/goproxy#1052]
repo里面的代码对不上，压缩包里面的go文件写了 `var version = "r9999"` ，后面没有做修改，但是日志输出变成了 `goproxy r26 ListenAndServe on [::]:` 这里对不上了。现在问题来了，本机要调试得修改哪个文件？

**Comment by phuslu** [comment]
对的上的，请看 https://github.com/phuslu/goproxy/blob/server.vps/Makefile 最后一行，这里修改了 version 变量。

**Comment by jostyee** [comment]
...看漏了，这个项目的代码组织不太idiomatic Go，不熟悉挺容易搞混的

**Comment by phuslu** [comment]
呃，这个项目我本来是作为闭源项目开发的（原因你懂的），由于要解决闭源项目的一些问题，所以不太 idiomatic Go :flushed:

**Comment by jostyee** [comment]
@phuslu 如果要对这个go文件提PR的话得怎么弄？或者单开一个repo？

**Comment by phuslu** [comment]
应该和普通的 PR 一样吧， fork 以后修改，然后 create pull request. 选对分支就可以了。

**Comment by jostyee** [comment]
faint, 居然是在 https://github.com/phuslu/goproxy/tree/server.vps branch上，三观大改了。。

**Comment by phuslu** [comment]
我上面的连接已经贴出来哦 😉

**Comment by jostyee** [comment]
@phuslu 我的意思是不能直接 `go.get` 这种传统方式操作了。
btw，有im可以讨论么？有段代码我理解有点问题，提issue不大合适。。

**Comment by phuslu** [comment]
https://gitter.im/phuslu/goproxy
