### ISSUE TITLE
SwitchyOmega 自动切换模式Youtube视频打不开

### ISSUE THREAD

**Issue by chili-Pepper** [phuslu/goproxy#1061]
换goagent模式没问题，请问怎么解决？以前好像在某个issue看到说是ip问题，找了一圈找不到那个贴了。怎么找到是哪个ip的问题呢

**Comment by jzp820927** [comment]
看看日志，有没什么报错

**Comment by cannanlly** [comment]
我感觉用SwitchyOmega反而不如之前的那个好了。SwitchyOmega这东西越做越渣了。。。。。。。。。。。

**Comment by blob2015** [comment]
@cannanlly 
foxyproxy 也没见提升什么，这么多年

**Comment by jzp820927** [comment]
赶脚还是 PAC 最方便，绿色，效率，又不用扩展。

**Comment by hcym** [comment]
pac和ssd一样

一旦用好，根本回不去

**Comment by chili-Pepper** [comment]
就是一直在重复"GAE FETCH GET"等到视频读取失败就停了

![image](https://cloud.githubusercontent.com/assets/13465694/17777392/03475994-6593-11e6-8c70-0d4f432c5467.png)

**Comment by chili-Pepper** [comment]
之前就每次看视频切一下模式，但是今天goagent模式下也出问题了。。。卡住retry
![image](https://cloud.githubusercontent.com/assets/13465694/17777698/16564d3c-6594-11e6-93d4-9729ffa5692d.png)

**Comment by Kisesy** [comment]
你这版本和配置太老了，现在的live.github.com都直连了，建议重新更新一下配置

**Comment by chili-Pepper** [comment]
@Kisesy 用服务端更新吗，早两天P大说更新898的时候一起更新的

**Comment by Kisesy** [comment]
哦，说错了，live.github.com 直连，需要开 SiteFilters，默认是不开的
服务端不用更，客户端随你吧，你这个也许只是IP被干扰了？

**Comment by chili-Pepper** [comment]
@Kisesy  把服务端更新了。听 @jzp820927  介绍试了下pac，youtube 果然奇效!!!因为有retry的话就会卡住所以把SiteFilters 也开了。谢谢~还有个蠢问题，以前Switchy的规则是不是现在就在SiteFilters里面写改？如果IP被干扰了怎么排除，我是追寻P大扔了一堆IP 进去的- -

**Comment by jzp820927** [comment]
SiteFilters 的作用和 Switchy 是一样的，2个选择一个用就可以了，不要同时用，不然就是重复了。
