### ISSUE TITLE
关于本机hosts和gae文件IP地址冲突的问题

### ISSUE THREAD

**Issue by hbjack** [phuslu/goproxy#1068]
例如我在本机hosts中用一个IP指定了google一系列的域名，而gae配置中google_cn的域名也包括在内，那么会直接使用hosts中的IP连接吗？又或者SiteToAlias选项中一些google的域名是通过google_hk中指定的IP来访问，而这些域名在本机hosts也指定了一个IP，那么会通过本机hosts的IP来连接还是google_hk的IP来连接？

**Comment by phuslu** [comment]
对于 google 系域名，goproxy 目前是忽略本机 host 的地址。

**Comment by hbjack** [comment]
感谢社长作答，了解了
