### ISSUE TITLE
heroku上部署了怎么连不上

### ISSUE THREAD

**Issue by zhangnick** [phuslu/goproxy#1070]

**Comment by zhangnick** [comment]
是我配置不对还是怎么，客户端没有任何反应，直接访问网页显示“binary.Read:EOF”，另一款代理gogo可以用但是不开源。

**Comment by zhangnick** [comment]
gae上部署的可以用，就是heroku上不行，改了php.json，httpproxy.json中php设为true，还有哪儿需要改的

**Comment by distance00** [comment]
端口改了吗？默认8088，看一下刚启动时的日志。单用php的话直接改Default。

**Comment by carotin** [comment]
部署好，访问网页显示：

Heroku | No such app

There is no app configured at that hostname.
Perhaps the app owner has renamed it, or you mistyped the URL.

**Comment by distance00** [comment]
最新版部署好以后显示的是“binary.Read:EOF”

**Comment by phuslu** [comment]
回滚了一下，再重新部署一次如何？

**Comment by Kisesy** [comment]
无论是 No such app 还是 binary.Read:EOF 都是可用的，试一下就知道了

**Comment by distance00** [comment]
@phuslu 请问怎么没有vendor目录了呀？那个不是为了支持fasthttp加的吗？是因为go1.7自带了吗？
我现在也得用php了，这里封锁忽然加剧，扫到了ip几分钟就玩完。

**Comment by phuslu** [comment]
不是，原本以为 binary.Read:EOF 是 fasthttp 相关的，所以回滚了一下。

待会再加回来。

GAE 封锁加剧的话，建议你扫描上千个 IP 放到 gae.user.json 里面，这样就会好很多。

**Comment by phuslu** [comment]
现在试下最新版的 php-go 呢，取消回滚了。

**Comment by distance00** [comment]
先放几百个试试，以前只放十来个。

**Comment by zhangnick** [comment]
又部署了一下，编译后比原来小，改了设置，虽然不知其所以然，但貌似可以了
