### ISSUE TITLE
HEROKU 上部署了最新版的PHP-GO 版后客户端只能上谷歌，其它网站都错误

### ISSUE THREAD

**Issue by ChicBrother** [phuslu/goproxy#1075]
首先感谢开发者的付出与社区各位朋友的支持。

我下的是R962 版，用的是一键部署到HEROKU 
然后下载的最新的客户端，修改PHP.JSON 的URL 与SSLVerify 为TRUE，启动服务但只能访问谷歌，其它类似TWITTER,FACEBOOK此类的网站都显示 

{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "go/devel +ebf8736 Wed Aug 24 06:47:42 2016 +0000 windows/amd64",
    "filter": "*gae.Filter",
    "error": "unexpected EOF"
}

日志显示 

I0824 22:55:53.199845    4816 stripssl.go:153] 127.0.0.1:53669 "STRIP CONNECT www.twitter.com:443 HTTP/1.0" - -
I0824 22:55:53.204850    4816 multidialer.go:242] MULTIDIALER DialTLS2("tcp", "goagenta.appspot.com:443") with good_addrs=11, bad_addrs=3
W0824 22:55:54.614837    4816 gae.go:474] 127.0.0.1:53669 "GAE FETCH GET https://www.twitter.com/ HTTP/1.1" error: *errors.errorString(unexpected EOF)
E0824 22:55:54.617843    4816 handler.go:94] 127.0.0.1:53669 Filter RoundTrip *gae.Filter error: unexpected EOF
W0824 22:55:56.357272    4816 gae.go:474] 127.0.0.1:53669 "GAE FETCH GET https://www.twitter.com/ HTTP/1.1" error: *errors.errorString(unexpected EOF)
E0824 22:55:56.361294    4816 handler.go:94] 127.0.0.1:53669 Filter RoundTrip *gae.Filter error: unexpected EOF
W0824 22:55:58.371140    4816 gae.go:474] 127.0.0.1:53669 "GAE FETCH GET https://www.twitter.com/ HTTP/1.1" error: *errors.errorString(unexpected EOF)
E0824 22:55:58.375153    4816 handler.go:94] 127.0.0.1:53669 Filter RoundTrip *gae.Filter error: unexpected EOF

请大家帮忙看看是什么出了问题，还要再配置哪个文件吗？记得之前是有个main.json的，好像后来的版本不用了。

我只修改了php.json文件

**Comment by phuslu** [comment]
你的日志显示还是使用 GAE 访问，而且 unexpected EOF 估计和你的 gae.user.json 配置有些问题。
看起来你的 php 配置没有生效。

**Comment by ChicBrother** [comment]
可是我php.json 里面 的URL 填了 https://xxxxx.herokuapp.com/index.go 了呀，是不是哪里还要再改呢？
还有我从github 下载的程序里面也只有个gae.json 没有gae.user.json呀。

**Comment by phuslu** [comment]
额，我猜你是第一次用 goproxy。 goproxy 的配置目前略繁。你可能需要看一下文档才大概明白。
https://github.com/phuslu/goproxy/blob/wiki/ConfigIntroduce.md

不愿折腾的话，其实可以考虑其他易用性比如 xx-net/xx-mini 等。:flushed:

**Comment by ChicBrother** [comment]
哈，是的，谢谢开发者，我看了下文档，启用了HTTPPROXY 里面的PHP 代理 方式就可以上了。
