### ISSUE TITLE
get over quota, retry...

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#1078]
社长说过，一个是urlfetch，另外一个是非urlfetch；有24小时限额，还有每分钟限额？
除此以外，还有其他限制不？
看yt视频，都没啥问题，但是下载一个40M不到的软件，反而出了问题。
反正小白，贴出来，给大家看看。

---

下载vivaldi浏览器，在vivaldi.com，出现下面的日志：
I0826 13:50:53.072639    1872 gaetransport.go:116] GAE: 【XXX】.appspot.com url
fetch "https://vivaldi.com/press/" get over quota, retry...
I0826 13:50:57.094869    1872 gaetransport.go:116] GAE: 【XXX】.appspot.com url
fetch "https://vivaldi.net/forum" get over quota, retry...
I0826 13:51:00.418060    1872 gaetransport.go:116] GAE: 【XXX】.appspot.com url
fetch "https://vivaldi.net/" get over quota, retry...

查https://appengine.google.com/ ，如下
![hs0019](https://cloud.githubusercontent.com/assets/12381704/17996192/c8b959b4-6b99-11e6-9ee9-38a40f6f4e1e.png)
![hs0020](https://cloud.githubusercontent.com/assets/12381704/17996190/c8ac06e2-6b99-11e6-9668-c5530eade907.png)
![hs0021](https://cloud.githubusercontent.com/assets/12381704/17996191/c8ac7c1c-6b99-11e6-81da-44a1d04e84f2.png)
![hs0022](https://cloud.githubusercontent.com/assets/12381704/17996194/c965eddc-6b99-11e6-9d53-a0e4e4f92005.png)
![hs0023](https://cloud.githubusercontent.com/assets/12381704/17996193/c8d226ce-6b99-11e6-8ae9-b5e2c6534d6b.png)

**Comment by MeABc** [comment]
这个月我回答这个问题三次了。。。。。。

都不看文档的吗？？

![1](https://cloud.githubusercontent.com/assets/18194126/17997223/d6a3207c-6b9f-11e6-9941-567da1492c5a.png)

![2](https://cloud.githubusercontent.com/assets/18194126/17997227/da415e4c-6b9f-11e6-947a-6636dd9edeab.png)

![3](https://cloud.githubusercontent.com/assets/18194126/17997230/ddcd0e1c-6b9f-11e6-8954-10af31bf0b1e.png)

> 看yt视频，都没啥问题

如果网站有重试的你就不会注意，没有重试的网站你就会发现是一样的。另一个，或许你看视频时并没有碰到 `get over quota` 。

下载时有断点续传的你怕什么。你是没碰到过，下载没有断点续传功能，而这时又刚好碰到 `get over quota` 情况，那才叫痛苦。

**Comment by blob2015** [comment]
@MeABc 
感谢老兄，对小白也如此包容 :grinning: 
我是想问问，这个怎么在 https://appengine.google.com/ 查看，是否over quota。然后，是否加入到autorange就可以暂时解决了？【就本案例来说，只有40M】
既然老兄出现了，再问一个小白问题。用pac，只要键入 http://127.0.0.1:8087/proxy.pac 就可以了？gfwlist会自动被转换？然后gfwlist差不多被自动更新，然后就是说，这个pac，其实也是自动升级了？
谢谢 :beers

**Comment by MeABc** [comment]
而我对这个问题的建议是，代码里不要再重试，第一次 `get over quota` 就把这个 appid 放入一个暂时的黑名单，比如 5 分钟。

**Comment by MeABc** [comment]
> 是否加入到autorange就可以暂时解决了

一样的。不过你可以试一下。你没有发现 autorange 里的网站一样会出现 `get over quota` 吗？

> gfwlist会自动被转换？然后gfwlist差不多被自动更新，然后就是说，这个pac，其实也是自动升级了？

会自动转换。会自动更新。文档里也有啊！！

**Comment by MeABc** [comment]
> 这个怎么在 https://appengine.google.com/ 查看，是否over quota

看不出来的。即你顶楼的图，你能看出 `over quota` 吗？ 又，即使在图里看出来又能怎么样呢，还不是解决不了问题。

**Comment by MeABc** [comment]
> 是否加入到autorange就可以暂时解决了？【就本案例来说，只有40M】

最快的解决方法，重载GP，重新下载。

**Comment by Kisesy** [comment]
可以看 https://github.com/phuslu/goproxy/issues/757 社长的经典问答
在以前的时候，Py 端在某些时候比 Go 要快哦，因为Py端遇到错误会在服务器自动重试，而Go需要在本地重试

**Comment by blob2015** [comment]
@MeABc 
感谢耐心答复。
重新下载了一次，好像就没有出现了，加入了autorange。可能因为文件还是比较小 :grinning: 
@Kisesy 
谢谢
eof也遇到过几次 :grinning:

**Comment by MeABc** [comment]
@blob2015 我上面说的 `重载GP` 意思是换一个 appid ，用来下载，和 `autorange` `文件还是比较小` 应该没有多大关系。。。

@Kisesy 之前我也看到过社长的这个回复。只不过回复同一个问题多次，我可能有点语无伦次了。

**Comment by distance00** [comment]
@phuslu 一个本地控制的思路，不知道是否容易实现。
1、右键加入一个“限速下载模式”，勾选以后重新加载并把goproxy限速为370k/s，如果你不看高清视频，这个速度足够用了，可以只用这个模式，每次右键”重新载入“都会换下一个id，如果你想下载一个将近1g的文件，就”重新载入“一下。
2、在本地计算quota，每分钟到了21m就转到下一个id。
3、计算quota可能比较复杂，并且和官方不一致，有个简单的办法，只要累计流量到了21m就换下一个id，不管是否over quota（分钟），这样把每天的over quota问题也避免了，一般用户都加入了远超自己能实际使用的id数量，循环切换每一个id都不会over quota（每天）。
感觉本地控制quota的好处是，不会在已经over quota的时候发送数据，等服务端返还了错误信息再处理，有的数据可能不会自动再次发送，把被动变成主动，更不容易出错，不知道是否合理？

**Comment by blob2015** [comment]
@MeABc 
嘿嘿，对于小白来说，重载啊，就是关了再开 :grinning: 
另外，问一下，autorange已经重构完全完成了？最近都没有看见消息，问社长也不好意思 :grinning: 
@distance00 
老兄把俺想说的，都说了，因为觉得实在比较小白，不敢胡言乱语 :grinning:

**Comment by wangyi2005** [comment]
迅雷极速版 设置 http代理 下载好像没有问题

**Comment by hcym** [comment]
胡言乱语

**Comment by wangyi2005** [comment]
![image](https://cloud.githubusercontent.com/assets/18438595/18007614/6fcd40c0-6bd7-11e6-804f-781690b85209.png)

**Comment by wangyi2005** [comment]
![image](https://cloud.githubusercontent.com/assets/18438595/18007925/97f6068a-6bd8-11e6-851e-9a1684eec393.png)
![image](https://cloud.githubusercontent.com/assets/18438595/18007953/bf66ed74-6bd8-11e6-823c-ffe91b3d863b.png)

**Comment by MeABc** [comment]
> autorange已经重构完全完成了？

按社长的意思是还没完成。但就我的平时正常使用来说，autorange 没有什么大问题啊，下载正常，视频正常。

@distance00 按照你的说法，是不是 APPID 循环使用（不管哪种实现）？如果是这样的话，那 autorange 就"形同虚设"，或者说，都可以不用 autorange 了。

 `get over quota` 现在是一个体验问题----有时“我们”宁愿等服务器三分钟，也忍受不了客户端一分钟。

**Comment by wangyi2005** [comment]
![image](https://cloud.githubusercontent.com/assets/18438595/18008086/57f257fe-6bd9-11e6-9959-a0dd051b81c1.png)

**Comment by MeABc** [comment]
我现在终于明白 Google 为什么会出验证码了。

**Comment by distance00** [comment]
@MeABc  现在每分钟over quota了，还是要换id的，换不及时就卡住，上次的修复一下好了很多，但有时还是会卡住，因为目前网络状况不好加了几百个ip红黄字比较多，就没做专门详细的测试。本地控制就不用等服务器返回出错信息再换id，而是自己主动换。

**Comment by blob2015** [comment]
@wangyi2005 @MeABc 
迅雷这种杀器都出现了……
唉
@distance00 
很简单，老兄只要加一个seo插件，会自动查询google排名的那种，保证搞个几次，就来一次验证码

**Comment by blob2015** [comment]
@MeABc 
下载地址 https://dl.google.com/dl/earth/client/GE7/release_7_1_5/googleearth-win-pro-7.1.5.1557.exe 
俺这边都是404，老兄也一样吗？

**Comment by jzp820927** [comment]
看来 dl 的中国服务器也不是所有资源都有。

**Comment by MeABc** [comment]
@blob2015 

和你一样。都是404。

你这两个地址是不是过期了（或不存在）。VPN 都不能下载或打开？！

**Comment by blob2015** [comment]
@MeABc 
我点google earth官网，然后点击下载……

---------------

@jzp820927 
感觉这个应该没有存国内服务器的吧？

**Comment by Kisesy** [comment]
PHP 可以打开下载地址，不过下面那个打不开

**Comment by blob2015** [comment]
@Kisesy 
感谢，下载下载客户端，然后也能下载，开全局的话
另外，个人小发现，网页版的google earth与客户端版的，两者好像不一样……客户端版的更加详细，数据更加全，更加新

**Comment by blob2015** [comment]
另外，搜索结果，登陆帐号，开启全面之类的，好像也更加多些
纯个人经验，各种配置参数没有细究，仅供参考

**Comment by jzp820927** [comment]
@MeABc 走 GAE 可以下载，我试了，地址没有问题。
@blob2015 dl.google.com，如果直接解析的话，就解析会国内 203 的IP段上的，就算你用 google dns，opendns，都是解析会国内的，除非你自己定义 hosts，我是用直接解析测试的，是 404，说明国内服务器不存在这资源；走 GAE 的话没问题，说明，国外服务器有这个资源。

**Comment by Kisesy** [comment]
以现在的情况来看, 一个 appid 出现 over quota, 那么会伴随着下一次还是这个id有问题, 只是地址不一样
说明这个 appid 出现 over quota 后，在 sleep 的时间内，又有请求在访问，导致再次出现 over quota
那么简单的解决方法是不是应该在一个appid出现超额后，在一段时间内不让它出现在appid列表中...

**Comment by MeABc** [comment]
>那么简单的解决方法是不是应该在一个appid出现超额后，在一段时间内不让它出现在appid列表中...

这个赞同。社长的 404 状态码优化后访问顺畅了很多。

**Comment by blob2015** [comment]
@Kisesy 
老兄换回了头像？
@MeABc 
老兄也换头像了

**Comment by MeABc** [comment]
![55](https://cloud.githubusercontent.com/assets/18194126/18316052/c2a12320-754b-11e6-8e48-48dc6a24f52d.png)

一说404，它就来这个。。。

 TryCloseConnectionByRemoteAddr 好像不管用。会刷屏。

@blob2015 换了一个和 MeABc 这名字相匹配的名字----我是小白。呵呵。

**Comment by phuslu** [comment]
啊，看起来 TryCloseConnectionByRemoteAddr 这个函数没有起效，我看下。

**Comment by phuslu** [comment]
@MeABc 请确认下，你是打开了 ForceHTTP2 是吗？

**Comment by MeABc** [comment]
> 请确认下，你是打开了 ForceHTTP2 是吗？

是的。

**Comment by phuslu** [comment]
嗯，我尽快修复它。再次感谢。

**Comment by MeABc** [comment]
![dd](https://cloud.githubusercontent.com/assets/18194126/18317513/04c2d4b0-7551-11e6-99b3-3463692ee29d.png)

有时候就好。这是怎么回事？

**Comment by phuslu** [comment]
尝试在 r1012 上修复了一下。

**Comment by MeABc** [comment]
社长辛苦！社长你这效率，必须给个赞！

**Comment by blob2015** [comment]
@MeABc 
怎么可以跟俺抢小白的称号 :grinning: 
你这样都小白，我这不得惨白 :grinning:

**Comment by MeABc** [comment]
![dd](https://cloud.githubusercontent.com/assets/18194126/18320027/ca736cac-755a-11e6-914c-bf5090682253.png)

社长，很奇怪 autorange 加载 autoproxy 的配置文件？

**Comment by MeABc** [comment]
但看上面，autorange 和 autoproxy 都是能正常工作的，但有时就会这样。

**Comment by phuslu** [comment]
@MeABc r1015 https://github.com/phuslu/goproxy/commit/ea8c5df36da2883593213f0203959d076e0f0ae5 尝试修复了一下

**Comment by MeABc** [comment]
r1015 没有问题了。

**Comment by MeABc** [comment]
![dd](https://cloud.githubusercontent.com/assets/18194126/18321953/dafb8674-7562-11e6-9dfb-b3625b18e25a.png)

TryCloseConnectionByRemoteAddr  正常了。

**Comment by LGA1150** [comment]
@blob2015 
这个地址屏蔽了中国IP

**Comment by phuslu** [comment]
2016-09-08 版本的 gae 服务端已经尝试在服务端重试 CLOSED 错误了。 https://github.com/phuslu/goproxy/commit/3ae2b4660d32a7438a14543cef13adc64326cdca

**Comment by blob2015** [comment]
@phuslu 
多谢社长 :beers:
