### ISSUE TITLE
HideGuard VPN 俄国免费

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1081]
http://hideguard.ru/

http://hideguard.ru/download/

有美英加3个服务器

**Comment by jzp820927** [comment]
试用了下，挺不错，不过好像只有3个服务器，没看到 de 的，太难连上了，连了十几次，才连上，不过连上了，就挺稳定的，速度也很好。

**Comment by sishentibu** [comment]
不错，备用。
昨天试了Windscribe一直连不上。太纠结了。

**Comment by Kisesy** [comment]
试了几次都连不上

**Comment by jzp820927** [comment]
昨天还能偶尔连上 1，2次，今天一直连不上了。

**Comment by yuan18** [comment]
求老司机代，如何使用，老司机给个教程先

**Comment by jzp820927** [comment]
打开，点按钮就行了，不过劝你别折腾了，基本上连不上。

**Comment by jasonliul** [comment]
这种客户端很适合用帽子加载~~
今年中国ip袜子表现还不错

**Comment by jzp820927** [comment]
VPN 还能前置帽子？真是试过，都不在一个层上。

**Comment by jasonliul** [comment]
@jzp820927 
pptp,L2TP 的有独立客户端应该都可以
IPSec不清楚.

Pegasus VPN, HideGuard VPN应该都可以

**Comment by wz7465** [comment]
@jasonliul 
那有没有试过vpngate前置的？
我记得vpngate有前置的设置，支持http代理和socks代理前置，最早的时候试过有效，后来版本就基本失效了，空有一个架子

**Comment by jzp820927** [comment]
基于 ssl 的VPN，应该走代理没问题，因为都在一个层，想 openvpn，vpngate 这些。

**Comment by jasonliul** [comment]
@wz7465 
自身的支持有问题很正常.
还是可以选用帽架程序, 


Proxifier
https://www.proxifier.com/download.htm

ProxyCap
http://www.proxycap.com/download.html

SocksCap64
https://sourceforge.net/projects/sockscap64/files/

**Comment by wz7465** [comment]
我现在就用Proxifier做全局代理，跑跑ssh没什么问题，但感觉没有vpn完美，启动了Proxifier后，浏览器不能使用免代理模式

**Comment by jzp820927** [comment]
VPN 感觉也不方便，不好控制流量。

**Comment by wz7465** [comment]
vpngate反正是免费的，不用控制啊。其实vpn我用的很少，毕竟全局代理不灵活。但有时还是必须的，以前部署GoAgent服务端时，死活上传不上，最后还是用vpn搞定的

**Comment by jasonliul** [comment]
@jzp820927 @wz7465 
VPN主要是提供手机使用

**Comment by wz7465** [comment]
手机vpn中国人用的多么？虽然play商店里琳琅满目的都是vpn，但我感觉都是外国人在用啊，以前用过一段时间openvpn，被gfw干掉后，就把app卸载了，还有play商店里的vpn根本搞不清是免费的还是收费的，懒得试了。

**Comment by jzp820927** [comment]
VPN 算是最后的救命稻草吧，也是现在封锁最厉害的。

**Comment by blob2015** [comment]
@jzp820927 
vpn一般比较容易用，用户群也比较大，某些行业，普遍使用，可能因此而惹来“关注”

**Comment by jzp820927** [comment]
总之现在 VPN 太难连上了，不过连上了，都还可以稳定使用。我就那天连上一次，就再也没连上过了。
