### ISSUE TITLE
新版的goproxy-vps 不支持http2连接？

### ISSUE THREAD

**Issue by dapao9999** [phuslu/goproxy#1083]
chrome 用 --ignore-certificate-errors ，发现连接都是http 1.1 facebook能打开，youtube打不开
![qq 20160830154432](https://cloud.githubusercontent.com/assets/6910161/18080585/c9287006-6ec8-11e6-9c21-2fb91720b5b3.png)

**Comment by phuslu** [comment]
不是吧，估计测试有误？

我的这是我访问此页的截图。

![image](https://cloud.githubusercontent.com/assets/195836/18080905/f8844392-6ec9-11e6-87fe-5ad02d0dfe80.png)

**Comment by dapao9999** [comment]
@phuslu 我被运营商QOS了？把端口换成25就好了
![qq 20160830160131](https://cloud.githubusercontent.com/assets/6910161/18081156/3388eb04-6ecb-11e6-94bc-8dc38afe81ea.png)

**Comment by phuslu** [comment]
goproxy-vps 已经支持多端口绑定了。

比如 ./goproxy-vps -addr :443,:8443,:25 即可。

用逗号分割即可，你这样的情况建议使用。

**Comment by dapao9999** [comment]
@phuslu 好，我试试

**Comment by dapao9999** [comment]
运行后在目录下生成的pwauth有啥用？设置密码的吗？

**Comment by phuslu** [comment]
pwauth 不是运行生成的，是近期 goproxy-vps 引入的。
具体作用我在 https://gitter.im/phuslu/goproxy 比较详细的解释了一下。

**Comment by dapao9999** [comment]
怎么设置密码？pwauth.txt怎么写啊？

**Comment by phuslu** [comment]
goproxy-vps 的 pwauth 使用方法

1. 通过 goproxy-vps 的 `-pwauth` 命令行参数打开。
2. 通过 goproxy-vps-auth.service 的 systemd 启动。

用户名配置支持两种

1. 默认使用 linux 的 pam 认证，就是说使用 linux 系统的用户名和密码。用 useradd/passwd/userdel 这些命令来添加或管理用户名和密码。
2. 也可以是用 pwauth.txt 来添加用户名和密码，格式如下
```
# This is pwauth.txt example file, format is <username> <password>
phuslu 123456
foobar 123456
```

**Comment by phuslu** [comment]
goproxy-vps 的 pwauth 使用请谨慎，特征比较明显。

GFW 会用爬虫嗅探 https proxy 的 407 返回码，当年“地下铁路”就因此被封了不少服务器。

**Comment by dapao9999** [comment]
自己用的话，可以不设置密码吗？

**Comment by phuslu** [comment]
自用的话，可以考虑不设置密码。

我考虑给 goproxy-vps 加个 IP 白名单的功能，方便“自用”需求。

**Comment by dapao9999** [comment]
谢谢社长，另外 ios 使用的话是不是要手动导入 goproxy-vps.crt 这个证书？

**Comment by phuslu** [comment]
不是。手机客户端使用 http2/https proxy 需要客户端支持。

据我所知 surge 是支持的，其他类似 shadowrocket, a.big.t 等是否支持，我不太清楚。

**Comment by dapao9999** [comment]
我用的 surge 发现不安装 goproxy-vps.crt 这个证书的话，一直报错，安装后正常。

**Comment by phuslu** [comment]
那是说明你的 goproxy-vps.crt/goproxy-vps.key 是自签证书。

我推荐使用 letsencrypt 签署证书。比如你先给 vps 绑个域名，然后安装 nginx 在 80 端口监听。
使用如下命令就可以签署 ECC 证书了。

```
openssl ecparam -genkey -name prime256v1 > ecc.key
openssl req -new -sha256 -key ecc.key -subj "/CN=vps.phus.lu" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:vps.phus.lu")) -outform der -out ecc.csr
letsencrypt certonly --text -n -vv --agree-tos --email phuslu@hotmail.com --csr ecc.csr --webroot --webroot-map '{"vps.phus.lu": "/var/www/html"}'
```

其中第三步的 letsencrypt 可以使用 yum/apt 安装得到的官方工具。

**Comment by phuslu** [comment]
ECC 证书的好处请见 imququ.com/post/ecc-certificate.html

**Comment by dapao9999** [comment]
我用的这个是小鸡，没绑域名，随便玩玩

**Comment by liyangyijie** [comment]
@dapao9999 绑定个ml、tk之类的域名呗

**Comment by dapao9999** [comment]
@liyangyijie 免费的不靠谱，动不动就被没收了呢

**Comment by liyangyijie** [comment]
@dapao9999 私用还是很稳定的，→_→某ml已经续约了几次了，解析放到dnspod，acme.sh可以用api速签证书

**Comment by dapao9999** [comment]
@liyangyijie 12个月到期了，续约不收钱？

**Comment by liyangyijie** [comment]
@dapao9999  别忘了续约就行，freenom那家免费续约点12个月选项就行了
