### ISSUE TITLE
求助：goproxy-vps 客户端能上google，不能上其它网站。

### ISSUE THREAD

**Issue by mixool** [phuslu/goproxy#1087]
最近折腾，用的最新的govps版本，访问google可以，访问其它网站显示如下：
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r984 (go/devel +46ddbd2 Wed Aug 31 00:58:36 2016 +0000 windows/amd64)",
    "filter": "*vps.Filter",
    "error": "http2: unsupported scheme"
}
是哪里没弄对么，感谢解答。

**Comment by mixool** [comment]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r984 (go/devel +46ddbd2 Wed Aug 31 00:58:36 2016 +0000 windows/amd64)",
    "filter": "*vps.Filter",
    "error": "http2: unexpected ALPN protocol ""; want "h2""
}
访问www.baidu.com 自动跳到https://www,baidu.com 显示如上。

**Comment by phuslu** [comment]
goproxy-vps 服务端大体可用了。
客户端正在开发，请关注 https://github.com/phuslu/net/commits/master/http2

**Comment by dapao9999** [comment]
可以直接用stunnel，配置这么写，浏览器设置代理http://127.0.0.1:1080
```
[https]
client = yes
accept  = 1080
connect = ip:port
```

速度爆炸，很稳定，我没用守护，运行了两天，进程也没掉，ubuntu 14.04 好像用不了社长的 systemd

**Comment by mixool** [comment]
@dapao9999 使用stunnel按照你的方法成功使用上了，感谢。
接下来看看怎么搞证书，直接stwitch omage https用。

**Comment by mixool** [comment]
成功部署在vps和arukas的免费docker容器上。
