### ISSUE TITLE
goagent 支持gvs

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#1089]
https://github.com/phuslu/goagent/archive/985cbd55e232833a859e7f2940b54f7dcb6cdb14.zip
注意：https://github.com/phuslu/goagent/releases 里的v3.2.3不是最新版

https://github.com/CNMan/goagent/commit/b9814aa6182fcbff3e377a300940ffb576f5f22b
proxy.py 修正了python 2.7.x(x>=10)版本号显示错误的问题
proxylib.py 修改了同时支持gws和gvs的cipher

不懂编程，乱改的，测试gvs可以用

proxylib.py 也可用楼下 Kisesy 修改的版本

**Comment by blob2015** [comment]
收藏一个
谢谢

**Comment by distance00** [comment]
似乎不行啊，全成了bad ip

**Comment by CNMan** [comment]
改完不支持gws了，晕

**Comment by distance00** [comment]
不知道把XX-Mini中近似位置的代码移植过来怎么样？

**Comment by Kisesy** [comment]
改成 `ALL:!RC4-SHA:!ECDHE-RSA-RC4-SHA:!ECDHE-RSA-AES128-GCM-SHA256:!AES128-GCM-SHA256:!ECDHE-RSA-AES128-SHA:!AES128-SHA` 就行了
RC4 属于废弃加密了

**Comment by CNMan** [comment]
@kisesy https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/openssl_wrap.py#L243
xx-net和xx-mini里是cipher_suites可以这么改，goagent貌似是单独的cipher，改完ssl连接不了

**Comment by CNMan** [comment]
@kisesy https://github.com/XX-net/XX-Net/blob/master/code/default/gae_proxy/local/openssl_wrap.py#L243
xx-net和xx-mini里是cipher_suites可以这么改，goagent貌似是单独的cipher，改完ssl连接不了

**Comment by Kisesy** [comment]
[proxylib.tar.gz](https://github.com/phuslu/goproxy/files/449370/proxylib.tar.gz)

应该没问题，顺便改了一下，支持了 OpenSSL

**Comment by CNMan** [comment]
WARNING - [Sep 01 18:16:46] create_ssl_connection to 'xxxxx.appspot.com' with [('x.x.x.x', 443), ('x.x.x.x', 443)] return ["[('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]"], try again.

**Comment by Kisesy** [comment]
不应该啊，我是直接拿你的代码改的，试试重新导入证书
还有如果升级Py版本也是会有各种毛病

**Comment by hcym** [comment]
收藏 
谢谢

**Comment by panpeach** [comment]
Kisesy 的附件，分别测试gws，gvs完全能用

**Comment by distance00** [comment]
@CNMan @Kisesy 非常感谢两位，可用了，专门扫了gvs的ip测试。一直想找一个这样的版本。

**Comment by CNMan** [comment]
@Kisesy 可能是我直接用python 2.7.12运行的缘故，sslv3貌似被抛弃了

**Comment by Kisesy** [comment]
嗯，也许是，现在的状况是，升级什么都会出现问题 :trollface: ，升级openssl也是有问题的。。
而且现在的DNS也有问题，老是出现黄字。。。

**Comment by blob2015** [comment]
@Kisesy 
谢谢

**Comment by Kisesy** [comment]
我的那个附件有点问题，在 win64上是不会启用 openssl 的，因为原来的代码只是判断了 win32
可以自己改一下，大概在2005行
把 `if sys.platform != 'win32':`  改成 `if not sys.platform.startswith('win'):`
或者重新下载一下楼上的附件

**Comment by distance00** [comment]
原来的服务端部署无效了，不知道该如何修改一下。
输入信箱密码以后就这样：
Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---
请按任意键继续. . .

**Comment by jzp820927** [comment]
可以用 XX-NET 部署，服务端通用的

**Comment by sishentibu** [comment]
@distance00 用xx-net重新部署下。(我也只会这么搞）

**Comment by distance00** [comment]
@jzp820927 @sishentibu
是跟XX-NET通用，不过我发现XX-NET的加个密，goagent就用不了了。

**Comment by sishentibu** [comment]
@distance00 xx-net的那个加密，goproxy是可以用的。按说goagent也是能用的。是不是没设置好？

**Comment by hcym** [comment]
又能优雅的用goagent了

哈哈，再次感谢

**Comment by distance00** [comment]
@sishentibu 试了多次，goagent打不开页面。
加密码的方法，有兴趣的可以试下。
XX-Net-3.1.19\code\default\gae_proxy\server\gae\gae.py 第五行。改完把gae.py改为只读，不改只要一部署就复原了，似乎每次部署前都自动下载？另外那个uploader没用。部署用的页面。
客户端改XX-Net-3.1.19\data\gae_proxy\config.ini，或者manual.ini

**Comment by jzp820927** [comment]
其实没必要加密，只要你不主动泄漏 appid，是不会被盗用的。

**Comment by cclu** [comment]
@distance00

直接把goproxy的服务端版过来即可
~/gae/下使用v323的server side
~/google_appengine/完全使用goproxy的
然后把.appcfg_oauth2_tokens复制过来
其他python, uploader完全删除

btw，我使用cygwin下python和openssl的。

**Comment by distance00** [comment]
@jzp820927 只是看到有这样的功能就折腾一下。

**Comment by jzp820927** [comment]
XX-NET 的服务端加密，现在好像改了，要通过命名传递密码参数才行

**Comment by distance00** [comment]
@cclu 开始也这样试了一次，没有弹出认证页面，就说没有权限。我再试试看。

**Comment by sishentibu** [comment]
@distance00 最新的3.1.19我也没试过。我以前用的3.1.14是改的uploader.py的。

**Comment by distance00** [comment]
@cclu 下了一个新的goproxy服务端，试验成了，可能以前的里面有什么残余。
https://codeload.github.com/phuslu/goproxy/zip/server.gae
把里面的gae文件夹删了，把goagent的拷贝过来，别的都不用动。

**Comment by distance00** [comment]
@sishentibu 密码的问题是我搞错了，很久没有goagent了，保存了多个拷贝和设置文件，一时弄错了。两个通用，没有问题。

**Comment by sishentibu** [comment]
@distance00 我也是好久没用gae了。社长也是推荐用的gop的

**Comment by distance00** [comment]
@sishentibu gae是千锤百炼出来的，gop现在还没有正式版，完全取代还有待时日。肯定是会取代gae的，这一点毫无疑问。

**Comment by CNMan** [comment]
gws

```
    Accepted  TLSv1  256 bits  ECDHE-RSA-AES256-SHA
    Accepted  TLSv1  256 bits  AES256-SHA
    Accepted  TLSv1  128 bits  ECDHE-RSA-AES128-SHA
    Accepted  TLSv1  128 bits  AES128-SHA
    Accepted  TLSv1  112 bits  DES-CBC3-SHA
```

gvs

```
    Accepted  SSLv3  128 bits  AES128-SHA
    Accepted  SSLv3  128 bits  RC4-SHA
    Accepted  SSLv3  112 bits  DES-CBC3-SHA
    Accepted  TLSv1  128 bits  ECDHE-RSA-AES128-SHA
    Accepted  TLSv1  128 bits  AES128-SHA
    Accepted  TLSv1  128 bits  ECDHE-RSA-RC4-SHA
    Accepted  TLSv1  128 bits  RC4-SHA
    Accepted  TLSv1  112 bits  DES-CBC3-SHA
```

```
Google video ip can act as Google FrontEnd if cipher suits not include 
RC4-SHA
ECDHE-RSA-RC4-SHA
ECDHE-RSA-AES128-GCM-SHA256
AES128-GCM-SHA256
```

测试把1171和1173行的ECDHE-RSA-AES128-SHA换成DES-CBC3-SHA可以同时支持gvs和gws。

**Comment by sishentibu** [comment]
@distance00 在有些网站上，gop是还有些问题。不过日常使用也够了。

**Comment by distance00** [comment]
@CNMan 我把以前用的版本就改了两个DES-CBC3-SHA，确实可以了。（神奇）
你说https://github.com/phuslu/goagent/releases不是最新版，不知道到哪里下最新版？

**Comment by CNMan** [comment]
主楼985cbd55e232833a859e7f2940b54f7dcb6cdb14.zip就是[20150607](https://github.com/phuslu/goagent/tree/985cbd55e232833a859e7f2940b54f7dcb6cdb14)的最新版
release 那里的是[20141122](https://github.com/phuslu/goagent/commit/846432747416bc469c6e394a5efb1822d09de51c)的版本

**Comment by Kisesy** [comment]
DES-CBC3-SHA确实可以，不知道能不能加到goproxy里

**Comment by Kisesy** [comment]
DES-CBC3-SHA 好像在GO里是 TLS_RSA_WITH_3DES_EDE_CBC_SHA？

**Comment by phuslu** [comment]
在 gae.json 里面试了一下，貌似是的。

**Comment by CNMan** [comment]
```
# git clone https://github.com/rbsec/sslscan.git
# cd sslscan
# make static
# ./sslscan gwsip/gvsip
```

gws

```
Preferred TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  AES128-GCM-SHA256
Accepted  TLSv1.2  128 bits  AES128-SHA
Accepted  TLSv1.2  128 bits  AES128-SHA256
Accepted  TLSv1.2  112 bits  DES-CBC3-SHA
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-GCM-SHA384   Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  ECDHE-RSA-AES256-SHA384       Curve P-256 DHE 256
Accepted  TLSv1.2  256 bits  AES256-GCM-SHA384
Accepted  TLSv1.2  256 bits  AES256-SHA
Accepted  TLSv1.2  256 bits  AES256-SHA256
Preferred TLSv1.1  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  128 bits  AES128-SHA
Accepted  TLSv1.1  112 bits  DES-CBC3-SHA
Accepted  TLSv1.1  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  256 bits  AES256-SHA
Preferred TLSv1.0  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  128 bits  AES128-SHA
Accepted  TLSv1.0  112 bits  DES-CBC3-SHA
Accepted  TLSv1.0  256 bits  ECDHE-RSA-AES256-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  256 bits  AES256-SHA
```

gvs

```
Preferred TLSv1.2  128 bits  ECDHE-RSA-AES128-GCM-SHA256   Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  AES128-GCM-SHA256
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  AES128-SHA
Accepted  TLSv1.2  128 bits  ECDHE-RSA-AES128-SHA256       Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  AES128-SHA256
Accepted  TLSv1.2  112 bits  DES-CBC3-SHA
Accepted  TLSv1.2  128 bits  ECDHE-RSA-RC4-SHA             Curve P-256 DHE 256
Accepted  TLSv1.2  128 bits  RC4-SHA
Preferred TLSv1.1  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.1  128 bits  AES128-SHA
Accepted  TLSv1.1  112 bits  DES-CBC3-SHA
Accepted  TLSv1.1  128 bits  ECDHE-RSA-RC4-SHA             Curve P-256 DHE 256
Accepted  TLSv1.1  128 bits  RC4-SHA
Preferred TLSv1.0  128 bits  ECDHE-RSA-AES128-SHA          Curve P-256 DHE 256
Accepted  TLSv1.0  128 bits  AES128-SHA
Accepted  TLSv1.0  112 bits  DES-CBC3-SHA
Accepted  TLSv1.0  128 bits  ECDHE-RSA-RC4-SHA             Curve P-256 DHE 256
Accepted  TLSv1.0  128 bits  RC4-SHA
Preferred SSLv3    128 bits  AES128-SHA
Accepted  SSLv3    112 bits  DES-CBC3-SHA
Accepted  SSLv3    128 bits  RC4-SHA
```

除了DES-CBC3-SHA，共有的还有AES128-SHA256、ECDHE-RSA-AES128-SHA256，测试了一下不行，goagent不支持tlsv1.2？

**Comment by Kisesy** [comment]
@CNMan 试了一下，ECDHE-RSA-AES128-SHA256 之类的是可以的
首先 py 的版本要高，然后在配置文件里把 sslversion 调成 sslversion = TLSv1_2 才行。。

**Comment by CNMan** [comment]
@Kisesy 

```
ERROR - [Sep 05 18:25:37] __main__.GAEProxyHandler.first_run() return AttributeError("'module' object has no attribute 'TLSv1_2_METHOD'",)
Traceback (most recent call last):
  File "E:\Program Files\goagent\local\proxylib.py", line 2257, in setup
    self.first_run()
  File "proxy.py", line 772, in first_run
    net2 = AdvancedNet2(window=common.GAE_WINDOW, ssl_version=common.GAE_SSLVERSION, dns_servers=common.DNS_SERVERS, dns_blacklist=common.DNS_BLACKLIST)
  File "E:\Program Files\goagent\local\proxylib.py", line 1542, in __init__
    self.openssl_context = OpenSSL.SSL.Context(getattr(OpenSSL.SSL, '%s_METHOD' % ssl_version))
AttributeError: 'module' object has no attribute 'TLSv1_2_METHOD'
```
为何我改完不行呢？

**Comment by CNMan** [comment]
@Kisesy 
按照你的思路，参考 https://docs.python.org/2/library/ssl.html 把`proxy.ini`里`sslversion = TLSv1`改成`sslversion = SSLv23`后，那两个TLSv1.2的cipher也可以用了

**Comment by Kisesy** [comment]
@CNMan 出错是因为 OpenSSL 的版本太低了

**Comment by CNMan** [comment]
@Kisesy 
```bat
C:\Windows\system32>pip list
cffi (1.7.0)
cryptography (1.4)
dnslib (0.9.6)
enum (0.4.6)
geoip2 (2.4.0)
gevent (1.1.2)
greenlet (0.4.10)
IP2Location (8.0.0)
ipaddr (2.1.11)
ipaddress (1.0.16)
maxminddb (1.2.1)
pip (8.1.2)
pygeoip (0.3.2)
pyOpenSSL (0.13.1)
requests (2.11.1)
setuptools (26.0.0)
six (1.10.0)
wheel (0.29.0)
win-inet-pton (1.0.1)
```
pyOpenSSL 已经升到0.13.1了，再高的话goagent log里重试那部分貌似有问题，log里会有错误
