### ISSUE TITLE
纸飞机奇怪的更新, 3.7.9

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1091]
https://github.com/breakwa11/shadowsocks-csharp/releases/
明明作者声明不再更新

但是SS显示新版3.7.9, 却不能下载..............

**Comment by baoziwan** [comment]
破娃酱的推上有解释：

> 所有版本包括3.7.4.1及之前的均推送一个不存在的版本3.7.9，点击后将跳转到原版（因为无法写3.2，写3.2将不会提示更新）。另外请不要在推上玩阴谋论

**Comment by caofengzi** [comment]
破娃酱 (14)@RT私 译
#ShadowsocksR 已停止更新正好7个月，建议删除手上所有的SSR软体，使用原版SS，不再解答任何有关SSR的问题
2016-09-01 14:59:43

**Comment by wenliyang** [comment]
因此文引起的

http://www.chinagfw.org/2016/08/shadowsocks_31.html

**Comment by phuslu** [comment]
应该转移到 https://telegram.me/shadowsocksr 了

**Comment by wz7465** [comment]
无所谓，反正不用ssr，觉得作者脑洞大开的样子

**Comment by phuslu** [comment]
这，ssr 作者虽然是有点少女心，但是在我看来相当多的对于 ssr 的评价是不客观和不公正的。

爱谁谁吧。

**Comment by wz7465** [comment]
嗯，妹子的技术有，但开发思路不敢恭维，我不太感兴趣什么流量混淆，用用goproxy-vps不是挺好啊

**Comment by phuslu** [comment]
流量混肴其实挺好的

1. 防 ISP 或 GFW 的流量整形（基于协议白名单的 QoS)
2. 可以实现免流（这个比较敏感）

goproxy-vps 也有计划在服务端支持 h2c 之后加入流量混淆。

**Comment by phuslu** [comment]
连土豪的  darkcloud 也支持这个模式，说明还是有相当的价值。

https://twitter.com/bluecloudlink/status/737244053692022784

**Comment by jasonliul** [comment]
@phuslu 
流量混淆简单实用, 成本也低.
赞成社长

**Comment by jasonliul** [comment]
小丫头起码加入了前置支持, 今年中国ip的前置增加很多...

墙是双向的, 对于洋人, 搞一些这种逆翻墙资源, 俺们正好沾光.

**Comment by wz7465** [comment]
大家都穿白衬衫，clowwindy弄了件灰衬衫，妹子给改成了花衬衫
有句话，大隐隐于市小隐隐于山
当然代理https数据流和原始https数据流还是有些差别的，并不是流量混淆不能用，关键在构建的功力上，好比迷彩服，迷彩服和花衬衫还是有区别的
以社长的功力，总能给予人信任感吧

**Comment by dapao9999** [comment]
我一直用原版的，感觉这个华而不实

**Comment by breakwa11** [comment]
这个帖子我盯了4个月，现在特来留个脸，嗯，再见

**Comment by phuslu** [comment]
不忘初心，方得始终。

这句话虽然落了俗套，但是却也应景。

有可能的话请不要弃坑，继续负重前行吧。

**Comment by jasonliul** [comment]
@breakwa11 

美妞留脸? 相亲不...
:)

**Comment by MeABc** [comment]
你们怎么都认为 breakwa11 是个女的。难道看头像？

我一直都觉得 breakwa11 是男的。

哈哈。

**Comment by jasonliul** [comment]
@MeABc 

人家叫破娃酱....

**Comment by MeABc** [comment]
https://twitter.com/breakwa11/status/824197848627638273

😃

**Comment by breakwa11** [comment]
@MeABc 你想要表达啥

**Comment by MeABc** [comment]
我是想说，美女，大过年的你发那么大火气干嘛
😄

**Comment by jasonliul** [comment]
@breakwa11 
揪住, 强吻~~
美女只要用心.

列位接力.........

**Comment by breakwa11** [comment]
@MeABc 那是年前的事了
@jasonliul 接力干啥捏

**Comment by MeABc** [comment]
@breakwa11 大过年的，其它不多说，祝你新年快乐！

**Comment by jasonliul** [comment]
@breakwa11 
接力强吻, 任你随心掠食~~

**Comment by wpyok500** [comment]
@breakwa11 直接推倒强上，来吧！👍。
