### ISSUE TITLE
GoogleIPRange--整合版IP数据库

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#1095]
[GoogleIPRange](https://github.com/CNMan/GoogleIPRange)
整合自[gogotester](https://github.com/azzvx/gogotester)、[checkgoogleip](https://github.com/moonshawdo/checkgoogleip)、[gscan](https://github.com/yinqiwen/gscan)、[XX-Net](https://github.com/XX-net/XX-Net)、[XX-Mini](https://github.com/xyuanmu/XX-Mini)、[Google-IP-Range](https://github.com/Rongronggg9/Google-IP-Range)及自己搜寻的IP库，特别感谢各位开发者。

googleip.txt 目前共497920 IPs
nogoogleip.txt 目前共3494912 IPs，不过在VPS上跑了2遍，基本没有可用IP在里面了，如果你发现里面有可用IP，烦请及时反馈。

快一年没更新了，这两天又在VPS上测试整理了一下:)

**Comment by jasonliul** [comment]
估计没有多少残余部队

**Comment by hcym** [comment]
整合版IP

感谢感谢

**Comment by blob2015** [comment]
@jasonliul 
确实如此……
lz威武

**Comment by jasonliul** [comment]
@blob2015 

俺几个月没有搜索ip了, CNMan大大的暴力强搜仅仅增加7段, 而且两段俺已知, 不过近来变快了.
今年谷歌ip更新奇慢, 而且有缩水的感觉.

**Comment by CNMan** [comment]
@jasonliul 暴力强搜是去年的事了，这次更新只整合了公开的IP库，IP段相比去年确实缩水了

**Comment by jasonliul** [comment]
@CNMan 
DNS摸奖很难了, 不过俺一向还有运气.

**Comment by jzp820927** [comment]
IP 越来越难找了，不过还好，现在的 IP 都比较稳定了，不像前段时间，经常失效。

**Comment by jasonliul** [comment]
@jzp820927 

墙儿们今年没有运动, 不能邀功. 也懒惰了.
自然恢复生态平衡

**Comment by jzp820927** [comment]
说起来也奇怪，去年和上半年，封IP都积极的很，现在怎么这么太平了，莫非是改变封锁策略了。

**Comment by jasonliul** [comment]
@jzp820927 

中国人就像陶瓷, 熊猫, 属于娇养溺爱的物种. 就爱个与众不同.
突然发现满世界都搞网墙, 立刻就没瘾了.

虽然现在不是东亚病夫, 其实骨子里还是东亚贱夫, 一副猥琐龌龊的嘴脸.

俺不是说普通中国民众....

**Comment by jzp820927** [comment]
好吧，我知道你是说的 gfwer ，希望可以保持这种状态。
不过话说，以前天天和 gfwer 抗战，感觉生活挺有激情的。
现在突然太平了，有点失落的感觉，生活都没有激情了。

**Comment by blob2015** [comment]
@jzp820927 
激情多点放在妹纸上 :grinning: 
@jasonliul 
感觉老兄应该有所经历，能折腾，还有所激越 :beers:

**Comment by jzp820927** [comment]
现在 issues 都清净多了，和以前 goagent 在 google code 上的 issues 一样，只要出了问题，才会热闹。
