### ISSUE TITLE
自认为最好的Goproxy使用教程

### ISSUE THREAD

**Issue by SOE-121** [phuslu/goproxy#1096]
http://lajiyouxi.cf/Goproxy/wiki.html
自从GoAgent挂掉以后，俺一直在折腾搬瓦工SS + FinalSpeed，速度可以跑满带宽，直到某天VPS面板被墙了，虽然只持续了两天，但是我意识到谷歌云的浩瀚，可能是我日常上黄网最后的防线，于是，重拾Goporxy!

**Comment by blob2015** [comment]
不知道什么原因，俺的ff35打开乱码，opera12倒是正常。

**Comment by jap33** [comment]
俺的ff45打开乱码

**Comment by yaoguaishou** [comment]
是文字编码的问题，更换为;中文简体

**Comment by jzp820927** [comment]
应该是 html 里面没指定编码吧

**Comment by panpeach** [comment]
FF27以下版本，打开楼主贴出的页面编码，自动显示为简体中文，无需手动切换。
而FF高版本，每次打开上述网页，文字编码都要手动选择文字编码为简体中文
高版本FF，解决顶楼的页面乱码方法：选项-内容-（默认字体这栏-高级）勾选“允许页面选择……，后备文字编码选择”简体中文“，确定保存即可。

**Comment by SOE-121** [comment]
我的错，服务器nginx设置的问题，现在所有的浏览器都可以正确显示了，同时优化了7小时自动扫IP这个程序的垃圾回收，内存占用不会超过80M了，而且如果你是100M带宽，那你可以同时开10个，不会冲突，扫IP更快。。。

**Comment by 171563857** [comment]
不能用,反而把我的网络搞炸好几次- =...

**Comment by 171563857** [comment]
到底该怎么用啊QAQ

**Comment by jzp820927** [comment]
官方 wiki

**Comment by 171563857** [comment]
照着官方wiki去做,结果不行
然后用这个,结果把网络一直搞炸QAQ

**Comment by blob2015** [comment]
@171563857 
那你具体叙述啊，什么样的步骤，什么样的炸，你啥都不说，怎么搞？

**Comment by jzp820927** [comment]
按官方 wiki 操作的时候，问题出在什么地方，请详细说明

**Comment by SOE-121** [comment]
@171563857  官方教程忽略了一个关键步骤，你必须先找到一个能翻墙的代理才能继续部署Goproxy，还有扫IP的时候不要用无线网。。

**Comment by blob2015** [comment]
@SOE-121 
无线网？wifi？俺基本上都是无线网……
老兄扫出来不同？
提到的第一点，倒是可以考虑加上

**Comment by jyuan15** [comment]
gp和ga一样都不需要安装，应该没什么难度吧。

gp最麻烦的是那个gae.user.json文件，很难把格式弄好，多一个、少一个空格都要出错。希望有大神放一个标准的gae.user.json文件出来，大家拿来只需填appid和googleip就能用了。

**Comment by melos2016** [comment]
@jyuan15 你下载的压缩包里面没有这个文件吗？

**Comment by wenliyang** [comment]
@jyuan15 将 gae.json 复制一份，重命名为 gae.user.json
再用 Notepad2 或 Notepad++ 修改 gae.user.json，去除不需要修改的部分，一般只保留 APPID 和 IP 两部分即可

**Comment by blob2015** [comment]
各种疑问、困难，除了查看教程，还可以看 @jasonliul 的帖子，有各种信息、工具提供
