### ISSUE TITLE
GP进入四位数时代

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#1097]
开帖小庆下
社长辛苦了 :beers:

**Comment by inkdie** [comment]
哈哈，祝社长早日解决iphone tumblr客户端超过十秒视频无法播放的问题。

另外，社长说，版本号超过1000，自动更新不分稳定版和测试版都能更新。

**Comment by jzp820927** [comment]
可惜还没出正式版，更可惜的是，autorange 还没完成。

**Comment by phuslu** [comment]
谢谢鼓励。

正式版还无明确的时间点，需要继续开发和完善的地方还有相当一部分工作。

**Comment by dfbgp** [comment]
社长辛苦了，专门来庆祝一下

**Comment by github-xx** [comment]
早就使用GP了，前一大段时间用XXnet,现在XX不更新了。基本转战用GP了，社长加油

**Comment by jzp820927** [comment]
现在 IP 非常稳定，用什么都没问题。

**Comment by hcym** [comment]
谢谢社长
辛苦了

**Comment by darkwolf99** [comment]
留个纪念

感谢社长

**Comment by wenliyang** [comment]
GP很好用
社长辛苦

**Comment by hotbbs** [comment]
鼓励鼓励，社长辛苦啦！！

**Comment by minorisprit** [comment]
社长加油，GP现在是速度最快的免费梯子了，IP也很稳定了，油管可以吃满带宽，基本是夫复何求了，以后再解决autorange问题的话，GP就基本无敌了

**Comment by jzp820927** [comment]
我觉得能解决证书问题，那才是真无敌。毕竟移动端很难兼容。

**Comment by vmnet** [comment]
:tada:  :hibiscus:

**Comment by cclu** [comment]
在MAC下遇到证书问题很头痛，就算sudo goproxy，firefox和safari仍然不认证书合法。WIN下无问题。

2016-09-05 19:16 GMT+08:00 vmnet <notifications@github.com>:

**Comment by jzp820927** [comment]
安装证书了麽

**Comment by cclu** [comment]
@jzp820927

问题已解决。不知道怎么装了俩goproxy crt..

**Comment by jzp820927** [comment]
估计你是导入新证书之前，忘记删除久证书了
