### ISSUE TITLE
r1000编译失败，cannot use pc.conn.RemoteAddr() (type net.Addr) as type string in assignment

### ISSUE THREAD

**Issue by tc5832** [phuslu/goproxy#1099]
编译golang有提示：
\# net/http
net/http/transport.go:1671: cannot use pc.conn.RemoteAddr() (type net.Addr) as type string in assignment

接着编译goproxy出错：
go build -v -ldflags="-s -w -X main.version=r1000 -X main.http2rev=d9943c3" -o /mnt/disk2/goproxy/goproxy/build/obj/goproxy .
net/http
github.com/cloudflare/golibs/lrucache
github.com/phuslu/glog
github.com/miekg/dns
github.com/wangtuanjie/ip17mon
golang.org/x/crypto/curve25519
golang.org/x/crypto/ed25519/internal/edwards25519
\# net/http
../go-linux-amd64-bootstrap/src/net/http/transport.go:1671: cannot use pc.conn.RemoteAddr() (type net.Addr) as type string in assignment
github.com/phuslu/net/http2/hpack
github.com/phuslu/net/lex/httplex
github.com/juju/ratelimit
golang.org/x/crypto/ed25519
golang.org/x/crypto/ssh
make: *** [Makefile:79: /mnt/disk2/goproxy/goproxy/build/obj/goproxy] Error 2

版本：
go
commit f5aacf8269c2e201b72159da589fe79762124a23
Author: Phus Lu <phuslu@hotmail.com>
Date:   Mon Sep 5 11:22:08 2016 +0800

    net/http: add RemoteAddr to *http.Response
    
    Signed-off-by: Phus Lu <phuslu@hotmail.com>

goproxy：
commit 23d0501b684127632c55119c24769106def89c2c
Author: Phus Lu <phuslu@hotmail.com>
Date:   Sun Sep 4 21:58:33 2016 +0800

    bump auto update version

编译golang用的是，https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz

**Comment by phuslu** [comment]
https://github.com/phuslu/goproxy/blob/wiki/HowToBuild.md

**Comment by johnsonz** [comment]
@phuslu  请问编译golang 工具链后，会不会对之前的golang环境造成影响？

**Comment by phuslu** [comment]
不会，只对当前 shell 有影响。因为设置了 goroot gopath 变量。
