### ISSUE TITLE
按照wiki做了2次,还是失败了,新人不懂啊QAQ

### ISSUE THREAD

**Issue by 171563857** [phuslu/goproxy#1102]
![qq 20160906202332](https://cloud.githubusercontent.com/assets/22027896/18282837/63dfd77a-7495-11e6-8fcf-124ef9bcbced.png)
![qq 20160907005113](https://cloud.githubusercontent.com/assets/22027896/18282847/6f3bd42a-7495-11e6-8aff-9fcc7217600b.png)
![qq 20160907005124](https://cloud.githubusercontent.com/assets/22027896/18282848/6f5cb046-7495-11e6-86a7-2f1efadd9d81.png)
做了2遍,还是同样的错误,新人一枚QAQ

**Comment by jzp820927** [comment]
看日志，你是没有可用IP，请观察日志中 绿色部分， good_addrs=0，请自行运行可用 IP ，放入 gae.json，然后再运行客户端。

**Comment by yqy6611** [comment]
没有ip

**Comment by 171563857** [comment]
可用ip是添加在"google_hk"里面吧?

**Comment by jzp820927** [comment]
对，官方 wiki 有详细说明，请查看官方 wiki 操作。

**Comment by 171563857** [comment]
解决了^0^

**Comment by 171563857** [comment]
那些写在配置介绍wiki里
我只跟着简单介绍wiki做

**Comment by blob2015** [comment]
看说明书，不会浪费你时间，或者不会浪费你时间，却会大大拯救你的时间，还有心情
