### ISSUE TITLE
请问社长，64位和32位的区别？

### ISSUE THREAD

**Issue by lazureice** [phuslu/goproxy#1121]
我的系统是win10，64位。请问64位和32位的goproxy有什么区别？
我用着感觉没啥区别....

**Comment by phuslu** [comment]
如果是近几年的 CPU（比如 i3， 支持 AES-NI 指令），推荐使用 64 位。

**Comment by lazureice** [comment]
@phuslu 

Intel Core i5-4200H @ 2.80GHz

**Comment by phuslu** [comment]
那更必须使用 64 的 goproxy 了。
cloudflare 用 AES-NI 指令大大加速了 golang tls 的加解密的速度，见 https://blog.cloudflare.com/go-crypto-bridging-the-performance-gap/

golang 1.6 以后的版本已经合并了这个补丁。

**Comment by lazureice** [comment]
Thx~
