### ISSUE TITLE
接R1K后，红字变多，好IP变不可用问题。

### ISSUE THREAD

**Issue by sh0uw4ng** [phuslu/goproxy#1128]
接上个问题 [#1126](https://github.com/phuslu/goproxy/issues/1126)

下载了最新版本1030，复现了我说的问题。
复现方式如下:
1.  正常刷推得请求
![2](https://cloud.githubusercontent.com/assets/8855832/18459820/4fd6b578-799f-11e6-883d-2fb144316421.png)

2.  访问 https://www.google.com/NCR
![1](https://cloud.githubusercontent.com/assets/8855832/18459828/699f189c-799f-11e6-9c46-ea0e91e1f570.png)

3.  IP不可用, [3f53ee4](https://github.com/phuslu/goproxy/commit/3f53ee4)
![3](https://cloud.githubusercontent.com/assets/8855832/18459839/8280afe2-799f-11e6-996e-81dfb413a6d4.png)

**Comment by Bobfree123** [comment]
appid是否重新上传到最新服务端了？

**Comment by phuslu** [comment]
是 `https://www.google.com/ncr` 不是 `https://www.google.com/NCR` 
你这样会让 goproxy 把你的 IP 误认为坏 IP 加入临时黑名单(5 分钟）

再加上你填的 IP 本来就少(2个?)，所以就上不去了。

**Comment by sh0uw4ng** [comment]
@phuslu 我是故意输错的，希望社长对这个规则再优化下？因为头几次也是不知道什么原因就触发了这个规则，然后就红了。在R1k及以前跑的很6，两个IP很快几乎没有问题。

**Comment by phuslu** [comment]
好的，我在 https://github.com/phuslu/goproxy/commit/0784994e176458281e375307ecce62da0f146028 加了一个判断，如果 good_ips 小于 10 的话，就不加入临时黑名单了。

这样应该会好些，谢谢反馈。

**Comment by sh0uw4ng** [comment]
谢谢社长！！

**Comment by jzp820927** [comment]
原来是这个原因造成的，怪不得我用的 4个IP，也有这个报错，但是IP其实都是好的，看来我得更新一下了。

**Comment by distance00** [comment]
是访问一个不存在的google地址就会触发吗？

**Comment by jzp820927** [comment]
不是，正常访问，也会促发。只是不影响使用，我就没反映上来。

**Comment by distance00** [comment]
正常访问，也许真是ip失效了，到底哪些情况会让gop误认为ip失效呢？访问连接不上的网站吗？

**Comment by MeABc** [comment]
> 正常访问，也许真是ip失效了，到底哪些情况会让gop误认为ip失效呢？访问连接不上的网站吗？

楼主的情况是社长新加的 404 优化引起的---对多 IP 的用户很有好处。返回404就会加入5分钟的黑名单----`认为ip失效` 。

**Comment by phuslu** [comment]
赞同 @MeABc 所说的，404 的问题在 1000+ 的 IP 上是个比较明显的问题，为此优化是值得。

`多IP` 的好处就是使用起来不必太关心那些有效那些无效，类似 xx-net 的体验。

**Comment by phuslu** [comment]
另外，请大家 ( @MeABc ) 注意 404 问题的 IP，有劳把 IP 地址发给我，我可以继续做相应的进一步的优化（防止误杀）

我的邮件地址请见我的 github 个人主页，谢谢大家。

**Comment by MeABc** [comment]
> 类似 xx-net 的体验。

呃，我现在 3000+ IP 了，达到 xx-net 的标准----GP用另一种方式实现了。

> 注意 404 问题的 IP，有劳把 IP 地址发给我

收到。

**Comment by phuslu** [comment]
嗯，出于种种原因，goproxy 在可以预见的一段时期都没有加入自动扫描 IP 功能的计划。
因此能做的就是，对于各种数目的 IP，尽量能够优化到一个良好的运行状态。

**Comment by yuli6800** [comment]
请问，类似这种Googleiprange扫出来的ip如何快速提取出来转化适用goproxy格式的ip
61.238.239.240 558 *.googlevideo.com gvs 1.0
115.164.12.156 559 *.googlevideo.com gvs 1.0
115.164.12.169 560 *.googlevideo.com gvs 1.0
115.254.121.230 560 *.googlevideo.com gvs 1.0
150.100.16.123 560 *.googlevideo.com gvs 1.0
113.171.242.226 561 google.com gws
150.100.16.117 561 *.googlevideo.com gvs 1.0，
后面的怎么快速删除

**Comment by yqy6611** [comment]
@yuli6800 有一种方法是先用MFF再次扫描一遍再用那个转格式软件

**Comment by MeABc** [comment]
> 150.100.16.117 561 *.googlevideo.com gvs 1.0，
> 后面的怎么快速删除

我是用脚本弄的

```
grep 过滤(提取) ip

grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' sourcefile.txt > destfile.txt
```

**Comment by yqy6611** [comment]
脚本这方法不错。有了这脚本后续怎么做？

**Comment by phuslu** [comment]
我是用 sublime 弄得，见下图 gif 动画

![1](https://cloud.githubusercontent.com/assets/195836/18476236/d0d7f7c0-79fb-11e6-8389-aa0f6b162532.gif)

**Comment by yuli6800** [comment]
谢谢各位解答。
