### ISSUE TITLE
挖矿, 已经out

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1142]
新货不多
SG
109.144.0.0

ID
203.207.55.0
45.121.219.0

RU
91.202.254.0

TH
115.87.70.0
115.87.71.0
110.164.9.0
110.164.18.0
49.231.55.0

NZ
203.184.8.0

**Comment by blob2015** [comment]
没老兄，不欢乐 :grinning: 
如果置于ipv6之下？
感觉最近都还是比较平稳，几个月了，都还能用 :grinning:

**Comment by jzp820927** [comment]
J大又出新货了，鸡冻啊！

**Comment by jasonliul** [comment]
@jzp820927 

没有挖矿红包派送, 这里死活木有人气.

再来几个

MM
103.52.13.0
103.52.15.0
43.224.86.0
59.153.90.0

KR
59.18.35.0 [复活]
59.18.45.0 [复活]
59.20.132.0

**Comment by jzp820927** [comment]
J大一到，气氛活跃。

**Comment by carotin** [comment]
凑下热闹~

**Comment by jasonliul** [comment]
@blob2015 
不过变动也很小, 很难找到新字段

**Comment by MeABc** [comment]
小提示：欧洲的也不错的。不要老是盯着`海底光缆`，还有很多`陆地光缆`。

**Comment by jasonliul** [comment]
几天前新版的服务端, 效率很高.
而且很多字段是人为增大的ping值, 只要无干扰, 连接上之后其实没有什么区别.

**Comment by jzp820927** [comment]
我这儿是电信网，你们懂得

**Comment by vmnet** [comment]
我晕，我还以为说Bitcoin呢

**Comment by jzp820927** [comment]
我能说其实我也以为是 BT 挖矿。

**Comment by yoker** [comment]
看不懂你们在说什么

**Comment by vmnet** [comment]
@jzp820927 13年初挖过，那时才10几美元，然后年底就涨到1200多好像

**Comment by jzp820927** [comment]
那你不是发财了？13年挖的，现在涨  N 倍了，你挖了多少个？

**Comment by jasonliul** [comment]
Id 45.121.219.0, 103.234.120.0, 114.125.97.0, 66.96.226.0, 66.96.224.0
Mn 103.29.146.0
My 58.26.8.0
VN 125.234.160.0
tw 61.58.64.0, 61.60.213.0

**Comment by wpyok500** [comment]
大神这是在深挖坑啊

**Comment by jzp820927** [comment]
现在好像都不缺 IP了，J大还在淘IP

**Comment by blob2015** [comment]
@jasonliul 
@jzp820927 
j哥这是战斗在继续 :grinning:
