### ISSUE TITLE
SafeIP 2.0.0.2615 中文版

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1145]
SafeIP 2.0.0.2615
http://www.freesafeip.com/SafeIP.exe

安卓
https://play.google.com/store/apps/details?id=com.safeip.openvpn&hl=cn

现在免费服务器不大多

需要加hosts使用, 或者使用帽架, #373
23.19.89.38 api.freesafeip.com
96.127.146.150 secure.freesafeip.com
5.135.181.91 secure2.freesafeip.com

暂时木有破解版本

**SafeIP 2.0.0.2602 PRO**
http://www.chaofree.com/2013/02/SafeIP.html
Sn
17108-85131-85564-95332-68376

**Comment by jzp820927** [comment]
又有新产品了，不错不错，马上试用
