### ISSUE TITLE
建议在加载ip后先检查一遍所有ip并按延迟率排列下ip,后优先加载延迟率低的ip使用

### ISSUE THREAD

**Issue by wpyok500** [phuslu/goproxy#1146]
因gp加载多ip时筛选比较温和，建议在加载ip后能先检查一遍所有ip并按延迟率排列下ip，后优先加载延迟率低的ip使用，提高下视频播放流畅性。

**Comment by Bobfree123** [comment]
这个建议好。
“后优先加载延迟率低的ip使用”，建议列一个范围（个数，延迟等），如果只是用一个ip，那这个ip压力好大。

**Comment by MeABc** [comment]
实现上社长在你的上一个帖子中已经说了，不知你有没有看明白或者测试过没。
上图：

![2](https://cloud.githubusercontent.com/assets/18194126/18604128/4ba5584c-7cab-11e6-9f5c-4dd9bc4cf2d7.png)

"Level"----这个就是 `IP筛选并发数` 。

有时间再更新下文档。

**Comment by MeABc** [comment]
关于 "按延迟排序" 这个问题，首先，N个版本号前就已做了优化，你可以先查看之前的贴子，看完后如有更好的方案或建议，再 @社长。

**Comment by wpyok500** [comment]
先排序后在使用，像xx那样有个检查所有ip模块。

**Comment by phuslu** [comment]
暂无计划

**Comment by phuslu** [comment]
解释一下，目前的 ip 筛选策略是深思熟虑过的。
目标是尽量保持温和的前提下针对不同数目和质量的 ip 做最优化。
目前算是初步达成目标。只会做一些小改进了。

ps，所谓温和要满足这些要求

1. 用户在使用过程中不会和用户进程争抢带宽和资源。
2. 用户在不使用的情况下，尽量让出带宽。
