### ISSUE TITLE
Google books 搜索结果无法打开，报错“Error 404”

### ISSUE THREAD

**Issue by liweitd** [phuslu/goproxy#1148]
1、使用https://books.google.com/进行搜索，搜索结果页面能顺利打开。
2、进一步打开搜索结果时，“https://books.google.com/books?id=”会自动切换为“https://books.google.cn/books?id=”，并报错“404. That’s an error.”。更换IP后问题重现。
3、使用XX-net的话，同样浏览器及插件环境下，搜索结果能顺利打开。

**Comment by phuslu** [comment]
已确认。

**Comment by phuslu** [comment]
请编辑 gae.json
加入类似
`"books.google.cn": "google_hk"`

**Comment by phuslu** [comment]
如果开了 region filter 的话，也请打开 site filter，把 *.google.cn 指定 gae filter

**Comment by liweitd** [comment]
@phuslu 
社长，按照你的提示进行了设置，但问题还是照旧，请帮忙再看看。谢谢！
报错提示：
W0918 14:56:18.590290    5368 gae.go:524] GAE: 61.238.239.241 StatusCode is 404, not a gws/gvs ip, add to blacklist for 5m0s

**Comment by jzp820927** [comment]
看日志是返回 的 IP 不可用，但验证了下，IP 好像是 gws 的

**Comment by riumiyama** [comment]
改了沒用

**Comment by phuslu** [comment]
r1044 已经修复。不过得把 books.google.cn 也加入浏览器插件的 goproxy 代理里面，或者使用 goproxy 全局代理。

**Comment by liweitd** [comment]
使用反馈：
社长修复后，网址不再由“"books.google.com"自动变更为"books.google.cn"，网页能打开，但只能加载书本的第一页内容。这种情况会和autorange有关吗？
谢谢 @phuslu

**Comment by liweitd** [comment]
使用反馈：
社长修复后，网址不再由“"books.google.com"自动变更为"books.google.cn"，网页能打开，但只能加载书本的第一页内容。
谢谢 @phuslu

**Comment by MeABc** [comment]
贴网址和日志看看。

亲，不要重发呀。

**Comment by liweitd** [comment]
网址：https://books.google.com/books?id=wVGB5Ym10hIC&pg=PA19&dq=glioblastoma&hl=en&sa=X&redir_esc=y#v=onepage&q=glioblastoma&f=false

I0918 23:26:07.046465    7160 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "clients5.google.com:443") with good_addrs=412, bad_addrs=103
I0918 23:26:07.047465    7160 gae.go:557] 127.0.0.1:4546 "GAE DIRECT GET https://books.google.com/googlebooks/images/kennedy/zoom_tool.png HTTP/1.1" 304
I0918 23:26:07.064476    7160 gae.go:557] 127.0.0.1:4572 "GAE DIRECT GET https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.krlNDzQq4UQ.O/m=gapi_iframes,googleapis_client,plusone/rt=j/sv=1/d=1/ed=1/rs=AHpOoo-1sKXim1lk_Z1AyYD0rbD4xIG8lw/cb=gapi.loaded_0 HTTP/1.1" 304
I0918 23:26:07.083489    7160 gae.go:557] 127.0.0.1:4557 "GAE DIRECT GET https://books.google.com/googlebooks/images/kennedy/zoom_out.png HTTP/1.1" 304
I0918 23:26:07.106521    7160 gae.go:557] 127.0.0.1:4546 "GAE DIRECT GET https://books.google.com/googlebooks/images/kennedy/maximize.png HTTP/1.1" 304
I0918 23:26:07.140044    7160 gae.go:557] 127.0.0.1:4557 "GAE DIRECT GET https://books.google.com/googlebooks/images/kennedy/insert_link.png HTTP/1.1" 304
I0918 23:26:07.165060    7160 gae.go:557] 127.0.0.1:4546 "GAE DIRECT GET https://books.google.com/googlebooks/images/my_library_logo.png HTTP/1.1" 304
I0918 23:26:07.197082    7160 gae.go:557] 127.0.0.1:4557 "GAE DIRECT GET https://books.google.com/googlebooks/images/kennedy/menu_down_arrow.png HTTP/1.1" 304
I0918 23:26:07.226107    7160 gae.go:557] 127.0.0.1:4546 "GAE DIRECT GET https://books.google.com/googlebooks/images/kennedy/page_left.png HTTP/1.1" 304
I0918 23:26:07.253124    7160 gae.go:557] 127.0.0.1:4557 "GAE DIRECT GET https://books.google.com/googlebooks/images/kennedy/page_right.png HTTP/1.1" 304
I0918 23:26:07.260129    7160 gae.go:557] 127.0.0.1:4540 "GAE DIRECT GET https://books.google.com/books/content?id=wVGB5Ym10hIC&printsec=frontcover&img=1&zoom=5&edge=curl&imgtk=AFLRE73X4dULQUmPyah1g2k9-LVisr20gmst7NerBmydVG9aYEshzzb7H1NqO5RRcgfldQB49mI_5dLCBgELyPcugGGBLBKN_7XSlQXjzmQVM7Y-sGQw6MY8PbpGcheZkN8V1w_On2J3 HTTP/1.1" 200 11566
I0918 23:26:07.283152    7160 gae.go:557] 127.0.0.1:4546 "GAE DIRECT GET https://books.google.com/googlebooks/images/kennedy/settings.png HTTP/1.1" 304
I0918 23:26:07.315682    7160 gae.go:557] 127.0.0.1:4755 "GAE DIRECT GET https://clients5.google.com/pagead/drt/dn/ HTTP/1.1" 304
I0918 23:26:07.383111    7160 gae.go:557] 127.0.0.1:4527 "GAE DIRECT GET https://books.google.com/books/content?id=wVGB5Ym10hIC&pg=PA19&img=1&zoom=3&hl=en&sig=ACfU3U29CFT8_okYf9XW3EUS0zHerJ1msQ&w=1280 HTTP/1.1" 200 309645
I0918 23:26:07.407644    7160 gae.go:557] 127.0.0.1:4555 "GAE DIRECT GET https://books.google.com/books/content?id=wVGB5Ym10hIC&pg=PA19&img=1&zoom=3&hl=en&sig=ACfU3U29CFT8_okYf9XW3EUS0zHerJ1msQ&w=685 HTTP/1.1" 200 112823
I0918 23:26:07.422661    7160 direct.go:144] 127.0.0.1:5278 "DIRECT CONNECT fonts.gstatic.com:443 HTTP/1.1" - -
I0918 23:26:07.517816    7160 gae.go:557] 127.0.0.1:4755 "GAE DIRECT GET https://clients5.google.com/pagead/drt/dn/dn.js HTTP/1.1" 304
I0918 23:26:07.605879    7160 gae.go:557] 127.0.0.1:4556 "GAE DIRECT GET https://books.google.com/books?id=wVGB5Ym10hIC&lpg=PA19&dq=glioblastoma&pg=PA20&jscmd=click3&vq=glioblastoma HTTP/1.1" 302 340
I0918 23:26:07.620390    7160 gae.go:429] 127.0.0.1:5273 "GAE REDIRECT GET https://books.google.com/books?id=wVGB5Ym10hIC&lpg=PA19&dq=glioblastoma&pg=PA20&jscmd=click3&vq=glioblastoma&redir_esc=y HTTP/1.1" - -
I0918 23:26:07.668543    7160 gae.go:557] 127.0.0.1:4575 "GAE DIRECT POST https://plus.google.com/u/0/_/n/gcosuc HTTP/1.1" 200
I0918 23:26:07.820610    7160 gae.go:557] 127.0.0.1:4572 "GAE DIRECT GET https://apis.google.com/u/0/_/+1/fastbutton?usegapi=1&size=small&count=true&source=google%3ABOOKS&hl=en&origin=https%3A%2F%2Fbooks.google.com&url=https%3A%2F%2Fbooks.google.com%2Fbooks%2Fabout%2FNeuro_Oncology_of_CNS_Tumors.html%3Fid%3DwVGB5Ym10hIC&gsrc=1p&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.krlNDzQq4UQ.O%2Fm%3D__features__%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo-1sKXim1lk_Z1AyYD0rbD4xIG8lw HTTP/1.1" 200
I0918 23:26:07.999796    7160 gae.go:557] 127.0.0.1:4572 "GAE DIRECT GET https://apis.google.com/_/scs/apps-static/_/ss/k=oz.plusone.1fi6yaqab7g5b.L.W.O/d=0/rs=AGLTcCNwKg7yoiaUygP_ZMX1yuSyfnmqSw HTTP/1.1" 304
I0918 23:26:08.052848    7160 dialer2.go:98] MULTIDIALER DialTLS2("tcp", "apis.google.com:443") with good_addrs=414, bad_addrs=103
I0918 23:26:08.107386    7160 gae.go:557] 127.0.0.1:4572 "GAE DIRECT GET https://apis.google.com/_/scs/abc-static/_/js/k=gapi.gapi.en.krlNDzQq4UQ.O/m=googleapis_client,iframes_styles_bubble_internal,gapi_iframes_style_common,gapi_iframes_iframer/rt=j/sv=1/d=1/ed=1/rs=AHpOoo-1sKXim1lk_Z1AyYD0rbD4xIG8lw/cb=gapi.loaded_0 HTTP/1.1" 304
I0918 23:26:08.159460    7160 gae.go:557] 127.0.0.1:4797 "GAE DIRECT GET https://apis.google.com/_/scs/apps-static/_/js/k=oz.plusone.en.TUtp-iUHjas.O/m=p1b,p1p/rt=j/sv=1/d=1/ed=1/rs=AGLTcCPiyITMO_1IXcnPwnSNLz7GwI4vZA/cb=gapi.loaded_1 HTTP/1.1" 304
I0918 23:26:08.209002    7160 gae.go:557] 127.0.0.1:4527 "GAE DIRECT GET https://books.google.com/favicon.ico HTTP/1.1" 200 1517

**Comment by MeABc** [comment]
![image](https://cloud.githubusercontent.com/assets/18194126/18616941/35968b4a-7df8-11e6-9913-0ab7bfc7e904.png)

**Comment by liweitd** [comment]
Google没那么小气的，一般可以免费预览几十页内容；
用XX-net能全部打开。

**Comment by phuslu** [comment]
调试了一下，发现 google 对国内直连 books.google.com 有很多限制，在此情况下没有好的解决办法。

在 r1043 把 books.google.com 加入到 ForceGAE 了，就这样吧。
