### ISSUE TITLE
goagent删了代表不再维护，因为自由的种子已经生根发芽!

### ISSUE THREAD

**Issue by phusIu** [phuslu/goproxy#115]
google code关闭了，goagent项目删除了，用帮主引用过的一句话就是： 
**Everything that has a beginning has an ending.**。

感谢帮主；
感谢各位contributors；
感谢各位墙友；
当然还要感谢goagent-based最性感的项目[XX-Net] (https://github.com/XX-net/XX-Net)，@XX-Net 
```
Google Code关闭后去哪里[交流地方如下]
第一个是帮主的github讨论区：
https://github.com/phuslu/goproxy/issues

另一个是前面组建的Google Group讨论组：
https://groups.google.com/forum/#!forum/fqlt


相关讨论的帖子，请参考：
https://code.google.com/p/goagent/issues/detail?id=22007
https://code.google.com/p/goagent/issues/detail?id=21651
```

===
最后，用一段帮主关于goagent原理的的Q&A来结束这个充满感恩的issue：

goagent 的原理用一句 python 代码就可以演示

```python
urllib2.urlopen(urllib2.Request('https://mail.google.com/fetch.py', data='methd=GET&url=http://twitter.com/&&body=', headers={'Host': 'goagent.appspot.com'}))
```
1. 好了，你现在有了一个托管在国外主机上的 WEB API，剩下的事情就是如何把它包装成一个本地代理了。

2. 包装成 HTTP 代理也比较简单，借助 python 标准库的 SimpleHTTPServer/BaseHTTPHanlder 我们大约需要 500 行的 python 代码完成这个代理。

3. 接下来的问题是大文件（视频）的支持和 HTTPS 的支持。
这个阶段你会遇到各种 HTTP/HTTPS 的细节问题，幸好我们完成了它，这时候代码增加到了 1000 行。

4. 好了，现在现在我们可以让它真正开始工作了。需要处理各个平台 windows/macos/linux/android 的问题，还好大多数平台我们可以自己找到，并且修复在这些平台的 bug。代码中会增加 1500 行。

5. 另外，我们还需要在各种浏览器下测试程序的行为，这时候程序 LOC 增长不会太大，但是解决这个兼容性问题会耗掉一些精力。

6. 为了这个程序能够易用，我们需要在各个平台写个简单的 GUI 外壳，这需要我们懂 pyobjc/gtk/win32 等等支持。不过这个并不算难，折腾一番，我们也把这些外壳捣鼓出来了。此时代码已经大大膨胀了。

7. 最后，用户会提出一些很合理的改进要求，比如 PAC/DNS/PHP 等等支持。嗯，加油做完这些，就差不多了。

```好吧，如上述所示，goagent 的确没有特别的难点，我相信任何一个 python 程序员会在一个星期到一个月的时间内把它做出来。 :)```

===
那么最后一个问题:

为什么各种软件中 goagent 相对比较受欢饮，它难在什么地方？

答案其实很简单, **热情和精力。**

是的，有心做这个程序的人不少，尤其是程序员，对于开发一个自用的翻墙软件很多人有相当的兴趣。事实上也有不少这样的实现。
但是当用户提起 goagent 的评价是：“好用，快速，稳定，免费”。能够同时满足这些要求，goagent 花了不少心思。

好用：为了让 goagent 好用，需要学习不同平台和不同浏览器的特性，琢磨用户的用法，反复推敲功能的实现。
快速：为了能让 goagent 跑的更快，作者阅读 python 的标准库代码和 CPython 的实现，看完了 sildeshares 上的绝大部分关于 python 高效代码的方式和技巧。
稳定：Google 时常被干扰，如何优化连接方式是个永恒的话题，goagent 的连接方式前后一共改过三次。
免费：是的，如同 Goagent是怎么赢利的？ 这个问题的最佳回答，我很赞同这个回答 **不是所有东西都是为了盈利才出现的**

**Comment by fletchere** [comment]
非常感谢phuslu，感谢goagent陪伴的日日夜夜。

**Comment by phuslu** [comment]
为什么假冒帐号。。。
