### ISSUE TITLE
帮主你终于出来了，看到你平安就好!

### ISSUE THREAD

**Issue by phusIu** [phuslu/goproxy#116]
首先，帮主，我无意冒犯你。

看到你几天没出来，墙友们都很焦急，于是我机智的取了这个山寨名，诱惑你出来 :sweat_smile:  

很高兴你close了我刚才的帖子，说明你还好好的！

永远爱你～ :heart:

**Comment by ARwMq9b6** [comment]
神人你终于出来了，俺要买你的 ID 。

**Comment by wenliyang** [comment]
等下，ID能取得一样的？

**Comment by ARwMq9b6** [comment]
基友们为了表达对帮主的思念，也是蛮拼的。

**Comment by phusIu** [comment]
@ARwMq9b6 我决定封印这个ID了:u7981:，for 帮主 

@wenliyang 我才是帮主的big fan :heart_eyes:

**Comment by phuslu** [comment]
现在谈论这个可能不合适。再过了一两个月后， 我会说明一下的。谢谢关心。
