### ISSUE TITLE
只是区分gvs与gws了？

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#1160]
底下的类别不要紧了？所谓带宽，波动也大？响应速度，还能一看？可能国家地区更加重要些？
以前好像_.c.docs.google.com 不好用？现在好像可以了？
gvs主要就_.c.docs.google.com与_.googlevideo.com？其他的都是gws？
*.appspot.com，_.au/de/fr/g/jp/uk/无.doubleclick.net，_.blogger.com，_.gfsvc.com，_.google-analytics.com，_.googleadservices.com，_.googleapis.com，_.googlecode.com，_.googlegroups.com，_.googleusercontent.com，_.gstatic.com（_.unicast.metric.gstatic.com），*.mail.google.com……
都差不多？

**Comment by jzp820927** [comment]
差不多是这样

**Comment by MeABc** [comment]
这要看你用哪个工具扫了，有些工具已不用域名来作判断了。

**Comment by blob2015** [comment]
@MeABc 
老兄介绍几个？不用域名的

**Comment by Asteroids89** [comment]
现在在用MMF，还有其他的更好的么？

**Comment by hcym** [comment]
checkiptools

**Comment by MeABc** [comment]
楼上正解
