### ISSUE TITLE
r1058--ip.html  bug

### ISSUE THREAD

**Issue by MeABc** [phuslu/goproxy#1166]
问题一:
![image](https://cloud.githubusercontent.com/assets/18194126/18673772/940952ba-7f7f-11e6-921a-e2547da8f690.png)

问题二:
![image](https://cloud.githubusercontent.com/assets/18194126/18673842/d5e9a220-7f7f-11e6-9a93-ddff7ea05d3d.png)

设置： "autoproxy.user.json" --> "IPHTML" --> "false" 

1。在 r1056 中，上述设置后，并不会出现这个按钮。
2。在 r1058 中，同样上述设置，格式化IP后，点这个按钮没有任何提示----即有没有导入成功。

**Comment by hcym** [comment]
唉
简单就是美啊

还是别弄这些花花绿绿的好

**Comment by wpyok500** [comment]
@hcym 这已经很简单了，在简单就没这个页面了。

**Comment by MeABc** [comment]
看了代码，图一代码中就有。。。

关于图2，我想说的是，那按钮最好有个控制开关(如 r1056)，我怕哪天自己手践点一下，几千个IP啊。。。。

**Comment by phuslu** [comment]
应该已经修复了。

**Comment by MeABc** [comment]
![image](https://cloud.githubusercontent.com/assets/18194126/18718851/784c9554-8057-11e6-8e4a-4a464fa0a809.png)

好了。有劳社长。
