### ISSUE TITLE
goagent的速度，114号你输了

### ISSUE THREAD

**Issue by tylokfree** [phuslu/goproxy#117]
设置得当，goagent是满带宽加速的。
![default](https://cloud.githubusercontent.com/assets/13965217/9495327/8ee93e42-4c3d-11e5-9a79-46c4062ae6fe.PNG)

**Comment by sundaqing1969** [comment]
还是要好ip吧

**Comment by dnsmasq** [comment]
30W,conoha.jp甘拜下风,要是我要linode跑1G端口绝对可以跑90W~

**Comment by maryjeck** [comment]
说的是设置得当，楼主倒是贴出来改了哪些参数啊

**Comment by lefantian** [comment]
最近 gfw疲软

**Comment by xyuanmu** [comment]
一个个都是土豪啊

**Comment by tylokfree** [comment]
其实也没啥说的，不要被表面唬住，只是免费蹭了隔壁杨小姐20M网络而已。一直用的是3.1.25版本，懒得更新。修改快一年了，某些细节忘了，只讲核心的，都是老调们：
仅用一个稳定ip，论坛多的是；magic-actions  始终flash加速：[autorange]threads = 32maxsize = 262144waitsize = 1048576bufsize = 32768  似乎还有其他的，忘了。
都是电脑，网络等综合知识的运用。

**Comment by Yamazaki-wu** [comment]
能否告知从哪里找到IP啊？设置的话能否发一份proxy.ini做参考，不过我是上海电信用户，不看4K看1080或者720也行啊。
