### ISSUE TITLE
为何获取的代理IP只有几个？

### ISSUE THREAD

**Issue by sobeited** [phuslu/goproxy#1172]
goproxy获取到到的代理IP为什么就那么几个？不同地域、不同id获取到的ip还是一样的。他是根据什么来获取代理ip的？另外，gae.json中添加的ip作用是什么，一直没搞懂，只是每天机械性的跟着更新

**Comment by jzp820927** [comment]
gae.json 中的 IP 是 GAE 的入口 IP，也就是用来连接 GAE 的 IP (给你打个形象的比喻，就好比是 路由器 LAN 口的 192.168 局域网 IP，这个 IP 你可以手工调整)，而网站上显示的你的 IP，是 GAE 的出口 IP (就好比是 路由器 WAN 口的外网 IP，而这个 IP 是 ISP 分配的，你是不能调整的)。
