### ISSUE TITLE
纸飞机 3.3.1, 还没死

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1173]
https://github.com/shadowsocks/shadowsocks-windows/releases

哈, 哈

**Comment by fuckGFW2015** [comment]
有人接手？

**Comment by jzp820927** [comment]
一直都没死啊，只是 开发者换了而已。而且开发不是在默认的 branch 里面开发，一般人看不出来而已。

**Comment by jang-u** [comment]
还有shadowsocks-rss也在，转到zeronet了

zeronet
https://zeronet.io/

shadowsocks-rss
http://127.0.0.1:43110/shadowsocksr.bit
http://127.0.0.1:43110/1GUwoyRUxHWkUik5o4BBKgjrpbeCMXFj9z/

**Comment by omixk** [comment]
从来没死过，而是百花齐放

**Comment by breakwa11** [comment]
https://github.com/shadowsocks/shadowsocks-windows/pulls?q=is%3Apr+author%3Abreakwa11+is%3Aclosed

**Comment by jasonliul** [comment]
@breakwa11 
美妞不玩了?
