### ISSUE TITLE
找不到有提交按钮ip.html打开方式

### ISSUE THREAD

**Issue by liweitd** [phuslu/goproxy#1176]
求助，如题！
谢谢

**Comment by wgf0330** [comment]
127.0.0.1:8087

**Comment by liweitd** [comment]
![index of](https://cloud.githubusercontent.com/assets/9819045/18738441/606e02c0-80ce-11e6-9b4e-db2d9e1231af.png)

**Comment by liweitd** [comment]
打开后如上图

**Comment by MeABc** [comment]
![image](https://cloud.githubusercontent.com/assets/18194126/18738477/b515ddde-80ce-11e6-94a7-811fc4e16b4f.png)

你是不是有自定义的 autoproxy.user.json  ，版本更新了，请确认 autoproxy.user.json 里有图中那哪一项。

**Comment by liweitd** [comment]
对  是这个原因  谢谢 @MeABc

**Comment by MeABc** [comment]
![image](https://cloud.githubusercontent.com/assets/18194126/18738539/3cfc5610-80cf-11e6-8d82-5f6063a26d02.png)

是两项。

**Comment by liweitd** [comment]
可以了
