### ISSUE TITLE
检查ip, dns,等侧漏

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1189]
https://ipleak.net/
https://www.doileak.com/

足够用了

**Comment by wpyok500** [comment]
怎么用？

**Comment by pug908** [comment]
Mountain View

**Comment by jzp820927** [comment]
XX人士必备。

**Comment by 11ydyu** [comment]
goproxy不是说没有什么隐蔽性吗，那一定会侧漏呀。要隐蔽不是说用tor(洋葱）或者I2P（大蒜）才行。

**Comment by yuan78** [comment]
编程随想的双虚拟机玩法，那才叫折腾，没试过，太麻烦。真正的匿名是做git push/git clone/git pull等git操作时，都查不到跟脚，那才是真正意义上的匿名

**Comment by jasonliul** [comment]
https://whoer.net/

这个更好玩

**Comment by jzp820927** [comment]
看样子 J 大对匿名研究的很透彻啊

**Comment by blob2015** [comment]
:beers:
