### ISSUE TITLE
道教VPN Taoist VPN

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1194]
Taoist VPN
http://smartpcsoft.com/taoist-vpn.html

System Requirements
Microsoft .NET Framework 4 client profile.

Taoist VPN 4.000
http://smartpcsoft.com/downloads/taoist-vpn/taoist_vpn.exe

免费, 美英加若干服务器

**Comment by samtone** [comment]
速度如何，有时间限制吗？？

**Comment by panpeach** [comment]
内置的13个服务器一个都连不上。

**Comment by jasonliul** [comment]
@panpeach 

Bug Report
Contact@smartpcsoft.com

support ticket
http://smartpcsoft.com/support-ticket.html

只是一家埃及的小公司, 可能是被猎杀.
