### ISSUE TITLE
关于govps server端的配置语法

### ISSUE THREAD

**Issue by yuan78** [phuslu/goproxy#1198]
关于govps server端的配置语法有以下几个问题：
1.  运行./goproxy-vps -h, 居然没有帮助信息，直接监听到了443端口，有没有json的配置范例？
2. 能否不在启用TLS的情况下建立通讯隧道？ 也就是说不使用TLS的cert和key，而是使用encrypt的预设置的key密码建立通讯隧道。
3. 监听端口能否不设置成443，改成其他自定义端口是否可以 ？

THX！

**Comment by MeABc** [comment]
![image](https://cloud.githubusercontent.com/assets/18194126/18939345/399e80fc-8632-11e6-8f0b-39d33d1b4da6.png)

**Comment by yuan78** [comment]
本人最烦那种不懂装懂，自以为是，其实不懂又喜欢乱回复的人。
问题要是简单到能够搜索issue历史就能解答的问题，你以为我还会在这里发issue?
我还是那句话; 不懂的人，就不要这里乱回复！

**Comment by MeABc** [comment]
我错了。

**Comment by hexianfu** [comment]
看你这个人，呵呵...我想知道的也不会回复你

**Comment by yuan78** [comment]
看看你们这样的心胸，自私自利，严重的小市民意识，难怪被共匪奴役这么久，我只能说活该！

知道的不会回复我？笑话？！你以为我真的不会用，真的不懂吗？！我只是想把问题拿出来给有识之士讨论一下而已，没想到却引出来一些被共匪洗脑洗坏的跳梁小丑！。
