### ISSUE TITLE
大家别忘了另外一个阵地哦。

### ISSUE THREAD

**Issue by yeahwu** [phuslu/goproxy#120]
xx大神在维护吧。
https://groups.google.com/forum/#!forum/fqlt

**Comment by aOJzQT** [comment]
没有忘 但group太难用了 怀念code

**Comment by keeno1982** [comment]
Group真的没法看，Google+估计也快关了

**Comment by ARwMq9b6** [comment]
不懂为啥弄那么多 JS 脚本，卡死了。

**Comment by aOJzQT** [comment]
@ARwMq9b6 卡成狗而且回复看起来乱糟糟的

**Comment by yeahwu** [comment]
卡是真的，其他的适应一段时间，还好啦。

**Comment by lefantian** [comment]
分散也有好处，两个都关注

**Comment by aOJzQT** [comment]
@lefantian never put all your eggs in one basket

**Comment by RedfrogismySon** [comment]
xx内蹄在召唤大伙
![19](https://cloud.githubusercontent.com/assets/14001050/9530171/d01508a8-4d30-11e5-92fd-bdc5f5fc3d7e.gif)
