### ISSUE TITLE
有些网站视频播放不了

### ISSUE THREAD

**Issue by playnetcn** [phuslu/goproxy#1203]
我使用的firefox 49,登陆有些视频网站，视频播放一半就停止了，有的视频缓冲一半就停止了。目前使用的版本是r1085，以前的版本对下面的视频网站也不支持。
播放几秒就停止了
http://www.rfa.org/mandarin/video?v=1_dwy0a8fs
以下为成人视频，缓冲不完整
http://my.tokyo-hot.com/product/n1185/
http://www.km-produce.com/movie/
(注：脸书的短视频也有问题，播放一会就断了，不完整，请@phuslu看看）

**Comment by jzp820927** [comment]
应该是 autorange 还没完善造成的吧

**Comment by blob2015** [comment]
@playnetcn 
建议：你下载个别人的修改继承版本，比如pcx，比如阳光盒子。你试试看，是不是播放就完整了。
FF的视频播放问题，有时候是自己问题。

---------------

成人视频，就不测试了。之前俺也有类似问题，升级到49就没问题了。
关于替俺们操心了心的rfa（已关闭默认的php指向），俺这边的错误提示：
```
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1070 (go/devel +1155c6c Fri Sep 23 13:09:41 2016 +0000 windows/386)",
    "filter": "*autoproxy.Filter",
    "error": "malformed HTTP status code "html>""
}
```
