### ISSUE TITLE
反监视 Detekt 2.0

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1211]
大赦国际, EFF, 数字化社会, 国际隐私几大组织出资赞助

下载
https://github.com/botherder/detekt/releases

虽然通常是人权活动者, 或者记者用.

但是谁都可以玩玩, 目前反间谍软件的一哥

**Comment by distance00** [comment]
mark下，不知道是不是驱动级的。

**Comment by jasonliul** [comment]
@distance00 
那是天朝特色. :)

**Comment by distance00** [comment]
确实被滥用了，不过有的木马病毒都是驱动级的，还有的拒绝在沙盘运行，如果是小众不被针对应该还是很有效果的。
很有趣的事，FBI的头儿Facebook的创始人都把自己的摄像头用胶布粘起来了。
https://www.youtube.com/watch?v=1MV3ZlazAlA
