### ISSUE TITLE
APPID每日流量是不是更少了

### ISSUE THREAD

**Issue by p1956** [phuslu/goproxy#1213]
连续两天出现了很快没有流量的错误，没怎么下载，有40多个appid，确定没有被盗用
以前从来没有发生过，也

**Comment by distance00** [comment]
可能是分钟流量，带宽在不断增加，视频清晰度在不断提高，这个问题会越来越突出。不如over quota也在服务端重试？

**Comment by p1956** [comment]
不是，基本可以确定是完全没有流量了

**Comment by distance00** [comment]
你怎么确实没有被盗用？40g的流量，就算你每分钟都满quota，连续24小时都用不完。

**Comment by p1956** [comment]
因为是不同的账号的appid，同时全部被盗的可能性非常非常小。我现在只是确认是不是自己哪里出问题了，还是谷歌改政策了，目前来看可能是我自己的问题，不过没有发现是怎么造成的，因为我基本没有下载什么。还有就是计流是有很大bug的，下载东西有时同时下一堆，40g流量很快用完了，一个个下载要好点。还有就是下超大文件（5gb以上），流量也很快会没，而且这个我认识的人也跟我说过发生过（25个appid）。都是用的idm下载

**Comment by phuslu** [comment]
用的是 go 版的服务端吗？

**Comment by p1956** [comment]
不是go版

**Comment by phuslu** [comment]
那基本不是 goproxy 的问题了
