### ISSUE TITLE
设置IE代理无法使用

### ISSUE THREAD

**Issue by LawrencePage** [phuslu/goproxy#1220]
版本:Goproxy 1092
系统:Win10 14936
问题:右下角通知栏图标右键goproxy设置IE代理127.0.0.1:8087,选择之后毫无反应,之前都可以开这个用Google Earth , 是电脑系统对goproxy作了限制么?

**Comment by jzp820927** [comment]
可以手动检查下，系统代理，是否设置成功

**Comment by xSancy** [comment]
Win10 14936和1492在右下角通知栏图标右键goproxy都无法设置IE代理的，应该是该版本win10系统的原因。只能手动去设置-网络和internet-代理 里填写

**Comment by jzp820927** [comment]
目前 win10 问题挺多，系统问题没有办法

**Comment by LawrencePage** [comment]
@xSancy  手动设置有效,谢谢了.  问题已解决. @phuslu
