### ISSUE TITLE
为什么所有的版本都会出这种问题

### ISSUE THREAD

**Issue by p1956** [phuslu/goproxy#1228]
从gae用到gop，所有的版本都会用久了就出黄字，网页载入不了，重新启动就可以了，反正一天总有几次，如果是在看视频什么的就更严重。用了好几年了，也换过电脑，换过网络，这个问题一直存在。虽然不是什么大问题，但对我来说还是挺严重的，因为有时候要下载那种直播视频，网络要一直保持稳定才能完美下载。

这个问题是无解的么？

**Comment by jzp820927** [comment]
会不会是 IP 问题

**Comment by p1956** [comment]
应该不是ip问题。我现在同时在用gae和goa，goa比较容易出现，gae很少

**Comment by jzp820927** [comment]
那就只能等 P 大处理了。

**Comment by blob2015** [comment]
是不是说over……然后显示retry？

**Comment by jzp820927** [comment]
没这么夸张吧，用一下，appid 就超额了。

**Comment by phuslu** [comment]
升级服务端
