### ISSUE TITLE
https://play.golang.org Forbidden 403 google限制？

### ISSUE THREAD

**Issue by johnsonz** [phuslu/goproxy#1232]
日志：
`I1018 11:16:25.365721    8540 gae.go:557] 127.0.0.1:14283 "GAE FETCH GET https://play.golang.org/p/34HgBb_OhZ HTTP/1.1" 403 30`

**Comment by jasonliul** [comment]
正常

**Comment by jzp820927** [comment]
正常

**Comment by johnsonz** [comment]
你们都是正常的？？
![untitled](https://cloud.githubusercontent.com/assets/2533629/19470320/990bd480-9551-11e6-864e-e034bc9e667d.png)

**Comment by jzp820927** [comment]
额，刚刚是 hosts 直连的，没注意，用 gop 确实不行，也是 Forbidden

**Comment by LGA1150** [comment]
https://www.v2ex.com/t/313687

**Comment by jzp820927** [comment]
想不到，google 也会封锁。而且又不是什么很特殊的内容，想不到，封锁的理由是什么。

**Comment by johnsonz** [comment]
https://github.com/golang/go/issues/12908

GFC==Google Friend Connect

But in order for that to happen, we are required to ensure that we do not permit the *.golang.org sites to be used for creating User Generated Content by Chinese internet users in accordance with those laws.
