### ISSUE TITLE
"error": "dial tcp 216.58.201.165:443: i/o timeout"

### ISSUE THREAD

**Issue by piaoyun** [phuslu/goproxy#1248]
**# 自己SB了。修改了gae.user.json中间的user为其他名字。难怪一直连接不上。现在好了。
真是太SB了。**

但是检查。发现配置文件里面是没有这个IP的。

还是显示无法连接呢。版本见下图
![qq 20161031193318](https://cloud.githubusercontent.com/assets/3724475/19852875/e6bd22e8-9fa0-11e6-863b-f8a55e0b5179.png)

**Comment by fengixng** [comment]
你需要填入自己扫描到的IP，否则人无法使用

**Comment by 171563857** [comment]
@fengixng 有添加ip,但是还是没法用

**Comment by piaoyun** [comment]
@fengixng 有扫描添加进去的IP。就是出现超时。添加的IP没有上面出错的IP在内呢

**Comment by Alvin9999** [comment]
格式对不对？ip的格式对吗？

**Comment by jzp820927** [comment]
仔细检查IP，剔除掉不可用的IP
