### ISSUE TITLE
一上GOOGLE系列网站就自动跳到https://github.com/_gh/？

### ISSUE THREAD

**Issue by IRISlMaple** [phuslu/goproxy#1254]
请问这是什么鬼~~~
包括YOUTUBE
![yy 20161102220432](https://cloud.githubusercontent.com/assets/22773754/19931681/62ee023a-a148-11e6-926b-b8d6ce317537.png)

**Comment by IRISlMaple** [comment]
忽然好了·~~

**Comment by phuslu** [comment]
ip 问题
