### ISSUE TITLE
xx-net和goproxy哪个快一点啊，共用xx-net的服务端会影响gop的速度吗？

### ISSUE THREAD

**Issue by Limsig** [phuslu/goproxy#1256]
不知道为什么，xx-net在单位用着很流畅，但回家里看视频就很卡。今天刚发现原来GoAgent已经成goproxy了，然后试了试，服务端还是用的xx-net的，看视频还是比较卡。请问，如果服务端换成gop的后速度会有较大的提升吗？

**Comment by oceanvia** [comment]
最好分开用，社长不是说了两者不兼容

**Comment by jzp820927** [comment]
服务端影响很小，IP 才是最主要影响速度的因素。
goproxy 没有 XX 的自动扫描，要自己手动找IP。

**Comment by wenliyang** [comment]
goproxy 的服务端和客户端配合使用，才能得到最好的效果

**Comment by Limsig** [comment]
到底应该听谁的啊，我也是看到有帖子说xx的服务端兼容gop，gop不兼容xx，所以就没更新服务端……

**Comment by jzp820927** [comment]
这么说吧，如果你是用的 XXNET，那么你只能用 XX 的服务端。
如果你是用的 goproxy ，那么你可以用 goproxy 的服务端，也可以用 XXNET 的服务端，不过用 goproxy 的服务端性能更好。

**Comment by Limsig** [comment]
谢谢各位，最后再问一句，如果改用gop的服务端，gop的性能会有较明显的提升吗？

**Comment by SeaHOH** [comment]
第一看 IP，第二就是服务端了。
go 效率较高，虽说你可能感觉不到。

**Comment by wenliyang** [comment]
@Limsig 看作者的说明

https://github.com/phuslu/goproxy/issues/973#issuecomment-234178172

**Comment by TangBaohua** [comment]
我总觉得goproxy 好用多了

**Comment by needfreedom** [comment]
"单位用着很流畅，但回家里看视频就很卡"是因为各自网络环境不同。不同的ISP服务商，及不同的网络使用环境出口能力完全不同，你单位的可能好一些。

**Comment by jzp820927** [comment]
单位的是商用网络，可能要好些吧

**Comment by Limsig** [comment]
谢谢各位，也就最近这两天晚上在家根本没法看视频，之前也就是慢一点。我开始还以为是因为家里电脑用的少，ip不够好，我专门把在单位扫的ip拷到家里的电脑，看视频还是巨卡，刚部署服务端一晚上了，总是报错，我另起一个帖子，还请大家指教啊……

**Comment by jzp820927** [comment]
既然你单位的网络比较好，你可以把XX在单位电脑运行，共享给家里用

**Comment by Limsig** [comment]
还可以这样？！怎么操作呢？

**Comment by jzp820927** [comment]
需要把你的 XX 监听者单位的外网IP上，然后家里用单位的外网IP，和 8087 端口就可以了。

**Comment by Limsig** [comment]
今天在家，感觉白天的时候xx-net还很流畅，一到晚上就巨卡，我想试试自己搜索，测试ip，有什么比较好用的软件吗？问题比较小白，谢谢大家啊……

**Comment by needfreedom** [comment]
说点题外话，算是建议。“一到晚上就巨卡”的问题，与 IP 应该无关。
不知你晚上有没有测过本地网速，如晚间与白天比较本地网速无大的变化，你可尝试使用前置加以改善网速，换 IP 应无多大效果 。如晚间与白天比较本地网速本身就不行，则无解。

**Comment by jasonliul** [comment]
@needfreedom 
是这样, 有些美剧组声明上传会在夤夜, 因为晚间巨慢.

晚间百毒盘也只能使用前置, 可以满速

**Comment by jzp820927** [comment]
这段时间晚间掉包厉害，使用速度较慢，和 IP 无关，只能等情况好转 了

**Comment by Limsig** [comment]
@needfreedom 测过网速的，晚上瞬时网速测试接近5mb，应该不是网的问题。前置是啥啊……如何操作呢？不论是不是ip的问题，就当是学习了。主要是edx上的视频不翻墙根本没法看，这几天的学习进度大受影响……

**Comment by needfreedom** [comment]
为了学习，一定要支持！
说到“前置”使用，@jasonliul 才是大行家。现将jasonliul兄的老贴奉上：
https://github.com/phuslu/goproxy/issues/373
望你仔细阅读。为了保障学习，建议你先不要拘泥GOPROXY了,赶快改变翻墙姿态。

如你坚持使用GOPROXY，现提供SOCKS4一枚帮你救急：120.234.15.130:1080，具体使用时需要你下载Proxifier或者其它帽架 [自选一种即可]，用法可见proxifier用法系列教程：
https://gochrome.info/tag/proxifier-series/

如选其它帽架，可google学习，都很容易学用。

祝你学习愉快！

**Comment by jasonliul** [comment]
@needfreedom 

客气了, 俺经常在网路满世界流浪, 玩得早一些.
袜子代理整个亚洲都使用得很少, 很多人误以为是高手黑客的玩意.

近两年国外代理商投资亚洲节点, 增长很快, 数目质量提高不小.

简单说,袜子就是专用快递通道. 经常吹嘘的游戏加速器,很多就是袜子代理.
对付网络不稳定, 或者距离遥远, 袜子能够起到作用.

**Comment by jzp820927** [comment]
edx 是啥，求科普

**Comment by Limsig** [comment]
哇！感动啊，感谢支持！@needfreedom

好的，我试试！@jasonliul

edX是由MIT和Harvard创办的在线课程学习平台，上面有许多世界名校提供的免费大学课程和相应练习。类似的平台还有Coursera，Udacity，MIT OCW等。@jzp820927

**Comment by Limsig** [comment]
@needfreedom 
嗨，关于前置的那个帖子我看了，感觉就是推荐了一堆软件啊……具体怎么操作，小白表示完全摸不着头脑啊，也搜了下看有没有相关的教程，弄了一晚上也还是没啥结果。希望能有更具体的教程啊……

我现在对前置的理解是，再转一道弯，通过一个代理去访问另一个代理再访问目标网站，对不？如果是这样我有疑问啊，稳定前置代理好找吗？需要付费吗……

**Comment by jasonliul** [comment]
@Limsig 
试试Sockscap64, 比较简单.
另外两个功能强大, 但是复杂不少

**Comment by jzp820927** [comment]
直接在浏览器设置就行了吧，用不着软件吧，又不是软件客户端

**Comment by Limsig** [comment]
我大概懂了，是在这里填对不

**Comment by Limsig** [comment]
我大概懂了，到这里设置一下就可以了对不
![qq 20161107101539](https://cloud.githubusercontent.com/assets/22915681/20044391/7e946144-a4d3-11e6-8a0d-71d2b731fa5b.jpg)

**Comment by jzp820927** [comment]
额，你是用的 XX-NET 啊，怎么跑这儿来发 issues 了

**Comment by needfreedom** [comment]
@Limsig 
如果你要用"GOPROXY"，建议用jasonliul 兄推荐的Sockscap64, 比较简单.Sockscap64教程;
http://hotss.xyz/229/
注意：
文中第三步 “3、点击代理管理器，点左下角那个小小的加号添加代理服务器 – 在代理地址输入127.0.0.1，端口1080”，这里你需要将127.0.0.1替换为上面提供的S4的IP：120.234.15.130或61.141.21.34或218.75.41.134 等等，端口1080；
按照文中第4步、将goproxy.exe拖拽到sockscap64的界面，然后双击运行即可。注意，此时goproxy的IP选用你日常可用IP即可 。

**Comment by jasonliul** [comment]
Goproxy 自身支持前置
gae.json
`"Proxy": {
"Enabled": true,
"URL": "socks5://114.55.33.237:1080",`

问题在于袜5节点是针对企业用户的, 通常连接速度反而不如袜4, 针对个人用户.
而且袜4节点如果有防ping保护, 隐匿性会比袜5更好.

俺提供一枚杭州的
114.55.33.237:1080

**Comment by jasonliul** [comment]
俺说点亚洲免费袜子代理的历史.

亚洲原本只有印尼, 俄国远东有一些免费袜子, 作为国际网络中转服务.

这几年全球狂修破墙, 亚洲很多国家都有了网络审查, 人权达人们最先是支持洋葱的, 近两年改为支持免费袜子代理. 

操作方还是那些提供廉价袜子服务的商家, 通常几个美金每月. 他们收集架设全球节点, 通常是>5000节点, 包括袜5,袜4, http, https,squid, 然后全天滚动检查, 随时提供十几枚可用的高速节点给付费用户.

但是有了赞助, 这些商家提供的亚洲袜子节点, 是半免费性质, 以前的袜子代理, 存活期很短带宽也小. 不过现在的亚洲代理, 动辄全天在线, 存活一两个月, 而且是仅限亚洲才有这类长效节点.

有了袜子前置, 没有翻墙工具会死的, 这才是真正有帮助.

有趣的是, 印尼翻墙同志[印尼墙社交网络, 视频网站]也不用袜子, 俺和他们聊起, 他们的高手才做了一些整合工具, 袜子+SSH或者赛风, 
自动搜索袜子, 测试带宽排序, 也可以自动切换袜子前置.
有了这种装备, 中国的破墙也是个屁.

中国没有那么多免费袜子, 但是找到几条, 所有的翻墙工具都是不死鸟.

**Comment by Limsig** [comment]
谢谢大家！晚上回来试了，袜子有效！耽搁了好几天，都是泪，终于不卡了！

我还有些疑问啊：怎么找免费又比较好用的袜子呢，是在Google上搜吗？我搜了下，试了几个，都连不上……

再就是jasonliul兄的帖子里推荐了tor，赛风（昨晚试了，好卡……）什么的，这些加了前置后速度也会彪起来吗？

@jzp820927 
edX最近是推出一些必须付费的课程，但大部分的课程如果你不要证书，只是旁听，都是免费的，旁听除了没证书，其他功能全都不受影响。

**Comment by dreamidiot** [comment]
@jasonliul @needfreedom 
感谢2位大神耐心详细的解答，和 @Limsig  的抛砖引玉！这个帖子让我受益不浅！终于知道那个老帖是讲什么的了~以及前置如何操作。。。但小白还有些困惑不明白，想问一下，各位见笑了！

1. 大神说“袜子就是专用快递通道”，那这个通道是不是直接通到墙外的？是不是用了socks后就不需要ip了，直接能翻？我用GoProxy：不用前置时，有一行绿字显示good_addrs多少bad_addrs多少；不用前置时，就没有这些绿字，基本上都是白字，偶尔黄字。是不是说明socks直通墙外，没有谷歌ip也行？

2. 有时候我用socks，速度有很大提升。但有时候用了速度反而卡了，还不如不用（可能是我socks找的不好）。我看论坛上很多大神都说socks能抗干扰，有加速的功能。有人能通俗易懂的讲下原因吗？为什么当goproxy或者xxnet用起来不顺的时候（就是当谷歌ip遭严重干扰，比如最近这段时间），socks却能躲过，有时候效果还不错？

3. 除了谷歌搜索外，如外查找socks？有没有一些特定的工具来搜索？像搜索谷歌ip那样的工具？

4. 获得了一些socks后，怎么判断哪些socks比较好，哪些比较差？谷歌ip可以从延时，丢包率来看，那socks怎么判断呢？

5. 从网上找的socks，端口除了1080外，还有其他各种奇奇怪怪的端口，这些有区别吗？用网上找来的socks来登陆邮箱、账号什么的安全吗？

小白的提问比较多，刚接触前置，各位见笑了！谢谢！

PS：
@Limsig  edx这网站不错，收下了！课程视频居然还有字幕，而且还可以自动翻译成中文，厉害了！
@jzp820927 你点右下方的audit this course就免费了，除了没有证书，其它什么资料都有

**Comment by dreamidiot** [comment]
@jasonliul @needfreedom 
感谢2位大神耐心详细的解答，和 @Limsig  的抛砖引玉！这个帖子让我受益不浅！终于知道那个老帖是讲什么的了~以及前置如何操作。。。但小白还有些困惑不明白，想问一下，各位见笑了！

1. 大神说“袜子就是专用快递通道”，那这个通道是不是直接通到墙外的？是不是用了socks后就不需要ip了，直接能翻？我用GoProxy：不用前置时，有一行绿字显示good_addrs多少bad_addrs多少；不用前置时，就没有这些绿字，基本上都是白字，偶尔黄字。是不是说明socks直通墙外，没有谷歌ip也行？

2. 有时候我用socks，速度有很大提升。但有时候用了速度反而卡了，还不如不用（可能是我socks找的不好）。我看论坛上很多大神都说socks能抗干扰，有加速的功能。有人能通俗易懂的讲下原因吗？为什么当goproxy或者xxnet用起来不顺的时候（就是当谷歌ip遭严重干扰，比如最近这段时间），socks却能躲过，有时候效果还不错？

3. 除了谷歌搜索外，如外查找socks？有没有一些特定的工具来搜索？像搜索谷歌ip那样的工具？

4. 获得了一些socks后，怎么判断哪些socks比较好，哪些比较差？谷歌ip可以从延时，丢包率来看，那socks怎么判断呢？

5. 从网上找的socks，端口除了1080外，还有其他各种奇奇怪怪的端口，这些有区别吗？用网上找来的socks来登陆邮箱、账号什么的安全吗？

小白的提问比较多，刚接触前置，各位见笑了！谢谢！

PS：
@Limsig  edx这网站不错，收下了！课程视频居然还有字幕，而且还可以自动翻译成中文，厉害了！
@jzp820927 你点右下方的audit this course就免费了，除了没有证书，其它什么资料都有

**Comment by dreamidiot** [comment]
不知道为啥发了2遍，抱歉

**Comment by needfreedom** [comment]
@dreamidiot 
依据个人体验，对应回答如下：
1，这个通道是代理的代理，不一定是直接通到墙外的。有的是，有的不是。直通的少。直通的就不需要填写ip了，即不必更改goproxy的原始链接模式。用GoProxy时如直接通过设置更改使用前置（当然此时应是“直通的”那种），它将直连你的应用，不走IP，故没有“good_addrs多少bad_addrs多少”。换句话说，有直通墙外前置代理时，没有谷歌ip也行。
2，用不用代理要依据自身情形来定。谷歌ip遭严重干扰socks能否躲过，要看代理的能力了，有的国货可直接穿墙，大多不能。但境外代理已在墙外，自然所谓“能抗干扰”，你懂。
3，特定的工具有，但实践中个人感觉效果不佳。个人经验不必贪婪大篇幅去找。GOOGLE一下即可。
4，还是那句话，不贪，不懒。实践一下。不靠工具。有的代理工具测试蛮好，用起来笨的很。你得靠实践来验证。
5，安全问题，个人理解互联网没有绝对安全可言，相对而已。

**Comment by jasonliul** [comment]
Gptool破解能够自动下载代理列表.

但是好的前置还是要多搜寻, 因为通常的袜子测试, 基于美国, 或者莫斯科.
因此亚洲基本是盲区, 他们收录得很少

**Comment by CHN008** [comment]
也准备把GoProxy用起来试试.

**Comment by jzp820927** [comment]
@dreamidiot 还真没发现哪儿有 audit this course，只有个 enroll now ，要不你发给免费的给我看看》

**Comment by Limsig** [comment]
@jzp820927 
enroll之后才能看到audit的选项

**Comment by dreamidiot** [comment]
@needfreedom @jasonliul 感谢大神的解答，受教了，又学会了一种技能！
@jzp820927 嗯，点enroll之后就能看到了。比如随便点一门电路课
![1](https://cloud.githubusercontent.com/assets/14074969/20083157/a3aab4ca-a595-11e6-9f58-558ee80065d1.JPG)
点enroll now
![2](https://cloud.githubusercontent.com/assets/14074969/20083162/a9359040-a595-11e6-81dc-204b5810e5fa.JPG)
点audit
![3](https://cloud.githubusercontent.com/assets/14074969/20083166/af3b4f7a-a595-11e6-99e5-9ad2beadf63c.JPG)
就有了

**Comment by jzp820927** [comment]
恩，刚刚看了下，好像视频是引用的 ytb 的视频。

**Comment by jasonliul** [comment]
@dreamidiot 
赞!

**Comment by Pekary** [comment]
看了这里的讨论，感觉socks好像很有意思，自己试了试，用的sockscap64 加速迅雷的下载，找的socks测试速度在40ms左右，但是下载没有速度，有没有大大能解释一下？

**Comment by needfreedom** [comment]
抱歉，没有做过加速迅雷的尝试。
"socks测试速度在40ms"你指的应该是PING值，它与下载速度无关。
经验告诉我，选socks不能用PING值选。这点与选GOOGLE 的ip时很相似。
但因目前没有好的工具推荐给你，只能鼓励你手工尝试。

**Comment by Pekary** [comment]
所以百度云、游戏之类的加速也是靠选到合适的ip么？

**Comment by needfreedom** [comment]
是的。
socks不具有普适性。A用户用的好，B用户甚至有可能根本用不了。

**Comment by Pekary** [comment]
好的，谢谢解答～

**Comment by jasonliul** [comment]
@Pekary 
Sockcap64  包纳子进程的能力不强, 渣雷有许多子进程.
实际上只有一部分经过袜子.

百度云客户是可以的. 速度奇慢的时候,可以加挂中国ip的袜子, 通常能够满速, 只是速度爬升得比较慢
