### ISSUE TITLE
很久没更新goproxy了，更新之后发现启动变慢

### ISSUE THREAD

**Issue by ydq** [phuslu/goproxy#1258]
之前一直是使用的 1000版本（比较喜欢整数）
然后今天没事更新一下GoProxy，突然来了个惊喜，支持Retina屏了。

但是也有点失望，就是启动速度比旧版慢上很多，**双击启动后至少有个两三秒才弹出通知并启动**，旧版（1000）基本上点击后是秒开的。

<img width="550" alt="goproxy" src="https://cloud.githubusercontent.com/assets/8097340/19968284/e3abffe6-a20e-11e6-8776-70133348cba6.png">

还有就是上图的，每次界面顶部的日志信息都是错乱的，前面还有一点不知道是乱码还是什么的，麻烦社长能改改么。看着简直蓝瘦香菇😭

还有一个就是**MacOS的版本的通知，历史通知不会自动删除**。

推荐做如下修改，这样在通知栏不会一直重复出现很多的通知记录，点击弹出的通知也能自动删除通知：

```shell
    def notify(self):
        from Foundation import NSUserNotification, NSUserNotificationCenter
        usernotifycenter = NSUserNotificationCenter.defaultUserNotificationCenter()
        notification = NSUserNotification.alloc().init()
        notification.setTitle_("GoProxy macOS Started.")
        notification.setSubtitle_("")
        notification.setInformativeText_("")
        notification.setSoundName_("NSUserNotificationDefaultSoundName")
        notification.setContentImage_(self.image)
        usernotifycenter.removeAllDeliveredNotifications()
        usernotifycenter.setDelegate_(self)
        usernotifycenter.scheduleNotification_(notification)

    def userNotificationCenter_didActivateNotification_(self, center, notification):
        from Foundation import NSUserNotification, NSUserNotificationCenter
        NSUserNotificationCenter.defaultUserNotificationCenter().removeAllDeliveredNotifications()
```

**Comment by jzp820927** [comment]
看来又是一个强迫症患者。

**Comment by blob2015** [comment]
@jzp820927 
而且是重度患者

**Comment by blob2015** [comment]
@jzp820927 
而且是重度患者

**Comment by phuslu** [comment]
谢谢。已经加入kanban

https://github.com/phuslu/goproxy/projects/1#card-685797

**Comment by phuslu** [comment]
r1238 已经修复，

**Comment by ydq** [comment]
@phuslu 今天升级了一下，速度确实秒开，感谢社长发威。
但当前版本（1255 Mac）点击通知后，gp在状态栏的图标会消失，但是进程还在

**Comment by blob2015** [comment]
最近社长在大力整理mac版本

**Comment by ydq** [comment]
@blob2015 @phuslu 感谢社长，1258 bug修复，使用已经堪称完美了，秒速的启动，而且社长还添加了app版本可以股东到dock栏，社长威武~~
