### ISSUE TITLE
php fetcherserver 部署到heroku没法用

### ISSUE THREAD

**Issue by mountainguan** [phuslu/goproxy#126]
我直接用https://github.com/phuslu/fetchserver/tree/golang 部署，结果返回的提示如下：

There is no app configured at that hostname.
Perhaps the app owner has renamed it, or you mistyped the URL.

**Comment by erichau** [comment]
可以用的，把地址填到php里就可以了

**Comment by mountainguan** [comment]
@erichau 填进去以后提示 net/http: TLS handshake timeout

**Comment by erichau** [comment]
你选的美国还是欧洲，我部署的时候试过欧洲的用不了，美国的没问题，不过电信用这个只能看看网页，很慢的

**Comment by mountainguan** [comment]
@erichau  欧洲的，能用，一开始貌似是我自己配置文件没弄好，现在可以用了。那你有没有什么好的介绍，扫ip可以看1080p视频…可是特别累，有没有什么好的加速方法，可以相对一劳永逸的，经常扫ip会得病的。

**Comment by ARwMq9b6** [comment]
XX-Net 自动扫 IP, 动态更换可用 IP 库 。 https://github.com/xx-net/xx-net

**Comment by mountainguan** [comment]
@ARwMq9b6 动态ip库在哪里

**Comment by ARwMq9b6** [comment]
@mountainguan https://github.com/XX-net/XX-Net/blob/master/gae_proxy/local/ip_range.txt
