### ISSUE TITLE
PingInfoView v1.55 老将出马

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1261]
PingInfoView v1.55 老将出马
http://www.nirsoft.net/utils/multiple_ping_tool.html

近期测狗工具相当有问题...

老把戏未必过时, 先用Gogotest或Ipscan筛选合格ip.
然后还是老把戏, PingInfoView, 

选择响应最快,ping成功率100%的那些.

**遵社长钧旨, 尽量多放一些IP.**

**Comment by SeaHOH** [comment]
100% 不丢估计少的可怜。我这调整参数正在测试，从昨晚到现在，几千 IP 就没不丢的，只有不到十个比较坚挺丢的少。

**Comment by jzp820927** [comment]
很多 IP 443 通，但是不一定能 ping 通

**Comment by dannymtseng** [comment]
怎么把gogotester的IP格式转成pinginfoview呢？

**Comment by jzp820927** [comment]
pinginfoview 是什么格式？

**Comment by jasonliul** [comment]
@dannymtseng 

一般文本工具都行, 搜索"|", 替换逗号","

**Comment by jasonliul** [comment]
@jzp820927 
延时越低的IP，还丢的越猛

是这样

**Comment by dannymtseng** [comment]
谢谢，测了，还象也是不准。

**Comment by dannymtseng** [comment]
谢谢，测了，还象也是不准。

**Comment by dannymtseng** [comment]
谢谢，测了，还象也是不准。

**Comment by dannymtseng** [comment]
谢谢，测了，还象也是不准。

**Comment by jasonliul** [comment]
@dannymtseng 

萎光症晚期...:) 资源干扰还在, 没有国外ip是可靠的, 不管是否Gip.
狗鞭会自行调整.

**Comment by jzp820927** [comment]
现在基本上只能保持有 IP 数量，质量基本上保证不了了。

**Comment by dannymtseng** [comment]
几组日韩IP早上时段用GOAGENT和GOPROXY稍微缓冲都能跑2k视频，但同一IP段里IP有轮番失效的现象，经验是多放些同一IP段的IP，哪怕暂时失效，稍后又能用了。

**Comment by jasonliul** [comment]
@jzp820927 

U+袜子是最稳定的方式之一, 俺现在加一条香港袜子, 是半速.
问题不在于速度, 而是不时会根本断连.

狗鞭也不可能更好, 唯一重要的是, 能够连接的情形, 确保满速下载.

**Comment by blob2015** [comment]
@SeaHOH 
在调整checkip了吗？
昨晚刷了好些个ip，但是发现还是差不多，看来只能暂时保有ip存量了？

**Comment by jasonliul** [comment]
@blob2015 

疑似天朝在大规模测试某种过滤器...
现在国内网站直连, 都会不是断掉, 与狗鞭无关

**Comment by SeaHOH** [comment]
@blob2015 
调我的新玩具。
刚测试了一个 1080P 视频，4分9秒119MB，播放前缓冲10秒，除2分半时顿了3下，一直流畅，下载播放速度基本持平。

**Comment by jasonliul** [comment]
今天百毒云又抽风, 不过所谓的破解失效并不存在.
俺下载到1/5, 那些会员广告才跳出来.

**Comment by sishentibu** [comment]
找不到那么多ping通100%的了

**Comment by jzp820927** [comment]
疑似天朝在大规模测试某种过滤器...
看来又要有大动作了。

**Comment by blob2015** [comment]
@jasonliul 
看来总是不时来折腾一番 :grinning: 
@SeaHOH 
大海兄强大啊 :grinning:

**Comment by jasonliul** [comment]
@blob2015 
俺其实有一种奇怪的想法, 貌似现在网络改得像烟草.
也就是各省各服务商,山头更独立, 

因此大家都努力拖用户后腿. 路桥费暴增, 搞得不要说国外, 就是跨省访问网络, 看来也变成了跳墙

**Comment by phuslu** [comment]
和楼上有同感。

**Comment by SeaHOH** [comment]
B站经常没速度

**Comment by jasonliul** [comment]
@SeaHOH 

何止, 俺选国内服务器校时, 除了夤夜, 其他时候都是"偶尔通", 
Ping值30几ms, 也很稳定.

**Comment by SeaHOH** [comment]
校时放了一堆服务器，然后就不用管了。

**Comment by blob2015** [comment]
@jasonliul @phuslu 
不知道说啥好…… :beers:

**Comment by jzp820927** [comment]
意思是，以后局域网也得翻墙
