### ISSUE TITLE
如何添加ip

### ISSUE THREAD

**Issue by Limsig** [phuslu/goproxy#1263]
我想把xx-net中扫到的ip放到gop里去，应该放到哪个文件里啊？问题比较小白，还请大家指教……

**Comment by jzp820927** [comment]
http://127.0.0.1:8087/ip.html

**Comment by Limsig** [comment]
直接粘贴进去就可以了吗？也没看到保存之类的按钮……我还以为跟GoAgent一样会有个iplist之类的东西哎……

**Comment by wenliyang** [comment]
运行 goproxy 客户端，再打开2楼所贴的链接
如果没有看到“写入到本地 json 文件”这个按钮的话，楼主是否修改了 autoproxy.json 这个文件

**Comment by Limsig** [comment]
噢，我知道错在哪了，我之前直接找到文件夹里的ip.html文件加的……

**Comment by jzp820927** [comment]
直接打开 html 文件不能写入 IP，要用 url 的时候，才能写入 IP 到 json 文件。

**Comment by asd2003asd** [comment]
很好用。
