### ISSUE TITLE
项目怎么没了，还是只有我是这种情况

### ISSUE THREAD

**Issue by johnsonz** [phuslu/goproxy#1272]
![capture](https://cloud.githubusercontent.com/assets/2533629/20088064/a7e2cf28-a5b8-11e6-8717-cd380f2cda3e.PNG)

**Comment by ydq** [comment]
切换一下分支即可。

**Comment by CHN008** [comment]
一直在的,社长把它隐藏了一下,你点"Branch",选"Master"就出来了.

![fireshot capture 5 - phuslu_goproxy at master - https___github com_phuslu_goproxy_tree_master](https://cloud.githubusercontent.com/assets/16646697/20088160/5fadc7fc-a5b9-11e6-8f93-041c3902c3a0.png)

**Comment by johnsonz** [comment]
嗷，看到了，为啥新建了一个分支，看到master分支Travis CI编译失败了

**Comment by yfdyh000** [comment]
#1269

**Comment by phuslu** [comment]
Travis CI 已经修复了。
