### ISSUE TITLE
aws挂了？

### ISSUE THREAD

**Issue by lovegithu** [phuslu/goproxy#1277]
有没有发现ping aws丢包非常严重，1116版本下载直接无反应。 这是GFW在搞鬼还是阿里双11

**Comment by jzp820927** [comment]
aws 一直都是处于访问困难状态。

**Comment by lovegithu** [comment]
严重怀疑运营商的问题，刚刚下了1116，家里PC正常，办公的不行。

**Comment by jzp820927** [comment]
不是一个 ISP 么？

**Comment by TangBaohua** [comment]
@jzp820927 怎么 GoProxy的下载链接消失了？

**Comment by jzp820927** [comment]
@TangBaohua https://github.com/phuslu/goproxy-ci/releases

**Comment by TangBaohua** [comment]
@jzp820927 怎么隐藏的这么深了

**Comment by jzp820927** [comment]
一直都是这样啊，你是不是很久没下载过了？

**Comment by jzp820927** [comment]
加 ci 的是每次编译版，也就是开发版，不加 ci 的是稳定版。

**Comment by TangBaohua** [comment]
@最近一个月我下载过，但我最近几天点上面的“Code”选项卡内容都空了，以前是可以看到内容的

**Comment by jzp820927** [comment]
默认分支隐藏了，你要看源代码，切换到 master 分支就可以看到了。

**Comment by blob2015** [comment]
@jzp820927 
前几天变的啦，本来进入gp主页就有发布链接的，现在都看不到了
可能社长有什么考虑

**Comment by blob2015** [comment]
@jzp820927 @phuslu 
以前是默认进入 master
现在默认进入是orphan
是不是调了什么

**Comment by jzp820927** [comment]
默认分支从 master 改为 orphan 了，是 P 大故意隐藏的，don't panic

**Comment by szh7379** [comment]
@jzp820927 @phuslu docker启动命令用什么？arukas上面，这没必要单开一个issue，直接在这问了…… usage那个命令好像不行啊，无法启动

**Comment by jzp820927** [comment]
docker 不太熟悉，问 P大吧

**Comment by szh7379** [comment]
@phuslu 呼叫P大

**Comment by wz7465** [comment]
docker run -d -p 443:443 --restart=always --log-opt max-size=50m phuslu/goproxy-vps /opt/goproxy-vps/goproxy-vps -acmedomain=yourdomain.com

**Comment by szh7379** [comment]
yourdomain.com填什么？

**Comment by szh7379** [comment]
这个命令跟上面那个没什么区别吧，这个只是保持自启而已

**Comment by wz7465** [comment]
你自己拥有的域名啊，应该还要给该域名申请官方权威证书，具体的没用过。上面那个命令只是打开帮助文档，用完即删的

**Comment by szh7379** [comment]
不是吧。这个域名不是要部署成功后才会有吗？这个docker部署这么麻烦……

**Comment by wz7465** [comment]
这就不知道了，如果镜像是自签发证书，别人都可以用啦，如果是绑定官方证书的，那只有创建者自己用的，当然你会docker的话，可以根据他的镜像来修改。

**Comment by szh7379** [comment]
P大发布到hub上的不可能是私有的吧，搞不懂，算了

**Comment by wz7465** [comment]
域名不管部署不部署，你得先有，然后ip指向你要部署的服务器，再申请官方权威证书，流程就这样的

**Comment by wz7465** [comment]
hub上镜像私有性质是要花钱的，基本上都公有展示的

**Comment by szh7379** [comment]
试了下gsnova，很简单，我还以为直接拉取就是了呢
