### ISSUE TITLE
最近的版本经常出现内存占用超级大的情况，会占用全部内存！

### ISSUE THREAD

**Issue by inkdie** [phuslu/goproxy#1278]
问题是这样的，我的电脑几乎从来不关机，每天早上上班的时候拍一下空格，输入密码就正常使用了。

最近一个月左右，出现过几次开机后电脑特别卡的情况，查看一下任务管理器，都是内存占用99%，然后goproxy就是占用内存最多的那个，要强制结束任务才可以。

我的内存是8G，系统是win10 64bit 一周年最新版

goproxy是从今年六月底到现在一直用的get-latest-goproxy来更新的。

**Comment by phuslu** [comment]
不能复现，推测是 win 10 特定版本的问题。

**Comment by lovegithu** [comment]
@inkdie  我两台电脑都是win10 64bit一周年，一台家庭版、一台企业版，没出现你这种情况，goproxy很正常。

**Comment by johnsonz** [comment]
我这也没出现过你这种情况，我也是从不关机的，win10 Pro x64

**Comment by jzp820927** [comment]
都是土豪，你们的电，都是免费用的麽？

**Comment by johnsonz** [comment]
公司的电脑，有时候在家的时候需要远程连到公司，不能关机啊

**Comment by inkdie** [comment]
好吧，貌似最近win10 经常会出现一些因为电源管理策略引发的莫名其妙的bug，有机会我会尝试把电源策略恢复到默认状态。不过，目前还是不想让电脑彻底休眠，因为我的电脑远程网络唤醒总是失败。

**Comment by inkdie** [comment]
内存占用问题再次出现，今天早上依旧拍一下空格，打开电脑。
从输入密码的界面就开始卡的厉害，好容易进了桌面，查看任务管理器，goproxy果然是占用最高的那个，4G左右。同时伴随着1.5m/s的硬盘读写。

所以，我猜测会不会是这个原因：电源策略里，硬盘默认15分钟后关闭电源，但是电脑并未进入睡眠模式。goproxy转发的流量无处释放，然后就便秘了。。。

我不是程序员，瞎猜的，别笑话我。嘿嘿

**Comment by jzp820927** [comment]
你可以试试让电脑正常运行一晚上，不要进入任何节能模式，看会不会出现这个问题
