### ISSUE TITLE
最近频繁出现这种问题

### ISSUE THREAD

**Issue by qiangliu8183** [phuslu/goproxy#1279]
经常出现这种错误

{
    "type": "localproxy",
    "host": "[::]:8087",
    "software": "goproxy r1117 (go/devel +3b5b0a6 Wed Nov 9 02:04:12 2016 +0000 linux/amd64)",
    "filter": "*gae.Filter",
    "error": "dial tcp 8.7.198.45:443: i/o timeout"
}

我知道这是ip超时不可用，但问题是我压根就没用8.7.198.45这个ip

**Comment by phuslu** [comment]
ip 数目太少的缘故。 goproxy 在尝试完所有 gae.user.json 的 IP 后发现不能连上之后，会继续尝试 google.com 的 IP 地址。

8.7.198.45 就是当地 ISP 返回的（被污染）的 google 地址。

**Comment by qiangliu8183** [comment]
而且每次出现这种错误i/o timeout的ip都不一样，我的gae.user.json里可只填了一个ip啊

**Comment by qiangliu8183** [comment]
@phuslu 应该不是ip的问题，重启一下goproxy就正常了，同样ip在goagent上就一切正常，但是没goproxy快

**Comment by phuslu** [comment]
https://www.google.com/search?q=8.7.198.45&newwindow=1&safe=off

**Comment by jzp820927** [comment]
估计是丢包造成短暂失效，重启后刚好遇到IP恢复，所以可用？

**Comment by qiangliu8183** [comment]
@jzp820927 重启刚好遇到ip恢复？我可是每次重启goproxy都能恢复正常啊，无一例外

**Comment by qiangliu8183** [comment]
好像确实是ip的问题，之前只有一个ip，刚才又加进去2个，再看看吧

**Comment by phuslu** [comment]
现在这个干扰下，建议数百个。

**Comment by phuslu** [comment]
自动更新脚本我自测没有发现问题。

它默认是不会跟随 goproxy-ci 的。
