### ISSUE TITLE
goproxy有命令行运行即打开8087的选项吗？

### ISSUE THREAD

**Issue by qmag** [phuslu/goproxy#1282]

**Comment by jzp820927** [comment]
没看懂，你想表达什么意思。

**Comment by distance00** [comment]
自己手动建立一个快捷方式吧，输入http://127.0.0.1:8087。

**Comment by szh7379** [comment]
我猜楼主是想说xx-net那样的点击直接进入webui：127.0.0.1:8085，我理解能力还可以吧hah

**Comment by jzp820927** [comment]
目前好像没有运行自动打开浏览器的参数。可以自己写个批处理吧

**Comment by qmag** [comment]
@jzp820927 @szh7379 @distance00 @phuslu 
不是打开8087网页，是运行批处理CMD，加个参数像goproxy.exe -h，goproxy.exe -8087之类，运行就能打开右键--设置IE代理--127.0.0.1:8087那个选项。

**Comment by cnrip** [comment]
右键点图标不是能设置?

**Comment by 1688pc** [comment]
右键点击右下角任务栏goproxy图标，左键点击选择设置IE代理
