### ISSUE TITLE
怎么禁止goproxy连接自定义ip地址以外的google.com地址？

### ISSUE THREAD

**Issue by qiangliu8183** [phuslu/goproxy#1290]
如题

**Comment by jzp820927** [comment]
不存在这个问题，不知道你遇到的是什么问题？

**Comment by qiangliu8183** [comment]
@jzp820927 https://github.com/phuslu/goproxy/issues/1279

**Comment by jzp820927** [comment]
你的意思是不要使用解析 google.com 的 IP 地址？

**Comment by linhua55** [comment]
>  goproxy 在尝试完所有 gae.user.json 的 IP 后**发现不能连上之后**，会继续尝试 google.com 的 IP 地址。

**Comment by qiangliu8183** [comment]
@linhua55 对，就是这个意思

**Comment by wpyok500** [comment]
应该是将这个节点
	"HostMap" : {
		"google_hk": [
			全部换成你的ip
		],
		"google_cn": [
			全部换成你的ip
		]
	},

**Comment by jzp820927** [comment]
gae.user.json

**Comment by qiangliu8183** [comment]
@jzp820927 gae.user.json文件怎么去掉gae.json里HostMap默认的域名？

**Comment by johnsonz** [comment]
。。。

**Comment by jzp820927** [comment]
gae.user.json 的功能和 gae.json 是一模一样的，你 gae.json 怎么写，gae.user.json 就怎么写。只是更新的时候，不会被覆盖。所以不用每次更新都要改 gae.json

**Comment by qiangliu8183** [comment]
@jzp820927 是我没表达清楚，我的意思是gae.user.json里的内容是替换gae.json里相同的内容还是只是gae.json的补充？

例如gae.json里google_hk是这样的
"google_hk": [
                        "mail.google.com",
                        "mail.l.google.com",
                        "maps.l.google.com",
                        "scholar.google.com",
                        "scholar.google.com.hk",
                        "www.l.google.com",
                ],

如果在gae.user.json里写入
"google_hk": [
                        "192.168.0.1",
                ],

google_hk的内容会完全替换gae.json的google_hk还是只是为gae.json里的google_hk做一个补充变成这样
"google_hk": [
                        "mail.google.com",
                        "mail.l.google.com",
                        "maps.l.google.com",
                        "scholar.google.com",
                        "scholar.google.com.hk",
                        "www.l.google.com",
                        "192.168.0.1",
                ],

**Comment by wenliyang** [comment]
https://github.com/phuslu/goproxy/blob/wiki/ConfigIntroduce.md

在新的 gae.user.json 文件里只须加上你想要修改的内容(选项)

gae.user.json 里的内容是替换 gae.json 里相同的内容

**Comment by qiangliu8183** [comment]
明白了，多谢各位
