### ISSUE TITLE
gop https代理转socks代理

### ISSUE THREAD

**Issue by lxl53535** [phuslu/goproxy#1299]
#首先下载ccproxy；
点ccproxy设置-高级-二级代理---127.0.0.1:8088；
然后点ccproxy添加账号，新建添上自己局域网某台设备的ip或者127.0.0.1；
然后设置chrome socks代理--127.0.0.1:1080;
就这样相当于反代了gop的8088端口，而且成功转换为 http代理 或者socks代理

![default](https://cloud.githubusercontent.com/assets/10113198/20438001/f76aac60-adf0-11e6-8afd-e57673562026.jpg)
![q](https://cloud.githubusercontent.com/assets/10113198/20438021/04214dc4-adf1-11e6-92ae-b9df10d59f82.jpg)
![3](https://cloud.githubusercontent.com/assets/10113198/20438036/0cfdd3f4-adf1-11e6-9363-d4faa8887561.jpg)

**Comment by wgf0330** [comment]
这样之后还需要导入证书么？

**Comment by SeaHOH** [comment]
关注点搞错了，应该是日本 IP 是什么鬼！

**Comment by rcyggdra** [comment]
gae的出口不都到美国IP么，日本IP怎么弄的？

**Comment by lxl53535** [comment]
8088是php模式的端口，我用个日本的php空间 有问题么？

**Comment by wpyok500** [comment]
在建appid时可以选，建完之后不能改。

**Comment by jzp820927** [comment]
你们都没注意吧，他的配置是 8088 ，不是 8087，是 PHP，应该是日本的 PHP 主机。
而且感觉把 https代理转成 socks代理 这样做没有任何意义。

**Comment by yaoguaishou** [comment]
这不是反代，ccproxy是个卖服务器的，你这么做等于用goproxy连接了他的日本代理服务器

**Comment by lxl53535** [comment]
最讨厌这种没事瞎装逼的货--（yaoguaishou）

**Comment by SeaHOH** [comment]
@lxl53535 @yaoguaishou 
别人又没说错，不是反代，怎么就提升逼格了，求教学。

**Comment by wz7465** [comment]
搞笑了，不过是伪socks代理，无意义啊

**Comment by lxl53535** [comment]
@wgf0330 我通过808端口 能访问到 本地局域网的某个8088端口，怎么不叫反代？我啥时候用ccproxy的服务器了？这家伙不懂装懂，我哪句说错了？

**Comment by lxl53535** [comment]
@SeaHOH 我通过808端口 能访问到 本地局域网的某个8088端口，怎么不叫反代？我啥时候用ccproxy的服务器了？这家伙不懂装懂还指指点点，我哪句说错了？

**Comment by SeaHOH** [comment]
@lxl53535 
那个字写了你用 ccproxy 的服务器？我中文不及格，麻烦指一下。
还有请教一下，你的 goproxy 有用 php 代理？

**Comment by lxl53535** [comment]
@SeaHOH @你们牛逼，还用得着我教学？

**Comment by lxl53535** [comment]
@SeaHOH 别跟说话了，我嫌你垃圾

**Comment by lxl53535** [comment]
说什么伪代理，麻烦看清楚了到底是什么协议；
还要纠正一次，ccproxy是软件，不是卖服务器的

**Comment by wz7465** [comment]
人要虚心学习，才能进步啊。说白了，你808端口能访问8088端口，不过是流量的端口转发而已，谈不到反代概念上啊，就如你这里的架构方式，浏览器监听1080，再转8088端口，不过是用了socks协议做了一下端口转发而已，后面的活还得gop来干，gop本身是http协议，还是干不了socks的活，所以最后还是没意义啊，如果http这么简单就能转socks，那社长也要拜你为师了

**Comment by lxl53535** [comment]
@wz7465 麻烦你试一下最老版本的wallproxy，服务端也是社长写的

**Comment by SeaHOH** [comment]
社长的代理软件我就用过 goagent，wallproxy 有什么区别？

**Comment by wz7465** [comment]
没用过wallproxy，既然是在gae上部署的，那原理是一样的。这种伪socks代理并不会影响你浏览网页啊，你拿来代理qq通讯类软件或游戏，就知道这不行了。

**Comment by lxl53535** [comment]
你个智障，麻烦你去看清楚通讯类基于什么协议；

**Comment by lxl53535** [comment]
另外  ，反向代理不是啥多高深的技术，8088端口你以为 我映射不出去？

**Comment by wz7465** [comment]
没必要骂人吧，也许我说错了，毕竟不用qq，记忆难免出错。只要领会到意思就可以了，也没必要抓到一点小辫子就趾高气扬了

**Comment by SeaHOH** [comment]
QQ 有多种通讯方式，有些就是不行。

**Comment by wz7465** [comment]
我在网上百度了一段：我们常用的聊天软件(如QQ)，起初就一直用的是UDP协议，所以只能用SOCK5的代理。当然现在能用tcp协议了，也能用http代理了，所以说啊，学无止境，人一懒惰，我就跟不上时代了

**Comment by SeaHOH** [comment]
反代本来就没啥稀奇，但有些人就是搞不清。

**Comment by SeaHOH** [comment]
百度.....

**Comment by lxl53535** [comment]
臭逼们，继续逼逼  千万别停

**Comment by lxl53535** [comment]
一个字 贱

**Comment by SeaHOH** [comment]
@phuslu 
这素质也是不好评价，求封。

**Comment by lxl53535** [comment]
正好
