### ISSUE TITLE
PureVPN 5.15.1.0 无限试用

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1306]
沙地阿拉伯达人分享

主页
https://www.purevpn.com/

下载
http://www.mediafire.com/file/j7n801hu5af9fyt/purevpn_setup.exe
重置试用
http://www.solidfiles.com/d/4AnPXKPjqkX2n
http://www79.zippyshare.com/v/djzLV6z9/file.html

服务器很多,而且支持所有VPN协议

**Comment by jzp820927** [comment]
我去，这个太给力了。

**Comment by blob2015** [comment]
j哥，一如既往地强大啊

**Comment by wz7465** [comment]
纯属浪费时间，华而不实的东西，那么多服务器，没连上几个，就算连上，连网页也不能稳定打开

**Comment by jzp820927** [comment]
试了一下，速度慢成狗，144P 都不流畅，这个估计也只能看网页了。确实能连上的 服务器 很少。

**Comment by jasonliul** [comment]
哪来这么多怨妇?
换协议再试

**Comment by wz7465** [comment]
所有协议，所有应用类型都试了一遍，偶而能连上的也只有pptp和udp协议

**Comment by jzp820927** [comment]
VPN 是重点封锁对象，而且协议特征明显，能连上就应该谢天谢地了。

**Comment by wz7465** [comment]
面对gfw,vpn算廉颇老矣，若没有新的技术突破，难有新生。不过j大似乎对此情有独钟，我想我可以理解，想当年，vpngate是我觉得最好用的软件了，虽然现在基本废了，我仍然舍不得删除，我想这就是情怀

**Comment by jzp820927** [comment]
看网页还是不成问题的，可以作为备胎应急。
