### ISSUE TITLE
赛门铁克报毒

### ISSUE THREAD

**Issue by deeplee** [phuslu/goproxy#1310]
Goproxy-gui。exe  被赛门铁克报毒

**Comment by johnsonz** [comment]
建议卸载掉赛门铁克试试

**Comment by phuslu** [comment]
https://www.virustotal.com/en/file/5cfbc806f3398ef564d10e9d6b39e161756c17c5c70d6417c437581ff6deb253/analysis/1479695811/

推测是 NOD32 的有意误报，并且把这个结果通过特征共享的方式传播给其他安全厂商（如赛门铁克）

没啥好建议。有担忧的话，建议酌情使用 goproxy

**Comment by Just2co** [comment]
是因为goproxy利用了证书欺骗的方式来使用GAE服务，自己明白是怎么回事就行了，把Goproxy加入赛门铁克或其他杀软的白名单即可解决！同时，也不要怕不安全，证书欺骗行为仅仅发生在本地端口代理端口之间，Goproxy跟GAE服务器间的通讯还是走的正常的443 TCP端口，通过安全的TLS1.2加密方式，可以说安全至极！

**Comment by blob2015** [comment]
我那老版qq，前几天也被杀软报了，说我几个dll文件是非必要文件什么什么的……

**Comment by cdmask** [comment]
@Just2co 这个所谓证书欺骗，可以科普一下吗？

**Comment by jzp820927** [comment]
就是用假证书来代理 https 流量。

**Comment by deeplee** [comment]
企业版  暂时加入白名单解决吧

**Comment by phuslu** [comment]
r1206 之后用 mingw-w64 编译了一下，现在不报毒了。

https://www.virustotal.com/en/file/e334a2a5b99fc8540dc1115dfbdd24eb3186016e0f6379dfb94b2c18db0a582d/analysis/1482806020/
