### ISSUE TITLE
UA 暴露 APPID 问题

### ISSUE THREAD

**Issue by sh0uw4ng** [phuslu/goproxy#1311]
会在 UA 最后加入 `AppEngine-Google; (+http://code.google.com/appengine; appid: s~xxxxxxxxxxx)`
xxxxxxxxxxx部分为个人的APPID，感觉这个会导致匿名性大大降低(鉴于普通人的安全意识，可轻松被爆菊)，社长请考虑下？
![image](https://cloud.githubusercontent.com/assets/8855832/20472193/9f64b318-aff2-11e6-8ccb-613e6dd18d39.png)

**Comment by jzp820927** [comment]
无解

**Comment by sh0uw4ng** [comment]
@jzp820927 goagent的时候没注意刚才用xx-net试了一下也存在这问题，看来是 gae 自动加的了。只能重新申请appid了  : (

**Comment by jzp820927** [comment]
是 GAE 的问题，和 客户端 无关，所有说无解，除非你能改版 google 的服务器。
