### ISSUE TITLE
特惠Smart DNS Proxy and SmartVPN

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1314]
SmartVPN

    Encrypt and secure your internet traffic.
    PPTP, L2TP & OpenVPN Support
    Access all Smart DNS Proxy services while you are connected to any SmartVPN server.
    Download Torrents
    Unlimited Device Access
    5 Simultaneous VPN Connections

http://sharewareonsale.com/s/smart-dns-proxy-giveaway-sale

**Comment by jzp820927** [comment]
好像前不久，也是 J大，才给过1年的优惠吧，好像都还没过期。

**Comment by jasonliul** [comment]
@jzp820927 

VPN或者透明代理, 都会有不少特惠, 圣诞节附近

**Comment by jzp820927** [comment]
好吧，我是问下，免费期是多长时间
