### ISSUE TITLE
特惠Windscribe VPN | 50GB

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1315]
Instructions:
    1. Follow sign up for Windscribe VPN (no need to download)
    2. Choose 10GB (instead of 2GB) - Limited Offer
    3. Choose unique Username and Password
    4. Enter and Confirm email for 10GB
    5. Apply Voucher Code before 28th November 2016
    6. Create Free Account 

Starting Date:
    Now 

Ending Date:
    28th November 2016 

    Get 50GB Free Usage for Windscribe VPN - 100% Discount

        Sign Up - Sign Up for Free - Windscribe
        Code - Windscribe VPN (100% Discount)
        Available Usage - https://windscribe.com/myaccount 

GIVEAWAY:
https://windscribe.com/signup

**Comment by jzp820927** [comment]
J大，一天连着2个特惠。

**Comment by jzp820927** [comment]
Apply Voucher Code before 28th November 2016
这个是怎么弄的
