### ISSUE TITLE
goproxy CONNECT 支持代理ssh吗？

### ISSUE THREAD

**Issue by cclu** [phuslu/goproxy#1316]
有办法通过goproxy代理ssh不？

比如经常需要访问公司服务器，ssh demoserver(通过id_rsa)，

goproxy配合其他软件可以做到不？corkscrew等我都撞南墙了……

**Comment by jzp820927** [comment]
只支持代理 http（80 端口），https（443 端口）数据

**Comment by wz7465** [comment]
用gost

**Comment by cclu** [comment]
@jzp820927 可能不是端口的问题，因为我用proxycommand等可以把ssh等程序挂给goproxy，但是可能因为SSL等原因不响应。

**Comment by jzp820927** [comment]
这个是 HTTP 代理，又不是 socks

**Comment by cclu** [comment]
而且也不支持 CONNECT

ok，有这句确认就可以了，谢谢。

**Comment by jzp820927** [comment]
收费版的 GAE 支持 ws，免费版的限制较多。如果能支持 CONNECT ，代理 https 就不用伪造证书了。
