### ISSUE TITLE
一不小心把韩国所有ip扫了一遍

### ISSUE THREAD

**Issue by qiangliu8183** [phuslu/goproxy#1319]
在公司服务器上扫了一个多月，收获不小

**Comment by jasonliul** [comment]
@qiangliu8183 
公器私用, 罪大恶极
:)

**Comment by qiangliu8183** [comment]
@jasonliul 哈哈，有这便利条件，不用白不用，话说checkip真吃内存啊，128G的内存基本耗尽了

**Comment by jasonliul** [comment]
@qiangliu8183 

还不上缴ip, 孝敬社长?

回去把港澳也扫一遍, 听候组织研究肿么处理你.

**Comment by qiangliu8183** [comment]
@jasonliul 发邮件吧，谁要留email

**Comment by panpeach** [comment]
@qiangliu8183 ，PM，panpeach@gmail.com

**Comment by CooalManER** [comment]
@qiangliu8183   tyrkosbgybce@gmail.com  谢谢！

**Comment by katsuyoo** [comment]
@qiangliu8183 ， 求ip，zhenxinu@gmail.com

**Comment by jzp820927** [comment]
这个必须要啊。jzp820927@gmail.com

**Comment by v80392** [comment]
@qiangliu8183 同求ip，谢谢。v80392@gmail.com

**Comment by jamako** [comment]
@qiangliu8183 求ip，感謝。gfxhoo@gmail.com

**Comment by tcwilliy** [comment]
@qiangliu8183 tcwilliy@gmail.com

**Comment by tcwilliy** [comment]
@qiangliu8183 谢谢

**Comment by waited33** [comment]
@qiangliu8183 求个IP  感谢了heyong7191@gmail.com

**Comment by AhernWalker** [comment]
遇到此等好事岂能错过？！万分感谢楼主大大！ lovecan555@gmail.com

**Comment by SeaHOH** [comment]
@qiangliu8183 老板，来一盘！
seahoh@gmail.com

**Comment by fengixng** [comment]
让我看下结果怎么样，谢谢楼主了
YTU0MDM1NTY4NkBnbWFpbC5jb20=

**Comment by jzp820927** [comment]
调查一下，收到IP的，你们都有多少IP可用

**Comment by MeABc** [comment]
哇，这贴热闹。

**Comment by brickexplorer** [comment]
@qiangliu8183  求个IP，谢谢楼主

**Comment by SeaHOH** [comment]
发觉我的 IP 里面已经有了。根据以往观察，速度很快，但是干扰也重。
在我这里使用率很小，基本上用一两分钟就不行了，因为不能一直保持连接。

**Comment by MeABc** [comment]
这个时间段干扰还严重吗？我这里这个时间开始 GAE 已经可以跑满带宽。

注：社长这次两个修复效果很明显啊。不会是我的错觉吧。 😄

**Comment by phuslu** [comment]
是说 r1143 版本吗，这个修复影响其实挺大。

以目前干扰严重的情况，难以断言是性能提升还是衰退，只能等大家测试反馈了。

**Comment by MeABc** [comment]
嗯，我正在用 r1143 呢。

goodip 和 badip 刷新很快啊。----这样正好能很好应对目前这样情况。

**Comment by MeABc** [comment]
嗯，我正在用 r1143 呢。

goodip 和 badip 刷新很快啊。----这样正好能很好应对目前这样情况。

**Comment by chili-Pepper** [comment]
@qiangliu8183 谢老板！ aiqinqin2012@gmail.com

**Comment by p1956** [comment]
p1956@live.cn 谢谢

**Comment by blob2015** [comment]
@MeABc 有这等好事，竟然又改进了那么多。等明后天，我也升级下试试。
@qiangliu8183 感觉棒子的还是很容易挂，在我这里。等着老兄那天扫其他国家与地区的 :grinning:

**Comment by qiangliu8183** [comment]
@SeaHOH 整个网段可用ip全扔进去

**Comment by SeaHOH** [comment]
刚看了下，放了 270 个。
刷新很快，刚筛选出来，下一轮就不行了。

**Comment by qiangliu8183** [comment]
@SeaHOH 随机干扰，整个网段放进去就是了

**Comment by MeABc** [comment]
我是丢了 2000+ 个在里面。

不过现在这种情况(GoProxy)很是合我的"胃口" 。哈哈。

**Comment by fengixng** [comment]
楼主发给我让我看下呗，我的邮箱在上面发了，base64加密的那个

**Comment by SeaHOH** [comment]
不好意思，好像没讲清楚。
我是说这些 IP 已经在我的配置里面了，虽说只有一半的样子。
总 IP 数 3万，但这些 IP 被使用的频率非常低。

**Comment by qiangliu8183** [comment]
@SeaHOH 3万？！太多了吧？我只要联通线路100ms以内的

**Comment by SeaHOH** [comment]
无所谓多少，我做了一个统计来筛选，优先列表大概有两三百个 IP。

**Comment by caofengzi** [comment]
@qiangliu8183 首先感謝付出。ziyouminzu617@gmail.com

**Comment by jap33** [comment]
@qiangliu8183谢谢了 japanooo99@gmail.com

**Comment by minorisprit** [comment]
老板给我来一份
minorisprit@gmail.com

**Comment by immeman** [comment]
@qiangliu8183 排队，先谢了 image.soraya@gmail.com

**Comment by fuckGFW2015** [comment]
独乐乐不如众乐乐fangdoggotohell@gmail.com

**Comment by horizonl** [comment]
一种1024的既视感，不过还是求一份
huangliang.0618@gmail.com

**Comment by wangbingqian** [comment]
我来啦 wangbingqian521@gmail.com

**Comment by james0808** [comment]
谢谢老板，给我来一份 chicagojmfan@gamil.com

**Comment by shindaren** [comment]
chinliu001@gmail.com   凑个热闹*_*~! @qiangliu8183

**Comment by masktao** [comment]
masktao@gmail.com 感谢

**Comment by CHN008** [comment]
这么多人? 不过过一段时间是不是就用不了了 :yum:

**Comment by p0oo0q** [comment]
@qiangliu8183  同求
beyondadmin@126.com

**Comment by wenliyang** [comment]
@qiangliu8183 求一份，谢谢
softworm888@gmail.com

**Comment by jzp820927** [comment]
@CHN008 确实，在我这边基本没有可用性。

**Comment by xc1988** [comment]
我来伸手要IP了
xc1988@gmail.com

**Comment by angle1895** [comment]
@qiangliu8183 ， 求ip，angle1895@gmail.com

**Comment by SeaHOH** [comment]
有点奇怪，我啥也没干，却发现从昨天凌晨开始这两段 IP 的选中率和使用率都增加了一些，尤其是选中率。

**Comment by jzp820927** [comment]
可能是受随机干扰的影响吧，好的时候，就被选中，坏的时候，又被踢掉。

**Comment by mrdeng912** [comment]
@qiangliu8183  老板 求一份 最近ip被封的太厉害了 基本没速度

**Comment by jzp820927** [comment]
我这儿是 电信 ISP，亚洲区的 IP 掉包最厉害，在我这儿基本上用不了。

**Comment by qiangliu8183** [comment]
那两段ip北京联通线路40ms的占90%

**Comment by jzp820927** [comment]
我这儿的干扰是随机化的，不是固定干扰，也就是这儿干扰的时候，那个好，那个干扰的时候，这个好。不过掉包太厉害，可以达到 95% 以上，基本上不能用。

**Comment by hexianfu** [comment]
楼主辛苦了 我来捡个便宜 hexianfu@mail.com

**Comment by jzp820927** [comment]
LS 的邮箱有点流弊，在哪儿注册的，我也去注册个

**Comment by hexianfu** [comment]
就是 mail.com

**Comment by showbye** [comment]
扫ip不易好好珍惜 LZ也来一份吧 showbye00@gmail.com

**Comment by blob2015** [comment]
@jzp820927 
好像也算老牌了啦，之前好像玩过一个，感觉还是没有g强大

**Comment by jzp820927** [comment]
还真不知道有这个邮箱，好吧，我承认，我 OUT 啦

**Comment by piaoyun** [comment]
求IP一份。谢谢了
loveyour@gmail.com

**Comment by wang3stone** [comment]
@qiangliu8183,留一份给我wang3stone@gmail.com

**Comment by distance00** [comment]
感谢楼主奉献，希望没有来晚。cooldistance@mail.com

**Comment by tec1987** [comment]
@qiangliu8183
可否分享一份，tec163[at]163.com
谢谢。

**Comment by hexianfu** [comment]
@qiangliu8183  楼主能发一份你的IP吗，前面留了邮箱几天了 还没收到 -  -

**Comment by Aaronee** [comment]
求扫ip方法，公司内网一般不都是白名单吗？

**Comment by tec1987** [comment]
等了很久也没有收到，既然楼主不发，我来一份吧：

    为了防止机器自动抓取，请将其中的美元符号和百分号替换没，＃和星号替换为半角句点

`
1#2$55*22.%0-255
$1*255#33.0%-255
58.1$23#102*0-255%
58.123#22%0*0$-255
58#229.92%*0-255$
%59#18.34*0-$255
59*18#35.0-$%255
59*1$8#44.%0-255
59*1%8.45$#0-255
59.1%8*46$#0-255
5%9.18#49*0-$255
59*2$0#132.0-%255
61.33*130#0$-%255
61*3%7.150#0$-255
%1$06#103*1.0-255
1%06*10$3.2#0-255
117.11%1#0*0-2$55
1%19#149*$187.0-255
119*149.%$188#0-255
121*7%8.71#0-25$5
121*$78.74#0%-255
121#78.206*0%-$255
12%2.202$#129*0-255
12%4*153#25$5.0-255
157#197.9$2*%0-255
157*197#93$.0%-255
182*163#240.0%-25$5
203%.$233#10*0-255
%203.233#18$*0-255
203.2%33*63#$0-255
$20%3*233.88#0-255
20$3%.233#92*0-255
2$03*233%.96#0-255
$203#2%33*126.0-255
203#248$*%180.0-255
$203#248.210*0-2%55
20$3*%252.15#0-255
2%10#$92*119.0-255
210$*94.15%3#0-255
211*49.146%#0-$255
21%1#117.39*0-$255
21$1*239.188%#0-255
211*23$9.234#0%-255
222#2%51*134.0-255$
223#62*225.$0%-255
223*6$2#226.0-255%
`

**Comment by jzp820927** [comment]
流弊，这个要支持一下。

**Comment by tec1987** [comment]
@jzp820927
算不上啦，并没有带来什么惊喜

**Comment by jzp820927** [comment]
估计包含 韩国 70% 以上了吧

**Comment by Aaronee** [comment]
意思就是这些ip段覆盖了所有韩国境内的IP了是吗?
然后用什么操作来识别我们需要的ip呢?
小白求赐教,谢谢 @tec1987

**Comment by PvCDp** [comment]
来一份：wwwcom@mail.com

**Comment by jzp820927** [comment]
上面都已经贴出来了，很全了，你复制一下就行了。不用邮箱了。

**Comment by tec1987** [comment]
@jzp820927 我估计至少90%吧，想和LZ强扫的结果对比确认一下。。。
你这面有的话帮忙对比一下，看看结果如何

**Comment by jzp820927** [comment]
LZ 就发了2个 24 段，而且很早以前有人发过的，没你这个全。

**Comment by fengixng** [comment]
tec1987 你发的IP段已经很全了，就差两个而已
121#78#52#0/24
211#175#187#0/24

**Comment by jzp820927** [comment]
漏网之鱼，马上补齐。

**Comment by yDan** [comment]
能不能把港澳臺的ip掃一下

**Comment by tec1987** [comment]
补充几段，
`1$2%1*78#42#84 1%24#$216#0*143 183#$9%1*238#78 20$3%#233#37*180 20$3#248%#132*148`

删除两段
121.78.71.
121.78.74.

数据更新于4月底

@yDan  目前没那个必要，挨个扫的方法太low，反正我是不会那么无聊去扫的。。

**Comment by yDan** [comment]
@tec1987  要不你教我怎么扫吧，用什么工具的？

**Comment by blob2015** [comment]
@tec1987 
有斗争经验的人哪

**Comment by tec1987** [comment]
@blob2015 老网虫一个，fuckGFW是必备技能。。。

@yDan 
目前IP资源还是不缺的，想学习的话去看 [https://github.com/phuslu/goproxy/issues/737](url)

**Comment by yDan** [comment]
能不能教我如何指定一个地区去扫描，比如我想要香港的google ip，怎么指定香港来扫？

**Comment by tec1987** [comment]
简单点的：Google “country ip range”
否则就自己去APNIC下载whios数据，然后过滤处理
@yDan
