### ISSUE TITLE
谁能告诉我为什么用PAC打不开google.cn

### ISSUE THREAD

**Issue by qiangliu8183** [phuslu/goproxy#1320]
不用PAC可以打开，用了反而打不开

**Comment by jzp820927** [comment]
google.cn ？你确定，不是 com ，是 cn ？谷歌在中国的业务都迁移到香港了，你访问 google.cn，就跳到 google.com.hk 的。

**Comment by SeaHOH** [comment]
cn 好像能用，地图有 cn 域名。我没试过。

**Comment by CHN008** [comment]
cn的只是一个链接,页面上放了一张链接到香港站点的图片而已. :cry: 

![g cn](https://cloud.githubusercontent.com/assets/16646697/20586716/b04c41a4-b241-11e6-924d-a1979b0b6117.png)

**Comment by qiangliu8183** [comment]
@CHN008 就是这个链接打不开，google.com和google.com.hk都能打开

**Comment by jzp820927** [comment]
这个本来就会自动跳到 google.com.hk，如果你 google.com.hk 能打开，那就是跳的时候，跳到 http 了，手动改为 https 就可以 了。

**Comment by qiangliu8183** [comment]
@jzp820927 我的意思是我看不到google.cn的跳转页面

**Comment by dannymtseng** [comment]
地图可以，http://www.google.cn/maps，不用翻墙。

**Comment by CHN008** [comment]
@qiangliu8183  用不了不用纠结啊,它本来就不是一个正常的页面.

**Comment by jzp820927** [comment]
google.cn 是国内的服务器，可能需要直连才行，走代理，不一定能打开，你直连试试
