### ISSUE TITLE
最近几个版本真给力

### ISSUE THREAD

**Issue by qiangliu8183** [phuslu/goproxy#1327]
r1145，同样的ip，非常稳定

![_2016-11-25_15-59-50](https://cloud.githubusercontent.com/assets/22366986/20618369/89ebec42-b329-11e6-96e6-17fd4ebb5806.png)

**Comment by jzp820927** [comment]
这个截图，就是你扫出来分享的韩国IP的速度？

**Comment by wz7465** [comment]
数字不准，要把任务管理器的贴出来才看的出

**Comment by qiangliu8183** [comment]
@jzp820927 是的

**Comment by jzp820927** [comment]
看样子，你那边连韩国还是挺好的，我这边虽然也能连，但是基本上没速度。可能是 ISP 的原因吧，我是南方电信。

**Comment by wz7465** [comment]
看看，比较比较
![default](https://cloud.githubusercontent.com/assets/7801728/20619590/527b9b2a-b330-11e6-9903-b7fc47104b72.JPG)

**Comment by jzp820927** [comment]
@wz7465 你这个和 LZ 的不是一个档次，没有可比性啊。LZ 是用的 720P 测速的。你这个 360P。要同一个层次，才有可比性。

**Comment by wz7465** [comment]
![2](https://cloud.githubusercontent.com/assets/7801728/20619713/edb4e98e-b330-11e6-825a-8e7644490699.JPG)
![default](https://cloud.githubusercontent.com/assets/7801728/20619712/edb4b4e6-b330-11e6-9600-9c48f81e4e59.JPG)

**Comment by wz7465** [comment]
![111](https://cloud.githubusercontent.com/assets/7801728/20619886/c388f44c-b331-11e6-9925-10bb51d70510.JPG)

**Comment by mrdeng912** [comment]
@qiangliu8183   可否发一份ip过来测试下  hdxjzh@gmail.com 谢谢

**Comment by jzp820927** [comment]
其实感觉最近几天的网络状况比前段时间要好多了，虽然掉包还厉害，但是 但是稳定性要好些了。速度基本上都挺快的。可能和 gop 的筛选机制优化有关。

**Comment by wz7465** [comment]
没错，火狐

**Comment by wz7465** [comment]
这是sniproxy稳配方案测得，数字不高，看720p一样流畅
![222](https://cloud.githubusercontent.com/assets/7801728/20620416/8a2b7f64-b334-11e6-8dab-d29f3812c998.JPG)

**Comment by hcym** [comment]
1150用了什么大杀器？

17:33 感觉木墙

**Comment by SeaHOH** [comment]
同电信，这段时间愈来愈渣，普通网站有时也丢包。

**Comment by qiangliu8183** [comment]
@wz7465 是要看下载速度吗？
![screenshot_2016-11-25-17-37-41](https://cloud.githubusercontent.com/assets/22366986/20620791/100ef3aa-b2c1-11e6-9aa1-00ada8da3cd4.png)

**Comment by wz7465** [comment]
下载速度？用代理的，浏览网页的速度
![default](https://cloud.githubusercontent.com/assets/7801728/20620953/50ff0a82-b337-11e6-8f40-060fd15129bb.JPG)

**Comment by SeaHOH** [comment]
不要炫耀你们的网络了！我这儿 5000 都不到，才 4000+。

**Comment by jzp820927** [comment]
@qiangliu8183 你的 ISP 是北方联通吧？之前好像听你说过，我的渣电信，就不和你们比速度了，我还是比较有自知之明的。

**Comment by qiangliu8183** [comment]
@jzp820927 北京联通

**Comment by jzp820927** [comment]
联通 和 移动 的网络，比电信好很多，我觉得你们的速度，都还算正常。电信都还要用 移动，和 联通来加速。

**Comment by SeaHOH** [comment]
@jzp820927
指实际平均下载速度，所以码率 3000+ 的高清也有可能卡。
早上和中午就不说了，码率 5／6000 也很流畅。

**Comment by jzp820927** [comment]
走移动的话，高清基本上还是没问题的，直连 gws/gvs 的话，就得看IP了，要精选才行。很难找到高质量的直连 IP。

**Comment by Pauly2015** [comment]
youtube上湖南卫视的的视频连接速度是超快的，用这个测能测出最大值

**Comment by jzp820927** [comment]
@Pauly2015 按你这么说起来，说不定湖南卫视的服务器在国内哦。

**Comment by SeaHOH** [comment]
是不是因为前段时间提升用户带宽造成的，毕竟电信用户最多，影响应该很大，总出口带宽又没变多。

**Comment by Pauly2015** [comment]
@jzp820927 50M宽带，常规最好连接速度一般是6M/s到7M/s，但用湖南卫视视频经常最高测出17M/s到18M/s，技术好的朋友请深挖

**Comment by jzp820927** [comment]
@SeaHOH 虽然电信用户基数大，但是经常需要国际流量的用户数占总总用户数，应该比例还是比较小。我觉得 80% 以上的用户都是 微信+微博+淘宝+国服网游。

**Comment by SeaHOH** [comment]
@Pauly2015 
我觉得湖南卫视那个对翻墙完全没影响，反正也就只有湖南卫视。
就算真挖出什么估计也不长久。
@jzp820927 
我也是乱猜。
不过现在翻墙成了常态，产业规模日趋扩大，只有我们这些穷人和没啥特别需要的人才用 GAE 来翻墙，其它各种手段简直不要太多，所以我觉得这个想法还是有点基础的。

**Comment by jzp820927** [comment]
而且我觉得还有一个问题，国人喜欢比速度，你 4K，我也是 4K ，估计国际带宽越来越拥挤，和这个关系很大

**Comment by yqy6611** [comment]
电信，只有上午和中午还能上5000，一到晚上1000都上不了ORZ

**Comment by jzp820927** [comment]
@yqy6611 看来都是电信的受害者啊，握个爪。

**Comment by yqy6611** [comment]
@jzp820927 曾经晚上也是能上5000的，就是最近晚上完全不行了。

**Comment by jzp820927** [comment]
最近干扰相当厉害，不过我这儿之前没干扰的时候，最多也就 480P，总感觉国际带宽严重不足

**Comment by SeaHOH** [comment]
我觉得星期二开始干扰加重了，之前码率 4000+ 的高清都能放。

**Comment by jzp820927** [comment]
星期二？22 号？

**Comment by drg78rnvgh** [comment]
@jzp820927 
我觉得肯定对youtube进行了专门封杀。
我的下载速度可以到800k的！看av网720p也是可看的。
youtube就360p都一直卡顿，你试试看

**Comment by jzp820927** [comment]
加密流量，关键字都无效，怎么针对性封杀。

**Comment by p1956** [comment]
想要看4k，速度要在稳定至少在1w+才行，前提是画质动态一般
![45242424](https://cloud.githubusercontent.com/assets/14120334/20637389/37b69056-b3c1-11e6-9885-a2d8ad4c7e79.gif)

**Comment by p1956** [comment]
发现以前有3w+的速度，现在不行了  
![qq 20161126102351](https://cloud.githubusercontent.com/assets/14120334/20637419/8d390a62-b3c2-11e6-9a3e-cf823940ee3c.jpg)

**Comment by phuslu** [comment]
@jzp820927 想了想还是和你说件事。

谢谢对 goproxy 的抬爱，但是有个小请求，请不要在 xx-net 帮 goproxy 做推广.

我觉得目前的无压力无责任的开发状态挺好的，想保持下去。谢谢 :trollface:

**Comment by hcym** [comment]
不主动不拒绝不负责

**Comment by SeaHOH** [comment]
还有我吗，收到。
我也有注意这个问题，一般不会提跟项目不相关的内容。以后会更加注意的。

**Comment by phuslu** [comment]
麻烦各位了，真的很感谢。

原因其实不一而足，甚至我家人也不希望我在 goproxy 花太多精力，所以保持现状是最好的。别无他求。(过会删除此回复）

**Comment by SeaHOH** [comment]
谈不上感谢，真要说也是我们感谢你。 :heart: 
等下一并删除吧，我也有点小害羞。

**Comment by jzp820927** [comment]
@phuslu 行，我已经把那边含有 “goproxy” 关键字的 issues 都删掉了，你检查下，如果还有漏掉的，就说声，我再去处理。

**Comment by phuslu** [comment]
惭愧，谢谢。时来天地皆同力，运去英雄不自由。先这样苟住吧。
