### ISSUE TITLE
建议gae增加备用代理设置

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1334]
gae毕竟有局限，建议gae增加备用代理设置，在使用gae请求失败后走备用代理。@phuslu

**Comment by phuslu** [comment]
暂无计划。

目前建议使用 SitesFilters 来手动调整。

**Comment by dou4cc** [comment]
@phuslu 那个不方便啊，而且未知网站怎么办？

**Comment by dou4cc** [comment]
@phuslu cow/meow不能解决我的需求，因为他们拿不到https明文，不知道gae是不是突然罢工返回个500以上的HTTP码

**Comment by phuslu** [comment]
呃，建议你最好先使用一段时间再提需求，50x 的 goproxy 已经处理了。

**Comment by dou4cc** [comment]
@phuslu 昨天用gae下一个安装包时gae告诉我要请求的文件太大

**Comment by phuslu** [comment]
啊，这个不好意思。这是 autorange 一直以来的 bug, 不能下载超过 32 MB 的文件。

这个 bug 会通过类似 goagent 的 autorange 实现方式修复掉，我不打算用“备用代理”的方式来绕过这个 bug.

**Comment by dou4cc** [comment]
@phuslu 我之前用的xxnet只支持get和post的http method，goproxy支持更多method了吗？支持所有method了吗？

**Comment by phuslu** [comment]
GAE 代理的局限都是类似的。

**Comment by dou4cc** [comment]
@phuslu 所以最好加一个备用代理设置嘛

**Comment by dou4cc** [comment]
@phuslu 外个楼问一下autorange只对指定uri有效是不是表示autorange不检查服务器是否支持range？

**Comment by phuslu** [comment]
暂无计划

**Comment by phuslu** [comment]
autorange 这块目前不完善，好久没碰它了，我也记不清楚了。

**Comment by dou4cc** [comment]
@phuslu 所以能不能reopen？

**Comment by phuslu** [comment]
小声说一句，“暂无计划”其实托辞啊，隐含意思其实就是不打算做的。

当用“暂无计划”来推脱的时候，原因一般有二

1. 建议的功能和我设想的 goproxy 的不符。比如 xx-net 自动扫描功能，我一开始就不想有这个功能。
2. 虽然是个有用的功能，但是我人手有限，再加上我自身对这个功能需求并不强烈，一时半会腾不出精力实现。但是直接说不做又不现实，因为某天可能我有了这个需求就实现了。比如 autoproxy 的 RegionFilters 功能就是这样的情况，在我买了小主机以后就实现了。

备用代理就属于第二种情况，虽然是个很有意思的功能，其实之前 snova 的代理就是实现了。可惜我对这个兴趣不大，但也说不准什么时候会做。

只能先回答“暂无计划”了，不好意思。

**Comment by dou4cc** [comment]
@phuslu 我觉得这是不是个需求是网站的程序员说了算的，随着RESTful的普及，会出现越来越多五花八门的method
即使社长不打算做，我也依然会持续使用goproxy

**Comment by dou4cc** [comment]
@phuslu 还有，如果reopen了说不准会有人PR

**Comment by phuslu** [comment]
当初我在做 goagent 的时候，大量用户的压力的也是让我烦不胜烦的。

所以现在从头用 go 语言实现 goproxy 的时候，我是想完全按自己的心意打造一个代理。

所以就会显得比较任性了，谢谢理解。

**Comment by phuslu** [comment]
goagent 后期流于炫技和迫于压力，堆叠了很多我现在看来不大喜欢功能。

所以现在我并不会可惜去比较同类软件的功能了。

用林纳斯的话来说， Just for fun 了。

**Comment by dou4cc** [comment]
@phuslu 其实看到goproxy那么复杂的参数就猜到社长不讲究corner case，不然绝大多数参数都可以让程序自动调整到最优

**Comment by SeaHOH** [comment]
社长你是在炫技啊，3.2 版本根本就看不明白 :sob:
