### ISSUE TITLE
goproxy能在断网后不筛IP吗？

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1338]
如题

**Comment by blob2015** [comment]
lz好像也是技术派。可能与社长更容易沟通，之前，俺也提起过，然后社长修改了一些参数。

**Comment by phuslu** [comment]
评估过，暂无计划。

**Comment by phuslu** [comment]
突然想到一个比较简便的方法，也许可以容易实现。

**Comment by phuslu** [comment]
r1162 在探测连接性的时候，会尝试连接一下 gae.json 里面的 dnsserver (默认是 114.114.114.114) ，如果连接不上就认为断网了，会暂停一下自动 IP 筛选。

这样就解决楼主的问题了。

注意：默认的被动式 IP 筛选机制还在，也就是说，断网之后如果还通过 goproxy 发起网络访问的话，依然会触发 IP 筛选机制。

**Comment by SeaHOH** [comment]
我觉得确定断网后可以暂停监听端口或暂停处理端口请求，这样就请求就终止了。

**Comment by SeaHOH** [comment]
我觉得确定断网后可以暂停监听端口或暂停处理端口请求，这样就请求就终止了。

**Comment by phuslu** [comment]
不太想这么做。

因为“主动的 IP 探测”的结果并不完全可信，尤其在网络稳定的情况下。
所以检测到所谓的“断网”结果最好只影响自身逻辑。

监听端口的逻辑还是照旧，保持对网络不稳定这个情况的容忍度。

**Comment by blob2015** [comment]
@phuslu 
收到。其实这个可能是有些强迫症的“需求” :grinning: 
那个ip是否改成养猪网，或者浪网，更加容易“遵守”规则？可以在dnsserver里面添加？

**Comment by phuslu** [comment]
考虑过。

但是它们的三次握手速度一般都不如 114dns 的的服务器快。毕竟 114dns 在全国范围内是任播的。

所以先这样吧。

**Comment by blob2015** [comment]
@phuslu 
:ok_hand:
