### ISSUE TITLE
信息滚动太快看不清，社长能否在输出信息那里加个过滤

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#1339]
就是加个Filters专门用于控制输出什么信息。
比如说我BlackList的请求太多，让我看当前的可用ip很费力。我就可以输出Filters那里选择不输出此类信息。
autorang的输出也非常多，可以选择直接不显示。
这些都是为了可以在窗口看到用户更想看到的，更人性化。而不是滚到眼花，在一大串里慢慢找可用ip剩下几个。

**Comment by drg78rnvgh** [comment]
@phuslu

**Comment by phuslu** [comment]
goproxy 使用的 glog 输出日志的。你研究一下它的 vmoule 参数。就可以实现你的需求了。

**Comment by drg78rnvgh** [comment]
@phuslu 不是搞开发的，请社长指点一下是哪个文件。

**Comment by drg78rnvgh** [comment]
@phuslu 不是搞开发的。没有编译环境，也很难编译你的每个新版本....其实这个功能我想也很容易加入。是你觉得有没有必要而已。

**Comment by szh7379** [comment]
这些加上跟商业软件差不多了，这是社长个人作品肯定不会做得那么全，而且功能越多越臃肿。加了这个肯定又得有其他的要求，比如以前说的自动扫描，一些小需求还是大家努力吧，毕竟这是个开源的东西嘛，就像ip.html这个工具一样

**Comment by distance00** [comment]
谁研究出来了分享一下经验，我也要一个功能，把日志中特定的内容输出到日志文件，不知道能否实现？
