### ISSUE TITLE
最近常碰到一页面加载不出，刷新一下才好

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1344]
猜测是连到了慢速IP，若果真如此，goproxy能否切断连接，另换IP？

**Comment by phuslu** [comment]
没有完美的方案。r1165 缩短了 keepalive 并加到了 gae level

应该有改善，你更新试试。

**Comment by blob2015** [comment]
有时候可能是卡在了cdn上面，比如这github……
慢速——可能响应迟？可以在ip筛选上面尽量搞些好的，不过，俺在check上面都好的，加入后，badip立马就过半了……
autorange也可以试试？

**Comment by SeaHOH** [comment]
这种情况不好办，没法自动处理好，强制设定一个速度限制不太合理。
一个比较合适超时时间能让部分此类问题有所改善。

**Comment by dou4cc** [comment]
可以这样，只要碰到IP减速到远低于预期，就估算换IP重连能省多少时间，把情况搞得更糟的概率如何，如果前者大而后者小，就换IP重连

**Comment by phuslu** [comment]
其实并不好做，因为网页 get/post 要保持幂等。很难保持这特性。

**Comment by dou4cc** [comment]
@plushu “幂等”是什么？

**Comment by phuslu** [comment]
通俗的说，防止”连击“。 goagent 之前实现过你说的这个特性，但是在网络不稳定的时候，用户回帖，打开网页都不能保持幂等，比如发帖三连击这种。

**Comment by dou4cc** [comment]
@plushu 这是网站自己没做放重放，goproxy不需考虑

**Comment by dou4cc** [comment]
@plushu 这是网站自己没做防重放，goproxy不需考虑

**Comment by dou4cc** [comment]
@plushu 这是网站自己没做防重放，goproxy不需考虑

**Comment by dou4cc** [comment]
@plushu 这是网站自己没做防重放，goproxy不需考虑

**Comment by dou4cc** [comment]
@plushu 这是网站自己没做防重放，goproxy不需考虑

**Comment by phuslu** [comment]
额，你看，你自己都连击了。

我在 GoAgent 实现过，发现有利有弊。暂无计划在 goproxy 引入。

**Comment by dou4cc** [comment]
@plushu 这是网站自己没做防重放，goproxy不负责任

**Comment by dou4cc** [comment]
@phuslu 这是github没做防重放，goproxy没有责任

**Comment by phuslu** [comment]
你看到了，连击之后发帖产生了太多 notification(noisy)， 以致我刚刚锁帖了。

**Comment by SeaHOH** [comment]
连击最近很常见，这个是网络状况差导致的，但 github 的确也有责任，页面和服务器的代码没做好配合。
一般程序默认超时时间都非常长，就有这个原因在里面。

**Comment by dou4cc** [comment]
@plushu 所以可不可以仅对GET method启用该机制？

**Comment by phuslu** [comment]
还是不太想做，单靠 GET 也不能确保不出问题。

之前测 GoAgent 的时候，这个机制会导致在线网盘降低可用性。

**Comment by phuslu** [comment]
就这样了。
