### ISSUE TITLE
再次请求gae添加备用代理设置

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1349]
如果有了和gae同级的备用代理，我的纸飞机便能因此享受autorange带来的好处，gae也更严谨。求不close

**Comment by jzp820927** [comment]
你说的应该是前置代理吧。

**Comment by dou4cc** [comment]
@jzp820927 https://github.com/phuslu/goproxy/issues/1334

**Comment by distance00** [comment]
开源的软件，自己想办法添吧。社长已经说的很清楚了。

**Comment by dou4cc** [comment]
@distance00 得花时间学学go~

**Comment by distance00** [comment]
添加功能社长也得花时间，响应了一个要求，会有更多人出来提要求，又不是商业软件，社长没这个义务也没那么多时间精力吧。

**Comment by jzp820927** [comment]
你说的 “纸飞机便能因此享受autorange带来的好处，” 只要把 SS 设为 gop 的前置代理就可以了。
