### ISSUE TITLE
这是什么情况？

### ISSUE THREAD

**Issue by qiangliu8183** [phuslu/goproxy#1352]
{
    "type": "localproxy",
    "host": "[::]:8087",
    "software": "goproxy r1168 (go/devel +1686f8b Thu Dec 1 15:21:26 2016 +0000 linux/amd64)",
    "filter": "*gae.Filter",
    "error": "dial tcp4 58.64.149.17:443: socket: too many open files"
}

**Comment by phuslu** [comment]
google 一下就可以解决。
