### ISSUE TITLE
除了 YouTube 其他所有视频网站都不能完整播放

### ISSUE THREAD

**Issue by CafeTee** [phuslu/goproxy#1353]
autorange.json 中已经添加了相关域名，但还是播放几秒就自动结束。

**Comment by jzp820927** [comment]
autorange 还不完善，可以试试不用 autorange ，能不能播放。

**Comment by CafeTee** [comment]
jzp820927 请问如何关闭 autorange 呢？wiki中似乎没有关闭方法。

**Comment by phuslu** [comment]
已知问题，请等待修复。
