### ISSUE TITLE
goproxy-vps last not support "auth"?

### ISSUE THREAD

**Issue by mhohai** [phuslu/goproxy#1363]
昨天装了最新的，没有auth了
-auth string
goproxy vps auth user:pass list

同时，goproxy默认内置了证书，这个建议大家自行替换

**Comment by phuslu** [comment]
1. 支持 pwauth, 使用系统自带的 pam auth.
2. 支持从 letsencrypt 自动签署证书，使用 -acmedomain 指定 vps 的域名。这个需要你绑定一个域名。

**Comment by phuslu** [comment]
目前还支持反代自身 80 端口的网站。这样伪装性更高。

给出一个测试的 goproxy vps 代理， https://vps.phus.lu (过会删除）

**Comment by wpyok500** [comment]
标记下

**Comment by mhohai** [comment]
我需要去学习下pam auth，ip都被墙害我搬家，我还是不要域名了。

**Comment by phuslu** [comment]
不要域名的话，就得忽略证书错误了。

pam auth 很简单，就是使用你 linux 系统用户的用户名和密码。

比如 root 123456

**Comment by mhohai** [comment]
`useradd -r -s /usr/sbin/nologin USERNAME`
我不愿意用root的密码啊，复杂一小步，学到了，感谢

**Comment by mhohai** [comment]
`passwd -d root`
这下放心了，亲测可以登录。

**Comment by mhohai** [comment]
using goproxy vps open pwauth with goagent client
`fetchserver = https://user:passwd@host:port/`
brower: 
    The proxy server is refusing connections
govps error log:
    E1214 21:15:14.776788    9848 goproxy-vps.go:123] Unrecognized auth type: "Baisic"

**Comment by jzp820927** [comment]
估计得用 gop 连吧

**Comment by mhohai** [comment]
以前都是用goagent的客户端连，现在的问题只是 认证问题，认证后是可以用的，关掉认证也是可以用的。

我发出来是告诉phuslu大大，有这回事，在goproxy客户端需要考虑认证问题。

**Comment by jzp820927** [comment]
好吧，那就等 P大处理吧

**Comment by mhohai** [comment]
>
    支持从 letsencrypt 自动签署证书，使用 -acmedomain 指定 vps 的域名。这个需要你绑定一个域名。

报错：
    acme/autocert: missing certificate

怀疑证书有问题，继续。
