### ISSUE TITLE
这个如何使用？请大神帮助看一下

### ISSUE THREAD

**Issue by shawwokou123** [phuslu/goproxy#1367]
https://github.com/lovesnow/GHi

因为工作需要必须用到百度hi，但是一直没有找到linux版本的，这次在github上找到一个，但是不知道该如何使用？
大家帮助看一下如何安装使用！请写清楚步骤！
感谢！

我是ubuntu14.04

**Comment by SeaHOH** [comment]
走错地方了？

**Comment by phuslu** [comment]
建议首先求助原项目。
