### ISSUE TITLE
goproxy 运行过程中出错

### ISSUE THREAD

**Issue by MeABc** [phuslu/goproxy#1369]
ver: r1180
os: win10-64

![1](https://cloud.githubusercontent.com/assets/18194126/21050675/1169ede4-be57-11e6-9146-e7f75ba876f1.png)

这个情况重启GP就好了。

贴这个希望对修复有帮助。

**Comment by MeABc** [comment]
先关了。

社长有时间看下。 @phuslu

**Comment by phuslu** [comment]
啊啊啊啊啊，谢谢反馈。记下了。
