### ISSUE TITLE
GAE药丸？

### ISSUE THREAD

**Issue by SerCom-KC** [phuslu/goproxy#1375]
今天GAE发邮件给我说违反ToS，理由的话简单来说就是多开appid绕过流量限制。
虽然我自备了VPS，想问问各位dalao这个问题有解吗？

**Comment by jzp820927** [comment]
之前有2，3个人反映过这个问题，不过没有更多的人反映过这个问题，我也没遇到过这个问题，估计是个例吧。你是不是流量用的太快了。

**Comment by phuslu** [comment]
几年前也同样收到过这样的邮件。

不过总体来看算是个案，还未看出谷歌开始限制 GAE 的免费试用。

**Comment by SerCom-KC** [comment]
@jzp820927 我最近也没怎么看视频啊，appid都是自己用的，而且自从Google Code时代开始我就在用GAE了，一直都没出过这个问题，不知道触发了啥= =

**Comment by SerCom-KC** [comment]
@phuslu 所以……重启服务继续用？（还是另外开appid，主要是我有点怕封号……）

**Comment by yqy6611** [comment]
从来没遇到过这个问题

**Comment by jzp820927** [comment]
估计就是封 appid ，最多也就封 GAE 的使用吧，不至于封账号吧

**Comment by SerCom-KC** [comment]
好吧，反正也没收到正式的warning，估计是系统自动怀疑了一下，我还是把issue关了吧
