### ISSUE TITLE
请问同一个谷歌账号申请的同一批APPID可以同时部署到XX-NET和goproxy一起使用吗？

### ISSUE THREAD

**Issue by asd2003asd** [phuslu/goproxy#1383]
请问同一个谷歌账号申请的同一批APPID可以同时部署到XX-NET和goproxy一起使用吗？莫名其妙被封了十几个APPID，不知道什么原因。

**Comment by PvCDp** [comment]
再申请就可以了，不要过于纠结这个。

**Comment by asd2003asd** [comment]
你是说再注册一个谷歌账号然后再申请APPID吗？

**Comment by jzp820927** [comment]
XX 和 GOP 的服务端不能同时存在于一个 APPID 上，只能选择其一。

**Comment by asd2003asd** [comment]
我把同一批APPID部署到XX 和 GOP 上了，那该怎么办呢？

**Comment by jzp820927** [comment]
后面部署的，会覆盖前面的。

**Comment by PvCDp** [comment]
应该没有问题，我一直是用同一批id部署到xx和gop以及goagent，没有出现过任何问题，因为你不可能同时在一台电脑上打开任何两个，你一次一台电脑只能用其中一个。

**Comment by phuslu** [comment]
这个问题回答多次了。

不能。会导致 goproxy 卡顿。

**Comment by jasonliul** [comment]
XX 也就是旧狗, 改装成弗兰克斯坦, 有什么必要抱残守缺, 好像满清遗老...
:)

**Comment by asd2003asd** [comment]
@jasonliul 哈哈哈你这个比喻很形象，其实XX前几个月还行，只是最近慢了，也不更新了，还好有GP，不过XX的自动扫IP功能挺不错的。

**Comment by asd2003asd** [comment]
@PvCDp 我就是同一批APPID部署到XX和GP然后在WIN10和debian里分别开XX和GP的，导致被谷歌怀疑我作弊，封了十几个APPID.

**Comment by phuslu** [comment]
两者各有长短，没必要争个高下。

就事论事，goproxy 的客户端的确不合适使用 goagent 和 xxnet 的服务端。

至于泛泛而谈的，「快慢」，「稳定」 这种比较可以休矣。
