### ISSUE TITLE
我的连通率正常吗？

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1405]
`I1224 22:40:30.599077    8560 dialer2.go:99] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=21, bad_addrs=6543`

**Comment by phuslu** [comment]
我的略好一些
`I1224 22:44:28.487804     638 dialer2.go:99] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=39, bad_addrs=1800`

**Comment by dou4cc** [comment]
```
> 21/6543
0.0032095369096744614
> 39/1800
0.021666666666666667
```
差一个数量级啊

**Comment by jzp820927** [comment]
I1224 23:01:21.237322   18136 dialer2.go:99] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=4, bad_addrs=360

**Comment by phuslu** [comment]
嗯，封锁如此严厉，挺无奈的。

goproxy 只能抓住这些瞬息即逝的连接机会去收发请求，有种白驹过隙的感觉。

置身事外的角度来看，会觉得这软件非常荒诞搞笑可怜可叹。我挺喜欢一句诗词来形容 goproxy 的现状

> 蜗牛角上争名利，石火光中寄此身。

1. http://baike.baidu.com/view/262335.htm
2. http://baike.baidu.com/subview/217331/15421046.htm

**Comment by dou4cc** [comment]
@jzp820927 你不低
```
> 4/(360+4)
0.01098901098901099
```

**Comment by jzp820927** [comment]
我觉得这种设置模式还是挺巧妙的，如果按正常模式来设计，根本没法运作。

**Comment by jasonliul** [comment]
社长, 这个不是针对谷歌ip的, 台湾,星加坡的透明代理, 很明显并不专项封杀, 但也是高丢包率, 属于"有时通".
看起来内联网是手淫梦遗, 自抠自摸用的.

国外的连接, 本身已经变成摆设.

**Comment by MeABc** [comment]
> 置身事外的角度来看，会觉得这软件非常荒诞搞笑可怜可叹。

这样是不是极端了。

**Comment by wz7465** [comment]
I1224 23:29:49.421875    5864 multidialer.go:242] MULTIDIALER DialTLS2("tcp", "xx.appspot.com:443") with good_addrs=24, bad_addrs=15
sni这么好的解决方案，为何用的人少呢？

**Comment by Kisesy** [comment]
![20161224233626](https://cloud.githubusercontent.com/assets/5843694/21467684/c2c8be18-ca31-11e6-99ba-08842e9c170b.png)
这个时间没干扰了？

**Comment by dou4cc** [comment]
@jasonliul @wz7456 @Kisesy 没被电信QoS的就别秀了

**Comment by jasonliul** [comment]
@Kisesy

K主任, 圣诞快乐, 有甚么红包?

**Comment by wz7465** [comment]
@dou4cc 我这儿干扰很厉害，但是用sniproxy的方案却很好啊
![111](https://cloud.githubusercontent.com/assets/7801728/21467777/d624004c-ca33-11e6-823c-e406b74f9189.JPG)

**Comment by phuslu** [comment]
@MeABc 如有冒犯还请谅解。我真的觉得 goproxy 是个勉强续命之作，其最大作用也许是来浇我胸中块垒罢了。

有篇文章很不错，转出来共享一下。

《不要怂》http://weibo.com/ttarticle/p/show?id=2309404055619761002120

**Comment by phuslu** [comment]
@jasonliul 谢谢。:)

**Comment by MeABc** [comment]
说到冒犯这个倒没有。

只是自己喜欢的东西被人说成一文不值，那是个什么心情。

goproxy 还有很多好的地方，如 vps ssh 。就没有人发现吗。只能说 gae 的风光盖过了她们。

**Comment by jzp820927** [comment]
不是 gae 盖过了她们。是 免费 盖过了 收费。

**Comment by MeABc** [comment]
> 是 免费 盖过了 收费。

这是大实话。

**Comment by jzp820927** [comment]
看看国内，什么免费的东西，不是一窝蜂的抢，所以吧。。。。此处省略一万字。。。

**Comment by Kisesy** [comment]
@jasonliul 哈哈，必须有啊，你随便找个邮箱往我邮箱里发个邮件，我给你些IP测试一下
alresvor@gmail.com

**Comment by jasonliul** [comment]
@Kisesy 
俺的ip也多得用不完... 噗哈哈
jasonliul@yandex.com

**Comment by yDan** [comment]
看者有份，发点ip给我，yangdan315623544@gmail.com

**Comment by kirbyzhu** [comment]
社长的微博暴露了不少私人信息啊

**Comment by kirbyzhu** [comment]
@wz7465 在arukas架了个sni，但是还是不知道怎么把它用起来。endpoint还是app分配的地址？另外还有系统分配的端口呢
