### ISSUE TITLE
☆ 印尼最新白金免费SSH

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1413]
**Free SSH service [Updated]**
http://skyssh.com/
https://sshdropbear.net/
http://speedssh.com/
https://fastssh.com/
http://www.mytunneling.com/
http://createssh.com/
https://bestvpnssh.com/
http://contassh.com/
http://www.sshagan.net/
http://sshfree.net/
http://www.portssh.com/
http://www.jetssh.com/
http://sshudp.com/
http://www.vpnjantit.com/
https://fullssh.com/
https://sshandroid.com/
http://www.globalssh.net/server/SSH
http://free-ssh.xyz/
http://cloudssh.us/

Credit to FD:FRS [Indonesia]

**Comment by jzp820927** [comment]
J大威武。

**Comment by wpyok500** [comment]
mark

**Comment by sishentibu** [comment]
mark

**Comment by jasonliul** [comment]
[U][B]Bitvise SSH Client v7.21[/B][/U]
[url]https://bvdl.s3-eu-west-1.amazonaws.com/BvSshClient-Inst.exe[/url]

Old Windows
[url]https://bvdl.s3-eu-west-1.amazonaws.com/BvSshClient-Inst-sha1.exe[/url]

**Comment by Yamazaki-wu** [comment]
速度马克

**Comment by horizonl** [comment]
马克

**Comment by jasonliul** [comment]
端午更新~
