### ISSUE TITLE
上传appid的时候总是出现这样的界面

### ISSUE THREAD

**Issue by jianglwei** [phuslu/goproxy#1420]
![Up
![1](https://cloud.githubusercontent.com/assets/23209020/21601280/89d7fe40-d1c3-11e6-868f-4d238acf48f9.png)
loading 1.png…]()

**Comment by jianglwei** [comment]
![1](https://cloud.githubusercontent.com/assets/23209020/21601282/95e84c8a-d1c3-11e6-88e3-5671ebbfc5fe.png)

**Comment by Alvin9999** [comment]
参考此帖https://github.com/XX-net/XX-Net/issues/4720
原因为是现在部署appid时，appid的位置要单独设置才行，不然不算有效的appid

**Comment by blob2015** [comment]
个人的经验：三更半夜，然后用yt之类的使用一阵子，就相对顺畅些。或者直接用vpn。

**Comment by jianglwei** [comment]
@Alvin9999 用xxnet里方法注册的账号还是没有上传成功，反倒是好多年前的旧appid上传的很顺利。

**Comment by jzp820927** [comment]
你这个应该是 appid 有问题，请仔细检查。

**Comment by caofengzi** [comment]
1代理有問題，2看看每個appid是否都用”|“隔開了。
