### ISSUE TITLE
OS X使用报错

### ISSUE THREAD

**Issue by Sec20** [phuslu/goproxy#1422]
版本：r1232
浏览器：Chrome
报错内容：
ERROR: logging before flag.Parse: F0104 20:08:25.724923    1438 gae.go:99] storage.ReadJsonConfig("gae.json") failed: invalid character 'Ã¢' looking for beginning of value
goroutine 1 [running, locked to thread]:
github.com/phuslu/glog.stacks(0xc42007a000, 0xc4201201c0, 0x8a, 0xe0)
	/tmp/goproxy.170104.25254/gopath/src/github.com/phuslu/glog/glog.go:784 +0xa7
github.com/phuslu/glog.(*loggingT).output(0x17bc260, 0xc400000003, 0xc4200a9130, 0x177428f, 0x6, 0x63, 0x0)
	/tmp/goproxy.170104.25254/gopath/src/github.com/phuslu/glog/glog.go:735 +0x312
github.com/phuslu/glog.(*loggingT).printf(0x17bc260, 0xc400000003, 0x1566d85, 0x26, 0xc420035f28, 0x2, 0x2)
	/tmp/goproxy.170104.25254/gopath/src/github.com/phuslu/glog/glog.go:655 +0x14f
github.com/phuslu/glog.Fatalf(0x1566d85, 0x26, 0xc420035f28, 0x2, 0x2)
	/tmp/goproxy.170104.25254/gopath/src/github.com/phuslu/glog/glog.go:1163 +0x67
_/tmp/goproxy.170104.25254/goproxy/httpproxy/filters/gae.init.1()
	/tmp/goproxy.170104.25254/goproxy/httpproxy/filters/gae/gae.go:99 +0x18f
_/tmp/goproxy.170104.25254/goproxy/httpproxy/filters/gae.init()
	/tmp/goproxy.170104.25254/goproxy/httpproxy/filters/gae/gaetransport.go:137 +0xca
_/tmp/goproxy.170104.25254/goproxy/httpproxy.init()
	/tmp/goproxy.170104.25254/goproxy/httpproxy/httpproxy.go:140 +0xac
main.init()
	/tmp/goproxy.170104.25254/goproxy/main.go:89 +0x6c
![2017-01-04 20 09 36](https://cloud.githubusercontent.com/assets/21214203/21641907/d5b45a74-d2b9-11e6-8627-08f49aff9411.png)

**Comment by phuslu** [comment]
gae.json 有不合法字符。

**Comment by Sec20** [comment]
@phuslu 我的gae.json下载下来就没动过，请教问题出在哪里。

**Comment by phuslu** [comment]
那看一下 gae.user.json 是否有不合法(非json)的字符呢

**Comment by Sec20** [comment]
@phuslu 我就在引号里面加过一个AppID和一个密码，都是字母和数字的组合，是这个问题吗？

**Comment by phuslu** [comment]
不确定，你把 gae.user.json.example 重命名为 gae.user.json 然后在编辑试试。

**Comment by Sec20** [comment]
@phuslu 如果我吧Windows版上的gae.user.json复制过来也没有可能解决？

**Comment by szh7379** [comment]
.json通用的

**Comment by Sec20** [comment]
@phuslu @szh7379 那么我过几天回家试试

**Comment by du-xin** [comment]
@USCOB 我今天也出这个错了，经 @phuslu 提醒在gae.user.json这个文件找到的。这个错误字符说的是中文的双引号引，在macos下修改文件的时候，自带的文本编辑器默认会自动把英文双引号给换成中文的双引号，在这个文本编辑器下面很难发现，中文的是有一点斜的，英文的是没有倾斜的，应该是设置里面的”智能引号“选项引起的，避免出错，换个高级一点的编辑器。注意检查一下gae.json和gae.user.json这两个文件。

**Comment by USCOB** [comment]
@du-xin 是这样啊，谢谢了，我也怀疑是编辑器的问题，就是一直没找到问题。
