### ISSUE TITLE
goproxy上不了网

### ISSUE THREAD

**Issue by cctvass** [phuslu/goproxy#1427]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1247 (go/devel +8f47dda Fri Jan 6 04:08:36 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "dial tcp 216.58.209.133:443: i/o timeout"

**Comment by yaoguaishou** [comment]
这是ip的问题，和goproxy无关

**Comment by cctvass** [comment]
多谢

**Comment by cctvass** [comment]
我是用heroku搭建的 是不是说明成功了？

**Comment by jzp820927** [comment]
你是用 php？还是 GAE ？
