### ISSUE TITLE
GoAgent和ShadowSocks移除GitHub代码 被EFF报道了

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#143]
https://www.eff.org/deeplinks/2015/08/speech-enables-speech-china-takes-aim-its-coders
@phuslu @Clowwindy

https://zh.wikipedia.org/wiki/电子前哨基金会

**Comment by xyuanmu** [comment]
共匪从来不用担心事情闹大，作为全世界最富有的政府，国债可以化解不少危机。

**Comment by aOJzQT** [comment]
Technologists like Phus Lu, Clowwindy and Xu Dong are now facing the same political scrutiny and intimidation in authoritarian regimes as independent writers, publishers, poets or journalists did in Solzhenitsyn’s time. Code is speech: and using police intimidation to compel these creators to delete their code repositories is as serious a violation of human rights law as compelling a writer to burn his or her own books.

世界上的共匪都是邪恶的独裁化身，它们从不担心把事儿闹大，它们有坦克，屁民好怕怕

**Comment by phuslu** [comment]
github 因为在墙内，并且五毛较少，大家措辞请温和一些。
