### ISSUE TITLE
墙在维护？

### ISSUE THREAD

**Issue by NAVrasZ** [phuslu/goproxy#1432]
现在没开代理直连YouTube、Facebook、t411，延迟小基本像国内一样秒开~而且貌似都能开并不是特例
![image](https://cloud.githubusercontent.com/assets/20354364/21779602/571af352-d6e3-11e6-8cc2-9a88eecca560.png)

**Comment by mixool** [comment]
应该是你有改hosts或者dns吧。

**Comment by NAVrasZ** [comment]
whoops...确实
忘了之前为了直连改了dns
