### ISSUE TITLE
Red Hat Enterprise Linux 7 如何导入证书到系统

### ISSUE THREAD

**Issue by riumiyama** [phuslu/goproxy#1434]
如题：）
Firefox 导入很简单 但是怎么导入到系统呢 直接双击导入 后没效果 我想用Google Chrome 謝謝大家

**Comment by lucifercn** [comment]
chrome 的设置里面 高级设置  证书管理  导入

**Comment by jzp820927** [comment]
就是双击导入，估计要不就是你导错区域了，要导入到 根证书。

**Comment by riumiyama** [comment]
嗯 姑且能用了  但是应用市场打不开 想全局代理怎么设置能让系统下载软件呢

**Comment by riumiyama** [comment]
![screenshot from 2017-01-12 19-10-27](https://cloud.githubusercontent.com/assets/18358396/21887486/ed4ad9cc-d874-11e6-9d9b-54ff83aa5dd2.png)

**Comment by jzp820927** [comment]
不知道环境变量管不管用。

**Comment by riumiyama** [comment]
刚不小心点了Close and comment 出现一个禁止符号吓屎我了  哎阴纹不好就是不方便啊
