### ISSUE TITLE
由于PyObjC3.2更新，导致goproxy-macos.command运行异常的解决

### ISSUE THREAD

**Issue by xn1924** [phuslu/goproxy#1443]
http://pythonhosted.org/pyobjc/core/changelog.html

**Comment by xn1924** [comment]
@objc.python_method
    def parseLine(self, line):

**Comment by phuslu** [comment]
谢谢

**Comment by phuslu** [comment]
如有可能，希望能提交一个 pull request

**Comment by xn1924** [comment]
没问题

**Comment by xn1924** [comment]
@phuslu 该issue是在r1152出现的，由于#!/usr/bin/env python 使用了我本机中高版本python和pyobjc，导致def parseLine(self, line):的语法在pyobjc3.2中不兼容，需要在前面加上@objc.python_method。
而当前版本r1262使用!/usr/bin/python调用系统自带python，不存在该issue。

**Comment by phuslu** [comment]
多谢定位。那就先保持这样吧。谢谢。

**Comment by xn1924** [comment]
客气😄😄😄

**Comment by riumiyama** [comment]
我以为是我系统有问题呢  只能用终端机运行

**Comment by riumiyama** [comment]
我以为是我系统有问题呢  只能用终端机运行

**Comment by phuslu** [comment]
把 parseLine 改名成 parseLine_ 了，https://github.com/phuslu/goproxy/commit/90f7396320c82d1544923dfe215ed0f9f0bd3719

貌似是一个比较友好的改法。
