### ISSUE TITLE
403问题

### ISSUE THREAD

**Issue by cdmask** [phuslu/goproxy#1446]
用google.dk搜索有时候会出现403问题，之前都没有出现的，最近经常出现。
版本号GoProxy r1266 
平台Windows 7 64 bit
浏览器Chrome
![image](https://cloud.githubusercontent.com/assets/11484898/22056383/d8ac9e3a-dd9a-11e6-87a0-e6a84e673d4b.png)
![image](https://cloud.githubusercontent.com/assets/11484898/22056506/5ddf49c2-dd9b-11e6-9b97-67b31d194ab5.png)

**Comment by phuslu** [comment]
google.dk 的话，加入 SiteAlias 试试。

**Comment by cdmask** [comment]
嗯，可以了。
