### ISSUE TITLE
这速度十分赞！

### ISSUE THREAD

**Issue by Alvin9999** [phuslu/goproxy#1448]
![gop](https://cloud.githubusercontent.com/assets/12132898/22088198/4264f660-de1d-11e6-8d1b-6b690d973fc0.PNG)

移动网络，早上测速。这比收费的ss还要好。

发帖主要是高兴软件的优异表现以及感谢一下社长的辛苦付出。

**Comment by TangBaohua** [comment]
怎么你窗口上的图标是这个了？

**Comment by phuslu** [comment]
谢谢鼓励。

移动线路目前仍然很好，用啥软件都很快， 尤其是早晨。goproxy 只是适逢其会罢了，没啥。

**Comment by wpyok500** [comment]
这段时间也比前段时间好，移动网络一直多很好，用其他软件也是一样。早晨时电信网络也好。

**Comment by Alvin9999** [comment]
@TangBaohua  这是和谷歌浏览器绑定了，然后弄了个一键启动程序，所以图标变了，但本质没变
@phuslu  不管怎样，我十分满意，感谢！
