### ISSUE TITLE
问下万能的Go友，夜间流量过大被ISP掐网如何避免

### ISSUE THREAD

**Issue by NAVrasZ** [phuslu/goproxy#1450]
第二次碰到这种情况，移动宽带，
移动fq炒鸡方便，简单的dns+goproxy差不多就能满速，昨天先是在youtube上看了几小时4k，后来又bt下BBC电视剧（嗯，就是那个...），下载超快的后果就是下载远大于上传
结果突然就断网了....
第一次碰到这个问题客服说是我路由器问题要我关十分钟再开（其实我已经知道...）这次因为大晚上没打客服，自己关路由器等待和恢复出厂设置均显示无网络，于是证明是机房的问题
早上9点工作人员上班，我啥没干宽带自己就恢复了，更明显表示就是我流量过大下载大于上传被掐了网
以前规避的方式是一直挂着种子让它传个几百G上去，我就每天能放心使用。但这月忘了这事结果就翻了船...
所以如何避免这种情况呢？isp通过网线连我，tor会有用吗？

**Comment by NAVrasZ** [comment]
移动有时还通过限速下载不限上传的方法，强行达到下载100G上传500G的效果...这个有解吗？

**Comment by PvCDp** [comment]
请问DNS+gop怎么用？

**Comment by SeaHOH** [comment]
isp 不都喜欢尽量限制上传嘛，移动反而鼓励？
你是不是搞错了，可能人家客服没骗你。

**Comment by NAVrasZ** [comment]
@PvCDp 咱就用了萌新友好型的dowsDNS开局域网共享（发现够用就没折腾了，貌似还有蛮多？），外加一枚moguDNS。局域网dns加goproxy的remoteDNS列表，moguDNS有延迟没加。
@SeaHOH 移动在这片新开，接的网线也是新的，来抢电信的地盘，电信上传500k，移动上下对等，二是用了电信的出口带宽，估计是按流量算双方收费，当然只进不出最好233

**Comment by PvCDp** [comment]
@NAVrasZ 我是小白，弄不明白，多谢。

**Comment by jap33** [comment]
现在移动在bt和科学上网时有时确实会断网﹝一般在后半夜上网人少时、断网时整个小区都断也许是共享的原因﹞，其他时间会时不时出现无网络连接2-3秒钟的情况。

**Comment by jap33** [comment]
移动上下行确实20m对称的，有两个出口上海和香港都是移动自己的网，所以bt下载都非常快。

**Comment by jasonliul** [comment]
移动前一阵百毒云根本跑不动.

不过使用代理断网, 没有遇见过, 无须疑神疑鬼

**Comment by jasonliul** [comment]
@jap33 

教授, 揪住先...
俺的纸飞机又断炊鸟, 近期有什么好介绍

**Comment by jap33** [comment]
http://shadowsocks.gzxultra.xyz/user
843 	ba1VfdlTndVRKPcgOnAG86Rfc2aAbJUt 	可用
844 	6jwgJjcbnAHCsPhwBti6wkJcNxc9DmRj 	可用
845 	pEzyQ7pz0ufqvzZnCGhCZmxDmFE8avCd 	可用
846 	SjULBJfR3UXdYIwgk7t6NXfyqgYXkhSB 	可用
847 	yIpktepz54mmrC1SMMfXt94t81HwovFG 	可用

**Comment by jasonliul** [comment]
@jap33 

多谢, 俺觉得还是这种冷门可靠, 过热的提供商变得很快.

**Comment by jap33** [comment]
https://plus.google.com/u/0/communities/103542666306656189846

**Comment by jasonliul** [comment]
俺之前用这几个
[url]https://plus.google.com/communities/104092405342699579599[/url]
[url]https://plus.google.com/communities/117702818760720009772[/url]
[url]https://plus.google.com/communities/109962494203239446911[/url]

果然还是教授懂行情...

**Comment by jap33** [comment]
现在一直用这个  https://github.com/wangchunming/2017hosts

**Comment by jasonliul** [comment]
@jap33 
俺一般用就是黄狗+ssh, 无限流量, 不过纸飞机总归还得有.
不然老夫没法"左牵黄, 右擎苍"

**Comment by jap33** [comment]
第一个hosts连香港服务器可直连也可走代理。

**Comment by jasonliul** [comment]
@jap33 
国内网站俺基本就不玩, 除了偶尔美剧

**Comment by jap33** [comment]
@jasonliul 
哪hosts不就是直接翻吗！

**Comment by distance00** [comment]
@NAVrasZ 你的意思是如果上传大于下载，结算的时候电信还要向移动付费？问题是移动用电信的出口，电信又不需要用移动的网络，为什么会跟移动这么结算？

**Comment by NAVrasZ** [comment]
@distance00 bt下载国外时走电信即电信传入移动，那我上传时就是移动传入电信。跨isp流量费

**Comment by SeaHOH** [comment]
那就投诉移动，这跟你和移动的合同又不相干。

**Comment by NAVrasZ** [comment]
😂我也想，但是好麻烦_(:з」∠)_
今天营业厅说是触发异常被锁可打客服解（摔

**Comment by jap33** [comment]
现在打开bt从连接的节点中路由追踪了几个节点。
![default](https://cloud.githubusercontent.com/assets/15140842/22174759/b020463c-e020-11e6-909f-0655261ecb0c.JPG)
![jpg1](https://cloud.githubusercontent.com/assets/15140842/22174760/b2cd4056-e020-11e6-8d6c-3dc2b08dbf39.JPG)

**Comment by distance00** [comment]
@NAVrasZ 电信干扰最严重，如果移动用电信国际出口，不知为何移动fq效果更好？即使用户上传也可以算成电信访问移动的流量，这也只是国内流量，而移动在耗费电信的国际流量，向国外isp传流量也是同样的结算办法吗？感觉合理的解释是国际间也这样结算，但你得保证你上传到了国外，这样电信才不吃亏。挂bt恐怕大部分传到国内了吧？

**Comment by NAVrasZ** [comment]
@distance00
电信干扰自家人（而且还是等级不高的那些—用户
移动原来是有自己出口，楼上教授的回复～
国际流量是他们和外国之间isp计费了
最后一句说的是移动大号局域网嘛233，我的连接解析显示是国外的（utorrent论坛上下的flags），然后…国内人追剧不大都是什么第三手分发网站的各种盘各种二压三压广告标版本嘛(･ัω･ั)

**Comment by hcym** [comment]
没有这么玄乎吧

触发异常被锁

那我不是天天触发异常

而且一直觉得电信除了广告丧心病狂

对代理带宽还是够量

**Comment by blob2015** [comment]
@jap33 
教授很强大啊 🍻

**Comment by hcym** [comment]
挖矿井
