### ISSUE TITLE
1273, 最近狗鞭木新闻, 减少内存占用

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1451]
...........

不知道近期狗鞭新花式............

**Comment by phuslu** [comment]
都是些修修补补

1.  goproxy-gui.exe 优化了编译，这样杀毒软件现在误报了。
2.  goproxy-gtk.py 优化了快捷方式生成。
3.  goproxy-macos 提供的 app bundle, 右键菜单功能大大增强。

**Comment by jasonliul** [comment]
社长, 小年啤酒烤肉不可少.
:)

**Comment by phuslu** [comment]
小年快乐 😸

**Comment by phuslu** [comment]
r1273 倒是有个改进，减少内存占用了。变相也算提高效率吧（虽然没有感觉。。。）

**Comment by jasonliul** [comment]
@phuslu 
果然社长懒蛋鸟~~
:)

**Comment by phuslu** [comment]
r1275 修复 auth 功能，现在 auth 能用了。cc @jzp820927

**Comment by jzp820927** [comment]
@phuslu 感谢社长大人，我终于可以在外网做认证了。

**Comment by jzp820927** [comment]
刚刚测试已经没有问题了，还有个意思，我看到 PHP 没有 auth 相关配置，是 PHP 不支持认证么？

**Comment by phuslu** [comment]
应该也支持的，请试下。

**Comment by jzp820927** [comment]
好，那我试试。

**Comment by jzp820927** [comment]
@phuslu 感谢社长大人提醒，经测试，PHP 的 auth 也没问题。auth 算是完美了，社长大人幸苦了！

**Comment by wangbingqian** [comment]
@phuslu  Mac下开始转菊花了，最近的版本出现的

**Comment by riumiyama** [comment]
不知道怎么回事 Mac 下新版无法运行   我现在退回到1250

**Comment by phuslu** [comment]
不能复现。如果不是个案的话，请提供更多信息。

**Comment by riumiyama** [comment]
![screen shot 2017-01-22 at 12 22 40 am](https://cloud.githubusercontent.com/assets/18358396/22175509/524e0c60-e039-11e6-92cf-00bcf87480d3.png)
![screen shot 2017-01-22 at 12 23 12 am](https://cloud.githubusercontent.com/assets/18358396/22175510/5b201720-e039-11e6-9a2d-f97e4845e497.png)
![screen shot 2017-01-22 at 12 25 10 am](https://cloud.githubusercontent.com/assets/18358396/22175511/5e688f7a-e039-11e6-9c82-2c61acfac7aa.png)

**Comment by phuslu** [comment]
可能是 10.12.2 的兼容性问题。

能否在 Terminal 下，执行 `/usr/bin/python2.7 -x goproxy-macos.commnd` 看下是什么错误？

**Comment by riumiyama** [comment]
Last login: Sun Jan 22 00:46:15 on ttys000
riumiyamas-Mac:~ riumiyama$ /usr/bin/python2.7 -x goproxy-macos.commnd
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'goproxy-macos.commnd': [Errno 2] No such file or directory
riumiyamas-Mac:~ riumiyama$

**Comment by phuslu** [comment]
呃，是需要 `cd` 到 goproxy 所在的目录下执行。

**Comment by riumiyama** [comment]
抱歉 本人小白
Last login: Sun Jan 22 00:57:33 on ttys002
riumiyamas-Mac:~ riumiyama$ cd /Applications/GoProxy.app/Contents/MacOS
riumiyamas-Mac:MacOS riumiyama$ /usr/bin/python2.7 -x goproxy-macos.commnd
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'goproxy-macos.commnd': [Errno 2] No such file or directory
riumiyamas-Mac:MacOS riumiyama$

**Comment by phuslu** [comment]
汗，我的错。是 `/usr/bin/python2.7 -x goproxy-macos.command`

**Comment by riumiyama** [comment]
![screen shot 2017-01-22 at 2 04 06 am](https://cloud.githubusercontent.com/assets/18358396/22176165/26eb0902-e047-11e6-926b-bad5fee1c1c6.png)
![screen shot 2017-01-22 at 2 05 15 am](https://cloud.githubusercontent.com/assets/18358396/22176166/3ed69a5e-e047-11e6-8e22-9fde757f256c.png)

**Comment by phuslu** [comment]
谢谢。

**Comment by phuslu** [comment]
谢谢，找到问题所在了，最后请再次执行以下 `scutil --proxy` 看看。方便我修复这个问题。

**Comment by riumiyama** [comment]
riumiyamas-Mac:MacOS riumiyama$ scutil --proxy
<dictionary> {
  ExceptionsList : <array> {
    0 : *.local
    1 : 169.254/16
  }
  FTPPassive : 1
}
riumiyamas-Mac:MacOS riumiyama$ 

谢谢 辛苦了

**Comment by phuslu** [comment]
r1280 应该已经修复了。

**Comment by riumiyama** [comment]
嗯 跑起来了

**Comment by Sak1tama** [comment]
@jzp820927 gop居然悄悄支持了auth 唉，xx这样下去要落后时代了，

**Comment by jzp820927** [comment]
@Sak1tama 早就知道了，只是一种有 bug，而且现在我测试也有 bug。

**Comment by phuslu** [comment]
@Sak1tama 少做宏观上或主观上比较吧，这太容易造成 FUD 的映像 https://github.com/phuslu/goproxy/issues/1468#issuecomment-277151837 ，进而给 goproxy 招黑。

**Comment by jasonliul** [comment]
@phuslu 

社长, 这是国人"穷骨头发烧 --爱折腾", 疑心生暗鬼.
由他们去罢

**Comment by SeaHOH** [comment]
@phuslu 
还是忍不住要说一句，这是马甲口牙，两边黑。社长还记得两天前删的帖吗？也是马甲。
还有那啥做得太过份了，@breakwa11 声讨他不？

**Comment by breakwa11** [comment]
没懂，说的什么？

**Comment by SeaHOH** [comment]
你不是删掉了吗，他发的帖子。

**Comment by jasonliul** [comment]
@SeaHOH 

骚黏, 破袜酱有一种雌性掠食者的能量场...
不要舍生取义. :)

**Comment by phuslu** [comment]
@breakwa11 破娃酱，你来晚了，现场已经没了。 -_-

**Comment by SeaHOH** [comment]
对了，他又删自己的回复了。是 @Sak1tama

**Comment by breakwa11** [comment]
这人我已经block了，不必理那种

**Comment by SeaHOH** [comment]
@jasonliul 
我已经到了不会尴尬癌你取名的级别啦，摸摸大~

**Comment by SeaHOH** [comment]
@breakwa11 
我猜到那人的大号了，发给你不？还是公布？

**Comment by breakwa11** [comment]
私发我？

**Comment by SeaHOH** [comment]
我 Gmail 用户名一样，要就给我发个邮件。

**Comment by breakwa11** [comment]
有twitter嘛？

**Comment by SeaHOH** [comment]
没……

**Comment by breakwa11** [comment]
那算了，直接说好了

**Comment by SeaHOH** [comment]
好吧，我是怀疑某人
1、讲话方式比较像
2、同样喜欢删回复
3、居然 follow 了马甲
4、马甲名字也比较接近（可能是我想多了）
就这几点，不算严谨。觉得这样可以讲出来吗？

**Comment by breakwa11** [comment]
我知道你说谁了，并不像

**Comment by SeaHOH** [comment]
OK，我也删

**Comment by Sak1tama** [comment]
@SeaHOH 我看到了

**Comment by SeaHOH** [comment]
哇，鬼啊~～
果然是马甲嘛？说删就删。
