### ISSUE TITLE
关于autorange这块的问题

### ISSUE THREAD

**Issue by playnetcn** [phuslu/goproxy#1452]
现在看网页和youtube视频基本没啥问题，但是有一些网站的视频就存在播放一会就卡住了，刷新页面或者重启程序也不好用，如果这块解决了就完美了，以前都说autorange导致的，但是一年左右了，也没看作者改这块，想咨询一下是啥原因。

**Comment by phuslu** [comment]
因为我平时不怎么看 YouTube，所以动力不够。😂

**Comment by phuslu** [comment]
不过我觉得也快了，我打算给我宝宝看 youtube kids 频道。初步方案打算用移动宽带和 goproxy  
到时候如果 youtube 高清视频不给力的话，autorange 的优先级应该会很高了 :trollface:

**Comment by playnetcn** [comment]
@phuslu 记得这事就行，希望以后给开发一下，新年快乐。

**Comment by jasonliul** [comment]
@phuslu 
恭喜!

问题其实是ip, 谷云ip被很多网站视为恶意, 人机验证也多.

**Comment by riumiyama** [comment]
滥用严重啊  好多用来发辣鸡信息
