### ISSUE TITLE
天朝全面搞死VPN

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1456]
http://www.scmp.com/news/china/policies-politics/article/2064587/chinas-move-clean-vpns-and-strengthen-great-firewall

看来俺们万狗狂奔的日子不远咧~~

**Comment by jzp820927** [comment]
有木有翻译稿？

**Comment by asd2003asd** [comment]
@jzp820927  直接用谷歌的翻译，翻译的挺好的。

**Comment by asd2003asd** [comment]
中国通过宣布未经授权的VPN服务非法来收紧大防火墙
移动意味着所有有线和VPN服务需要事先政府批准，并且随着北京在权力改组党代会前加紧审查

北京已经启动了一个为期14个月的全国范围的运动，打击未经授权的互联网连接，包括虚拟专用网（VPN）服务，允许用户绕过该国臭名昭着的“大防火墙”。
工业和信息化部星期天发布的通知称，大陆的所有特殊电缆和VPN服务都需要事先获得政府批准，这使得大多数VPN服务提供商都是非法的。

该通知说，国家互联网连接的“清理”将立即开始，直到2018年3月31日。

中国的网络安全负责人保证对西方领导层的忠诚

“中国的互联网连接服务市场...有需要紧急监管和治理的发展无序的迹象，”该部说。

打击不受监管的互联网连接旨在“加强网络空间信息安全管理”。

包括Vypr和Express在内的主要VPN服务公司表示，他们知道这个问题。

虽然Vypr的代表说，该公司目前正在努力解决这个问题，来自Express的代表Dane说，他的公司很快就会在其博客上发布官方声明。

根据Greatfire.org的调查，中国在全球顶级网站（包括谷歌，Facebook，Twitter和YouTube）排名中，阻止了1000个网站中的135个网站的访问，该网站监控大陆的网络审查。

因此，大陆的许多互联网用户依靠VPN服务访问被阻止的站点和服务。因此，猫和鼠标游戏已经在当局和VPN服务提供商之间进行了多年。

上一次对VPN的主要打击是在2016年3月在北京举行的全国人民代表大会上。许多公司抱怨他们的付费VPN服务不能运行一个星期。

中国网络安全法可能损害在大陆经营的外国公司，亚洲金融机构负责人说

北京的网上信息审查其互联网访问控制是特别警惕在2017年的一次在一个十年电力洗牌党的代表大会
，分析师说。

中国网络空间管理局负责监管互联网并担任网络审查办公室，对1月5日习近平主席领导的共产党领导人表示忠诚。

主席团官员发表声明说，他们今年的优先事项之一是培育一个“有利于第十九届成功大会”的在线环境。

两天前，一个自由智囊团运作的两个网站，连同15个其他网站，关闭了，因为控制紧缩党的代表大会。

最新的打击在互联网上引起了轰动，许多社交媒体用户抱怨他们的VPN服务失败或减慢。一些人表示担心失去与外界的接触或担心安全部队对使用VPN系统负责。

一个微博用户写道：“很多人都在笑（美国总统唐纳德）特朗普在墨西哥附近修建一堵墙，而我们不知道我们已经在加厚我们自己的墙。我们越监视，我们越失去。

**Comment by jzp820927** [comment]
好吧，翻译了一下，大概看懂了，看来又向大局域网靠近了一步。

**Comment by asd2003asd** [comment]
哈哈哈，没事的，有什么能阻挡技术的进步，只不过是痴人说梦罢了，万里长城还在，然而...

**Comment by jzp820927** [comment]
确实，对于我们这些懂技术的，确实没啥用，主要是阻挡了小白的脚步。

**Comment by SeaHOH** [comment]
主要影响手机，PC 可以无视。公司线路更不影响，申请就是了。

**Comment by jzp820927** [comment]
手机上 SS 完全可以代替 为皮恩，而且 SS 比对 为皮恩，还有智能路由的优势。

**Comment by SeaHOH** [comment]
vpn 用户更多些，SS 资源较少。

**Comment by jzp820927** [comment]
这个到是事实，为皮恩 比较大众化，而且手机默认自带 VPN 客户端，估计这就是为什么 为皮恩 封锁这么厉害的原因。

**Comment by asd2003asd** [comment]
还有SSR混淆协议，这个牛逼。

**Comment by blob2015** [comment]
@SeaHOH 
是啊，多了很多很多

**Comment by blob2015** [comment]
@jasonliul 
J哥，阿里云多线Ip是啥来着？

**Comment by magnet1215** [comment]
@jzp820927 hello，我这儿有160G 的x-tunnel流量，有效期还有半年，你要不要呀?

**Comment by jasonliul** [comment]
@blob2015 
什么乱七八糟?

**Comment by blob2015** [comment]
@jasonliul 
ip啊……
分类法对应的是诸如电信之下的ip，联通之下的ip。
搞不清楚，所以问问。试了下，能用，难道是阿里云之下的ip？比如103.233.37.54，95.168.222.153，嗯，好像俺一般也能用。

**Comment by jzp820927** [comment]
@magnet1215 发来吧， jzp820927@hotmail.com

**Comment by jasonliul** [comment]
103.233.37.54，95.168.222.153
菲律宾,捷克的Gip

**Comment by SeaHOH** [comment]
现在都是多放些 IP 然后自动筛选，怎么都差不多，习惯了。
干扰小的 IP 很少，其中很多是 SNI。
也有只支持谷歌的 SNI，是不是 GGC 不知道，但速度很好，比如澳门的那个。

**Comment by jasonliul** [comment]
x-tunnel 是什么?

提供商死翘翘, 搞得绿凤凰, puff的https都没了, 少了两件玩具.

**Comment by jzp820927** [comment]
@jasonliul x-tunnel 是 XX 的组件，楼上的发错地方了。
怪不得我说 puff 的 https 怎么用不了了。

**Comment by blob2015** [comment]
@jasonliul @SeaHOH 
这样啊
