### ISSUE TITLE
最新版不能观看youtube

### ISSUE THREAD

**Issue by dwbii** [phuslu/goproxy#1461]
换回旧版就可以

见图
<img width="606" alt="default" src="https://cloud.githubusercontent.com/assets/18597768/22321941/8fc28fa6-e3d3-11e6-8973-a40b391e9dfd.PNG">

**Comment by phuslu** [comment]
你怎么访问 goagenta.appspot.com 了？

基本上是新版没配置好。

**Comment by dwbii** [comment]
我没有改动，请教要设置哪里？

**Comment by dwbii** [comment]
还有，换回旧版能播放

**Comment by dwbii** [comment]
都是默认设置

**Comment by dwbii** [comment]
刚升级到r1287
现在正常了
原因不明
