### ISSUE TITLE
nas上运行的gop，pc如何远程查看状态？

### ISSUE THREAD

**Issue by magnet1215** [phuslu/goproxy#1468]
nas上运行的gop，pc如何远程查看状态？比如查看版本号，查看Goodip的数量等等？

**Comment by phuslu** [comment]
然而并没有。:trollface:

目前只能登陆到 nas 上看 goproxy 日志，暂时没有太好的想法改动这块。

的确还需改进，但是需要想好一个不会增加复杂度的方法。

**Comment by magnet1215** [comment]
@phuslu 谢谢社长回复。
其实只要有自动搜ip的功能，显示Goodip的功能就不需要了。嘿嘿
原本用xxnet，刚转来gop，所以总害怕ip会不够。

**Comment by phuslu** [comment]
那你放个数千个 IP 就没这个烦恼了，目前 goproxy 的 IP 筛选效率还可以，我的体验是可以比较轻松的处理万级别一下的 IP。

**Comment by blob2015** [comment]
社长不喜欢复杂啊，之前检测网络也是 :grinning:

**Comment by phuslu** [comment]
复杂度是个双刃剑，会不小心成为软件生命周期的敌人。

ss 之所以参与者众多，呈现百花齐放的局面，最大的优势就是在于它本身足够简单。

 GAE 因为原理限制，不得不做的比较复杂。在这种情况下，就小心添加复杂度了。
我给 xx-net 的评语在 https://github.com/XX-net/XX-Net/issues/4712#issuecomment-268139376 其实这个评语也是对之前做 goagent 的一个反思。

**Comment by magnet1215** [comment]
@phuslu 开发我不懂，但使用上同样在nas共享，gop的效果高的不是一点半点。内网同时好几个设备访问都感觉不累。

**Comment by phuslu** [comment]
运行效率的差异除了软件自身的实现有关，和时段，运行商都有关系。

泛泛而谈的比较容易引起 FUD, 不要如此谈论。
