### ISSUE TITLE
用goproxy看youtube视频经常出现断流现象

### ISSUE THREAD

**Issue by xiaomage2000** [phuslu/goproxy#1471]
用goproxy看youtube视频常常需要等很长时间才能载入播放器，而且经常出现断流现象。
google ip都是刚刚扫出来的。但一放进goproxy就会死一大批:(
日志如下：
W0205 21:58:54.452638   10468 gaetransport.go:49] GAE: "GET https://r3---sn-vgqs
en7r.googlevideo.com/generate_204" timeout: net/http: timeout awaiting response
headers, helpers.CloseConnections(*http.Transport)
W0205 21:58:54.452638   10468 gae.go:517] 127.0.0.1:63810 "GAE FETCH GET https:/
/r3---sn-vgqsen7r.googlevideo.com/generate_204 HTTP/1.1" error: *http.httpError(
net/http: timeout awaiting response headers)
E0205 21:58:54.453639   10468 handler.go:96] 127.0.0.1:63810 Filter RoundTrip *g
ae.Filter error: net/http: timeout awaiting response headers
W0205 21:58:54.565645   10468 gaetransport.go:49] GAE: "GET https://s.youtube.co
m/api/stats/qoe?event=streamingstats&fmt=247&afmt=251&cpn=6_1jadMjfb1qDfsp&ei=jS
-XWLzrCoq7uQLIy6LoCw&el=detailpage&docid=wBrFbk2Fqls&ns=yt&fexp=3300110%2C330013
0%2C3300164%2C3313274%2C3313321%2C9419451%2C9422596%2C9428398%2C9431012%2C943168
1%2C9433221%2C9434046%2C9434289%2C9434905%2C9435036%2C9439580%2C9441513%2C944215
7%2C9443258%2C9443436%2C9443612%2C9444898%2C9446054%2C9446364%2C9447935%2C944903
4%2C9449243%2C9450059%2C9451345%2C9451873%2C9452320%2C9455328%2C9456640%2C945673
7%2C9457021%2C9457083%2C9457141%2C9457423%2C9457443%2C9457494%2C9458759%2C946007
2%2C9460440%2C9460727%2C9461151%2C9461984%2C9462120&cl=146398760&seq=1&c=WEB&cve
r=1.20170131&cplayer=UNIPLAYER&cbr=Chrome&cbrver=56.0.2924.87&cos=Windows&cosver
=6.1&vps=0.002:N,0.018:N&vfs=0.018:247:248::s&view=0.018:854:480&bwe=0.018:24726
0&bh=0.018:0.000&vis=0.018:0&cmt=0.018:0.000" timeout: net/http: timeout awaitin
g response headers, helpers.CloseConnections(*http.Transport)
W0205 21:58:54.568645   10468 gae.go:517] 127.0.0.1:63780 "GAE FETCH GET https:/
/s.youtube.com/api/stats/qoe?event=streamingstats&fmt=247&afmt=251&cpn=6_1jadMjf
b1qDfsp&ei=jS-XWLzrCoq7uQLIy6LoCw&el=detailpage&docid=wBrFbk2Fqls&ns=yt&fexp=330
0110%2C3300130%2C3300164%2C3313274%2C3313321%2C9419451%2C9422596%2C9428398%2C943
1012%2C9431681%2C9433221%2C9434046%2C9434289%2C9434905%2C9435036%2C9439580%2C944
1513%2C9442157%2C9443258%2C9443436%2C9443612%2C9444898%2C9446054%2C9446364%2C944
7935%2C9449034%2C9449243%2C9450059%2C9451345%2C9451873%2C9452320%2C9455328%2C945
6640%2C9456737%2C9457021%2C9457083%2C9457141%2C9457423%2C9457443%2C9457494%2C945
8759%2C9460072%2C9460440%2C9460727%2C9461151%2C9461984%2C9462120&cl=146398760&se
q=1&c=WEB&cver=1.20170131&cplayer=UNIPLAYER&cbr=Chrome&cbrver=56.0.2924.87&cos=W
indows&cosver=6.1&vps=0.002:N,0.018:N&vfs=0.018:247:248::s&view=0.018:854:480&bw
e=0.018:247260&bh=0.018:0.000&vis=0.018:0&cmt=0.018:0.000 HTTP/1.1" error: *http
.httpError(net/http: timeout awaiting response headers)
E0205 21:58:54.573645   10468 handler.go:96] 127.0.0.1:63780 Filter RoundTrip *g
ae.Filter error: net/http: timeout awaiting response headers
希望作者和论坛高手支招，THANKS！

**Comment by dou4cc** [comment]
同@phuslu 刚开始还是3000kbps+，过一会儿就限在500kbps一下，南京电信

**Comment by phuslu** [comment]
额，goagent 的 autorange 在检测到视频断流的时候会重试。

然而 goproxy 还没实现这个逻辑，不好意思 😞 

这个目前优先级比较高，我打算近期修复。

**Comment by blob2015** [comment]
@phuslu 
期待

**Comment by wpyok500** [comment]
同样期待

**Comment by xiaomage2000** [comment]
期待中！感谢@phuslu的努力！

**Comment by Sak1tama** [comment]
@phuslu 其实ytb视频我都习惯于用clipconverer加IDM下载后观看，这种方法节省goproxy流量

**Comment by starobots** [comment]
一个720p视频1小时也不到1gb，多部署几个gae就行了，有10个gae的流量就够一天看的。
也没那么多时间看。

**Comment by gxggsrmyy** [comment]
@phuslu  ios 平台 youtube app 上的敏感词 视频会断流，另外的视频却可以播放，难道youtube app 不是加密连接，敏感词被侦测到了
