### ISSUE TITLE
It seems to not recognize this created gae project

### ISSUE THREAD

**Issue by hyperdoit** [phuslu/goproxy#1477]
![image](https://cloud.githubusercontent.com/assets/25634373/22732213/4dfa090a-ee28-11e6-85ea-4284aa7e4ce4.png)
![image](https://cloud.githubusercontent.com/assets/25634373/22732388/f6e269ae-ee28-11e6-9fa7-fa239d0d1be0.png)

**Comment by hyperdoit** [comment]
![image](https://cloud.githubusercontent.com/assets/25634373/22732306/ac515940-ee28-11e6-9c73-69297ba4e1da.png)
As is shown in GAE

**Comment by hyperdoit** [comment]
Should I wait for a few days then try again?

**Comment by MeABc** [comment]
Refer to  https://github.com/XX-net/XX-Net/issues/4720  and try again.
