### ISSUE TITLE
新加的Appid不起作用

### ISSUE THREAD

**Issue by Sec20** [phuslu/goproxy#1478]
之前长期用一个Appid没有出现问题，现在多加了一个，似乎新加的没有起到作用，只有减慢速度。
是这样加上去就可以吗，还是有什么别的步骤？
![snip_20170209125001](https://cloud.githubusercontent.com/assets/21214203/22769893/eb318948-eec6-11e6-8936-8959ec891262.png)

**Comment by yaoguaishou** [comment]
速度取决于你的ip，appid只是多加了流量

**Comment by Sec20** [comment]
@yaoguaishou 可能我没讲清楚，问题不是这个
如果原来的Appid流量用完了，再加新的Appid，浏览器直接显示404

**Comment by SeaHOH** [comment]
你不要等用完再加，一起放上就不用管了。

而且也不应该用“加”，用完了需要“换”。

**Comment by Sec20** [comment]
@SeaHOH 
现在就是一起放上去，似乎第二个还是没有起作用，客户端里也有显示404

**Comment by johnsonz** [comment]
加上后要重新载入才会生效

**Comment by Sec20** [comment]
@johnsonz 是重新载入了，但是似乎是这个Appid工作不正常，有时候显示什么/_gh/之类的

**Comment by asd2003asd** [comment]
服务端没部署？

**Comment by Sak1tama** [comment]
@Sec20 XX-net/XX-Net/issues/4973

**Comment by Sec20** [comment]
@asd2003asd 就是我自己没部署，忘了，谢谢提醒

**Comment by Sak1tama** [comment]
@Sec20 部署方式变了，你要注意啊

**Comment by Sec20** [comment]
@Sak1tama 确实，一个最近注册的appid没部署成功，谢谢提醒
