### ISSUE TITLE
小白不会配置

### ISSUE THREAD

**Issue by gohahaha** [phuslu/goproxy#1480]
按照 https://github.com/phuslu/goproxy/blob/wiki/SimpleGuide.md 教程成功 部署了appid  但出错了

![](http://ww1.sinaimg.cn/large/0069EP5Mly1fckejop5zcj30hq04k0sm)

那位大神能把 Win64 版配置好的发我邮箱里  不用发 appid  我 appid 配置好了 729185911@qq.com 谢谢

**Comment by gohahaha** [comment]
![](http://ww1.sinaimg.cn/large/0069EP5Mly1fcketiwcfvj30hu05odg2)

**Comment by Sak1tama** [comment]
gae.json 有问题，你认真开wiki了么
