### ISSUE TITLE
大概gfw改变了对google ip的策略

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1481]
不管是goproxy还是改hosts连google ip都遭到限速，希望改变goproxy策略，遇到低速ip直接拉黑

南京电信

**Comment by Sak1tama** [comment]
等下，社长忙着调试goproxy-vps呢 你的意思是，新设置一个时间函数，每过一个周期就对ip按照延迟重新排列，再按照排列后的ip列表连接GAE么

**Comment by dou4cc** [comment]
不是延迟，是带宽，部分google ip踩到会造成全局限速

**Comment by Sak1tama** [comment]
goproxy筛选ip时不是根据带宽的，你这么说没法儿弄

**Comment by phuslu** [comment]
不能确定是 GFW 还是 ISP 的策略。

希望能搜集到更多信息。

**Comment by MeABc** [comment]
我这段时间也碰到这个情况（限速？）。另，我也在相同时间里试了其它代理（手头上有的，还包括 issues 里发里 SNI proxy），也会有相同的情况。但我这的情况是，只是每天晚上高峰时2到3小时会这样，其它时间包括 gae 在内的代理基本上都能跑满带宽。之前我还认为是不是被 Qos 了，现在我更偏向网络拥堵。

**Comment by wz7465** [comment]
用前置的方法，有速度，但会受到大量的干扰
![111](https://cloud.githubusercontent.com/assets/7801728/22783655/b5c40f6a-ef07-11e6-854a-18d8050d23af.JPG)

**Comment by SeaHOH** [comment]
我这儿没发现限速，但是感觉干扰更严重了。四川电信。

**Comment by wz7465** [comment]
![222](https://cloud.githubusercontent.com/assets/7801728/22783725/071ceddc-ef08-11e6-9004-0a3210e91aaf.JPG)
ip数很稳定

**Comment by Sak1tama** [comment]
最近很多人跟我说翻墙速度慢，翻不出去等，他们也显得有点儿急，极有可能是最近长城防火墙升级策略了

**Comment by Sak1tama** [comment]
最近很多人跟我说翻墙速度慢，不止你一个，我猜是长城防火墙升级策略了，表现为随机丢包干扰和QOS

**Comment by Sak1tama** [comment]
@SeaHOH 最近很多人跟我说翻墙速度慢，不止你一个，我猜是长城防火墙升级策略了，表现为随机丢包干扰和进口数据限速

**Comment by SeaHOH** [comment]
@Sak1tama 
就是重试出现比较多，速度还是很快的。

**Comment by hcym** [comment]
基本正常

也是南京电信

**Comment by dou4cc** [comment]
用gogotunnel没出现限速，但速度一跳一跳的，像：https://github.com/phuslu/goproxy/issues/1470#issuecomment-278591089

**Comment by wz7465** [comment]
gogotunnel用的智能路由，有大量的连接是国内直连的，没有走代理，还有一些使用到了sniproxy，相当于官方通道，但是一旦连接上它的自建服务器，速度就不行了，干扰，丢包一样严重

**Comment by dou4cc** [comment]
我用的就是sniproxy

**Comment by SeaHOH** [comment]
SNIProxy 那是相当的挤。我也在用，但是还添加了几个干扰相当小的谷歌 和 GGC IP。

**Comment by dou4cc** [comment]
gogo是单ip连接

**Comment by dou4cc** [comment]
sniproxy有好几个虽然出错率和延迟高，但带宽有4~5Mbps

**Comment by dou4cc** [comment]
把浏览器预加载打开，延迟不算什么

**Comment by dou4cc** [comment]
把智能dns关掉以免踩到google ip导致限速

**Comment by SeaHOH** [comment]
视频没法预加载吧。

说个题外话，U2B 显示的那个链接速度一点都不准，跟我测试的差好几倍，明显比实际快了。

**Comment by SeaHOH** [comment]
谷歌限速可以用多 appid 和增加 autorange 线程来规避。

**Comment by dou4cc** [comment]
看视频延迟高点没什么，u2b的测速在流量平滑的情况下是比较准的，限速是全局的

**Comment by SeaHOH** [comment]
appid 有个每分钟限速，你说的不是这个？

**Comment by dou4cc** [comment]
我说的是电信的限制，一旦踩到某些google ip，所有出口流量都限速

**Comment by SeaHOH** [comment]
好吧，南京真恐怖。

**Comment by dou4cc** [comment]
https://github.com/XX-net/XX-Net/wiki/GoAgent-Blocked
这种伎俩不是首次出现了，之前那次是断网，现在是限速

**Comment by MeABc** [comment]
说到 GoAgent-Blocked 这个， goproxy 也有相应的功能，gae.json-->"IPBlackList" 。不过是要手动添加。

（“配置文件”里我把"IPBlackList"理解错了，改好后就 PR）

**Comment by MeABc** [comment]
说到 GoAgent-Blocked 这个， goproxy 也有相应的功能，gae.json-->"IPBlackList" 。不过是要手动添加。

（“配置文件”里我把"IPBlackList"理解错了，改好后就 PR）

**Comment by MeABc** [comment]
补充几点：

对 xx-net 不了解，不知道它现在还有没有用到这个（GoAgent-Blocked）；也不知道它是怎么实现自动判断的。要是一个一个手动加那麻烦了。

**Comment by dou4cc** [comment]
原来的方法不管用了，原来是断网，现在是限速，原来的方法只探测相关ip对整体出口流量连通性的影响，不探测对带宽的影响。

**Comment by SeaHOH** [comment]
XX-Net 有计算下载速度的代码，能够部分反应带宽状况，但是只用于显示，没有搞其它花样。

**Comment by MeABc** [comment]
现在 goproxy 我能想到的就是 "超时拉黑" ----于应对动态干扰。

至于 “限速拉黑” 这个是不是复杂了。

最后，我还是不敢相信 GFW 会把 ISP 的活给抢了。

**Comment by dou4cc** [comment]
可能就是isp干的

**Comment by SeaHOH** [comment]
可以按成功率、失败率高低加成不同 IP 类型权重来排序。我就是这么干的。

**Comment by MeABc** [comment]
你这主意不错。

**Comment by dou4cc** [comment]
@SeaHOH 你这个还是不能解决全局限速的问题，算了，我先换gogo吧

**Comment by jap33** [comment]
俺借这里问问俺gop中的升级get-latest-goproxy命令脚本怎么会自动消息呢？

**Comment by dou4cc** [comment]
为@ghost 烧香
