### ISSUE TITLE
每日遛狗鞭, 一路雄起

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1499]
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/23008186/ff6f1646-f448-11e6-8cfc-0dacb2d3dfa9.jpg)
**10M电信, GoProxy, [强制http2, cn段使用原中国谷歌]**

俺从换成新狗鞭以来, 一路滑溜.
基本上ssh 俺都不再用, 虽然亚洲高速节点还有70几个. 因为下载也总是满速.

Goagent的时代过去了, 不用提心吊胆, 新版狗鞭才是狗的精华.

**Comment by Sak1tama** [comment]
@jasonliul 老哥，我最近自建的ss速度比不上狗鞭了，坑爹啊

**Comment by jasonliul** [comment]
@Sak1tama 
近来ss表现疲软, 还不如ssh. 网页应用频繁刷新的话, ssh可以完成, 纸飞机却出来一些空白单元.
原因不明, 不像是某种干扰

**Comment by wpyok500** [comment]
我这边没这个速度

**Comment by phuslu** [comment]
现在我比较关注 tls 1.3 在谷歌服务器的部署情况了。

1. https://bugs.chromium.org/p/boringssl/issues/detail?id=76
2. https://bugs.chromium.org/p/chromium/issues/detail?id=641225

这个问题解决以后，预计谷歌服务器就可以全部上 tls 1.3，那样的 goproxy 的体验就能再上一个台阶了。

和 http2 这个依赖比较好的网络状况的特性不一样。tls 1.3 的 1-RTT 和 0-RTT 恰恰适合现在的干扰剧烈的恶劣网络了。

**Comment by jasonliul** [comment]
@phuslu 

我这里网络很难说好, ping一批国内的DNS, 不时会丢包.
而且讽刺的是, 那些真正快速的, 一会儿丢这个, 一会儿那个.

**Comment by gxggsrmyy** [comment]
@jasonliul cn段使用原中国谷歌 就能用了吗，hk 段不用填ip 了吗？

**Comment by Alvin9999** [comment]
@phuslu  期待中

**Comment by PvCDp** [comment]
@Alvin9999 多谢你的ip自动更新程序，不再找ip，对于懒人来讲非常实用，多谢！

**Comment by magnet1215** [comment]
@PvCDp 哪个程序

**Comment by starobots** [comment]
强制http2，还是unexpected EOF。
原中国谷歌是g.cn那个？

**Comment by blob2015** [comment]
@phuslu 
社长，预估大概什么时候可以用上这个tls 1.3？

**Comment by phuslu** [comment]
很难说。客户端支持 tls1.3 只是一个开关的问题。但是服务端是谷歌的部署的，我个人估计在可能迟到 6 月份左右才会用上 :(

而且是分批的，第一批应该只有 gws 的服务器会部署 tls1.3

胡乱猜测。

**Comment by blob2015** [comment]
@phuslu 
6月，现在都2月中旬了啦，眼睛一闭一开就到了 :grinning: 
gws服务器第一批部署，倒也符合一般的情况，到时候筛选下ip就是了 :grinning: 
有期待才更加美好 :grinning:

**Comment by jasonliul** [comment]
@phuslu 

我等垂涎期待~~
LOL

**Comment by phuslu** [comment]
r1297 https://github.com/phuslu/goproxy/commit/881bf3d47c10a3aff8bb01d7b1b0ca6d8aebcf3b 打开了浏览器和客户端的 tls1.3 支持。

虽然对速度提升不大，但是可以有效的降低一些电脑的 CPU 占用率了。

![r61](https://ws1.sinaimg.cn/large/0060lm7Tgy1fctufsx3wrj30w30bo75o.jpg)


如上图所示，我的笔记本 CPU 是比较旧的 T9200， 不支持 AES-NI 只能. 使用了 tls1.3 之后的 x25519/chacha20 可以有效降低 CPU 了。 😄

**Comment by blob2015** [comment]
@phuslu 
社长，你这下手也太快了 :grinning:

**Comment by phuslu** [comment]
因为我的 atom 的 CPU，比较弱的 N270. 也很受益这个改动，所以想到的话，就赶紧改动了。

至于谷歌服务器和客户端的 tls1.3 的链接支持 tls1.3, 这个就有得期待了。 :rofl:

**Comment by phuslu** [comment]
![screenshot_2017-02-17-23-44-13-757_com chrome beta](https://cloud.githubusercontent.com/assets/195836/23071967/b5d747da-f4f5-11e6-82f3-357bb1eb747b.png)

手机上 chrome beta 已经默认开启了 tls1.3 很不错。

**Comment by jasonliul** [comment]
@phuslu 
流畅性更好, 速度确实变化不大

可以测试:
https://www.neowin.net/news/cat/software
这个网站会疯狂传送数据.

**Comment by starobots** [comment]
对了，还要问一下，switchomega插件有的时候会占用特别高的内存，有时候将近300mb，今天看utb占用796mb，结束进程之后就好了。。。这算是bug么。

**Comment by phuslu** [comment]
@starobots 貌似是 chrome 的问题，https://github.com/FelisCatus/SwitchyOmega/issues/815#issuecomment-276563870

**Comment by starobots** [comment]
好的谢谢lu

**Comment by jzmswe** [comment]
以前youtube 1080P一直卡。从1297开始，youtube卡一会儿后，1080P就一直流畅下去了，应该是TLS 1.3起得作用。

**Comment by phuslu** [comment]
@starobots 据说 chrome 已经修复。
https://mobile.twitter.com/_catus/status/835695836705263617

**Comment by starobots** [comment]
好的，谢谢lu，我去更新一下chrome！
