### ISSUE TITLE
最近不知道为啥 用goproxy电脑很卡

### ISSUE THREAD

**Issue by hexianfu** [phuslu/goproxy#1501]
就是最近几天的事！我这期间装过Python 去用一个工具，然后就出现无论是omega自动切换还是直接走goproxy 电脑就卡，一换回直连或PAC，ss就好了。现在python已经卸载了， 卡是体验在，移动鼠标有停顿，系统声音卡。中间我还重新装过chrome 。发现不是这个原因。不知道有没有人懂？ 先谢过了！

**Comment by phuslu** [comment]
goproxy 是用 go 语言实现的，和 python 没啥关系。

怀疑你搞错了。

**Comment by hexianfu** [comment]
我的情况确实是用了python 之后 才出现这种打开goproxy就卡的情况。

**Comment by phuslu** [comment]
但这个说不通啊。

你看下任务管理器，是不是有没退干净的 python 进程？

如果没有的话，我也想不出其他原因了？

**Comment by hexianfu** [comment]
发现卡之后 我就卸载调Python了 难道要重装系统 -  -

**Comment by ruby186** [comment]
有的东西不好说；我遇到过更新goproxy时，WIN7更新了一个长期补丁，导致明显SSD降速。卸载了补丁就好了。

2017-02-17 22:54 GMT+08:00 Phus Lu <notifications@github.com>:

**Comment by hexianfu** [comment]
很明显是跟系统哪里 不兼容了。又找不出到底问题在哪里，也不想重装系统。- - ！

**Comment by MeABc** [comment]
goproxy 这黑锅背的有点冤....

**Comment by hexianfu** [comment]
@MeABc  你这话说的，我都说了 我知道不是GOPROXY的问题，是我这几天装了什么或者设置了什么跟他冲突了，我发个帖也就是看有没有人知道怎么回事

**Comment by MeABc** [comment]
我也就开个玩笑。不要介意。

**Comment by hexianfu** [comment]
今天起来打开goproxy-gui.exe  以前也是一直打开的这个，出现   

 控制台窗口主机  已停止工作

问题事件名称:	APPCRASH
  应用程序名:	conhost.exe
  应用程序版本:	6.1.7601.18015
  应用程序时间戳:	50b826c0
  故障模块名称:	conhost.exe
  故障模块版本:	6.1.7601.18015
  故障模块时间戳:	50b826c0
  异常代码:	c0000005
  异常偏移:	000000000003c1dd
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	cb0b
  其他信息 2:	cb0b939dcde4fb7917a2b6a9a4a3d85f
  其他信息 3:	411c
  其他信息 4:	411cf00eb0fab256e2d8c630b70b5043
  
 关掉这个停止窗口后goproxy-gui.exe也自动关闭了。然后我单独打开goproxy.exe 用着也不卡了 也不关闭了(@  @)   不过这个窗口也不能隐藏了。还有单独打开这个 youtube右键 详细统计信息 里 Connection Speed也看不到变化了固定1937Kbps 实际走的带宽高于这个

**Comment by hexianfu** [comment]
@phuslu  好像好了。搜索了下相关名称，说是可能是插件等原因，删除了多余的插件启动项 稳定运行了 ，不知道还会不会出错。把帖子关了吧
