### ISSUE TITLE
频繁出现红字

### ISSUE THREAD

**Issue by THLIVSQAZ** [phuslu/goproxy#1508]
用了r1298频繁出现红字，网速略慢，
![1487505311959](https://cloud.githubusercontent.com/assets/25531652/23102114/1921a60c-f6de-11e6-89ed-1d161e192e3d.jpg)
有无影响？

**Comment by phuslu** [comment]
"unkown certificate" 这个错误比较少见。

推测是和你的环境有关，请补充更多信息。

**Comment by phuslu** [comment]
google 了一下这个错误，很有可能是环境问题。
比如没有正确安装证书等等。

**Comment by THLIVSQAZ** [comment]
重装证书后正常，谢谢社长 @phuslu
