### ISSUE TITLE
今天ip突然全部失效

### ISSUE THREAD

**Issue by PvCDp** [phuslu/goproxy#1509]
mff扫描出来的ip全部不通，checkiptools直接就扫描不出来。

**Comment by phuslu** [comment]
我这边不能复现，其他人有这样情况吗？

**Comment by MeABc** [comment]
报告，我这正常。

**Comment by phuslu** [comment]
那继续观察吧，昨天我也也遇到可用 ip 比较少的问题。
猜测可能是又会大规模封 ip 了。

**Comment by blob2015** [comment]
@phuslu 
我这边的情况是这样的：黄红出现，然后一路显示bad ip数量飙升（短短一段时间，bad的数量就成了两三千），good ip显示为零。
**偶发**，多在刚开动电脑后的首次使用出现。
解决：关闭，重开gp，就行了。

**Comment by starobots** [comment]
估计是地方的特定isp抽风吧。我这还好。

**Comment by PvCDp** [comment]
我在无锡，确实不行

**Comment by Asteroids89** [comment]
![qq 20170220150014](https://cloud.githubusercontent.com/assets/19388220/23115043/67af0bda-f77d-11e6-8014-164a257ae72e.png)
报告，杭州这边还是正常的

**Comment by wz7465** [comment]
楼上的似乎ip掉的有点快啊

**Comment by caofengzi** [comment]
最近的確有時候一啟動會出現沒有ip的情況，但是運行一會就好了，ip有幾個能夠使用的就夠了。

**Comment by jyuan15** [comment]
有时启动后good ip一直为0，而bad ip数量不断攀升，当然也打不开网页。重新启动后就有good ip数量了。

电信移动都在用，但电信封得厉害多了，同一批IP段9万多IP，移动能测出一两千IP，电信只能测出1、2百个。

![2017-02-20_152455](https://cloud.githubusercontent.com/assets/12642186/23115672/60eadfa0-f781-11e6-9f71-bc7e1dc137b2.jpg)

**Comment by blob2015** [comment]
@jyuan15 
就是俺的情况。
移动的话，主要是“带宽”不稳定，下载的话，速度高高低低不停地跳，即便对方已经给足了流量带宽，是股市般的曲线；但是电信就会一直在带宽的最高点，是平直线。
电信就是封得多了些，但大致也在还能用的范围。

**Comment by phuslu** [comment]
我也是电信，没做二次筛选。good/bad 比例在 1/50 左右。

**Comment by hcym** [comment]
电信正常

GoAgent也正常无异

**Comment by hcym** [comment]
dialer2.go:99] MULTIDIALER DialTLS2("tcp", "######.appspot.com:443") with good_addrs=247, bad_addrs=311

忽大忽小，速度喜人，GoAgent刚刚下载几百M，也很给力

可能出口带宽用的人少吧

**Comment by ylhfz** [comment]
最近几个版本会出现：
狗屁刚启动，尤其是系统启动后，第一次启动狗屁，goodip一直为0
然后手动关闭狗屁，重启，就一切正常。。。

**Comment by Asteroids89** [comment]
是滴，我这今天出现了两次了

**Comment by 94oiio** [comment]
昨晚移动同样出现ip大规模失效，直接降为0，重开goproxy后又能用了 r1300

**Comment by PvCDp** [comment]
急需要出现像phuslu这样的大咖来编译提升找ip的软件，目前看遇到封锁加强时，几乎一个ip也扫不到。

**Comment by blob2015** [comment]
@PvCDp 
看J哥帖子，里面提到的，主任等升级的，够用了

**Comment by PvCDp** [comment]
发现同一批ip,goproxy一般显示会有一些goodaddrs,而goagent完全不能用，估计以后goagent会完全被封杀。
