### ISSUE TITLE
都说http/2好用，为啥默认设置里面是关闭的啊？

### ISSUE THREAD

**Issue by kirbyzhu** [phuslu/goproxy#1511]
为了体验  是不是要自己在里面打开？ 为啥在默认的设置里面是关闭的啊？

	"DisableHTTP2": true,
	"ForceHTTP2": false,

**Comment by phuslu** [comment]
https://github.com/phuslu/goproxy/issues/1499#issuecomment-280242787

最后一句。

**Comment by kirbyzhu** [comment]
前面有人讨论的时候 我看说是http2在网络干扰比较严重 延迟比较大的时候能稳定运行？ 是我看反了？

**Comment by phuslu** [comment]
1. 网络干扰不严重(丢包率低)  2. 延迟比较大
适合 http2

1. 网络干扰比较严重(丢包率高) 2. 延迟比较大
适合 tls1.3 (这个客户端已经实现，等待谷歌升级服务端）

**Comment by kirbyzhu** [comment]
了解了
