### ISSUE TITLE
Googel Search 搜索时又要输入验证码

### ISSUE THREAD

**Issue by boromeke** [phuslu/goproxy#1513]
大家使用 Googel Search 时是不是发现验证机制又从方便的点击式变回了手动输入字符的模式？

而且使用同样的 IP 使用 Goproxy 来 Googel Search 时则需要输入验证码（我也试过禁用过所有扩展，同样需要输入验证码

**Comment by phuslu** [comment]
别做比较，已经有口水战的趋势，请勿提及友商吧。

**Comment by phuslu** [comment]
还有，请使用了 goproxy 用户也不要到友商的项目说 goproxy 如何如何。

**Comment by phuslu** [comment]
可能 goproxy 已经引起了其他用户的人不满，从针对 goproxy 已经在针对我的品格了。

> phuslu这个作者是双面娇娃，有俩ID。zhao这个分叉已经没了，另外一个原始版还保留着，用海外IP可以查看。昨天因为phuslu的zhao没了，我下载了zhao看了看，这些资料很水。XX-NET Mini不是他的项目（我弄错了），他只是fork。zhao讨论版的帖子看了下，难怪github曾经被封。

> XX的评价高得多，但XX讨论版有许多挺GoProxy黑XX的言论。貌似Go支持VPS（Virtual Private Server）。

诸位还是低调使用 goproxy 吧。
