### ISSUE TITLE
我这儿github.com   又有问题了。。。。别人有问题吗，最新版，访问google.com的网站很快

### ISSUE THREAD

**Issue by doracl** [phuslu/goproxy#1517]
W0224 10:01:23.020854    7220 gaetransport.go:49] GAE: "GET https://github.com/" timeout: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond., helpers.CloseConnections(*http2.Transport)
W0224 10:01:23.020854    7220 gaetransport.go:49] GAE: "GET https://avatars2.githubusercontent.com/u/11531880?v=3&s=40" timeout: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond., helpers.CloseConnections(*http2.Transport)
W0224 10:01:23.020854    7220 gaetransport.go:49] GAE: "GET https://assets-cdn.github.com/favicon.ico" timeout: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond., helpers.CloseConnections(*http2.Transport)
W0224 10:01:23.022804    7220 gaetransport.go:55] GAE: 211.49.146.24 is timeout, add to blacklist for 5m0s
W0224 10:01:23.020854    7220 gaetransport.go:49] GAE: "GET https://github.com/" timeout: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond., helpers.CloseConnections(*http2.Transport)
W0224 10:01:23.020854    7220 gaetransport.go:49] GAE: "GET https://github.com/" timeout: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond., helpers.CloseConnections(*http2.Transport)
W0224 10:01:23.021822    7220 gae.go:517] 127.0.0.1:54943 "GAE FETCH GET https://assets-cdn.github.com/assets/frameworks-d876e21057f406b37686f3dc7b9666f5957cda4847a48ec11e040df065624617.css HTTP/1.1" error: *net.OpError(read tcp 172.18.8.255:54946->211.49.146.24:443: use of closed file or network connection)
W0224 10:01:23.021822    7220 gaetransport.go:55] GAE: 211.49.146.24 is timeout, add to blacklist for 5m0s
W0224 10:01:23.021822    7220 gaetransport.go:55] GAE: 211.49.146.24 is timeout, add to blacklist for 5m0s
W0224 10:01:23.022804    7220 gae.go:517] 127.0.0.1:55088 "GAE FETCH GET https://assets-cdn.github.com/favicon.ico HTTP/1.1" error: *net.OpError(read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
W0224 10:01:23.023778    7220 gaetransport.go:55] GAE: 211.49.146.24 is timeout, add to blacklist for 5m0s
W0224 10:01:23.023778    7220 gaetransport.go:55] GAE: 211.49.146.24 is timeout, add to blacklist for 5m0s
E0224 10:01:23.023778    7220 handler.go:96] 127.0.0.1:54943 Filter RoundTrip *gae.Filter error: read tcp 172.18.8.255:54946->211.49.146.24:443: use of closed file or network connection
W0224 10:01:23.024754    7220 gae.go:517] 127.0.0.1:54744 "GAE FETCH GET https://github.com/ HTTP/1.1" error: *net.OpError(read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
W0224 10:01:23.024754    7220 gae.go:517] 127.0.0.1:54920 "GAE FETCH GET https://avatars2.githubusercontent.com/u/11531880?v=3&s=40 HTTP/1.1" error: *net.OpError(read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
E0224 10:01:23.024754    7220 handler.go:96] 127.0.0.1:55088 Filter RoundTrip *gae.Filter error: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
W0224 10:01:23.024754    7220 gae.go:517] 127.0.0.1:55052 "GAE FETCH GET https://github.com/ HTTP/1.1" error: *net.OpError(read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
E0224 10:01:23.026710    7220 handler.go:96] 127.0.0.1:55052 Filter RoundTrip *gae.Filter error: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
W0224 10:01:23.024754    7220 gae.go:517] 127.0.0.1:55086 "GAE FETCH GET https://github.com/ HTTP/1.1" error: *net.OpError(read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
E0224 10:01:23.025732    7220 handler.go:96] 127.0.0.1:54744 Filter RoundTrip *gae.Filter error: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0224 10:01:23.025732    7220 handler.go:96] 127.0.0.1:54920 Filter RoundTrip *gae.Filter error: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0224 10:01:23.041374    7220 handler.go:96] 127.0.0.1:55086 Filter RoundTrip *gae.Filter error: read tcp 172.18.8.255:54756->211.49.146.24:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by caofengzi** [comment]
俺這裡沒有問題一切正常。

**Comment by tec1987** [comment]
Github 没必要走GAE吧。。。
访问不了一般都是DNS解析问题

**Comment by doracl** [comment]
嗯，现在好了，就是抽风
