### ISSUE TITLE
关于 GAE 服务端运行效率

### ISSUE THREAD

**Issue by SeaHOH** [phuslu/goproxy#1521]
这几天发现服务端处理请求消耗的实例小时数跟请求数关系不大，反而和运行时间相关，大概为实际时间的 0.7 多点。

这属于 GAE 平台、Go 语言自身还是服务端的原因呢？有没有可能改进让它消耗少点？

主要是想到那么多 appid 平时没有使用时也在平白浪费资源，不像 Python 版服务端不处理请求就基本上没多少消耗那样心安理得。

**Comment by phuslu** [comment]
go 的 server 是一直在 GAE 运行。
python 其实是一段脚步，以 cgi/wsgi 方式运行。

所以，
1. python 比较省执行时间
2. go 响应较快，因为没有 warmup 时间。

**Comment by phuslu** [comment]
在部署的时候也可以从日志里面看出来， go 的 server 在上传以后是编译成一个独立文件再运行的。

所以它的运行时间会比较长些，不太容易被睡眠。有利有弊吧。

**Comment by SeaHOH** [comment]
谢谢社长解惑。

也就是说 Python 版的是以插件方式运行，Go 版的是以单独服务方式运行。
这应该属于平台原因，只能谷歌自己改进，这样理解没错吧？

**Comment by SeaHOH** [comment]
又想起前几天看到的 cgi/wsgi 介绍了。

是否可以这样理解？
Go 版应该也是 cgi/wsgi 方式运行，但 Go 是插入进程，但为了整体效率不会立即停止；
而 Python 版是线程插入，所以处理完就结束线程。

**Comment by phuslu** [comment]
大体如此。

go 版的 server 是编译到一起，和外部服务（比如 urlfetch service) 用 protobuf 通信。
python 版的 server 是以 wsgi appliation 跑在 google sandbox python runtime 里面，然后 google sandbox python runtime 再用 protobuf 调用外部服务。

所以 python 可以比较准确的计算 frontend time.
而 go 版就比较难，所以就按它的运行时间计算 fontend time 了。

**Comment by SeaHOH** [comment]
感觉不够环保……还以为能改进下，原来就是设计成这样的。
唉，都是逼出来的，能好好上网谁还玩这套啊。

话说谷歌真是有钱，都不封。
