### ISSUE TITLE
访问wsj报错

### ISSUE THREAD

**Issue by ruby186** [phuslu/goproxy#1527]
我确认wsj本身没有问题，通过opvn和shadowsocks都能正常访问。

场景如下：
1 启动goproxy，IP为雨伞地区（咳咳……）
2 访问cn.wsj.com，会自动跳转到/gb，这个不是问题，他本身就那样
3 点击任意一新闻，打开一个新的标签页，goproxy发生数段请求
4 goproxy报错，其中部分日志如下（其他看起来正常？）
5 窗口直接消失。。

版本信息如下：
```
r1305 (go/d48eaf5 tls13/4358932 http2/9c2c85e windows/386)
```  

日志：
```
I0228 00:12:14.954233    4728 gae.go:584] 127.0.0.1:40278 "GAE FETCH GET http://
us.pixel.newscgp.com/i?stm=1488211934642&e=pv&url=http%3A%2F%2Fcn.wsj.com%2Fgb%2
F20170227%2Fbgh130410.asp&page=%E5%8D%B0%E5%B0%BC%E4%B8%87%E9%9A%86%E9%81%AD%E9%
81%87%E5%B0%8F%E5%9E%8B%E7%82%B8%E5%BC%B9%E8%A2%AD%E5%87%BB%20-%20%E5%8D%8E%E5%B
0%94%E8%A1%97%E6%97%A5%E6%8A%A5&refr=http%3A%2F%2Fcn.wsj.com%2Fgb%2Findex.asp&tv
=js-2.6.2&tna=_ncg__0&aid=newsconnect-global&p=web&tz=Asia%2FShanghai&lang=zh-CN
&cs=UTF-8&f_pdf=1&f_qt=0&f_realp=0&f_wma=0&f_dir=0&f_fla=1&f_java=0&f_gears=0&f_
ag=0&res=1366x768&cd=24&cookie=1&eid=989e5be2-6c46-4491-be69-7b1da92c9a8c&dtm=14
88211934638&vp=1366x662&ds=1349x5714&vid=27&sid=1c362ec9-3033-4c70-88f5-cc316709
f085&duid=8546cd04-fb1b-45d2-a09c-7763b0e04141&fp=824942146&uid=157d030f972-d31c
190f-c875-4d14-906f-b7b1f7eecd69&cx=eyJzY2hlbWEiOiJpZ2x1OmNvbS5zbm93cGxvd2FuYWx5
dGljcy5zbm93cGxvdy9jb250ZXh0cy9qc29uc2NoZW1hLzEtMC0wIiwiZGF0YSI6W3sic2NoZW1hIjoi
aWdsdTpjb20ubmV3c2NncC9ha2EvanNvbnNjaGVtYS8xLTAtMCIsImRhdGEiOnsidXNlcl9pZCI6IiIs
InVzZXJfcHJvdmlkZXIiOiJpbmhvdXNlIiwidXNlcl9tZW10eXBlIjoibm9uc3ViIiwidXNlcl9uZXdz
bGV0dGVyX2lkIjoiIiwidXNlcl9uZXdzbGV0dGVyX3Byb3ZpZGVyIjoiIiwiYnJvd3Nlcl9kbXBfaWQi
OiIiLCJicm93c2VyX2RtcF9wcm92aWRlciI6ImJsdWVrYWkiLCJicm93c2VyX2Fkc19wcGlkIjoiIiwi
YnJvd3Nlcl9hZHNfcHJvdmlkZXIiOiJkZnAiLCJicm93c2VyX2FuYWx5dGljc19pZCI6IjU5NUY2QkE0
QkU4RTBERjYtMUU0RTZDRDMxRkFEMUYzNCIsImJyb3dzZXJfYW5hbHl0aWNzX3Byb3ZpZGVyIjoib21u
aXR1cmUiLCJicm93c2VyX25jZ19pZCI6IjEwNDg1MTE1LWIxOTQtNDEyMy05YjI1LWVmMWMxYzNiODFh
MSJ9fSx7InNjaGVtYSI6ImlnbHU6Y29tLm5ld3NjZ3AvYXJ0aWNsZS9qc29uc2NoZW1hLzEtMC0wIiwi
ZGF0YSI6eyJhcnRpY2xlX2lkIjoiIiwiYXJ0aWNsZV9zb3VyY2UiOiIiLCJhcnRpY2xlX3B1Ymxpc2hl
ZF90aW1lIjoiIiwic2VjdGlvbiI6IkFydGljbGUiLCJzdWJzZWN0aW9uIjoiIiwic3Vic3Vic2VjdGlv
biI6IiIsImFydGljbGVfcGFpZF9jb250ZW50X3R5cGUiOiIifX1dfQ HTTP/1.1" 200 43
I0228 00:12:15.289252    4728 gae.go:584] 127.0.0.1:40268 "GAE FETCH GET http://
tags.bluekai.com/site/4454?ret=html&phint=primaryProduct%3DChinese%20WSJ&phint=p
ageName%3DCWSJ_world_bgh130410&phint=section%3DCWSJ_China&phint=articleType%3DCW
SJ_Article_world&phint=subSection%3DCWSJ_world&phint=contentType%3Darticle&phint
=contentChannel%3DArticle&phint=isSub%3DCWSJ_login_yes&phint=edition%3DEdition_C
hina&phint=referrer%3Dhttp%3A%2F%2Fcn.wsj.com%2Fgb%2Findex.asp&phint=__bk_t%3D%E
5%8D%B0%E5%B0%BC%E4%B8%87%E9%9A%86%E9%81%AD%E9%81%87%E5%B0%8F%E5%9E%8B%E7%82%B8%
E5%BC%B9%E8%A2%AD%E5%87%BB%20-%20%E5%8D%8E%E5%B0%94%E8%A1%97%E6%97%A5%E6%8A%A5&p
hint=__bk_k%3D%E5%8D%B0%E5%B0%BC%E4%B8%87%E9%9A%86%E9%81%AD%E9%81%87%E5%B0%8F%E5
%9E%8B%E7%82%B8%E5%BC%B9%E8%A2%AD%E5%87%BB&phint=__bk_pr%3Dhttp%3A%2F%2Fcn.wsj.c
om%2Fgb%2Findex.asp&phint=__bk_l%3Dhttp%3A%2F%2Fcn.wsj.com%2Fgb%2F20170227%2Fbgh
130410.asp&limit=10&r=83753531 HTTP/1.1" 200 1088
I0228 00:12:15.541267    4728 gae.go:584] 127.0.0.1:40275 "GAE FETCH GET http://
cn.wsj.com/news/commenting/djlivefyre?config=livefyreConfig&streaminfo=undefined
&_=1488211933335 HTTP/1.1" 404 85736
```  
__I0228 00:12:15.545267    4728 handler.go:145] IOCopy &http.bodyEOFSignal{body:(*
http.body)(0x13180bd0), mu:sync.Mutex{state:0, sema:0x0}, closed:false, rerr:err
or(nil), fn:(func(error) error)(0x610300), earlyCloseFn:(func() error)(0x6102b0)
} return 8192 *net.OpError(write tcp 127.0.0.1:8087->127.0.0.1:40275: wsasend: A
n established connection was aborted by the software in your host machine.)__   
```
I0228 00:12:17.255365    4728 gae.go:584] 127.0.0.1:40301 "GAE FETCH GET http://
ping.chartbeat.net/ping?h=cn.wsj.com&p=%2Fgb%2Findex.asp&u=xFcvGDmDwnmCEVWk9&d=c
n.wsj.com&g=8900&n=0&f=f2025&c=0.5&x=200&m=200&y=4031&o=1349&w=662&j=60&R=0&W=0&
I=1&E=8&e=0&v=http%3A%2F%2Fcn.wsj.com%2Fgb%2F&b=4824&t=DzqMB3B2HtAiDtlCX2DOiCmgC
lDI09&V=89&tz=-480&sn=3&eM=0002&EE=8&sv=zKVxJDmoSUuoIAVZC0fhsBvMDl&sr=http%3A%2F
%2Fcn.wsj.com%2Fgb%2F&_ HTTP/1.1" 200 43
I0228 00:12:18.450433    4728 gae.go:584] 127.0.0.1:40313 "GAE FETCH GET http://
wsjstream.wsj.net/bg/api/Pickup.ashx?c={%22c%22:%22797a18a9fb2642c7b3ae80868997d
5be%22,%22s%22:%2210.241.40.129%22}&m=[]&_=1488211938187 HTTP/1.1" 200 315
I0228 00:12:22.854685    4728 stripssl.go:146] 127.0.0.1:40354 "STRIP CONNECT cl
ients4.google.com:443 HTTP/1.1" - -
```

**Comment by MeABc** [comment]
我这没有问题。

![11](https://cloud.githubusercontent.com/assets/18194126/23370517/df722472-fd4f-11e6-9623-6d948a3a899d.gif)

**Comment by phuslu** [comment]
不能重现。有可能是 IP 问题。

**Comment by ruby186** [comment]
118.143.88.141

HK段的，好吧，如果真的是IP问题请忽略。但是……打开其他网站都没有问题啊，不然我怎么上来提的ticket。。

**Comment by MeABc** [comment]
我也没有别的意思。不是说你提 issue 不对。

大家把各自情况说一下，你也好自已检查和排除问题。

**Comment by ruby186** [comment]
@MeABc 客气啦，客气啦，呵呵。我第一时间想到的是我昨天夜里可能检查的不仔细；第二时间看了你的截图才想起来，写的不完善，应该是新请求的那个浏览器窗口直接消失，而不是(goproxy)窗口消失，呵呵……

不用多解释了，这里大家都学到很多东西，都懂，谢谢你：）

**Comment by zdf0145** [comment]
我这也上不去，报这个错，以前没见过
{
    "type": "appengine",
    "host": "×××××.appspot.com",
    "software": "Google App Engine/1.9.48",
    "error": "API error 7 (urlfetch: DNS_ERROR)"
}

**Comment by MeABc** [comment]
哇，这个错误没有见过。刷新一下应该没有问题吧。
    
    
    在 2017/2/28 20:56, pandora 写道:
    
    
      我这也上不去，报这个错，以前没见过
        {
        "type": "appengine",
        "host": "×××××.appspot.com",
        "software": "Google App Engine/1.9.48",
        "error": "API error 7 (urlfetch: DNS_ERROR)"
        }
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/phuslu/goproxy","title":"phuslu/goproxy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/phuslu/goproxy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zdf0145 in #1527: 我这也上不去，报这个错，以前没见过\r\n{\r\n    \"type\": \"appengine\",\r\n    \"host\": \"×××××.appspot.com\",\r\n    \"software\": \"Google App Engine/1.9.48\",\r\n    \"error\": \"API error 7 (urlfetch: DNS_ERROR)\"\r\n}"}],"action":{"name":"View Issue","url":"https://github.com/phuslu/goproxy/issues/1527#issuecomment-283031924"}}}

**Comment by kirbyzhu** [comment]
我这个错也出现了 cn.wjs.com访问就是报那个错误 刷新也不行 把这个域名加入到Goproxy的连接方式也不行

然后从google的搜索页面可以进去 发现自动跳转/gb了

**Comment by phuslu** [comment]
是 wsj 不是 wjs. 楼主之前写错了。

**Comment by ruby186** [comment]
我很郁闷的是，第一次遇到这样的，一开始还怀疑虚拟机中毒了，赶紧还原了个干净镜像，后来认真测试了下，活生生见浏览器窗口消失，然后抓了个日志，就凌乱了。。现在还在猜是否哪里兼容性不好

**Comment by kirbyzhu** [comment]
@phuslu 难怪我谷歌之后能登录 用楼主给的网址测试一直不行

**Comment by ruby186** [comment]
server r-60，client r-1349以后此问题已消失，不会再报错中断会话。
