### ISSUE TITLE
谷歌图片，以图搜图，上传文件失败，链接已重置

### ISSUE THREAD

**Issue by inkdie** [phuslu/goproxy#1528]
https://www.google.com.hk/searchbyimage/upload

上传本地文件没有成功过

win10,64bit，R1306

==================问题已解决===============
非常感谢各位，问题解决了
解决办法就是重装chrome

**Comment by jzp820927** [comment]
什么版本？

**Comment by inkdie** [comment]
@jzp820927 R1306

**Comment by SeaHOH** [comment]
以前是正常的吗？

**Comment by inkdie** [comment]
@SeaHOH 使用频率不高，但是最近用过几次都不能用，年前应该成功过的。

**Comment by kirbyzhu** [comment]
r1309没你说的这个问题 
第一次上传正常能够搜索
第二次上传出现流量异常要验证，验证后搜索正常

**Comment by SeaHOH** [comment]
用其它代理试过没有，当前浏览器配置是否能用？

**Comment by caofengzi** [comment]
此网站无法提供安全连接

www.google.com 发送的响应无效。
ERR_SSL_PROTOCOL_ERROR

**Comment by blob2015** [comment]
试试：二次筛选ip，ip数量大一些（5000以上），如果二次筛选得到的ip没有很好的话
个人使用这个图片搜索，一直都比较正常

**Comment by inkdie** [comment]
相同配置下，Chrome打不开，IE却可以打开，可能问题出现在Chrome上，具体原因不明，谢谢大家。

**Comment by kirbyzhu** [comment]
我就是chrome

**Comment by inkdie** [comment]
@kirbyzhu 从Chrome各种丰富的插件这个角度来说，世界上没有两个长得一模一样的chrome。所以，问题可能是出在某个chrome插件上，比如广告拦截、字体修改、网页版式优化、甚至某些资源探测插件等，这会儿没工夫挨个测试，等有时间了，我会尝试重装Chrome，或者挨个禁用插件。

PS：刚刚写到禁用插件的时候，突然想到隐身模式可以禁用全部插件，尝试了一下，还是不行。谷歌图片的网站可以打开，不能上传本地文件进行搜索。估计还是要尝试重新安装一次。

**Comment by inkdie** [comment]
@SeaHOH 同样的配置，IE能打开也可以上传本地文件搜索，chrome目前没有可用的备用梯子，所以还没尝试。

chrome具体表现为谷歌图片的网站可以打开，不能上传本地文件进行搜索。

**Comment by SeaHOH** [comment]
Chrome 的隐身模式还是会受你过往使用配置的影响，可以先用同步备份，然后的恢复默认设置尝试。

**Comment by MeABc** [comment]
试了一下，没有问题。

![000](https://cloud.githubusercontent.com/assets/18194126/23409296/02329a76-fe06-11e6-920e-ab33ad65ff3c.gif)

**Comment by inkdie** [comment]
感谢各位，重新安装了chrome，目前能用了，说明问题还是出在chrome上面，具体原因不明。
