### ISSUE TITLE
为Command配置代理出现证书错误

### ISSUE THREAD

**Issue by johnsonz** [phuslu/goproxy#1530]
win10 x64
r1297

使用windows下cmd窗口配置代理然后下载github上的资源出现证书错误

> set http_proxy=http://127.0.0.1:8087
> set https_proxy=http://127.0.0.1:8087
> set strict-ssl=false

cmd中的错误：

> fatal: unable to access 'https://github.com/xxx/': SSL certificate problem: unable to get local issuer certificate
> package github.com/xxx: exit status 128

日志：

> I0301 21:53:57.728431   47628 stripssl.go:159] 127.0.0.1:28613 *tls.Conn.Handshake() error: &net.OpError{Op:"remote error", Net:"", Source:net.Addr(nil), Addr:net.Addr(nil), Err:0x30}
> E0301 21:53:57.728431   47628 handler.go:74] 127.0.0.1:28613 Filter Request *stripssl.Filter error: remote error: tls: unknown certificate authority

**Comment by phuslu** [comment]
如果是 git 的话，需要这么设置
```
git config --global http.proxy 127.0.0.1:8087
git config --global http.sslVerify false
git config --global http.postBuffer 524288000
```

**Comment by SeaHOH** [comment]
@phuslu 
默认才 1MiB，有必要这么大么。现在代理不算特别稳定，断掉的时候容易丢数据吧？

**Comment by SeaHOH** [comment]
@phuslu 
默认才 1MiB，有必要这么大么。现在代理不算特别稳定，断掉的时候容易丢数据吧？

**Comment by SeaHOH** [comment]
@phuslu 
默认才 1MiB，有必要这么大么。现在代理不算特别稳定，断掉的时候容易丢数据吧？

**Comment by SeaHOH** [comment]
@phuslu 
默认才 1MiB，有必要这么大么。现在代理不算特别稳定，断掉的时候容易丢数据吧？

**Comment by phuslu** [comment]
嗯，删掉了。 😄

**Comment by johnsonz** [comment]
确实需要配置下git，多谢
