### ISSUE TITLE
gae r51上传 “a version or backend parameter is required”

### ISSUE THREAD

**Issue by NAVrasZ** [phuslu/goproxy#1531]
传前11个都没问题，最后一个突然出这个提示然后停止了，后台挂的是goproxy

**Comment by NAVrasZ** [comment]
Error 409: --- begin server output ---
No transaction is in progress.

**Comment by NAVrasZ** [comment]
uploader.py: error: Error parsing gae\app.yaml: Unable to assign value '*** 409' to attribute 'application':
Value 'xx-net-appid9 409' for application does not match expression '^(?:(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{0,99}[a-z\d])$'
  in "gae\app.yaml", line 1, column 14.
怎么感觉重新上传一遍开始随机出错...但goproxy日志里并没有黄/红字

**Comment by SeaHOH** [comment]
有空格

**Comment by NAVrasZ** [comment]
@SeaHOH 409并不是我的appid名，而是上一次的error代码，不知道为什么被程序混进名字里去了...

这台上传的电脑上还同时挂着很重的python3.6任务，可能是这个原因。出错有间隔，每次出错后删掉整个gae文件夹重新解压创建才能正常，发现出错时正好是python3.6开始输出的时候，可能二者不能兼容？

**Comment by NAVrasZ** [comment]
*上传前请关闭其他程序
