### ISSUE TITLE
关于可适用于goagent代理的邮件客户端

### ISSUE THREAD

**Issue by zjhxmjl** [phuslu/goproxy#1532]
@jostyee @phuslu @cxjava @yfdyh000 @johnsonz  and 所有人
目前只能通过浏览器登录gmail,linux下thunderbird无法通过goagent代理收发邮件,不知有何其它应用可以适用(linux系统下)或一定的配置方法来配置thunderbird,thks!

**Comment by 94oiio** [comment]
表示windows下outlook可以

**Comment by ruby186** [comment]
我这边实验，foxmail等对socks5还好点……

gmail其实你试下hosts，找个能用的应该可以的；gmail的pop.gmail.com，smtp.gmail.com，印象中过去三五年只有个把时段封锁很厉害。这玩意搞了的话会民怨太大的，放心。

**Comment by zjhxmjl** [comment]
sorry,win不考虑

**Comment by blob2015** [comment]
如果用的是客户端，根本不用这么麻烦，直接填写ip【mail服务器的】就得了，几年了，就换过一次ip

**Comment by zjhxmjl** [comment]
thks all,问题已经solved

**Comment by zjhxmjl** [comment]
thks all,问题已经solved
