### ISSUE TITLE
关于地区判断问题

### ISSUE THREAD

**Issue by SeaHOH** [phuslu/goproxy#1539]
感觉普通的 IP 地理库不太适合梯子的需求，是否可以考虑使用 APNIC 公布的 IP 分配信息：
https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest
这个是 `国家/地区 | asn 号/ IP 段` 格式的，asn 条目似乎可以无视，然后 CN 条目就只有不到一万条，其中还有 IPv6 信息，而且更新快，感觉很方便。

@phuslu 
请教社长，我这个想法是否可行？行的话我就加入自己的项目替换 17mon 了。

**Comment by phuslu** [comment]
这个问题考虑过。也许这个更准 https://github.com/17mon/china_ip_list

不过我还是不像放弃 ip 地理库的通用特性，所以没有动手。

**Comment by phuslu** [comment]
一旦使用特定的列表，可以使用高效的算法来定位地理位置，比如线段树 https://github.com/toberndo/go-stree

不过考虑到 LRU Cache, 其实没啥差别。

**Comment by SeaHOH** [comment]
原来社长早就考虑过，也就是可行啰。那我就放弃普通 IP 地理库了。
谢谢解答哈。 :laughing:
