### ISSUE TITLE
最新出现的错误提示

### ISSUE THREAD

**Issue by kirbyzhu** [phuslu/goproxy#1541]
前一秒还用得好好的 下一刻就不能从google scholar里面读取endnote的引文信息了

403. That’s an error.

Your client does not have permission to get URL /scholar.enw?q=info:Qlv2hWgj-CAJ:scholar.google.com/&output=citation&scisig=AAGBfm0AAAAAWL-CI-hvHGwehO3Nqxzp3jSAhAlthRNk&scisf=3&ct=citation&cd=0&hl=zh-CN from this server. (Client IP address: 202.119.228.41)

Please see Google's Terms of Service posted at http://www.google.com/terms_of_service.html 

That’s all we know.

![image](https://cloud.githubusercontent.com/assets/10296293/23692167/064b3264-0408-11e7-804e-19e5d9d3bda8.png)

**Comment by phuslu** [comment]
scholar.googleusercontent.com 加入 ForceGAE 试试。

**Comment by kirbyzhu** [comment]
感谢lu大 这么快就进1316了。

**Comment by kirbyzhu** [comment]
@phuslu 升级1316后发现出现流量异常错误， 把forcegae里面的新增的行注释掉之后正常了

我更换了上网环境之后又能正常下载endnote引文文件，可能前面是突发状况

**Comment by phuslu** [comment]
不是突发状况，是你的 ip 混杂了一些不能使用 googleusercontent 的 ip。

r1316 尝试用 ForceGAE 规避，不过看起来有问题。

最好是你用扫 ip 工具检查一下你的这些 ip 是否真的是 google ip

**Comment by kirbyzhu** [comment]
好的 我昨晚确实重新增加了几百个ip 用mff扫出来的一批
