### ISSUE TITLE
请问，gp是依托那个网址来运行？

### ISSUE THREAD

**Issue by 523860169** [phuslu/goproxy#1543]
你好，我有在路由器里利用ipset来匹配google网址以自动走ss，但是电脑上想尝试下gp的效果，却发现gp一直走的路由器上的ss通道，因为当我关闭路由上的ss时，电脑上的gp也死了。
于是我去除.appspot.com和.google.com的ipset规则，并停用路由器的ss，结果还是不行，所以产生了这个疑问，我需要去掉哪个网址的ipset规则，电脑上的gp才不会走ss通道

**Comment by SeaHOH** [comment]
你搞错了，不是域名是 IP。域名即使配置了，也会解析成 IP 再使用。
所以只能黑名单，不能白名单。

**Comment by 523860169** [comment]
@SeaHOH 可是我浏览器里全局走gp，google显示的ip却是ss的ip，且路由器上的ss 停用后，gp也死了啊

**Comment by 523860169** [comment]
@SeaHOH 找到了，应该是.gae.googleusercontent.com，因为在某个没有添加ipset规则的测ip网站上，显示的是hostname是127.194.178.107.gae.googleusercontent.com

**Comment by SeaHOH** [comment]
>google显示的ip却是ss的ip

哪儿显示的？
>因为在某个没有添加ipset规则的测ip网站上，显示的是hostname是127.194.178.107.gae.googleusercontent.com

没看懂，测的什么 IP？

**Comment by 523860169** [comment]
@SeaHOH 这是我浏览器全局走gp情况下，分别访问google和另一个测ip网站的结果，前者在路由器里有设置ipset规则，后者没有
![1](https://cloud.githubusercontent.com/assets/6436073/23734564/d0f9b668-04ba-11e7-9fe0-c12584c961a1.PNG)
![2](https://cloud.githubusercontent.com/assets/6436073/23734565/d15494c0-04ba-11e7-8cf0-ade509fba86e.PNG)

**Comment by SeaHOH** [comment]
懂了。
第一个谷歌是 GoProxy 直连，你设置了 ipset 到 SS 的路由，所以显示 SS IP；
第二个是 GAE 出口 IP，正常。

新建一个 ipset，将以下配置中的域名和 IP 添加进这个 ipset，然后配置走默认路由，不走 SS。
`gae.json -> HostMap -> google_hk | google_cn`

**Comment by 523860169** [comment]
我在firewall.user里是下列这样来和ipset搭配用的，所以，如果要排除gae.json -> HostMap -> google_hk | google_cn里的域名，应该怎么添加iptables规则
ipset flush proxylist
ipset create proxylist hash:ip
iptables -t nat -I PREROUTING -p tcp -m set --match-set proxylist dst -j REDIRECT --to-port 1080
iptables -t nat -I OUTPUT -p tcp -m set --match-set proxylist dst -j REDIRECT --to-port 1080

**Comment by SeaHOH** [comment]
使用 -j ACCEPT 放行，记得把 noproxylist 的规则放在前面匹配。

**Comment by 523860169** [comment]
这样吗？
```
ipset flush noproxylist
ipset create noproxylist hash:ip
iptables -t nat -I PREROUTING -p tcp -m set --match-set noproxylist dst -j ACCEPT
iptables -t nat -I OUTPUT -p tcp -m set --match-set noproxylist dst -j ACCEPT
ipset flush proxylist
ipset create proxylist hash:ip
iptables -t nat -I PREROUTING -p tcp -m set --match-set proxylist dst -j REDIRECT --to-port 1080
iptables -t nat -I OUTPUT -p tcp -m set --match-set proxylist dst -j REDIRECT --to-port 1080
```

**Comment by SeaHOH** [comment]
差不多就这样，其实那两条 PREROUTING 规则好像可以不用。

**Comment by 523860169** [comment]
其实我之前也没有prerouting，后来好像遇到什么了，才加了这两条进去的

**Comment by SeaHOH** [comment]
无所谓，才四条规则，不算多。

**Comment by 523860169** [comment]
我ipset这么设置
```
ipset=/mail.google.com/noproxylist
ipset=/mail.l.google.com/noproxylist
ipset=/maps.l.google.com/noproxylist
ipset=/scholar.google.com/noproxylist
ipset=/scholar.google.com.hk/noproxylist
ipset=/www.l.google.com/noproxylist
ipset=/.google.com/proxylist
ipset=/.google.com.hk/proxylist
```
firewall.user这么设置
```
ipset flush noproxylist
ipset create noproxylist hash:ip
iptables -t nat -I PREROUTING -p tcp -m set --match-set noproxylist dst -j ACCEPT
iptables -t nat -I OUTPUT -p tcp -m set --match-set noproxylist dst -j ACCEPT
ipset flush proxylist
ipset create proxylist hash:ip
iptables -t nat -I PREROUTING -p tcp -m set --match-set proxylist dst -j REDIRECT --to-port 1080
iptables -t nat -I OUTPUT -p tcp -m set --match-set proxylist dst -j REDIRECT --to-port 1080
```
但是不挂代理时mail.google.com还是可以上，gp在google的ip还是显示ss的ip

**Comment by 523860169** [comment]
我改好了，firewall.user里那俩顺序调换一下后可以了。谢谢

**Comment by SeaHOH** [comment]
话说，其实当后面有个透明代理时，想在这个透明代理处正确分流前面一个代理的流量是比较麻烦的，而且可能不是很精准。这涉及到两个代理使用的 DNS，解析结果务必要相同。

**Comment by 523860169** [comment]
@SeaHOH 我吧google_hk里的几个网址全删掉，替换了，检测到的可用gae Ip后，已经成功解决问题了。
现在不仅不需要路由器段另建ipset白名单，goa也不会再一直提示deadline了

**Comment by SeaHOH** [comment]
这也是种解决方法，排除了 DNS 不一致的问题。
 
关于异常验证，试一下下面的方法。我没有使用 goproxy，但是这应该是可行的。
既然用 IP 的话，建议新加一个 IP 列表，里面全部放 gws IP；
然后把 SiteToAlias 里面的 google_hk 改成这个列表名称。

**Comment by 523860169** [comment]
嗯，我试试看，现在变这样了
	"HostMap" : {
		"gws_ip": [
			"115.164.140.234",
			"172.217.25.127",
			"189.247.160.94",
			"61.238.239.173",
			"66.96.224.155",
			"113.171.247.39",
			"115.164.140.234",
			"113.171.247.39",
			"66.96.224.155",
			"66.96.224.26",
			"203.133.72.152",
		],
		"google_hk": [
			"mail.google.com",
			"mail.l.google.com",
			"maps.l.google.com",
			"scholar.google.com",
			"scholar.google.com.hk",
			"www.l.google.com",
		],
		"google_cn": [
			"www.g.cn",
			"www.google.cn"
			]
	},
	"SiteToAlias": {
		"*.doubleclick.net": "google_cn",
		"*.google-analytics.com": "google_cn",
		"*.google.cn": "google_cn",
		"*.googlesyndication.com": "google_cn",
		"*.googletagmanager.com": "google_cn",
		"*.googletagservices.com": "google_cn",
		"csi.gstatic.com": "google_cn",
		"fonts.gstatic.com": "google_cn",
		"dl.google.com": "google_cn",
		"fonts.googleapis.com": "google_cn",
		"*.appspot.com": "gws_ip",
		"*.ggpht.com": "gws_ip",
		"*.google.com": "gws_ip",
		"*.google.co.jp": "gws_ip",
		"*.google.co.kr": "gws_ip",
		"*.google.co.uk": "gws_ip",
		"*.google.com.hk": "gws_ip",
		"*.google.com.sg": "gws_ip",
		"*.google.com.tw": "gws_ip",
		"*.googleapis.com": "gws_ip",
		"*.googlecode.com": "gws_ip",
		"*.googlegroups.com": "gws_ip",
		"*.googleusercontent.com": "gws_ip",
		"*.gstatic.com": "gws_ip",
		"*.ytimg.com": "gws_ip",
		"upload.youtube.com": "gws_ip",
		// "*.youtube.com": "gws_ip",
	},

**Comment by SeaHOH** [comment]
google_hk 还是要用 IP 的，刚才说漏了一点，下面这个保持原样
"*.appspot.com": "google_hk",

**Comment by 523860169** [comment]
这样不是就跟我之前的做法差不多吗
```
"google_hk": [
			"115.164.140.234",
			"172.217.25.127",
			"189.247.160.94",
			"61.238.239.173",
			"66.96.224.155",
			"113.171.247.39",
			"115.164.140.234",
			"113.171.247.39",
			"66.96.224.155",
			"66.96.224.26",
			"203.133.72.152",
		],
```

**Comment by SeaHOH** [comment]
google_hk 还可以放 gvs IP，增加 good IP 数量。
另建 gws IP 列表确保直连正常使用。

**Comment by 523860169** [comment]
就是gws_ip放gws，google_hk放gvs的？
其实我不是很懂这两个的区别，要不两个都放在google_hk，就不要再弄gws_ip这个表了？

**Comment by SeaHOH** [comment]
如果你不清楚就不要改吧，只是看你说有异常提示验证才想到这么个方法，我也没用过。
google_hk 可以多放点 IP，几百上千个，gws 和 gvs 都可以。
