### ISSUE TITLE
最近好像访问google的网站频繁出问题

### ISSUE THREAD

**Issue by kirbyzhu** [phuslu/goproxy#1545]
![image](https://cloud.githubusercontent.com/assets/10296293/23733515/595f6e5a-04b4-11e7-808d-d67d0a081c44.png)

访问youtube出现人机验证 而且频繁出现 基本上每点一个页面就出现一次
访问google出现流量异常
访问scholar.google出现页面拒绝访问

昨天重新用mff全部扫描过一遍ip 之前使用gp从来没出现过这些问题

**Comment by SeaHOH** [comment]
可能混进了移动的反代，用的人多了，所以偶尔会验证。

**Comment by blob2015** [comment]
是有验证，不时出现，但若lz这般的，俺还是没有

**Comment by thundery1** [comment]
偶尔会出现人机验证的
