### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by THLIVSQAZ** [phuslu/goproxy#1554]
heroku+goproxy-server.php.go
部署正常
![1489401936696](https://cloud.githubusercontent.com/assets/25531652/23855033/24326b86-07c2-11e7-91d5-231d9d687cbd.jpg)

直接访问正常
![1489401938034](https://cloud.githubusercontent.com/assets/25531652/23855068/3f016d68-07c2-11e7-801e-107ee08e29ea.jpg)
goproxy错误信息
![1489401938908](https://cloud.githubusercontent.com/assets/25531652/23855086/5a1cfdd8-07c2-11e7-964d-3256a3c3a66e.jpg)
浏览器错误信息
![1489401939578](https://cloud.githubusercontent.com/assets/25531652/23855119/7f11ce5c-07c2-11e7-9874-a32319aa6459.jpg)

  @phuslu udp包受阻？配置问题还是网络问题？

**Comment by THLIVSQAZ** [comment]
经过测试，在电脑上连接正常
![1](https://cloud.githubusercontent.com/assets/25531652/24038045/b9fcd844-0af7-11e7-907a-9ac4e5b3564c.png)
![2](https://cloud.githubusercontent.com/assets/25531652/24038044/b9f309f4-0af7-11e7-9f93-100aafabd7ab.png)
  @phuslu 疑似goproxy-arm存在问题

**Comment by phuslu** [comment]
不是。推测是环境的 ipv6 配置存在问题，禁用系统的 ipv6 试试。

**Comment by THLIVSQAZ** [comment]
手机上没有使用ipv6，也用root强禁了，倒是发现一个很奇怪现象，换了个云部署，手机上访问还是一样的错误信息，有个共同点，访问什么网站都失败，唯独访问部署自家的官网正常，是不是goproxy规则有异常？

**Comment by phuslu** [comment]
在 https://github.com/phuslu/goproxy/issues/1584 重复了，关闭这个反馈。
