### ISSUE TITLE
goproxy166 mac 版本测试

### ISSUE THREAD

**Issue by ydq** [phuslu/goproxy#156]
问题同 #24 （*r152版本测试反馈*）

使用php模式一段时间后还是出现503（一般是访问youtube有很多预览图多刷新几次，加载到一半后出现）

然后页面显示**`Service Unavailable`**,比如要重新启动goproxy或者reload一下才恢复正常~

默认生成出来的证书依旧是红色的叉叉提示“**`此根证书不被信任`**”，而goagent生成的证书导入到系统默认状态仅仅只是黄色感叹号提示“**`此证书尚未经过第三方验证`**”

启动速度远远不及GoAgent，体积远大于GoAgent

@phuslu （2015年09月04日23:44:01）
我把服务器的***php***改用**`nodejs`**，使用**`index.js`**后**`完全正常`**不会再出现**`503`**以及**`Service Unavailable`**问题了
*同时之前GoAgent下使用php会导致访问Google等网站，标签栏一直转啊转的在加载某个东西似的，以及youtube主页点击视频后地址栏变了但是不能直接跳转到播放非得刷新一下才能播放的问题，改用nodejs后也解决了。*

**Comment by thundery1** [comment]
俺这儿时不时连不上云空间,显示eof...大概是gfw干扰的吧..

**Comment by phuslu** [comment]
非常感谢，我看下。

**Comment by wrfly** [comment]
@phuslu 太佩服你啦！感谢你无私的付出！

**Comment by phuslu** [comment]
感谢更新测试情况，为什么不适用 golang 版本，它的效率最高。

**Comment by ARwMq9b6** [comment]
神！竟然能察觉顶楼的帖子更新了内容。
