### ISSUE TITLE
实在是走投无路了，不是黄字就是红字，求高手调试，@有偿付费调试@

### ISSUE THREAD

**Issue by gelujay** [phuslu/goproxy#1562]
求高手支招，本人WX:gelujay
/(ㄒoㄒ)/~~

**Comment by phuslu** [comment]
请提供更多信息再求助。

**Comment by gelujay** [comment]
![image](https://cloud.githubusercontent.com/assets/25122892/24078019/3c419d90-0c9b-11e7-9d96-12bb725d2264.png)
