### ISSUE TITLE
就问下移动现在还有上下对等的带宽吗

### ISSUE THREAD

**Issue by NAVrasZ** [phuslu/goproxy#1569]
新办改光纤，加到100M，上行只有1MB/s（bt最大上传），求安慰T_T

¬_¬不过讲真移动之前就是收购铁通，用的人多了感觉这是药丸的节奏啊

营业厅说没有单独售卖宽带的业务，机顶盒捆绑宽带就是普通宽带，v2ex里讲到的“精品宽带”也没有
那么问题来了
挖掘机...(划掉
各位的上下对等的宽带是如何办成的呢？之前我的是小区宽带，但新搬的地方没有小区宽带统一光纤入户
难不成实际上每个机房的方（政）案（策）都不一样？

这下彻底坑了，强制包年业务不可取消，而且入户光纤线只有一条三家ISP共用（躺

**Comment by NAVrasZ** [comment]
多说一句，刚办是60M，加到100M之后突然发现干扰没了, 之前是试遍各种方式都堵得牢牢的，现在基本又回到之前满速过墙的状态（但上传算是坑了...

**Comment by jyuan15** [comment]
有啊
![2017-03-21_111449](https://cloud.githubusercontent.com/assets/12642186/24131132/b25a70e6-0e27-11e7-9a80-d223279bf766.jpg)

**Comment by NAVrasZ** [comment]
![image](https://cloud.githubusercontent.com/assets/20354364/24131293/a6b9e9be-0e28-11e7-95ab-9240608bf6fd.png)

天，楼上那是百兆上行不限速嘛....真的无语了

**Comment by NAVrasZ** [comment]
打10086咨询这档子问题，客服除了抵赖还是抵赖

（想把客服扔出去>"<啊不对我手机呢

**Comment by NAVrasZ** [comment]
另外移动有透明代理这种破事
现在观察到除了以前用过的117.xxx和39.xxx还有一个新出很少的186.xxx
其中39上YouTube最快
那么这三个中有哪一个不是透明代理的吗？
以前39的ip能查到对应自家地址，现在也不能了跑到浙江去了（谷歌第一个网站）

**Comment by jasonliul** [comment]
俺刚刚长宽换电信...

结果发现ssh, 赛风的速度被限制, 无耻

**Comment by NAVrasZ** [comment]
前年脱的电信的坑，100M对500k上传...(坑x2

三家已坑两家，不知有没有联通的go友（手动滑稽x2

**Comment by phuslu** [comment]
联通和移动的出国速度一直不错，用 goproxy 也比较流畅。

电信出国线路一直很糟，不过最近一段时间 goproxy 的在电信的表现比以前要好很多，可能和电信扩容有关。

**Comment by jasonliul** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/24134921/3ea82326-0e42-11e7-85e9-f6320d8adc1a.jpg)
电信30M[所谓50]

**Comment by NAVrasZ** [comment]
这缩水>_<
好吧虽然移动今年比去年坑，但和电信一比...

不过一直觉得移动对用户分级，人多了小带宽用起来很不稳定（像移动牌铁通...
前两天60M时全是黄红字，这是改为100M后截图
![goproxy](https://cloud.githubusercontent.com/assets/20354364/24135862/1c8d23d6-0e47-11e7-94e8-5faa7af079e6.PNG)
任务管理器里狗牙网速也差不多平了
![image](https://cloud.githubusercontent.com/assets/20354364/24136181/84174530-0e48-11e7-96c5-869c65a0d1e7.png)
目测门槛是个人带宽最大速率1/2，之前是50M为，今年改到了100M，要是明年变200M...窝要那么大下行带宽干嘛（摔）考虑入联通233

**Comment by blob2015** [comment]
@NAVrasZ 
以前，这边联通就是小区人一多，就肯定卡，在高峰期。
联通在这边要性价比，没有移动好，要性能，没有电信稳定。
拿着曾经最好的牌，打成这样，也算是传说中的烂泥。

**Comment by asd2003asd** [comment]
联通用着马马虎虎，价格还算便宜，600包年20M,出国和下载还行，上传就不敢想了，严重不对等。

**Comment by NAVrasZ** [comment]
额...这样啊233那我将就用着吧
我这叫身在福中不知福_(:з」∠)_

**Comment by starobots** [comment]
电信出口拿出来单卖的。上海精品网一个月多交钱就给你好的出口。
说实话，固网联通还是最良心。不过谁叫电信固网地方大，移动有钱。

**Comment by tec1987** [comment]
说白了，还是价格，几十块钱/月，一年才几百块的宽带，能和几百块/月，上千块/月的线路比么。。。

便宜有便宜的道理，贵有贵的好处，不管哪家ISP，这是不变的。。。

**Comment by NAVrasZ** [comment]
今天正好路过移动小区宽带机房，问他们这个问题，客服委婉透露：
移动宽带上行设定是当初上门装机的师傅用他的仪器设定的
我说为啥升到100M上传还是只有1M...
根据他们建议，我拿小区对等宽带账号登陆连光纤的路由器测速
这是小区宽带线路测速
![benchmark](https://cloud.githubusercontent.com/assets/20354364/24196850/43334d78-0f3a-11e7-9c45-da19dd2352f4.PNG)
这是光纤线路使用小区宽带账号
![default](https://cloud.githubusercontent.com/assets/20354364/24196886/637b5292-0f3a-11e7-8ca9-53a2e82cf0fd.PNG)

下次装宽带记得给上门师傅塞条烟，也许有惊喜（手动滑稽

**Comment by starobots** [comment]
这玩意后台设置的，都是软限速。
当然外包的客服没这个权限。
你要是认识人，给你调就行。

**Comment by NAVrasZ** [comment]
@starobots 打10050他们说也调不了只能看到我办的是100M光宽带，这次他们主动提出上门服务不像昨天推脱估计有戏

看来主动把牌亮明让客服知道糊不到我比之前被客服牵着走有效。

**Comment by NAVrasZ** [comment]
![image](https://cloud.githubusercontent.com/assets/20354364/24349207/dffb6b34-1310-11e7-8d88-af62262bb55c.png)
得，今儿个体验到啥叫胳膊拧不过大腿 ：)
折腾一个星期后，我现在是交着光纤的钱用着adsl的网
师傅挺好，确实上传比下载还多了，只不过他们动的是下载 
:-) :-) :-) :-) :-) :-) :-) :-)

**Comment by SeaHOH** [comment]
@NAVrasZ 
国内也是 3Mbps？？

**Comment by NAVrasZ** [comment]
@SeaHOH 用dns上的...应该是国内
用装了360的电脑测速也是一样，“相当于2-3M带宽”

**Comment by SeaHOH** [comment]
@NAVrasZ 
我不是指这个测速网站代表的出国带宽，是问你浏览国内网站也是这个带宽吗？

**Comment by NAVrasZ** [comment]
@SeaHOH 360测的就是网页打开速度吧...？
这个网站之前我测是大约100M的结果（楼上）现在2.6M肯定不对....

**Comment by SeaHOH** [comment]
不越修越慢了，这能忍？

**Comment by NAVrasZ** [comment]
@SeaHOH 不能，现在唯一能告的只有省厅了...10086基本废了
明显是所谓“领导”故意坑了我，叫几个师傅来抄了光猫号，晚上说“我叫人帮你改了”一测就变成了电话线....
再打过去说你至少先还我之前正常速度吧，那边就推脱“明天再帮你找个更好的调”“我在开会等下再打来”“你这个调要上报，我报了你等两天吧”
当初改电话线速度怎么就那么爽快不用上报呢（摔

**Comment by dou4cc** [comment]
@NAVrasZ 移动封bt

**Comment by NAVrasZ** [comment]
@dou4cc 貌似是，有些国外的连不上。但正常一般国外的种子例如rarbg上的都能很快下完，只有冷门的1/2个peer的尽管对方100%但就是连不上。
这种情况一般挂一天都连不上就没救，移动奇怪的是有时（例如凌晨/下午）突然国外连接无比顺畅，gp连YT速度10000+kbps。昨天还挂了2个老种，一个是只有几b的速度另一个没有peer，第二天再看全都完成了233
不多说，总觉得啥事一说出来就被立马关照。。。

**Comment by NAVrasZ** [comment]
ps：宽带上传的事，自从改回后没再折腾，过了半年偶然一测上传已有70+M，可能要等机房升级不是瞎说，虽然对方也没有承认（还就是电信牌铁通）

**Comment by dou4cc** [comment]
@NAVrasZ 移动不能bt，除非被劫持到移动缓存服务器

**Comment by SeaHOH** [comment]
bt 也能缓存？这是抢渣雷生意啊~

**Comment by NAVrasZ** [comment]
@dou4cc 这个我知道，一两年前是这样，无论如何都下不动，后来宽带升级改造后看起来是放开了些，虽然到不了满速但有1-2MB/s（ip解析显示国外）。听说其他地区仍是封的，用官话讲就是“机房政策不一样”（噗
![rrr](https://user-images.githubusercontent.com/20354364/30009547-e0f28896-915b-11e7-872b-fc5268c6c6af.PNG)
host
![rrrr](https://user-images.githubusercontent.com/20354364/30009557-eed3a6e8-915b-11e7-9a02-2cb011798935.PNG)
gp

**Comment by NAVrasZ** [comment]
另外现在bt协议默认加密，不知道是不是因为这个

**Comment by dou4cc** [comment]
@SeaHOH @NAVrasZ 加密bt能降级成明文bt

**Comment by NAVrasZ** [comment]
我搜了下貌似是移动nat？确实我做种貌似有问题经常没什么人，[tracker](https://github.com/ngosang/trackerslist)也被封了不少
但[ip](https://www.whatismyip.com/)显示是路由器ip，应该如何验证nat？

**Comment by dou4cc** [comment]
@NAVrasZ nat不影响upnp，是移动故意限制的，不信你要个公网ip，还是不能bt。ipip.net显示的ip和路由器拨到的ip一样就是公网ip，否则内网ip。

**Comment by NAVrasZ** [comment]
![dghfgh](https://user-images.githubusercontent.com/20354364/30314492-6fb840a2-97d3-11e7-9595-f9d144a07f98.PNG)
![dsfg](https://user-images.githubusercontent.com/20354364/30314518-7d5ae192-97d3-11e7-95cc-f3e65ded7408.PNG)
![cfgj](https://user-images.githubusercontent.com/20354364/30314522-8035ef9c-97d3-11e7-881b-3189f7231043.PNG)

**Comment by qwerttaa** [comment]
只要政策在，任何不达标问题不要打客服，徒劳

直接工信部投诉，解决起来巨快

**Comment by NAVrasZ** [comment]
@qwerttaa 国内的带宽都只标下载速度，不确定是否会有用

ps：@dou4cc 
![dghfgh](https://user-images.githubusercontent.com/20354364/30314492-6fb840a2-97d3-11e7-9595-f9d144a07f98.PNG)
![dsfg](https://user-images.githubusercontent.com/20354364/30314518-7d5ae192-97d3-11e7-95cc-f3e65ded7408.PNG)
下载有点问题但没到不能下的地步
![cfgj](https://user-images.githubusercontent.com/20354364/30314522-8035ef9c-97d3-11e7-881b-3189f7231043.PNG)
热种一堆迅雷吸血，不知道有什么办法（迅雷支持加密了貌似）

**Comment by starobots** [comment]
联通现在新的入户协议都写了100m、200m是10m上传，50m是5m上传，500m的是20m上传。
好像多拨也没上传带宽叠加了，诶。
不下国内种子就完了，或者用qbittorrent，git上就有项目页，能给断开客户。
不知道他们会不会以后开发自动检测吸血的插件，感觉不费事吧，emule的dlp都弄了好多年了。

**Comment by NAVrasZ** [comment]
@starobots 交代越详细越好，体现对用户尊重，就是这上传学电信抠门 xD qb看issue讨论有默认内置反吸血，只是没有设置可调，不知道为啥挡不住......手动断开比较麻烦。下的种子是rarbg上的，估计有人搬到了国内美剧网站
