### ISSUE TITLE
Goproxy DNS居然还是114 

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1573]
偶然路由器里面查看到...
默认启动时, GP使用gae.json里面的dns解析, 俺不信任114. 谷歌的好像很早被玩残.

所以改为
209.244.0.3
209.244.0.4
或者其他....

不过一旦连接, 就用不上这个了.
试了一下, 好像没有之前启动后死翘翘的问题.

**Comment by phuslu** [comment]
啊，没有太好的备选。我研究一下，看下能不能换掉

**Comment by wpyok500** [comment]
建议支持自定义配置

**Comment by hcym** [comment]
无所谓的啦
我都要添加运营商的，感觉防火墙只是屏蔽反动网站
不少加密网盘，下载服务器直接跑都能跑满带宽

**Comment by jasonliul** [comment]
@phuslu 
奇怪的是长宽下启动从无故障, 只有电信.
114解析google.cn是故意出错, 不值得信任.

俺建议129.250.35.250/129.250.35.251, 这一组一直都是最稳定.

**Comment by jzmswe** [comment]
114前两年曝出偷窃用户隐私。

**Comment by jasonliul** [comment]
Level31	209.244.0.3	209.244.0.4
Verisign2	64.6.64.6	64.6.65.6
Google3	8.8.8.8	8.8.4.4
DNS.WATCH4	84.200.69.80	84.200.70.40
Comodo Secure DNS	8.26.56.26	8.20.247.20
OpenDNS Home5	208.67.222.222	208.67.220.220
DNS Advantage	156.154.70.1	156.154.71.1
Norton ConnectSafe6	199.85.126.10	199.85.127.10
GreenTeamDNS7	81.218.119.11	209.88.198.133
SafeDNS8	195.46.39.39	195.46.39.40
OpenNIC9	96.90.175.167	193.183.98.154
SmartViper	208.76.50.50	208.76.51.51
Dyn	216.146.35.35	216.146.36.36
FreeDNS10	37.235.1.174	37.235.1.177
Alternate DNS11	198.101.242.72	23.253.163.53
Yandex.DNS12	77.88.8.8	77.88.8.1
UncensoredDNS13	91.239.100.100	89.233.43.71
Hurricane Electric14	74.82.42.42	 
puntCAT15	109.69.8.51

https://www.lifewire.com/free-and-public-dns-servers-2626062
这个列表不错

**Comment by wpyok500** [comment]
dns我换了119.29.29.29，182.254.116.116，目前缓解了context deadline exceeded    good_addrs=0问题

**Comment by SeaHOH** [comment]
马克马克

**Comment by blob2015** [comment]
mark
一些小dns，访问一些诸如微博什么的，国内的一些东西，有时候会有问题

**Comment by jasonliul** [comment]
hp-pelzer.cn 58.240.184.86
mail.youqii.com 116.247.97.42
mail.sinnsa.com 180.168.126.75
servers.szgwbn.net 211.162.77.182
ttdco.cn 58.253.81.99

外国人的奸诈选择, 中国外企的DNS.

**Comment by cnrip** [comment]
mark,以后可能会有用.

**Comment by kirbyzhu** [comment]
我也继续马克一下

**Comment by xrwz007** [comment]
mark!

**Comment by Asteroids89** [comment]
Mark下

**Comment by ShureCool** [comment]
给力，收集起来

**Comment by fredericky123** [comment]
请问gae.user里的dns是否可以多加几个呢，加入的顺序有影响吗？goproxy是否会自动筛选呢 @phuslu
