### ISSUE TITLE
VPS版本提示SimplePAM error

### ISSUE THREAD

**Issue by whu-inf** [phuslu/goproxy#1581]
在Vultr上搭的服务端。客户端使用chrome + switchy omega的https代理。请问pam认证应该怎么用？我无论使用linux的账户，或是新建pwauth.txt写入的账户，都出错误。
@phuslu 

goproxy-vps.toml配置
[[http2]]
listen = ":443"
server_name = ["www.xxxxxx.tk","xxxxxx.tk"]
proxy_fallback = "file:///var/www/html"
proxy_auth_method = "pam"

W0323 12:47:35.500009   20550 goproxy-vps.go:112] SimplePAM: username=goproxy password=goproxy error: exit status 3

![image](https://cloud.githubusercontent.com/assets/14085739/24238142/35235868-0fe4-11e7-91cb-6d76d24872c9.png)

![image](https://cloud.githubusercontent.com/assets/14085739/24238295/ce3d6afc-0fe4-11e7-81c2-94613a616c47.png)

**Comment by Vbubblery** [comment]
这个问题解决了么？
