### ISSUE TITLE
一启动就出现这个错误

### ISSUE THREAD

**Issue by wpyok500** [phuslu/goproxy#1583]
W0325 22:23:37.542108   16568 rootca.go:172] Verify RootCA("GoProxy") error: x509: certificate signed by unknown authority, try import to system root
E0325 22:23:37.546108   16568 rootca.go:174] Remove Old RootCA("GoProxy") error: Cannot find object or property.
E0325 22:23:37.548044   16568 rootca.go:177] Import RootCA("GoProxy") error: Access is denied.

**Comment by phuslu** [comment]
如果是 macos 平台请暂时忽略，不影响使用。

**Comment by wpyok500** [comment]
@phuslu 我的win10

**Comment by phuslu** [comment]
使用管理员权限运行。
