### ISSUE TITLE
今天突然无法连网

### ISSUE THREAD

**Issue by chinagirl1** [phuslu/goproxy#1587]
win7 64位   Google Chrome 57.0.2987.110(64-bit)  插件 SwitchyOmega  显示
![default](https://cloud.githubusercontent.com/assets/16515138/24332928/bbf83b0c-1281-11e7-96a1-21166b17221e.PNG)

**Comment by chinagirl1** [comment]
SS正常

**Comment by phuslu** [comment]
gae.json 配置有误。

**Comment by chinagirl1** [comment]
谢楼主大神！！！ 有点不明白，我是在原文件的gae.json，重名为gae.user.json  只是在gae.user.json 中加入我的id和服务器id而以。原文件gae.json我没改变。

**Comment by chinagirl1** [comment]
我是在原文件的gae.json一份

**Comment by chinagirl1** [comment]
我是在原文件的gae.json复制一份

**Comment by phuslu** [comment]
那检查一下 gae.user.json 吧，貌似引号有问题
