### ISSUE TITLE
此视频包含来自National Geographic的内容，由于版权的原因，该合作伙伴已禁止在您所在的国家/地区播放这些内容。

### ISSUE THREAD

**Issue by Sec20** [phuslu/goproxy#1595]
这个问题不知道怎么解决，是和以前GoAgent的解决方法一样吗？求大家指导。
https://youtu.be/OmZMWQ8eTmo

**Comment by jzmswe** [comment]
以前的方法失效。

**Comment by jasonliul** [comment]
亚洲贱民, 知道没?
:)

**Comment by jzmswe** [comment]
@jasonliul 美国人在亚洲怎么办？

**Comment by jzmswe** [comment]
楼主的网址不对劲，youtu.be？虽然最后转到youtube。但跳转后的网址后面多了个=youtu.be

**Comment by Sec20** [comment]
@jzmswe 网址就是从YouTube分享功能复制上来的
![2017-03-30 14 48 47](https://cloud.githubusercontent.com/assets/21214203/24491083/240a1b6a-1558-11e7-835b-264b6e394051.png)
另外求教现在有什么别的解决方法？

**Comment by Sec20** [comment]
@jzmswe 直接搜名字的话搜索结果里面有，在后面。

**Comment by jzmswe** [comment]
正常的网址应该是这个：
https://www.youtube.com/watch?v=OmZMWQ8eTmo

**Comment by Sec20** [comment]
@jzmswe 这个分享功能YouTube出了好久了吧，一样可以用的。

**Comment by NAVrasZ** [comment]
youtu.be youtube自家短网址

自测gp+sni 能上，普通gp用法全局不行

**Comment by starobots** [comment]
NG在其他国家卖版权的，这种视频是被版权骗子跟utb举报过，或者他自己设置的。
这和亚洲贱民有啥关系，弄玄学弄多了吧？
https://www.youtube.com/watch?v=76FOnCgEnyc
这个也是FBI hostage rescue team，画质不则么样。
直接youtube搜一下不就行了。

**Comment by Sec20** [comment]
@starobots 我就是要看这段，顺便问一下地区限制的问题，既然看不到就算了。

**Comment by p1956** [comment]
这种等同全球禁止/视频无法播放，在订阅中看到过类似的视频，一上传也是类似这样的提示“****该合作伙伴已禁止在您所在的国家/地区播放这些内容”，一直0观看量，官方VEVO的，后来解禁就正常了
