### ISSUE TITLE
胜利日大阅兵  

### ISSUE THREAD

**Issue by tylokfree** [phuslu/goproxy#160]
老不死百人方队 1.255.22.0/24
![1](https://cloud.githubusercontent.com/assets/13965217/9647174/ed720258-520c-11e5-9fc3-a7ff14d91877.PNG)

**Comment by invincibility** [comment]
厉害，这个版本的gogotester没见过，可以共享不。

**Comment by sundaqing1969** [comment]
感谢分享

**Comment by xyuanmu** [comment]
楼主这些ip延时真的是超低啊，感谢！阅兵快开始了，看阅兵去。

**Comment by pug908** [comment]
修复ip工程的一段而已

**Comment by EmmieMcDonald** [comment]
请问这是什么扫描软件

**Comment by wangbingqian** [comment]
多半活不长

**Comment by vincent131** [comment]
什么版本？

**Comment by xyuanmu** [comment]
楼主的软件应该是MotherFuckerFang，地址：[云端硬盘](https://drive.google.com/file/d/0B4lIa3JGSHbQakpRZFZlS1c2WVE/view)

**Comment by ARwMq9b6** [comment]
谢谢！+
谢谢楼上。

**Comment by aOJzQT** [comment]
抗击共匪的日子还将继续，我们期待胜利日的到来！！
自由必胜，民主必胜，屁民必胜！
![xxnet](https://cloud.githubusercontent.com/assets/13990565/9652462/3170babe-520b-11e5-95b1-9d271fb4d9ba.jpg)
