### ISSUE TITLE
win7 64bit chrome  youtube乱码

### ISSUE THREAD

**Issue by chinagirl1** [phuslu/goproxy#1601]
win7 64位  chrome 版本 57.0.2987.110 (64-bit)  youtube乱码  goproxy  r1346     
![Uploading 捕获.PNG…]()
![Uploading youtube.PNG…]()

**Comment by chinagirl1** [comment]
win7 64位铬版本57.0.2987.110（64位）youtube乱码go​​proxy r1346
![youtube](https://cloud.githubusercontent.com/assets/16515138/24547075/b4fe577e-1640-11e7-8158-7b48ff6432d1.PNG)
![default](https://cloud.githubusercontent.com/assets/16515138/24547085/bcf41270-1640-11e7-98f0-ee5fd8b9f08d.PNG)

**Comment by phuslu** [comment]
服务端升级一下还有这个问题吗？

**Comment by caofengzi** [comment]
win7 32位1346版沒有問題。

**Comment by chinagirl1** [comment]
服务端升级？是不是重新上传AppID

**Comment by chinagirl1** [comment]
急

**Comment by phuslu** [comment]
是的。

**Comment by cryyifei** [comment]
![qq 20170331215345](https://cloud.githubusercontent.com/assets/26810943/24553531/1156328c-165d-11e7-9a59-083f5103320b.png)
怎么办?

**Comment by phuslu** [comment]
@cryyifei 升级服务端试试。。。

**Comment by cryyifei** [comment]
@phuslu  The authentication flow has completed.代表升级了吗？但也是不行

**Comment by wpyok500** [comment]
用r57服务端重新上AppID部署，或者.youtube=goole_hk去掉注释试试。

**Comment by vcheng** [comment]
报告，升级服务器也不管用。

**Comment by phuslu** [comment]
这，好吧。我明天再修修，换个效率略低的修法肯定能修掉。。。

**Comment by cryyifei** [comment]
@phuslu  我成功啦！谢谢

**Comment by chinagirl1** [comment]
@phuslu  
升级服务端显示
{
    "type": "appengine",
    "host": "xxxxxx.appspot.com",
    "software": "Google App Engine/1.9.48",
    "error": "No Password."
