### ISSUE TITLE
r1348无法连接youtube

### ISSUE THREAD

**Issue by chinagirl1** [phuslu/goproxy#1605]
win7 64bit  Google chrome 版本 57.0.2987.133 (64-bit) GoProxy r1348无法连接youtube    显示"无法访问此网站

网址为 https://www.youtube.com/?gl=HK 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_CONTENT_DECODING_FAILED "
![default](https://cloud.githubusercontent.com/assets/16515138/24579037/0fe36438-1720-11e7-809c-cd8b819ddd68.PNG)
![1346](https://cloud.githubusercontent.com/assets/16515138/24579038/12452162-1720-11e7-94b1-c00d23e0fe20.PNG)

**Comment by phuslu** [comment]
https://github.com/phuslu/goproxy/issues/1600
