### ISSUE TITLE
如何修改全局代理的端口

### ISSUE THREAD

**Issue by Limsig** [phuslu/goproxy#1606]
我同时在用xx-net，于是把gop的监听端口改成了8088，但改了之后貌似全局就不能走gop了，我猜是因为全局的端口还是8087，如何修改让全局端口也变成8088呢？谢谢大家！

![image](https://cloud.githubusercontent.com/assets/22915681/24584685/eba7b42e-17a7-11e7-93f7-743bf40ab450.png)

**Comment by caofengzi** [comment]
得用resource hacker修改端口。

**Comment by kirbyzhu** [comment]
@Limsig 我也这么试过 建议修改xxnet的端口设置 那个更方便 
另外没必要同时使用这两个 用了gop之后 就懒得再开xx了

**Comment by phuslu** [comment]
@kirbyzhu 呃，就问题解决问题就好了。最后的泛泛而谈的两者比较尽量不要这么讲，避免 [FUD](https://zh.wikipedia.org/zh-cn/FUD) 嫌疑。

**Comment by Limsig** [comment]
谢谢各位，所以不能通过gop直接改是吧。开xxnet主要是因为gop不能自动扫ip啊。以及xxnet可以改全局代理的端口么？@kirbyzhu

**Comment by wenliyang** [comment]
@Limsig 你可以在 XX-Net 自动扫到好用的IP后，把扫到的IP导入 goproxy 中使用
XX-Net 的相关问题最好去那个项目提 issue

**Comment by kirbyzhu** [comment]
@Limsig 没试过改gop的全局端口 其实你要解决的就是端口冲突后两者不能并行运行的事情 需要xxnet扫描的话 改了xxnet的监听端口就可以了 xxnet后台运行不影响的 
另外你前面和我的想法差不多 但是现在发现没必要 使用其他扫ip的工具 一次性扫个几千 放到gop里面 至少很长很长一段时间不要操心ip的事情 效率很高 而一直运行xx的话 还是占用电脑资源的

**Comment by kirbyzhu** [comment]
#373

**Comment by Limsig** [comment]
好的，谢谢大家！
