### ISSUE TITLE
如何实现带宽分流？

### ISSUE THREAD

**Issue by hyperdoit** [phuslu/goproxy#1609]
众所周知，有很多免费的shadowsocks服务器，但是很多都有限流，有办法把连接随机分配吗，那样子看视频可能可以快一点。

**Comment by hyperdoit** [comment]
比如说，有软件可以随机分配连接，然后设置为访问本地的多个端口来实现吗？

**Comment by Kisesy** [comment]
SS里的负载均衡不是干这个的？

**Comment by hyperdoit** [comment]
是干这个的吗，那么如何设置呢？
