### ISSUE TITLE
疑似证书导入问题

### ISSUE THREAD

**Issue by hyperdoit** [phuslu/goproxy#1610]
使用r1292没有问题，使用r1349会出现如下错误

```您的连接不是私密连接

攻击者可能会试图从www.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_INVALID
```
注意，是一切网站

**Comment by smovie** [comment]
同出现一样的错误

**Comment by smovie** [comment]
W0404 21:56:49.633125    3132 rootca.go:172] Verify RootCA("GoProxy") error: x50
9: certificate signed by unknown authority, try import to system root
E0404 21:56:49.648750    3132 rootca.go:174] Remove Old RootCA("GoProxy") error:
 asn1: syntax error: PrintableString contains invalid character

**Comment by smovie** [comment]
更新到r1354重新生成证书问题解决。
ps：证书有效期只有一年，是不是短了点？

**Comment by phuslu** [comment]
短一点好，现在浏览器的都不接受三年以上的证书了。

而且 goproxy 在运行过程中每一个星期都会检查一下加载的证书有没有过期，如果过期就立刻重签。

**Comment by phuslu** [comment]
啊，那我记错了。那应该只是一个提案了，Chrome 还没实现。
