### ISSUE TITLE
无法在edX.org上播放YouTube的视频

### ISSUE THREAD

**Issue by Limsig** [phuslu/goproxy#1611]
无法在edX.org上播放YouTube的视频，但在直接在YouTube上看没问题。
之前没有这个问题，前几天升级到r59后出现（印象中刚升级后也没出现，不太确定），我尝试再次更新服务端至r60，但该问题仍无法解决。相关截图如下，谢谢大家！

![image](https://cloud.githubusercontent.com/assets/22915681/24640173/8f4fda54-1927-11e7-802b-3036a77b398c.png)
![image](https://cloud.githubusercontent.com/assets/22915681/24640166/77815150-1927-11e7-9be7-0a34fc20924b.png)
![image](https://cloud.githubusercontent.com/assets/22915681/24640278/6a85582e-1928-11e7-8a07-f2288e9f93b5.png)

**Comment by phuslu** [comment]
我看下

**Comment by phuslu** [comment]
已经复现，确认是 bug， 正在修复。

**Comment by phuslu** [comment]
已经修复，请更新服务端到最新版 https://github.com/phuslu/goproxy/archive/server.gae.zip

**Comment by Limsig** [comment]
哇，大大太迅速啦！大大辛苦！
