### ISSUE TITLE
给各位介绍一款基于X86 CPU的软路由，非广告

### ISSUE THREAD

**Issue by Just2co** [phuslu/goproxy#1612]
https://detail.tmall.com/item.htm?id=543822156787&ali_refid=a3_430582_1006:1125075451:N:%E8%BD%AF%E8%B7%AF%E7%94%B1:ef5d913a6fe6631520c76aeca9b5438d&ali_trackid=1_ef5d913a6fe6631520c76aeca9b5438d&spm=a230r.1.14.8.Gy2XJK&sku_properties=5919063:33030646

天猫工厂店，最便宜的一款赛扬J1900 4核CPU，才680元，功耗10瓦特，比网件七八百元的R7000性能强很多倍，功耗还更低。可以刷openwrt等很多开源第三方固件。如果把goproxy部署在这上面，家里所有设备都可以免费翻墙。

**Comment by yaoguaishou** [comment]
某宝上面还有一款神器叫netgater智能网关什么的

**Comment by hcym** [comment]
x86的还是不如Arm
纠结

**Comment by blob2015** [comment]
听着感觉好像不错？谢谢lz。
