### ISSUE TITLE
goproxy 部署在gae和vps上的区别是什么？gae上为什么不能部署shadowsocks？

### ISSUE THREAD

**Issue by hyperdoit** [phuslu/goproxy#1613]
(如果您是遇到本软件使用问题而并不清楚具体原因的话，请尽量提供更多信息，如操作系统信息，日志截图，浏览器截图等。否则问题可能会被忽略或关闭)

**Comment by phuslu** [comment]
免费的 gae 只有 urlfetch 接口，没有 socket 接口
