### ISSUE TITLE
前置代理 的 真实作用是什么？求大家给小白科普

### ISSUE THREAD

**Issue by hyperdoit** [phuslu/goproxy#1616]
比如说，我用一只袜子前置代理tor，那么袜子的作用是哪一个：
1、让我在网络中找到tor的服务器并与tor直接建立连接
2、让每一次连接都经过袜子再转发给tor最后再转发回来

- Additional question 1：
tor只是在保护你不会受到追踪吗，（如果不需要隐藏身份的话）可以直接使用前置代理翻墙吗？

- Additional question 2：
NAT类型2和3既然都是非公网IP，那么有什么区别？

- Additional question 3：
如何保证与ISP（e.g. China Telecom)申请到公网IP？

**Comment by hyperdoit** [comment]
@jasonliul @jzp820927 @Kisesy

**Comment by yaoguaishou** [comment]
2 
1.可以
2
3.家庭用户不可能
