### ISSUE TITLE
R1357的 GoProxy Version 后面TS13后面有5个?

### ISSUE THREAD

**Issue by Asteroids89** [phuslu/goproxy#1618]
如下图,记得以前是没有的呢
![qq 20170405113647](https://cloud.githubusercontent.com/assets/19388220/24688756/a58ff97a-19f4-11e7-8eb8-e9088c4c6907.png)

**Comment by phuslu** [comment]
回滚了，为了解决偶发的启动以后长时间 goodip = 0 的问题。

**Comment by Asteroids89** [comment]
那能不能暂时隐藏掉,强迫症的人受不了呀......

**Comment by phuslu** [comment]
好的，晚上改下。

**Comment by Asteroids89** [comment]
谢谢社长

**Comment by 2378** [comment]
个人还是喜欢TLS1.3 停留在1349

**Comment by phuslu** [comment]
已经删除了启动信息的 ???? 问好。

**Comment by Asteroids89** [comment]
谢谢
