### ISSUE TITLE
共匪阅兵，我只能说共匪无耻到人渣不如的地步了！

### ISSUE THREAD

**Issue by yuan78** [phuslu/goproxy#162]
共匪搞的抗日庆祝阅兵：------只能是说无耻；或者是说不要脸：抗日，本为原来大陆的中华民国政府, 所为的爱国战争，与当初和现今的共匪政权，根本无关。而当年的共匪背后却做了些什么？------不仅不抗日，并全面挑起中日战争；勾结日本军；向日本军告密国民政府军动向；甚至联合日本军消灭国民政府军；在国民政府军抗战了14年，军粮尽弹绝覆灭的重创之际，却立刻发动了中华民族5千年来，最大规模的反革命政变（所谓：‘解放战争’），成功篡夺了大陆中国政权------‘先’共匪们，是一群地地道道的卖国贼们。而今的‘后’共匪们，居然又贪国民政府军功绩，为己功；跑出来所谓‘代表中国人民’，搞什么‘抗日战争’70周年庆祝阅兵了，简直是无耻！不要脸！！！

**Comment by ARwMq9b6** [comment]
@yuan78 楼主莫怪，有苦衷： https://github.com/phuslu/goproxy/issues/143#issuecomment-136235792
