### ISSUE TITLE
升级到1358版本，发现TLS版本成了1.2了

### ISSUE THREAD

**Issue by Just2co** [phuslu/goproxy#1625]
@phuslu 社长好，升级到今天下午最新版1358，发现浏览器跟goproxy之间的连接成了TLS1.2了，不过加密方式还是针对CPU优化的chacha20，前几天还是TLS1.3，请问这样改的用意是？TLS1.3不是更省电更流畅么？尽管是在本机上，应该也是有优化的吧?

**Comment by NAVrasZ** [comment]
#1615
