### ISSUE TITLE
分享安卓导入证书的一种方法

### ISSUE THREAD

**Issue by 523860169** [phuslu/goproxy#1628]
把goproxy生成的证书转化为系统内置证书模式，有以下便利：
1、不再必须设置锁屏才能导入证书
2、可能解决了高版本安卓大部分APP不采用系统代理设置的问题

具体步骤：
1、goproxy运行一次自动生成GoProxy.crt
2、获取该证书的哈希值，比如获得了890c6016
`openssl x509 -inform PEM -subject_hash_old -in GoProxy.crt | head -1`
3、将证书改名为刚刚获得的哈希值（890c6016），并加扩展名.0
Win: `type GoProxy.crt > 890c6016.0`
Linux & Mac: `cat GoProxy.crt > 890c6016.0`
4、添加证书信息
`openssl x509 -inform PEM -text -fingerprint -in GoProxy.crt -out /dev/null >> 890c6016.0`

> 以上第2-4步可以合并为以下这一命令：
> ```
>gethash=$(openssl x509 -inform PEM -subject_hash_old -in GoProxy.crt | head -1);cat GoProxy.crt> ${gethash}.0;openssl x509 -inform PEM -text -fingerprint -in GoProxy.crt -out /dev/null >> ${gethash}.0
>
> ```

5、将经过上面步骤处理后的证书（890c6016.0）复制到手机的/etc/security/cacerts/该文件内，重启手机即生效

检查是否生效方法：设置——安全——信任的凭据——系统，查找是否存在一证书名为“GoProxy”。

建议备份第一步生成的GoProxy.crt、GoProxy.key和第4步生成的证书（890c6016.0），这样以后手机刷机后只需执行第5步即可

**Comment by hcym** [comment]
谢谢

试试

**Comment by wpyok500** [comment]
mark

**Comment by panpeach** [comment]
楼主的头像好眼熟，是不是卡饭的ACVAA维护者？

**Comment by horizonl** [comment]
之前rr上直接把生成的证书Goproxy.crt丢到/etc/security/caerts文件夹下就在系统信任的凭据里了，不过感觉楼主的方式稳一些。

**Comment by SeaHOH** [comment]
不是所有人都能用这个方法，这里再讲一种：
1、将证书正常导入安卓
2、从 `/data/misc/keychain/cacerts-added` 提取格式为 `哈希值.0` 的证书
3、清除凭证
4、将第 2 步提取的证书放入 `/system/etc/security/cacerts/`

**Comment by wpyok500** [comment]
@SeaHOH  没cacerts-added这个文件夹/文件

**Comment by SeaHOH** [comment]
嗯，反正就在 `cacerts-added`，大家慢慢找哈。

**Comment by dlzdwxdt** [comment]
@wpyok500 @SeaHOH 太感谢了！

**Comment by hcym** [comment]
学习学习再学习

**Comment by horizonl** [comment]
如果在系统证书列表没看到goproxy，记得检查下.0文件的权限

**Comment by phuslu** [comment]
不知道能不能通过 twrp 来实现免 root 添加系统证书

**Comment by jyuan15** [comment]
有个问题，gop每次更新，之前版本的证书就不能用了，这个怎么办？或者说这样导入成系统证书就可以长期用？

**Comment by SeaHOH** [comment]
需要记得删除，确实麻烦，按修改时间排列会比较方便辨识。

**Comment by wpyok500** [comment]
@jyuan15  证书不用每次更新，使用脚本升级更新不会生成新的证书或者你可以备份证书，更新后使用备份的证书覆盖就可以了。

**Comment by SeaHOH** [comment]
是不一定会更新，有时社长改了格式需要更新，但是肯定会过期。

**Comment by roc1010kmt** [comment]
@SeaHOH 用你的方法不行，顯示不是私密鏈接。怎麼回事？

**Comment by SeaHOH** [comment]
@roc1010kmt 
哪儿显示的？
我觉得如果真的不行，可能是你做错了某个步骤，请删除后重新尝试。

**Comment by doracl** [comment]
请问不root 可以成功吗？

**Comment by 523860169** [comment]
@doracl 不root估计不行

**Comment by phuslu** [comment]
不 root 的话，可以尝试 twrp 这样方案。

**Comment by doracl** [comment]
@phuslu  老大，有入门教程没 👍

**Comment by lsnmx** [comment]
记录一下

**Comment by maxfun0** [comment]
安卓7.1 HTC 按照此方法无法导入证书，chrome还是不行，firefox无需系统证书也可以
