### ISSUE TITLE
这是什么错误

### ISSUE THREAD

**Issue by 523860169** [phuslu/goproxy#1630]
![screenshot_20170408-151947](https://cloud.githubusercontent.com/assets/6436073/24826720/e5535e36-1c6e-11e7-876f-3ea182303ad1.png)

**Comment by phuslu** [comment]
啊，可能是 dns 的问题，我看看。

**Comment by SeaHOH** [comment]
环境问题？
https://github.com/phuslu/goproxy/issues/1584#issuecomment-289260760

**Comment by 523860169** [comment]
我同样配置文件下，电脑正常，手机不正常。帮我看看是什么问题吧

> autoproxy.user.json
```
{
	"SiteFilters": {
		"Enabled": true,
		"Rules": {
			"live.github.com": "direct",
			"pastebin.com": "php",
			"whatismyipaddress.com": "php",
		},
	},
	"RegionFilters": {
		"Enabled": true,
		"DNSServers": [
			"223.5.5.5",
			"119.29.29.29",
		],
	},
}
```

> gae.user.json
```
{
	"AppIDs": [
		*************
	],
	"Password": "********",
	"HostMap" : {
		"google_hk": [
			"61.238.239.157","218.253.0.188","61.238.239.152","218.253.0.189","61.238.239.162","61.238.239.178","118.143.88.174","61.238.239.247"",
		]
	},
	"DNSServers": [
		"223.5.5.5",
		"119.29.29.29",
		"202.141.176.93",
		"208.67.220.220",
		"208.67.222.222",
		"8.8.8.8",
		"2001:4860:4860::8844",
		"2001:4860:4860::8888",
		"2001:470:20::2",
	],
}
```

> httpproxy.user.json
```
{
	"Default": {
		"RoundTripFilters": [
			"autoproxy",
			// "auth",
			// "vps",
			"gae",
			"php",
			"direct",
		],
	},
}
```
> php.user.json
```
{
	"Servers": [
		{
			"URL": "http://*****.tk/go.php",
			"Password": "******",
		}
	],
}
```
以上配置在全局代理的情况下效果应该是：
1、国外IP走代理，国内IP不走代理
2、whatismyipaddress.com走php
但是，手机上表现的却不是如此，主要有以下问题：
1、火狐、yandex浏览器可以正常访问网络，但是其他包括VIA浏览器、QQ微信内置浏览器都无法访问网络，不管是百度还是谷歌都打不开
2、即使火狐、yandex浏览器访问效果也不正常，显示的是国内IP，谷歌可以正常访问，说明RegionFilters的分流是正常的，但是whatismyipaddress.com显示的也是国内IP，而不是php的ip
3、APP方面，youtube完全走代理，但是google play下载app不走代理
另外，上面这些问题，都是我在仅配置gae.user.json的情况下时完全没有遇到的，不论是QQ微信等内置浏览器和VIA浏览器无法联网，或者Google play下载不走代理，都没有发生。
![ck o _ nf hmg 5a _7t](https://cloud.githubusercontent.com/assets/6436073/24827046/1b49f91c-1c76-11e7-8a5d-23f3512dd17d.png)
![screenshot_20170408-161115](https://cloud.githubusercontent.com/assets/6436073/24827049/23b8e2f2-1c76-11e7-8b67-ce6f37b16ba2.png)
![b_4254aw t5vrl4 o dfaw](https://cloud.githubusercontent.com/assets/6436073/24827058/4d6e9a06-1c76-11e7-8bf0-d5c11eab27e6.png)
![screenshot_20170408-161247](https://cloud.githubusercontent.com/assets/6436073/24827059/55a4eb1c-1c76-11e7-9e60-eb55d01c8877.png)

**Comment by wz7465** [comment]
https://www.dnsleaktest.com/
用这个查查是否dns泄露

**Comment by 523860169** [comment]
这个网站未代理的情况下，电脑可以打开，手机浏览器都打不开，显示超时
![k2dt qtb6710f z j48v0rj](https://cloud.githubusercontent.com/assets/6436073/24827425/e08004d8-1c7b-11e7-86d1-9a692d9b62b1.png)

**Comment by wz7465** [comment]
换一个试试 https://ipleak.net
手机和台式机dns的运作方式不太一样吧，基本上电脑上都不存在dns泄露的问题，换到手机app时，基本都有这个问题，像ss，proxydriod，drony，还有一大堆免费的vpn都没解决这个问题

**Comment by 523860169** [comment]
我上面更新了，你看一下吧

**Comment by wz7465** [comment]
isp里只要看到有China就说明dns泄露了，一个也没有才是安全的

**Comment by 523860169** [comment]
所以？

**Comment by wz7465** [comment]
说明你的链接是受到监控的，gfw想干扰的时候就可以干扰。当然app大部分情况下还是可以使用的，但是处于gfw的蓄意放水的情况下

**Comment by 523860169** [comment]
主楼的问题我已经解决了，现在是4楼的问题

**Comment by SeaHOH** [comment]
等社长吧，估计只改配置不行。

**Comment by 523860169** [comment]
嗯，感觉就是autoproxy有点问题，php完全没生效，连带的pac也出问题了

**Comment by THLIVSQAZ** [comment]
与goproxy的运行原理有关，自动代理是pac+autoproxy，但实际只有电脑上才兼容，安卓wifipac不兼容，用proxydroid是提示不支持的pac文件，termux的环境不完整，容易出现那个[::53]，php也无法运行

**Comment by THLIVSQAZ** [comment]
安卓上为了防止部分不走代理，最佳方案目前就是将代理切换为手动，youtube和play store都走goproxy

**Comment by 523860169** [comment]
嗯，我看到另外一个帖子里说更换gnuroot能运行php了，但是我从play下载gnuroot后，却不会用，而且还会FC，你能说一下怎么用吗？或者至少说下怎么进入shell界面

**Comment by THLIVSQAZ** [comment]
我帖子用的是gnuroot+gnuroot wheezy，装两个apk，然后就把goproxy_arm64拷过去，执行，arm系列都正常
现在用的是gnuroot debian ，一个apk，不过实测goproxy_arm运行不了，非法指令报错，可能与phuslu大大的编译器有关，goproxy_arm_cgo正常，你的是arm64，我没试过

**Comment by THLIVSQAZ** [comment]
shell界面，gnuroot+gnuroot wheezy选择第一个项部署wheezy环境，再选第二个项启动shell，别忘了打上root那个选项
gnuroot debian打开就进入shell了，首次自动部署
其实gnuroot是phuslu大大推荐的

**Comment by THLIVSQAZ** [comment]
![1491706087361](https://cloud.githubusercontent.com/assets/25531652/24834298/b832064a-1ca6-11e7-913f-f661a781c9f3.jpg)

**Comment by 523860169** [comment]
gnuroot debian下，goproxy可以放在sdcard下执行吗？

**Comment by THLIVSQAZ** [comment]
应该不行吧，貌似linux程序都不能在fat32上执行

**Comment by 523860169** [comment]
我发现既没有wget也没curl，所以想更换镜像源，你知道怎么换吗

**Comment by THLIVSQAZ** [comment]
挂一下vpn，蓝灯之类的，我这边不挂也正常，清源和阿里云好像没有arm的源

**Comment by 523860169** [comment]
好了，设置了全局代理，php正常了，国内外分流也正常了
但是偶尔YouTube会断流，而且感觉网速比之前慢了不少
