### ISSUE TITLE
Mac os Sierra 10.12.4下状态栏goproxy的set proxy切换功能失效

### ISSUE THREAD

**Issue by qq995910521** [phuslu/goproxy#1632]
在状态栏的goproxy下的set proxy选项，切换《 None 》，pac，127.0.0.1：8087无效了，但是手动到系统偏好设置-网络-代理处勾选http和https代理有效，虽然不影响使用，但是这个快捷调节系统全局代理的选项如果能修好就再好不过了，谢谢~

**Comment by phuslu** [comment]
啊啊啊，等我手头 mac 升级了就来看。

**Comment by riumiyama** [comment]
我通常用終端機模式 UI模式運行時容易崩潰

**Comment by phuslu** [comment]
@qq995910521 不能重现。
@riumiyama 开始尝试优化 UI 模式.

**Comment by phuslu** [comment]
r1393 尝试对 goproxy macos 的 UI 做了些稳定性优化。

**Comment by ydq** [comment]
好像中间好多个版本就开始不灵了，忘记从哪个版本开始的

**Comment by qq995910521** [comment]
@phuslu 更新了新的客户端，goproxy_macos_app-r1403.tar.bz2问题依旧，点击状态栏切换无效，进系统网络代理处勾选http和https有效。

**Comment by qq995910521** [comment]
@phuslu 更新了新的客户端，goproxy_macos_app-r1403.tar.bz2问题依旧，点击状态栏切换无效，进系统网络代理处勾选http和https有效。

**Comment by qq995910521** [comment]
@phuslu 更新了新的客户端，goproxy_macos_app-r1403.tar.bz2问题依旧，点击状态栏切换无效，进系统网络代理处勾选http和https有效。

**Comment by phuslu** [comment]
@qq995910521 不能重现。。。

**Comment by wzdnzd** [comment]
<img width="404" alt="687367555568508176" src="https://user-images.githubusercontent.com/8565764/28993654-5129a99e-79ee-11e7-8bb7-3108caeb6290.png">
社长，mac下的状态栏的菜单似乎真的切换不了，试了很多遍了
gop版本：1532
mac os版本：10.12.6
