### ISSUE TITLE
Json 编辑器

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1634]
![jsonedit png](https://cloud.githubusercontent.com/assets/2461165/24871494/54e7325c-1e4c-11e7-9ae2-492b47a2e0f5.png)

波兰人的小玩意

http://tomeko.net/software/JSONedit/index.php?lang=en

**Comment by jasonliul** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/24871913/e9b6bad2-1e4d-11e7-8fe2-c048df32d424.jpg)
![screenshot 2](https://cloud.githubusercontent.com/assets/2461165/24871917/ef129d16-1e4d-11e7-808d-6c036ab5c33b.jpg)

@phuslu 
揪出社长的笔误, 哈哈

**Comment by SeaHOH** [comment]
不是笔误，是社长特别做的末尾分隔符支持。

**Comment by wz7465** [comment]
@SeaHOH  厉害了，业务更精深啊

**Comment by jasonliul** [comment]
@SeaHOH 
等那些洁癖厮们出来嚎叫...
LOL

**Comment by blob2015** [comment]
@jasonliul 
嚎叫吧，强迫症，社长说，等俺有空 😀

**Comment by SeaHOH** [comment]
其实吧，我倒是倾向于用 toml。

**Comment by phuslu** [comment]
嗯嗯，我已经非常想迁移到 toml 了。
