### ISSUE TITLE
请教:关于r1370的信息

### ISSUE THREAD

**Issue by ylhfz** [phuslu/goproxy#1638]
![Uploading image.png…]()

运行后,出现这个信息,然后狗屁就无效了..

**Comment by ylhfz** [comment]
额,好像我不会贴图...

信息:

goroutine 14 [running]:
net.(*TCPConn).Close(0x0, 0xc042aebfa0, 0x0)
        <autogenerated>:1 +0x5
_/tmp/goproxy.170411.9473/goproxy/httpproxy/helpers.(*MultiDialer).dialMultiTLS.func2(0xc0420766c0, 0x4)
        /tmp/goproxy.170411.9473/goproxy/httpproxy/helpers/dialer2.go:250 +0x97
created by _/tmp/goproxy.170411.9473/goproxy/httpproxy/helpers.(*MultiDialer).dialMultiTLS
        /tmp/goproxy.170411.9473/goproxy/httpproxy/helpers/dialer2.go:245 +0x3f6

**Comment by ylhfz** [comment]
出现这个信息后,再进YouTube,显示:
未连接到互联网

**Comment by kirbyzhu** [comment]
![default](https://cloud.githubusercontent.com/assets/10296293/24903157/24254bb6-1edf-11e7-81bd-d1c1e55eee01.png)

1370有问题

**Comment by Asteroids89** [comment]
社长已经确认了，R1370有问题的。

**Comment by ylhfz** [comment]
哦,谢谢各位,我现在用r1369,挺好的

**Comment by 2378** [comment]
为什么总是有问题

我停留在 r51+r1349 都用得好好的

**Comment by blob2015** [comment]
@2378 
“总”，是一个很有杀伤力的词啊
这是一个婆娑世界，婆娑即堪忍

**Comment by 2378** [comment]
语文不精， 见谅

**Comment by phuslu** [comment]
正在修复，稍等。

**Comment by phuslu** [comment]
r1371 应该已经修复。
