### ISSUE TITLE
r1365正常 更新到r1370无法连接

### ISSUE THREAD

**Issue by chinagirl1** [phuslu/goproxy#1639]
win7  64bit   Google Chrome 版本 57.0.2987.133 (64-bit) r1365正常 更新到r1370无法连接   r1370显示
![1](https://cloud.githubusercontent.com/assets/16515138/24911548/e4b17986-1efd-11e7-8c76-cdf7d23bbc69.PNG)
![default](https://cloud.githubusercontent.com/assets/16515138/24911554/ece27f2e-1efd-11e7-9cf4-5e5361272877.PNG)

**Comment by phuslu** [comment]
r1372 已经修复。
