### ISSUE TITLE
GFW肯定是火力全开了

### ISSUE THREAD

**Issue by zhanxiage233** [phuslu/goproxy#164]
蓝灯很卡，xxnet勉强正常

**Comment by ARwMq9b6** [comment]
真是蛮拼的，补充：
+ 昨晚 Akamai 亚洲 IP 严重阵亡，不过今天白天又活了过来
+ 一部分 Shadowsocks 分享站被 24 小时监视，进行域名 DNS 污染及节点 IP 屏蔽，即使更换域名及节点 IP 也会很快被封。但是也有一些 Shadowsocks 分享站从未受干扰

**Comment by xyuanmu** [comment]
楼主蓝灯是什么版本的？目前用着2.02挺流畅的，就是带宽小看不了视频而已。

**Comment by zhanxiage233** [comment]
@xyuanmu 就是看不了视频还有什么用，以前直接1080p无压力的

**Comment by ouyangmalnd** [comment]
http://imgsrc.baidu.com/forum/w%3D580/sign=c327a96ab5de9c82a665f9875c8080d2/ba56e6014c086e064cea721804087bf40bd1cb76.jpg

**Comment by ouyangmalnd** [comment]
![ba56e6014c086e064cea721804087bf40bd1cb76](https://cloud.githubusercontent.com/assets/14039301/9655189/fe373216-5261-11e5-994e-beffe9b45696.png)
只和楼主说一句，从来不用XX看视频，一般都是用goagent，速度怎么样看图就知道。GFW就上次封的IP有点多，扫到的优质IP从来就没中断过，相信论坛里面也有人偶尔会分享

**Comment by wenliyang** [comment]
XX-Net 一样可以用来看视频，goagent 里如何优化设置，XX-Net 里也是类似的

**Comment by 1688pc** [comment]
蓝灯2.02可以看视频，老版本在我这里全部失效

**Comment by jerry011235** [comment]
@ouyangmalnd 希望把这些可用IP发送到[GoAgent比特信交流頻道](https://code.google.com/p/goagent/issues/detail?id=20843&q=比特信&colspec=ID%20Opened%20Reporter%20Modified%20Summary%20Stars)，话说现在怎么没人玩比特信了？这个应该是匿名的吧，原本就是打算分享IP用的，结果昙花一现了……

**Comment by jyuan15** [comment]
goa仍然给力
![2015-09-05_121652](https://cloud.githubusercontent.com/assets/12642186/9697697/7ed75284-53ca-11e5-9b84-588f970e15f8.jpg)

![2015-09-05_122409](https://cloud.githubusercontent.com/assets/12642186/9697695/3eaacea2-53ca-11e5-9f00-d7d60e307cf3.jpg)

**Comment by sundaqing1969** [comment]
韩国ip？楼上

**Comment by bygloam** [comment]
GoAgent 用好确实快 
![6j skrnq ilz ym r_ok1](https://cloud.githubusercontent.com/assets/13960978/9809736/82c0e608-589d-11e5-8793-f358c545c3bc.jpg)
