### ISSUE TITLE
win7 64bit Google Chrome版本57.0.2987.133（64位）r1365正常更新到r1370无法连接r1370显示

### ISSUE THREAD

**Issue by chinagirl1** [phuslu/goproxy#1640]
![2](https://cloud.githubusercontent.com/assets/16515138/24911985/5dd2f9ba-1eff-11e7-9f91-6eeb2108e725.PNG)
![2](https://cloud.githubusercontent.com/assets/16515138/24912035/7f49418a-1eff-11e7-8ef4-c5b60830c89a.PNG)

**Comment by phuslu** [comment]
正在看呢

**Comment by phuslu** [comment]
正在看呢

**Comment by phuslu** [comment]
r1371 已经修复。
