### ISSUE TITLE
appid能不能重复使用？

### ISSUE THREAD

**Issue by kirbyzhu** [phuslu/goproxy#1648]
以前部署的一些xx-net的appid 想更换了用在goproxy 发现提示无权限
是不是一经部署之后就只能一条道走到黑了？

**Comment by kirbyzhu** [comment]
好像新申请的appid也不能使用了 提示权限不够 也不弹出授权网页了 

是上次谷歌gae重启造成的么？

**Comment by 523860169** [comment]
不会吧，我都转成功了
没有弹授权网页的话，就自己复制授权网址打开咯

**Comment by kirbyzhu** [comment]
请输入您的appid, 多个appid请用|号隔开
注意：appid 请勿包含 ios/android/mobile 等字样，否则可能被某些网站识别成移动设备。
APPID:********************
12:33 PM Application: **************
12:33 PM Host: appengine.google.com
12:33 PM Rolling back the update.
Error 403: --- begin server output ---
You do not have permission to modify this app (app_id=u's~********').
--- end server output ---

**Comment by kirbyzhu** [comment]
刚刚么？ @523860169 再测试一下呢？ 没有授权网址好复制诶 直接就结束了

**Comment by panpeach** [comment]
APPID，不管是老部署的，还是新部署的，xx-net，goagent，goproxy 通用！

**Comment by kirbyzhu** [comment]
据说客户端是gop的 部署也是gop的比较好 况且现在都是r63了

**Comment by kirbyzhu** [comment]
ps： gop的服务端是不能在xxnet里面用的

**Comment by 523860169** [comment]
我前几天才重新部署过，你试试一个appid看能不能部署

**Comment by phuslu** [comment]
推荐重新部署，r63 修复了压缩问题，提升比较大。

**Comment by 523860169** [comment]
@phuslu 我刚刚重新上传，提示sdk不是最新
![default](https://cloud.githubusercontent.com/assets/6436073/25037400/7923b9e2-212b-11e7-93cc-7731f046a64c.png)

**Comment by kirbyzhu** [comment]
我试了还是一样的提示 没有权限

**Comment by kirbyzhu** [comment]
重新下载了个r63，解压后再部署appid 发现正常了 
第一次出现楼上的同样的提示 显示sdk不是最新的
第二次没有提示 全部部署完成

**Comment by phuslu** [comment]
@523860169 sdk 升级比较频繁，这个错误还好，暂时先忽略吧。
