### ISSUE TITLE
google被重定向到github 是dns的问题么？

### ISSUE THREAD

**Issue by kirbyzhu** [phuslu/goproxy#1650]
在小米路由器上安装的gop客户端

访问的时候有时候能正常访问 有时候就会被重定向

访问google 页面变成 https://github.com/_gh/

客户端的配置基本和我原来电脑的配置一样了 不知道问题是出在哪里

**Comment by THLIVSQAZ** [comment]
确实有出现过这个现象，很奇怪

**Comment by kirbyzhu** [comment]
不对 我开始以为是小米路由器的问题 换成本机的客户端一样出现这个问题了 所以应该是个普遍问题

访问谷歌学术和youtube出现

**Comment by phuslu** [comment]
ip 问题

**Comment by kirbyzhu** [comment]
有坏id？这玩意怎么识别剔除啊？

**Comment by jasonliul** [comment]
@kirbyzhu 
HK字段混入中国谷歌ip, 就会这样.

203.208.32.0-203.208.63.255
剔除这些字段ip

**Comment by kirbyzhu** [comment]
查了一遍 没有这个网段的

保险起见 我把203.207段的都删掉了 再试试看

**Comment by kirbyzhu** [comment]
好像还是不行

**Comment by kirbyzhu** [comment]
这一堆ip已经用了好久了 一直没出现这个问题 刚刚冒出来 真是奇怪

**Comment by jasonliul** [comment]
github网站带有google analytics, 之前Goagent尾声那段时间, 也能被识别为good ip使用, 现在不能.

**Comment by kirbyzhu** [comment]
我把所有的ip再扫mff扫一遍吧 看来太多了也容易出问题

**Comment by kirbyzhu** [comment]
还是不行 剔除掉所有203.208打头的 
剩下的全部mff扫了一遍 把其他设置都修正了 还是不行

**Comment by CHN008** [comment]
**我的也出现过这种问题,有时还会返回代理错误.有好多种**
**1.**

Invalid URL

The requested URL "[no URL]", is invalid.
Reference #9.680a4cdb.1492183698.3657802


**2.**

{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1340 (go/devel +92745bd Tue Mar 21 06:10:50 2017 +0000 windows/amd64)",
    "filter": "*gae.Filter",
    "error": "EOF"
}


**3.**

<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>Ref A: B7E7251EB7034B678F6CA2F1664073AB Ref B: HKBSCHEDGE0108 Ref C: Fri Apr 14 08:30:23 2017 PST


**这几种错误经常出现,有时等上几分钟再重新打开就又能正常访问了.**

**Comment by kirbyzhu** [comment]
只留下10个不到的可用 ip 还是出问题 
我觉得这次不是ip的问题 坐等其他人报错

**Comment by Kisesy** [comment]
关机重启吧，保证管用

**Comment by kirbyzhu** [comment]
@Kisesy 实测不管用

**Comment by wpyok500** [comment]
浏览器被劫持了，修复下浏览器。

**Comment by kirbyzhu** [comment]
试试看 chrome好像安全性挺好的啊

**Comment by kirbyzhu** [comment]
@wpyok500 果然，谢谢了！ 用edge访问没问题 
清除chrome浏览器数据后问题解决。

**Comment by Kisesy** [comment]
https://github.com/phuslu/goproxy/search?q=github.com%2F_gh%2F&type=Issues&utf8=%E2%9C%93

你要是提前搜一下，早解决了
