### ISSUE TITLE
小米路由器R1D安装goproxy客户端步骤及存在问题（无法贴图）

### ISSUE THREAD

**Issue by kirbyzhu** [phuslu/goproxy#1651]
1 小米官网root和ssh 参考 http://bbs.xiaomi.cn/t-9921071 注意如果小米路由器固件一开始是稳定版 记得先刷成开发版

2 用putty和winscp做客户端登录路由器 winscp很好用。

3 uname -a 看看路由器的版本 r1d应该是armv71 下载goproxy_linux_arm-r1373.tar.bz2 可以先在电脑上解压了 配置好gae.user.json, httpproxy.user.json 等，然后通过winscp上传到 /userdisk/goproxy 目录下
记得把本机上能正常运行goproxy客户端的 cache 文件夹和里面的 ecc文件夹 一起拷贝进去，解决证书问题

4 putty登录 输入root密码 进入goproxy文件夹 chmod +x goproxy

5 ./goproxy 运行

  ash ./goproxy.sh start 运行会有错误提示 但是后台运行正常

  监听端口改成0.0.0.0:8087 然后网内客户端就可以访问登录

证书问题无法解决，局域网内客户端也存在证书问题  我用goproxy管理员方式运行后导入才行 所以感觉这种fq方式意义不大

**Comment by phuslu** [comment]
请把 ash  ./goproxy.sh start
的错误信息复制贴上来。

**Comment by kirbyzhu** [comment]
贴图贴不上来真是很烦恼

Starting goproxy(19155): ps: invalid option -- a
BusyBox v1.19.4 (2017-02-21 15:54:45 CST) multi-call binary.

Usage: ps

Show list of processes

        w       Wide output

Failed

**Comment by kirbyzhu** [comment]
ps查看 goproxy还是运行的 虽然有failed的字样

刚才测试了一下

**Comment by SeaHOH** [comment]
无法贴图可能是用的非 goproxy.gae 服务端。
