### ISSUE TITLE
macOS Sierra Safari如何切换搜索引擎到google.com.tw

### ISSUE THREAD

**Issue by ruby186** [phuslu/goproxy#1657]
咳咳咳……首先声明：

【这个不是一个goproxy issue，与作者无关】

只是实在找不到求助的地方了，google了很多帖子都无办法，才来这里求助。

safari，默认不开代理和VPN的情况下，如果激活mac时选的国家和地区是中国，则默认搜索引擎是http://www.google.com.hk 。而我想变更到https://www.google.com.tw ，无论我怎么折腾都无法起到作用，比如修改语言和区域到台湾？还有记得以前10.8有地方可以修改plist的，现在没办法了吗？

如果ip可用的情况下，hosts可以直接搜索的，不需要翻墙，翻墙只需要特定场景采用。有大神能提供思路不？还是这个配置被打包到Safari二进制程序里了，无法改？

碰碰运气提问求助，如果实在没办法我就关闭issue了，或者管理也可以直接关闭，抱歉哈！

**Comment by riumiyama** [comment]
先訪問一下https://www.google.com/ncr 就不會跳轉了

**Comment by ruby186** [comment]
@riumiyama safari浏览器默认的搜索是使用非安全的http google hk，ncr无法定制搜索的baseurl啊，如果是chrome我还知道怎么改。。

**Comment by riumiyama** [comment]
不需要改什麼啊  直接先訪問一下 就不會跳轉了   其實你用什麼語言激活Mac Safari搜索引擎都是一樣的

**Comment by riumiyama** [comment]
![screen shot 2017-04-16 at 1 02 43 am](https://cloud.githubusercontent.com/assets/18358396/25065314/6b7c97f8-2240-11e7-9b66-bcca9eda1683.png)

**Comment by panpeach** [comment]
标题要求切换到google.com.hk，而内容却要求变更到google.com.tw
看不懂什么意思

**Comment by ruby186** [comment]
@riumiyama，搜索引擎默认的是google hk(http)，你必须手工切一次才能到安全搜索。而且siri默认跟随你选择的搜索引擎。。

**Comment by ruby186** [comment]
![chrome](https://cloud.githubusercontent.com/assets/618701/25067907/1b974e1a-2284-11e7-8cc1-7f57f1771a64.png)

如图，chrome是可以管理搜索引擎的；我记得以前低版本safari也可以修改plist，现在不可以了吗，除了插件没有其他办法？
