### ISSUE TITLE
挺好用的，就是有时候不稳定

### ISSUE THREAD

**Issue by xjock** [phuslu/goproxy#1663]
good_addrs大于0，但是还是不能连接

**Comment by blob2015** [comment]
上次更改筛选法后，俺的good ip有小幅提升，但是连接yt，进入主页的速度好像有些下降的感觉，但播放还是差不多。
其他的，大致没啥太大变化的感觉。
---------------
纯主观，就一说，也可能是干扰加强了，俺就一说啊。

**Comment by phuslu** [comment]
多放些 ip 试试。
