### ISSUE TITLE
r1381, 似乎改良不小

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1665]
bad-ip增长明显比之前慢.
俺之前也遇见突然僵死, 基本都是bad ip 个数接近good ip个数. 现在这样稳定很多.

测试
http://openspeedtest.com/

这个html5网站之前使用, 几乎每次都得重启GP, 现在是不需要

**Comment by MeABc** [comment]
> bad-ip增长明显比之前慢.

有同感。有可能是这个 [305c5dd](https://github.com/phuslu/goproxy/commit/5518a37c890f10b2e815f9512b3caa880c9aef2b) 的改变

**Comment by MeABc** [comment]
又认真看了一遍，发现 "Level":9 和 "Level":8 结果是一样的。 :trollface:

**Comment by phuslu** [comment]
哈哈，被看穿了。这就是所谓的以力取胜，博君一笑耳。

**Comment by SeaHOH** [comment]
的确没啥反应卡 IP 的了。

**Comment by MeABc** [comment]
哈哈，社长你这“害人不浅”啊！

**Comment by phuslu** [comment]
好说好说，感谢鼓励和反馈😉

**Comment by fredericky123** [comment]
该版本是否能在浏览器开启tls1.3呢

**Comment by phuslu** [comment]
已经恢复了

**Comment by xc1988** [comment]
自动更新还是1380呢。。

**Comment by fredericky123** [comment]
关于自动更新有个问题，由于使用的是gae.user，每次自动更新后gae.user文件是没有变化的，这样的话gae里的改变不是没有更新到gae.user吗？比如这次level的调整

**Comment by jasonliul** [comment]
@phuslu 
多谢社长给猪加力, 猪强鞭壮.
:)

**Comment by kirbyzhu** [comment]
@fredericky123 一般在user.json里面不会写level的配置的

**Comment by fredericky123** [comment]
从gae.json复制而来，里面不是有level配置吗，默认没改，可是最新版的gae.json相较于之前版本的gae.json在level配置上有改动

**Comment by kirbyzhu** [comment]
gae.user.json 没有必要完全复制 目录下面有 .example的 用这个模版就行 需要改什么再增加什么

**Comment by fredericky123** [comment]
有道理哈 这样就解决了上述提到的问题！感谢！

**Comment by houhuliang** [comment]
1381在哪里下载

**Comment by lsnmx** [comment]
小弟我找出当初跑了1 个月哪1W IP出来，精选了900多IP到GP上，速度很牛逼的说，再套上香港的SS

**Comment by Asteroids89** [comment]
![Uploading QQ截图20170427180332.png…]()
