### ISSUE TITLE
PHP模式可以有多个服务器地址么？

### ISSUE THREAD

**Issue by cc1024** [phuslu/goproxy#1667]
把Goproxy部署到Heroku上，可以修改本地php.json文件来使用多个服务器地址么？
格式是什么样的？
是类似GAE用竖线“|”来分隔吗？
"URL": "https://11111.herokuapp.com/index.do|https://22222.herokuapp.com/index.do",

请高手指点。谢谢！

**Comment by Kisesy** [comment]
可以， https://github.com/phuslu/goproxy/blob/wiki/ConfigIntroduce.md#phpjson-配置文件
改的时候，照着上面改，注意前后逗号

**Comment by cc1024** [comment]
刚搜了一下，是下面这样的格式。问题关闭，格式写在下面留给需要的人吧。

```
"Servers": [
		{
			"URL": "https://11111.herokuapp.com/index.do",
			"Password": "123456",
			"SSLVerify": true,
			"Host": "",
		}
	],
	"Servers": [
		{
			"URL": "https://22222.herokuapp.com/index.do",
			"Password": "123456",
			"SSLVerify": true,
			"Host": "",
		}
	],
```

**Comment by cc1024** [comment]
谢谢@Kisesy

**Comment by ruby186** [comment]
提个建议：http可以继续用gae；heroku用websocket做socks5可能更好：）

**Comment by cc1024** [comment]
谢谢Ruby！
GAE的IP总是被封，找IP太麻烦。我只是在公司用Goproxy，heroku的够用就可以了。家里用SS。

**Comment by kirbyzhu** [comment]
马克一下
