### ISSUE TITLE
使用gae在mychrome里面没办法在线更新

### ISSUE THREAD

**Issue by kirbyzhu** [phuslu/goproxy#1671]
下载个几M然后就停掉了，换成php才行。不知道是不是autorange的问题。
当初听了lu大的话才换了mychrome的，确实好用但是更新反而出新问题了

**Comment by phuslu** [comment]
嗯，是的。我的 mychrome 一般用 sina 源更新的。

**Comment by hcym** [comment]
chrome更新没墙
同步是墙的死死的

**Comment by ruby186** [comment]
chrome可以用offline installer更新，直接下载完整包，会好点
