### ISSUE TITLE
php代理问题

### ISSUE THREAD

**Issue by kirbyzhu** [phuslu/goproxy#1672]
在heroku部署了php，然后在tk上申请了个域名 指向herokuapp这个服务网址 可以正常访问对应的app
想用tk的dns来加速，所以在php.json设置中使用了tk的网址 dns 那边写的是 80.80.80.80
但是启动后出错如下，请牛人们看看是啥问题
![image](https://cloud.githubusercontent.com/assets/10296293/25224407/e11185ba-25f0-11e7-95dc-ca212641163b.png)

好像是证书问题 在客户端提示  "error": "x509: certificate is valid for *.herokuapp.com, herokuapp.com, not *****.**.**"

**Comment by kirbyzhu** [comment]
好像是证书问题

**Comment by houhuliang** [comment]
应该是你域名证书的原因，试试http

**Comment by kirbyzhu** [comment]
http没戏 怎么才能导入目前网站的证书呢？
