### ISSUE TITLE
google搜索 异常流量

### ISSUE THREAD

**Issue by hg123** [phuslu/goproxy#1676]
今天我将一台电脑XP系统换成win8.1， 然后就发现使用google搜索时频繁的提示异常流量 ，而另一台使用XP的电脑却没有出现这种提示 。
win8.1的这台电脑使用XXnet也没有出现这种提示，实在弄不懂怎么回事，请高手帮忙分析一下。

**Comment by SeaHOH** [comment]
信息不足，有截图嘛。

**Comment by hg123** [comment]
刚才观察了一下每次用google搜索时日志就会出现如截图所示信息
![123](https://cloud.githubusercontent.com/assets/736009/25314308/0949f6fe-2874-11e7-8f97-219425f0443d.PNG)

**Comment by hg123** [comment]
不知道为什么会转到google.cn

**Comment by SeaHOH** [comment]
尝试访问一次 https://www.google.com/ncr#hl=zh_CN

**Comment by hg123** [comment]
问题依旧

**Comment by SeaHOH** [comment]
google_hk 的配置是 IP 还是域名？尝试换一批 IP。

**Comment by hg123** [comment]
换过一批IP了 但没用 相同的IP在另一台XP电脑上却没这种问题 
浏览器的缓存cookies都清除过了

**Comment by SeaHOH** [comment]
你是不是直接用地址栏搜索的？你的浏览器是什么？感觉不像是 Chrome。

**Comment by hg123** [comment]
是用的chrome。 用地址栏搜索过，打开google网页也搜索过。有时候重启gp第一次搜索时不会出现异常流量提示，但第二次搜索时就会出现，有时候点人机验证通过后可以继续搜索，但再后来就会图片验证而且验证的图片会不停出现，根本无法通过验证。

**Comment by SeaHOH** [comment]
没道理这么频繁，可能你运气不好。
建议换 gws 类型的 IP，或者配置 `.google.com` 到 `ForceGAE`。

跳 google.cn 应该是地址栏搜索的问题。

**Comment by hg123** [comment]
谢谢了，我再找找试试看

**Comment by hg123** [comment]
原来是hosts里面的IP有问题 删除后恢复正常
