### ISSUE TITLE
php 访问freenom出现411错误

### ISSUE THREAD

**Issue by kirbyzhu** [phuslu/goproxy#1677]
登录之后界面始终是  411 Length Required

**Comment by phuslu** [comment]
啊，我看下

**Comment by Kisesy** [comment]
@phuslu 现在的php也不能前置gae了... 这个有空的话也应该修一下

**Comment by phuslu** [comment]
啊，我尽快修复

**Comment by phuslu** [comment]
@Kisesy 奇怪，我测了下php 的 gae 前置   ，是好的。
php.user.json 如下。
```
	"Transport": {
		"Proxy": {
			"Enabled": true,
			"URL": "http://127.0.0.1:8087",
		},
	}
```
你是说 gae + php 前置吗？

**Comment by Kisesy** [comment]
@phuslu 是这个设置
我这里，会出现这个，用的是 heroku
![image](https://cloud.githubusercontent.com/assets/5843694/25387108/3fff2faa-29fc-11e7-9700-c030d0d1014b.png)
我重新部署一下试试看吧，最新一次更新我并没有部署..

**Comment by Kisesy** [comment]
@phuslu 最新的可以了，唉这个还不一样.........
