### ISSUE TITLE
出现大量unexpected EOF红字黄字

### ISSUE THREAD

**Issue by xiaomage2000** [phuslu/goproxy#1679]
使用中出现大量unexpected EOF红字黄字，YOUTUBE视频加载缓慢。谷歌IP是刚刚扫出来的。昨天就出现类似问题，ytimg.com无法正常打开。请社长和各位大神看看。感激不尽！
本地的客户端和gae服务端都是最新版本。
`I0424 13:40:34.605939    5048 dialer2.go:96] MULTIDIALER DialTLS2("tcp", "***.appspot.com:443") with good_addrs=172, bad_addrs=21
W0424 13:40:34.784949    5048 gae.go:524] 127.0.0.1:52255 "GAE FETCH GET https:/
/r16---sn-q4f7snls.googlevideo.com/videoplayback?id=357b9b21ece00f31&itag=135&so
urce=yt_otf&requiressl=yes&pl=28&ei=i4_9WN69L8riuAKu4oeQDg&ratebypass=yes&mime=v
ideo%2Fmp4&otfp=1&otf=1&lmt=1482103620714255&key=cms1&signature=81A9D62592E00583
2A4490DA1FF0CB20B0536822.7CA4B3B887D8C62C7A656176E61C4AC757ACCBF1&upn=MIPywRB3hn
M&cpn=ElN1pmVaczaVEJmL&mpd_version=5&pacing=0&ip=107.178.194.39&ipbits=0&expire=
1493033964&sparams=ei,expire,id,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,otf
,otfp,pl,ratebypass,requiressl,source&alr=yes&keepalive=yes&c=WEB&cver=1.2017041
8&cm2rm=sn-vgqe7d7s&redirect_counter=2&cms_redirect=yes&ipbypass=yes&mm=34&mn=sn
-q4f7snls&ms=ltu&mt=1493012295&mv=m&sq=22&dur=5.000&rn=49&rbuf=46696 HTTP/1.1" e
rror: *errors.errorString(unexpected EOF)
E0424 13:40:34.784949    5048 handler.go:96] 127.0.0.1:52255 Filter RoundTrip *g
ae.Filter error: unexpected EOF
I0424 13:40:34.911956    5048 gae.go:591] 127.0.0.1:52271 "GAE FETCH GET https:/
/s.youtube.com/api/stats/qoe?event=streamingstats&fmt=135&afmt=140&cpn=ElN1pmVac
zaVEJmL&ei=i4_9WN69L8riuAKu4oeQDg&el=detailpage&docid=NXubIezgDzE&ns=yt&fexp=940
5982%2C9419451%2C9422596%2C9431012%2C9434046%2C9434289%2C9435036%2C9443436%2C944
4898%2C9446054%2C9446364%2C9449243%2C9452320%2C9453897%2C9456640%2C9457141%2C945
7443%2C9458576%2C9462822%2C9463594%2C9463965%2C9464882%2C9465533%2C9465813%2C946
5961%2C9466204%2C9466210%2C9466712%2C9466778%2C9466778%2C9466793%2C9466795%2C946
7031%2C9467710%2C9468052%2C9468325%2C9468385%2C9468844%2C9469224%2C9471112%2C947
1856%2C9472097&cl=153650577&seq=8&c=WEB&cver=1.20170418&cplayer=UNIPLAYER&cbr=Ch
rome&cbrver=57.0.2987.133&cos=Windows&cosver=6.1&error=76.675:net.connect:55.177
:rt.0.24;lb.0;pt.2.17;pb.721875;stall.0.00;elbowTime.NaN;elbowBytes.0;shost.r16-
--sn-q4f7snls.googlevideo.com;rn.46;itag.135;ml.1;action.retry&bwm=76.675:787645
:5.481,80.003:165451:1.288&bwe=76.675:436907,80.003:458031&bh=76.675:44.927,80.0
03:41.698&bat=76.675:1:1,80.003:1:1&cmt=76.675:55.177,80.003:58.505 HTTP/1.1" 20
4
I0424 13:40:37.202087    5048 gae.go:591] 127.0.0.1:52255 "GAE FETCH GET https:/
/r16---sn-q4f7snls.googlevideo.com/videoplayback?id=357b9b21ece00f31&itag=135&so
urce=yt_otf&requiressl=yes&pl=28&ei=i4_9WN69L8riuAKu4oeQDg&ratebypass=yes&mime=v
ideo%2Fmp4&otfp=1&otf=1&lmt=1482103620714255&key=cms1&signature=81A9D62592E00583
2A4490DA1FF0CB20B0536822.7CA4B3B887D8C62C7A656176E61C4AC757ACCBF1&upn=MIPywRB3hn
M&cpn=ElN1pmVaczaVEJmL&mpd_version=5&pacing=0&ip=107.178.194.39&ipbits=0&expire=
1493033964&sparams=ei,expire,id,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,otf
,otfp,pl,ratebypass,requiressl,source&alr=yes&keepalive=yes&c=WEB&cver=1.2017041
8&cm2rm=sn-vgqe7d7s&redirect_counter=2&cms_redirect=yes&ipbypass=yes&mm=34&mn=sn
-q4f7snls&ms=ltu&mt=1493012295&mv=m&sq=22&dur=5.000&rn=50&playerretry=1&rbuf=464
27 HTTP/1.1" 200 240697
W0424 13:40:37.506105    5048 gae.go:524] 127.0.0.1:52255 "GAE FETCH GET https:/
/r16---sn-q4f7snls.googlevideo.com/videoplayback?id=357b9b21ece00f31&itag=135&so
urce=yt_otf&requiressl=yes&pl=28&ei=i4_9WN69L8riuAKu4oeQDg&ratebypass=yes&mime=v
ideo%2Fmp4&otfp=1&otf=1&lmt=1482103620714255&key=cms1&signature=81A9D62592E00583
2A4490DA1FF0CB20B0536822.7CA4B3B887D8C62C7A656176E61C4AC757ACCBF1&upn=MIPywRB3hn
M&cpn=ElN1pmVaczaVEJmL&mpd_version=5&pacing=0&ip=107.178.194.39&ipbits=0&expire=
1493033964&sparams=ei,expire,id,ip,ipbits,ipbypass,itag,lmt,mime,mm,mn,ms,mv,otf
,otfp,pl,ratebypass,requiressl,source&alr=yes&keepalive=yes&c=WEB&cver=1.2017041
8&cm2rm=sn-vgqe7d7s&redirect_counter=2&cms_redirect=yes&ipbypass=yes&mm=34&mn=sn
-q4f7snls&ms=ltu&mt=1493012295&mv=m&sq=23&dur=5.000&rn=51&rbuf=48946 HTTP/1.1" e
rror: *errors.errorString(unexpected EOF)
E0424 13:40:37.508105    5048 handler.go:96] 127.0.0.1:52255 Filter RoundTrip *g
ae.Filter error: unexpected EOF`

**Comment by qwerttaa** [comment]
最好说明一下c/s端的版本，我这边都是最新版的，没有这个问题

**Comment by vcheng** [comment]
最近有大事件，所以封锁、干扰很严重。

**Comment by THLIVSQAZ** [comment]
确实目前污染很严重

**Comment by wz7465** [comment]
还好了，没断网就不错了，时不时的还放点水

**Comment by qwerttaa** [comment]
@vcheng 你是说郭七星爆料的事儿吧

**Comment by vcheng** [comment]
qwerttaa   是的啊

**Comment by xiaomage2000** [comment]
现在终于查到原因了。APPID创建时按照新手提示，做了一个hello world的程序，导致无法正常使用。删除APPID后正常。

**Comment by qrpengx** [comment]
@xiaomage2000 请问怎么删除新手时创建的hello world

**Comment by xiaomage2000** [comment]
@qrpengx
我比较简单粗暴，直接把那个appid删了，重建。
