### ISSUE TITLE
捕获到一个疑似bug

### ISSUE THREAD

**Issue by THLIVSQAZ** [phuslu/goproxy#1680]
访问php代理8088正常运行，不久后gae会自动开始ip筛选，并没有访问8087端口，按理说是被动探测，应该不启动筛选才对，最主要的是ip筛选good ip为0，切换8087端口自然也无法访问
两次试验均复现该问题
![1493038990384](https://cloud.githubusercontent.com/assets/25531652/25339580/be3a2038-28f2-11e7-9bb9-0ad6b0280c61.jpg)
![screenshot_20170424-205843_li](https://cloud.githubusercontent.com/assets/25531652/25339593/c9027d4e-28f2-11e7-8f4e-7587a1522c72.jpg)
![screenshot_20170424-205856](https://cloud.githubusercontent.com/assets/25531652/25339601/ce4727dc-28f2-11e7-8a31-f5dcbc632271.png)

**Comment by Kisesy** [comment]
不是，gae和php是可以共存的，你用php是不会影响gae运行的，gae在跑IP是因为开启了DeadProbe
如果你只想用php而彻底不开gae，那么需要在httpproxy.json里关掉，就是关掉那个默认

**Comment by THLIVSQAZ** [comment]
@Kisesy 多谢指点。good ip 0 问题估计要等社长解决了
