### ISSUE TITLE
服务端只能部署在GAE 上吗？

### ISSUE THREAD

**Issue by ziming2018** [phuslu/goproxy#1689]
digitalocean不行吗？

**Comment by phuslu** [comment]
digitalocean 是 vps, 有完整的转发支持。没必要部署 GAE 这样的“残废”客户端。

digitalocean 的话，推荐部署 SSR 或 goproxy-vps，然后开启 TCP BBR 就行了啊。没必要和 GAE 磕上啊。

**Comment by jasonliul** [comment]
VPS 方案
突厥 史翠珊 Streisand
https://github.com/jlund/streisand

自动化安装脚本, 同时生成客户端配置文件.
L2TP/IPsec, OpenConnect, OpenSSH, OpenVPN, Shadowsocks, sslh, Stunnel, a Tor bridge, and WireGuard.

**Comment by phuslu** [comment]
啊，我也贴一个我比较喜欢的 https://github.com/hwdsl2/docker-ipsec-vpn-server

用 docker 部署的 ipsec VPN(psk 模式），挺方便的。

**Comment by jasonliul** [comment]
其实Stunnel也是很好的, 不过很少有人提供免费节点.
:(

**Comment by mixool** [comment]
我也贴一个我喜欢的docker[mixool/gost](https://hub.docker.com/r/mixool/gost/)

**Comment by ziming2018** [comment]
@jasonliul @phuslu @mixool 我怎么越来越糊涂？goproxy需要和这些搭配使用吗？

**Comment by linhua55** [comment]
@ziming2018 
如果你要 免费的，那么只能部署在 GAE上，部署的是 goproxy-gae 版

如果你 愿意 花费 用 digitalocean ， 那么 可以用 goproxy-vps， 也可以用其他工具（不用goproxy ，如SSR）

是 digitalocean 可以和 这些搭配使用

**Comment by Alvin9999** [comment]
@phuslu  关于锐速和BBR哪个更好的说法，社长你怎么看

**Comment by ziming2018** [comment]
@mixool 你的回答对我很有帮助
