### ISSUE TITLE
windows 64位系统出现的问题

### ISSUE THREAD

**Issue by tianlichunhong** [phuslu/goproxy#17]
在chrome上出现下面文字：
dial tcp 86.127.118.151:443: ConnectEx tcp: i/o timeout
是设置了GAE优先，没有设置php。增加了GVS的IP。看看是怎么回事。

**Comment by xyuanmu** [comment]
把gvs ip放最前面，或者干脆替换掉原网址

**Comment by tianlichunhong** [comment]
原来就是将GVS的IP放前面的，后来去掉原来的网址，也是一样的。
