### ISSUE TITLE
无法上传文件到google drive，dropbox？

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#1703]
gp之前倒也一直都没试，今天试了，好像都不行，要改一下设置？还是暂时还是不行？
试了全局，其他没有试。

**Comment by 523860169** [comment]
我也发现了，不能上传到youtube，之前某个版本时还偶尔能上传，现在好像完全上传不了了

**Comment by MeABc** [comment]
我只试 google drive 上传，上传不了。

**Comment by SeaHOH** [comment]
直连可以上传，怀疑 fakeoptions 没处理好。 @phuslu 社长看一下。

**Comment by blob2015** [comment]
最近涉及到上传，好像都有问题，以前还能用来同步xmarks等的数据，现在一律报错
@phuslu

**Comment by phuslu** [comment]
奇怪，刚试了下 google drive 上传，是可以的。

有失败的日志吗？

**Comment by MeABc** [comment]
又试了一下，Firefox 和 Chorme 上传都不成功。

Firefox 日志

![1](https://cloud.githubusercontent.com/assets/18194126/26031370/20c52152-38a3-11e7-8a5c-2e6a4c9c121c.png)

--

Chrome 日志

![2](https://cloud.githubusercontent.com/assets/18194126/26031373/31fd2aa0-38a3-11e7-9d40-a1d4a9264d6e.png)

--

**Comment by phuslu** [comment]
试下 r1406 https://github.com/phuslu/goproxy/commit/bcdfa509dd1c433457b0e3b2f1a5b4cbe76a1386 还有吗？

**Comment by MeABc** [comment]
好的。我试下。

**Comment by MeABc** [comment]
r1406 两个浏览器都试了，可以了。

**Comment by phuslu** [comment]
嗯，看起来可是 chrome tls1.3 实现有点问题，tls cipher text 超过标准最大大小

**Comment by MeABc** [comment]
现在这样改更好了，下次只改配置。

**Comment by MeABc** [comment]
现在这样改更好了，下次只改配置。

**Comment by MeABc** [comment]
我是只直 clone 下编译的。

编译步骤 https://github.com/phuslu/goproxy/blob/wiki/HowToBuild.md 这里少了加这个 [fe9860d](https://github.com/phuslu/goproxy/commit/c457658d9cfa3e7cca9abf95e8caef77b77214d0) 

你有时间改下

**Comment by blob2015** [comment]
@phuslu 
社长，刚才测试了一下1406，google drive与drop，都可以了。感谢。
@MeABc 
也感谢ABC兄。

**Comment by kirbyzhu** [comment]
dropbox的客户端手动设置http代理 用8087连接不上 网页上传没问题

**Comment by blob2015** [comment]
@kirbyzhu @phuslu @MeABc 
只能再次请ABC兄与社长看看了 😀

**Comment by MeABc** [comment]
如 Dropbox 和手机上的一些 app 等这些，不能通过 gae（/Google App Engine/ 
）代理来使用，那是因为 gae 不支持  http connect 请求。


在 2017/5/25 5:39, Blob 写道:

**Comment by MeABc** [comment]
所以，这类客户端选择 http/https 代理时，要选用支持 http Connect 的 
http/https 代理才行。


在 2017/5/25 5:39, Blob 写道:

**Comment by kirbyzhu** [comment]
原来如此 用ss就可以 我说呢
