### ISSUE TITLE
创建appid时，是选择python还是go语言？

### ISSUE THREAD

**Issue by one360** [phuslu/goproxy#1704]
地区选择亚洲速度会更好吗？

**Comment by caofengzi** [comment]
好像是都選擇us。

**Comment by kirbyzhu** [comment]
前面有解释过 选啥最后都是us的出口

**Comment by one360** [comment]
@kirbyzhu 选择语言有差异吗？选择go语言会更好吗？

**Comment by 523860169** [comment]
现在还能创建appid？不是都自动跳转到gcs了吗

**Comment by dfbgp** [comment]
@523860169 可以的吧，上个月我教一个同事用GOPROXY就是新建的

**Comment by kirbyzhu** [comment]
应该不会 因为最后用啥语言是看你上传部署的环境

**Comment by kirbyzhu** [comment]
appid没问题的吧 不过我前面留了十来个备用

**Comment by szh7379** [comment]
如果不能创建了，离关闭也不远了。

**Comment by yqy6611** [comment]
亲自尝试过，appid还是可以创建的，一个gmail最多创建12个。

**Comment by yDan** [comment]
如果不能创建了，离关闭也不远了。 这句话真的说得好伤心。希望GAE能长久下去。

**Comment by yDan** [comment]
“如果不能创建了，离关闭也不远了。” 这句话真的说得我好伤心。希望GAE能长久下去。

**Comment by kirbyzhu** [comment]
我使用appid测试 分别选择美中和亚洲两个地址，结果发现使用亚洲appid速度是使用美中的两倍以上。但是在whatismyip里显示都是山景城
