### ISSUE TITLE
./goproxy -bash: ./goproxy: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by friends137** [phuslu/goproxy#1706]
手机 小米5  miui8 7.4.20开发版  android7.0
按着#1359 一步一步来的 
aarch64 
用的 goproxy_linux_amd64-r1390.tar.xz
执行时如下
./goproxy 
bash: ./goproxy: cannot execute binary file: Exec format error

请问是什么问题？谢谢了

**Comment by phuslu** [comment]
arm64 不是 amd64

**Comment by friends137** [comment]
收到收到 @phuslu 谢谢老大

**Comment by friends137** [comment]
可以了，感谢大家，
