### ISSUE TITLE
更新了最新版的goproxy，之前用旧版本的goproxy-gae-rXX.zip部署文件上传的appid会不会有问题？

### ISSUE THREAD

**Issue by yDan** [phuslu/goproxy#1713]
是要用新版本的部署文件重新上传吗？

**Comment by blob2015** [comment]
社长说了，最好重新上传下……

**Comment by yDan** [comment]
不会吧，要重新上传，那好麻烦，我一百多个appid。早知道不更新了。

**Comment by yDan** [comment]
还有用goproxy做代理，上Facebook超缓慢的，看Facebook里面的直播视频经常中断的，用ss就不会，你们没有遇到这个问题吗？

**Comment by wenliyang** [comment]
更新服务端会提升性能，参考 #1033

**Comment by yDan** [comment]
用这个升级比较好？我是进入社长的主页重新下载的。又错了

**Comment by yDan** [comment]
goproxy本来更新就很快的，难道每次更新都要重新上传appid？

**Comment by kirbyzhu** [comment]
看gae的版本号
r63很久没更新了

**Comment by yDan** [comment]
@kirbyzhu oh,I see.  thank u
