### ISSUE TITLE
已经创建并已部署好的的AppID，当初节点选择asia-east1的，能不能再改为us-central ？

### ISSUE THREAD

**Issue by panpeach** [phuslu/goproxy#1714]
当初部署创建App引擎，有的AppID服务器节点选择了asia-east1，有的AppID选择了us-central
现发现凡是服务器节点选择了asia-east1的APPID，能打开youtube，有的视频能播放，
但只要播放某新闻直播视频，有数据流，网页文字也能实时显示，但播放窗口黑屏，一直转圈无法显示画面。
而服务器节点选择us-central的AppID，播放youtube新闻直播视频，一切正常。
反反复复单个测试了当初创建部署的节点asia-east1和us-central的AppID，问题如上所述。
请问如何将当初选择节点asia-east1的AppID再改回us-central节点？

**Comment by mixool** [comment]
居然还有这个效果，我都忘了当初选的啥了，忙着注册25个appid去了。。。

**Comment by SeaHOH** [comment]
先从 GoProxy 配置中移除；
再从 https://console.cloud.google.com/ 中删除；
接下来就是等，等到删除完成，最快七天，长的两个多月都有；
等某天你发现终于删掉了，就可以创建新的 appid。

**Comment by mixool** [comment]
@SeaHOH 现在appid不是有限制了么，删除了还可以建不？

**Comment by SeaHOH** [comment]
一直有限制，满了删掉才能建。

**Comment by panpeach** [comment]
谢谢楼上的，只能删除AppID了，提示等待一个星期
刚才又注册了个gmail账号，重新创建并部署，选择（us-central）节点，youtube中天新闻直播完美播放
![222](https://cloud.githubusercontent.com/assets/13916352/25850527/477a7b50-34f5-11e7-937f-5f6552f3448c.jpg)

**Comment by riumiyama** [comment]
為何我創建APPID沒有看到 有選擇節點的選項 我想試試新的東京數據庫

**Comment by yDan** [comment]
@panpeach 选择us-central节点速度会比asia-east1节点快吗？

**Comment by panpeach** [comment]
@yDan ，我这里单独反复测试下来，asia-east1节点比us-central慢，而且很多youtube视频加载不出来。
us-central节点的AppID，youtube视频基本全部能播放，而且速度基本保持在10000kbps~20000kbps

![555](https://cloud.githubusercontent.com/assets/13916352/25860396/04626f7a-3514-11e7-9ceb-575d0bc384ab.jpg)

**Comment by qwerttaa** [comment]
哪儿查看appid对应的节点？我之前很早很早创建时候好像没有可选的。。。。吧？

**Comment by panpeach** [comment]
@qwerttaa ,https://console.cloud.google.com/  APP引擎，左上角选择AppID，点开来一个一个查看.
AppID创建时可选语言和节点。

![666](https://cloud.githubusercontent.com/assets/13916352/25862985/96ee02e8-351c-11e7-9b0f-a7dc41973ce3.jpg)

**Comment by riumiyama** [comment]
最近才出來的可選節點 不過我沒有看到 難道是付費才有麼

**Comment by yDan** [comment]
@panpech你创建appid选择是哪种语言？go语言吗？
