### ISSUE TITLE
用goproxy做代理选择哪种语言速度快一点？

### ISSUE THREAD

**Issue by yDan** [phuslu/goproxy#1718]
![qq 20170510103852](https://cloud.githubusercontent.com/assets/21190788/25880960/f8719e9e-356c-11e7-8f98-7b892aa81133.png)

**Comment by wz7465** [comment]
选go，服务端本身就是用go写的

**Comment by yDan** [comment]
@wz7465你确定服务端是用go写的？但是很多网上的资料都说是用python写的。

**Comment by SeaHOH** [comment]
@yDan 
既然都来这里了，用自己的眼睛确认。

**Comment by yaoguaishou** [comment]
@yDan  网上的资料过时了
