### ISSUE TITLE
来谈谈抗日战争真相

### ISSUE THREAD

**Issue by fulljump** [phuslu/goproxy#172]

**Comment by tmh8964** [comment]
共产党靠抗战发家，谁都知道。蒋领导的国军才是真抗战

**Comment by fulljump** [comment]
根据日本的战史，中日8年战争共打了47场战役，其中与中共有关的只有1场。在华作战的日军几乎没有人听过中共的「八路军」、「新四军」之名。中共说「百团大战」造成日军2万多人死伤，可是日本的纪录说日军仅阵亡2百余人。

《汉和防务评论》即将在本月刊登此一内容。《汉和》创办人平可夫表示，在查阅了众多的日本官方、民间史料后，勾画出中共抗战的真相。平可夫强调，这是极其贵重的史料，「欢迎全文转载!」

文章指出，要谈谁是抗战的「中流砥柱」，最权威、中立的证人当然是日本自己。日本官方最权威的应是防卫厅防卫研究所战史室编纂的《战史丛书》、《支那事变陆军作战》等。民间具代表性的有Usui Katumi编纂的2000年新版《中日战争》等。翻遍这些官、民战史，「提到中国共产党的地方，基本上只有5、6处」，包括西安事变、中共发表抗日救国纲领等。

日本的史书记录了中日战争中的47场大小战役，从芦沟桥开始，到芷江作战、湘桂反攻等，与中共有关的只有「百团大战」1场。在日方纪录中，中方作战的主角是国民党正规军、国民党地方军。平可夫指出，日本的史料极其细緻，日军死伤100人以上的战斗，都详细记录在案;上述史料的原始记录都是引自当时的日本「支那派遣军」内部通报;对内的战斗纪录，日本人没有夸大或贬低等习惯。

有关「百团大战」，《支那事变陆军作战》(1975年朝云新闻社出版)记道，日方损失最大的是独立混成第4旅，战死276人;然中共方面声称日军死伤20,645人(第256页)。双方数字何以差别如此巨大?平可夫认为，中共发动战役的传统模式是首先歼灭弱敌，因此百团大战中真正「大量」被歼灭的极可能只是汪精卫的伪军。

即使「百团大战」这么一场，也不合毛泽东的心意。日本防卫厅防卫研究所战史室编纂的《战史丛书18：北支的治安战》写道，1944年4月，完全控制了党内的毛泽东在延安会议上说，百团大战是一部分党员的冒险行为、右倾机会主义。

平可夫指出，要论中共在抗战中的整体表现，可以参考《支那事变陆军作战》一书第251页，其中写道：「八路军标榜『七分政治、三分军事』，基本上避免与日本军直接交战」。

《汉和防务评论》还询问了当年的日本「支那派遣军」老兵;他们除一人之外，全部不知道「八路军」、「新四军」之名。

**Comment by lefantian** [comment]
历史就是当权者的游戏，更何况一个满口胡言乱语政权

**Comment by giveup** [comment]
抗日战争是真的你中爹日爹美爹那个给你好处？都不会，要是是假的，你中爹日爹美爹一样，对你没有好处。所以呢？在一个技术社区讨论这些有毛用，无论真相怎样都改变不了你只能当个垃圾的事实，根本没人管你。我不是针对你，我是说，所有在技术社区讨论政治的，都是垃圾。

**Comment by fulljump** [comment]
在哪都能讨论政治，这才是正常国家，这里讨论政治的也不是没有，你已经把很多人都骂了，原来你就是那高尚的键盘侠，技术大神

**Comment by giveup** [comment]
@fulljump 你试想你一下，你在别人妈葬礼上谈论政治，你看别人会不会把你牙齿都打爆。（我已经尽量克制不说你妈葬礼）讨论东西要分场合。你这么有空我真心希望你能多pull两行代码，而不是发一个毫无关系的issue。我也是吃饱了撑的，想要认真的回复你。

**Comment by fulljump** [comment]
@giveup 你管的还真宽，有毛病去医院，发个帖唧唧歪歪的，还骂人，有点教养没有，这里谈政治的贴多了去，你厉害你去一个个喷吧

**Comment by Qixingchen** [comment]
首先，GitHub并不是技术论坛。

2015-09-09 9:14 GMT+08:00 fulljump <notifications@github.com>:

**Comment by GiveMeAHug** [comment]
楼主要去喊人了，大家小心哦
![1939873_7aadafaef8f67e54435572276228bcac_1441679939](https://cloud.githubusercontent.com/assets/14194132/9755228/e65def0e-5702-11e5-9ea8-0950414281cd.gif)

**Comment by cmdlet1** [comment]
其次，人家说什么是人家的事

**Comment by wenliyang** [comment]
虽然我也反感在这里谈政治，不过phuslu不管就是允许这种贴了吧

**Comment by GiveMeAHug** [comment]
果不其然，楼主把楼上的cmdlet1喊来了，让大伙大吃一惊






![Uploading 1897477_da16db15d.gif…]()
![189](https://cloud.githubusercontent.com/assets/14194132/9756811/635df948-570f-11e5-9a5c-a85fbe80ab88.gif)

**Comment by cmdlet1** [comment]
@GiveMeAHug 哎，一个人在这里唱双簧有意思，按你的话，有那时间还不如去写代码

**Comment by fulljump** [comment]
既然有人不愿意看到我就清空他吧，对不起你，删掉了，别纠结了
