### ISSUE TITLE
错误提示an existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by Waynesway** [phuslu/goproxy#1725]
帮我看下是哪里出问题了，昨天一样的配置还可以用。 今天就是一片红字。
------------------------------------------------------
GoProxy Version    : r1382 (go/8671ce1 http2/6064a03 windows/386)
GoProxy Profile    : Default
Listen Address     : 127.0.0.1:8087
Enabled Filters    : autoproxy,stripssl,autorange|autoproxy,gae,direct|autorange

Pac Server         : http://127.0.0.1:8087/proxy.pac

------------------------------------------------------
W0513 09:42:31.348345    4276 rootca.go:175] Verify RootCA("GoProxy") error: x50
9: certificate signed by unknown authority, try import to system root
E0513 09:42:31.357346    4276 rootca.go:177] Remove Old RootCA("GoProxy") error:
 The parameter is incorrect.
I0513 09:42:31.362346    4276 rootca.go:182] Import RootCA(GoProxy.crt) OK
E0513 09:42:31.362346    4276 rootca.go:188] *storage.FileStore.Delete("cache/ec
c") error: remove D:\Program Files\goproxy_windows_386-r1382\cache\ecc: The dire
ctory is not empty.
I0513 09:42:34.348517    4276 stripssl.go:144] 127.0.0.1:50243 "STRIP CONNECT 0.
client-channel.google.com:443 HTTP/1.1" - -
W0513 09:42:35.351574    4276 gae.go:524] 127.0.0.1:50243 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/gsid HTTP/1.1" error: *errors.error
String(context canceled)
E0513 09:42:35.351574    4276 handler.go:96] 127.0.0.1:50243 Filter RoundTrip *g
ae.Filter error: context canceled
I0513 09:42:35.353574    4276 stripssl.go:144] 127.0.0.1:50247 "STRIP CONNECT 0.
client-channel.google.com:443 HTTP/1.1" - -
W0513 09:42:36.499640    4276 gaetransport.go:49] GAE: "GET http://config.pinyin
.sogou.com/components/update.php?h=61402CD8D14F39E3E3EC9863795C99A6&v=7.0.0.9553
&r=0000_sogou_pinyin_65&utp=2&b0=1010_1.0.0.792" timeout: read tcp 127.0.0.1:502
40->127.0.0.1:1080: wsarecv: An existing connection was forcibly closed by the r
emote host., helpers.CloseConnections(*http.Transport)
W0513 09:42:36.500640    4276 gae.go:524] 127.0.0.1:50239 "GAE FETCH GET http://
config.pinyin.sogou.com/components/update.php?h=61402CD8D14F39E3E3EC9863795C99A6
&v=7.0.0.9553&r=0000_sogou_pinyin_65&utp=2&b0=1010_1.0.0.792 HTTP/1.1" error: *n
et.OpError(read tcp 127.0.0.1:50240->127.0.0.1:1080: wsarecv: An existing connec
tion was forcibly closed by the remote host.)
E0513 09:42:36.501640    4276 handler.go:96] 127.0.0.1:50239 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50240->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
W0513 09:42:40.456866    4276 gae.go:524] 127.0.0.1:50247 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/channel/cbp?ctype=hangouts&prop=gma
il&appver=chat_frontend_20170509.10_p0&gsessionid=7ki35RpeyiAERfpm8p2JuSQEc9J2BW
ax&VER=8&MODE=init&zx=j85n54omy0jp&t=1 HTTP/1.1" error: *net.OpError(read tcp 12
7.0.0.1:50248->127.0.0.1:1080: wsarecv: An existing connection was forcibly clos
ed by the remote host.)
E0513 09:42:40.457866    4276 handler.go:96] 127.0.0.1:50247 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50248->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
I0513 09:42:40.463866    4276 stripssl.go:144] 127.0.0.1:50254 "STRIP CONNECT ww
w.google.com:443 HTTP/1.1" - -
W0513 09:42:43.346031    4276 gae.go:524] 127.0.0.1:50247 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/gsid HTTP/1.1" error: *errors.error
String(context canceled)
E0513 09:42:43.349031    4276 handler.go:96] 127.0.0.1:50247 Filter RoundTrip *g
ae.Filter error: context canceled
I0513 09:42:43.350031    4276 stripssl.go:144] 127.0.0.1:50260 "STRIP CONNECT 0.
client-channel.google.com:443 HTTP/1.1" - -
W0513 09:42:45.561158    4276 gae.go:524] 127.0.0.1:50254 "GAE DIRECT GET https:
//www.google.com/images/cleardot.gif?zx=17v4q66kipm HTTP/1.1" error: *net.OpErro
r(read tcp 127.0.0.1:50255->127.0.0.1:1080: wsarecv: An existing connection was
forcibly closed by the remote host.)
E0513 09:42:45.562158    4276 handler.go:96] 127.0.0.1:50254 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50255->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
I0513 09:42:47.337260    4276 stripssl.go:144] 127.0.0.1:50268 "STRIP CONNECT co
nsole.cloud.google.com:443 HTTP/1.1" - -
I0513 09:42:47.339260    4276 rootca.go:388] Issue GoProxy certificate for "*.cl
oud.google.com"...
W0513 09:42:48.445323    4276 gae.go:524] 127.0.0.1:50260 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/channel/cbp?ctype=hangouts&prop=gma
il&appver=chat_frontend_20170509.10_p0&gsessionid=7ki35RpeyiAERfpm8p2JuSQEc9J2BW
ax&VER=8&MODE=init&zx=7bd0939bowby&t=1 HTTP/1.1" error: *net.OpError(read tcp 12
7.0.0.1:50261->127.0.0.1:1080: wsarecv: An existing connection was forcibly clos
ed by the remote host.)
E0513 09:42:48.894349    4276 handler.go:96] 127.0.0.1:50260 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50261->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
W0513 09:42:52.396549    4276 gae.go:524] 127.0.0.1:50268 "GAE DIRECT GET https:
//console.cloud.google.com/m/operations?maxResults=100 HTTP/1.1" error: *net.OpE
rror(read tcp 127.0.0.1:50269->127.0.0.1:1080: wsarecv: An existing connection w
as forcibly closed by the remote host.)
E0513 09:42:52.397549    4276 handler.go:96] 127.0.0.1:50268 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50269->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
W0513 09:42:53.908635    4276 gae.go:524] 127.0.0.1:50254 "GAE DIRECT GET https:
//www.google.com/images/cleardot.gif?zx=f4agg48n3ja8 HTTP/1.1" error: *net.OpErr
or(read tcp 127.0.0.1:50271->127.0.0.1:1080: wsarecv: An existing connection was
 forcibly closed by the remote host.)
E0513 09:42:53.909635    4276 handler.go:96] 127.0.0.1:50254 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50271->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
W0513 09:42:58.345889    4276 gae.go:524] 127.0.0.1:50260 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/gsid HTTP/1.1" error: *errors.error
String(context canceled)
E0513 09:42:58.348889    4276 handler.go:96] 127.0.0.1:50260 Filter RoundTrip *g
ae.Filter error: context canceled
I0513 09:42:58.350889    4276 stripssl.go:144] 127.0.0.1:50281 "STRIP CONNECT 0.
client-channel.google.com:443 HTTP/1.1" - -
W0513 09:43:03.420179    4276 gae.go:524] 127.0.0.1:50281 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/channel/cbp?ctype=hangouts&prop=gma
il&appver=chat_frontend_20170509.10_p0&gsessionid=7ki35RpeyiAERfpm8p2JuSQEc9J2BW
ax&VER=8&MODE=init&zx=3ref1zibgqdx&t=1 HTTP/1.1" error: *net.OpError(read tcp 12
7.0.0.1:50282->127.0.0.1:1080: wsarecv: An existing connection was forcibly clos
ed by the remote host.)
E0513 09:43:03.421180    4276 handler.go:96] 127.0.0.1:50281 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50282->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
W0513 09:43:08.466468    4276 gae.go:524] 127.0.0.1:50254 "GAE DIRECT GET https:
//www.google.com/images/cleardot.gif?zx=7c37k9ieljhp HTTP/1.1" error: *net.OpErr
or(read tcp 127.0.0.1:50288->127.0.0.1:1080: wsarecv: An existing connection was
 forcibly closed by the remote host.)
E0513 09:43:08.467468    4276 handler.go:96] 127.0.0.1:50254 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50288->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
W0513 09:43:11.347633    4276 gae.go:524] 127.0.0.1:50281 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/gsid HTTP/1.1" error: *errors.error
String(context canceled)
E0513 09:43:11.348633    4276 handler.go:96] 127.0.0.1:50281 Filter RoundTrip *g
ae.Filter error: context canceled
I0513 09:43:11.351633    4276 stripssl.go:144] 127.0.0.1:50298 "STRIP CONNECT 0.
client-channel.google.com:443 HTTP/1.1" - -
W0513 09:43:12.334689    4276 gae.go:524] 127.0.0.1:50268 "GAE DIRECT GET https:
//console.cloud.google.com/m/emergencies HTTP/1.1" error: *net.OpError(read tcp
127.0.0.1:50292->127.0.0.1:1080: wsarecv: An existing connection was forcibly cl
osed by the remote host.)
E0513 09:43:12.335689    4276 handler.go:96] 127.0.0.1:50268 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50292->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
W0513 09:43:16.355919    4276 gae.go:524] 127.0.0.1:50298 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/channel/cbp?ctype=hangouts&prop=gma
il&appver=chat_frontend_20170509.10_p0&gsessionid=7ki35RpeyiAERfpm8p2JuSQEc9J2BW
ax&VER=8&MODE=init&zx=ut1clg3jgkp5&t=1 HTTP/1.1" error: *net.OpError(read tcp 12
7.0.0.1:50299->127.0.0.1:1080: wsarecv: An existing connection was forcibly clos
ed by the remote host.)
E0513 09:43:16.356919    4276 handler.go:96] 127.0.0.1:50298 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50299->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
W0513 09:43:21.418209    4276 gae.go:524] 127.0.0.1:50254 "GAE DIRECT GET https:
//www.google.com/images/cleardot.gif?zx=wo83jzone2hj HTTP/1.1" error: *net.OpErr
or(read tcp 127.0.0.1:50305->127.0.0.1:1080: wsarecv: An existing connection was
 forcibly closed by the remote host.)
E0513 09:43:42.095392    4276 handler.go:96] 127.0.0.1:50254 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50305->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.
W0513 09:43:44.356521    4276 gae.go:524] 127.0.0.1:50298 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/gsid HTTP/1.1" error: *errors.error
String(context canceled)
E0513 09:43:44.358521    4276 handler.go:96] 127.0.0.1:50298 Filter RoundTrip *g
ae.Filter error: context canceled
I0513 09:43:44.357521    4276 stripssl.go:144] 127.0.0.1:50311 "STRIP CONNECT 0.
client-channel.google.com:443 HTTP/1.1" - -
W0513 09:43:49.428811    4276 gae.go:524] 127.0.0.1:50311 "GAE DIRECT GET https:
//0.client-channel.google.com/client-channel/channel/cbp?ctype=hangouts&prop=gma
il&appver=chat_frontend_20170509.10_p0&gsessionid=7ki35RpeyiAERfpm8p2JuSQEc9J2BW
ax&VER=8&MODE=init&zx=zcfbnafgy838&t=1 HTTP/1.1" error: *net.OpError(read tcp 12
7.0.0.1:50312->127.0.0.1:1080: wsarecv: An existing connection was forcibly clos
ed by the remote host.)
E0513 09:43:49.429811    4276 handler.go:96] 127.0.0.1:50311 Filter RoundTrip *g
ae.Filter error: read tcp 127.0.0.1:50312->127.0.0.1:1080: wsarecv: An existing
connection was forcibly closed by the remote host.

**Comment by Waynesway** [comment]
过了几个小时 现在可以了。请版主close 这个issue 吧

**Comment by phuslu** [comment]
看起来是证书没有正确导入。
