### ISSUE TITLE
r1406, 抽筋吗?

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1731]
r1404 ->r1406, 突然抽筋般流畅很多.

http://openspeedtest.com/
这个测试看起来很明显.

**Comment by SeaHOH** [comment]
扭扭更健康

**Comment by phuslu** [comment]
r1406 回滚了，tls1.3。

因为发现 chrome 有些不符合标准的行为。https://github.com/phuslu/goproxy/issues/1703

**Comment by jasonliul** [comment]
俺用火狐, 看起来还是这样好.

**Comment by 94oiio** [comment]
发现一个问题，我用了上面这个测速网站测试了herokuapp搭的PHP代理的速度后，即使关掉了浏览器，什么也不做，goproxy也根本停不下来，一直在疯狂的连接ec2-XX-XX-XXX-194.compute-1.amazonaws.com这个ip ，速度时快时慢，最快的时候都能彪到20M，我在网页测速时都没这么快的速度只有大概2M的速度，而且goproxy没有任何日志输出，只有正常的goodip badip显示，无其他信息。 

![default](https://cloud.githubusercontent.com/assets/18633798/26053072/014c8106-399a-11e7-9f1a-8947dcf24a17.PNG)


已经再三确认了，没有开启任何需要goproxy代理的软件，上面那个ip我用浏览器打开后发现是herokuapp的网址，怀疑就是我搭的php地址，所以打了个码
![1](https://cloud.githubusercontent.com/assets/18633798/26052640/b49a152c-3998-11e7-9d87-5f1039dc57fe.PNG)

**Comment by jasonliul** [comment]
@94oiio 
这个测试网站是html5, 或许浏览器太旧?

**Comment by 94oiio** [comment]
@jasonliul  最新稳定版chrome,而且我即使完全退出关闭浏览器，也是一样的   已经重启goproxy 试了3次了，每次都是这样 只要一用上面的网站测速就会出现  系统win10 1703

**Comment by jasonliul** [comment]
@94oiio 
还是把社长揪出来罢~~
火狐没有问题

**Comment by 94oiio** [comment]
而且，最诡异的是goproxy没有任何相关日志输出，只有绿字的good ip bad ip显示
难不成是win10资源监视器的bug？

**Comment by jasonliul** [comment]
@94oiio 
应该不是, Goproxy对于chromium类浏览器, 似乎总有一些问题...

**Comment by 94oiio** [comment]
顺便@phuslu

**Comment by jasonliul** [comment]
现在最好的html5测试, 还有一个是
https://fast.com/

优点是始终会稍小于实际速度, 比较可靠

**Comment by 94oiio** [comment]
刚回到家又试了一下，https://fast.com/测速也会出现这种情况，不过可能家里和公司不在同一网络下，这次持续连接的ip变成了23.23.117.76，经查询也是个Amazon的ip，应该都是herokuapp的
而且同时也测试了看youtube直播和视频，并不会出现这种情况，貌似只有你这两测速的网站有这种现象
但是用gae代理的话就完全没问题   家里用的360极速  goproxy版本1404    公司chrome goproxy1406

**Comment by 94oiio** [comment]
应该就是PHP代理有问题

**Comment by kirbyzhu** [comment]
![image](https://cloud.githubusercontent.com/assets/10296293/26063317/43388bde-39c0-11e7-8e4c-01b828afead8.png)
今天新增了一些ip 频繁出现这个错误 以前还从来没有 怀疑是新增ip里面有问题 但是不知道这种情况如何去掉badip

**Comment by jasonliul** [comment]
@kirbyzhu 
河北廊坊字样都出来了...

**Comment by kirbyzhu** [comment]
是的 后来想想还是不冒险了 恢复原来的ip集合算了 新增的是在xxnet里面扫描出来的  

这种badip怎么测试出来？

**Comment by 94oiio** [comment]
MFF扫一遍就好了或者pinginfoview

**Comment by jasonliul** [comment]
两个有用的小工具
http://nirsoft.net/utils/cports.html
查看打开端口, 能直接看到GP当前使用的GIP, 其实就几个.

http://www.nirsoft.net/utils/ip_country_info_offline.html
批量查看ip所属国家

**Comment by kirbyzhu** [comment]
谢谢j大

**Comment by blob2015** [comment]
@phuslu 
第一次丝般柔顺完成服务端的升级，一气呵成，在白天。
所以1.3目前来说，还是不成熟？

**Comment by kirbyzhu** [comment]
我升级服务端一直很柔顺丝滑的啊
