### ISSUE TITLE
娱乐. 两个测试网站

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1732]
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/26049187/b7d1dd8a-398c-11e7-9d89-2e88224cab83.jpg)
本机ip
https://2ip.ru/
这个独特的地方是, 连通性很好的话, 会显示笑脸.
国内isp分配的ip, 只是偶尔有笑脸, 但是有的话, 所有代理都鸡血.

浏览器
http://browserbench.org/
所有浏览器相关, 有些问题无关代理.

**Comment by SeaHOH** [comment]
没血啦，奶妈在哪儿？ :yellow_heart:

**Comment by jasonliul** [comment]
@SeaHOH 
俺发现内网一个奇怪的用户, 在分支路由器下面, 没法直接揪出来.
上传稳定600-700kb, [几乎是全部, 线路上传10M], 下载却只有10几kb. 简直是黄狗杀手.

这是什么鬼程序?

**Comment by SeaHOH** [comment]
看描述像是 bt 做种，难道找不出这个 IP ？

**Comment by jasonliul** [comment]
@SeaHOH 
忘了这茬...
