### ISSUE TITLE
每天第一次打开quora推送的链接时，网页都无法完全加载

### ISSUE THREAD

**Issue by Limsig** [phuslu/goproxy#1734]
每天第一次打开quora推送的链接时，网页都无法完全加载，但多次刷新后又能恢复正常，而且一旦恢复正常后就再不会出现这种情况。在chrome隐身模式下则会反复出现该情形。

我觉得是gop的问题，因为用xx-net时不会出现这个问题。

链接：
https://www.quora.com/Why-are-there-so-many-fake-data-scientists-and-machine-learning-engineers

截图：
![image](https://cloud.githubusercontent.com/assets/22915681/26137086/87914bda-3af2-11e7-9c83-70ed5a6aed77.png)

**Comment by blob2015** [comment]
俺用ff最新版的ESR，国内个别网站也有这种加载不完全的情况
小白就插一嘴，不多说

**Comment by SeaHOH** [comment]
这个网站可以直连。

**Comment by Limsig** [comment]
然而有的功能和内容在直连的情况下无法正常使用 @SeaHOH

**Comment by SeaHOH** [comment]
我用的 goproxy.gae 服务端，没用 goproxy 客户端，走 GAE 代理，第一次正常加载完全。

**Comment by jasonliul** [comment]
没有问题.
清空浏览器缓存再试

**Comment by SeaHOH** [comment]
我又试了一次，禁用 ADB 和 NoScript、开启 cookie，直连完全正常。

**Comment by Limsig** [comment]
已禁用ADB，一直没用script，cookie一直开启，重新清空缓存，依然如此。直连部分内容如公式常无法正常显示，我给的链接里没有。

**Comment by SeaHOH** [comment]
给个链接呗。

**Comment by Limsig** [comment]
我觉得和缓存没关系，因为隐身模式下缓存都是默认被清空的吧……？还有我觉得是不是跟switchomega有关，貌似只有自动切换的时候才会出现这种情况。

**Comment by SeaHOH** [comment]
给个链接，我也试试。

**Comment by Limsig** [comment]
@SeaHOH 
https://www.quora.com/What-is-the-value-of-x-in-this-equation-4-x-8x

![image](https://cloud.githubusercontent.com/assets/22915681/26143833/30a10f8c-3b19-11e7-8f6a-57bc6c1ac46f.png)

**Comment by jasonliul** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/26143888/6d2af2c4-3b19-11e7-9b63-86e818f39a8e.jpg)

仍然正常

**Comment by Limsig** [comment]
往下滚啊……我上面的也正常

**Comment by jasonliul** [comment]
也正常

**Comment by SeaHOH** [comment]
全部正常，直连。

**Comment by Limsig** [comment]
呃…………这…………

**Comment by SeaHOH** [comment]
你可能觉得难以置信，但这是真的。

**Comment by MeABc** [comment]
chrome隐身模式下正常

![11](https://cloud.githubusercontent.com/assets/18194126/26144253/ada08502-3b1a-11e7-9f88-b781f1449f8a.gif)

**Comment by SeaHOH** [comment]
看网页源码，样式是内嵌的。

**Comment by jasonliul** [comment]
http://browserbench.org/
Chromium一类浏览器, 插件其实还是不如火狐, 很可能是某个插件造成的. 像LastPass 有些机器上内存占用异常.

**Comment by SeaHOH** [comment]
我 pm，扩展各种不兼容，刚才想截图，发现扩展挂了……

**Comment by SeaHOH** [comment]
火狐扩展马上就要跟 Chromium 一样了，药丸。

**Comment by MeABc** [comment]
![image](https://cloud.githubusercontent.com/assets/18194126/26144498/a48689ca-3b1b-11e7-8adb-7e75fdfc4e12.png)

红圈处的 `DEADLINE_EXCEEDED` ，上面还有很多，更新最新版试下，另一个，在重试时如网络断了，就有可能出现楼主的情况。

**Comment by MeABc** [comment]
得出一个不靠谱的结论： goproxy 太快，服务器拒绝，要重试。这时要看 IP 质量。

**Comment by jasonliul** [comment]
@SeaHOH 
俺其实是把新版火狐默认开启的pipelining改小为8, 不然没完没了的人机验证.

**Comment by SeaHOH** [comment]
走 GAE 代理的确会有这种错误，但是多等几秒也就加载完全了。直连就没这个烦恼。

**Comment by SeaHOH** [comment]
@jasonliul 
由于浏览器完全走代理的原因，我直接禁用 pipelining。

**Comment by Limsig** [comment]
我这直连和使用自动切换是这个样子…………但用SwitchyOmega全部走gop时又没这个问题……
![qq 20170517161212](https://cloud.githubusercontent.com/assets/22915681/26145130/e811ea0c-3b1d-11e7-9003-6b387c5cae66.png)
![qq 20170517161649](https://cloud.githubusercontent.com/assets/22915681/26145131/e81a5322-3b1d-11e7-93b8-b80111fc7455.png)

**Comment by SeaHOH** [comment]
网站可能有 IP 检测，而且网站使用了 cdn，走不同 IP 导致浏览器无法整合页面。

**Comment by MeABc** [comment]
这应该是地区网络问题，被阻断了。

**Comment by SeaHOH** [comment]
我见过有的网站不同地区访问时，页面一毛一样，但引用资源有很多不同。

**Comment by MeABc** [comment]
> 把新版火狐默认开启的pipelining改小为8, 不然没完没了的人机验证.

这个有效果不，改天试了。火狐人机验证很多啊，简直是在考验人的耐心。

**Comment by Limsig** [comment]
我把不能正常加载的资源都自动切换走gop，貌似解决了！谢谢大家！

**Comment by jasonliul** [comment]
@MeABc 
俺还是建议开启, 不会提升速度, 但可以增加代理稳定性, 改为8, 或者6比较合适.
新版火狐默认开得太大, 疑似恶意行为

**Comment by MeABc** [comment]
@jasonliul 

我看了一下常用的 Firefox nightly ，里面竟然没有这些 `pipelining` 了。 firefox 53 还有。

google 了一下，从下个版本(54)开始不支持这个了。

https://developer.mozilla.org/en-US/Firefox/Releases/54

```
Pipelining support has been removed in FIrefox 54. Maintaining it as we make the move into a new world full of HTTP/2 and other substantial, standardized improvements to networking performance is not worthwhile given pipelining's compatibility and performance issues. The network.http.pipelining preference (as well as the other preferences that start with "network.http.pipelining") is now ignored. See bug 1340655 for further information.
```

**Comment by jasonliul** [comment]
@MeABc 
不奇怪, 这个功能一直被视为鸡肋.

**Comment by blob2015** [comment]
@jasonliul @MeABc 
看了下，network.http.pipelining.maxrequests，俺这边就是8，难道俺之前改过？都忘记了。另外还有一个值，network.http.pipelining.max-optimistic-requests，是4。
那个验证，确实挺烦人。
@SeaHOH 
是啊，据说扩展要完，据说新版扩展的效率不好什么什么的。有时候真是搞不明白，整容整得跟c一样，那人家干嘛不用原汁原味的c？
个人不是怎么喜欢c，总感觉有点太霸道，搞广告的，总会比较那啥。
之前用Opera，然后整容整得人不像人鬼不像鬼，没法用了，然后做了数字的妾。
感觉FF这么搞下去，会不会撞墙，然后回头？还是也做了谁的妾？
感觉都没个好用的浏览器了，这么下去。

**Comment by SeaHOH** [comment]
@blob2015 
转 PaleMoon 吧，安全方面还在不断更新，新标准也在不断开发支持，就是有些扩展需要修改才能支持。

下面这些扩展是没有其它能用的兼容修改，然后只好自己改。
https://github.com/SeaHOH/pm-addons

**Comment by blob2015** [comment]
@SeaHOH 
那天ublock的开发者倒说了一嘴，说他就信palemoon。
等过了这段日子，试试看。浏览器重度（只是指时间）使用者。
感谢大海兄。

**Comment by MeABc** [comment]
@SeaHOH 
厉害！还改了那么多！
nightly 禁用了好多。

**Comment by SeaHOH** [comment]
你们遇到不兼容的扩展可以告诉我，如果不是很复杂，估计我还能改。只限 PM 最新的大版本。

**Comment by SeaHOH** [comment]
@blob2015 
ublock 用着很不习惯，层次太多，有限制某些想法没法用上，还是 ADB 好。

**Comment by blob2015** [comment]
@SeaHOH 
有些语法确实，尤其最近加了好些个……
不过，反正，对于大多数人来说，就是关灯那啥，不讲究那么多，反正很多人都是不会自己去设置 😀 
不过，之前对付cnbeta的广告、提醒，ub确实能起作用，自己稍微设置下的话。关于两者的争论，那是……反正人嘛，总有很多不同习惯 😀

**Comment by SeaHOH** [comment]
ADB 也可以隐藏 cnbeta 的提醒
`##DIV[style^="display:block"]`
