### ISSUE TITLE
这个错误非常频繁出现（gae filter error invalid read on closed body）

### ISSUE THREAD

**Issue by vcheng** [phuslu/goproxy#1736]
一旦出现，facebook视频就会断掉，YouTube直播聊天室会断掉。这个怎么搞？
![03](https://cloud.githubusercontent.com/assets/3966423/26196014/26384fec-3bf0-11e7-9d58-91a906d6cc01.png)

**Comment by MeABc** [comment]
前面有其它类型的错误不？
你是用火狐浏览器吗？

**Comment by MeABc** [comment]
facebook视频， YouTube直播， 网址能发下不

**Comment by vcheng** [comment]
是的，用的火狐浏览器。没有其他错误，就只有这个。facebook任何视频，youtube任何直播。你可以试试这个直播看看，https://www.youtube.com/watch?v=Od-5LRHr-DQ

**Comment by MeABc** [comment]
我大概猜出是什么情况了，你可以这样试下

gae.json 

![image](https://cloud.githubusercontent.com/assets/18194126/26198787/075121bc-3bfa-11e7-93b1-2728a6cf4b9c.png)

把这个改大点。比如 30

**Comment by MeABc** [comment]
刚那个回复删了。看错了。你用的是 PHP。我以为是 GAE。。。

**Comment by MeABc** [comment]
你那图上是 gae 前置 php 的吧。

呃，再补上刚删的那个回复。。。

gae.json/gae.user.json

![image](https://cloud.githubusercontent.com/assets/18194126/26199405/6e224158-3bfc-11e7-944d-cdd1f1d91234.png)

把这个加大点，比如 30。

**Comment by vcheng** [comment]
不行，问题还是存在。

**Comment by kirbyzhu** [comment]
放足够多的IP试试 发自网易邮箱手机版 在2017年05月18日 19:37，vcheng 写道： 不行，问题还是存在。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MeABc** [comment]
我用 firefox ， gae 前置 PHP ，测试楼主给的地址，一路飘白，连黄字都没有，神奇了。（第一次这样子用来访问youtube）

而用 gae 走 youtube 直播的话，会卡住，但不会断。gae 前置 PHP 一点都不卡！！！

**Comment by MeABc** [comment]
![image](https://cloud.githubusercontent.com/assets/18194126/26203246/1fff5978-3c0d-11e7-9f0c-e6bf4ba4aadc.png)

有图有真相。红圈处，30000多帧都不丢一帧。

**Comment by vcheng** [comment]
有可能是环境或者IP质量造成的？？

**Comment by MeABc** [comment]
目前来看，只能是多放IP进去试了。

--
再附一张 10 万帧的图，不掉一帧。（关声音挂机 30 分种以上。）


![image](https://cloud.githubusercontent.com/assets/18194126/26205581/bf026482-3c14-11e7-8bf8-a8c401a45938.png)

**Comment by vcheng** [comment]
你敢放你的IP出来不？

**Comment by MeABc** [comment]
额。。。

--

你可以搜一下 issues 。另，推荐一个给你

https://github.com/phuslu/goproxy/issues/1095

**Comment by blob2015** [comment]
@MeABc 
ABC兄真是好人 😀 

---------------

怀疑，可能还是ip问题。俺从之前的万余，加到了两万不到，之前很少的红黄就开始大幅增加。数量就是质量，但有时候数量未必是质量 😀 
另外，个人建议，不要说，“敢放你的IP出来不”，听着有点小不爽。是你想着查找、解决问题，并非欠你。

**Comment by vcheng** [comment]
又没问你，奇怪。

**Comment by yDan** [comment]
@vcheng 我的也是这种情况，出现这种情况，Facebook直播视频会断掉。你解决了没？解决了就告诉我一下方法。

**Comment by MeABc** [comment]
Facebook 直播我试了一下，只要 IP timeout 就会断掉，貌似它不会重试；而这种情况下（IP timeout），youtube 直播会重试，且是会重试多次。这就是为什么 youtube 直播会卡但不会断掉的原因。

Facebook直播测试地址
https://www.facebook.com/livemap

**Comment by yDan** [comment]
@MeABc 有什么办法可以解决的吗？

**Comment by MeABc** [comment]
我想到有两种解决方法：

1。要求 google ip 质量好点。
2。或者，取消 ip timeout add to blacklist ，让 gae 来重试。

第二条同样要求 ip 质量，不然重试也没用。

**Comment by yDan** [comment]
那就说没有办法囖，都是ip问题囖，没好ip问题永远都解决不了囖

**Comment by MeABc** [comment]
当然，第二种要求 IP 不用那么高，可能会变成直播时好时坏，完美的解决方法只能是 fackbook 改成 youtube 那种断开连接重试多次。

**Comment by yDan** [comment]
ip timeout add to blacklist   这个在哪个文件里的？  怎么才能像youtube那样断开会重连？怎么搞呢？

**Comment by kirbyzhu** [comment]
我使用直播没出现过类似的错误

**Comment by yDan** [comment]
@kirbyzhu 你放了多少个ip呢？

**Comment by MeABc** [comment]
想了一下，也不用搞那么复杂，注释掉下面这行应该可以解决这个

[gaetransport.go#L62](https://github.com/phuslu/goproxy/blob/master/httpproxy/filters/gae/gaetransport.go#L62)

--

> 我使用直播没出现过类似的错误

我在这里测试时， 日志 timeout 直播就会断开，且不会重试。
呃，我也有可能看得不仔细，大家也可以多测看下。或者提供地址。

**Comment by kirbyzhu** [comment]
7k个

**Comment by yDan** [comment]
@kirbyzhu 我就觉得放那么多的ip ，就不怕差的ip拖住好的ip吗？差的ip把好的ip的路堵住了，上网怎么会快呢？7K个大部分都是延迟非常高的ip。

**Comment by phuslu** [comment]
如果担心性能的话，可以先放 1k~2k 左右的 IP 试试。

**Comment by blob2015** [comment]
@MeABc 
ABC兄脾气好，人好 😀
@yDan 
不是所有人都那么敏感速度的，而且也不是所有人那么勤快。多加些，可以免维护啊，而且大多也就看个网页。每个人需求不同。
@phuslu 
社长，1.3还没熟啊？看着好像出了不少版本了啊？

---------------

某人沾到屎了，然后大吼，怎么回事，我怎么会沾到屎，掐着兰花指、指着某人说，快给我说说，你丫的怎么就没有沾到呢，有什么秘密！赶紧说！
路人甲看到，插了句，你好像有点臭啊。那厮阴阳怪气来一句：“又没有问你，奇怪。” 😀

**Comment by vcheng** [comment]
@blob2015
我看阴阳怪气的倒是你。本来就没问你，你跳出来找事干嘛？你这人不仅像个女人一样小气，且EQ也不会很高，听不出好话坏话，不会有什么朋友。这有什么可秘密的？感情就你秘密多，真是自作多情，自我感觉无比良好。

**Comment by yDan** [comment]
@在这里讨论问题的，怎么变成吵架论坛了。把问题解决了才是有意义的事

**Comment by phuslu** [comment]
先锁帖一天。。。
