### ISSUE TITLE
r1410 编译有问题

### ISSUE THREAD

**Issue by MeABc** [phuslu/goproxy#1741]
![default](https://cloud.githubusercontent.com/assets/18194126/26282140/9742d42e-3e3d-11e7-8af4-d412cf767d53.png)

应该是这里 
[make.bash#L114](https://github.com/phuslu/goproxy/blob/master/make.bash#L114)

ldflags="${LDFLAGS}" 这个变量取不到值。

**Comment by MeABc** [comment]
@phuslu 社长，你看下。我先关这个了。

**Comment by kirbyzhu** [comment]
使用正常 就是显示出问题了

**Comment by MeABc** [comment]
嗯，可以正常使用。

**Comment by phuslu** [comment]
r1411 应该已经修复。

**Comment by MeABc** [comment]
![default](https://cloud.githubusercontent.com/assets/18194126/26282767/759ea494-3e4a-11e7-8b28-4cb6376ae753.png)

可以了。

**Comment by phuslu** [comment]
这几个 commits 其实为了这几行 https://github.com/phuslu/goproxy/blob/188cf1e85adc6c99c2a5e8c94c8fb22ea17218be/assets/build/ci.sh#L286-L295

并行化编译 goproxy-vps，这样可以少等待些时间。
