### ISSUE TITLE
从1402版升级到1412后只能上google了，此贴终结，我犯了个低级错误……

### ISSUE THREAD

**Issue by ashi876** [phuslu/goproxy#1747]
之前升级各版本一直都用的很好。升级到1412后只能打开google.
打开youtube会显示appid上的版本介面

**Comment by phuslu** [comment]
贴个截图和日志上来看看

**Comment by SeaHOH** [comment]
#1745 这儿有

**Comment by ashi876** [comment]
我的页面打开上楼有一点不同，好象最后一行出错不一样
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1412 (go/devel +2cf1f91 Sat May 20 15:26:25 2017 +0000 windows/amd64)",
    "filter": "*gae.Filter",
    "error": "unexpected EOF"
}

**Comment by SeaHOH** [comment]
社长还需要点日志。

**Comment by ashi876** [comment]
日志是哪个文件？
我的系统是win7 64. firefox浏览器，回退到1406一切正常

**Comment by SeaHOH** [comment]
就是运行窗口中的，截图也可以，要出错那段。

**Comment by ashi876** [comment]
运行窗口打开油管出错信息如下：
s3.google.com:443") with good_addrs=3, bad_addrs=28
I0523 10:15:55.533742    4636 stripssl.go:158] 127.0.0.1:54103 "STRIP CONNECT ww
w.youtube.com:443 HTTP/1.1" - -
W0523 10:15:55.825758    4636 gae.go:524] 127.0.0.1:54103 "GAE FETCH GET https:/
/www.youtube.com/ HTTP/1.1" error: *errors.errorString(unexpected EOF)
E0523 10:15:55.826758    4636 handler.go:96] 127.0.0.1:54103 Filter RoundTrip *g
ae.Filter error: unexpected EOF

**Comment by ashi876** [comment]
![2](https://cloud.githubusercontent.com/assets/28881760/26335905/98836bb8-3fa1-11e7-9099-95e8ecdcceec.png)

**Comment by SeaHOH** [comment]
你是说你不小心设置成全局代理了？

**Comment by ashi876** [comment]
全局代理一样能上youtube吧.
我忘记输入appid了，第一次知道原来不要appid原来也能打个google.也正是因为能开google,以为自己翻强成功了~好羞耻的感觉

**Comment by SeaHOH** [comment]
还好啦，能自己冷静分析。
