### ISSUE TITLE
能问问这句红字什么意思么

### ISSUE THREAD

**Issue by ashi876** [phuslu/goproxy#1748]
从goA转到gop几个月了，其实goA目前在我的电脑上运行良好，从来不出红黄字，速度也快。前些日子被chrome58的证书问题逼着换到了goP,虽然后来也解决了。也正因此找到了这个新的项目，感谢社长，我也是才发现goA还有后续。

想着goP才有更新，没更新的goA只能是前途暗淡。用了一段时间goP换过三次版本用的很顺利，特别是服务端上传比以前goA还要方便。

废话那么多现在要问 问题了，gop总是长期显示一段红字如下
E0523 10:38:08.181965    3104 handler.go:96] 127.0.0.1:56852 Filter RoundTrip *g
ae.Filter error: http: invalid Read on closed Body
很想知道这个Filter的错误到底是怎么产生的？能避免么，虽然基本上没感觉有影响使用的~

最后说一句，因为翻强而产生如此多的同好，这也是一大奇观。

**Comment by SeaHOH** [comment]
你经常看视频，而且没看完就关闭？

**Comment by ashi876** [comment]
呃，你一说好象是这么回事。

**Comment by SeaHOH** [comment]
那就对了，这是正常记录，只是社长没有分得太细，成了红色。

**Comment by yDan** [comment]
社长太厉害了，写了个goa、gop出来，而且速度还挺不错的。搞到我也想去学习编程了。现在做平面设计，觉得一点前途(钱途)都没有。一定要有维护者，要是社长又被请喝茶了，逼得不已删除源代码的话，一定要有后续的维护者才行，不然怎么长久。你看ss作者被请喝茶了，原作者也不在维护ss了。但是它有后续的新人继续维护开发。

**Comment by phuslu** [comment]
翻墙软件的编写难度其实不大，难的是在于持之以恒的投入时间和精力做。

换用 go 语言来做，是因为我想看看用传说的本地语言来做 GAE 代理究竟能获得多大好处。当时评估了 go, lua, rust, erlang 还有 ocaml，最后选择 go. 目前来说效果还不错。（如果重来的话，或许会选 rust...)

至于喝茶，上次我认怂比较快，所以还好。我估摸着，只要 goproxy 没有获得大的影响力，应该不会再喝了。（天知道会不会立 FLAG。。。）

**Comment by SeaHOH** [comment]
好多评价说 Rust 比较坑，Mozilla 在玩概念吹牛，实际效果不大。

**Comment by phuslu** [comment]
我工作中用 ocaml 多一些，比较认同内存安全这个概念。rust 已经是做的挺好的一个实现，社区的成熟速度也比我心中预料的好和快。

比如这个项目， https://github.com/ctz/rustls 一个语言如果能从头实现 ssl 的话，我觉得已经接近可用了。

**Comment by SeaHOH** [comment]
Mozilla 还算有钱，又忽悠了一群人的感觉。只希望能稳定点，不要做一下就又放弃了。

**Comment by phuslu** [comment]
嗯，在我看来， rust 算是函数式语言(ocaml/haskell) 在现代编程语言的投射。不会太流行，但是在某些领域能够达到性能的极限，替代 c/c++ 的位置。

至于 go, 它的实现只能到达对标 java 的程度。

**Comment by SeaHOH** [comment]
社长关注的是技术，我只希望 Mozilla 不要又搞得开发者和用户都嫌弃它。
