### ISSUE TITLE
goproxy-vps 服务端错误

### ISSUE THREAD

**Issue by tiany520** [phuslu/goproxy#1750]
F0523 16:54:00.598584 2811 goproxy-vps.go:1044] Listen(:443) error: listen tcp :443: bind: address already in use
很莫名其妙 我以为是系统问题 又把VPS还原了 再配置来安装 还是显示这个错误 查看了端口占用 也就是 goproxy-vps 进程用了 443 端口

直接https://我的域名 访问失败 确认了是端口并未打开
后来改端口到 8080 还是访问不了

**Comment by tiany520** [comment]
搞定了 原来是因为没有把防火墙打开 一直再折腾 死活链接不上去

**Comment by kirbyzhu** [comment]
搞定就close吧
