### ISSUE TITLE
GP一运行就闪退

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#176]
GP版本：windows_386-r166
电脑：Win7 SP1, 32
对json的修改：按照“fh0205z...@gmail.com”的简略教程，修改了iplist.json（添加了ip——一行一个，加英文双引号，后面加英文逗号），gae.json（添加了appids，格式如前面的iplist），main.json【也跟上面写的一样】

情况：如果是刚下载的，没有编辑的，不会闪退；编辑后，立刻闪退。

**Comment by dfdragon** [comment]
json不是非得要一行一个的。我估计是你修改后的格式不对，仔细检查一下，或者用json在线工具检查一下。

**Comment by xyuanmu** [comment]
无论是id还是ip最后一个后面是没有半角逗号的

**Comment by Yamazaki-wu** [comment]
格式：“APPID-1","APPID-2","APPID-3"   最后一个引号后不要加英文的逗号了。
”1.2.3.4“,"2.3.4.5","3.4.5.6"    同样不要加

**Comment by blob2015** [comment]
感谢以上三位，我看了一下，最末的没有加逗号。不过我用//与/**/注释掉了部分，这个可以的吧？
明天我稍微处理下，把相关的json文件粘贴一下。

**Comment by dfdragon** [comment]
JSON的标准语法是不带注释的。我猜测会不会是goproxy的JSON解释器不认/**/格式

**Comment by blob2015** [comment]
GAE.JSON
---------------
{
	"appids": [
		//"goagenta"
		"xxx1",
		"xxx2",
		"xxx3",
	],
	"scheme": "https",
	"domain": "appspot.com",
	"path": "/_gh/",
	"password": "",
	"sslverify": false,
	"transport": "iplist",
	"sites": [
		"*"
	],
	"autorange": {
		"threads": 3,
		"maxsize": 1572864,
		"bufsize": 8192,
		"sites": [
			"*.atm.youku.com",
			"*.c.docs.google.com",
			"*.c.youtube.com",
			"*.d.rncdn3.com",
			"*.edgecastcdn.net",
			"*.googlevideo.com",
			"*.mms.vlog.xuite.net",
			"*.x.xvideos.com",
			"*av.vimeo.com",
			"archive.rthk.hk",
			"cdn*.public.extremetube.phncdn.com",
			"cdn*.public.tube8.com",
			"cdn*.video.pornhub.phncdn.com",
			"s*.last.fm",
			"smile-*.nicovideo.jp",
			"video*.modimovie.com",
			"video.*.fbcdn.net",
			"videos.flv*.redtubefiles.com",
			"vs*.thisav.com",
			"x*.last.fm"
		],
		"suffixs": [
			"*.avi",
			"*.dmg",
			"*.f4v",
			"*.flv",
			"*.hlv",
			"*.iso",
			"*.m4v",
			"*.mp3",
			"*.mp4",
			"*.ogg",
			"*play*"
		]
	}
}

**Comment by blob2015** [comment]
IPLIST.JSON
---------------
{
	"dialer": {
		"Window": 6,
		"Timeout": 8,
		"KeepAlive": 180,
		"DualStack": false
	},
	"transport": {
		"DisableKeepAlives": true,
		"DisableCompression": false,
		"TLSHandshakeTimeout": 8,
		"MaxIdleConnsPerHost": -1
	},
	"hosts": {
		"dl.google.com": "google_cn",
		"talk.google.com": "google_talk",
		"talk.l.google.com": "google_talk",
		"talkx.l.google.com": "google_talk",
		"*.appspot.com": "google_hk",
		"*.ggpht.com": "google_hk",
		"*.google-analytics.com": "google_cn",
		"*.google.cn": "google_cn",
		"*.google.com": "google_hk",
		"*.google.com.hk": "google_hk",
		"*.googleapis.com": "google_hk",
		"*.googlecode.com": "google_hk",
		"*.googlegroups.com": "google_hk",
		"*.googletagmanager.com": "google_hk",
		"*.googletagservices.com": "google_hk",
		"*.googleusercontent.com": "google_hk",
		"*.gstatic.com": "google_hk"
	},
	"iplist" : {
		"google_talk": [
			"talk.google.com",
			"talk.l.google.com",
			"talkx.l.google.com"
		],
		"google_cn": [
			"www.g.cn",
			"www.google.cn"
		],
		"google_hk": [
			"1.255.22.203",
			/*"googleapis.l.google.com",
			"cert-test.sandbox.google.com",
			"googlecode.l.googleusercontent.com",
			"maps.l.google.com",
			"code.l.google.com",
			"mail.l.google.com",
			"mail.google.com",
			"www.google.com.hk",
			"www.google.com.tw",
			"www.l.google.com",
			"www2.l.google.com",
			"www3.l.google.com",
			"www4.l.google.com",
			"www5.l.google.com",
			"www.google.com"*/
		]
	},
	"dns": {
		"servers": [
			"114.114.114.114",
			"114.114.115.115",
			"168.95.1.1",
			"168.95.192.1",
			"178.79.131.110",
			"199.91.73.222",
			"2001:470:20::2",
			"2001:4860:4860::8844",
			"2001:4860:4860::8888",
			"208.67.220.220",
			"208.67.222.222",
			"209.244.0.3",
			"209.244.0.4",
			"223.5.5.5",
			"223.6.6.6",
			/*"8.8.4.4",
			"8.8.8.8"*/
		],
		"blacklist": [
			"183.207.229.*",
			"183.207.239.*"
		],
		"expand": [
			// "google_hk"
		]
	}
}

**Comment by blob2015** [comment]
MAIN.JSON
---------------
{
	"logtostderr": true,
	"Addr": "127.0.0.1:8000",
	"http": {
		"mode": "h1",
		"KeepAlivePeriod": 0,
		"ReadTimeout": 600,
		"WriteTimeout": 3600,
		"Certificate": "goproxy.pem",
		"PrivateKey": "goproxy.key"
	},
	"groupcache": {
		// "addr": "127.0.0.1:10080",
		"peers": [
			"http://127.0.0.1:10080"
		]
	},
	"filters": {
		"request": [
			// "auth",
			"stripssl"
		],
		"roundtrip": [
			"autoproxy",
			"gae",
			//"iplist",
			"direct",
			"auth",
			"vps",
			"php"
		],
		"response": [
		]
	}
}

**Comment by blob2015** [comment]
以上是改动过的3个JSON文件，请大家帮忙看看，是那里除了岔子？
谢谢！

**Comment by dfdragon** [comment]
![qq 20150908125713](https://cloud.githubusercontent.com/assets/9766935/9726707/4a6ae5c2-5629-11e5-9ec5-b8a89ec3929b.png)
这里是不对的。1.注释格式错误；2.注释后的"223.6.6.6"后面多了一个逗号。

同样的错误也出现在google_hk里。

**Comment by xyuanmu** [comment]
楼上说的对，而且注释符号错了，多行应该是 /*  */ 注释而不是双斜杠，正确的注释是这样的：
```json
"servers": [
"114.114.114.114",
"114.114.115.115",
"168.95.1.1",
"168.95.192.1",
"178.79.131.110",
"199.91.73.222",
"2001:470:20::2",
"2001:4860:4860::8844",
"2001:4860:4860::8888",
"208.67.220.220",
"208.67.222.222",
"209.244.0.3",
"209.244.0.4",
"223.5.5.5",
"223.6.6.6"/*,
"8.8.4.4",
"8.8.8.8"*/
],
```

**Comment by blob2015** [comment]
感谢dfdragon与xyuanmu
我改一下试试

**Comment by cnv5** [comment]
肯定是格式有问题，找到了就可以了

**Comment by blob2015** [comment]
@phuslu 
不支持/* */注释吗？
发现把这种注释删掉就不会闪退了
