### ISSUE TITLE
goproxy和gae间https通信是不是没有验证？  另外提醒一下大家查水表的事情

### ISSUE THREAD

**Issue by greershot** [phuslu/goproxy#1763]
关于查水表(部分地区)，我想提醒下大家。可能大家还不清楚网上流传的脑控到底是什么。

脑控是超声类远距离扬声器导致受害人幻听，然后24小时不间断传声骚扰。（真实经历确认）
为什么只有受害人幻听，周围人没不幻听？超声类高频声波在不同体质人体衰减不同，而且幅度小，如果不是衰竭后作用在头部而是其他部位，一般人根本感觉不到。

不管有没有被这类技术骚扰，希望作者和大家多注意吧！@phuslu

**Comment by jasonliul** [comment]
求助心理医生去罢~

**Comment by EMLVIRUS** [comment]
1. 远距离下声波意义有限，见于多普勒效应
2. 体质对于人体物理结构影响极小，一般影响的是内环境的化学性质
3. 超声的基本特征之一就是振幅大

**Comment by EMLVIRUS** [comment]
@phuslu pls lock & close this issue

**Comment by greershot** [comment]
@EMLVIRUS  一些很无聊的issue都没close，为什么要close我的issue。

**Comment by greershot** [comment]
@EMLVIRUS   LRAD 2000X的有效距离都有3-5公里

**Comment by wpyok500** [comment]
自寻烦恼

**Comment by 523860169** [comment]
工作压力太大，睡眠时间太少，又缺乏运动，精神状态不好，周围电器太多，都可能差生幻听，你还是去看医生吧

**Comment by yDan** [comment]
你得了憂鬱症吧？

**Comment by yDan** [comment]
你得了忧郁症吧，思觉失调？

**Comment by MeABc** [comment]
这帖貌似要火。嘎嘎！！！

**Comment by SeaHOH** [comment]
我有耳鸣，一年多了，遗传的，但这两年作息不太规律是诱因。

**Comment by jasonliul** [comment]
@SeaHOH 
你夜夜找些饥渴少妇扶贫, 这是战争创伤~

**Comment by hcym** [comment]
这家伙不像神经病
可能是@phuslu的情敌

**Comment by SeaHOH** [comment]
什么情况，有八卦？

**Comment by jasonliul** [comment]
@hcym 
严禁无事@, 社长正在樱花下食粽... 顺便野战一发~~

**Comment by SeaHOH** [comment]
j 哥小道消息忒多，说得好像你看见了似的~
明天才食粽，我今天食咸蛋。

**Comment by jasonliul** [comment]
@SeaHOH 
你已经好咸湿了~

**Comment by SeaHOH** [comment]
我认输，湿傅~

**Comment by linhua55** [comment]
@greershot 
你以为 这是 洗脑？ 就算相当于暗示、催眠，作用也微乎其微。
没事多看书，不要胡思乱想，保持一颗强大的内心。 很多病是闲出来的。   另外学会批判性思维，学会区分 事实和观点 ， 不要被别人 惊悚的不实言论  吓唬住。
https://program-think.blogspot.com/2013/05/difference-between-fact-and-opinion.html

记得在一部恐怖电影中，有把某些指令性、暗示性画面 植入到电视中，以达到暗示、催眠的目的。以正常速度看电视看不出来，只有一帧帧的看，才能看到那几帧画面。不过这是吓唬人的。 如果你有幻听的毛病，建议去 医院（耳鼻喉科） 看看，有可能只是耳鸣

**Comment by itaintbld** [comment]
我只想回复下标题，"goproxy和gae间https通信是不是没有验证？ 另外提醒一下大家查水表的事情"
#### 1，是gae到其它网站默认是没有验证的，然而，浏览器添加了goproxy的证书，，，。
所以，我建议"gae.json"的`"SSLVerify": false,`改为true。
#### 2，我想不会被天朝查，但是美国的big brother肯定看着我们。
google对每条访问记录都有追踪。
- 例如即使使用了gae，用google还是可以搜索到自己的ip的。
- 不使用gae的，http头中也会被添加一条追踪信息。

> 另外建议尽早就医。如果真有这么屌的技术，那也不会浪费在我们这些平民身上。

**Comment by qwerttaa** [comment]
日了，我一哥们儿咒我痔疮，结果没几天我就真痔疮了，是不是楼主说的脑控来着

**Comment by jasonliul** [comment]
@itaintbld 
另外建议尽早就医。如果真有这么屌的技术，那也不会浪费在我们这些平民身上。

病态自恋生暗鬼, 医生也要遁~

**Comment by itaintbld** [comment]
@jasonliul 
#### 1. gae添加了两条追踪信息。
- user_agent: 可以知道是哪个appip访问的。
- X_CLOUD_TRACE_CONTEXT: 可以知道是哪个ip访问了appid。
> 自己用纯gae模式访问这个网址看看。[https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending](https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending)

#### 2. 谷歌默认记录你帐号的所有访问信息
- google的搜索记录
- youtube的观看记录等等
- 其它所有google的应用
> 如果你用谷歌的帐号，自己访问[https://myactivity.google.com/myactivity](https://myactivity.google.com/myactivity)看看你几年前都干了什么好事？

#### 3. 谷歌还是不错的
至少告诉你它在记录，不像百度。

最后，感谢斯诺登，他是英雄。

**Comment by MeABc** [comment]
唠叨几句。

> gae添加了两条追踪信息。。。等等

怎么还在纠结这个呢，gae 只是用来翻墙的（代理/proxy），它不是匿名工具。这应该用之前就应想清楚或者说是必须了解的。这么多人这么多年过去了，为什么还在用，难道就没有一个人知道吗？！不见得吧。

N 年前炒得很火的证书问题，多大点儿事儿啊----非得把 gae 当成匿名工具，那这个就是天大的事；如果把 gae 当成如免费的 SS 这些代理，那大家都是一样的，一样会被记录。我很奇怪的是，其它免费代理都没见到 N 年如一日的这样被提到隐私问题。是不是把  gae 看得太高，抬得太高了。要人家免费的东西，还在指望别人不要记录，是不是在自欺欺人。如注册个扣扣号，还要求企鹅不要看我们的聊天记录，这话儿说出去我们自己信吗？！

不就是一个普通的免费代理工具吗，非得要加入一些政治道德因素进来，才显得我们很高大尚吗？

又如度娘与狗哥，就我而言，用狗哥能找到资料，用度娘就找不到，无关国家，无关政治，无关道德。

**Comment by starobots** [comment]
楼主是不是有精神障碍？
合着去医院的人，周围都没得病，就他得病了，都是政府操控他得病？

精神医学领域，认为有些宣称自己被“脑控”的人其实更可能是下面几种情况：
　　被害妄想：患者无中生有地坚信周围某些人或某些集团对患者进行打击、陷害、谋害、破坏等不利的活动。加害的方式有多种多样，可以是施毒、监视、跟踪、搞阴谋、造谣诽谤、以非人道的方式用患者做试验、控制病人的思想、行为或性冲动等。　　
　　物理影响妄想：一种认为自己的思想、情感或身体均被外界力量控制和干扰的病态观念。这种外界力量常被称为电波、超声波、激光等现代先进技术，病人认为自己的一切均受到外力的控制、操纵，自己无力违抗，如患者觉得自己的大脑被电脑控制，自己是机器人，同时可因这种电波或仪器干扰而有身体不适的感觉。此症状是精神分裂症的一种特征性症状。　　
　　内心被揭露感：俗称读心症，病人认为他所想的事已被人知道，虽然病人说不出是怎样被人探知的，但确信已经尽人皆知，甚至搞得满城风雨，所有的人都在议论他。
　　这些类型症状与以往普通精神疾病患者的表现并没有差异。患者称“自己被思维被控制，被植入思想，产生命令性的幻听”等症状都是以前普通精神病常见的症状。
