### ISSUE TITLE
前置搜刮检测: HellLabs Proxy Checker/ Gather Proxy Premium 8.9.0 

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1764]
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/26538175/442ba7da-4477-11e7-9522-042a8725efee.jpg)
前置检测经典: 乌克兰 HellLabs Proxy Checker 

Proxy Checker Personal 7.4.18
https://yadi.sk/d/mgPvb-cuaYuij

Proxy Checker Pro 7.4.12
https://yadi.sk/d/3tseiFuRaYudc

原网站代理评估已经玩完, 因此评估网站可以填写:
http://proxyjudge.us/judge.php

4行相同, 或者你也可以搜索其他代理评估网站.

注意: 如果使用4个不同的评估网站, 无必要的项目都要取消, 不然会很慢.
例如只检测袜子, http相关的项目都取消.

该程序会自动连接代理评估[预检测], 要等黄色箭头可见, 再点击测试.

其他
**EPS**
https://www.eliteproxyswitcher.com/

**SPC**
https://www.socksproxychecker.com/

**Comment by jasonliul** [comment]
101.200.151.23:1080
101.231.249.202:1080
106.110.119.159:1080
106.39.162.168:80
106.75.137.20:20000
112.124.50.85:1080
112.124.57.223:1080
112.90.51.50:4130
112.93.64.139:1080
115.29.161.167:1080
116.231.49.49:1080
118.114.242.106:1080
119.254.100.120:8091
120.198.151.4:1080
120.234.15.130:1080
120.24.245.193:1080
120.24.245.193:1080
120.26.206.178:8888
121.40.208.69:1080
122.192.32.74:7280
122.192.32.76:7280
122.192.32.77:7280
122.4.254.54:1080
122.7.88.41:1080
123.56.199.152:3641
123.56.199.203:5271
123.56.200.75:5261
123.57.132.192:1080
123.57.132.192:1080
123.59.100.243:1080
123.59.100.245:1080
123.59.100.246:1080
123.59.100.253:1080
124.161.16.92:1080
124.161.16.93:1080
124.207.126.15:1080
124.237.112.100:1080
124.42.118.60:1080
124.93.222.95:8080
125.72.125.14:1080
125.93.75.245:1081
180.153.87.22:10080
180.153.87.22:10080
180.173.223.104:1080
180.173.223.104:1080
182.92.225.78:1080
182.92.225.78:1080
182.92.225.79:1080
218.201.98.196:1080
218.58.52.158:1088
218.58.52.158:1088
221.203.169.50:1080
221.214.208.226:1080
221.6.206.114:1080
222.133.16.134:1080
222.133.16.134:1080
222.90.134.210:9000
222.90.134.210:9000
223.241.116.86:1080
223.241.117.152:1080
49.51.36.187:1080
58.20.41.172:1080
58.241.32.186:1080
59.37.163.176:1080
59.63.248.182:1080
60.167.112.107:1080
60.167.112.107:1080
60.169.114.155:1080
61.129.70.109:1080
61.135.155.82:1080
61.135.155.82:1080
61.141.21.34:1080
61.177.248.202:1080

一些中国ip袜子, 自己测试

**Comment by SeaHOH** [comment]
hunter 早就不更新了，这个似乎也是。

**Comment by jasonliul** [comment]
@SeaHOH 
就这样了, 还要怎么更新? 这类技术成熟好多年了.
现在越南同志比较热衷~

**Comment by SeaHOH** [comment]
就是觉得个别 UI 和设置不是很顺手了。

**Comment by jasonliul** [comment]
@SeaHOH 
这个和猎手, 还是太在乎http代理.

现在网站在线检测不可靠, 因为国内无事阻塞一些ip --无法连接.
只好老将出马, 圣诞树, 也得发光~

**Comment by tec1987** [comment]
让我想起了当年的代理猎手、代理超人、花刺等。。。

**Comment by jasonliul** [comment]
@tec1987 
哇噻, 你跟我一样, 白胡子老爷爷~

**Comment by kirbyzhu** [comment]
用过这些就是白胡子老爷爷？那我可能更老一些

**Comment by Kisesy** [comment]
厉害了，话说我一样也没用过。。。

**Comment by jasonliul** [comment]
@Kisesy 
主任不能只养膘, 不时也得过来喝一杯~

**Comment by tec1987** [comment]
@jasonliul 俺是黑胡子的青壮年。。。

@kirbyzhu 说说为什么更老？

**Comment by kirbyzhu** [comment]
看看你的id就知道了 我比你老一个年代

**Comment by tec1987** [comment]
看来我得注册个不暴露年龄的账号了。。。

**Comment by AndyLau2017** [comment]
用中国的袜子不安全吧，毕竟服务器都在国内。

**Comment by kirbyzhu** [comment]
在arukas上部署个gost 然后本地数据sockes转发 做gp的前置 速度还行

**Comment by AndyLau2017** [comment]
不知道是我哪里不对，J大发的那一堆中国袜子，只有两个可用，而且还有一个是超慢的。

**Comment by jasonliul** [comment]
@AndyLau2017 
现在是月尾月初. :)

**Comment by jasonliul** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/26775843/43e2e38c-4a09-11e7-9f9d-7a89e6fa8051.jpg)
HPC还需要帮手...
http://www.proxifier.com/proxychecker/

逐一细查必须的, 可以显示丢包率.

**Comment by jasonliul** [comment]
一点中国袜子
119.28.15.252:2018

124.161.16.94:1080
124.239.177.85:1080
106.14.46.60:1080
180.173.223.104:1080
112.124.35.165:1080
43.241.224.18:8080
61.157.198.66:1080
123.59.100.243:1080
180.76.132.5:1080
115.182.255.234:1080
124.42.118.60:1080
120.133.6.6:9065
112.124.57.223:1080
101.203.174.209:1080
61.163.39.70:1080
59.78.17.137:1080
103.3.120.19:1080
61.177.248.202:1080
115.29.161.167:1080
124.207.126.15:1080
222.188.10.1:1080
222.133.16.134:1080
123.59.100.245:1080
123.59.173.0:1080
120.26.206.178:8888
101.201.233.38:1080
123.56.200.75:5261
123.56.199.152:3641
61.129.70.109:1080
106.75.137.20:10092
120.234.15.130:1080

**Comment by jasonliul** [comment]
**Socks Proxy Checker 1.16** 
 https://www.socksproxychecker.com/

Download
https://www.socksproxychecker.com/SPC_setup.exe 
检测袜4并不好

**Comment by blob2015** [comment]
mark一下

**Comment by AndyLau2017** [comment]
@jasonliul  start按钮是灰色的，是什么情况呢？J大

**Comment by blob2015** [comment]
@jasonliul 
J哥，你用的什么系统啊？俺的win7/32，这个start按钮，也是灰色的啊
另外，好ProxyHunter 3.1，不识别utf字码啊
继续测试J哥推荐的其他一些家伙
😀 
![hs0074](https://user-images.githubusercontent.com/12381704/27379810-5052e5d8-56af-11e7-9768-1c489c456b0a.png)

**Comment by jasonliul** [comment]
45.33.54.195 proxyjudge.us 
加入hosts文件

**Comment by blob2015** [comment]
@jasonliul 
多谢J哥，目前正在用Socks Proxy Checker战斗，总算搞了几个，还以为绝缘呢 😀 
![hs0075](https://user-images.githubusercontent.com/12381704/27380482-e0706f76-56b1-11e7-9ed2-7b6d510b75f6.png)

**Comment by jasonliul** [comment]
http://proxysearcher.sourceforge.net/Proxy%20List.php?type=socks&filtered=true
滚动检查.

之前推过**Gather Proxy**, 自动搜刮检测, 不过不能检测袜4

**Comment by blob2015** [comment]
@jasonliul 
多谢J哥
不过Gather这货，是不是跳出个弹窗，这个倒也算了，那个说是可以下载list，nnd，下载下来是不知道什么的html文本，没有看到半个list，或者刚好遇到了它的大姨妈？ 😀 
正在尝试加挂袜子，感觉还行 😀

**Comment by jasonliul** [comment]
![sr0z8df](https://user-images.githubusercontent.com/2461165/27381251-b702d608-56b4-11e7-8896-05e57a264692.png)

[GatherProxy Premium 8.9.0.zip](https://github.com/phuslu/goproxy/files/1091295/GatherProxy.Premium.8.9.0.zip)

**Comment by blob2015** [comment]
@jasonliul 
Proxy Checker 7.4已经可用
多谢J哥

**Comment by AndyLau2017** [comment]
我感觉搜出来的袜子，很多速度都好慢，不知道是不是我方法不对

**Comment by zhangyz1997** [comment]
@jasonliul J大,我想问一下为什么我用Gather Proxy的时候CPU占用率会突然升高然后一直降不下来,整个程序也会很卡顿,如果不在任务管理器里设定相关性的话就会彻底死机

**Comment by AndyLau2017** [comment]
@zhangyz1997  这种问题难道不是应该去问官方吗

**Comment by jasonliul** [comment]
@zhangyz1997 
那是.net frameworks支持的问题, x64比较常见.

**Comment by zhangyz1997** [comment]
兼容性设过了,还是卡,不过搜袜子不卡,已经换用SPC
还是谢谢J大

**Comment by jasonliul** [comment]
Elite ssl
159.8.114.37:8123
136.144.129.163:8888
35.186.191.176:80
35.188.234.181:80
35.188.233.199:80
35.186.187.102:80
35.185.121.98:80
35.185.99.214:80
104.196.101.67:80
104.198.9.77:80
35.186.162.20:80
104.196.52.107:80
35.185.19.89:80
104.196.175.206:80
149.56.227.84:3128
173.192.21.89:8123
35.186.184.113:80
35.186.167.174:80
35.186.183.91:80
35.186.171.16:80
35.186.188.64:80
35.188.228.12:80
35.188.234.106:80
35.186.184.23:80
35.186.180.97:80
35.186.184.187:80
35.185.45.192:80
35.186.167.58:80
104.196.62.163:80
104.196.68.117:80
35.185.82.112:80
35.186.180.71:80
50.56.184.166:80
151.80.79.89:808
173.192.128.238:8123
35.186.174.3:80
35.185.118.248:80
180.148.33.29:80
64.137.234.25:3128
119.81.71.27:8123
178.62.64.37:8118
46.101.47.42:8118
188.166.144.79:8118
35.186.190.81:80
46.101.22.252:8118
119.81.71.27:80
64.15.156.151:80
181.65.239.105:3128
50.31.14.151:8124
151.80.126.12:808
138.68.151.208:8118
138.68.178.130:8118

**Comment by jasonliul** [comment]
![1 png](https://user-images.githubusercontent.com/2461165/27898693-aba44b56-6259-11e7-8506-d473c23581c4.png)
真正的袜子玩具~~ :)

**Comment by tec1987** [comment]
老兄居然换头像了。。。
俄罗斯大叔![image](https://user-images.githubusercontent.com/23297763/27907207-521af6dc-6279-11e7-9d03-d9bc24856f94.png)

**Comment by jasonliul** [comment]
@tec1987 
以前那个太中年~~
:)

**Comment by Just2co** [comment]
@jasonliul 我用的SCP，检测的结果非常准，测试速度也比较快，中国的一些袜子速度是最快的，其次就是香港、日本，你说的巴西最近比较快，我这里测试好几个都比较慢，真是太给力了，袜子居然能让goproxy青春焕发！https代理，能放进去不？改成https://43.23.23.32:443 这种形式的？

**Comment by jasonliul** [comment]
@Just2co 
你得问社长. 
通常是写成http://43.23.23.32就行

**Comment by jasonliul** [comment]
玩袜子的基本原则是带宽大于ping值, 满速的400ms也不错.
一旦建立连接, 会象填鸭一样灌输数据过来~~~
