### ISSUE TITLE
这什么情况？看youtube老是断断续续的！！！

### ISSUE THREAD

**Issue by yDan** [phuslu/goproxy#1766]
![qq 20170531095734](https://cloud.githubusercontent.com/assets/21190788/26612772/6599a1c4-45e9-11e7-89bb-019bf9c40f41.png)
![qq 20170531100936](https://cloud.githubusercontent.com/assets/21190788/26612777/6ecbb6d8-45e9-11e7-9155-7e6d47a2ec09.png)

**Comment by phuslu** [comment]
「over quota」了
