### ISSUE TITLE
这什么意思？Youtube 经常断流？

### ISSUE THREAD

**Issue by yDan** [phuslu/goproxy#1767]
![qq 20170531133807](https://cloud.githubusercontent.com/assets/21190788/26617493/fb80b6d2-4607-11e7-805b-5ef94e10a9de.png)

**Comment by phuslu** [comment]
请勿重复发帖  https://github.com/phuslu/goproxy/issues/1766

**Comment by yDan** [comment]
社长，不好意思，不是你说的那个没流量。我重新申请几个新的appid，放上去也是这种情况。应该不是没流量吧，因为我觉得问题还存在，还没解决。我就重新发了。要是你觉得我是重复发的，那我就不发了。不好意思。

**Comment by MeABc** [comment]
不是不让发，是你重复发帖。相关问题在一个帖子里跟帖就好。

是不是你的 appid 太少了。另外，你放新的 APPID 
进去后，日志还是会出现，有可能也是原来的那几个“超额”的 APPID 
。注意看下是不是这种情况。

“断断续续”有可能是 IP 质量问题，近期不是有很人分享 googleip 
吗，用上再说，先不要管别人是怎么搞来的。有些问题不是一两就可以搞明白的。像盾阵，我想了几年都没想明白。。。。

**Comment by yDan** [comment]
@MeABc 好，谢谢。

**Comment by MeABc** [comment]
如再有相关问题，可以在这里跟帖，帖子关了也是可以看到的。

在 2017/5/31 14:31, yDan 写道:
