### ISSUE TITLE
罗马利亚 ChrisPC Anonymous Proxy

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1768]
![chrispc_anonymous_proxy_main_settings png](https://cloud.githubusercontent.com/assets/2461165/26706755/59508aec-4772-11e7-9e46-f2ee0193624a.png)

ChrisPC Anonymous Proxy
http://proxy.chris-pc.com/
免费匿名代理, 使用Tor节点, 速度一般般. 有几个弹窗.

破解版本容易失效.

**Comment by qwerttaa** [comment]
和直接用tor有啥区别呢？直接用tor不就好了啊~

**Comment by Kisesy** [comment]
这个经典啊

**Comment by jasonliul** [comment]
@Kisesy 
俺也不确定主任是否能够去掉弹窗?

但是破解版不仅麻烦, 而且失效也快

**Comment by Kisesy** [comment]
@jasonliul 破解它倒是不难，不过不知道是不是真破解，弹窗我没看到，就不弄了
[ChrisPC Proxy_.tar.gz](https://github.com/phuslu/goproxy/files/1046589/ChrisPC.Proxy_.tar.gz)

**Comment by jasonliul** [comment]
@Kisesy 
SND的破解
http://www.mirrorcreator.com/files/DYZXEBF7/Chris-PC.Anonymous.Proxy.Pro.v7.05.Keygen-SND_0.rar_links

麻烦就是, 还得防火墙屏蔽IP 86.105.152.166.
现在显示还是pro版本, 但是实际上无法连接.

**Comment by Kisesy** [comment]
@jasonliul SND的注册机，你那能用吗，可以连接？

**Comment by jasonliul** [comment]
@Kisesy 
不能, 跟你的一样, 死活不连接, 
相反免费版还不错, 连接快, 也有7,8 M的样子

**Comment by Kisesy** [comment]
@jasonliul 那就搞错对象了

**Comment by jasonliul** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/26710155/80f9a746-478a-11e7-9909-287fe6ce9594.jpg)

@Kisesy 
俺这里勉强可以, 3,4M.
不过可以袜子前置. :)

**Comment by jasonliul** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/2461165/26710994/06e3862e-4790-11e7-973a-ada6589a977a.jpg)

免费版偶尔弹窗~

**Comment by jasonliul** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/26711967/b10a1e14-4796-11e7-89c4-e80e2ffedffe.jpg)

**Comment by Kisesy** [comment]
@jasonliul 好吧，免费版去弹窗.
说实在的这弹窗实在是难去，麻烦的很，不好搞，后来想了想，把免费版弄成pro版不就行了，还真行....
[ChrisPC Proxy.tar.gz](https://github.com/phuslu/goproxy/files/1046768/ChrisPC.Proxy.tar.gz)

**Comment by kirbyzhu** [comment]
好像连不上

**Comment by jasonliul** [comment]
@Kisesy 
哇靠, 这么邪恶的急转弯..........
刚刚测试, 好像没有弹窗了.

基本都在刚刚开始用的时候弹窗.

**Comment by candy2107** [comment]
用不了......
![jt](https://cloud.githubusercontent.com/assets/28686933/26721371/2c32130e-47be-11e7-8c1c-1c9b3b370330.png)

**Comment by candy2107** [comment]
@Kisesy 点击 connect to proxy 弹出这对话框,怎么回事?

**Comment by Kisesy** [comment]
@candy2107 先装原文件，我发的第一个，需要装 Pro 版，第二个对应 Free 版，然后覆盖

**Comment by candy2107** [comment]
秒懂!

**Comment by jasonliul** [comment]
![screenshot 1](https://user-images.githubusercontent.com/2461165/26910450-792be5f2-4c39-11e7-89cc-05fa18ed25ce.jpg)
瑞士节点+袜子

**Comment by jasonliul** [comment]
**v 7.15**
http://www.chris-pc.com/files040/setup_chrispc_free_anonymous_proxy_7_15.exe

更新套套文件

**Comment by jasonliul** [comment]
@Kisesy
主任, 又要劳烦你~~~

嘢, 胖虎哥又出去猎艳鸟...................

**Comment by kirbyzhu** [comment]
以前版本不支持win10？难怪我一直连不上

**Comment by Kisesy** [comment]
这次我这终于连上了，还是需要前置，而且后面还背了个tor，速度可想而知..... :trollface: 
[ChrisPC Proxy2.tar.gz](https://github.com/phuslu/goproxy/files/1067832/ChrisPC.Proxy2.tar.gz)

**Comment by jasonliul** [comment]
@Kisesy 
俺这里最好的时候9M, 最差就2M

**Comment by Kisesy** [comment]
![image](https://user-images.githubusercontent.com/5843694/27031300-57614b44-4fa2-11e7-9ea2-f0c131017a85.png)

看起来pro版并不好搞，也许是网络验证，比如试用版可以获取地址信息，不过要是破解的话，就是ERROR了
看看snd那帮人能不能搞，毕竟我的水平差他们太远了

**Comment by jasonliul** [comment]
@Kisesy 
这类软件名堂可以加在服务端...

Hide All IP刚刚被搞得不能破解, 不过有loader

**Comment by Kisesy** [comment]
@jasonliul 所以一般像vpn之类的都没人搞，也搞不定，因为你破解只能改动客户端，服务端都验证不了，都不给流量，也是白破解

不过以前的时候有个代理，还是可以破解的，因为它的验证很傻，它验证服务端传回来的数据，判断能不进 vip 通道

而这个数据就是个json，类似 "isVip": "false"，我就写了个hook，启动时候注入客户端，

等连接时服务端传回数据的时候改成 true，就过了，就这样用了几个星期，然后就不行了，因为作者改验证了，改成交钱试用了

那时候它是我第一个用着爽的代理，后来我就用 goagent 了，现在想想....

我用 goagent 的时间也是我给 goagent 提交代码的时间，那时候我才学 python 几个月, 什么都不会, 连 socket 都没用过
那也是我第一次提交代码，那时候杰哥还把我认成女社长 :trollface:

**Comment by Kisesy** [comment]
![image](https://user-images.githubusercontent.com/5843694/27032647-788707a4-4fa8-11e7-8ee9-9a8f131d669f.png)
嘿嘿，这是最骚的

**Comment by candy2107** [comment]
@Kisesy @jasonliul 
原来你们都是从GoAgent时代跟着社长一路走过来的,很了不起.
话说现在ssr开发者发福利,最新版ssr内置了数十个免费服务器,不用g组q群签到了,J哥不能错过这个啊

**Comment by SeaHOH** [comment]
J 哥早没救了，看谁都是妞。 :trollface:

**Comment by jasonliul** [comment]
@SeaHOH
俺是佛眼, 见人都是妞........
无差别心.

善哉~

**Comment by jasonliul** [comment]
@Kisesy
俺最早是玩ssh的, 上次爱沙尼亚那几个变态, 疯狂破解全球ssh密码的时候, 费事搞到那一份, 号称30万, 好用的7,8千. 基本等同商业化ssh. 全球都有. 也是去年狂增ping值, 加大丢包率, 搞得最后那100多节点也基本废掉了. 现在基本都加挂袜子.

不过俺还有一枚白金澳门节点直连满速. 原来破墙最薄是Macao. :)

**Comment by kirbyzhu** [comment]
前面加gost做袜子，终于能让状态切换到on，速度还是不行。而且只要登录google就永远是验证。

**Comment by kirbyzhu** [comment]
看来还是rondom国家的缘故，指定国家会好一点

**Comment by jasonliul** [comment]
@kirbyzhu 
http://ss.fq24.cn/

用风起就是...
欧美节点强过亚洲, 不要盯着港日星

**Comment by kirbyzhu** [comment]
@jasonliul ssh能多个服务端并发负载均衡么？

**Comment by jasonliul** [comment]
@kirbyzhu 
印尼人做过, 就是做Klephon那家伙

**Comment by kirbyzhu** [comment]
@jasonliul 我用的是自己部署在arukas上的gost 应该和风起的速度差不多

**Comment by jasonliul** [comment]
@kirbyzhu 
还是那些伪中国ip的袜子是最优, 不过今天周一, 精尽休整~~

**Comment by jasonliul** [comment]
![screenshot 1](https://user-images.githubusercontent.com/2461165/27118190-ca6c7710-510c-11e7-925c-2e2a2efcc960.jpg)
更新到新版洋葱7.5a的文件,表现似乎更好一点...

台湾袜子+德国节点
