### ISSUE TITLE
IPList转换程序

### ISSUE THREAD

**Issue by dfdragon** [phuslu/goproxy#177]
做了一个简单的转换程序，支持goagent格式和goproxy格式的相互转换，下载链接：http://pan.baidu.com/s/1sjLx7Jn
大家可以试试看。

**Comment by xyuanmu** [comment]
测试了下，转换很快，不错，谢谢分享。

**Comment by zhhzq** [comment]
如何换行？是不是不换行也能使用？

**Comment by dfdragon** [comment]
不需要换行的

**Comment by Yamazaki-wu** [comment]
挺不错的，收下了！谢谢楼主的帮助

**Comment by ARwMq9b6** [comment]
Ｔｈａｎｋ　ｙｏｕ　！！！

**Comment by thundery1** [comment]
这个好,来感谢顶下楼主

**Comment by dlsflh** [comment]
不错

**Comment by lefantian** [comment]
谢谢分享！先收藏。

**Comment by aOJzQT** [comment]
自学了点Python，写个转换起来更简单，贴主是用C++写的吧

```python
#! /usr/bin/python
# -*- coding: utf-8 -*-

import os
import time


# 粘贴需要转换的GoAgent格式的ip到3个单引号(''')中
ip_goagent = '''

1.1.1.85|1.1.1.115|
1.1.1.112|

1.1.1.152
'''


# 粘贴需要转换的GoProxy格式的ip到3个单引号(''')中
ip_goproxy = '''


"1.1.1.85","1.1.1.115","1.1.1.152",

"1.1.1.112"
'''

# 转换方式
GOAGENT_TO_GOPROXY = 1  # GoAgent ip -> GoProxy ip
GOPROXY_TO_GOAGENT = 2  # GoProxy ip -> GoAgent ip


def convert_ip(ip_goagent, ip_goproxy, action=GOAGENT_TO_GOPROXY):
    ip_result = set()
    if action not in(GOAGENT_TO_GOPROXY, GOPROXY_TO_GOAGENT):
        raise Exception("invalid prompt, exit!")

    if action == GOAGENT_TO_GOPROXY:
        ip_list = ip_goagent.strip('|').split('|')
        bracket = '"'
    elif action == GOPROXY_TO_GOAGENT:
        ip_list = ip_goproxy.replace('"', '').split(',')
        bracket = ''

    # 将ip加到set中
    for i in ip_list:
        ip_formated = "{0}{1}{0}".format(bracket, i.strip(os.linesep))
        ip_result.add(ip_formated)

    return "|".join(sorted(ip_result)) if action == GOPROXY_TO_GOAGENT else ",".join(sorted(ip_result))


if __name__ == '__main__':
    prompt = raw_input("""
    请指定转换方式:
    1. GoAgent --> GoProxy
    2. GoProxy --> GoAgent

    """)
    flag = -1
    if prompt == "1":
        flag = GOAGENT_TO_GOPROXY
    elif prompt == "2":
        flag = GOPROXY_TO_GOAGENT
    else:
        print "无效的方式, exit!"
    result = convert_ip(ip_goagent, ip_goproxy, flag)
    filename = r"NewIP-{0}.txt".format(time.strftime("%H_%M_%S", time.localtime()))
    with open(filename, "w") as out:
        out.write(result)
        print "转换完成, 请打开文件[{0}]查看".format(filename)
```

**Comment by sundaqing1969** [comment]
@aOJzQT，编译成可执行文件，我们小白才能用，谢谢

**Comment by aOJzQT** [comment]
@sundaqing1969 源代码公开是为了让大家放心，没有恶意代码。

**使用方法**
在GoAgent的local子目录中，新建一个新文件，随便起个名，比如叫做convertip.py，或者convertip.txt，复上面的代码到文件中，保存。然后在cmd模式下，执行 `python27.exe convertip.py`

> 图：
![演示图例](https://cloud.githubusercontent.com/assets/13990565/9716758/749342c2-555c-11e5-8491-eee5dd82620e.jpg)

执行完毕后就有个文本文件生成。

**Comment by sundaqing1969** [comment]
@aOJzQT,长知识了，谢谢

**Comment by dfdragon** [comment]
@aOJzQT Delphi写的，很久不用了。没事了写写类似于这种的小工具感觉还是挺好的。

**Comment by dfdragon** [comment]
另外说一下程序大小的问题：Delphi在生成exe时，默认会将很多用不到的包(package)装进exe文件，导致exe文件庞大(本来几十K就能工作，结果现在2M多)，Delphi XE6尤甚。不过大家可以放心，程序里没有多余的代码。

我已将代码上传，开发环境：WIN7 64位 SP1，Delphi XE6 Update1下编译。 
http://pan.baidu.com/s/1uhRqu

**Comment by sundaqing1969** [comment]
@aOJzQT，我的cmd窗口的盘符不能处于“D:”状态，这怎么办

**Comment by sundaqing1969** [comment]
问题已经解决

**Comment by aOJzQT** [comment]
@sundaqing1969 
cmd窗口的路径，不需要在D盘，只需要在你GoAgent目录下的local子目录下就可以了。

一个最简单的方法:
* 进入GoAgent的local子目录
* 在windows的资源管理器地址栏里，直接输入cmd，回车就好了
![convertip](https://cloud.githubusercontent.com/assets/13990565/9718632/01d9ecac-556d-11e5-8b57-79fddbb96dff.jpg)

**Comment by aOJzQT** [comment]
@dfdragon 谢谢，不懂Delphi，自学了点Python，皮毛

**Comment by sundaqing1969** [comment]
@aOJzQT，又长知识了，谢谢你

**Comment by dfdragon** [comment]
@aOJzQT Delphi算是比较古老的语言，现在使用的人很少了，本人最初使用Delphi，现在开发环境已经转移到Java和C#。但Delphi在windows平台下开发原生程序还是很不错的，尤其是这种小程序。

**Comment by sundaqing1969** [comment]
报告@aOJzQT，我的转换不成功，我的ip有500多，转换出来只有4个，而且还不是我原来的ip

**Comment by aOJzQT** [comment]
@sundaqing1969 

那4个ip是测试用的，你需要把你自己的GoAgent ip复制出来粘贴到代码中的，位置就是3个单引号中间

```
# 粘贴需要转换的GoAgent格式的ip到3个单引号(''')中
ip_goagent = '''

1.1.1.85|1.1.1.115|
1.1.1.112|

1.1.1.152
'''
```

**Comment by aOJzQT** [comment]
@dfdragon Python对于我这种非专业小白来说已经够用了，哈哈，只有不断学习才能抵抗共匪的封锁

@sundaqing1969 

那4个ip是测试用的，你需要把你自己的GoAgent ip复制出来粘贴到代码中的，位置就是3个单引号中间

```
# 粘贴需要转换的GoAgent格式的ip到3个单引号(''')中
ip_goagent = '''

1.1.1.85|1.1.1.115|
1.1.1.112|

1.1.1.152
'''
```

**[上面](https://github.com/phuslu/goproxy/issues/177#issuecomment-138259225)的代码有更新**
`已经加上了自动从proxy.ini文件的iplist中读取google_hk ip的代码，有时间再完善吧。`

**Comment by sundaqing1969** [comment]
十分感谢！

**Comment by TonnyTonny** [comment]
感謝分享

**Comment by yyssxx** [comment]
非常感谢！很实用。
