### ISSUE TITLE
https方案, 老鱼不死, FuguHub MxTunnel 梭鱼

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1773]
![fuguhub png](https://cloud.githubusercontent.com/assets/2461165/26813963/7eef4406-4ab4-11e7-975c-442e7543be9e.png)

FuguHub MxTunnel 梭鱼
https://barracudadrive.com/MxTunnel.lsp

以前推过, 不过现在是全套VPS方案.

俺此前怂恿他人试过的, 速度不赖, 不过那厮拒绝分享... LOL

**Comment by tec1987** [comment]
这图标好萌，哈哈哈

**Comment by jasonliul** [comment]
@tec1987 
![screenshot 1](https://cloud.githubusercontent.com/assets/2461165/26832569/80139cbc-4b02-11e7-8c56-b7f93fe5c151.jpg)

以前是一条淫贱鱼, 现在变成河豚....

**Comment by mixool** [comment]
VPS方式，最新openvpn的tls-crypt方式也可以扶墙了。顺便放一个别人的一键脚本：[https://github.com/Angristan/OpenVPN-install](https://github.com/Angristan/OpenVPN-install)，2.4分支，不过不清楚openvpn有啥优势。

**Comment by jasonliul** [comment]
@mixool 
嘢, 老家伙纷纷复活...

**Comment by ugvf2009** [comment]
想问一下，这东西怎么弄的。有没有布置服务器的教程。
