### ISSUE TITLE
社长，出来报个平安

### ISSUE THREAD

**Issue by qwerttaa** [phuslu/goproxy#1778]
软件可以不更新，但是人必须好好儿的啊。。。

好些天没音信了

**Comment by SeaHOH** [comment]
表吓人，项目都还在哈。

**Comment by yDan** [comment]
表吓人，项目都还在哈。

**Comment by yDan** [comment]
项目源文件我都备份好了

**Comment by hcym** [comment]
吃饱了撑的啊
不是一直有改动，只是没动gp而已
就算社长有压力，过一阵再说也没啥事
邓光贵都能制住包子，怕个屁啊

**Comment by phuslu** [comment]
汗，好着呢，这两天在弄别的项目呢

https://github.com/phuslu
