### ISSUE TITLE
IP Hider Pro 5.8.0.1 

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1779]
![5zisoqs jpg](https://user-images.githubusercontent.com/2461165/26972997-d1f2ceea-4d46-11e7-856c-3c73d28ccf62.jpg)

home
http://iphiderpro.com/

破解UZ1
https://www.datafilehost.com/d/f1fa4789
https://www.upload.ee/files/6208962/__IP_Hider_Pro.rar.html 

大概是唯一还能跑的更改ip工具, 不过俺不喜欢要加一个系统服务.

**Comment by hcym** [comment]
又搞这些神神叨叨的东西
你要是郭大贵，躲到克里姆林宫也能查水表

**Comment by kirbyzhu** [comment]
改ip有啥用 肉体还在

**Comment by blob2015** [comment]
改ip的话，有时候还是有些用处啦，现在封google ip的地方太多了，还有的封国内的ip——是的，也有国内封国外的……
当然，自己买了搬瓦工什么的，可能就不用愁google ip被封这事儿了

**Comment by kirbyzhu** [comment]
j哥是狡兔十八窟

**Comment by jasonliul** [comment]
@kirbyzhu 
去年被墙农搞坏的玩具, 基本都回来了~
:)

**Comment by kirbyzhu** [comment]
@blob2015 有时候我在想，如果境外的vps和paas这些全部被封了ip 大部分比较好走的路也就死翘翘了

**Comment by kirbyzhu** [comment]
@jasonliul 新墙防不住老枪
