### ISSUE TITLE
前置玩家宝库

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1781]
https://happy-hack.ru/proxy/
这家最齐全, 并且绝大部分是破解版.

很多古旧软件依然可用, 而且好用

**Comment by blob2015** [comment]
J哥看来经常去毛子家逛 😀

**Comment by jasonliul** [comment]
@blob2015 
他们收集旧版, 其他地方很少...

**Comment by kirbyzhu** [comment]
厉害，除了里面几个软件的英文名字认得！

**Comment by jasonliul** [comment]
有兴趣玩袜子的, 炎夏正是季节.
因为通常正常地球人, 是拿袜子加挂游戏的, 而炎夏是游戏旺季.

今年只读留意的是袜子巨头, 新增巴西, 带宽汹涌~~

**Comment by hcym** [comment]
我就在一个谷家吊死
gae加上gce

**Comment by kirbyzhu** [comment]
关键是gce试用期过后要美金了 
我还搞了openshift arukas和heroku 
分别使用了社长的goproxy-vps和php，gsnova，gost和tinyproxy,SSR等部署了。

**Comment by jasonliul** [comment]
@kirbyzhu 
这次被封杀, 俺找到袜子的用法.
必须是中国ip, 而且主机不在中国.

加挂freegate测试, FG对于伪中国主机很敏感, 会拒绝提供服务

**Comment by kirbyzhu** [comment]
@jasonliul j大威武
