### ISSUE TITLE
iPhone Chrome 浏览器 证书问题 err cert authority invalid

### ISSUE THREAD

**Issue by johnsonz** [phuslu/goproxy#1784]
刚升级了客户端和服务端 
goproxy r1419
goproxy gae r65
goproxy linux mipsle r1419 

使用路由器pac代理，已导入证书，电脑正常，iPhone Safari手动信任证书正常，但是Chrome 59出现证书验证错误，有人碰到过吗？

难道Chome有自己的证书系统了

<img src="https://user-images.githubusercontent.com/2533629/27007981-1a2cb818-4e98-11e7-9753-08958e2fb0de.PNG" alt="" width="50%">

**Comment by johnsonz** [comment]
补上日志，safari可以正常使用google
Chrome:
![chrome](https://user-images.githubusercontent.com/2533629/27009784-5e4a8c6a-4ec9-11e7-94e0-23dd38570837.PNG)
Safari:
![safari](https://user-images.githubusercontent.com/2533629/27009785-5e5d4774-4ec9-11e7-94c2-848fed4714d2.PNG)

**Comment by MeABc** [comment]
重新生成 goproxy 证书（相对 chrome 59 之前），且导入系统。---- 有没有这样试过？

**Comment by inkdie** [comment]
应该是你的iOS升级到最新版本了
最新版本iOS不仅仅要导入证书，还有一个验证过程。

设置---通用----关于本机-----证书信任设置，找到go的证书，把开关打开，应该可以了。你试试先

**Comment by johnsonz** [comment]
@inkdie  多谢
ios10.3.2确实多了一个开关
