### ISSUE TITLE
goproxy代理为什么登不了Google scholar

### ISSUE THREAD

**Issue by Lemonjay** [phuslu/goproxy#1790]
登录几乎就没成功过。另外登录Google搜索也很卡。求问怎么配置，还是只能修改hosts，才可以。

**Comment by SeaHOH** [comment]
把 `accounts.google.com` 放到 `ForceGAE` 尝试一下。

**Comment by kirbyzhu** [comment]
为啥我默认设置都没这些问题啊 
我觉得还是ip太少的问题

**Comment by SeaHOH** [comment]
也有可能是浏览器没设置好……

**Comment by Lemonjay** [comment]
换了IP，可以了，可能要经常换吧！hehe

**Comment by kirbyzhu** [comment]
@Lemonjay 不是要经常换，是要放一堆。社长设计的精妙之处在于以力破巧，千斤压四两。
