### ISSUE TITLE
很奇怪，单独某一人的推特打不开？可别人的都好好儿的啊。。。。。

### ISSUE THREAD

**Issue by qwerttaa** [phuslu/goproxy#1792]
无关乎 正 治，就是比较奇怪

现在看任何其他人的推特都是可以直接打开页面，唯独郭x贵打不开

我甚至下了个tor完整浏览器套件，发现同样是打不开他的个人推页面

https://twitter.com/K***M****

我特想知道这是为什么啊？

另外，在推特里搜索他的中文名字，时间轴上可以看到郭的正常推文

在推特里搜索他的唯一ID标识K***M****，然后搜索也不显示了

那么问题一定就是K***M****这个英文字串么？也不是。。。。打开google搜索这个英文字串是可以正常显示搜索结果的

当然，我尝试搜索了K***M***，少了最后一个字母s，结果是可以正常搜索。。。

哦，对，连接都是https

当然，除了K***M****这个ID，他另一个ID也一样出现这样的问题G******，然而一众仿冒的ID都没事儿

这就蹊跷了，tor也不好使了？哪位肉番的直接试试呢？

我现在时间不充裕，预备回家以后上个英文系统虚机下一个英文版的tor，看看跟环境语言有没有关系

如果跟环境语言有关系，是不是说明是推特官方自己搞的鬼。。。和墙没关系。。。

帖子写的比较乱，逻辑上如果没看明白。。。劳烦再看一遍。。。。。

最后，哪位大神知道这是为毛？问题出现在哪个环节？如果明示了，我就不折腾了。。。

**Comment by dou4cc** [comment]
是推特被迫的，你登录就能看了

**Comment by qwerttaa** [comment]
@dou4cc 我确实没登陆。。。主要是我登陆的账号是什么我都想不起来就更别提密码了。。。。。。。。。。。。。。

**Comment by qwerttaa** [comment]
以前的号找回来了，果然是登陆了以后就可以看到了，囧
