### ISSUE TITLE
Zoolz Cloud Storage 100 GB

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1793]
http://home.zoolz.co.uk/100gb-free-lifetime/

Email get
http://cloud2.zoolz.com/Offer100GB?utm_source=FREE_100GB_FREE&utm_campaign=FREE_100GB_Promo&utm_medium=email

国内已经死光光了

**Comment by blob2015** [comment]
国内的话，老爷子永硕还在啊，免费的好像是1G，太难得了，那么多挂了的。当然，你长久不登陆，会删数据，至于是否有下载什么的限制，就不知道了。
网易的，向来比较精明，上传的容积以外，下载还有次数限制。
但凡流量一大、一出名，就容易挂，这个变现比较不容易、成本压力终究摆在那里。
再等等吧，看能活下来几个。
Google的改变世界，其中之一，是邮箱容量、存储容量，从几十M、一百M，直接进入G点。
喧嚣过后，继续喧嚣？
不知道，又会倒下几个，存活几个。

**Comment by kirbyzhu** [comment]
是的 用了php代理注册成功
