### ISSUE TITLE
youtube能正常播放，但是其他引用youtube视频的网站播放则提示we are sorry.....

### ISSUE THREAD

**Issue by AndyLau2017** [phuslu/goproxy#1797]
我已经使用goproxy最新版了（r1419 32位），ip是从xx-net复制进来的，youtube能正常打开，但是打开这个东京热的视频  https://ohyeah1080.com/video/tokyo-hot-se125-3-eiko-ishii/   
会显示google的错误提示：We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now. 

使用SS可以正常播放，而goproxy则提示上面那个错误，
如@Alvin9999 说的【GoProxy：把gae.user.json文件里面的某一行修改为：//"*.youtube.com": "google_hk"】，但r1419默认就是这个设置，不知道哪位大神有方法解决？
是那个网站屏蔽了gae访问吗？

![2345 20170616165644](https://user-images.githubusercontent.com/29122546/27219599-d6527120-52b4-11e7-81aa-cb59a2a20eee.jpg)

**Comment by MeABc** [comment]
把` youtube.googleapis.com ` 加入 `gae.json/gae.user.json --> "ForceGAE"` 试下。

**Comment by AndyLau2017** [comment]
@MeABc 改了之后，没有提示错误了，但是点击播放一直在转圈圈，还是播放不了哦，是ip的问题吗？
![2345 20170616172514](https://user-images.githubusercontent.com/29122546/27220724-c1699c58-52b8-11e7-8342-8bd6c13de846.jpg)

**Comment by AndyLau2017** [comment]
SS能正常播放视频，就是goproxy不行，会不会是屏蔽了gae，但是视频引用的是youtube上的啊，按道理应该是能播放才对的。好奇怪

**Comment by MeABc** [comment]
（是ip的问题吗？）

不清楚是不是这个。还没具体测试。。。


在 2017/6/16 17:25, AndyLau2017 写道:

**Comment by SeaHOH** [comment]
可能是 cookie 在起作用，把 `ohyeah1080.com` 也加入 GAE 试试。

**Comment by AndyLau2017** [comment]
@SeaHOH 一样不行呢，这网站太厉害了，把AV资源放到youtube上，然后在自己网站上播放，目前只有ss能播放，gae类都不行

**Comment by SeaHOH** [comment]
```
"DIRECT GET https://r12---sn-i3b7kne6.c.docs.google.com/videoplayback?id=33f5fb5d6471ce06&
itag=22&source=webdrive&requiressl=yes&ttl=transient&mm=30&mn=sn-i3b7kne6&ms=nxu&
mv=u&pl=19&ei=Lq9DWba7M4b1qQWzl46gBQ&driveid=0B2aZ4uKdgrQ0UjhCWGFKZHJ1cGM&
mime=video/mp4&lmt=1497539272810526&mt=1497607604&ip=118.119.161.91&ipbits=0&
expire=1497622382&cp=QVJOWUdfUVNWQ1hNOl9zRVUxa0pKQThQ&
sparams=ip,ipbits,expire,id,itag,source,requiressl,ttl,mm,mn,ms,mv,pl,ei,driveid,mime,lmt,cp&
signature=7664D6D11AECAB15FDB42FAEB68C0CD1AAF38717.73F6F19F73E451944880F9CC79C022
81AC9D5061&key=ck2&app=explorer&cpn=q2nNkcmOz7lEDo-Y&c=WEB&cver=1.20170614 HTTP/1.1" 404 2229
```
人家视频地址妖艳，在 GoProxy 中默认是不走 GAE 的，所以 404。

**Comment by AndyLau2017** [comment]
@SeaHOH 但是强制gae也不行呢，这就更奇怪了

**Comment by SeaHOH** [comment]
没毛病，老司机正看着呢。

**Comment by AndyLau2017** [comment]
@SeaHOH   大佬的意思是你那可以正常播放？卧草，怎么弄好的，求上车，求带

**Comment by SeaHOH** [comment]
就上面那个地址啊 `*.google.com/videoplayback`。

**Comment by AndyLau2017** [comment]
终于搞定了，“澳门顶级赌场”终于又在耳边响起来了，泪流满面
本屌方年20有加，正是壮年之时，还望大佬多带上车 []~(￣▽￣)~*
话说，大佬，为啥用chrome看可以拖进度条，firefox则不能拖，是什么原理呢？
