### ISSUE TITLE
海少, 你的checkgip死翘翘...

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1798]
今天忽然发现的...
不过gogotest也抽筋, 一样一样.

只有个别字段可以检测

**Comment by SeaHOH** [comment]
死了？没关系，大家都用这么久了，手头肯定有以前扫的 IP，只管往 GoProxy 里面放就是，社长给大家兜底。
这几天正在开展 GotoX 二期工程，所以继续重写 checkip 会在这之后。

**Comment by jasonliul** [comment]
不知道其他人怎样...
看起来是新版封杀, 确实good_ip剧烈减少

**Comment by phuslu** [comment]
我用的韩国 ip， 目前看起来还好。

试下流行的 https://github.com/racaljk/hosts 项目的 ip 看看呢。

用一下命令行可以提取 good ip
`curl -sSL https://raw.github.com/racaljk/hosts/master/hosts | grep google | awk '{print $1}' | sort | uniq`

比如
```
216.58.196.236
216.58.200.33
216.58.206.14
216.58.221.144
61.91.161.217
64.233.171.192
64.233.177.127
64.233.188.121
64.233.188.125
64.233.188.14
64.233.188.16
64.233.188.188
64.233.189.108
64.233.189.128
64.233.191.121
```
（待会删除）

**Comment by SeaHOH** [comment]
这个星期是有点折腾，但用着不影响。

**Comment by wpyok500** [comment]
不知道MFF怎么样

**Comment by hcym** [comment]
日
我说怎么手机出叉叉
hosts失效了
老大，那个VPS版本能不能不用域名，像影梭直接ip
尝到gce甜头，小甜甜大头

**Comment by jasonliul** [comment]
@SeaHOH 
今天下午之前都正常...

**Comment by SeaHOH** [comment]
是么，没啥感觉，跟昨天差不多。
十多天前有段时间，有五六个段根本就没干扰……

**Comment by jasonliul** [comment]
@SeaHOH 
俺3000多ip, 现在测试只有18个.

不过俺的妖气盾阵就来了. 18变55~~
![screenshot 1](https://user-images.githubusercontent.com/2461165/27224530-306d2534-52c8-11e7-8547-4d5fa53ae11b.jpg)

**Comment by SeaHOH** [comment]
完全搞不懂~我们根本没在一个国家的感觉。

**Comment by jasonliul** [comment]
电信, 下午都是正常的...
还以为墙农又要过节~

**Comment by SeaHOH** [comment]
以上感慨是针对 J 哥的妖气盾阵~

**Comment by blob2015** [comment]
刚才特意测试了下，还是正常的，但是有个由来已久的老问题，如果是默认设置的话，最好多检几遍【2-3，个人是这样的】，否则总有不少遗漏的。
另外， @SeaHOH ，好像我这边设置成256以上的线程，好像容易出现错误？——但程序运作依然好像正常。目前一般都是设置128，试了下，就算设置只有10，照样还是容易“漏”，还是多检几遍来得效率高。
等海兄忙完那个项目，再搞这个，不迟，估计应该可以用挺长时间的，除非要看yt的直播，否则好像基本上还是挺乐呵，但yt的直播，对ip好像就比较挑剔了。

**Comment by jasonliul** [comment]
@blob2015 
难道是俺的线路问题....

**Comment by SeaHOH** [comment]
@blob2015 
这原本就不是我写的，只是汉化+小改。感谢 moonshawdo。
我改了这个之后，才有了修改 goAgent 的念头，多个 Privoxy 不环保。

说道 IP，澳门那个 IP 已经不离不弃一年多了，完全通畅。

**Comment by blob2015** [comment]
@jasonliul 
可能有时候就是一时发作？
@SeaHOH 
澳门还有这ip？俺曾经把周边国家、地区强扫过一遍的，也没发现特别好的啊，因为isp与地区的梗？
moonshawdo不搞了吧？那就是开枝散叶了啊，其中一枝到了大海兄这儿，“一枝寒梅……” 😀

**Comment by SeaHOH** [comment]
指天发誓，真事。

**Comment by tec1987** [comment]
@SeaHOH 
电信直接路由过去的，估计是加了白名单

**Comment by tec1987** [comment]
最近一些GGC有调整，有些IP段不可用了。。。

**Comment by MeABc** [comment]
GGC节点分布图。扫 IP ，你懂的。。。。

![default](https://user-images.githubusercontent.com/18194126/27227886-f558ea36-52d7-11e7-9302-3dc162a4e127.png)

**Comment by AndyLau2017** [comment]
我的ip都是在xx拷贝过来的，现在更新xx到最新版本，可用ip30个不到，youtube还提示500错误，这封ip真是太疯狂了

**Comment by jasonliul** [comment]
刚才房东搞定了, ISP分配两种字头的ip地址, 有一组是通连性问题.
不是封杀ip, 其他用户也有若干不能连接.

房东的做法是蛮干重启n次, 直到正常 :)

**Comment by wangbingqian** [comment]
不是因为郭文贵在油管直播吗？

**Comment by phuslu** [comment]
更新我这边情况，刚刚用了好几月的韩国 3000+ IP 貌似挂了。用 mff 扫了 200 来个 IP 讲究着用了。

**Comment by AndyLau2017** [comment]
我用mff扫描了之前那个好心网友分享的ip段，得到了几个ip，我直接把这些ip导入到goproxy中也能用，但是用几分钟就提示
Invalid URL
The requested URL "[no URL]", is invalid.
Reference #9.8c62d9cb.1497636890.5238cd9
那些ip的类似只有一个是GVS的，其他有AkamaiGhost， 证书是这个akamai.net的，
请问有人知道是什么问题吗？第一次自己手动找ip

**Comment by jasonliul** [comment]
@phuslu 
貌似是一种新封杀的方式, 不过搞得网络极不正常.
俺的房东只上极少数国内网站, 也有问题.

**Comment by phuslu** [comment]
我扫的 ip 是 @dou4cc 分享的那个 5w 个IP 里面的，目前用起来还行。

![2017-06-17_022423](https://user-images.githubusercontent.com/195836/27239642-5e939736-5304-11e7-8e5c-55bbc555f0db.png)

youtube 速度相比之前的韩国稍慢，但是也挺不错，可能是深夜的关系。

![2017-06-17_022527](https://user-images.githubusercontent.com/195836/27239710-a402a49c-5304-11e7-97d1-c0bad5f1f54f.jpg)

**Comment by fengixng** [comment]
@MeABc 这个分布图是你自制的么，和官网的颜色不一样啊

**Comment by AndyLau2017** [comment]
@fengixng 又看到你了

**Comment by jasonliul** [comment]
俺改用GP以来, 这还是首次出点问题, 难得...LOL

**Comment by tec1987** [comment]
这次大量封IP不知道是不是区域性的，这些IP前几天还好用，这两天全部被封了

```
#45.115.252.46
#45.115.252.47
#45.115.252.48
#45.115.252.49
#45.115.252.50
#45.115.252.51
#45.115.252.52
#45.115.252.53
#45.115.252.54
#45.115.252.55
#45.115.252.56
#45.115.252.57
#45.115.252.58
#45.115.252.59
#45.115.252.60
#45.115.252.61
#203.210.6.142
#203.210.6.146
#203.210.6.150
#203.210.6.154
#203.210.6.158
#203.210.6.162
#203.210.6.164
#203.210.6.165
#203.210.6.166
#203.210.6.170
#203.210.6.174
#203.210.6.178
#203.210.6.182
#203.210.6.186
#203.210.6.188
#203.210.6.189
#203.217.98.14
#203.217.98.18
#203.217.98.22
#203.217.98.26
#203.217.98.30
#203.217.98.34
#203.217.98.36
#203.217.98.37
#203.217.98.38
#203.217.98.42
#203.217.98.46
#203.217.98.50
#203.217.98.54
#203.217.98.58
#203.217.98.60
#203.217.98.61
#203.66.155.148
#203.66.155.149
#203.66.155.150
#203.66.155.151
#203.66.155.152
#203.66.155.153
#203.66.155.154
#203.66.155.155
#203.66.155.180
#203.66.155.181
#203.66.155.182
#203.66.155.183
#203.66.155.184
#203.66.155.185
#203.66.155.186
#203.66.155.187
#123.241.78.14
#123.241.78.15
#123.241.78.16
#123.241.78.17
#123.241.78.18
#123.241.78.19
#123.241.78.20
#123.241.78.21
#123.241.78.22
#123.241.78.23
#123.241.78.24
#123.241.78.25
#123.241.78.26
#123.241.78.27
#123.241.78.28
#123.241.78.29
#202.142.224.82
#202.142.224.83
#202.142.224.84
#202.142.224.85
#202.142.224.86
#202.142.224.87
#202.142.224.88
#202.142.224.89
#202.142.224.90
#202.142.224.91
#202.142.224.92
#202.142.224.93

```

**Comment by SeaHOH** [comment]
@jasonliul 
房东威武！

@phuslu @tec1987 
并没有封，但变慢了许多，似乎是增加了路由节点。

另外，似乎今日凌晨开始状况又变了，IP（快速） 轮换频率大大减少，似乎干扰少了。

**Comment by jyuan15** [comment]
重新扫了下，可用IP变少，但速度貌似变快了
![2017-06-17_100837](https://user-images.githubusercontent.com/12642186/27249334-64543086-5345-11e7-866d-8b85fc730e0e.jpg)

**Comment by jyuan15** [comment]
重新扫了下，可用IP变少，但速度貌似变快了
![2017-06-17_100837](https://user-images.githubusercontent.com/12642186/27249334-64543086-5345-11e7-866d-8b85fc730e0e.jpg)

**Comment by jasonliul** [comment]
看起来墙农也不能总是养膘, 
这次应该是例假...唔, 例行维护

**Comment by wpyok500** [comment]
368个ip段（共100608个ip）checktools线程1000扫除了1146个ip，1个203.66ip段扫出4个203.66的ip

**Comment by jasonliul** [comment]
俺也重开摸奖, 把亚洲巡游一遍.
只增加6个现役短字段, 一些后备役.

是时候存粮, 以防墙农破坏生态平衡~~~

**Comment by zhaym** [comment]
@jasonliul  很难说是GFW的威力还是Google的访问限制。
现在的情况让我不得其解，有些Google IP明明可以ping通，但nmap的结果却提示Host is down，加-Pn参数扫描443端口，显示为443/tcp filtered https。奇怪的是，将这个IP用到hosts文件，配合chrome浏览器，居然能正常访问Google网站，但其他浏览器例如Safari却不行。

**Comment by SeaHOH** [comment]
@zhaym 
是么，麻烦给个这样的 IP 我看一下。

**Comment by MeABc** [comment]
@fengixng 
节点图不是我弄的。

**Comment by zhaym** [comment]
@SeaHOH 很多，我给你一个网上公开的，61.91.161.217。
hosts里分配给www.google.com，我Mac上的Chrome正常访问。

**Comment by tec1987** [comment]
@SeaHOH
我这面确实是封了，TCP 443和80端口连不上，如果你那可用的话，估计是部分ISP/地区封锁。

@zhaym 
这是TH的GGC，我这测试没有问题，就是丢包30%以上。。。

**Comment by jasonliul** [comment]
61.91.161.251|61.91.161.250|61.91.161.249|61.91.161.248|61.91.161.247|61.91.161.246|61.91.161.244|61.91.161.245|61.91.161.243|61.91.161.242|61.91.161.240|61.91.161.241|61.91.161.239|61.91.161.238|61.91.161.237|61.91.161.236|61.91.161.235|61.91.161.234|61.91.161.233|61.91.161.232|61.91.161.231|61.91.161.230|61.91.161.229|61.91.161.228|61.91.161.226|61.91.161.227|61.91.161.225|61.91.161.224|61.91.161.223|61.91.161.222|61.91.161.221|61.91.161.220|61.91.161.219|61.91.161.218|61.91.161.217|61.91.161.216|61.91.161.215|61.91.161.213|61.91.161.214|61.91.161.212|61.91.161.211|61.91.161.209|61.91.161.204|61.91.161.210|61.91.161.208|61.91.161.206|61.91.161.207|61.91.161.205|61.91.161.187|61.91.161.186|61.91.161.185|61.91.161.184|61.91.161.183|61.91.161.180|61.91.161.182|61.91.161.181|61.91.161.179|61.91.161.178|61.91.161.175|61.91.161.177|61.91.161.176|61.91.161.174|61.91.161.173|61.91.161.172|61.91.161.171|61.91.161.170|61.91.161.169|61.91.161.168|61.91.161.167|61.91.161.166|61.91.161.165|61.91.161.164|61.91.161.162|61.91.161.163|61.91.161.161|61.91.161.160|61.91.161.159|61.91.161.157|61.91.161.158|61.91.161.156|61.91.161.152|61.91.161.155|61.91.161.153|61.91.161.154|61.91.161.151|61.91.161.150|61.91.161.146|61.91.161.149|61.91.161.148|61.91.161.147|61.91.161.143|61.91.161.145|61.91.161.144|61.91.161.142|61.91.161.141|61.91.161.140|61.91.161.120|61.91.161.123|61.91.161.122|61.91.161.121|61.91.161.119|61.91.161.118|61.91.161.117|61.91.161.116|61.91.161.115|61.91.161.114|61.91.161.113|61.91.161.110|61.91.161.112|61.91.161.111|61.91.161.109|61.91.161.106|61.91.161.108|61.91.161.107|61.91.161.105|61.91.161.103|61.91.161.104|61.91.161.102|61.91.161.101|61.91.161.100|61.91.161.99|61.91.161.98|61.91.161.97|61.91.161.96|61.91.161.95|61.91.161.94|61.91.161.93|61.91.161.92|61.91.161.91|61.91.161.90|61.91.161.89|61.91.161.88|61.91.161.87|61.91.161.86|61.91.161.85|61.91.161.84|61.91.161.83|61.91.161.82|61.91.161.81|61.91.161.80|61.91.161.78|61.91.161.79|61.91.161.77|61.91.161.76|61.91.161.59|61.91.161.58|61.91.161.57|61.91.161.56|61.91.161.55|61.91.161.54|61.91.161.53|61.91.161.52|61.91.161.51|61.91.161.50|61.91.161.49|61.91.161.48|61.91.161.47|61.91.161.46|61.91.161.45|61.91.161.44|61.91.161.43|61.91.161.42|61.91.161.41|61.91.161.40|61.91.161.39|61.91.161.38|61.91.161.37|61.91.161.36|61.91.161.35|61.91.161.34|61.91.161.33|61.91.161.32|61.91.161.31|61.91.161.30|61.91.161.29|61.91.161.28|61.91.161.27|61.91.161.26|61.91.161.24|61.91.161.25|61.91.161.23|61.91.161.22|61.91.161.21|61.91.161.20|61.91.161.19|61.91.161.18|61.91.161.17|61.91.161.16|61.91.161.15|61.91.161.14|61.91.161.13|61.91.161.12

正常开放443的是这些, 俺这里全封

**Comment by SeaHOH** [comment]
@tec1987 
看来地区差别很大。

@zhaym 
我这里也能用，就是非常不稳定。

**Comment by tec1987** [comment]
墙的封锁策略早就分配给ISP了，全部在国际出口处理的话，估计封锁能力不足，或者对网络影响较大。。。
总之一句话，墙是按地区分等级的。。。

**Comment by SeaHOH** [comment]
>墙是按地区分等级的

三年多前就有这猜测

**Comment by jasonliul** [comment]
@SeaHOH 
多出去旅游, 这不是猜测

**Comment by tec1987** [comment]
事实上也差不多这样，几年前我跟一些ISP的人聊过，他们机房里大都有网监的服务器。。。

**Comment by tec1987** [comment]
一些地区偶尔抽风，应该是这些服务器维护或者重启。。。

**Comment by zhaym** [comment]
@SeaHOH  能用对了，我也能用。但问题是，nmap的结果是这样。
nmap -Pn -p 443 61.91.161.217
PORT    STATE    SERVICE
443/tcp filtered https

换言之，这个IP能用，但常规的工具扫不出来，连nmap也认为它的443屏蔽了。

**Comment by MeABc** [comment]
> 多出去旅游, 这不是猜测

之前有机会全国游，明显体会到各地不一样。直连 github.com 就可以看出。

**Comment by jasonliul** [comment]
@tec1987 
俺猜是墙农在办公桌嘿咻, 误操作而已~~
:)

**Comment by SeaHOH** [comment]
J 哥以前的确是猜，现在早确认了。

**Comment by SeaHOH** [comment]
@zhaym 
nmap 的扫描机制有问题吧。

**Comment by tec1987** [comment]
@zhaym 
不会吧？

你试试这个Tcping：
https://elifulkerson.com/projects/tcping.php

或者 WinEggDrop 的 Scanner ：
http://www.xfocus.net/tools/200407/753.html

**Comment by jasonliul** [comment]
@SeaHOH 
墙农似乎有办法干扰ping或其他检测.
最近有一些星加坡袜子, ping值接近400ms, 但是连接就非常快, 正常是不可能的.

**Comment by SeaHOH** [comment]
万事靠丢包嘛，从 0% 到 100%。

**Comment by MeABc** [comment]
> 万事靠丢包嘛，从 0% 到 100%。

这招狠。哈哈。。

**Comment by jasonliul** [comment]
@SeaHOH 
俺其实觉得, 防ping保护是被忽视的有效方式, 无论透明袜子或者纸飞机节点.
不过纸飞机党更喜欢国内中转~~~

**Comment by SeaHOH** [comment]
>防ping保护是被忽视的有效方式

类似这些保护都该由主机服务商来提供吧。

**Comment by tec1987** [comment]
@jasonliul 
ICMP ping 在IDS和路由策略下，确实不怎么好用。。。
TCP连接才是王道

**Comment by MeABc** [comment]
> 万事靠丢包嘛，从 0% 到 100%。

插播一下广告。---- 上 tls1.3 + http2 。

**Comment by SeaHOH** [comment]
@MeABc
即使上了也是想丢就丢吧。社长现在的策略不是拿到就走嘛，丢之前就把活干的差不多了。

**Comment by phuslu** [comment]
@zhaym 能否看下 chrome，F12 以后看security页面，看下用你这个 ip 访问谷歌网站的时候是不是用的quic协议。

谢谢

**Comment by zhaym** [comment]
@phuslu 应该是
The connection to this site is encrypted and authenticated using a strong protocol (QUIC), a strong key exchange (X25519), and a strong cipher (AES_128_GCM).

**Comment by SeaHOH** [comment]
换成 quic 链接 GAE 岂不无敌了

**Comment by phuslu** [comment]
quic 的 go 语言库我一直在关注，目前已经接近可用，但还不够成熟。

https://github.com/lucas-clemente/quic-go

我会集成一下试试，不过期望不用太高。在吞吐率上这个库还是有些问题，只能先做个备选方案。

**Comment by Kisesy** [comment]
不光google主页支持 quic，youtube， gae 都是支持的
![20170617173147](https://user-images.githubusercontent.com/5843694/27251875-1e7bae8e-5383-11e7-81d1-846e0cb96d9c.png)

**Comment by MeABc** [comment]
quic 这能做无缝结合吗？

在项目里，是重写了吧。。。我也不是很了解。。。

**Comment by SeaHOH** [comment]
既然是无链接的，会不会发展出“多对一”的 S/C 模式。

**Comment by jasonliul** [comment]
@phuslu 
社长, 还是做一个旁支版本, 慢慢来罢~

**Comment by phuslu** [comment]
不至于重写，我调研过。

集成 quic 这个库还算简单，gae.json 里面会多一项，叫 EnableQUIC: false , 主要要改的是 transport.go 这个文件

不过之前的基于 ssl 连接的 ip 评分机制要失效了，因为 quic 是 udp 协议，需要对这个库做些修改才能评分。

所以目前集成的话，只能靠诸位自己人肉筛选一些 quic 的 good ip 放进去了。

**Comment by MeABc** [comment]
> 基于 ssl 连接的 ip 评分机制要失效了

有得有失了。。。。

**Comment by wpyok500** [comment]
在出个专门扫quic的ip

**Comment by tec1987** [comment]
估计今年年底能够标准化。。。

**Comment by jasonliul** [comment]
@tec1987 
社长还是留一手好咧~~

**Comment by blob2015** [comment]
@MeAB 

> tls1.3 + http2

1.3还是不怎么靠谱吧？

---------------

今天真热闹 😀

**Comment by MeABc** [comment]
> 1.3还是不怎么靠谱吧？

上次那是终端问题（chrome 浏览器）。

**Comment by blob2015** [comment]
@MeABc @phuslu 
就是服务端已经开始了？
社长为这个憋了好久了吧 😀

**Comment by phuslu** [comment]
服务端估计还早，目前只有 inbox.google.com 部署了 tls1.3

**Comment by tec1987** [comment]
该死的长城宽带，港台上千个IP没有一个能用的。。。

用电信和联通都没问题。。。

**Comment by AndyLau2017** [comment]
@ tec1987  老哥，你搞错了吧？我这是电信能用的ip没几个......

**Comment by kirbyzhu** [comment]
@jasonliul 

我能扫出来3个可用ip

**Comment by kirbyzhu** [comment]
quic好像被墙屏蔽了吧

**Comment by phuslu** [comment]
据观察不少的确的 quic 还是能用的。

goproxy 集成 quic-go 的预备工作已经完成了，主要对 quic-go 的 IP 解析做了处理，可以指定为 gae.user.json 里面的 IP, 这样也为以后做 UDP 层面的 ip 评分做了基础。

https://github.com/phuslu/quic-go/commits/gae

**Comment by tec1987** [comment]
@AndyLau2017 
地区情况不一样，如果不是墙的问题，估计是路由问题或者反向屏蔽

@kirbyzhu 
深圳长宽比较坑，UDP用不了。。。

**Comment by jasonliul** [comment]
@tec1987 
这么看来, 这是一次封杀预演, 深圳, 金陵过后, 其他地方也是迟早.
履霜坚冰至~

**Comment by tec1987** [comment]
@jasonliul 
这个不好说，我更希望不是墙的问题

亚太地区就像开启白名单一样，九成以上的IP不可用。。。

**Comment by SeaHOH** [comment]
杀不了吧，vps 怎么杀？总有渠道能用。
都怪这么多说药丸的，害得我去听了会儿文贵讲故事，把我吓的。

**Comment by AndyLau2017** [comment]
@SeaHOH 哈哈，半夜听相声，感觉会起到催眠的作用

**Comment by tec1987** [comment]
妈蛋。。。
果然是网络问题，断网重连就好了

@jasonliul 虚惊一场

**Comment by kirbyzhu** [comment]
@jasonliul 金陵电信没啥问题啊

**Comment by phuslu** [comment]
从昨夜开始，貌似我这边恢复正常了，youtube 的流畅度回来了。。。

**Comment by SeaHOH** [comment]
前天昨天没啥区别，就是高峰期丢包多点，今天从凌晨开始就很少干扰，流畅的很。
怀疑我的公网 IP 立功了，NAT 可能受限更多。

**Comment by jasonliul** [comment]
其实墙农再封杀一次, 用GP的人数会激增.
人之初, 性本贱~~~

**Comment by panpeach** [comment]
电信，全面恢复
![11](https://user-images.githubusercontent.com/13916352/27260264-712e1a54-545a-11e7-8c3a-09d108aeb0fb.jpg)

**Comment by linhua55** [comment]
https://www.v2ex.com/t/369309

**Comment by AndyLau2017** [comment]
哇，你这速度也太夸张了吧。我的才2000多Kbps

**Comment by blob2015** [comment]
@linhua55 
好像打不开了，已经，说的啥？

**Comment by MeABc** [comment]
要登陆。


在 2017/6/18 20:31, Blob 写道:

**Comment by blob2015** [comment]
@MeABc 
原来如此 😀

**Comment by phuslu** [comment]
quic 已经集成，见 https://github.com/phuslu/goproxy/issues/1805#issuecomment-309732282

**Comment by wpyok500** [comment]
社长威武。
