### ISSUE TITLE
深圳...袜子玩家

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1801]
更新

gae.json里面	
	"Proxy": {
			"Enabled": true,
			"URL": "socks5://112.90.51.50:4130",
不妨试试~~

**Comment by tec1987** [comment]
居然走的香港阿里云。。。

**Comment by kirbyzhu** [comment]
J哥的袜子穿不完啊

**Comment by jasonliul** [comment]
@kirbyzhu 
白俄的玩意...

**Comment by AndyLau2017** [comment]
@jasonliul 膜拜，真正的袜子玩家

**Comment by AndyLau2017** [comment]
好奇问下J大，这些袜子难道都没有流量限制的？应该会类似VPS那样，每个月固定有多少流量的吧？

**Comment by yDan** [comment]
@jasonliul 那些ip和端口号放到gae.json哪个地方啊？

**Comment by kirbyzhu** [comment]
@yDan J大写得很清楚了
gae.json里面
"Proxy": {
"Enabled": true,
"URL": "socks5://112.90.51.50:4130",

**Comment by yDan** [comment]
我明白了。

**Comment by yDan** [comment]
再问一下，是把所有的ip地址都放进gae.json里面吗？还是只选择其中一个ip地址放进去就行了？

**Comment by kirbyzhu** [comment]
小姑娘，很多事情可以自己动手试试之后再提问。或者看看“提问的智慧”。

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md

**Comment by imyhxy** [comment]
为啥袜子ping的通，但是放进gp内还是用不了

**Comment by jasonliul** [comment]
@imyhxy 
袜子节点不是全天在线的, 得用测试工具

**Comment by IRISlMaple** [comment]
@jasonliul J大~请问现在什么测试工具可用，有什么推荐啊？刚看到你前几天推的Proxy Shark说阵亡了？

**Comment by jasonliul** [comment]
#1764

**Comment by jasonliul** [comment]
101.200.151.23:1080
101.203.174.209:1080
112.124.50.85:1080
115.182.255.234:1080
115.152.84.111:1080
115.29.161.167:1080
115.148.173.19:1080
121.10.141.149:1080
116.231.49.49:1080
59.37.163.176:1080
115.29.192.194:1080
123.59.173.50:1080
183.239.240.138:1080
182.96.245.171:1080
119.28.15.252:2018
111.76.202.38:1080
123.56.199.203:5271
180.173.223.104:1080
58.253.70.149:1080
115.29.193.119:1080
112.124.57.223:1080
112.74.194.74:1080
112.124.35.165:1080
111.76.205.108:1080
61.177.248.202:1080
222.188.10.1:1080
119.61.13.242:1080
111.76.206.81:1080
118.114.242.106:1080
111.76.202.18:1080
110.185.170.181:1080
115.29.161.103:1080
115.29.192.43:1080
122.4.254.54:1080
120.234.6.50:1080
123.59.100.243:1080
123.59.173.53:1080
120.234.15.130:1080
123.59.100.245:1080
115.150.251.173:1080
123.59.173.52:1080
182.92.225.78:1080
182.92.225.79:1080
222.129.43.96:1080
58.241.32.186:1080
222.52.76.51:1080
182.96.244.105:1080
124.161.16.91:1080
115.150.230.119:1080
114.215.90.211:1080
202.112.31.203:1080
124.239.177.85:1080
101.4.101.74:1080
124.161.16.94:1080
58.20.41.172:1080
124.251.90.71:1080
60.21.161.55:1080
123.56.199.152:3641
61.157.198.66:1080
116.193.153.166:9666
