### ISSUE TITLE
Elite https 前置

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1808]
Proxy Shark, 自动收集测试http类型前置.

类似袜子设置

**Comment by AndyLau2017** [comment]
厉害了！

**Comment by blob2015** [comment]
这个得另外安装软件？gp好像不支持直接填入https？http倒是看见了，选了一两个填入，好像不行？

**Comment by jasonliul** [comment]
@blob2015 
http前置很多不支持ssl, 
这些支持, 用法相同

**Comment by AndyLau2017** [comment]
@jasonliul  有批量测试http代理的软件吗？

**Comment by jasonliul** [comment]
45.59.171.14:3128
192.151.247.106:3128

**Comment by SeaHOH** [comment]
听说火狐现在支持 HTTPS 类型的代理，这些都是吗？有没有人试过？

**Comment by blob2015** [comment]
@SeaHOH 
试过一两个，没成，可能有地域差别？没有批量检查，什么时候搞个检查工具，再说

**Comment by SeaHOH** [comment]
谁用火狐最新版，试一下呗。

**Comment by SeaHOH** [comment]
@blob2015 
我看你上面是直接放到 GoProxy 中试的，社长没说过支持吧。

**Comment by blob2015** [comment]
@SeaHOH 
洞洞又不是只有一个，怎么可能只试一个洞洞呢？ 😀  
大海兄真是专一的人儿啊 😀 
Proxifier

**Comment by SeaHOH** [comment]
刚看了下源码，社长支持的真全：
`socks5、socks4、http、https、https+h2、ssh、ssh2`

**Comment by blob2015** [comment]
@phuslu 
要做就做全套，社长的追求 😀

**Comment by jasonliul** [comment]
[ProxyShark2016v1.6VipProEdition.zip](https://github.com/phuslu/goproxy/files/1088007/ProxyShark2016v1.6VipProEdition.zip)

**Comment by wz7465** [comment]
@SeaHOH 试过了，http代理而已，不是什么https代理

**Comment by blob2015** [comment]
@jasonliul 
感谢J哥 😀

**Comment by phuslu** [comment]
@wz7465 在公共代理领域，一般 `HTTPS 代理` 是指
> 支持 HTTPS 网站的 HTTP 代理

**Comment by jasonliul** [comment]
[Proxy Shark 2015 (Vip Pro Edition) v2.7.zip](https://github.com/phuslu/goproxy/files/1088019/Proxy.Shark.2015.Vip.Pro.Edition.v2.7.zip)
俺用的更旧..

**Comment by AndyLau2017** [comment]
我现在的情况是这样，自己扫出来的ip，筛选出延迟在60以内的，放入gp中，但是播放youtube很不稳定，一会速度5000Kbps，一会直接降到600Kbps，大部分时候速度都是在1000Kbps左右，而把这些相同ip导入到xx中，速度一直维持在3000Kbps左右，挺稳定的。然后gp要加了袜子才能稳定下来，不知道是我哪里没设置对（r1419全部是默认设置）？感觉gp的速度应该更加快才对啊！！

**Comment by SeaHOH** [comment]
@jasonliul 
所以说，这些都是支持 `CONNECT` 的 http 类型的代理而已？我还以为是 https 类型的代理。

**Comment by SeaHOH** [comment]
安全的前置还是 socks5、https 和 ssh，https 一直没见过。

**Comment by wz7465** [comment]
哈哈，其实社长说的没错，但是毕竟https代理的含义有所变迁了，最典型的就是squid了，其http代理支持http connect，盲转发连接https网站，但http网站还是明文，后面出现的squid https代理，全程都加密，概念上已经有所区分了。

**Comment by blob2015** [comment]
@SeaHOH 
没办法，谁叫俺是小白呢 😀

**Comment by SeaHOH** [comment]
话说，火狐新版能直接配置 https 类型代理，这是不是真的啊？

**Comment by wz7465** [comment]
是啊，好像从52版就能支持了

**Comment by SeaHOH** [comment]
一直奇怪为什么标准里没有 https 类型代理，现在火狐支持了，不知道以后会不会加入标准。

**Comment by wz7465** [comment]
![default](https://user-images.githubusercontent.com/7801728/27334057-9b438666-55fa-11e7-8be4-719002b7d071.png)

**Comment by SeaHOH** [comment]
不知道苍月何时跟进。

**Comment by blob2015** [comment]
那位 @pug908 好久没有看见了啊，说是要修理ggc。老兄最近怎么样来着。

**Comment by SeaHOH** [comment]
@blob2015 
火狐换人后简直就成了狐狸精了，受不了这花样百出。肯定是谷歌勾引嘀~

**Comment by blob2015** [comment]
@SeaHOH 
我说呢，怎么成了chrome fox，原来换过人啊，nnd，各种跟在chrome后面……

**Comment by jasonliul** [comment]
106.248.234.43:8080
113.53.230.195:3128
119.81.189.194:8123
119.81.71.27:80
119.81.71.27:8123
134.213.152.188:3129
134.213.152.188:4444
134.213.158.212:3129
134.213.158.212:4444
134.213.208.193:3130
134.213.208.43:2016
134.213.208.43:3129
134.213.208.43:5070
134.213.210.70:2016
134.213.210.70:3129
134.213.210.70:4444
134.213.214.34:3124
134.213.214.34:3129
134.213.49.60:4444
134.213.49.87:4444
134.213.62.13:3129
134.213.62.13:4444
136.144.129.163:8888
138.219.40.99:8080
138.68.131.209:8118
138.68.161.123:8118
138.68.167.147:8118
138.68.178.178:8118
138.68.185.233:8118
139.59.165.143:8118
159.203.84.241:3128
159.8.114.37:8123
162.13.136.29:3129
162.13.152.211:3129
162.13.166.149:3129
162.244.134.96:8080
162.244.135.135:8080
162.244.135.156:8080
162.244.135.209:8080
162.244.135.85:8080
163.172.213.3:3128
174.36.202.74:80
177.194.142.213:3128
178.62.11.5:8118
178.93.125.14:8080
187.75.146.123:3128
187.75.146.123:80
188.166.144.97:8118
188.166.145.77:8118
188.166.21.143:8080
195.248.169.76:8118
198.23.229.222:8118
198.50.219.230:80
200.123.138.229:8080
201.16.140.205:3128
201.90.120.194:3128
202.5.17.76:8080
212.191.32.83:8080
36.55.226.146:3128
40.118.240.200:8080
46.101.46.237:8118
46.101.78.82:8118
46.101.90.139:8118
46.167.210.2:8118
47.52.57.172:80
47.88.154.164:80
47.88.154.164:8080
5.189.189.196:8080
50.31.14.151:8140
50.31.14.152:8140
51.15.49.7:3128
52.20.9.123:3129
52.20.9.123:4000
52.44.16.168:3129
52.44.16.168:4000
58.27.217.75:3128
64.62.206.182:61812
77.120.102.84:3128
88.99.174.139:3128
91.134.213.154:3128
92.60.180.113:3128

换一拨~~

**Comment by tec1987** [comment]
还是学老外 叫支持SSL的HTTP代理比较好，叫HTTPS容易混淆。。。
@SeaHOH 
@johnsonz

**Comment by AndyLau2017** [comment]
@tec1987 老哥，我那个问题有解吗？难道无解了？

**Comment by kirbyzhu** [comment]
J大的福利是一波又一波

**Comment by tec1987** [comment]
@AndyLau2017
哪个？

**Comment by blob2015** [comment]
@jasonliul 
J哥，俺用你给的Proxy Shark 2015检了一遍，在俺这里，集体阵亡 😀

**Comment by AndyLau2017** [comment]
@tec1987  我现在的情况是这样，自己扫出来的ip，筛选出延迟在60以内的，放入gp中，但是播放youtube很不稳定，一会速度5000Kbps，一会直接降到600Kbps，大部分时候速度都是在1000Kbps左右，而把这些相同ip导入到xx中，速度一直维持在3000Kbps左右，挺稳定的。然后gp要加了袜子才能稳定下来，不知道是我哪里没设置对（r1419全部是默认设置）？感觉gp的速度应该更加快才对啊！！

**Comment by kirbyzhu** [comment]
速度不稳定是正常的

**Comment by jasonliul** [comment]
@blob2015 
俺已经检测过几个, 直接用

**Comment by AndyLau2017** [comment]
@kirbyzhu  主要是gp的速度变化太厉害了，而且跨度也很大，一下子从最高点掉到最低点的感觉。不过xx就一直很稳定，速度也快，不知道是哪里出了问题

**Comment by jasonliul** [comment]
@tec1987 
这个不是叫法的问题, 俺提供这些, 也混入真正的https, 需要帐户密码的, 现在没有好办法区分.
搜刮测试都有这问题

**Comment by tec1987** [comment]
@AndyLau2017
这个问题还真不好说。。。

如果用在XX里速度好且稳定，那你就先用一阵看看。

另外你能确定XX和GP连的是同一IP？不同IP不同时段 有速度差异是正常的。

就目前的网络状况来看：
低延迟未必高带宽，或者使用人数多，人均带宽低
瞬时的干扰情况，和抗干扰的逻辑处理。。。等等

**Comment by AndyLau2017** [comment]
@tec1987 嗯，有道理，看来我还要继续观察才行。
@jasonliul  我这也是检查到集体阵亡

**Comment by SeaHOH** [comment]
@jasonliul @tec1987 
应该有四种：HTTP 和 HTTPS，支持和不支持 `CONNECT`。除非公布了，前面两类不好区分。

**Comment by jasonliul** [comment]
Proxy Shark 已经被封杀

**Comment by Just2co** [comment]
@jasonliul J大，你分享出来才几天就被封杀了，GFW的效率也太高了吧，这里面一定有GFW里的狗，经常潜水嗅探！那要怎样才能让proxy shark复活？

**Comment by jasonliul** [comment]
#1764 
换就是.
