### ISSUE TITLE
新搜了几个IP，碰到如下问题

### ISSUE THREAD

**Issue by ftwcpc** [phuslu/goproxy#1809]
服务端版本：goproxy-gae-r65
客户端版本：r1419 (go/6bca56f http2/faee95b windows/amd64)
浏览器版本：chrome 58.0.3029.110 (64-bit)
问题描述：今天手头IP全挂了，搜了几个IP来用，但使用过程中chrome浏览器经常出现如下画面
![error](https://user-images.githubusercontent.com/1639418/27322180-a8e9fee2-55cf-11e7-8510-fd1a433a6a9b.PNG)
也有时候错误画面是这样的
![error2](https://user-images.githubusercontent.com/1639418/27323019-a7943e24-55d2-11e7-87e3-257133dac346.PNG)

可以观察了下后台，goodip仍有5个，但打开任何gogole页面均出现此错误，多次重启goproxy解决。

麻烦大家帮忙分析下问题原因

还有个奇怪现象，我在浏览器地址栏直接输入translate.google.com或者www.google.com,均会跳转到hangout.google.com,这是google目前的机制么？

**Comment by hcym** [comment]
还是ip问题吧
有些121,125,188的是专门用于hangout

**Comment by ftwcpc** [comment]
@hcym 这可以解释跳转的问题，图片中的错误感觉抓瞎，实在不行只能人工排除可能问题IP了

**Comment by fengixng** [comment]
ip问题，只使用`*.googlevideo.com`，`*.google.com`，`*.c.docs.google.com`这三种证书的ip，其他证书的IP不要使用就行了

**Comment by ftwcpc** [comment]
@fengixng 好的

**Comment by ftwcpc** [comment]
@hcym  @fengixng 谢谢二位的解答
