### ISSUE TITLE
GP r1433问题依旧(奇怪现象 ＃1807   有时无法加载 ＃1806)

### ISSUE THREAD

**Issue by chinagirl1** [phuslu/goproxy#1812]
win7(64位)系统 Google Chrome版本 59.0.3071.109（正

式版本） （64 位） 另外，我已经将*,youtube.com  *.googlevideo.com添加条件为GP了，怎么插件数字老是出现。

![png1](https://user-images.githubusercontent.com/16515138/27387742-24601992-56cc-11e7-9198-5b20d28dfb74.PNG)

![Uploading 捕获.PNG1.PNG…]()

![default](https://user-images.githubusercontent.com/16515138/27387741-24007190-56cc-11e7-8d31-d4f32cd63432.PNG)
![Uploading 捕获.PNG1.PNG…]()

**Comment by Asteroids89** [comment]
代 理用的什么扩展？@chinagirl1

**Comment by chinagirl1** [comment]
小行星 89           chrome插件 Proxy SwitchyOmega

**Comment by AndyLau2017** [comment]
那个不影响的吧

**Comment by AndyLau2017** [comment]
不过看视频会断，而且红黄字不断冒出来

**Comment by Asteroids89** [comment]
@chinagirl1 谢谢

**Comment by kirbyzhu** [comment]
@chinagirl1 建议不要把敏感人物的图片贴出来

**Comment by AndyLau2017** [comment]
@kirbyzhu 为啥？

**Comment by kirbyzhu** [comment]
不为啥，保护goproxy呗

少在坛子里面涉及政治 也是保护社长

**Comment by AndyLau2017** [comment]
@kirbyzhu 噢，我忘了github没有被墙，还是要小心点好

**Comment by Asteroids89** [comment]
只谈技术和问题，莫涉及政治。

**Comment by jasonliul** [comment]
@Asteroids89 
这些玩意其实并非政治, 草民的政治只有民生. 就是管他权贵名流死活, 俺们只顾"打酱油"的精神.
中国大宋朝草民是现代普世平民阶层的前身.

伪政治的作秀, 历史不到700年, 乞丐, 蛮夷, 流氓, 山贼们拿来愚民的. 仅供驴民们嚎叫几嗓子, 牲口为主分忧,  不妨事的~~

让驴们关心于己无干的屁事, 忘却自身的民生幸福, 本来就是目的.

**Comment by AndyLau2017** [comment]
@jasonliul  有深度！！！厉害了

**Comment by SeaHOH** [comment]
掌权者们也许觉得一切尽在手中，其实不尽然。社会的发展跟生物的进化有些相似之处，什么时候会发生剧变，谁都无法准确预料。所谓剧变，就没有**标志性**的征兆，即使有些**预兆**，也是模糊和暧昧的。如果这剧变是进步还好，要是倒退就真是悲哀了。不管是进步还是倒退，我都真心期望这不要发生在我所处的时代，如果一定要变，我希望它是平稳的，有点自私了（似乎还是妄想，感觉自己特消极）。

**Comment by jasonliul** [comment]
@SeaHOH 
你站在错误的角度, 中国的责任在于每一个人.

俺的朋友, 一世实权高官, 却严苛要求, 把子女入籍欧美, 为什么?
文明本身有进化同化, 也有退化异化, 这也是鲁迅先生被遗忘的原因.

在所谓现代中国, 成神败牲, 勿论大神或牲口, 横竖不是人.
所以俺的老友坚持子孙后代去体验正常人类的人生, 总算活得明白... 在这么多年, 对上对下, 坚持做最佳保姆, 人脉可保几代人之后.

**Comment by SeaHOH** [comment]
我就是真草民，还是混得特失败那种，别人看我都是异类，我都不知道自己的三观是怎么就跟别人差这么多……
话说，J 哥你高寿？感觉你经历丰富，沧桑感爆棚，突然有种距离感。

**Comment by jasonliul** [comment]
@SeaHOH 
俺在国外论坛, 他们当俺最经典中国人, 但在国内论坛就是异类.
谁在乎?

俺是基督徒, 追随拿撒勒的潦倒木匠.
作为一个人, 他总是选择自己的路, 订自己的游戏规则走自己的路, 接受这个并不美好世界真实的面孔, 直到终点, 不枉此生.

最初朋友传教, 说些永生, 劈开红海, 俺根本就不以为然.
但是他力邀, 因此俺们查阅了许多历史记载, 找点真实.

以下是真实的, 最起码敌方的记述也没有歪曲.
木匠背着十字架走去刑场, 罗马士兵一路追着鞭笞, 路边有贵族看不过眼, 指责那士兵, 木匠只是笑笑: **"不用责备他, 他只是活不明白."**

**Comment by SeaHOH** [comment]
@jasonliul 
这是被鼓励了嘛，感谢！自怨自艾是不好，我也想坚强点，加油！

**Comment by AndyLau2017** [comment]
当大部分人已经习惯了围墙内的生活，总会有小部分人在想办法把wall推翻，历史的进步总是靠着小部分人的努力而推进，因为大部分人都是旁观者，要让大部队跟着自己走，就要有人做表态。我就特别佩服社长这种从goagnet到goproxy直到现在还在挖wall的实在人，据说社长已经肉身翻wall了？保重安全第一。跬步千里，水滴石穿，你们做的每一小步，都将是民族进步的一大步！

**Comment by phuslu** [comment]
肉翻还没实现，在旧都搬砖呢 https://github.com/phuslu

**Comment by AndyLau2017** [comment]
@phuslu 那社长还是要多注意安全，加油！
