### ISSUE TITLE
刚刚好 Proton VPN 1.0.3

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1813]
![interface png](https://user-images.githubusercontent.com/2461165/27390517-0ea41b1e-56d4-11e7-8abb-a581c0a95417.png)

 Official Website: https://protonvpn.com/
Register/Signup: https://account.protonvpn.com/signup
Login: https://account.protonvpn.com/login/ 

Hosts

    Australia
    Canada
    France
    Germany
    Hong Kong
    Iceland
    Japan
    Netherlands
    Singapore - New
    Spain
    Sweden
    Switzerland
    United Kingdom
    United States

新开VPN, 7天免费试用. 有免费帐户, 不过申明会慢~

**Comment by AndyLau2017** [comment]
可惜了，7天有点短了..
