### ISSUE TITLE
proxy.pac文件怎么添加新网址？

### ISSUE THREAD

**Issue by mymatrix2002** [phuslu/goproxy#1815]
goproxy中选择使用http://127.0.0.1:8087/proxy.pac，然后想在proxy.pac增加一个被墙的网址，该怎么修改proxy.pac这个文件啊？

我在新生成的proxy.pac中添加字段：
var sites = {
"breakwa11.github.io":1
};
后保存重启goproxy，依然不能访问这个网站。

求大神指导。

**Comment by MeABc** [comment]
搜一下 issues ，我印象中自已回复过几次这个问题了。

**Comment by mymatrix2002** [comment]
@MeABc 看过你以前的回复，你提到将autoproxy.json中"GFWList"的"Enabled"设为false，并将gfwlist.txt中的网址复制到proxy.pac中，这样就能走pac，但我并不想这样，因为考虑到gfwlist.txt要是更新的话就不知道了。
既然社长在软件中可以使用pac的话，那么应该有一个增加新网址的规则或方法吧。
求社长解释一下，谢谢。 @phuslu

**Comment by MeABc** [comment]
我可能也是把问题想复杂了。。。

```
var sites = {
"breakwa11.github.io":1
};
```

楼主，你的意思是在 proxy.pac 里写了上面的语句，重启依然不能访问这个网站是不？如果是这样的话，那问题简单了。。。

1. pac 文件是使用 javascript 语言，所以，你得懂 javascript 语法。
2. 根据 javascript 语法，你上面语句不会有任何的输出。
3. 修改 proxy.pac 文件后，除了重启 goproxy 外，还要在浏览器里，重载 pac 规则。

**Comment by MeABc** [comment]
> 根据 javascript 语法，你上面语句不会有任何的输出。

意思是，你还要进行判断走哪个代理或直接，只定义一个变量是不会作任何动作的。具体 google 。

**Comment by Kisesy** [comment]
写法挺多的
```js
var sites2 = {
	"breakwa11.github.io":1,
}

// User-defined FindProxyForURL
function FindProxyForURL(url, host) {
    if (isPlainHostName(host) ||
        isInNet(host, "10.0.0.0", "255.0.0.0") ||
        isInNet(host, "172.16.0.0", "255.240.0.0") ||
        isInNet(host, "169.254.0.0", "255.255.0.0") ||
        isInNet(host, "192.168.0.0", "255.255.0.0") ||
        isInNet(host, "127.0.0.0", "255.255.255.0") ||
        shExpMatch(host, "*.local") ||
        shExpMatch(host, 'localhost.*')) {
        return 'DIRECT';
    }

	// 下面几种都可以
    if (
		dnsDomainIs(host, "github.io") ||
		host == "breakwa11.github.io" ||
		sites2.hasOwnProperty(host) ||
		shExpMatch(host, '*.google*.*')) {
        return "PROXY 127.0.0.2:8087";
    }

    return 'DIRECT';
}
```

**Comment by Kisesy** [comment]
要论效率 hasOwnProperty 可能是最高的
现在的 pac 有缺陷，无法定义白名单，而且因为这个，即使判定到了 127.0.0.1 这类地址，还是会走一遍gfwlist (大概吧

**Comment by mymatrix2002** [comment]
@Kisesy @MeABc 我后来改成了这样，是参照http://127.0.0.1:8087/proxy.pac写的，请帮忙看看这样是否正确？
// User-defined FindProxyForURL
function FindProxyForURL(url, host) {
    if (isPlainHostName(host) ||
        isInNet(host, "10.0.0.0", "255.0.0.0") ||
        isInNet(host, "172.16.0.0", "255.240.0.0") ||
        isInNet(host, "169.254.0.0", "255.255.0.0") ||
        isInNet(host, "192.168.0.0", "255.255.0.0") ||
        isInNet(host, "127.0.0.0", "255.255.255.0") ||
        shExpMatch(host, "*.local") ||
        shExpMatch(host, 'localhost.*')) {
        return 'DIRECT';
    }

    if (shExpMatch(host, '*.google*.*')) {
        return 'PROXY 127.0.1.2:8087';
    }

    return 'DIRECT';
}

// AUTO-GENERATED RULES, DO NOT MODIFY!
var autoproxy_host = {
    "breakwa11.github.io": 1
}

function FindProxyForURLByAutoProxy(url, host) {
    if ((Q = MyFindProxyForURL(url, host)) != "DIRECT") {
        return Q
    }

    var lastPos;
    do {
        if (autoproxy_host.hasOwnProperty(host)) {
            return 'PROXY 127.0.0.1:8087';
        }
        lastPos = host.indexOf('.') + 1;
        host = host.slice(lastPos);
    } while (lastPos >= 1);
    return 'DIRECT';
}

另外，发现一个情况，FindProxyForURL(url, host)这个地方如果是从http://127.0.0.1:8087/proxy.pac中查看的话就会变成MyFindProxyForURL(url, host)，因此我将Q定义为MyFindProxyForURL(url, host)，不知道这样对不对？

**Comment by MeABc** [comment]
1. 你改后能正常用不。能用就行。（怎么改都可以，能用就行。）

2. 

> 发现一个情况，FindProxyForURL(url, host)这个地方如果是从 http://127.0.0.1:8087/proxy.pac 中查看的话就会变成MyFindProxyForURL(url, host)

这不是什么新情况。程序设计如此。如果不改，就会两个同名函数。

**Comment by MeABc** [comment]
认真看了下你改后的结果，再补充。（你改后能用不，我也没有具体试，但目测不能用或者说没有效果吧）

3. 也是补充第一点。你改了要自己测一个下有没有效果。

看你的回复，你是不是想用这种格式

```javascript

var sites2 = {
	"breakwa11.github.io":1,
}

或者

var autoproxy_host = {
"breakwa11.github.io": 1
}

```

如果是的话，那在你还没有真正搞明白之前，我建议你还是用上面 Kisesy 的例子先写一份能用的出来。等你全搞明白了，再大改。

**Comment by SeaHOH** [comment]
@mymatrix2002 
>// AUTO-GENERATED RULES, DO NOT MODIFY!

你的修改不要放在这行之后，会被更新覆盖。所有修改都要在这行之前，就像 Kisesy 主任写给你的例子一样。

**Comment by mymatrix2002** [comment]
好的，非常感谢各位的意见和指导 。
目前我在使用Kisesy的方法，感觉代码比较简洁。
