### ISSUE TITLE
社长的项目怎么突然没有了？

### ISSUE THREAD

**Issue by mymatrix2002** [phuslu/goproxy#1818]
昨晚还好好的，突然所有相关goproxy 的内容都没有了，也没了下载，什么情况？

**Comment by lxok89** [comment]
我也刚发现。难道。。。。。。？

**Comment by out0fmemory** [comment]
默认分支变成ophan了，，，，，应该是master，故意设置的？ @phuslu

**Comment by lxok89** [comment]
@out0fmemory 社长低调起见，减少麻烦。

**Comment by phuslu** [comment]
谢谢关心
