### ISSUE TITLE
GP复活, 来来来, 狗友齐齐升级r1465

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1819]
社长口谕:
r1450 也把 quic 的重试策略应用到了之前的 tls 上了。
这样使用 tls 的话，也会减少 "dial timeout" 这类错误出现的机会了。

其实这个变化蛮大, 跑满速需要一些时间, 但是阿狗从来没有这样平稳皮实.
即使在局域网, 力扛其他用户p2p下载.

社长近日伯虎附体, 真是才情汹涌~~
赞!!!

**Comment by SeaHOH** [comment]
顶

**Comment by kirbyzhu** [comment]
一怒之下不精炼ip了 把以前攒的1万多个重新填进去

**Comment by hcym** [comment]
顶顶

**Comment by jasonliul** [comment]
来段视频, 试试狗~~~
https://youtu.be/1zaHVucS_Sk?list=LLQ4xGnSfjNiFJ4NfH1cDySA

**Comment by yDan** [comment]
升级这个是不是每次都要手动下载最新版的？不能像以前那样用“get-latest-goproxy.cmd”这个脚本来升级？

**Comment by jap33** [comment]
怎么这段视频只能放五秒钟。

**Comment by phuslu** [comment]
get-latest-goproxy.cmd 设计成只会升级到所谓的“稳定版”，而 r1450 还未被我标志成稳定版。

所以暂时不能自动升级。

**Comment by jasonliul** [comment]
@jap33 
大大好久不见, 想念得紧

红包拿来~~~
纸飞机邀请码

**Comment by jyuan15** [comment]
那段视频放不出来，卡的一比，DASH是no



![2017-06-25_113414](https://user-images.githubusercontent.com/12642186/27513498-cd16e6da-599a-11e7-9bf2-b4687c27d70d.jpg)

**Comment by MeABc** [comment]
@jyuan15 

> 为什么要全局才能上传成功图片？

你是指 youtube 上传吗？

**Comment by MeABc** [comment]
不试不知道，想试一下， google 登陆出错了。。。

反复试了几遍，密码回车后就出现这个。。。有没有人出现这个呀，我想对比下是不是我的问题。。。

![default](https://user-images.githubusercontent.com/18194126/27513874-201d3c30-59aa-11e7-9261-1cdcbe2f475e.png)

**Comment by jasonliul** [comment]
木有问题~

**Comment by phuslu** [comment]
貌似是新该出的bug， 我看看

**Comment by MeABc** [comment]
呃。。。个人个案了。。。

我看下是我哪里的问题。

**Comment by MeABc** [comment]
社长来了，那补充一下， 登陆时没有用 QUIC ，goproxy 日志是显示 POST 出错。

**Comment by jyuan15** [comment]
@MeABc 不，就是这里传图

**Comment by MeABc** [comment]
@jyuan15 
因为 github 的很多网址默认都不走 gae 的，所以一有点网络问题就上传不了。

**Comment by boycc1974** [comment]
![default](https://user-images.githubusercontent.com/18365033/27514289-e8a0b426-59b8-11e7-8b26-0c6cdd69878c.jpg)

**Comment by xyuanmu** [comment]
goproxy 现在速度很给力，IP基本都不会挂

**Comment by blob2015** [comment]
@xyuanmu @jap33 
两位现在都忙啥呢 😀

**Comment by xyuanmu** [comment]
@jasonliul 换个头像就不认识我了，桑心
@blob2015 现在工作忙啊

**Comment by jasonliul** [comment]
@xyuanmu 
你红男变绿女, 一定有古惑~~

**Comment by wpyok500** [comment]
贺贺

**Comment by chinagirl1** [comment]
出现
![Uploading 捕获.PNG…]()

**Comment by chinagirl1** [comment]
![default](https://user-images.githubusercontent.com/16515138/27516332-8e193820-59ea-11e7-9465-8b62ac62443c.PNG)

**Comment by phuslu** [comment]
这个应该是 ip 里面混入了不少非 gws/gvs 的 IP. （这些 IP 曾经是，但是现在不是了）

**Comment by blob2015** [comment]
除此以外，还有可能网络环境恶劣如我，堵塞了……

**Comment by chinagirl1** [comment]
@phuslu 所有ip都是经过MotherFuckerFang测试的。我还有个问题。chrome插件Proxy SwitchyOmega选gp自动时出现几个资源未加载。当点选添加条件为gp(其实已经添加了，就是总会出现未加载)是就出错。何解？

**Comment by chinagirl1** [comment]
![default](https://user-images.githubusercontent.com/16515138/27516581-4cc7c62a-59ef-11e7-88b2-e0fb22b81bc8.PNG)
![png1](https://user-images.githubusercontent.com/16515138/27516583-4d68bef4-59ef-11e7-9d16-811f6a3b679d.PNG)
![png2](https://user-images.githubusercontent.com/16515138/27516582-4cd4b272-59ef-11e7-8f45-97fc2d6cb16f.PNG)

**Comment by SeaHOH** [comment]
`live.github.com` 要直连

**Comment by phuslu** [comment]
r1453 进一步优化了 quic 的卡顿问题。(其实是在 phuslu/quic-go 修的。。。）

目前 bug 所剩无多，目测十天半个月后就可以进入 quic 性能提升环节了 😄

**Comment by ax003** [comment]
哪里升级呢？

**Comment by jasonliul** [comment]
@xyuanmu @jap33 
休走~~~
快回来升级.

**Comment by MeABc** [comment]
@phuslu 
社长，上面那个 google 登陆不了的问题，你有看不？

**Comment by phuslu** [comment]
啊，还没开始看呢。我尽快看下

**Comment by phuslu** [comment]
啊，试了一下。我这边不能复现。你访问一下 https://www.google.com/ncr 然后再尝试登陆 google 试试？

**Comment by MeABc** [comment]
用 ncr 试了，没有效。

奇怪的是，即使出现错误，但实际上是登陆了。（新开一个标签页）

但， youtube 不认可这种登陆方式。。。
--

那就是我自己个案了，我再看看。

**Comment by kirbyzhu** [comment]
社长的效率惊人！

**Comment by SeaHOH** [comment]
因为是 UDP 流量

**Comment by invincibility** [comment]
通过谷歌chrome搜图的功能不行了，社长弄弄？
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1450 (go/devel +9b7ad338a1 Sat Jun 24 13:59:28 2017 +0000 windows/amd64)",
    "filter": "*gae.Filter",
    "error": "http: invalid Read on closed Body"
}

**Comment by endlessX** [comment]
嗯，跟楼上一样，也遇到"error": "http: invalid Read on closed Body"的问题

**Comment by phuslu** [comment]
嗯，我在谷歌人机验证的时候也遇到了。应该是新改出的bug。

会尽快修复。

**Comment by smovie** [comment]
同楼上，开不开quic都是这个错："error": "http: invalid Read on closed Body"

**Comment by jasonliul** [comment]
@phuslu 
俺没有遇见这类错误, 火狐~

**Comment by phuslu** [comment]
r1454 已经修复上一个错误。

**Comment by xyuanmu** [comment]
这更新速度，可以

**Comment by phuslu** [comment]
好说，得益于 go 1.9 (tip) 的一个重大改进（并行化编译），goproxy 的每次自动构建时间现在缩短到 5 分钟左右了。

见 https://travis-ci.org/phuslu/goproxy/builds

**Comment by hcym** [comment]
试了试1454确实没卡过

**Comment by phuslu** [comment]
其实还有卡顿，我正在逐步排查 quic-go 的代码，争取这几天都修掉。

**Comment by blob2015** [comment]
@phuslu 
社长真是太强大了，俺连JavaScript都搞不定呢 😀

**Comment by lsnmx** [comment]
@phuslu  社长启用前置代理后，EnableQuic不能开启啊？

Pac Server         : http://127.0.0.1:8087/proxy.pacF0627 13:44:16.844262    6980 gae.go:266] EnableQuic is conflict with Proxy setting!

**Comment by phuslu** [comment]
quic-go 目前还不支持代理，我看了一下代码支持代理还是比较复杂的。所以目前只能禁用了。

**Comment by jasonliul** [comment]
使用帽架没有问题的,
例如Sockscap64

**Comment by lsnmx** [comment]
@phuslu  好的谢谢，如果可以后续EnableQuic支持一下代理，测试过如果不开EnableQuic，纯IP不用代理，完全翻不了出去，启用EnableQuic后不用代理，同样的IP居然全活了，EnableQuic性能确实有等提升，不过速度算过得去了，社长真牛逼啊！
还是希望后续EnableQuic支持代理，套上上前置SS代理不用折腾IP省事，上谷歌的网站比较多还是GP比较快的，直接SS翻有时直接卡死

**Comment by SeaHOH** [comment]
其实前置代理就没必要用 QUIC 了，反正有 HTTP2，而且即使真要用，就象杰哥讲的用 Sockscap64 之类，就不用专门支持了，这样社长也省点精力（潜台词就是继续加油优化其它部分啦）。

**Comment by phuslu** [comment]
@SeaHOH 谢谢。

感觉 tls1.3 跳票之后，quic 协议正在带一波节奏。

这有个 c 库 https://github.com/ngtcp2/ngtcp2 很有潜力能成为 node/python 的 quic 绑定。

**Comment by phuslu** [comment]
ngtcp2 的作者 tatsuhiro-t 也是 nghttp2 的作者，质量和功能应该不用担心。

**Comment by jasonliul** [comment]
@SeaHOH 
俺袜子了几天, 其实或许比直接用GP还要好.
下载方面强大很多.

而且并不觉得连接慢多少, 袜子合适, 几乎没有感觉差别

**Comment by hcym** [comment]
喜欢简单粗暴，最近heroku不用前置也不错
加上gce，偶尔quic
什么鞋子袜子的头大

**Comment by lsnmx** [comment]
@SeaHOH 我只请求社长，个人需求不一样嘛，启用EnableQuic干扰少很多，也快，Sockscap64用过没GP原生支持好

**Comment by SeaHOH** [comment]
@phuslu 
其实我搜遍了网络也没发现完整可用的纯 Python 实现，也没有现成的编译好的 library。
手头没有编译工具……以前安装的被我搞坏了，其实也没咋用，所有懒得再装了。
>很有潜力能成为 node/python 的 quic 绑定

希望这个工作能有人快点完成。

@jasonliul 
我还以为你光搜不用呢，尽拿来博爱了。 :smile_cat: 

@lsnmx 
原生支持当然好啦，这不感觉社长进来还挺忙的嘛，估计真搞前置要等很久了。

**Comment by jasonliul** [comment]
@SeaHOH 
GP一开始支持前置就比GP强得多.
呃~~ 总有自私的家伙重启路由器, 不时只能从帽架启动~~

GP本身CPU占用就不小, 纸飞机前置的阔佬信口, 可以无视~

**Comment by SeaHOH** [comment]
我语文不好，你不要诓我，阔佬能无视么，巴结下也许我也可以用用。

@lsnmx 开玩笑啦，你还不如直接用社长的 vps 服务端搭，重用特性很好的。

**Comment by lsnmx** [comment]
@SeaHOH 没事啦，我只是表达清楚，我不是一味跟社长要这样哪样，vps的GP服务端没用过，我个人是现在自己搞马云的国际版，19美金，1T流量的VPS搭SS，用GP主要是浏览谷歌的应用多没办法啊，用GP后走的是谷歌全球的网络，一个快，一个GP有autorange不至于像SS一样，时不时卡死

**Comment by MeABc** [comment]
说到 autorange ，不得不说一下社长，从我没结婚等到我结婚，你总不能让我再等到我儿子结婚还没搞好吧。。。 :trollface:

**Comment by phuslu** [comment]
汗，好吧。主要 autorange 用 go 写起来巨烦，我得找个好心情再加沐浴焚香，才能搞定它 :trollface:

**Comment by jasonliul** [comment]
@MeABc 
阿呀, 你网名取得像卫生棉也就罢了~~
居然在社长夏风得意之际, 前来添堵, 咪走........................

![spank gif](https://user-images.githubusercontent.com/2461165/27577521-97b4f152-5b53-11e7-99b0-b54fa50e15cf.gif)

**Comment by MeABc** [comment]
我哪儿是添堵嘛。。。只不过是时不时的提醒一下社长。。。 😄

**Comment by jasonliul** [comment]
@MeABc 
对错是非, 二进制0与1, 那是专供所谓人脑做事机的.
做人, 先同乐社长之乐...带上啤酒~~

孔老师曰: 看人, 别看事. 你也是斯文人, 怎生如此婆妈?

**Comment by MeABc** [comment]
斯文人？第一次被人这样说，窃喜中。。。

**Comment by blob2015** [comment]
@MeABc 
abc兄竟然结婚了，恭喜，不用窃喜了啦 😀 
autorange除了巨烦，估计也是社长较少下东西，没有需求，就少动力啊 😀

**Comment by jasonliul** [comment]
@MeABc @blob2015 
你两个成日在社长的牡丹花丛晒内裤, 社长那有动力?

**Comment by MeABc** [comment]
@blob2015 

写文章不都是这样举例子的吗？就是举个例子，不要当真。。。。

**Comment by houhuliang** [comment]
有木有人遇到程序卡死的现象？goproxy界面直接黑屏了
![image](https://user-images.githubusercontent.com/6376086/27582028-0c15eade-5b62-11e7-8e63-c5153f707f99.png)

**Comment by jasonliul** [comment]
@phuslu 
社长, 俺似乎觉得开启Quic,  中国谷歌ip就全废.
既然中国谷歌ip都完好, 能否开启quic仅仅用于"google_hk"里面的ip

而"google_cn"内的ip仍沿其旧?

**Comment by phuslu** [comment]
@jasonliul 比较困难，暂时想不到太好的解法。等我把 quic 卡顿问题修得差不多再来看看。

**Comment by hcym** [comment]
不急不急了
ss足够一年的余粮

**Comment by jasonliul** [comment]
@phuslu 
一时怪想, 社长某日想异类时再玩不迟~~
:)

**Comment by immeman** [comment]
get-latest-goproxy.cmd在默认升级稳定版的同时，希望能给一个可以升级最新版的选项，现在版本更新得有点快

**Comment by MeABc** [comment]
@jasonliul @phuslu 

![default](https://user-images.githubusercontent.com/18194126/27774398-2795c0e8-5fc4-11e7-95dd-ddcd2f846a4e.png)

国内的已支持 QUIC 了。社长还是安心解决其它问题。。。。 😄

**Comment by MeABc** [comment]
我发这里好了。

![default](https://user-images.githubusercontent.com/18194126/27824581-858695a8-60df-11e7-9a66-35202426ea02.png)

这个是抓包 chrome 连 www.google.cn 的图。

我的意思是：如果 goproxy 能模拟这两项就更好了。

@phuslu 社长，你参考下。

**Comment by phuslu** [comment]
不是很明白。指定这两项的目的是。

我自测 curl -v -x 127.0.0.1:8087 https://www.google.cn 已经是可以访问的啊。

**Comment by MeABc** [comment]
![default](https://user-images.githubusercontent.com/18194126/27825573-94d9f254-60e2-11e7-9a2f-df17523eec02.png)

这是测试 quic-go 例子图。默认他应该是用 37 版本号。而 Agent 这个还知道默认是什么。。。

**Comment by jasonliul** [comment]
@MeABc 
嘢~~
这样开房私聊更好. :)

**Comment by jasonliul** [comment]
GP已经复活了~~~
狂笑中

**Comment by MeABc** [comment]
20170710 更新：

quic-go 默认没有设置 UAID 这个 Tag 。

（PS：我拿这帖当做笔记好了。。。）

**Comment by wpyok500** [comment]
@phuslu  autorange准备开进了吗？
