### ISSUE TITLE
goproxy的vps版怎么用？

### ISSUE THREAD

**Issue by darkred424** [phuslu/goproxy#182]
按照之前在google code上的issue（ https://code.google.com/p/goagent/issues/detail?id=22361 ），似乎是只要解压release里govps的包然后运行里面的可执行文件，然后在Chrome加启动参数就可以了。我照做之后vps这边显示如下错误信息（ip和端口被我替换了）：
TLS handshake error from IP:PORT: tls: oversized record received with length 20037
这是什么原因呢？是需要在vps上配置go环境还是要做什么别的操作？我是在Mac Yosemite上操作的，确认启动参数是添加成功了的，因为启动的时候Chrome有警告。

好吧，我白了……是SwitchOmega里面的HTTPS代理设置弄成HTTP了……

**Comment by ren2014311** [comment]
解压，执行sudo ./vps 没了，端口是443，

**Comment by mhohai** [comment]
but it's listen on ipV6, Can I config it on govps.service?  @ren2014311
