### ISSUE TITLE
关于 Cipher，AES_GCM 不能用么？

### ISSUE THREAD

**Issue by hyxxsfwy** [phuslu/goproxy#1820]
看社长的 QUIC 开发的这么给力，又想着来折腾下 GP 了。开启 QUIC 的效果如社长所言，连通率高，吞吐量上不去，偶发卡顿。于是再试试开启 H2，发现一开 H2，基本就连不上了，与服务器握手失败……
感觉是加密方式的问题，于是在配置文件里把 Cipher 指定为 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256，发现这下可以连接了，而且 good ip 也涨了一大截，看着是好事呀。
然而， Cipher 一改，似乎很多 IP 就没法转发 GAE 的请求了，访问直连的 Google 域名没问题，要经由 GAE 代理的时候就报错(405)。是不是 gvs 不支持 AES_GCM 加密模式下作为 GAE 的前端代理呀。

**Comment by phuslu** [comment]
嗯，quic 的卡顿还在优化。

gvs 目前只能以 aes-cbc 的方式使用

**Comment by blob2015** [comment]
mark，姿势
