### ISSUE TITLE
youtube用gp总是打不开，ssr正常

### ISSUE THREAD

**Issue by chinagirl1** [phuslu/goproxy#1823]
win7 64位      google chrome版本 59.0.3071.109（正式版本） （64 位）
![default](https://user-images.githubusercontent.com/16515138/27592436-14353d76-5b87-11e7-9459-94cddba119d0.PNG)
![png1](https://user-images.githubusercontent.com/16515138/27592437-143b9e46-5b87-11e7-83fd-980e393e2696.PNG)
![png3](https://user-images.githubusercontent.com/16515138/27592439-144173de-5b87-11e7-80ee-701e1e2fdde8.PNG)

**Comment by pgz123** [comment]
+1

**Comment by pgz123** [comment]
lookup 115.87.71。53: getaddrinfow: No such host is known.
I0627 22:40:25.281250    1492 resolver.go:85] LookupIP("115.87.71。53") r
], err=lookup 115.87.71。53: getaddrinfow: No such host is known.
W0627 22:40:25.286132    1492 dialer2.go:60] LookupHost("115.87.71。53")
lookup 115.87.71。53: getaddrinfow: No such host is known.
I0627 22:40:25.310546    1492 resolver.go:85] LookupIP("115.87.71。53") r
], err=lookup 115.87.71。53: getaddrinfow: No such host is known.
W0627 22:40:25.315429    1492 dialer2.go:60] LookupHost("115.87.71。53")
lookup 115.87.71。53: getaddrinfow: No such host is known.
I0627 22:40:25.323242    1492 resolver.go:85] LookupIP("115.87.71。53") r
], err=lookup 115.87.71。53: getaddrinfow: No such host is known.
W0627 22:40:25.329101    1492 dialer2.go:60] LookupHost("115.87.71。53")
lookup 115.87.71。53: getaddrinfow: No such host is known.
I0627 22:40:26.143554    1492 resolver.go:85] LookupIP("115.87.71。53") r
], err=lookup 115.87.71。53: getaddrinfow: No such host is known.
W0627 22:40:26.148437    1492 dialer2.go:60] LookupHost("115.87.71。53")
lookup 115.87.71。53: getaddrinfow: No such host is known.
I0627 22:40:29.570312    1492 resolver.go:85] LookupIP("115.87.71。53") r
], err=lookup 115.87.71。53: getaddrinfow: No such host is known.
W0627 22:40:29.576171    1492 dialer2.go:60] LookupHost("115.87.71。53")
lookup 115.87.71。53: getaddrinfow: No such host is known.

**Comment by phuslu** [comment]
还是 ip 问题。
