### ISSUE TITLE
是否接受捐赠？

### ISSUE THREAD

**Issue by summerdaydream** [phuslu/goproxy#1824]
12年开始先用goagent，到后来开始用XXNET不过还是基于goagent。如果作者愿意接受捐赠的话，虽然钱不多但也想表示一下感谢。

**Comment by phuslu** [comment]
非常感谢，暂无计划。

**Comment by MeABc** [comment]
这个可以有。支持匿名的最好。

**Comment by ruby186** [comment]
我们凑1BTC为社长买个145的小蝶吧：）
