### ISSUE TITLE
facebook在我这里被解封了，youtube也可以直接上去，只是不传送视频内容

### ISSUE THREAD

**Issue by sundaqing1969** [phuslu/goproxy#183]
湖南电信

**Comment by shindaren** [comment]
吹你麻痹

**Comment by wenliyang** [comment]
墙会偶而抽风的，一般这种情况后是更严重的封锁

**Comment by sundaqing1969** [comment]
![9](https://cloud.githubusercontent.com/assets/13601611/9736135/240ae942-5672-11e5-869a-1c368889589e.PNG)
另外有网友也出现同样情况
