### ISSUE TITLE
发现一个问题，

### ISSUE THREAD

**Issue by zdf0145** [phuslu/goproxy#1832]
直接在地址栏搜索（默认google）,
![image](https://user-images.githubusercontent.com/12776587/27730189-014795ca-5dbb-11e7-9e7a-b7248c399416.png)
刷新就正常

**Comment by dou4cc** [comment]
确实是gop的问题，如果gop直接切断和浏览器的连接而不是返回5xx，chrome自己就重试了

**Comment by blob2015** [comment]
这个问题不是这样才会触发，有段时间停歇就会触发，好像，给你配一张图吧：
![hs0079](https://user-images.githubusercontent.com/12381704/27739132-2644409c-5de0-11e7-96b3-9d1d2d6656c3.png)
