### ISSUE TITLE
quic支持判定

### ISSUE THREAD

**Issue by linhua55** [phuslu/goproxy#1833]
61.238.239.209  为gvs ip

>curl -kI https://61.238.239.209

    HTTP/1.1 404 Not Found
    Date: Fri, 30 Jun 2017 18:29:29 GMT
    Content-Type: text/html; charset=UTF-8
    Server: gvs 1.0
    Content-Length: 1561
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: SAMEORIGIN

>curl -kI https://61.238.239.209 --ciphers ECDHE-RSA-AES256-GCM-SHA384

    HTTP/1.1 301 Moved Permanently
    Location: http://www.google.com/
    Content-Type: text/html; charset=UTF-8
    Date: Fri, 30 Jun 2017 18:24:46 GMT
    Expires: Sun, 30 Jul 2017 18:24:46 GMT
    Cache-Control: public, max-age=2592000
    Server: gws
    Content-Length: 219
    X-XSS-Protection: 1; mode=block
    X-Frame-Options: SAMEORIGIN
    Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"

**Alt-Svc: quic=":443"; ma=2592000; v="39,38,37,36,35"**

https://imququ.com/post/http-alt-svc.html
@phuslu

**Comment by SeaHOH** [comment]
社长早就知道了……

**Comment by tec1987** [comment]
在远程TCP 443端口无法连接的情况下，这么做没有什么意义，还是超时。。。

**Comment by itaintbld** [comment]
我想写个扫quic的工具，，，
有人在做吗？会不会重复造轮子。

**Comment by SeaHOH** [comment]
那就做个有创意的轮子，丰富生态环境嘛。

**Comment by SeaHOH** [comment]
那就上 https://www.zoomeye.org/ 搜，社长推荐，方便的一笔！

**Comment by linhua55** [comment]
@SeaHOH 
看来 我火星了
