### ISSUE TITLE
warmingf...@gmail.com 大大: Akamai 节点前置

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1834]
warmingf...@gmail.com 大大原创
softw...@gmail.com 大大整理

除了赛风这个必备软件之外，还需要 Proxifier 这个软件来达到目的，这是商业软件，不过破解版在网上也是比较容易找到的。3.28 版本在 Windows 8/8.1 下可能有问题，锁不住赛风的进程之类的，推荐使用 3.21 版本。
安装并输入注册码激活后，建议重启下操作系统，否则后面的步骤可能不成功。还有，在 Proxifier 中订制规则强制赛风使用 Akamai CDN 服务前，请先运行下赛风，保证它是可以连接上服务器的。我曾经碰到过在 Proxifier 中订制规则前没有运行过赛风，结果赛风根本连不上服务器的情况..

我在MEGA网盘上传了附带注册机的版本

3.21

https://mega.co.nz/#!x4AHBSDT!FxxNVrdjU9TNDu2G65f-pfLPLgfaHchdrYZBdsZ2VX0

3.28

https://mega.co.nz/#!R95EhTxb!RIKkg-AV3oR7ROEkrz9RS-RWFQxWtNWCxUZdH5Xlhy0

第一步、订制规则（这里就直接借用 warmingf...@gmail.com 的截图了）

规则1使 *.akmaihd.net 直连
https://i.imgur.com/IUvNSgl.jpg

注意如果使用的是 Proxifier 3.28 版本，这里的 Applications 里要填写：psiphon3.exe;psiphon-tunnel-core.exe，否则可能在软件里看不到赛风的进程

规则2使赛风访问其他服务器IP被屏蔽
https://i.imgur.com/K3m3HCa.jpg

要确保规则1在规则2上面，否则就失效了
https://i.imgur.com/gfnYeKz.jpg

并让 Proxifier 处理直连的程序，这样做使网络情况更直观
https://i.imgur.com/nfXu2ab.jpg

小Tips：
1.在 Applications 框里填写时，不需要点 Browse... 按钮找，直接复制粘贴：psiphon3.exe;psiphon-tunnel-core.exe 及 psiphon-tunnel-core.exe 进去就行了
2.订制好规则后，可以保存，并导出为配置文件，卸载重装等情况下再导入即可

保存：File -> Save Profile As...
导出：File -> Export Profile...
导入：File -> Import Profile...

第二步、修改本机 hosts 文件，加一行

210.0.156.15    yryirjrhqffsxwpg-a.akamaihd.net

注意 210.0.156.15 这个IP地址是 warmingf...@gmail.com 给出的，他用这个IP速度很快，你就不一定了，还需要更换IP地址，方法后文会讲。

小Tips：修改 hosts 文件后，是不会立即生效的。想生效，方法有二
1、重启计算机（这...改次 hosts 文件就要重启一次，SSD硬盘还好，要用的机械硬盘，那重启一次得等好长时间啊，所以还有方法2）
2、按 Win + R 键调出“运行”对话框，输入：cmd，回车，在弹出的命令行窗口中，输入：ipconfig /flushdns，回车

对了，在用上述方法2之前，请关闭浏览器，做完再打开，再试通过赛风上网速度是否变快了

这个方法的关键在于 Proxifier 这个软件，这个软件很强大，可以让不自带代理服务器设置的软件通过代理服务器连网，可以让软件只能连接某地址，等等。
说这个方法比较复杂，问题也出在 Proxifier 这个软件上，比如在进程里找不到赛风的 psiphon-tunnel-core.exe，比如造成系统网络问题。我已经碰到过几次因为 Proxifier 这个软件造成无法上网只能重启系统了，所以在用第2种方法成功后就卸载了这个软件。

----------------------------------------------------------------------

再来说方法2，这次要用到 3proxy 这个俄罗斯人写的软件。说到这个软件，我以前在用地下铁路时用过它（不知道现在还有多少人记得“地下铁路”了，曾经广发邀请码搞得象传销一样...）

1、下载 warmingf...@gmail.com 已经做好基本设置的 3proxy 软件
https://copy.com/pU0aZGd0oBsAigwS/3proxy.7z
（注意压缩包加密了，否则copy.com会报有病毒不让分享，解压密码：goagent）

我在MEGA网盘上也传了一份，压缩包未加密：
https://mega.co.nz/#!QloC1LLL!8RAcPdwMOGH0SfpBW_De2yoXVYn8-FVE98OIDb5VctE

2. 解压，编辑 config.txt 这个文件以修改其中的 Akamai IP 地址为在你的网络环境下表现好的 IP 地址，不修改默认是 210.0.156.15
3. 打开 3proxyLauncher.exe （修改自 Phus Lu 的开源 goagent.exe ）
4. 打开赛风，做如下操作 https://i.imgur.com/lNo4bnu.jpg
5. 关闭赛风，重新打开赛风

最后，如果你选用的香港服务器IP，建议在赛风里将服务器改成：Singapore（新加坡），速度会更快点

这个方法简单不少吧，不用改 hosts，系统也不会出现奇怪的网络问题，推荐使用。

那为啥还要方法一呢。方法还是多点比较好吧，而且你喜欢研究的话，Proxifier 还是蛮有用的。

----------------------------------------------------------------------

好了，现在还有一个问题，前面说过要找更适合自己的IP地址，怎么找呢，可以用 checkgoogleip 或 gogotester，虽然看软件名字都是找 Google 可用IP的，但也能用来找其它的IP

我用的是 checkgoogleip，说下方法

用记事本打开 checkip.py 这个文件，找到这些内容：（注意*号是为了显示更醒目些，原文件里是没有的）
*********************************************************************************
ip_str_list为需要查找的IP地址，第一组的格式：
1.xxx.xxx.xxx.xxx-xx.xxx.xxx.xxx
2.xxx.xxx.xxx.xxx/xx
3.xxx.xxx.xxx.
4 xxx.xxx.xxx.xxx
5 xxx.xxx.xxx.xxx-xxx

组与组之间可以用换行相隔开,第一行中IP段可以用'|'或','
获取随机IP是每组依次获取随机个数量的，因此一组的IP数越少，越有机会会检查，当然获取随机IP会先排除上次查询失败的IP
"""
ip_str_list = '''
*********************************************************************************
然后接着就是很多IP了，把这些IP都删了，然后把待测试的 Akamai CDN 服务器IP粘贴进去（当然要先改成软件允许的格式），完成后这个样子的

ip_str_list = '''
（这里是你粘贴进来的 Akamai CDN 服务器IP地址）
'''

最后，给出一些 Akamai CDN 服务器IP地址，有空慢慢扫吧 :)

香港
203.78.32.0-255
203.186.47.0-255
203.78.36.0-255
210.0.146.0-255
110.4.12.0-255
203.78.42.0-255
175.45.42.0-255
210.0.156.0-255
202.40.221.0-255
110.4.24.0-255
180.150.145.0-255

澳门
202.175.16.21|45.64.21.19|45.64.21.10|45.64.21.11|45.64.21.4|45.64.21.16|45.64.21.25|45.64.21.6|45.64.21.28|45.64.21.12|45.64.21.14|45.64.21.41|45.64.21.24|45.64.21.32|45.64.21.7|45.64.21.17|45.64.21.34|45.64.21.33|45.64.21.9|45.64.21.29|45.64.21.35|45.64.21.26|45.64.21.27|45.64.21.15|45.64.21.21|45.64.21.18|202.175.5.101|45.64.21.8|45.64.21.36|45.64.21.37|45.64.21.40|202.175.5.105|202.175.5.114|202.175.5.122|202.175.5.173|202.86.161.15|202.175.5.117|202.175.5.118|202.175.5.154|202.175.5.148|202.175.5.98|202.175.5.178|202.175.5.150|202.175.5.106|202.175.5.94|202.175.5.95|202.175.30.162|202.175.5.93|202.175.5.99|202.175.5.175|202.175.5.104|202.175.5.107|202.175.5.96|202.175.5.100|202.175.5.102|202.175.5.120|202.175.5.174|202.175.5.121|202.175.5.176|202.175.5.110|202.175.5.97|202.175.5.152|202.175.5.153|202.175.5.167|202.175.5.112|202.175.5.113|202.175.5.115|202.175.5.171|202.175.5.172|202.175.5.177|202.175.5.179|202.175.5.92|202.175.5.184

http://ipblock.chacuo.net/view/c_MO

马来西亚
203.82.75.100|203.82.75.103|203.82.75.110|203.82.75.102|203.82.75.104|203.82.75.118|203.82.75.122|203.82.75.114|203.82.75.115|203.82.75.120|203.82.75.109|203.82.75.108|203.82.75.116|203.82.75.117|203.82.75.101|203.82.75.121|203.82.75.105|203.82.75.107|203.82.75.106|203.82.75.111|203.82.75.113|203.82.75.199|203.82.75.196|203.82.75.205|203.82.75.208|203.82.75.213|203.82.75.198|203.82.75.214|203.82.75.204|203.82.75.201|203.82.75.206|203.82.75.222|203.82.75.211|203.82.75.226|203.82.75.229|203.82.75.197|203.82.75.223|203.82.75.207|203.82.75.215|203.82.75.225|203.82.75.224|203.82.75.220|203.82.75.228|203.82.75.221|203.82.75.202|203.82.75.200|203.82.75.230|203.82.75.203|203.82.75.234|203.82.75.233|203.82.75.216|203.82.75.209|203.82.75.212|203.82.75.217|203.82.75.232|203.82.75.210|203.82.75.218|203.82.77.41|203.82.77.53|203.82.77.39|203.82.77.42|203.82.77.46|203.82.77.49|203.82.77.44|203.82.77.37|203.82.77.57|203.82.77.43|203.82.77.52|203.82.77.55|203.82.77.47|203.82.77.40|203.82.77.36|203.82.77.45|203.82.77.54|203.82.77.56|203.82.77.58|203.82.77.50|203.82.77.59|203.82.77.51|203.82.77.38|203.82.77.132|203.82.77.142|203.82.77.145|203.82.77.144|203.82.77.139|203.82.77.149|203.82.77.154|203.82.77.133|203.82.77.140|203.82.77.141|203.82.77.143|203.82.77.134|203.82.77.148|203.82.77.137|203.82.77.151|203.82.77.138|203.82.77.156|203.82.77.161|203.82.77.153|203.82.77.155|203.82.77.150|203.82.77.160|203.82.77.152|203.82.77.136|203.82.77.135|203.82.77.157|203.82.77.147

印尼
202.152.192.201|202.152.192.200|202.152.192.199|202.152.192.198|202.152.192.197|202.152.192.196|202.152.192.203|202.152.192.202|202.152.192.208|202.152.192.204

注意找到的IP可能延迟低，但不稳定，用来看 youtube 视频就不会很流畅，需要用这个视频 https://savedeo.com/download?url=https://vimeo.com/126255791 中的 akamai 地址测速

1. 修改系统 hosts 指定 210.0.156.15 pdlvimeocdn-a.akamaihd.net 。前面的就是要测的 IP ，我这里测试电信用它很快。

2. 浏览器直连（别使用代理）播放（有的浏览器不播放，会直接下载）这个视频，就能看到速度。

----------------------------------------------------------------------

赛风默认运行后会打开浏览器并设置为系统代理，如果你用 Chrome、Firefox 等浏览器，用扩展实现代理上网的话，建议关掉，需要修改注册表

HKEY_CURRENT_USER\Software\Psiphon3

SkipProxySettings 值改为 1
SkipBrowser 值改为 1

也可以下载  warmingf...@gmail.com 写的注册表文件，导入即可
https://copy.com/kYXodB6tIQiyUQJU/Psiphon3.reg

赛风默认是自动指定本地代理端口的，建议改成固定的，方便在浏览器中设置
https://i.imgur.com/ahh23kY.jpg

**Comment by jasonliul** [comment]
如果GP不支持, call社长~~~

怀念当年的大白鲨们.

**Comment by blob2015** [comment]
J哥彪悍 😀

**Comment by SeaHOH** [comment]
我顶~

**Comment by 10069** [comment]
😀😀😀😀😀😀

**Comment by kirbyzhu** [comment]
顶顶顶

**Comment by IRISlMaple** [comment]
这个当年用过，超好用。随便找个ip都是满速。J大测试过现在ip好找吗？回头我再鼓捣鼓捣！

**Comment by wpyok500** [comment]
@jasonliul  Proxifier不能下载了
![image](https://user-images.githubusercontent.com/14154547/27766105-d8732680-5ef7-11e7-9b88-a3e29294496d.png)

**Comment by wpyok500** [comment]
@jasonliul  Proxifier不能下载了
![image](https://user-images.githubusercontent.com/14154547/27766105-d8732680-5ef7-11e7-9b88-a3e29294496d.png)

**Comment by jyuan15** [comment]
你传的那些软件一个都下不了

**Comment by THLIVSQAZ** [comment]
学习学习了

**Comment by wenliyang** [comment]
楼上说软件不能下载的，楼主是转贴，可以下载的：

https://mega.nz/#!htohgRAR!FxxNVrdjU9TNDu2G65f-pfLPLgfaHchdrYZBdsZ2VX0
https://mega.nz/#!dtxGVI7A!RIKkg-AV3oR7ROEkrz9RS-RWFQxWtNWCxUZdH5Xlhy0

**Comment by hcym** [comment]
翻墙本来是个愉快的事
给你这么一搞，不如登珠峰

**Comment by jyuan15** [comment]
赛风不设置上层代理速度还不错，设了反而连不上了

**Comment by IRISlMaple** [comment]
@hcym
个人倒是觉得翻墙不能满速才是真正地不愉快..

**Comment by IRISlMaple** [comment]
@jyuan15
你是不是没有自己去实验ip，这个要配合Akamai ip的。

**Comment by IRISlMaple** [comment]
@jasonliul
J大问下现在checkgoodip最好用的是哪个版本呀？

**Comment by jyuan15** [comment]
@IRISlMaple 是呀，就是用默认的

**Comment by jasonliul** [comment]
@wpyok500 
#373

等喂饭? :)

**Comment by jasonliul** [comment]
@IRISlMaple 
如果被封, 社长钦点钟馗
https://www.zoomeye.org/search?t=host&q=gws

施粥哥也还在

**Comment by zou888666** [comment]
这个方法几百年前就已经失效，居然还被楼主骗了，以为又复活了。。。。果然是一直连接中。。。

**Comment by AndyLau2017** [comment]
我也记得好像后来赛风更新后就失效了，有人试过还可以的吗？

**Comment by lmw1qaz** [comment]
这个方法还是不错的，现在都还能用，就是要稍微改一下设置。就是有点蛋疼，怎么找AKAMAI的问题…………
之前都是用Checkgoogleip那个改了一下，可以用来找Akamai，可惜质量太不稳定了，好的能看4k，不好脸1080P都看不了……不知道有什么比较好的寻找节点的方式……

**Comment by p1956** [comment]
旧方法了，早失效了，很多ip被封杀了

**Comment by jasonliul** [comment]
@IRISlMaple 
终于有个玩家说话........................
社长连夜苦战,为了Quic, 为狗友.

我等生活在從未完美但真實的世界, 但我們能盡綿薄之力, 效法社長, 使之better.
:)

**Comment by jasonliul** [comment]
台灣教友發來的...

聖法蘭西斯禱告詞（1182－1226）

主耶穌啊，使我作你和平的使者：

在有仇恨的地方，讓我播種仁愛；

在有傷害的地方，讓我播種寬恕；

在有懷疑的地方，讓我播種信心；

在有絕望的地方，讓我播種希望；

在有黑暗的地方，讓我播種光明；

在有悲哀的地方，讓我播種喜樂；

噢,主耶穌啊，賜我那夢寐以求的：

不求人安慰，但去安慰人；

不求人理解，但去理解人；

不求愛，但去愛；

因為給予，就是得著

寬恕人，就被寬恕；

這樣的死亡，就是我們的永生。

 

讓我們一起來領受聖法蘭西斯的《讓我愛而不受感戴》這首詩也是一個禱告的典範:

讓我愛而不受感戴，讓我事而不受賞賜；

讓我盡力而不被人記，讓我受苦而不被人睹。

只知傾酒不知飲酒，只想擘餅不想留餅；

倒出生命來使人得幸福，捨棄安寧來使人得舒服。

不受體恤，不受眷顧；不受推崇，不受安撫；

寧可淒涼，寧可孤苦；寧可無告，寧可被負。

願意以血淚作為冠冕的代價，願意受虧損來度旅客的生涯；

因為當你活在這裡時，你也是如此過日子。

欣然忍受一切的損失，好使近你的人得安適。

我今不知前途究有多遠，這條道路一去就不在還原；

所以讓我學習你那樣的完全，時常被人辜負心不生怨。

求你在這慘淡時期之內，擦乾我一切暗中的眼淚；

學習知道你是我的安慰，並求別人喜悅以度此歲。
---------------------------------------------------------------

白話版的麥克阿瑟將軍為兒子的禱告詞:

耶和華神,

懇求你教導我的兒子，使他在軟弱時，能夠堅強不屈；在懼怕時能夠勇敢自持，
在誠實的失敗中，毫不氣餒；在光明的勝利中，仍能保持謙遜溫和。

耶和華神,

懇求你教導我的兒子，篤實力行而不空想；引領他認識你，同時讓他知道，
認識自己，才是一切知識的基石。

我祈求耶和華神，不要使他走上安逸、舒適之途，求你將他置於困難、艱難和挑戰的磨練中，求你引領他，使他學習在風暴中挺身站立，並學會憐恤那些在重壓之下失敗跌倒的人。

耶和華神,求你塑造我的兒子，耶和華神求你讓他有一顆純潔的心，並有遠大的目標；使他在能指揮別人之前，先懂得駕馭自己；當邁入未來之際，永不忘記過去的教訓。

在他有了這些美德之後，我還要祈求耶和華神賜給他充分的幽默感，以免他過於嚴肅，還苛求自己。

求耶和華神賜給他謙卑的心，使他永遠記得，真正的偉大是單純，真正的智慧是坦率，
真正的力量是溫和。

然後作為父親的我，才敢輕輕的說：「我這一生總算沒有白白活著」，阿門！


P.s 從來沒有大陸/台灣, 如果你不服, 請列舉清國對台灣的任何行政撥款 -- 任何領土所必備.
台灣, 中國, 我等樂於結交炎黃子孫.

**Comment by yqy6611** [comment]
这方法不太灵了。

**Comment by IwakuraLain1984** [comment]
@zou888666 

![youtube](https://user-images.githubusercontent.com/29833268/27790531-6c65b660-6023-11e7-84d6-5c04ef48478b.PNG)
试了一下，找了一下午的IP，还是勉强可以用的，就是节点难找，不太搞的清楚哪个速度好，得一个个试过去……

**Comment by jasonliul** [comment]
@IwakuraLain1984 
https://www.zoomeye.org/search?t=host&q=after%3A%222017-01-01%22+akamai

**Comment by tec1987** [comment]
akamai的关键字应该是这个吧：
https://www.zoomeye.org/search?t=host&q=AkamaiGHost

另外还可以用shoudan
https://www.shodan.io/search?query=Server%3A+gvs

**Comment by jasonliul** [comment]
@tec1987 
正好揪住~~
Sniproxy的key word, 试了几种都不对

**Comment by IwakuraLain1984** [comment]
@tec1987 

试了试，zoomeye找出来的有些服务器似乎有点问题……
shodan倒是可以分辨是不是akamai的特定证书从而分辨能不能用……现在主要就是要一个个慢慢试验，没有什么太好的办法检测IP质量……再加上本身Psiphon链接的都比较随机，变量太多没法很好的测试……

不过找到一个好用的IP的话，起码能一直用一个月左右，还是比较稳定的

**Comment by jasonliul** [comment]
@IRISlMaple 
可以试试Klephon, 还是比赛风稳定, 同等情形下, KP总是连接到带宽更好的节点.
看来赛风还是有服务器流量均衡机制, 但是KP搞掉了

**Comment by tec1987** [comment]
@IwakuraLain1984 
用API 把IP数据get下来，然后扫描TCP 443端口，最后用扫描工具获取证书（如果有必要的话）

@jasonliul 
Sniproxy 目前没找到明显的服务器特征，还是要实际连接测试才可以。。。

**Comment by jasonliul** [comment]
@tec1987 
多谢大大...
好歹俺也找到两枚柬埔寨, 二狗也还快.

**Comment by tec1987** [comment]
@jasonliul 客气了

可否不要叫"大大"，感觉怪怪的 （我印象中这个词一般与大伯同义，比自己父亲大的人的称呼）

**Comment by jasonliul** [comment]
@tec1987 
也好, 俺是社长的酒保, 日后改成客官~~~
:)

**Comment by blob2015** [comment]
大大，在北方、东北的叫法是这意思 😀

**Comment by jasonliul** [comment]
@blob2015 
俺是给台湾友带坏的..........
顺口

**Comment by IwakuraLain1984** [comment]
@tec1987 
多谢提点……忘了还有这一招，效果还不错了
![youtube](https://user-images.githubusercontent.com/29833268/27855795-60ca0168-619e-11e7-9aea-4a100c6c7a80.PNG)
现在可以比较稳定的看1080P，基本满足需求了……先度过这段时间暂时用着吧

**Comment by IRISlMaple** [comment]
@jasonliul 嗯~如果可以高效地找Akamai IP的话，这个就又活了~
