### ISSUE TITLE
新手咨询GAE appid的问题

### ISSUE THREAD

**Issue by hxiaoqiang** [phuslu/goproxy#1846]
# 新手咨询GAE appid的问题
我现在遇到的问题如下图所示：
![appid](https://user-images.githubusercontent.com/11829192/27893260-49d821d0-6237-11e7-8f62-d07beae1a608.png)
由于很久没有用GAE了，所以搞不清楚APPID是哪个？
我使用console登陆后，使用`gcloud app describe`，查看app的信息，里面有id显示，如截图右边显示**xiaoqianghf8**
```
xiaoqiang_hf@xiaoqianghf8:~$ gcloud app describe 
authDomain: gmail.com
codeBucket: staging.xiaoqianghf8.appspot.com
defaultBucket: xiaoqianghf8.appspot.com
defaultHostname: xiaoqianghf8.appspot.com
gcrDomain: us.gcr.io
id: xiaoqianghf8
locationId: us-central
name: apps/xiaoqianghf8
servingStatus: SERVING
```
但是我使用Goproxy server使用这个id上传时，服务器却报错：
```
APPID:xiaoqianghf8
10:45 AM Application: xiaoqianghf8
10:45 AM Host: appengine.google.com
10:45 AM Rolling back the update.
Error 403: --- begin server output ---
You do not have permission to modify this app (app_id=u's~xiaoqianghf8').
--- end server output ---
```
这块不知道怎么处理，还请知情的老司机带带路，多谢！

**Comment by lucifercn** [comment]
把这个文件  .appcfg_oauth2_tokens 删除掉  然后重新试试看看   然后看看谷歌帐号是不是登陆对了

**Comment by hxiaoqiang** [comment]
@lucifercn  感谢回复，有个细节我忘记说了，就是我换了登陆的google账号，所以才会提示无权限的问题，把 .appcfg_oauth2_tokens文件删除，然后重新上传时，出现登陆验证，即可上传成功。
