### ISSUE TITLE
gfw/isp在速度上对长连接的干扰并不严谨

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1847]
南京电信刚刚发现在进行长连接时混入一些相似的短连接能提高速度，但降低连通率

**Comment by SeaHOH** [comment]
错觉吧，都是按流量特征来的，还能提升就说明没到顶。

**Comment by phuslu** [comment]
可能是 ISP 相关，@jasonliul 也观测到类似现象，曾建议 goproxy 启动先访问 google_cn 的 IP 来混淆流量，我这边还没有完全想明白这个原理。。。

**Comment by dou4cc** [comment]
比我想象的复杂，我再看看

**Comment by SeaHOH** [comment]
@phuslu 机器学习是个黑箱，看不透正常。

**Comment by dou4cc** [comment]
（抓狂

**Comment by SeaHOH** [comment]
@dou4cc 为嘛？

**Comment by dou4cc** [comment]
@SeaHOH 一会儿速度涨到4600Kbps，一会儿又断流，明明应该能1080p流畅的，看一分多钟又卡住

**Comment by jasonliul** [comment]
@phuslu 
社长, 刚好人家疯狂重启路由器, 暂时俺解封.

俺现在是这样, 先访问一个https网站
 https://whoer.net/
而且hosts文件已加, 也就是避开dns.
通常要连两三次才通. 但是之后, 和从前一样.

如果直接连GP, 连续关闭, 启动5,6 次也不行. 就算行, 90几个好ip, 突然就下跌到60几...
按说现在是未封线路, 但和从前不一样.

**Comment by phuslu** [comment]
看起来你那边的 isp。对出国链接有监控，不容许太高并发。

你尝试调低 gae.json 的，level 值试试

**Comment by SeaHOH** [comment]
@dou4cc 
先看看视频是否是分段的，如果是这种间断卡钝就容易出现。

**Comment by dou4cc** [comment]
@phuslu 和DASH没关系

**Comment by jasonliul** [comment]
@phuslu 
果然, 调为8, 随便都能连上.
有劳社长

**Comment by dou4cc** [comment]
奠信简直疯狂，这么晚了还在干扰，尤其是互联互通的流量
