### ISSUE TITLE
goproxy-vps部署问题

### ISSUE THREAD

**Issue by THLIVSQAZ** [phuslu/goproxy#1856]
vps：arkuas
已在freenom申请域名，并添加dns记录到vps的ip
问题：miss certificate ,看起来签不出证书，ping正常指向vps的ip
![1499565299344](https://user-images.githubusercontent.com/25531652/27990620-1a4c6e0c-6422-11e7-9115-e63d0eb3756a.jpg)

**Comment by phuslu** [comment]
goproxy-vps.toml 里面需要指定域名。

**Comment by THLIVSQAZ** [comment]
已经指定了，看起来acme没办法给新域名签出证书，尝试用acme.sh签证书，要求添加dns txt记录，难道是Let's Encrypt要求增加了？

**Comment by hcym** [comment]
社长，域名能不能用ip的？
就怕绑定捆绑

**Comment by THLIVSQAZ** [comment]
不能，域名其实算是实现原理这一，怎么摸索绑定问题

**Comment by hcym** [comment]
ss可以用ip啊

**Comment by THLIVSQAZ** [comment]
额，代理原理不一样，http2和socks5

**Comment by THLIVSQAZ** [comment]
社长，给freenom加了dns解析，在goproxy-vps可以看到有ecc文件夹，但还是出现miss certificates的错误，是不是还要自行签证书？

**Comment by THLIVSQAZ** [comment]
@phuslu

**Comment by THLIVSQAZ** [comment]
重新整了一下域名和dns解析，用acme.sh成功签出了证书，但问题依旧，看来问题不在域名解析上，查看了goproxy-vps源代码，查阅了golang官方文档，找到了问题
``func (*Manager) GetCertificate
func (m *Manager) GetCertificate(hello *tls.ClientHelloInfo) (*tls.Certificate, error)
GetCertificate implements the tls.Config.GetCertificate hook. It provides a TLS certificate for hello.ServerName host, including answering *.acme.invalid (TLS-SNI) challenges. All other fields of hello are ignored.

If m.HostPolicy is non-nil, GetCertificate calls the policy before requesting a new cert. A non-nil error returned from m.HostPolicy halts TLS negotiation. The error is propagated back to the caller of GetCertificate and is user-visible. This does not affect cached certs. See HostPolicy field description for more details.

func (*Manager) Listener
func (m *Manager) Listener() net.Listener
Listener listens on the standard TLS port (443) on all interfaces and returns a net.Listener returning *tls.Conn connections.

The returned listener uses a *tls.Config that enables HTTP/2, and should only be used with servers that support HTTP/2.

The returned Listener also enables TCP keep-alives on the accepted connections. The returned *tls.Conn are returned before their TLS handshake has completed.

Unlike NewListener, it is the caller's responsibility to initialize the Manager m's Prompt, Cache, HostPolicy, and other desired options.

就是说 LE服务器签证书时要验证服务器443口的，arukas vps就挂在了端口重定向上，443为空端口，自然而然验证失败，然后就miss certificates，再次翻看了issus，把自签的证书放在了配置文件，解决了autocert问题

**Comment by THLIVSQAZ** [comment]
#1470
