### ISSUE TITLE
打开任何网页都显示Invalid URL

### ISSUE THREAD

**Issue by hekensway** [phuslu/goproxy#1859]
版本为r1474，，
打开任何网页都显示Invalid URL

已尝试自己解决多次，但是仍然未能解决，，，求大神....
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1474 (go/devel +2e7626d15e Fri Jul 7 04:38:45 2017 +0000 windows/amd64)",
    "filter": "*gae.Filter",
    "error": "dial tcp 216.58.212.197:443: i/o timeout"
}

**Comment by Alvin9999** [comment]
图片看不到，最好重新上传一下

**Comment by phuslu** [comment]
看起来是 ip 问题，你 gae.user.json 放的 ip 有多少个？

**Comment by blob2015** [comment]
社长最近屡屡赤膊上阵啊 😀

**Comment by hekensway** [comment]
导入了800个IP地址，打开谷歌稍微好一点，但是打开国内地址，就会出现各种红黄绿的信息。甚至还出现{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1474 (go/devel +2e7626d15e Fri Jul 7 04:38:45 2017 +0000 windows/amd64)",
    "filter": "*gae.Filter",
    "error": "dial tcp: lookup xiaoyong-1378.appspot.com: getaddrinfow: The requested name is valid, but no data of the requested type was found."
}

**Comment by phuslu** [comment]
额，你这错误看起来 ip 根本没生效.

所以我开始才这么问。请再摸索摸索吧。
