### ISSUE TITLE
[原创]服务器参数优化，让你的搬瓦工也能看高清720P

### ISSUE THREAD

**Issue by cmdlet1** [phuslu/goproxy#186]
本文参考了很多文章后总结出了一套搬瓦工VPS上使用Shadowsocks能够流畅观看视频网站的方法。文章内容是cmdlet总结的，如转载请注明作者和出处。

我们首先要了解搬瓦工不支持锐速、不支持TCP Fast Open、不支持hybla，加入hybla参数是为了其他服务器也能使用这篇文章的内容，其实那个参数对搬瓦工来说，然 并 卵

作者本人使用的电信20M光纤宽带，国际网速比较坑爹，优化之后，非高峰时段，Shadowsocks可看720p，高峰时段标清不卡。以下是详细步骤：
搬瓦工可以一键安装Shadowsocks服务器端，这里不多说安装步骤了，网上很多地方也都有。

<strong>1. 调整搬瓦工Shadowsocks的加密方式</strong>

加密方式改为CR4-MD5，相对aes-256-cfb来说可能加密方式更弱，但加密速度是后者的好几倍，对于一般用户来说，没有影响但能提高速度。

服务器端口一定要使用默认的443端口（很重要），具体原因不多讲了，端口特性

默认是CENTOS 6 X86环境，下面讲讲优化：

<div><b>2.增加系统文件描述符的最大限数</b></div>
<div></div>
<div>编辑文件 limits.conf</div>
<div></div><br>
<div>vi /etc/security/limits.conf</div><br>
<div></div>
<div>增加以下两行</div>
<div></div><br>
<div>* soft nofile 51200</div>
<div>* hard nofile 51200</div><br>
<div></div>
<div>启动shadowsocks服务器之前，设置以下参数（这一步是Shadowsocks官文上讲的，但实际上上面两步就是执行下面这一步，所以，下面的参数可以跳过了）</div>
<div></div>
<div>ulimit -n 51200</div><br>
<div></div>
<div><b>3. 更新sysctl和modprobe</b></div>（ 非openvz平台跳过这一步，openvz据说改内核参数然并卵，没有副作用，随手做一做吧，下面的也跟着改一改吧）<br>
<div></div>
<div>rm -f /sbin/sysctl</div><br>
<div></div>
<div>ln -s /bin/true /sbin/sysctl</div><br>
<div></div>
<div>rm -f /sbin/modprobe</div><br>
<div></div>
<div>ln -s /bin/true /sbin/modprobe</div><br>
<div></div>
<div><b>4. 修改配置文件 sysctl.conf</b></div><br>
<div></div>
<div>vi /etc/sysctl.conf</div><br>
<div></div>
<div>增加如下内容:</div><br>
<div></div>
<div>fs.file-max = 51200</div>
<div>net.ipv4.conf.lo.accept_redirects=0</div>
<div>net.ipv4.conf.all.accept_redirects=0</div>
<div>net.ipv4.conf.eth0.accept_redirects=0</div>
<div>net.ipv4.conf.default.accept_redirects=0</div>
<div>net.ipv4.ip_local_port_range = 10000 65000</div>
<div>net.ipv4.tcp_congestion_control = hybla</div>
<div>net.ipv4.tcp_fin_timeout = 30</div>
<div>net.ipv4.tcp_fastopen = 3</div>
<div>net.ipv4.tcp_keepalive_time = 1200</div>
<div>net.ipv4.tcp_rmem  = 32768 436600 873200</div>
<div>net.ipv4.tcp_syncookies = 1</div>
<div>net.ipv4.tcp_synack_retries = 2</div>
<div>net.ipv4.tcp_syn_retries = 2</div>
<div>net.ipv4.tcp_tw_reuse = 1</div>
<div>net.ipv4.tcp_tw_recycle = 0</div>
<div>net.ipv4.tcp_timestsmps = 0</div>
<div>net.ipv4.tcp_tw_reuse = 1</div>
<div>net.ipv4.tcp_max_tw_buckets = 9000</div>
<div>net.ipv4.tcp_max_syn_backlog = 65536</div>
<div>net.ipv4.tcp_mem = 94500000 91500000 92700000</div>
<div>net.ipv4.tcp_max_orphans = 3276800</div>
<div>net.ipv4.tcp_mtu_probing = 1</div>
<div>net.ipv4.tcp_wmem = 8192 436600 873200</div>
<div>net.core.netdev_max_backlog = 250000</div>
<div>net.core.somaxconn = 32768</div>
<div>net.core.wmem_default = 8388608</div>
<div>net.core.rmem_default = 8388608</div>
<div>net.core.rmem_max = 67108864</div>
<div>net.core.wmem_max = 67108864</div><br>
<div></div>
<div>执行生成</div><br>
<div></div>
<div>sysctl -p</div><br>
<div></div>
<div><b>5. 安装net-speeder</b></div><br>
<div></div>
<div>分别执行以下命令：</div><br>
<div></div>
<div>wget --no-check-certificate https://gist<wbr />.github.com/<wbr />LazyZhu/dc3f<wbr />2f84c336a08f<wbr />d6a5/raw/d8a<wbr />a4bcf955409e<wbr />28a262ccf529<wbr />21a65fe49da9<wbr />9/net_speede<wbr />r_lazyinstal<wbr />l.sh</div>
<div></div><br>
<div>sh net_speeder_lazyinstall.sh</div><br>
<div></div>
<div>加入开机启动</div><br>
<div></div>
<div>echo 'nohup /usr/local/net_speeder/net_speeder venet0 "ip" &gt;/dev/null 2&gt;&amp;1 &amp;' &gt;&gt; /etc/rc.local</div><br>
<div></div>
<div><b>6. 重启VPS</b></div><br>
<div></div>
<div>reboot</div>
<div></div>
<div></div>
<div>以上步骤执行完成之后速度效果如下：</div>
<div> <img  src="https://cloud.githubusercontent.com/assets/14194638/9777924/7100252a-579c-11e5-9999-bd2e4bdd8b2c.png"   /> </div>

<div></div>
<div>文件下载实时速度：</div>
<div><img  src="https://cloud.githubusercontent.com/assets/14194638/9777957/d4b4853e-579c-11e5-9cfa-a9257a58ae05.png"   /> </div>

<div></div>
<div>

<hr />

</div>
<div>

<strong>参考文献：</strong><br>

Shadowsocks官方服务器优化之南<br>

https://github.com/shadowsocks/shadowsocks/wiki/Optimizing-Shadowsocks<br>

shao.bing的博文<br>

http://blog.csdn.net/shaobingj126/article/details/8549494<br>

net-speeder安装指南<br>

https://code.google.com/p/net-speeder<br>

LazyZhu的懒人脚本<br>

https://github.com/LazyZhu<br>
</div>

**Comment by sdyg** [comment]
第2步是什么鬼……LZ又把网上那段搞笑版教程抄过来了。对于openvz来说，只有net-speeder是有效果的，内核参数无法修改。

**Comment by cmdlet1** [comment]
@sdyg 不知道对openvz是否有效，但亲测不安装net-speeder的情况下，改和不改确实速度上有差别

**Comment by tianlichunhong** [comment]
安装锐速，应该就不需要net-speeder了吧？两个是否有冲突？

**Comment by cmdlet1** [comment]
@tianlichunhong 没用过锐速。。

**Comment by passcodex** [comment]
@sdyg 是的，无法修改Bandwagon的内核参数，优化没什么用，这个主要还是取决你本地的网络情况，搭建SS和VPN后，使用公司网路根本用不着优化，Download Youtube 1080P 都稳定在3M/s

**Comment by cmdlet1** [comment]
说无效的哥们自己去试一下吧，不多说

**Comment by ren2014311** [comment]
无用

**Comment by GiveMeAHug** [comment]
说没有用的修改net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
后面的参数，原因吗-----各人的网络情况不同，并且服务器要是是32位的话就必须改。
![1936596_6a6b04219f0757634e7ee8b7479e65ef_1441460032](https://cloud.githubusercontent.com/assets/14194132/9761340/adf84e4e-572e-11e5-912b-1179a2668036.gif)

**Comment by cmdlet1** [comment]
![1](https://cloud.githubusercontent.com/assets/14194638/9767766/607d1f2c-5752-11e5-9e7b-a6e2a2c44fd3.png)

**Comment by sdyg** [comment]
唉，为了不让更多小白被误导，我还是提醒一下吧：
第2步的那四条指令，是将sysctl和modprobe这两个程序删除，并且将/bin/true这个程序软连接为前面这两条程序。也就是说，后面无论是执行sysctl还是modprobe，其实都是执行/bin/true。true是什么呢？这个程序什么都不做，固定返回true，也就是运行了和没运行无任何区别。这种掩耳盗铃的“优化”，早就被人笑掉大牙了。
LZ获得的所有速度提升，都是来自net_speeder，和前面调节内核参数无任何关系。所以只要从第5步开始就行了。

**Comment by cmdlet1** [comment]
没事，顶多是没效果，又没副作用，都做一遍也好

**Comment by malthae** [comment]
我这版瓦工还是不稳定，快的时候飞起，慢的时候开个网页都要半天

**Comment by fulljump** [comment]
我以前用移动也是，要么就连不上，要么就很快，移动老是间歇性的干扰

**Comment by zjgood** [comment]
第二部纯属自慰，并且早已在v2ex上证伪
楼主注意一下

**Comment by Chingpo-Lai** [comment]
感谢分享心得

**Comment by xubin990510** [comment]
你删了sysctl和modprobe。。VPS还能启动。。 哈哈哈

**Comment by 0plon0lz** [comment]
增加系统文件描述符的最大限数是啥意思。。。。

**Comment by raphaeltao** [comment]
用443端口是什么梗？我用的一个100以下的端口

**Comment by alanljj** [comment]
试了，我是电信30M的，速度明显改善

**Comment by truebit** [comment]
感谢楼主的分享。不过“更新sysctl和modprobe”这里完全是自欺欺人。因为`true`这个命令啥都不干……不信你可以输入`man true`看看。。

**Comment by xubin990510** [comment]
删了那两个能不能开机都不一定

**Comment by wzlee104** [comment]
试过了，改善不明显，晚11点左右，连240p都看不了

**Comment by wisdomSir** [comment]
默认的443端口直接被墙了
我配置了443端口 只能使用谷歌搜索其他都不行.改端口后就没问题了

**Comment by HeYang1024** [comment]
端口特性是什么鬼？？

**Comment by Lyanf** [comment]
真的有用，就是第五步，感谢之前评论的那位

**Comment by asir6** [comment]
请问如果通过docker部署ss，那么是否vps和docker都需要做相应修改？

**Comment by omixk** [comment]
板瓦工自带的ss，怎么配置多端口？在哪里改？没找到文件

**Comment by Lyanf** [comment]
我只是搞了他说的第五步，其他都没搞，因为之前有评论的同学也说了之前的几步没什么作用。

**Comment by jxzy199306** [comment]
看到netspeeder就莫名想喷，再不济你好歹用个finalspeed啊，netspeeder自己优化30%，杀人200%，finalspeed好歹优化100%，杀人100%

**Comment by tianlichunhong** [comment]
据说finalspeed耗资源厉害，新出的kcptun据说不错。

**Comment by caoyunxuan07** [comment]
在使用这一句`sysctl -p`的时候报错如下
```error: permission denied on key 'fs.file-max'
error: "net.ipv4.conf.eth0.accept_redirects" is an unknown key
error: permission denied on key 'net.ipv4.ip_local_port_range'
error: permission denied on key 'net.ipv4.tcp_fin_timeout'
error: "net.ipv4.fastopen" is an unknown key
error: permission denied on key 'net.ipv4.tcp_keepalive_time'
error: permission denied on key 'net.ipv4.tcp_rmem'
error: permission denied on key 'net.ipv4.tcp_synack_retries'
error: permission denied on key 'net.ipv4.tcp_tw_reuse'
error: permission denied on key 'net.ipv4.tcp_tw_recycle'
error: "net.ipv4.tcp_timestsmps" is an unknown key
error: permission denied on key 'net.ipv4.tcp_max_tw_buckets'
error: permission denied on key 'net.ipv4.tcp_max_syn_backlog'
error: permission denied on key 'net.ipv4.tcp_mem'
error: permission denied on key 'net.ipv4.tcp_max_orphans'
error: permission denied on key 'net.ipv4.tcp_mtu_probing'
error: permission denied on key 'net.ipv4.tcp_wmem'
error: permission denied on key 'net.core.netdev_max_backlog'
error: permission denied on key 'net.core.wmem_default'
error: permission denied on key 'net.core.rmem_default'
error: permission denied on key 'net.core.rmem_max'
error: permission denied on key 'net.core.wmem_max'
error: "net.bridge.bridge-nf-call-ip6tables" is an unknown key
error: "net.bridge.bridge-nf-call-iptables" is an unknown key
error: "net.bridge.bridge-nf-call-arptables" is an unknown key
error: permission denied on key 'net.nf_conntrack_max'
net.ipv4.ip_forward = 0
net.ipv4.tcp_syncookies = 1
net.ipv4.conf.lo.accept_redirects = 0
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.tcp_syncookies = 1
net.core.somaxconn = 32768
net.netfilter.nf_conntrack_max = 64000

Exit code: 255```

添加如下解决
```#rm -f /sbin/sysctl  
#ln -s /bin/true /sbin/sysctl ```
这是为啥？这两句又是干啥？

**Comment by Hyvi** [comment]
> echo 'nohup /usr/local/net_speeder/net_speeder venet0 "ip" >/dev/null 2>&1 &' >> /etc/rc.local
我加入后重启电脑，这个并没有启动，是什么原因？
系统：debian 7 x64
runlevel: N 2

**Comment by fanbuxie** [comment]
https://www.banwago.com - Bandwagonhost
[搬瓦工](https://www.banwago.com)专注于分享Bandwagonhost的使用教程以及Bandwagonhost的优惠信息
