### ISSUE TITLE
SpyOFF VPN 免费百日

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1861]
![b5117af04a png](https://user-images.githubusercontent.com/2461165/27996275-47a31ac8-6511-11e7-907f-be1d9a4136ff.png)

https://www.spyoff.com/de/chip

免费测试100天

**Comment by Just2co** [comment]
@jasonliul 类似这些商业VPN服务，好像都是用的openvpn协议，pptp、l2tp都已经可以被精准识别并且阻断。

**Comment by malthae** [comment]
活动结束了吗?去官网看了一下好像只能免费试用15天了
