### ISSUE TITLE
Quic 新GP, 一切照常

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1863]
![screenshot 1](https://user-images.githubusercontent.com/2461165/28000653-b1e2c9f4-6559-11e7-810d-481600477550.jpg)

有了K主任的新玩具, 调整IP, 结果和从前一样...

**Comment by lsnmx** [comment]
新玩具共享一下呗

**Comment by qwerttaa** [comment]
新的扫描工具看这里https://github.com/phuslu/goproxy/issues/1841#issuecomment-313344673

另外楼主这个测速是哪个网站？正经能支持1g的带宽测试？

**Comment by jasonliul** [comment]
http://openspeedtest.com/
https://fast.com/
http://speedsmart.net/

几个目前人气的, speedsmart支持各种怪胎, 例如U.

**Comment by mikecheng78** [comment]
@jasonliul  
![1](https://user-images.githubusercontent.com/26914252/28003277-1b34a4bc-656f-11e7-85e8-2238ea5917ed.JPG)
![2](https://user-images.githubusercontent.com/26914252/28003276-1b2a889c-656f-11e7-8f39-3f77c79c067c.JPG)
![3](https://user-images.githubusercontent.com/26914252/28003278-1b3a45c0-656f-11e7-9980-281cd775f6a0.JPG)
结果差很大？？

**Comment by mikecheng78** [comment]
@jasonliul 我的上传速度比你好很多

**Comment by wz7465** [comment]
楼上百兆带宽不给力啊，看看我的30m
![default](https://user-images.githubusercontent.com/7801728/28003671-eb4b1af8-6571-11e7-8ba7-facc4a5ec2be.png)

**Comment by qwerttaa** [comment]
北京联通实测这几个测速网站，都没有speedtest。net好使，speedtest。net节点比较多，不挂代理的话能达到满带宽，我北京联通200m，下行到250m，上行不稳，差不多平均30m
