### ISSUE TITLE
用了一个星期，来谈谈感受

### ISSUE THREAD

**Issue by yadex** [phuslu/goproxy#1866]
在这之前用的是隔壁xx-net。ip是用xx-net扫描出来的导入的。大概1000多个。用了一星期，感觉速度比隔壁快很多。尤其在下载方面好很多，还有就是隔壁登录谷歌账号经常会鬼畜，而goproxy并不会。一星期过去了，还剩这么多ip，
![screenshot at 2017-07-10 22 17 11](https://user-images.githubusercontent.com/20081672/28023248-ebc7cd98-65bf-11e7-88ad-ae29122f1a47.png)
油管1080P依旧无压力
![screenshot at 2017-07-10 22 21 58](https://user-images.githubusercontent.com/20081672/28023290-0f5d4ee0-65c0-11e7-9e30-8653a48fd7b9.png)

**Comment by phuslu** [comment]
谢谢认可。

但这种直接的比较容易引发口水贴。。。
