### ISSUE TITLE
Quic 字段, 大家来摸奖

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#1868]
61.91.161.8|118.98.30.5|61.91.161.9|61.91.161.7|61.91.161.6|61.91.161.4|61.91.161.10|61.91.161.11|210.171.10.4|114.125.33.4|118.98.30.73|210.171.10.5|210.171.10.6|118.98.30.71|61.91.161.72|61.91.161.71|61.91.161.73|61.91.161.81|61.91.161.70|213.59.210.4|61.91.161.68|118.98.30.70|213.59.210.5|213.59.210.6|213.59.210.8|61.91.161.196|61.91.161.136|61.91.161.134|61.91.161.202|61.91.161.198|61.91.161.201|61.91.161.200|61.91.161.217|61.91.161.203|61.91.161.139|61.91.161.132|61.91.161.133|61.91.161.110|213.59.210.11|213.59.210.75|213.59.210.73|213.59.210.69|213.59.210.70|213.59.210.71|213.59.210.68|118.98.30.207|213.59.210.72|94.190.64.189|94.190.64.190|118.98.30.213|118.98.30.137|213.59.210.74|61.91.161.199|213.59.210.197|213.59.210.199|213.59.210.202|213.59.210.196|213.59.210.137|213.59.210.139|213.59.210.198|213.59.210.135|213.59.210.138|213.59.210.136|114.125.33.174|114.125.33.165|114.125.33.166|114.125.33.176|114.125.33.167|114.125.33.169|114.125.33.172|213.59.210.134|114.125.33.164

61.91.161.0/24
118.98.30.0/24
213.59.210.0/24
210.171.10.0/24
114.125.33.0/24
94.190.64.0/24

其实不少坟头长草的老字段, 又回来了~~
而且还不用担心所谓随机干扰鸟

**Comment by Alvin9999** [comment]
想到一个问题，Quic这么好用，那么GoAgent能否也启用Quic协议呢？
由于社长太忙了，如果可以的话，有没有其它高手能够帮忙解决一下这个问题呢，毕竟GoAgent在某种程度上来说有可用之处。

**Comment by mikecheng78** [comment]
goagent 可以用gvs ，尽管在稳定性方面不错，特别是访问网页很稳定。但是看视频确实比gop差很远。我两个都有

**Comment by kirbyzhu** [comment]
goproxy enable quic后现在如果长时间没使用，就会出一大堆红黄字然后要重启才行

**Comment by sishentibu** [comment]
能扫出不少来

**Comment by zhangyz1997** [comment]
其实有了Zoomeye以后字段还真不会缺

**Comment by Alvin9999** [comment]
隔壁XX-net论坛有不少人反应现在连ip都搜不出来，可见有的地区干扰确实很严重。

**Comment by mikecheng78** [comment]
@Alvin9999 可能和地区封杀有关。我这里没啥封杀，一会就扫描出GWS、GVS各十几个。是经过验证有效地那种。

**Comment by jasonliul** [comment]
@Alvin9999 
 go语言下面, 有谷歌官家做的quic参考代码, 所以社长省心.
python下面没有的, 而且谷歌的这些语言, 也是炒作性质, 恕我直言, python已经out~~

**Comment by dou4cc** [comment]
@kirbyzhu 试试[时不时产生流量](https://raw.githubusercontent.com/dou4cc/code/gh-pages/daemon.html)

**Comment by wpyok500** [comment]
我都不用扫IP，以前的ip继续使用着。

**Comment by kirbyzhu** [comment]
@dou4cc 这玩意怎么用啊？

**Comment by Alvin9999** [comment]
@jasonliul  懂了

**Comment by 94oiio** [comment]
@kirbyzhu   那个网页另存为html  然后再用浏览器打开它你就知道了

**Comment by blob2015** [comment]
J哥又在制造快乐了 😀

**Comment by jasonliul** [comment]
@blob2015 
你光说不练, 没诚意~

**Comment by blob2015** [comment]
@jasonliul 
要怎么练？ 😀

**Comment by SeaHOH** [comment]
@blob2015 
跟着乐呵呀，不然杰哥唱独角戏了~

**Comment by blob2015** [comment]
@SeaHOH 
那能让J哥独角戏呢 😀 
有ABC兄，还有大海兄，那能寂寞 😀

**Comment by jasonliul** [comment]
@SeaHOH @blob2015 
你两个光水, 没ip.
欺骗消费者, 退票~~~

**Comment by blob2015** [comment]
@jasonliul 
好久没有扫了啦，J哥……
一般也就用个google的网页搜索
视频也较少看，没办法，需求简单，J哥才是青春无敌的太阳范啊

**Comment by SeaHOH** [comment]
俺也好久都没大规模扫过了，偶尔加一两个段，还是各位好心人的施粥呢，谢谢啦。 :smile_cat:
