### ISSUE TITLE
今天下午似乎搜索不到GWS IP，之前手中可用的GWS IP也全部死翘翘

### ISSUE THREAD

**Issue by WashingtonDC20500** [phuslu/goproxy#1870]
今天下午似乎搜索不到GWS IP，之前手中可用的GWS IP也全部死翘翘，GVS IP倒是找到不老少，看YouTube 1080p绰绰有余，这是啥情况？

**Comment by hcym** [comment]
母鸡了

**Comment by mikecheng78** [comment]
@WashingtonDC20500 可能是你所在地区封杀厉害？？我刚才用10分钟扫描到了15个gws 和 12个GVS
，好像很容易扫描出来？？可能是所在地区比较幸运？

**Comment by jasonliul** [comment]
@WashingtonDC20500 
恭喜你加入挨封党,你的申请已被组织批准.
转用quic功能就是, 狗照跑, 舞照跳~~~~

**Comment by wpyok500** [comment]
看你们在这天天扫ip，都感叹，咋我这边都不用烦心，随便使用。

**Comment by jasonliul** [comment]
@wpyok500 
你那是流配区域, 南蛮, 缴税就行............
:)
