### ISSUE TITLE
☆ 2017 高速健壮的反审查武库大阅兵

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1871]
求分享一些梯子，满足以下条件：
- 即使是电信也能高速
- 难以封锁（quic、heroku这种很容易封掉的就不满足条件）

**如果能免费请特别标注**

目前只想到ssr，悲哀~

**Comment by wegood9** [comment]
还以为lz要像J哥一样分享点什么高速健壮的东西，原来是求……

**Comment by phuslu** [comment]
嗯，ssr 挺好。v2ray看上去貌似也不错。

**Comment by jasonliul** [comment]
d小少, 你你你............
居然发个李鬼版本

**Comment by MeABc** [comment]
楼主你标题党，还以为是要分享，原来是求…… （同二楼）

**Comment by dou4cc** [comment]
@wegood9 @jasonliul @MeABc 每人都分享一点不就成wiki了么。。别水啊😟

**Comment by jasonliul** [comment]
@dou4cc 
明明是你水俺的帖子~
![spank gif](https://user-images.githubusercontent.com/2461165/28073033-2eb05c16-6687-11e7-9f30-6825d9b8e5f1.gif)

**Comment by MeABc** [comment]
好吧，我推荐 goproxy ，理由是我这能上 4K 。 :trollface:

**Comment by jasonliul** [comment]
@MeABc 
赞同~~
米少爷

**Comment by zhangyz1997** [comment]
但哪天直接像之前那样封掉quic如果又没有VPS或者前置的话goproxy不就扑街了

**Comment by kirbyzhu** [comment]
标题党

**Comment by kirbyzhu** [comment]
quic只是社长主力做的补充方案 目前即使不使用quic，一样溜溜的

**Comment by 94oiio** [comment]
goproxy 上海电信 2k无压力 
![default](https://user-images.githubusercontent.com/18633798/28100037-58e463c2-66f2-11e7-9c4b-5c52dd3e3d38.PNG)

**Comment by Alvin9999** [comment]
[SS or SSR免费账号（长期更新）](https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7)

**首选还是GoProxy，毕竟谷歌服务器，这些ss服务器经不起太多人来使用，所以只能作为备选。**

**Comment by mikecheng78** [comment]
@dou4cc 吃着碗里的看着锅里的？？捧着金饭碗要饭？？有了gp这样的高速免费的代理，还去哪找更好的呢？？

**Comment by mikecheng78** [comment]
@ Alvin9999  我是不折腾其他的了，花功夫在找高质量ip的技术和方法上，手持GP、GA，解决科学上网已经足够了。

**Comment by phuslu** [comment]
最近兄弟火气怎么都这么大啊。

可能被墙怼的吧。。。楼上请别这样

**Comment by jasonliul** [comment]
@phuslu 
社长, 号召大家多啤酒才行~~~
左手牵狗, 右手啤酒.
:)

**Comment by jasonliul** [comment]
@phuslu 
社长, 刚刚看到被锁的帖子.

任何引发口水争斗的帖子, 删无赦.
中国人这种内部斗驴游戏, 请坚决阻止在此地.

**Comment by 94oiio** [comment]
也借地方吐槽一下，这哥们看东西都不看全来的，想当然的上来就一通质问
![default](https://user-images.githubusercontent.com/18633798/28108695-fce4229c-671e-11e7-9f79-4c935a9d33c6.PNG)
原文清清楚楚明明白白的写道，goagent早就更新了不会使用同一个证书，还上来问这么一通
还有其他的一些问题，简直就是有点不可理喻。

**Comment by MeABc** [comment]
我倾向于有意找茬。这哥们对 python 很熟悉，自恃有才，先喷 SSR 再过来喷 goproxy 。

**Comment by qwerttaa** [comment]
没必要评论，更没必要抨击。

锁帖，成为过去，迅速被遗忘。。。。。。

**Comment by MeABc** [comment]
嗯，我是最后一次回复这种问题，下次直接引用----反正也不用担心版权问题。。。

**Comment by SeaHOH** [comment]
@MeABc 
到是觉得他不是有意来怼，纯粹自视过高。
建议回复这种问题之前看看他的历史 issues，这个帐号就爱这样，把自己搞不清的东西就拿来乱讲，别人解释也觉得自己的逻辑才是对的，没法沟通。

**Comment by phuslu** [comment]
嗯，网上的很多嘴仗多是话赶话导致的，大家的本意都挺好了。

我尽快搞好 faq，以后就应该能避免误会了。

**Comment by phuslu** [comment]
另外真的很感谢几位的抬爱和维护。

其实不用这样，这样的帖子和情况放置一下就好了，我做 gae 这么多年，毁誉已经完全不会影响我的心境了。

再次感谢。

**Comment by MeABc** [comment]
高大上的话咱不说，我从一个普通用户的角度来谈：
1. 这代理用着正爽着呢，忽然跑来一个捣蛋的，不能忍。
2. 前一个项目结局摆在那，不能怂。社区必须要有人来回应，社长可以无视，但我们时间多，很多时间闲很慌。

**Comment by jasonliul** [comment]
@MeABc 
米少爷, 以后戒尺交给你.........
各种随便

**Comment by jasonliul** [comment]
@phuslu 
附议米少爷...

江苏是刘邦的故乡, 社长啤酒狗肉洗脚之余, 写写程序~~
其他的请允许我等代劳

**Comment by MeABc** [comment]
少爷这样叫着是不是回到封建时代了。。。。

**Comment by MeABc** [comment]
不过可以叫我小米。。。。哈哈。。

**Comment by zhangyz1997** [comment]
goproxy是不错,可惜据说手机上不完美,总会有些app用不了

**Comment by kirbyzhu** [comment]
goproxy本来就不是为手机设置的，手机用ssr最方便

**Comment by jasonliul** [comment]
@MeABc
你和海少是本社双煞, 恶少, 少狼~~

**Comment by Jason4774** [comment]
@zhangyz1997 facebook用不了，

**Comment by phuslu** [comment]
借贴来说个事情，看下这个项目 https://github.com/wangchunming/2017hosts 所以请诸位低调使用 goproxy 谢谢。

**Comment by jasonliul** [comment]
居然有这种事...

**Comment by MeABc** [comment]
社长应在 FAQ 里加个类似免责声明，如果使用 goproxy 来从身违法活动，一切后果必须自己承担。

这就是我昨天也表达的一个观点，很多人希望开发者声明 goproxy 是一个多么多么安全的代理，以后好做文章。即使这代理很安全，也不能说安全 ---- 在这个国度。不能掉入这坑。

**Comment by wenliyang** [comment]
社长说的那人之前在ghihub某个较知名hosts项目里为自己的项目推广
有人在issue里问某某网站对应IP失效，他就回复请使用他的项目（说的不太好听这有点象踢馆了），那个较知名hosts项目负责人士提醒他不要这么做，不听继续，后来被block了
于是，现在突然出了这事
虽然之间不一定有啥关联，社长低调的说法是很有道理的

**Comment by jap33** [comment]
还是安全认识不高，qq：微信都是实名电话号码注删的。

**Comment by jasonliul** [comment]
今年把翻墙下放公安, 作为外快收入, 等同以前的小赌.
近几年他们饥渴得紧~~ :)

**Comment by SeaHOH** [comment]
现在低调才是存身之道，不然不仅自身遭殃，还可能会连累社长。
那啥，且用且珍惜~

**Comment by Kisesy** [comment]
围观，期待后续

**Comment by dou4cc** [comment]
@phuslu 你不是匿名的吗？

之前发生了啥~~

**Comment by MeABc** [comment]
哈哈，恶意踢馆看不下去了都，总不能集体沉默吧。。。。
他要是在XX日报上喷，咱管不了，这都上门了，还不顶他几句。。。

**Comment by MeABc** [comment]
联想近段时间之事，人家都欺负到家门口了，我们还在抢占道德制高点。。。。

**Comment by MeABc** [comment]
其实早就被社长说中了，近期被墙怼的，火气大没处发，刚好逮到一个，所以就。。。让大家见笑了。。。 :trollface:

**Comment by jasonliul** [comment]
@MeABc 
![realkid jpg](https://user-images.githubusercontent.com/2461165/28201977-d92da336-68a5-11e7-8085-637d1eaeb58e.jpg)

**Comment by MeABc** [comment]
啥情况？

**Comment by jasonliul** [comment]
@MeABc 
你的自拍~~

**Comment by dou4cc** [comment]
王春明事件后续：https://twitter.com/dou4cc/status/891192663680180224
