### ISSUE TITLE
goproxy是否存在中间人攻击漏洞？goagent 曾经拥有的问题

### ISSUE THREAD

**Issue by Justsoos** [phuslu/goproxy#1874]
参考此文：《翻墙软件 GoAgent 的安全风险》
https://www.bamsoftware.com/sec/goagent-advisory.html#zh-CN

如此文所述，那么goproxy 是否还拥有同样的安全风险？

1，goproxy 是否拥有同一个根证书私钥？ 怎么保证安全？
2，由于用户系统内加入了goproxy 根证书，用来欺骗浏览器，是否访问攻击者可以定制的假的，由goproxy根证书生成的SSL 证书网站，没有任何报警？比如，假 gmail，假twitter 网站
3，goproxy GAE是怎么避免goagent GAE 同样面对的google GAE禁止https真代理模式的？ 还是没有改变？和goagent GAE同样方式？-- 也就是说，保留了所有goagent 的中间人攻击安全风险？
4，目前看不到goproxy 源码，是近期隐藏了？ 这是开源项目吗？
5，goproxy 非GAE 代码是否也沿用了浏览器端假证书这个原理？
6，是否能公开 goproxy 在网络传输的加密方法和过程？
谢谢回复，让用户们可以安心

**Comment by 94oiio** [comment]
这个项目已经倒闭了，主事者被抓去喝茶了

**Comment by hcym** [comment]
这种鬼地方还怕中间人

**Comment by hcym** [comment]
94oiio 
抓你妈逼，吓唬谁啊

**Comment by MeABc** [comment]
非官方回复一下。

上一次回复某位老兄时，我打了一大堆字，现在再让我打那么多字也打不出来了。他删了我也就删了。这次不删了。。。。。留做下次引用----以后肯定还会有很多的。

![default](https://user-images.githubusercontent.com/18194126/28102725-b3938d3c-6703-11e7-895c-d953734da1ee.png)

本来嘛，如果引用 linus 大神的话来回复这种问题，就一句：代码都给你了，你还想怎么样。。。

PS：你让开发者天天回复这种问题，不过社长脾气也是好，要是我直接删帖。

不过下面以我以对 goproxy 的了解尽量做个详细的。

1. 没有用同一个证书。不保证安全 ---- 自行判断。
2. 第一点 + 看源码 + 自行判断。
3. 就一个 https 模式。已写死在源码。不过自己作死改了代码就不要喷项目。
4. 不回答。既然都科学上网了，为什么不学一下怎么用搜索。
5. 是的。
6. 看源码。如果看不懂，但学一下怎么用搜索这个应该不难吧。

最后，这是用来科学上网的，但你如果用来反美帝活动，必被美帝抓去捅菊花。祝你好运。

**Comment by kirbyzhu** [comment]
像是别有用心来踢馆的

**Comment by phuslu** [comment]
楼上别怼了，楼主也是有些疑惑和怀疑才发帖的。

帖子本身并无冒犯之意，只是没有使用就问这么多就让我有些不愿意详细答疑了。

诸位请勿诛心啦。

**Comment by phuslu** [comment]
goproxy 这玩意我本来就没有想太多人用，起名也是起个泯泯然的名字。

做着玩意除了浇胸中块垒，就是冀望能够尽量给 gae 一脉留个传承。

**Comment by MeABc** [comment]
既然很多人都找不到。。。以后干脆这样算了。。。。 哈哈。。。

**Comment by Justsoos** [comment]
@phuslu  谢谢作者回复，我曾经是 goagent 的用户，goproxy 的使用模式没有太大区别。问这些问题，和是不是使用过没关系。

目前很多人用goproxy，是非常多，其实是利用了 Google 的GAE 有免费流量，有相当低延迟的google 服务器可以免费刷流量，对安全毫不在意。 尤其是360 背后支持的沃通，startcom滥用 SSL 假证书的事儿都爆发这么久了，在系统内插一个个人定制根证书，这安全危害程度有多大？？

既然 goproxy 和goagent 都是牺牲安全来成就访问方便舒适 -- 主要是google GAE服务器的免费流量 -- 还是在项目显著位置写出来比较好。让用户清楚自己面对的交换。-- 目前没看到哪里有写。但goagent 的安全问题，goproxy 应该是延续继承了。

在发本帖之前，我在 issues 里搜索了，并没有发现有相关解答和问题。包括closed 。

**Comment by phuslu** [comment]
谢谢恢复，在外面手机打字不方便，待会详细答复。

**Comment by hcym** [comment]
明明在监狱里呆着担心外面的小流氓
你怕个裘啊

**Comment by MeABc** [comment]
> 在发本帖之前，我在 issues 里搜索了，并没有发现有相关解答和问题。包括closed 。

其它几点可能没有详细的，但第四点就可以说明你没有认真找或者没有认真看。

我帮你找了一下，第四点

[项目怎么没了，还是只有我是这种情况 ](https://github.com/phuslu/goproxy/issues/1272)

**Comment by Justsoos** [comment]
@hcym  如果你觉得为了和流氓斗，自己也要流氓化，那是你的自由。
除你之外，让其他用户知道自己身处何地的知情权，这是软件全体行业的基本守则。

**Comment by MeABc** [comment]
> 让其他用户知道自己身处何地的知情权，这是软件全体行业的基本守则。

笑话！你在一个开源项目里大谈知情权。

你干嘛你不去找政府。怂了吧。专门欺负弱小是中国人的专利。

**Comment by MeABc** [comment]
不懂就说不懂。认真虚心请教没有人会笑你。

装神弄鬼，乱扣帽子，这也叫自由。。。对不起，这里没有这种自由。

**Comment by Justsoos** [comment]
如果没有 这个作者 撰文指出goagent 的安全问题，至今也不会有几个人去解读源代码，并撰文，广为周知。《翻墙软件 GoAgent 的安全风险》
https://www.bamsoftware.com/sec/goagent-advisory.html#zh-CN

如果没有众多技术人广为指出、宣传wosign 沃通，startcom 滥发SSL 证书，加之google 苹果对这个流氓的抵制，也没有现在的局面。

用 @MeABc 你的逻辑来说，对付耍流氓的某政府，就可以不要专业性，要笑掉大牙。
恐怕你根本理解不了，Google GAE为什么不允许 HTTPS 转发代理，因为Google 不想自己的引擎变成黑客小流氓的黑产加速器！！这对于你来说，太专业了，不允许你耍流氓了，你就要跳起来骂娘了？

懒得搭理你这种为了反Gong 而反共，无知，无专业的精神病人。

**Comment by phuslu** [comment]
诸位消消气，这贴我先锁了。
