### ISSUE TITLE
为何今天每个YouTube视频都会弹出Ads by Google广告？

### ISSUE THREAD

**Issue by WashingtonDC20500** [phuslu/goproxy#1881]
今天看YouTube总是有广告，如下图，以前极少这样。
换用SSR就没有广告，不知何故？
![image](https://user-images.githubusercontent.com/29592223/28211277-605311e8-68ce-11e7-9565-f5a80f30cfd2.png)

**Comment by MeABc** [comment]
亲，y2b 的广告是可以关闭的。。。。

**Comment by WashingtonDC20500** [comment]
@MeABc 怎么关闭？请教！
好像不是随机，每个都有。

**Comment by Asteroids89** [comment]
或者用油猴脚本 youtube+

**Comment by WashingtonDC20500** [comment]
我说的是怎么让YouTube不显示广告，而不是显示了广告再手动关闭。

**Comment by WashingtonDC20500** [comment]
@MeABc 我说的是怎么让YouTube不显示广告，而不是显示了广告再手动关闭。

**Comment by MeABc** [comment]
呃。。。。那你用脚本好了，我没有用过，都是手动关。

**Comment by WashingtonDC20500** [comment]
一直没有广告，怎么今天突然蹦出广告了。

**Comment by hcym** [comment]
好像跟谷歌识别你在哪里有关

**Comment by YL-Li** [comment]
哪有，我关闭去广告插件都没有看到一个广告。不过我关闭了谷歌广告推荐，在谷歌广告设置里面把兴趣项目全部关闭

**Comment by WashingtonDC20500** [comment]
@YL-Li 这一步也设置了，依旧广告不断，隔几分钟就弹出一次。

**Comment by SeaHOH** [comment]
直接点右上，关闭个性广告。

**Comment by WashingtonDC20500** [comment]
试过了所有方法，皆无效，更换另外一个Google Account，所有Ads by Google消失，Google真是欺负老客户。
