### ISSUE TITLE
使用一段时间后失去响应

### ISSUE THREAD

**Issue by xiaomage2000** [phuslu/goproxy#1884]
使用一段时间后失去响应，在日志里只能看到STRIP CONNECT 
日志如下：
`I0715 20:21:16.232056    7460 handler.go:145] IOCopy &gae.onErrorBody{ReadCloser
:(*quic.stream)(0x11d10210), OnError:(func(error))(0x83a0a0)} return 3444 *net.O
pError(write tcp 127.0.0.1:8087->127.0.0.1:52821: wsasend: An established connec
tion was aborted by the software in your host machine.)
I0715 20:21:16.240056    7460 stripssl.go:158] 127.0.0.1:52852 "STRIP CONNECT ww
w.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:16.353063    7460 gae.go:568] 127.0.0.1:52795 "GAE FETCH GET https:/
/www.smartdnsproxy.com/images/rounded_boxbg.png HTTP/1.1" 200 426
I0715 20:21:16.353063    7460 gae.go:568] 127.0.0.1:52768 "GAE FETCH GET https:/
/images.smartdnsproxy.com/images/logo/digital_journal.png HTTP/1.1" 200 610
I0715 20:21:16.367063    7460 gae.go:568] 127.0.0.1:52836 "GAE FETCH GET https:/
/www.smartdnsproxy.com/css/fonts/ProximaNova-Bold.woff HTTP/1.1" 200 59820
I0715 20:21:16.372064    7460 gae.go:568] 127.0.0.1:52770 "GAE FETCH GET https:/
/images.smartdnsproxy.com/images/logo/geek_insider.png HTTP/1.1" 200 1156
I0715 20:21:16.399065    7460 gae.go:568] 127.0.0.1:52712 "GAE FETCH GET https:/
/www.smartdnsproxy.com/images/feature_bg.jpg HTTP/1.1" 200 15063
I0715 20:21:16.408066    7460 stripssl.go:158] 127.0.0.1:52861 "STRIP CONNECT ww
w.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:16.567075    7460 handler.go:145] IOCopy &gae.onErrorBody{ReadCloser
:(*quic.stream)(0x12634f20), OnError:(func(error))(0x83a0a0)} return 15731 *net.
OpError(write tcp 127.0.0.1:8087->127.0.0.1:52836: wsasend: An established conne
ction was aborted by the software in your host machine.)
I0715 20:21:21.041331    7460 stripssl.go:158] 127.0.0.1:53157 "STRIP CONNECT ww
w.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:25.882608    7460 stripssl.go:158] 127.0.0.1:53459 "STRIP CONNECT cl
ients4.google.com:443 HTTP/1.1" - -
I0715 20:21:29.090791    7460 stripssl.go:158] 127.0.0.1:53650 "STRIP CONNECT ww
w.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:29.127793    7460 stripssl.go:158] 127.0.0.1:53652 "STRIP CONNECT ww
w.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:29.127793    7460 stripssl.go:158] 127.0.0.1:53653 "STRIP CONNECT ww
w.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:29.138794    7460 gae.go:527] 127.0.0.1:53653 "GAE FAKEOPTIONS OPTIO
NS https://www.smartdnsproxy.com/lib/mapplic/world.json HTTP/1.1" 200
I0715 20:21:29.168796    7460 stripssl.go:158] 127.0.0.1:53655 "STRIP CONNECT ww
w.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:29.216798    7460 stripssl.go:158] 127.0.0.1:53660 "STRIP CONNECT ww
w.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:30.508872    7460 stripssl.go:158] 127.0.0.1:53743 "STRIP CONNECT im
ages.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:38.376322    7460 stripssl.go:158] 127.0.0.1:54233 "STRIP CONNECT im
ages.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:38.377322    7460 stripssl.go:158] 127.0.0.1:54234 "STRIP CONNECT im
ages.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:38.377322    7460 stripssl.go:158] 127.0.0.1:54235 "STRIP CONNECT im
ages.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:38.380322    7460 stripssl.go:158] 127.0.0.1:54236 "STRIP CONNECT im
ages.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:38.394323    7460 stripssl.go:158] 127.0.0.1:54238 "STRIP CONNECT im
ages.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:21:38.397323    7460 stripssl.go:158] 127.0.0.1:54239 "STRIP CONNECT im
ages.smartdnsproxy.com:443 HTTP/1.1" - -
I0715 20:22:21.975613    7460 stripssl.go:158] 127.0.0.1:57009 "STRIP CONNECT mt
alk.google.com:443 HTTP/1.1" - -
I0715 20:22:41.435425    7460 stripssl.go:158] 127.0.0.1:58236 "STRIP CONNECT ww
w.facebook.com:443 HTTP/1.1" - -
I0715 20:22:41.466426    7460 stripssl.go:158] 127.0.0.1:58237 "STRIP CONNECT ww
w.facebook.com:443 HTTP/1.1" - -
I0715 20:22:41.478427    7460 stripssl.go:158] 127.0.0.1:58239 "STRIP CONNECT cl
ients1.google.com:443 HTTP/1.1" - -
I0715 20:23:04.837422    7460 stripssl.go:158] 127.0.0.1:59723 "STRIP CONNECT pr
ogram-think.blogspot.com:443 HTTP/1.1" - -
I0715 20:23:04.840422    7460 stripssl.go:158] 127.0.0.1:59724 "STRIP CONNECT ww
w.blogger.com:443 HTTP/1.1" - -
I0715 20:23:04.849422    7460 stripssl.go:158] 127.0.0.1:59725 "STRIP CONNECT ww
w.blogger.com:443 HTTP/1.1" - -
I0715 20:23:04.899425    7460 stripssl.go:158] 127.0.0.1:59726 "STRIP CONNECT ww
w.blogger.com:443 HTTP/1.1" - -
I0715 20:23:13.830936    7460 stripssl.go:158] 127.0.0.1:60300 "STRIP CONNECT ww
w.blogger.com:443 HTTP/1.1" - -
I0715 20:23:13.850937    7460 stripssl.go:158] 127.0.0.1:60301 "STRIP CONNECT ww
w.blogger.com:443 HTTP/1.1" - -
I0715 20:23:13.853937    7460 stripssl.go:158] 127.0.0.1:60303 "STRIP CONNECT pr
ogram-think.blogspot.com:443 HTTP/1.1" - -
I0715 20:23:33.200044    7460 stripssl.go:158] 127.0.0.1:61547 "STRIP CONNECT ww
w.blogger.com:443 HTTP/1.1" - -
I0715 20:23:33.225045    7460 stripssl.go:158] 127.0.0.1:61548 "STRIP CONNECT pr
ogram-think.blogspot.com:443 HTTP/1.1" - -
I0715 20:23:33.379054    7460 stripssl.go:158] 127.0.0.1:61559 "STRIP CONNECT pr
ogram-think.blogspot.com:443 HTTP/1.1" - -
I0715 20:23:33.554064    7460 stripssl.go:158] 127.0.0.1:61571 "STRIP CONNECT pr
ogram-think.blogspot.com:443 HTTP/1.1" - -
I0715 20:23:33.712073    7460 stripssl.go:158] 127.0.0.1:61583 "STRIP CONNECT pr
ogram-think.blogspot.com:443 HTTP/1.1" - -
I0715 20:23:33.880083    7460 stripssl.go:158] 127.0.0.1:61594 "STRIP CONNECT pr
ogram-think.blogspot.com:443 HTTP/1.1" - -
I0715 20:23:34.042092    7460 stripssl.go:158] 127.0.0.1:61606 "STRIP CONNECT pr
ogram-think.blogspot.com:443 HTTP/1.1" - -
I0715 20:23:55.928344    7460 stripssl.go:158] 127.0.0.1:63011 "STRIP CONNECT pr
ogram-think.blogspot.com:443 HTTP/1.1" - -`
希望社长加以改进，谢谢！

**Comment by xiaomage2000** [comment]
任何网页无法打开，重启恢复正常。多次出现此问题。

**Comment by phuslu** [comment]
是不是开启了 quic?

**Comment by xiaomage2000** [comment]
@phuslu 
是的，之前还出现过`NetworkIdleTimeout: No recent network activity`的问题，当时没有截图，日志没有保留下来。

**Comment by phuslu** [comment]
已知问题，请暂时先忍忍吧。

正在修复

**Comment by xiaomage2000** [comment]
好的，谢谢社长！
