### ISSUE TITLE
此网页有部分显示不出来

### ISSUE THREAD

**Issue by jzmswe** [phuslu/goproxy#1891]
https://cn.nytimes.com/china/20170713/liu-xiaobo-dies-at-61/
# BTW：在gae.json中把 EnableQuic": false 改为 true，quic就开启成功了？
![20170717141807](https://user-images.githubusercontent.com/11971258/28257291-449ef70c-6afc-11e7-9a44-44a95acafdc3.png)

**Comment by jasonliul** [comment]
成为显示不出来的那部分...
:)

**Comment by jzmswe** [comment]
多谢，回复有内涵有深度。不过，请问怎样才能使之显示出来？

**Comment by jasonliul** [comment]
@jzmswe 
中国的伟大, 来自秦始皇, 将人与财物分离. 我们称为暴君, 仅仅因为他将六七代人完成的旷世功勋, 坚持一代完成, 完全没有中国人推己及人的初心.

世界历史上, 平民最初的声音来自中国, 两个心怀不满的民工:
**王侯将相, 宁有种乎?** 西方要迟千余年.

**中国人曾经是将秦始皇, 两个民工同等尊崇的人类文明先驱.**

我们都是先辈的后裔, 何须膜拜偶像, 
没有伟人创造中国历史, 从两个民工开始, 从来都是那些默默无名, 谦卑踏实的中国草民.

伟大的只是群体, 没有呕像.

**Comment by qwerttaa** [comment]
这个是要是gfwlist的坑吧？那一部分的域名是不是不一样了？

**Comment by jzmswe** [comment]
@qwerttaa 可是在autoproxy.json中把
"GFWList": {
		"Enabled": true,
true改为false，再去那个网页试，还是不行。

**Comment by panpeach** [comment]
并非GP问题，用SS全局也无法显示。换IE等多个浏览器也一样无法显示。

**Comment by MeABc** [comment]
![default](https://user-images.githubusercontent.com/18194126/28261946-d7a8fc70-6b13-11e7-91a0-7ed72ca518d2.png)

美帝真是不知我们的小水管，将近 600 个请求。。。。。。

**Comment by Lemonjay** [comment]
楼主，这张图片瘆得慌，应该打打马赛克。 哈哈!
