### ISSUE TITLE
@phuslu 在搞事情啊（

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1899]
![](https://raw.githubusercontent.com/dou4cc/resource/master/phuslu-wtf.png)

**Comment by dou4cc** [comment]
@phuslu 一个版本发3次？？？

**Comment by phuslu** [comment]
没有啦，是重复 ci 三次。。。

**Comment by jasonliul** [comment]
@phuslu 
社长, 新版本性能提升, 该发帖号召升级了~

**Comment by dou4cc** [comment]
@phuslu 3次一样只是changelog不同吗？

**Comment by phuslu** [comment]
@jasonliul quic 的 bug 还没修完，我要适配一下 quic-go 这个新改动。github.com/lucas-clemente/quic-go/pull/579

@dou4cc 嗯。

**Comment by jasonliul** [comment]
@dou4cc 
标题党, 捉住, 拧pat~~~
