### ISSUE TITLE
“没有可是”

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#1901]
[link](https://www.v2ex.com/t/376275)
💊？

**Comment by SeaHOH** [comment]
这种谣言都传，用屁股想都知道是假的。

**Comment by jasonliul** [comment]
@SeaHOH 
揪住, 原来你也是粪青.

Wiki: 粪青, 由于过度粪涨, 该生物切换为使用屁股思考, 美称粪青.
**严重警告: 专业人士动作, 请勿模仿**

**Comment by SeaHOH** [comment]
讲道理好不好，堵是肯定的，堵死就只可能是找死了。
要知道，国家这么大，人口这么多……逼急了发生点什么都不奇怪。

**Comment by phuslu** [comment]
最近还是不要讨论的好，等等看吧。
