### ISSUE TITLE
今晚 goproxy 项目会转为 github 私有项目。

### ISSUE THREAD

**Issue by phuslu** [phuslu/goproxy#1905]
何时再开，并不确定。二进制文件，应该还可以在 ci 项目中找到。

诸君再会。请勿乱回帖，我可能删此贴回复的啊。

**Comment by Asteroids89** [comment]
社长，什么意思？是不是goproxy项目以后就不公开了么？

**Comment by kirbyzhu** [comment]
赶紧保存文件

**Comment by phuslu** [comment]
嗯，goproxy 这个项目就不会公开了。不过以后的二进制和代码已然能从 goproxy-ci 拿到。

最大的影响是 issues 讨论区不可见了，这个我觉得对不住大家。

希望形式能够有重开的机会。

**Comment by kirbyzhu** [comment]
噩耗，太遗憾了！

**Comment by minorisprit** [comment]
噩耗，这次堪比当时goa关闭啊，难道要转移到G+或者reddit？

**Comment by hyperdoit** [comment]
为什么，和goagent的原因一样吗？

**Comment by phuslu** [comment]
这次不一样，是我自主决定。主要就是避风，希望自己的工作生活在这段时间不受影响。

**Comment by minorisprit** [comment]
最近管控要空前严格听说了，校长搞出了嗅探SS的也听说了，不过社长不是已经肉翻了么，最近回来了？

**Comment by jasonliul** [comment]
@phuslu 
社长, 你所做的, 已经远远超出你该做的...
金陵的樱花柳巷, 再会社长~~

**Comment by MeABc** [comment]
什么情况。。。

**Comment by Asteroids89** [comment]
尊重社长的决定，希望还有再见时！

**Comment by jasonliul** [comment]
@MeABc 
... 俺也不再在中国论坛现身, 2015-2017.

天下熙熙，皆为利来；天下攘攘，皆为利往。

**Comment by MeABc** [comment]
哎。。。。

**Comment by minorisprit** [comment]
@jasonliul 
G+，reddit都不错，G+中文社区也算相当壮大了，大部分SS的讨论都在上面

**Comment by wz7465** [comment]
1480版下载好了，谢谢社长的付出

**Comment by MeABc** [comment]
社长，希望能再会。

**Comment by Asteroids89** [comment]
社长，你有G+么？ @phuslu

**Comment by minorisprit** [comment]
@jasonliul 
G+，reddit都不错，G+中文社区也算相当壮大了，大部分SS的讨论都在上面

**Comment by starobots** [comment]
还能自动更新吗。

**Comment by phuslu** [comment]
自动更新的功能已经迁移到 goproxy-ci 了。所以不会受影响。

其实我大半年前就对形势有些担忧，所以陆续完善了一下 goproxy-ci 这个东东。

希望能够保留下来。

**Comment by Asteroids89** [comment]
社长深谋远虑呀，🐮 ( ఠൠఠ )ﾉ

**Comment by starobots** [comment]
多谢大佬

**Comment by kirbyzhu** [comment]
感谢社长！

**Comment by fredericky123** [comment]
希望能在转私有之前在G+开个讨论组

**Comment by SeaHOH** [comment]
谢谢！

**Comment by liweitd** [comment]
好难过，感谢社长！

**Comment by hcym** [comment]
感谢社长！

**Comment by baoziwan** [comment]
社长保重！

**Comment by houhuliang** [comment]
谢谢社长，祝君一切安好！

**Comment by Waynesway** [comment]
感谢社长，再会！

**Comment by mailsuhua** [comment]
谢谢一直以来的无私付出

**Comment by xrwz007** [comment]
感谢社长这么多年

**Comment by ydq** [comment]
感谢社长这么多年默默的付出

**Comment by phuslu** [comment]
凛冬已至矣，吾血尚温乎？

谢谢，再会。
