### ISSUE TITLE
r169经常error403

### ISSUE THREAD

**Issue by hijklmn** [phuslu/goproxy#194]
不知道是不是没有有效IP还是什么原因，会是不是出现403错误，刷新以后偶尔会重新恢复。

**Comment by cnv5** [comment]
使用goproxy时怎么判断ip失效，goa比较直观，可以看出好的ip数量，gop从哪里可以看出来？

**Comment by p1956** [comment]
有严重bug，php模式下载大文件会中断，有些地址下载后暂停再继续就报错，旧版新版都有这个问题

**Comment by cnv5** [comment]
使用一批Ip，用Goa3.2.3版基本不断线，r169经常403错误导致断线，希望开发者找出原因完善一下。
