### ISSUE TITLE
请问下50个左右IP在线播放很慢下载速度满速是什么原因？

### ISSUE THREAD

**Issue by fei5seven** [phuslu/goproxy#1942]
在使用联通的27 39段的时候基本这样，124段下载和播放速度基本相同，确定所有的流量都是通过gae的，然而油管也就2000左右，用mega通过GAE下载最少1.5M/S。有办法能优化这个情况吗？谢谢。。。

**Comment by dou4cc** [comment]
油管连接数有限，你把googlevideo加进autorange

**Comment by fei5seven** [comment]
![Uploading image.png…]()
IP也不少，但是现在的下载也慢的不行了。感觉还是IP段的锅吧。。。

**Comment by fei5seven** [comment]
![qq 20170814193703](https://user-images.githubusercontent.com/12988636/29270170-11a7fa78-8128-11e7-9a23-d3e199a167ca.jpg)

**Comment by c6132a1** [comment]
dou4cc   googlevideo怎么加进autorange

**Comment by fei5seven** [comment]
我是直接加了一行"*.googlevide.com",并不知道对不对，因为加了还是没感觉，无奈，晚上再去播124段IP去

**Comment by c6132a1** [comment]
你少了一个o, fei5seven

**Comment by fei5seven** [comment]
呃。好吧，拼写错误，设置里没写错

**Comment by fei5seven** [comment]
@c6132a1 
![qq 20170814222517](https://user-images.githubusercontent.com/12988636/29275954-84cf1448-813f-11e7-9aa4-15c9991fdfaa.jpg)
我试了下用扫了7000多个IP丢进去，开了quic，联通27段 按理说是干扰比较严重的段了，实在是没耐心去抽124段IP这个奖了，这样的话其实也基本满足了，
设置下"Threads": 5,

**Comment by c6132a1** [comment]
fei5seven ,我是电脑菜鸟，这个Threads": 5,在哪里，还有图片怎么添上去。

**Comment by fei5seven** [comment]
图片直接拖到框里就行。。。然后这个是在autorange.json最下面

**Comment by c6132a1** [comment]
怎么把图片拖到框里，兄弟

**Comment by c6132a1** [comment]
"MaxSize": 1572864,
"BufSize": 32768,
"waitsize": 524288,
"Threads": 3,

**Comment by MeABc** [comment]
兄弟，我就服你。。。。
![2](https://user-images.githubusercontent.com/18194126/29318990-e18957c8-8204-11e7-8649-fe5706260646.png)

**Comment by MeABc** [comment]
![2](https://user-images.githubusercontent.com/18194126/29319012-faae1f22-8204-11e7-8dbd-8a8c95338ee2.gif)

**Comment by c6132a1** [comment]
2.png这个软件哪里来的

**Comment by dou4cc** [comment]
@c6132a1 就服你

**Comment by fei5seven** [comment]
我。。。。。回复完他那句话他又问我我觉得此贴就可以终结了来着。。。。

**Comment by c6132a1** [comment]
桌面搞好了2.png，图片怎么进去。

**Comment by dou4cc** [comment]
@fei5seven close吧
