### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by out0fmemory** [phuslu/goproxy#1947]
ubuntu14.04 64位系统，按照步骤编译出现如下错误

httpproxy/proxy/https.go:20:2: cannot find package "github.com/google/boringssl/ssl/test/runner" in any of:
	/home/loong/goproxy/go/src/github.com/google/boringssl/ssl/test/runner (from $GOROOT)
	/home/loong/goproxy/gopath/src/github.com/google/boringssl/ssl/test/runner (from $GOPATH)

**Comment by MeABc** [comment]
如果是按照“编译步骤”里面来操作就会出现这个，要加上这个：

[build/ci.sh#L117](https://github.com/phuslu/goproxy/blob/master/assets/build/ci.sh#L117)

```javascript
	git clone https://github.com/google/boringssl $GOPATH/src/github.com/google/boringssl
	cd $GOPATH/src/github.com/google/boringssl/ssl/test/runner
	sed -i -E 's#"./(curve25519|poly1305)"#"golang.org/x/crypto/\1"#g' *.go
	sed -i -E 's#"./(ed25519)"#"github.com/google/boringssl/ssl/test/runner/\1"#g' *.go
	sed -i -E 's#"./(internal/edwards25519)"#"github.com/google/boringssl/ssl/test/runner/ed25519/\1"#g' ed25519/*.go
	git commit -m "change imports" -s -a
        go get -x github.com/google/boringssl/ssl/test/runner
```

**Comment by out0fmemory** [comment]
@MeABc 多谢，明天我试试，现在木有虚拟机试
建议社长完善下编译文档
当然，我编译通过后会修改下提个pull

**Comment by phuslu** [comment]
谢谢，已经修改了 wiki 文档。

魔改较多，编译时麻烦了一些。又因为模块之间独立比较强，不好引入 vendor 机制。这块的确搞得不是特别友好，但是的确已经尽力了。

**Comment by out0fmemory** [comment]
@phuslu 
问题已解决，thks
