### ISSUE TITLE
ip越来越少，有朋友贡献新ip段吗

### ISSUE THREAD

**Issue by sundaqing1969** [phuslu/goproxy#195]

**Comment by toobed** [comment]
感觉很恐怖，似乎主创人员出事了？这几天帖子都没人发了，连XX-Net都用不了，似乎gcd开始大规模行动了，白色恐怖的感觉人心惶惶

**Comment by yqy6611** [comment]
自己去找

**Comment by zhanxiage233** [comment]
@toobed 别自己吓自己，xxnet和蓝灯现在都很好用，都是满速状态

**Comment by vcheng** [comment]
还白色恐怖。。。。

**Comment by jasonliul** [comment]
58.123.220.72|58.123.220.97|201.151.207.6|201.151.207.51|217.13.217.34

**Comment by sundaqing1969** [comment]
感谢分享

**Comment by jasonliul** [comment]
61.91.18.68|61.91.18.73|178.45.251.82|178.45.251.115|178.45.251.116|178.45.251.117

**Comment by jasonliul** [comment]
61.91.18.68|61.91.18.73

118.98.30.9|118.98.106.71|118.98.106.70

178.45.251.82|178.45.251.116|178.45.251.117|178.45.251.115

**Comment by sundaqing1969** [comment]
兄弟，感谢分享

**Comment by sundaqing1969** [comment]
啊
