### ISSUE TITLE
网页开启速度慢，偶尔会爆黄红字，请问是什么原因？版本为1550

### ISSUE THREAD

**Issue by mooredam** [phuslu/goproxy#1955]
![default](https://user-images.githubusercontent.com/13420372/29484624-20002b4c-84f5-11e7-974c-a76f3af70400.png)

**Comment by mooredam** [comment]
![1](https://user-images.githubusercontent.com/13420372/29484652-ce0f055a-84f5-11e7-9621-c4e166471e21.png)

**Comment by phuslu** [comment]
额，貌似你没放自定义 ip 进去?

**Comment by phuslu** [comment]
尝试用 gscan_quic 扫一批 ip 试下。
