### ISSUE TITLE
图片不显示了

### ISSUE THREAD

**Issue by Asteroids89** [phuslu/goproxy#1961]
社长，现在用的是最新版的服务端和客户端R76和R1553,浏览器是chrome最新稳定版
http://www.cool18.com/bbs6/index.php?app=forum&act=threadview&tid=14227429   
此网站的图片都不能显示了，用全局模式也不能显示，以前是可以显示的，请问是 什么原因，可以修复么？  谢谢
PS：此网站是含有18禁内容 @phuslu

**Comment by Asteroids89** [comment]
以前可以显示的服务端和客户端应该是 R73和R1547及以前（或许不准确）

**Comment by phuslu** [comment]
新版服务端的问题，目前新的服务端还未稳定，请保持关注。

**Comment by Asteroids89** [comment]
好的，谢谢社长

**Comment by SeaHOH** [comment]
这个其实不算 goproxy 的锅，是图片服务器返回了错误的 header，可以用相关浏览器插件修复。

**Comment by SeaHOH** [comment]
以前有修改 header 的插件，现在不知道有没有，名字我也忘了……

**Comment by phuslu** [comment]
看了一下，的确服务器图片返回有误，我尝试修复一下。

**Comment by SeaHOH** [comment]
感觉修复这个挺麻烦的，这次是图片，以后其它网站出错怎么办？

**Comment by Asteroids89** [comment]
社长辛苦了，赶紧升级去

**Comment by SeaHOH** [comment]
@Asteroids89 还没有发布，需下载源码替换。

**Comment by phuslu** [comment]
不恢复没关系，只要没有 `Content-Encoding: deflate`， 浏览器会做猜测(sniff)
不过这一行为可以通过 `X-Content-Type-Options: nosniff` 禁用。

**Comment by phuslu** [comment]
r77 已经可用了

**Comment by Asteroids89** [comment]
谢谢社长

**Comment by phuslu** [comment]
服务端正在持续改动，请勿追新。稳定了我会发帖通知的。
