### ISSUE TITLE
youtube-dl 需要怎么配置 似乎用不了

### ISSUE THREAD

**Issue by skychan** [phuslu/goproxy#1965]
我在服务器(server ip) 上启动的goproxy，httpproxy.json 配置如下：
{
	"Default": {
		"Enabled": true,
		"Address": "0.0.0.0:8087",
		"KeepAlivePeriod": 0,
		"ReadTimeout": 600,
		"WriteTimeout": 3600,
		"RequestFilters": [
			// "auth",
			// "rewrite",
			"autoproxy",
			"stripssl",
			"autorange",
		],
		"RoundTripFilters": [
			"autoproxy",
			// "auth",
			// "vps",
			// "php",
			"gae",
			"direct",
		],
		"ResponseFilters": [
			// "autorange",
			// "rewrite",
		]
	},
	"PHP": {
		"Enabled": false,
		"Address": "127.0.0.1:8088",
		"KeepAlivePeriod": 0,
		"ReadTimeout": 600,
		"WriteTimeout": 3600,
		"RequestFilters": [
			"stripssl",
		],
		"RoundTripFilters": [
			"autoproxy",
			"php",
		],
		"ResponseFilters": [
		]
	},
}

在客户端机器上浏览器访问都没问题，但是使用youtube-dl 下载视频似乎不行，错误如下：

% youtube-dl --proxy [server ip]:8087 --no-check-certificate "http://www.youtube.com/watch\?v\=vT1JzLTH4G4\&index\=1\&list\=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--proxy', '[server ip]:8087', '--no-check-certificate', 'http://www.youtube.com/watch\\?v\\=vT1JzLTH4G4\\&index\\=1\\&list\\=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.08.18
[debug] Python version 3.6.2 - Linux-4.12.8-2-ARCH-x86_64-with-arch-Arch-Linux
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3, rtmpdump 2.4
[debug] Proxy map: {'http': '[server ip]:8087', 'https': '[server ip]:8087'}
[generic] watch\?v\=vT1JzLTH4G4\&index\=1\&list\=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv: Requesting header
WARNING: Could not send HEAD request to http://www.youtube.com/watch\?v\=vT1JzLTH4G4\&index\=1\&list\=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv: HTTP Error 404: Not Found
[generic] watch\?v\=vT1JzLTH4G4\&index\=1\&list\=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 502, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 2168, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

请问是什么原因造成的呢

**Comment by SeaHOH** [comment]
不要用斜杠转义

**Comment by skychan** [comment]
@SeaHOH 塞高！
我发现是我的终端在粘贴url的时候，自动添加了斜杠转义。
