### ISSUE TITLE
任务栏没有QUIC开关是有点不方便，弄个批处理凑合用

### ISSUE THREAD

**Issue by ashi876** [phuslu/goproxy#1969]
随便弄了个批处理方便点
@echo off
setlocal enabledelayedexpansion
title dll
color f0 
mode con: cols=45 lines=15
cls>nul
:menu
echo ================================
echo 关闭quic并重启GP………………1
echo 打开quic并重启GP………………2
echo 退出………………………………3
echo ================================

set /p UserSelection=选择 ( 1 , 2 ，3)
if "%UserSelection%"=="3" (
exit
) 
if "%UserSelection%"=="1" (
goto quicoff
:quicoff
@echo off&setlocal enabledelayedexpansion
set "src="EnableQuic": true,"
set "dst="EnableQuic": false,"
(for /f "delims=" %%a in (gae.user.json) do (
    set "str=%%a"
    echo,!str:%src%=%dst%!
))>#
@move # gae.user.json
taskkill /im goproxy-gui.exe /f
taskkill /im goproxy.exe /f
ping -n 2 127.0.0.1 > nul
start goproxy-gui.exe
)
::goto menu
if "%UserSelection%"=="2" (
goto quicon
:quicon
@echo off&setlocal enabledelayedexpansion
set "src="EnableQuic": false,"
set "dst="EnableQuic": true,"
(for /f "delims=" %%a in (gae.user.json) do (
    set "str=%%a"
    echo,!str:%src%=%dst%!
))>#
@move # gae.user.json
taskkill /im goproxy-gui.exe /f
taskkill /im goproxy.exe /f
ping -n 2 127.0.0.1 > nul
start goproxy-gui.exe
)
::goto menu

**Comment by mymatrix2002** [comment]
楼主你这个批处理会将原来gae.user.json中的谷歌IP地址清空的哟。希望能改进一下
