### ISSUE TITLE
废物利用 ---- 安卓 4.x 手机上运行 goproxy

### ISSUE THREAD

**Issue by MeABc** [phuslu/goproxy#1970]
**关键字：废物利用 `移动的 goproxy` **

理由：安卓 5.x 上可以用 termux ， 4.x 的不能用 termux 。所以。。。。开始折腾。。。。

方案：
使用 busybox + Linux Deploy 组合。这个方案可扩展性强。
除了 goproxy ，以后还可以安装 dns 、http server  等等。这就是一个随身携带的小型服务器。

前提条件：
手机系统 安卓  4.x ，且 root 。（怎么 root ，自行 google 。）

```
手机配置：

OS: Android 4.3
CPU: 高通 双核
RAM: 512MB
ROM：2GB 可用容量。不用 SD 卡，直接装在内部储存卡上。
```

使用的 apk ：
busybox  版本：1.27.1
Linux Deploy 版本：v2.0.2
JuiceSSH  版本：v2.1.4

安装顺序： busybox --> Linux Deploy --> JuiceSSH

busybox 和 JuiceSSH 的安装过程不写了。默认就行。不懂自行 google :)
JuiceSSH 在手机上用不多。
重点写下 Linux Deploy 设置、配置和安装过程。可能会没有图。

```
Linux Deploy 设置 （左上角的"三道杠"）

锁定屏幕：取消勾选
销定Wi-Fi：勾选
wake lock：勾选
语言：简体中文。(你英语好就用英文) 点击左上角的"三道杠"，Setting --> language --> 简体中文。
其它默认
```

```
Linux Deploy 属性（部署配置 --- 左下角下载图标）

Containerization method： chroot
发行版： Debian
发行版版本： stretch
架构： armhf （默认。软件自动选择。）
镜像地址： http://mirrors.ustc.edu.cn/debian/
安装类型：文件  （这个是重点。“文件”类型占用空间小。）
安装路径：默认。（${EXTERNAL_STORAGE}/linux.img）
镜像大小：  2048 MB
文件系统：默认。（我选择 ext4）
用户名：xxxx ( ssh 连接用到)
用户密码：xxxx ( ssh 连接用到)
本地化：zh_CN.UTF-8
选择组件： 只保留 SSH 服务器 ( SSH --> Enable -- 勾选 )

其它默认
图形界面： 取消勾选（破手机就不上这个了。。。）
自定义挂载（MOUNTS）： 取消勾选
```
安装过程注意事项：
1. 修改"属性"后须要重新"点击"一次"配置"（重新配置）。要点击“停止”才可以“安装”。
2. 安装过程中如有出错，须“停止”再重新“安装”。
3. 安装源尽量用国内源。国外源有可能都连不上，且中途容易出错。

安装过程：
右上角选择“安装”开始安装。（显示 `<<< deploy` 表示完成）
安装完成后“启动(start)”开始运行。（显示 `<<< start` 表示完成）

如下图：安装完成后，基本系统只占用 314M ，还有 1.6G 的空间。

![1](https://user-images.githubusercontent.com/18194126/29728078-19246a54-8a09-11e7-8274-7152f24523d2.png)

编译（可选）：
我使用的是自编译。关键字：GOARM=7
如不能自编译，armhf 架构选择的版本是 goproxy_linux_arm-rxxxx

SSH 上传 goproxy ：
使用 ssh 来上传文件。帐号密码是配置时所设定的。
windows 下我用 FileZilla （sftp）来上传文件。简单快捷。

FileZilla 设置：关键是红线部分。 

![image](https://user-images.githubusercontent.com/18194126/29745214-4b412ed0-8ae7-11e7-9b52-be6dfb219332.png)

上传前准备工作：
1. 解压 goproxy_linux_arm-rxxxx.tar.bz2
2. 拷贝 PC 上 goproxy 目录下的以下文件到上面解压目录下。

```
cache 目录以及子目录下所有文件
GoProxy.key
GoProxy.crt
*.user.json
proxy.pac
```
这样做其中一个重要目的：保持 Android 和 PC 端“证书”一样。

新建一个目录，用 FileZilla （sftp）上传到此目录下。结果图：

![image](https://user-images.githubusercontent.com/18194126/29745095-5bc0a710-8ae5-11e7-8327-55cb763f4e6c.png)

运行与使用：

```
# 增加运行权限
chmod +x goproxy

# 后台运行
nohup ./goproxy &>/dev/null &

# 下面这两个是查找和关闭 ---- 调试时或者出错时用。
ps -aux|grep goproxy
kill xxxxx
```

测试：

y2b 720p 视频测试（单开）。下面是1分钟动图。

![2](https://user-images.githubusercontent.com/18194126/29745261-9b214ca4-8ae8-11e7-86c1-ce6c46cbc8c2.gif)

CPU 占用看起“很高”，但你算下，前面几个加起来都超过 100% 了。。。。
使用过程中并没有延时的感觉 ---- 不管是网页还是视频。
最后最重重要的，耗电问题 ---- 垃圾手机一小时一天能耗多少电 :)

（goproxy 部分完）

--

（下部分预告 --- DNS ）

**Comment by candy2107** [comment]
安卓6 免root运行 goproxy (占楼待补)

**Comment by 2378** [comment]
支持折腾

**Comment by blob2015** [comment]
abc兄好腻害 😀 👍

**Comment by needfreedom** [comment]
好巧，这两天正为linuxdeploy犯愁。
每次点 install 均出现  >>>deploy后迅速跳<<< deploy，
谷歌不到解决办法。

**Comment by MeABc** [comment]
> 每次点 install 均出现 >>>deploy后迅速跳<<< deploy

这个要看具体日志信息。

是不是这情况（我上面有写）：
`修改"属性"后须要重新"点击"一次"配置"（重新配置）。要点击“停止”才可以“安装”。`

**Comment by MeABc** [comment]
>>>deploy
（重点是这里提示什么）
<<< deploy

**Comment by needfreedom** [comment]
刚才又试了一次，deploy之间无文字提示.
如 start  在 start之间 出现:
missing parameters : target_path

**Comment by MeABc** [comment]
> missing parameters : target_path

安装过程中是不是有出错了。
安装版本是什么，如果是其它版本的话，那你就要去 Linux Deploy 官方发 issue 了。

**Comment by needfreedom** [comment]
谢谢兄台，我自己再学习学习。

**Comment by alexhua** [comment]
其实，静态编译版本的 goproxy-linux-arm拷到安卓手机上直接可以通过adb跑起来。要尝鲜的可以这么试试。

**Comment by MeABc** [comment]
记录一下：

dns 错误：
有可能是没有 eth0 引起的？
ls /sys/class/net/
or
ifconfig -a

#1630

**Comment by wpyok500** [comment]
现在手机哼少有安卓4.X，有也是基本上老年人在用，这部分人基本不FQ吧，年青人、中年人、基本上连很大部分老年人也都是安卓5.X以上了吧。

**Comment by wpyok500** [comment]
现在手机哼少有安卓4.X，有也是基本上老年人在用，这部分人基本不FQ吧，年青人、中年人、基本上连很大部分老年人也都是安卓5.X以上了吧。

**Comment by MeABc** [comment]
如果说用安卓5.X 是青年人，安卓4.X 是老年人，那我就属于老年人那一波了。。。。

本帖主要目的是，用破旧的手机变废为宝。

**Comment by devcodewak** [comment]
@MeABc 好文，请教
此时手机浏览器选哪几个？需要配代理插件吗？插件？
另进阶如何全局或pac代理app ? 
　
这个方法可以类推gsnova、gost上, arm7编译，直接跑bin。
另root后，也可装下SSHDroid（即ssh服务端）+ 终端， pc端 putty + winscp
　
真心浏览器没配成。。。请教

**Comment by MeABc** [comment]
@devcodewak 说请教高抬我了（受宠若惊）

我的目标：双手机 或者 phone + pc 的方案解决翻墙。（需求是出远门。）
打算是在这个 4.x 手机装 DNS + goproxy + gsnova 这样一个组合。
浏览器通过 goproxy ，app (socks) 通过 gsnova 。
手机浏览器我用 Firefox ，使用 pac (goproxy)，通过自定义 pac 让 websocks 等分流到 gsnova 。

手机翻墙：
手机上的代理插件这个用不多，也不知道哪个好，我是打算试下 fqrouter 还能不能用。（还没弄）
手机全局，这个需求不多，一般都是通过“手机设置”里弄。

PS: 如果是单手机翻墙的话，貌似一个 gsnova 就可以解决（上面所有复杂的设置）。

**Comment by qwerttaa** [comment]
手机翻墙不是高频，蓝灯，赛风足矣，另外好像蓝灯要出ios版了

**Comment by kirbyzhu** [comment]
手机翻墙最大的意义在于热点分享

**Comment by devcodewak** [comment]
@MeABc 谢

手机上装了下firefox, 无代理选项。另扩展中 foxyproxy, pan 插件都不适合手机版。
gsnova 最近一直在大改，其安卓版稳定前不会出。

**Comment by wpyok500** [comment]
firefox 手机可以使用PAN插件，然后将默认的SS代理更改为GoAgent即可。

**Comment by MeABc** [comment]
@devcodewak 
firefox pac 设置可以参考这个（主要是有图）
https://github.com/XX-net/XX-Net/issues/6322
