### ISSUE TITLE
最新版 访问tumblr出问题

### ISSUE THREAD

**Issue by hg123** [phuslu/goproxy#1978]
比如这个网址 http://trust.tumblr.com/  显示一片空白

I0827 15:37:56.358844    3132 gae.go:575] 127.0.0.1:54372 "GAE FETCH GET http://trust.tumblr.com/ HTTP/1.0" 200
W0827 15:37:56.358844    3132 handler.go:147] IOCopy helpers.ReaderCloser{Reader:(*brotli.Reader)(0x1124bc00), Closer:(*gae.QuicBody)(0x1222c0e0)} return 0 errors.Error(brotli: corrupted input)

**Comment by MeABc** [comment]
![image](https://user-images.githubusercontent.com/18194126/29748015-e82e5cac-8b3e-11e7-95af-e933716d80bf.png)

PS: 最新版（客户端与服务端）

**Comment by hg123** [comment]
我这里服务端是r84 客户端是r1559 却无法打开 用xxnet却可以打开

**Comment by phuslu** [comment]
客户端更新到 r1560，然后再上传一次服务端

**Comment by hg123** [comment]
好的

**Comment by hg123** [comment]
已经重传服务端r84 客户端是r1561 打开网页还是一片空白 错误依旧 
难道是浏览器的问题 浏览器是firefox 54.0.1
I0827 16:09:09.739463    7668 gae.go:575] 127.0.0.1:50125 "GAE FETCH GET http://trust.tumblr.com/ HTTP/1.0" 200
W0827 16:09:09.739463    7668 handler.go:147] IOCopy helpers.ReaderCloser{Reader:(*brotli.Reader)(0x11b88000), Closer:(*gae.QuicBody)(0x11b10290)} return 0 errors.Error(brotli: corrupted input)

**Comment by phuslu** [comment]
哦，我待会看下，貌似 firefox 下有问题

**Comment by hg123** [comment]
刚试了下 chrome也是同样情况

**Comment by phuslu** [comment]
额，那就奇怪了，我这边不能复现。。。

**Comment by hg123** [comment]
我用edge能打开

**Comment by jap33** [comment]
firefox esr 52没问题。

**Comment by wenliyang** [comment]
Firefox 55.0.3，可正常访问

**Comment by darkwolf99** [comment]
我这里能正常打开
r84+r1561
cent (Chromium 60.0.3112.101)
电信

**Comment by hg123** [comment]
换成firefox55.0.2还是同样问题 我奇怪的是为什么同样浏览器xxnet可以打开 难道是我设置有问题？？？
但都是用gp IE和edge也可以打开 
为什么就我一个人碰到这个情况 难道是人品问题？

**Comment by beimunizhou** [comment]
我这边也没问题，你把之前用的删了重下包不就行了，很明显问题不在浏览器那里

**Comment by phuslu** [comment]
楼主你关了 quic 试下？

**Comment by beimunizhou** [comment]
![snipaste20170827_181232](https://user-images.githubusercontent.com/8838425/29748918-7f3a9dc2-8b53-11e7-9d26-81803adabcda.jpg)
火狐RunningCheese Firefox V8

**Comment by fengixng** [comment]
r84+1561
chrome版本 62.0.3192.0（正式版本） （64 位）
正常

**Comment by hg123** [comment]
关了quic  重下了客户端 还是打不开 这么奇怪的问题居然被我碰到了

**Comment by 94oiio** [comment]
r84+1563 没开quic
chrome版本 60.0.3112.113（正式版本） （64 位）
正常

**Comment by SeaHOH** [comment]
@hg123 安全模式启动火狐试试

**Comment by hg123** [comment]
安全模式重启火狐后 问题依然存在

不过我刚才用xxnet+chrome56 也打不开

换成xxnet+chrome43或火狐可以打开

可能还是与浏览器有一定关系

**Comment by hg123** [comment]
终于找到原因了
我的浏览器是便携版
所以浏览器必须以管理员身份运行 才能打开网页
