### ISSUE TITLE
遇到了非常奇怪的错误

### ISSUE THREAD

**Issue by xiaomage2000** [phuslu/goproxy#1983]
遇到了非常奇怪的错误，之前也遇到过，但没有今天这么严重。是IP问题吗？很久没有扫IP了。QUIC已关闭。
![default](https://user-images.githubusercontent.com/13915895/29822288-7f8a0b36-8cfd-11e7-9a4f-28607ed8c207.PNG)
![2](https://user-images.githubusercontent.com/13915895/29822296-82e87a10-8cfd-11e7-95dc-c92c8e08c16b.PNG)

**Comment by phuslu** [comment]
证书错误，你是不是开了 sslVerify?

**Comment by xiaomage2000** [comment]
@phuslu 是的，我关闭试了一下，目前这个问题没有再出现。谢谢！

**Comment by phuslu** [comment]
看起来 google 已经在陆续部署新的证书了。sslVerify 用的指纹也需要更新了。

**Comment by phuslu** [comment]
记录一下 https://censys.io/certificates/fdf89974b399dbfae76a6547588ee67035ec7b49cee76e9e1b848dc7f46a0428

**Comment by MeABc** [comment]
我这也有。。

![image](https://user-images.githubusercontent.com/18194126/29835942-2142f88e-8d26-11e7-9d79-5bcffc3ee8ac.png)

**Comment by phuslu** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=cert-test.sandbox.google.com

**Comment by phuslu** [comment]
http://pki.goog/gsr2/GTSGIAG3.crt
