### ISSUE TITLE
iOS上证书认证问题

### ISSUE THREAD

**Issue by hyperdoit** [phuslu/goproxy#1995]
证书已经导入并且信任，但是就是有ERR_CERT_AUTHORITY_INVALID
![img_1415](https://user-images.githubusercontent.com/25634373/30002010-8bc3a632-90d1-11e7-947e-40e7662105d1.png)
![img_1416](https://user-images.githubusercontent.com/25634373/30002012-90e2acd0-90d1-11e7-8580-676872edb286.png)

**Comment by hyperdoit** [comment]
访问www.google.com是ERR_CERT_AUTHORITY_INVALID
访问www.youtube.com是ERR_SSL_PROTOCOL_ERROR

**Comment by hyperdoit** [comment]
![image](https://user-images.githubusercontent.com/25634373/30025635-fdd5b2ee-91ab-11e7-93d3-4e9e2df7af2a.png)
访问YouTube

**Comment by hyperdoit** [comment]
![image](https://user-images.githubusercontent.com/25634373/30025694-36b21ad0-91ac-11e7-866d-a6d7bcaf2108.png)
访问google

**Comment by hyperdoit** [comment]
@dou4cc

**Comment by johnsonz** [comment]
#1784

**Comment by hyperdoit** [comment]
@johnsonz 你可以看我的第一张截图，确实这样设置了，然后也试过重新生成crt但是没用

**Comment by hyperdoit** [comment]
![image](https://user-images.githubusercontent.com/25634373/30055102-fa251be8-9260-11e7-9a2e-0e7a8d76eecc.png)

**Comment by hyperdoit** [comment]
@phuslu

**Comment by hyperdoit** [comment]
@inkdie
