### ISSUE TITLE
最近更新的GP都不错，夜猫出来啰

### ISSUE THREAD

**Issue by lsnmx** [phuslu/goproxy#1996]
goproxy r1577加持goproxy-gae-r90 速度确实给力，社长谢谢了！

弱弱问题一下Quic没动静了？
开Quic还是不能戴套啊

**Comment by fei5seven** [comment]
quic社长一直在常识完善，不要急啦。我这个疯狂干扰地区的人都习惯了【笑】

**Comment by masktao** [comment]
嗯,看u2不错.但是看图片居然红黄一片片,无法理解

**Comment by phuslu** [comment]
谢谢鼓励，quic 的话，我会跟随 quic-go 代码不停的做完善工作（其实就是所谓的抗干扰优化了）
