### ISSUE TITLE
goproxy登录谷歌云端硬盘点击上传出现错误

### ISSUE THREAD

**Issue by xyuanmu** [phuslu/goproxy#2]
使用goproxy r43版本，gae模式，登录谷歌硬盘后点击上传按钮后就会出现以下错误然后就离线了，要重启goproxy才能继续使用，修改过 iplist.json 里的ip，google_cn用的 gws ip，google_hk用的是 gvs ip，不知道是不是ip的问题，但是不修改ip又无法使用。
php模式可以点击上传按钮，可是上传无速度，所以也不能上传。
<pre>
goroutine 863 [IO wait]:
net.(*pollDesc).Wait(0xc0834b25f0, 0x72, 0x0, 0x0)
        /go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082040048, 0xc0834b24e0, 0x8dea60, 0x7, 0x9b9f78, 0xc083884e40, 0x0, 0x0)
        /go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0834b2480, 0xc083a47000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082040268, 0xc083a47000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/net/net.go:121 +0xe3
crypto/tls.(*block).readFromUntil(0xc0849fb770, 0x15f0a8, 0xc082040268, 0x5, 0x0, 0x0)
        /go/src/crypto/tls/conn.go:454 +0xed
crypto/tls.(*Conn).readRecord(0xc084060840, 0x17, 0x0, 0x0)
        /go/src/crypto/tls/conn.go:539 +0x2e1
crypto/tls.(*Conn).Read(0xc084060840, 0xc0838df000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/crypto/tls/conn.go:904 +0x16d
net/http.(*liveSwitchReader).Read(0xc084710c28, 0xc0838df000, 0x1000, 0x1000, 0x417249, 0x0, 0x0)
        /go/src/net/http/server.go:214 +0xb2
io.(*LimitedReader).Read(0xc084714560, 0xc0838df000, 0x1000, 0x1000, 0xc0834b2480, 0x0, 0x0)
        /go/src/io/io.go:408 +0xd5
bufio.(*Reader).fill(0xc0849f9b00)
        /go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).ReadSlice(0xc0849f9b00, 0xc0838d120a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/bufio/bufio.go:295 +0x25e
bufio.(*Reader).ReadLine(0xc0849f9b00, 0x0, 0x0, 0x0, 0xc081e07900, 0x0, 0x0)
        /go/src/bufio/bufio.go:324 +0x69
net/textproto.(*Reader).readLineSlice(0xc083f86e40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/net/textproto/reader.go:55 +0xa5
net/textproto.(*Reader).ReadLine(0xc083f86e40, 0x0, 0x0, 0x0, 0x0)
        /go/src/net/textproto/reader.go:36 +0x56
net/http.ReadRequest(0xc0849f9b00, 0xc0841dedd0, 0x0, 0x0)
        /go/src/net/http/request.go:598 +0xd2
net/http.(*conn).readRequest(0xc084710be0, 0x0, 0x0, 0x0)
        /go/src/net/http/server.go:586 +0x276
net/http.(*conn).serve(0xc084710be0)
        /go/src/net/http/server.go:1162 +0x6a5
created by net/http.(*Server).Serve
        /go/src/net/http/server.go:1751 +0x365
</pre>

**Comment by xyuanmu** [comment]
还有，刚刚提交issue的时候，一直转圈没有跳转，还以为发布失败，其实已经发表成功了。

**Comment by jzp820927** [comment]
goproxy 都好久没更新了
