### ISSUE TITLE
对端的证书有一个无效的签名。

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#200]
对端的证书有一个无效的签名。 （错误码： sec_error_bad_signature）

169 似乎不能使用加密连接, 奇怪
FF浏览器, 证书已导入

**Comment by weiliang1216** [comment]
浏览所有的网页都不行？
FF的证书是导入到server还是auth里了？

**Comment by jasonliul** [comment]
GAE+IP

**Comment by weiliang1216** [comment]
我的意思是通过goproxy走的所有网页都不行么？
从报错上看，感觉是导入到FF的证书有问题。

**Comment by jasonliul** [comment]
重新导入, 变成证书密钥对于所尝试的操作使用不当。 （错误码： sec_error_inadequate_key_usage）

会长天天趴在洋妞身上遛狗, 抛弃我等了. :(

**Comment by jasonliul** [comment]
新版无法得到有效的crt文件, 把旧版goagent目录下的拷贝过来,
一切Ok, 再度遛狗.

**Comment by lovegithu** [comment]
@jasonliul r169版本， chrome浏览器出现这个问题：NET::ERR_CERT_AUTHORITY_INVALID，遇到过没？

**Comment by jasonliul** [comment]
估计是同一个问题.
拷贝以前Goagent生成的crt应该也OK.

**Comment by lovegithu** [comment]
@jasonliul 已成功，非常感谢。
