### ISSUE TITLE
服务端更新appid失败，R90/R1572.

### ISSUE THREAD

**Issue by alpha-pi** [phuslu/goproxy#2001]
![default](https://user-images.githubusercontent.com/19911597/30143893-a2af64f8-93ba-11e7-99c6-4384b1ba7db7.png)

**Comment by SeaHOH** [comment]
把 `ForceGAE` 的 `appengine.google.com` 注释掉，上传完再改回来。

**Comment by alpha-pi** [comment]
@SeaHOH 问题成功解决，感谢！
