### ISSUE TITLE
最近几个版本页面显示不怎么好

### ISSUE THREAD

**Issue by playnetcn** [phuslu/goproxy#2003]
最近几个版本的客户端和服务端对一些网页显示不怎么好，例如港台网站，明报，苹果日报，on.cc刷页面不流畅，刷好几次才能完整显示出来，苹果日报视频看一半就断了，不能看完整视频，YOUTUBE页面加载的慢，视频还可以。总体感觉页面加载不怎么好，慢，有的时候需要反复刷页面，rfi法广也是听一次刷好次才能出来。请作者看看是啥原因。目前我已经升级到最新版本。启用了Quic。问题还是依旧。

**Comment by hotbbs** [comment]
更新到最新的服务端，再试一试吧

**Comment by phuslu** [comment]
贴下日志截图

**Comment by playnetcn** [comment]
W0908 10:10:02.524150    6008 gaetransport.go:133] GAE *h2quic.RoundTripper.Roun
dTrip("https://playnetcn.appspot.com/_gh/") get HTTP Error 400
W0908 10:10:02.526150    6008 gaetransport.go:133] GAE *h2quic.RoundTripper.Roun
dTrip("https://playnetcn.appspot.com/_gh/") get HTTP Error 400
W0908 10:10:10.214590    6008 handler.go:152] &gae.QuicBody{Stream:(*quic.stream
)(0x131bf760), Transport:(*h2quic.RoundTripper)(0x12278100), MultiDialer:(*helpe
rs.MultiDialer)(0x12268230)}.OnError(write tcp 127.0.0.1:1080->127.0.0.1:52951:
wsasend: An established connection was aborted by the software in your host mach
ine.) called.

**Comment by phuslu** [comment]
400 是 quic 模式的 bug，还没修复。

**Comment by playnetcn** [comment]
@phuslu 谢谢回复。
