### ISSUE TITLE
HTTPS 代理的问题

### ISSUE THREAD

**Issue by pexcn** [phuslu/goproxy#2004]
如果用 VPS 版的 goproxy, 使用 443 端口，以 GFW 的视角，是不是相当于访问一个 https 的网站？
而我换成其他端口，是不是就相当于访问一个非 443 端口的 https 站？

**Comment by phuslu** [comment]
理论上是这样。对付一般的 IPS 系统就够了。

但是如果做流量分析，比如分析访问真正的 HTTPS 和通过 HTTPS 代理访问 youtube 上的健身视频的差异。
通过机器学习是能分辨出来的。

不过在这种技术下，任何任何使用 socket 转发的工具基本都会暴露（ss/ssr 等），https 代理算是强度比较高的。
能够对抗这种分析的，我所知的只有 goproxy php 模式，因为使用了中间人证书，和真正的 HTTPS 流量已经无异。所以流量分析基本没有太大用处。

除了流量分析，工具还需防止探针试探。ssr 做了先驱性并且卓有成效的工作。
至于 HTTPS 代理，对抗探针的方式比较简单和容易，直接开启客户端证书验证就差不多了。

**Comment by pexcn** [comment]
原来是这样，谢谢。（另外第一句的 `IPS 系统`是不是打错字了？ISP？

**Comment by dou4cc** [comment]
@phuslu 流量分析分析不出你在翻墙不代表分析不出你在上YouTube

**Comment by SeaHOH** [comment]
@dou4cc 墙的能力是有限的，它实际不可能这么做，除非你被盯上了，会采取更加恶劣的手段监视。

**Comment by dou4cc** [comment]
@SeaHOH 喂，你别诅咒我啊~
你信不信以后gfw做到你家光猫里？

**Comment by SeaHOH** [comment]
改成除非我被……
