### ISSUE TITLE
如何验证 TLS 1.3 的问题

### ISSUE THREAD

**Issue by pexcn** [phuslu/goproxy#2005]
用了最新的 vps 版的 goproxy, 并在 Chrome 上配合 SwitchyOmega 使用 HTTP 2 代理，设置了 `disable_legacy_ssl = true`，Chrome 也开了 TLS 1.3

请问如何验证 TLS 1.3 已经启用了？

**Comment by pexcn** [comment]
![tls](https://user-images.githubusercontent.com/4590439/30205041-31de23f8-94ba-11e7-84a9-f7d000914f43.png)

这样是不是说明并没有启用 tls 1.3 呢?

**Comment by phuslu** [comment]
chrome://flags/#ssl-version-max

**Comment by phuslu** [comment]
你贴谷歌不能说明没有启用，因为这已经到了转发层面。

TLS1.3 是连接层面的事情，要访问你自己的 https 网站。

**Comment by pexcn** [comment]
emmm.... 服务器的 log 全是 tls 1.3 的，https://github.com/phuslu/goproxy/issues/1470 是一个 tls 1.3 代理的意思是不是说：从 vps 传回来的数据的连接是 tls 1.3？

**Comment by phuslu** [comment]
准确的说，是 tls1.2 over tls1.3

tls1.2 这个无法改变（除非做中间人证书）
tls1.3 是 goproxy-vps 为了效率做的优化。用的是 cloudflare 的补丁。

**Comment by pexcn** [comment]
原来是这样，太好了
