### ISSUE TITLE
嫌疑犯通缉令

### ISSUE THREAD

**Issue by wangjingzhuaren** [phuslu/goproxy#2011]
Phus Lu ：
　　你长期与反华势力狼狈为奸，已经违反相关法律与规定。公安部技术侦察组现已定位你的网络IP地址，限你于3日内到户籍所在地公安局或民政局投案自首，争取宽大处理，否则后果自负！

　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　南京市公安局
　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　2017年9月9日

**Comment by xxnet** [comment]
去死，你们这些土共的爪牙，哪天你们自己没有价值了，被土共维稳的时候，你们去哪里申诉去？

开源项目，不是你们想封就封的！

**Comment by mixool** [comment]
Closed. Blacklist this 傻逼。

**Comment by wegood9** [comment]
闲的蛋疼吧

**Comment by MeABc** [comment]
@wangjingzhuaren 祝你全家成为被维稳对象。

**Comment by jyuan15** [comment]
别开玩笑，P大不比其他人，他承受的压力要大得多。

**Comment by pexcn** [comment]
受不了这些傻逼，有能力的还是赶紧移民吧
