### ISSUE TITLE
goproxy-gae能抗高峰期的原因是啥

### ISSUE THREAD

**Issue by mixool** [phuslu/goproxy#2017]
美西的VPS白天能跑4000Kpbs，高峰期（现在周末20：00）只有300Kpbs。（goproxy-vps-http2）
而Goproxy-gae，基本都能稳定在7000Kpbs+。是得益于优质IP和autorange吗？
goproxy-vps 是否会支持autorange，能否在安卓手机上运行？

**Comment by phuslu** [comment]
ip 多了之后，候选的 ip 范围就比较多了。配合还行的筛选方法，所以受线路抽风影响就比较小。所谓的「以力破巧」

**Comment by phuslu** [comment]
和 autorange 关系不大，其实

**Comment by dou4cc** [comment]
@phuslu 是线路限速而非抽风，高峰时段有些isp会单连接限速，autorange还是有用的
