### ISSUE TITLE
反馈：开启 quic 可能导致服务端更新失败

### ISSUE THREAD

**Issue by 2378** [phuslu/goproxy#2018]
R91+r1588  更新R96 
关闭 quic 上传成功 更新成功
开启 quic 上传成功 更新失败 
“no transaction in process”
数据库的问题吗？
![20170910013717](https://user-images.githubusercontent.com/24506320/30242686-9d994c1c-95cd-11e7-8f35-c8b939fab237.jpg)

**Comment by fei5seven** [comment]
这个很正常啊，不开QUIC网络不稳定、ip质量差也有概率失败，本身QUIC社长就是处于开发完善阶段，出现断开连接再正常不过了。此贴终结【笑】

**Comment by phuslu** [comment]
嗯，已经复现，我看下

**Comment by blob2015** [comment]
目前更新服务端，还是加个袜子，关闭quic比较容易搞定
