### ISSUE TITLE
貌似墙进化了

### ISSUE THREAD

**Issue by sundaqing1969** [phuslu/goproxy#2021]
刚填入的好ip，打开一个被墙网站后，ip马上就失效了。

**Comment by dou4cc** [comment]
请提供详细信息

**Comment by phuslu** [comment]
(如果您是遇到本软件使用问题而并不清楚具体原因的话，请尽量提供更多信息，如软件版本，日志截图，地级运营商信息等。否则问题可能会被忽略或关闭)
