### ISSUE TITLE
这几天经常报404错误，或者白屏

### ISSUE THREAD

**Issue by TangBaohua** [phuslu/goproxy#2027]
![qq 20170914104731](https://user-images.githubusercontent.com/11957114/30409865-3dfa4534-993a-11e7-928f-75976537e783.png)
![404](https://user-images.githubusercontent.com/11957114/30409904-7c3aa532-993a-11e7-92ec-13617c66a5a0.png)

r1555

**Comment by qwerttaa** [comment]
1、升级客户端和服务端至最新
2、建议开启quic

**Comment by TangBaohua** [comment]
已经更新到最新版了，开启quic有时好一点，但还是经常出现
**Not Found
The requested URL /_gh/ was not found on this server.**
给我的生活带来极大不便

**Comment by TangBaohua** [comment]
已经更新到最新版了，开启quic有时好一点，但还是经常出现
**Not Found
The requested URL /_gh/ was not found on this server.**
给我的生活带来极大不便

**Comment by phuslu** [comment]
这是有 ip 是谷歌 IP。

**Comment by TangBaohua** [comment]
已经更新到最新版了，开启quic有时好一点，但还是经常出现
**Not Found
The requested URL /_gh/ was not found on this server.**
给我的生活带来极大不便

**Comment by phuslu** [comment]
这是有 ip 不是谷歌国外 IP。

**Comment by TangBaohua** [comment]
@phuslu 那我还是精简下IP
