### ISSUE TITLE
IP段分享（含搜索工具MFF）

### ISSUE THREAD

**Issue by Alvin9999** [phuslu/goproxy#2029]
[700万谷歌官方ip](https://nofile.io/f/X2ccqxNUfAy#256618fcee88e6be)

[3.8亿日韩ip](https://nofile.io/f/X2ccqxNUfAy#256618fcee88e6be)

[全球ip段](http://ipblock.chacuo.net/) 

 [MFFv8](http://www.mediafire.com/download/x6ezywy5c6xp7ed/MFF_1.0.8_v8_.net4.6.rar)

以上软件搜集自互联网。

**Comment by hyxxsfwy** [comment]
这个压缩包里的扫 IP 软件是 15 年的了，老了点吧，现在还是用 gscan 直接导入 IP 段扫比较靠谱。

**Comment by 1688pc** [comment]
@hyxxsfwy 蛤蛤出品必属精品，MFFv8修改版依然可用，扫ip速度超快，推荐使用Kisesy兄的修改版，本人依然以MFF为主力

**Comment by Limsig** [comment]
什么鬼，打开没多久就蓝屏了……

**Comment by Alvin9999** [comment]
@Limsig  这么奇怪啊，这些资源都是大佬分享的

**Comment by shihaibing** [comment]
@Kisesy

**Comment by Jason4774** [comment]
谢谢分享，前两个链接是一样的啊？

**Comment by Jason4774** [comment]
且下载的压缩包是损坏的呢？
