### ISSUE TITLE
大家的GVS都正常？

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#203]
我的一运行GVS，妥妥的404：
The requested URL /_gh/ was not found on this server.

**Comment by yqy6611** [comment]
没有更新服务端

**Comment by xyuanmu** [comment]
你之前使用的版本是多少？goagent 3.2.x 以及 goproxy 都需要重新上传appid

**Comment by TangBaohua** [comment]
有正常的，都是稀有IP，和客户端没关系，GoAgent我是用终极版

**Comment by bygloam** [comment]
正常 = =

**Comment by hijklmn** [comment]
终极版是哪个版本，3.2.3吗？

**Comment by hijklmn** [comment]
@TangBaohua 终极版是哪个版本，3.2.3吗？

**Comment by alresvor** [comment]
@hijklmn 不是，开发版最新
https://github.com/phuslu/goagent/archive/985cbd55e232833a859e7f2940b54f7dcb6cdb14.zip

**Comment by hijklmn** [comment]
@alresvor 多谢。

**Comment by sundaqing1969** [comment]
开发版最新是什么来历？@alresvor

**Comment by blob2015** [comment]
@xyuanmu
GA在用3.23，GWS没问题。

**Comment by blob2015** [comment]
@alresvor
感谢。
同问，开发最新版是？

**Comment by blob2015** [comment]
比较了一下alresvor提到的，proxy.py里面就多了“try:”，“except Exception as e:”等两三行代码。其他基本没有区别。

**Comment by blob2015** [comment]
@bygloam
老兄用的是Goproxy？

**Comment by alresvor** [comment]
@blob2015 
你得分跟哪个版本比啊，要是跟3.2.3比，那么多出将近100个提交，在这些提交中就添加了对GVS的支持
现在大家一般用的就支持了gvs，那么说明版本已经是比较新的

**Comment by sundaqing1969** [comment]
phuslu还在给goagent完善代码？

**Comment by blob2015** [comment]
@alresvor
感谢回复解惑

**Comment by hijklmn** [comment]
目前感觉goproxy不稳定，一直是时断时续，没有goagent用起来方便，不知道goproxy项目的优势在什么地方。另外如果没有好的办法扫到ip的话，这个项目前景就很渺茫了。

**Comment by blob2015** [comment]
@alresvor 
确实跟原始的3.2.3比，俺的3.2.3确实升级过，从phuslu的发布里面
---------------
@hijklmn 
目前phuslu在完善，只能慢慢来，毕竟他不是专职做这个。
怀念曾经的GVS，现在俺这边的GVS，基本上没法用，就剩下寥寥无几的GWS在撑着。

**Comment by TangBaohua** [comment]
@hijklmn 终极版就是作者的最后一个版本，6月17日发布的985cbd5(20150617)

**Comment by blob2015** [comment]
@yqy6611 
@xyuanmu 
@alresvor 
特意再次更新了一下服务端，但是还是会不时出现404，然后多刷几下就能好，因为ip里面掺杂了doc.google，或者GA对于vps的支持是不完全的？或者里面的配置出了问题？
用gws的话，没有问题。
网络是联通。

**Comment by blob2015** [comment]
绕了一圈，原来是跟ip的所在地相关
216打头的，还有国内的，就会有问题

**Comment by blob2015** [comment]
还有就是，*.c.docs.google.com最好不要用？要么很快失效，要么404？
