### ISSUE TITLE
关于ios手机共享使用局域网中电脑的代理

### ISSUE THREAD

**Issue by mymatrix2002** [phuslu/goproxy#2031]
已经将httpproxy.user.json中的监听地址改为0.0.0.0:8087，如下：
{
	"Default": {
		"Enabled": true,
		"Address": "0.0.0.0:8087",
		"KeepAlivePeriod": 0,

IOS手机中也将HTTP代理设为电脑（192.168.0.102）中的IP，端口8087。在Safari中可以打开http://192.168.0.102:8087，并导入goproxy.crt证书。

用Safari可以打开谷歌网页，但是用APP却不能连上YOUTUBE之类的视频软件，重点是不能连上ICLOUD备份，会出现以下红字错误
E0915 10:44:24.189131    8292 handler.go:74] 192.168.0.100:56270 Filter Request *stripssl.Filter error: remote error: tls: unknown certificate

请问各位这个该怎么解决？

**Comment by hyperdoit** [comment]
#1784

**Comment by phuslu** [comment]
也有可能是证书有效期的问题，前段时间刚改长了。

我改短试试

**Comment by mymatrix2002** [comment]
谢谢 @hyperdoit 和 @phuslu 的帮助，

**1. 导入goproxy.crt证书；
2. 设置---通用----关于本机-----证书信任设置，找到go的证书，把开关打开。**

这样设置后其他APP都可以共享使用局域网中电脑的代理了。
