### ISSUE TITLE
考虑到GAE支持了自定义域名，建议GoProxy和GoGoTunnel合并

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#2033]
gogo依托heroku，其只支持%appname%.herokuapp.com，gfw要封起来哗哗的。gae的ip多，但没有socket handle，只有http handle。所以我建议合并后的软件——
- 路线：浏览器---sniproxy---gae---heroku---目标网站
- 界面照搬现在的gogo，反正都是走sni，也不用找google ip了

@phuslu

**Comment by dou4cc** [comment]
@gogotunnel

**Comment by phuslu** [comment]
额，不太好吧，gogo 哪里不好了？ 我目前无意做这块。

**Comment by dou4cc** [comment]
heroku和quic都是用一天是一天的东西

**Comment by MeABc** [comment]
我个人不赞同这个，现在 goproxy 很小众，这种感觉真好 :trollface:

**Comment by dou4cc** [comment]
@MeABc 伸手党也有翻墙的权利

**Comment by MeABc** [comment]
不不不，我没有剥夺别人翻墙的权利的意思啊。。。。
