### ISSUE TITLE
谷歌不是可靠的中间人

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#2034]
http://www.solidot.org/story?sid=53858

**Comment by dou4cc** [comment]
邀请大家在此收集谷歌的恶。

**Comment by phuslu** [comment]
我不喜欢这种帖子。谷歌不欠我们，一遍用它的产品一篇骂它，没有公正性。

**Comment by SeaHOH** [comment]
利益而已，犯不着上纲上线。
先前我就表示过对谷歌返华的担忧，这中间有庞大的利益。

**Comment by dou4cc** [comment]
谷歌有远大的使命：https://zh.greatfire.org/blog/2016/dec/china-obstacle-google%E2%80%99s-plan-end-internet-censorship

谷歌本来就不以营利为目的。

**Comment by phuslu** [comment]
再强调一次我的观点，**一遍用它的产品一篇骂它，没有公正性。**

**Comment by SeaHOH** [comment]
只是个商业公司而已

**Comment by SeaHOH** [comment]
即使以前不是，现在也是了。

**Comment by phuslu** [comment]
说的再直白一点，谷歌如果为了返华而对中国 IP 关闭 GAE 入口，我也会觉得是我们*应得*的。

> 有个人很有爱心，尽管自己也不宽裕，但非常同情一个长期“住”在自家附近的乞丐，每个月施舍他100块钱，乞丐很感激。两年后的一天，他这一次给了乞丐50元。乞丐很诧异，问他为什么比原来给得少了。他解释说，自己的老婆刚生了第二个孩子，家庭开支加大，手头很拮据，所以以后每月只能给他50元。乞丐勃然大怒说，你凭什么拿我的钱去养你的孩子？？

**Comment by dou4cc** [comment]
@phuslu 你不该一边要求自己为了gop牺牲工作生活，一边宽容谷歌放弃使命甚至作恶。

**Comment by SeaHOH** [comment]
使命都是骗人的，连自己都骗……

**Comment by phuslu** [comment]
我们的权利（我是指联合国[世界人权宣言](https://zh.wikipedia.org/wiki/世界人权宣言)提出的**信息自由流动**的权利）是靠我们自己争取的。

谷歌的 GAE 只是一个施舍，不是我们天然的权利。

至于我维护 goproxy, 因为我是一个个体，一个中国人，做出的选择而已。
至于谷歌，它是一个美国商业公司，施舍出 GAE 的大量 IP 和流量，这对我们是施舍。

如果我们要评判它（的确，近几年它的风评是每况愈下），但是起码我们在批评的时候要保证自己的立场要站得住。

**Comment by SeaHOH** [comment]
@phuslu 倒也不完全是施舍，还是有利益考量在里面的。

**Comment by dou4cc** [comment]
。。。天真的我一直以为面对审查，谷歌是我们的一员。。。

**Comment by phuslu** [comment]
@dou4cc 也许曾今是。但是现在即使不是了，我们也没法苛责。因为它是一家美国商业公司，没有为我们战斗的道理。

上面的这个笑话，替我表达了我的观点。

**Comment by phuslu** [comment]
另外，谷歌真正的恶，不是在这些细微末节，而是它已经庞大到可以操控政府决策的地步了。
《生化危机》中保护伞公司已经初露峥嵘了。

http://www.ftchinese.com/story/001058677
http://cn.wsj.com/gb/20170713/tec084533.asp

这才是谷歌真正的恶，是会真真切切伤害到美国人民甚至世界人民的大恶。

**Comment by SeaHOH** [comment]
托拉斯……

**Comment by dou4cc** [comment]
@phuslu 自己人叛变，为什么不该数落？谷歌如果不接下破除审查的使命，也不会有像现在这样多的人以它为中间人翻墙。先友人后敌人，不是停止施舍而是阴谋。

**Comment by phuslu** [comment]
@dou4cc 它不是自己人，它是美国公司，还是一家商业公司。不是 NGO 组织。之前同情我们，现在不同情了，我们无话可说。是我们**应得**的。

什么叫“叛变”，把我们资料交出来，这才称得上“叛变”。具体案例，请谷歌 "雅虎 记者"

**Comment by phuslu** [comment]
PS: 今天有点激动，待会我把这个帖子回复都删了。抱歉。

**Comment by dou4cc** [comment]
@phuslu 所以我正在阻止悲剧的发生，谁知道那么多年来gae代理的https明文是不是一直被谷歌保存着

**Comment by phuslu** [comment]
再再再强调一次我的观点，**一边用它的免费产品一边用诛心之论骂它，没有公正性。**

**Comment by dou4cc** [comment]
@phuslu 我邀请大家罗列证据，你说我诛心，我为你遗憾。

**Comment by phuslu** [comment]
https://zh.wikipedia.org/zh-hans/极光行动 中谷歌已经证明了自己的底线，所以我说这是诛心。

**Comment by phuslu** [comment]
另外这个维基词条缺少了很多细节，要知道我为什么这么说，请看维基解密的相关细节。

**Comment by phuslu** [comment]
总结一下，我的观点有两个

1. 谷歌不在向中国用户提供 GAE 的话，不算作恶。（目前你也同意了）
2. 谷歌的底线不会把 GAE 的资料交出来。 （目前你还有疑问）

**Comment by SeaHOH** [comment]
>谷歌的底线不会把 GAE 的资料交出来。

这个不好讲，我们首先违反了谷歌的使用政策。

**Comment by dou4cc** [comment]
@phuslu 你close该issue来阻止大家讨论google的善恶以防悲剧，自己却接连放出证明google清白的链接。我不太懂你，希望你reopen。

**Comment by SeaHOH** [comment]
@dou4cc 商业公司也有商业公司的底线。

**Comment by SeaHOH** [comment]
它会虽其规模和影响而逐渐变化。

**Comment by phuslu** [comment]
@dou4cc 我 close 是为了了控制这个问题的讨论范围仅限于我们几个人。

**Comment by SeaHOH** [comment]
其实看几本经济类书籍就能理解了

**Comment by dou4cc** [comment]
@phuslu 你得对自己的言行负责：https://archive.is/v0YgW

**Comment by SeaHOH** [comment]
或者看看扎克伯格的言行就能窥得一二

**Comment by phuslu** [comment]
。。。你这人好烦，那我闭嘴好了。不用讨论了，一会我全删除。 @dou4cc 你到twitter上去散布这个链接好了。
