### ISSUE TITLE
google全封了，再没host可用了

### ISSUE THREAD

**Issue by wukent** [phuslu/goproxy#2035]
google全封了，再没host可用了。移动的。
扫了一晚上，没一个。

**Comment by phuslu** [comment]
9月13日开始，干扰增强。可以到 https://github.com/phuslu/goproxy/issues/2026 参与讨论，请勿重复发帖。

**Comment by wukent** [comment]
非913开始，之前至少有可用的，昨天傍晚开始，全封了。

**Comment by dou4cc** [comment]
@wukent 移动确实要dns去污染，不然整个网络都出问题。

**Comment by MeABc** [comment]
1. 换 IP 。
2. 换扫描工具。
如果再不行，然后就没有然后了。。。

**Comment by phuslu** [comment]
3 还有袜子最后一招，不过普通人不愿意这么烦就是了。

**Comment by MeABc** [comment]
![image](https://user-images.githubusercontent.com/18194126/30509603-763c1c70-9ae7-11e7-9867-a4f872aee938.png)

@wukent 亲，你这么做可不对哦，quic 还可用你上来就用 “google全封了”这种标题。。

**Comment by MeABc** [comment]
> 3 还有袜子最后一招

一般我不敢说这个，怕别人向我要袜子，我可不是J哥，手一挥上百个袜子。。。

**Comment by wukent** [comment]
@MeABc 
quic只在gproxy用，host用不上。socks慢。

**Comment by SeaHOH** [comment]
Chrome 可以直接用 host

**Comment by wukent** [comment]
一直用firefox

**Comment by dou4cc** [comment]
@SeaHOH 难不成你只上谷歌？

**Comment by SeaHOH** [comment]
@dou4cc 说明而已

**Comment by MeABc** [comment]
@dou4cc Chrome 只能上谷哥？

**Comment by SeaHOH** [comment]
而且这很对题……

**Comment by wukent** [comment]
下了一个xx-net，绝对熄火了。

**Comment by MeABc** [comment]
@wukent hosts 什么的可以有，搜一下。

**Comment by MeABc** [comment]
> 下了一个xx-net，绝对熄火了。

@wukent 不要搞大新闻，隔壁还有很多人能用。。。

**Comment by wukent** [comment]
@MeABc 
我截图给你看，开了半小时了。无法上图。

开始时间：
Sep 16 13:58:15.703 - [INFO] use build-in openssl lib
Sep 16 13:58:15.703 - [INFO] start XX-Net 3.4.2
Sep 16 13:58:15.703 - [DEBUG] start confirm_xxnet_exit
Sep 16 13:58:16.720 - [DEBUG] good, xxnet:8087 cleared!
Sep 16 13:58:17.751 - [DEBUG] good, xxnet:8085 clear!
Sep 16 13:58:17.751 - [DEBUG] finished confirm_xxnet_exit
Sep 16 13:58:18.188 - [INFO] SSL use version:TLSv1_2
Sep 16 13:58:19.282 - [INFO] OpenSSL support alpn
Sep 16 13:58:19.298 - [INFO] load ip range file:C:\Users\Administrator\Desktop\XX-Net-3.4.2\code\default\gae_proxy\local\ip_range.txt
Sep 16 13:58:19.423 - [INFO] detected Win10, enable connect concurrency control, interval:40
Sep 16 13:58:19.423 - [INFO] load google ip_list num:0, gws num:0
Sep 16 13:58:19.470 - [INFO] OpenSSL support alpn
Sep 16 13:58:19.485 - [WARNING] no enough ip
Sep 16 13:58:19.517 - [DEBUG] ## GAEProxy set keep_running: True
Sep 16 13:58:19.517 - [INFO] ------------------------------------------------------
Sep 16 13:58:19.517 - [INFO] Python Version     : 2.7.13
Sep 16 13:58:19.517 - [INFO] OS                 : Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:272; ProductType:0
Sep 16 13:58:19.517 - [INFO] Listen Address     : 127.0.0.1:8087
Sep 16 13:58:19.517 - [INFO] GAE APPID          :
Sep 16 13:58:19.517 - [INFO] Pac Server         : http://127.0.0.1:8086/proxy.pac
Sep 16 13:58:19.517 - [INFO] ------------------------------------------------------

现在：

Sep 16 14:22:36.779 - [WARNING] no enough ip
Sep 16 14:22:37.295 - [WARNING] no enough ip
Sep 16 14:22:37.811 - [WARNING] no enough ip

**Comment by SeaHOH** [comment]
各地区情况不同

**Comment by phuslu** [comment]
请勿 FUD

**Comment by wukent** [comment]
是，就几个gvs还可以用，不到十个。

**Comment by wukent** [comment]
@MeABc   慢慢来找，还是host方便。

**Comment by MeABc** [comment]
hosts 维护麻烦啊。。。但你用别人搞好的当然简单。。

**Comment by dou4cc** [comment]
@wukent 试试[dnsproxy+gogo+goproxy](https://raw.githubusercontent.com/dou4cc/resource/master/fq.7z.zip)：
![image](https://user-images.githubusercontent.com/7764678/30510279-bce51cd8-9af3-11e7-86e2-51b93f05a52d.png)
