### ISSUE TITLE
有没有人能共享下gae.user.json，把你的ID删除，我填上自己的，好难弄，看完教程还是红字

### ISSUE THREAD

**Issue by miss747** [phuslu/goproxy#2038]
有没有人能共享下gae.user.json，把你的ID删除，我填上自己的，好难弄，看完教程还是红字。部署和上传都没问题，现在就是这个东西有问题，导致红字，不懂事什么原因。。。。

**Comment by qwerttaa** [comment]
`{
	"AppIDs": [
	],
	"CustomDomains": [
	],
	"Password": "",
	"SSLVerify": true,
	"DisableIPv6": false,
	"ForceIPv6": false,
	"DisableHTTP2": true,
	"ForceHTTP2": false,
	"EnableQuic": true,
	"EnableDeadProbe": true,
	"EnableRemoteDNS": false,
	"HostMap" : {
		"google_hk": [	
		],
		"google_cn": [
			"www.g.cn",
			"www.google.cn",
		]
	},
	"SiteToAlias": {
		"*.doubleclick.net": "google_cn",
		"*.google-analytics.com": "google_cn",
		"*.google.cn": "google_cn",
		"*.googlesyndication.com": "google_cn",
		"*.googletagmanager.com": "google_cn",
		"*.googletagservices.com": "google_cn",
		"csi.gstatic.com": "google_cn",
		"fonts.gstatic.com": "google_cn",
		"dl.google.com": "google_cn",
		"fonts.googleapis.com": "google_cn",
		"*.appspot.com": "google_hk",
		"*.ggpht.com": "google_hk",
		"*.google.com": "google_hk",
		"*.google.co.jp": "google_hk",
		"*.google.co.kr": "google_hk",
		"*.google.co.uk": "google_hk",
		"*.google.com.hk": "google_hk",
		"*.google.com.sg": "google_hk",
		"*.google.com.tw": "google_hk",
		"*.googleapis.com": "google_hk",
		"*.googlecode.com": "google_hk",
		"*.googlegroups.com": "google_hk",
		"*.googleusercontent.com": "google_hk",
		"*.gstatic.com": "google_hk",
		"*.ytimg.com": "google_hk",
		"upload.youtube.com": "google_hk",
		// "*.youtube.com": "google_hk",
	},
	"ForceGAE": [
		// "*.drive.google.com",
		"appengine.google.com",
		"books.google.com",
		"business.google.com",
		"clients1.google.com",
		"clients2.google.com",
		"clients3.google.com",
		"clients4.google.com",
		"domains.google.com",
		"plus.google.com/$",
		"tools.google.com",
		"www.google.com/maps",
		"www.google.com/patents",
		"youtube.googleapis.com",
	],
	"ForceBrotli": [
	],
	"TLSConfig": {
		"Version": "TLSv1.2",
		"ClientSessionCacheSize": 1024,
		"Ciphers": [
			"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
			"TLS_RSA_WITH_AES_128_CBC_SHA256",
			"TLS_RSA_WITH_AES_256_CBC_SHA256",
			"TLS_RSA_WITH_3DES_EDE_CBC_SHA",
		],
		"ServerName": [
			"download.windowsupdate.com",
			"www.apple.com",
			"www.bing.com",
			"www.microsoft.com",
			// "googleads.g.doubleclick.net",
			// "pubads.g.doubleclick.net",
			// "www.google-analytics.com",
			// "ad.doubleclick.net",
			// "appleid.apple.com",
			// "hkg12s09-in-f14.1e100.net",
			// "hkg12s09-in-f17.1e100.net",
			// "hkg12s09-in-f3.1e100.net",
			// "hkg12s09-in-f4.1e100.net",
		],
	},
	"GoogleG2PKP": "7HIpactkIAq2Y49orFOOQKurWxmmSFZhBCoQYcRhJ3Y=",
	"GoogleG3PKP": "f8NnEFZxQ4ExFOhSN7EiFWtiudZQVD2oY60uauV/n78=",
	"FakeOptions": {
		"*": [
			"Access-Control-Allow-Credentials: true",
			"Access-Control-Allow-Headers: Accept, Authorization, Content-Type, If-Modified-Since",
			"Access-Control-Allow-Methods: GET, POST, HEAD, PUT, DELETE, OPTIONS, PATCH",
			"Access-Control-Allow-Origin: *",
			"Access-Control-Expose-Headers: Cache-Control, Content-Encoding, Content-Length, Content-Type, Date, Expires, Server, Vary, X-Google-GFE-Backend-Request-Cost, X-FB-Debug, X-Loader-Length",
			"Access-Control-Max-Age: 1728000",
			"Status: 200",
			"Vary: Origin",
			"Vary: X-Origin",
		],
	},
	"DNSServers": [
		"114.114.114.114",
		"114.114.115.115",
		"8.8.4.4",
		"8.8.8.8",
		"2001:4860:4860::8844",
		"2001:4860:4860::8888",
		"2001:470:20::2",
	],
	"IPBlackList": [
		"159.106.121.75",
		"203.98.7.65",
		"243.185.187.39",
		"37.61.54.158",
		"59.24.3.173",
		"46.82.174.68",
		"78.16.49.15",
		"8.7.198.45",
		"93.46.8.89",
	],
	"Transport": {
		"Dialer": {
			"DNSCacheExpiry": 864000,
			"DNSCacheSize": 8192,
			"SocketReadBuffer": 0,
			"DualStack": false,
			"KeepAlive": 5,
			"Level": 24,
			"Timeout": 5,
		},
		"Proxy": {
			"Enabled": false,
			"URL": "socks5://127.0.0.1:1080",
		},
		"DisableKeepAlives": false,
		"IdleConnTimeout": 5,
		"MaxIdleConnsPerHost": 32,
		"ResponseHeaderTimeout": 16,
		"RetryDelay": 0.5,
		"RetryTimes": 3,
	}
}
`

**Comment by dou4cc** [comment]
@qwerttaa 部署都没问题，红字应该是干扰。

@miss747 现在干扰很猛，gop已经不能单用了，我的配置（tutorial.txt是教程）：https://raw.githubusercontent.com/dou4cc/resource/master/fq.7z.zip

**Comment by qwerttaa** [comment]
我这里北京鹏博士，北京联通，都还可以哈哈

**Comment by phuslu** [comment]
(如果您是遇到本软件使用问题而并不清楚具体原因的话，请尽量提供更多信息，如软件版本，日志截图，地级运营商信息等。否则问题可能会被忽略或关闭)

推测是 IP 问题。

**Comment by dou4cc** [comment]
@qwerttaa 鹏博士据说只要连非鹏博士的统一限速5Mbps，无关套餐，是真的吗？

**Comment by qwerttaa** [comment]
不会，至少我单位这儿用着好好儿的，没这回事儿

http://www.speedtest.net/my-result/6633170611

**Comment by dou4cc** [comment]
@qwerttaa 个人宽带和非个人宽带完全是两回事，你以后反映情况可得写清楚了！

**Comment by miss747** [comment]
@qwerttaa非常感谢，我看看哈，之前没有截图，GAE几年前用过，Google ID 部署啥的还记得，GAE设置感觉也没有这么复杂，现在可能封锁太严重了。。。

**Comment by phuslu** [comment]
我个人主页上有个 gae.user.json， 你看下 https://phuslu.github.io/

待会自删。
