### ISSUE TITLE
非gp相关，纯提醒：CCleaner v5.33.6162 / 32被植入？

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#2039]
> 据悉，黑客入侵后在CCleaner v5.33.6162、CCleaner Cloud v1.07.3191两个版本的软件中植入了远程管理工具，会在用户后台偷偷连接未授权网页，下载其他软件。

http://news.pconline.com.cn/998/9982565.html
https://www.howtogeek.com/326742/ccleaner-was-hacked-what-you-need-to-know/              【竟然建议重做系统……真是tmd……】

具体啥情况不知道……
目前CCleaner已经属于Avast旗下，也没见作出特别说明，给出专门工具

**Comment by MeABc** [comment]
还有这姿势。。。

**Comment by dou4cc** [comment]
@MeABc 你不是关注我推特了吗？

**Comment by MeABc** [comment]
我 N 年不上一次那货。。。 :trollface:

**Comment by blob2015** [comment]
是啊，俺也是据说的“1/200万”、将近“1/300万”分之一 😀 
不是每个版本都升，但那个版本刚好升了，这运气，真是 😀

**Comment by dou4cc** [comment]
@blob2015 V2EX有分析认为是政府行为，你需要做的可能不止重装系统那么简单。

**Comment by phuslu** [comment]
差点中招，还好上次没更新.

**Comment by blob2015** [comment]
@dou4cc 
给个链接呗
重装系统都不想，上面没啥东西，网购都手机了，翻q主要也是g家，也就偶尔围观下谁，下载啪啪啪.avi的数量也不多

**Comment by dou4cc** [comment]
@blob2015 https://archive.is/HAF2K#selection-441.37-441.49

**Comment by MeABc** [comment]
我也用这家伙，吓得我赶紧看我的版本号。。。还好！

**Comment by SeaHOH** [comment]
几年没更过，偶尔用一下。Win7...

**Comment by qwerttaa** [comment]
我一直x64版本。。。万幸

**Comment by blob2015** [comment]
在有更加详细的信息出来前，也不用太过担心？当然，如果有人做个扎实的分析，提出些可行的建议，自然更加好，但360之流的就算了。不过数字那次危机都写软文推销自己。
真要搜集信息，360、迅雷、QQ、微信、搜狗输入法、各种壳浏览器，那个都更加给力。
小白瞎想，估计搜集信息是第一步，然后筛选“高价值”目标。
就那样吧。

**Comment by fredericky123** [comment]
5.33.6161 不过是64位 不知道有没有影响 赶快升级，，，

**Comment by fuckGFW2015** [comment]
马上看了一下版本号，显示5.26.5937，庆幸啊。不过话说回来，这货不是杀毒软件，根本用不着频繁升级！

**Comment by sishentibu** [comment]
正好是。。。赶紧升下

**Comment by darkwolf99** [comment]
一直用dim++的路过

**Comment by 1688pc** [comment]
@qwerttaa 是的就86，但是64安装后有86和64两个exe，不过快捷方式创建的是64，所以86一般不会被启动，除非手贱到主程序文件夹里点86的exe。

**Comment by qwerttaa** [comment]
我一直用国内整合规则的xx绿色版，从来都没点过32位的嘿

**Comment by dou4cc** [comment]
@blob2015 [CCleaner投毒者似乎来自中国](https://archive.is/IZc6k)
