### ISSUE TITLE
社长，这是什么个情况呀？

### ISSUE THREAD

**Issue by Asteroids89** [phuslu/goproxy#2048]
上传服务端：
![1](https://user-images.githubusercontent.com/19388220/30674984-5f0f2f8e-9eb0-11e7-9877-30090e15ee60.png)
客户端日志：
![2](https://user-images.githubusercontent.com/19388220/30675001-806498b8-9eb0-11e7-8bb4-698664f85496.png)
查询部署appid：
![3](https://user-images.githubusercontent.com/19388220/30675016-95801b78-9eb0-11e7-9f26-791ad3cd894c.png)

**Comment by MeABc** [comment]
你用 goproxy 来上传服务端？现在 gae 不稳定，换代理上传。

**Comment by Asteroids89** [comment]
一直都是用的goproxy上传服务端的，这种情况今天还是第一次出现

**Comment by MeABc** [comment]
要不你换用 tls 来试下。服务端没有部署成功，这个只能多试几遍了。

**Comment by Asteroids89** [comment]
try again

**Comment by sypopo** [comment]
可不可以在centos 系统中上传，如果可以用国外VPS上传那不是很快。

**Comment by caofengzi** [comment]
重啟gop重新上傳。

**Comment by Asteroids89** [comment]
重启N次，仍失败，今天的干扰这么强？

**Comment by phuslu** [comment]
额，放到 vps 上传播

**Comment by masktao** [comment]
现在多线程上传比以前单线程恐怖多了,

**Comment by jap33** [comment]
上传服务端出现登陆错误，但邮箱又能打开





![default](https://user-images.githubusercontent.com/15140842/30678311-dcfdabb0-9ec3-11e7-9999-3fb80245f8f1.PNG)

**Comment by jap33** [comment]
服务端代理设置在什么地方呢找不到。

**Comment by jyuan15** [comment]
昨天上传r101也用的gop，期间某个appid失败两次，但最后还是成功了。

![2017-09-21_123805](https://user-images.githubusercontent.com/12642186/30679123-c5255ee2-9ec9-11e7-9c78-1a4e63e3b159.jpg)

**Comment by caofengzi** [comment]
這是上傳成功了。

**Comment by blob2015** [comment]
服务端上传，效率已经大幅提高了，今天刚升了一次，比较顺利，用的quic

**Comment by jap33** [comment]
现在白天两端最新用起来非常顺利，就看月黑风高的时候怎样了。不过俺还是想知道服务端代理设置在什么地方呢？谁能指点一下！

**Comment by Asteroids89** [comment]
今天开着goproxy上传了不下30次，服务端死活传不上去。想开着Lantern，临时上传下，不知各位高人知道怎么用Lantern上传goproxy的服务端？

**Comment by dou4cc** [comment]
命令详解
　　（以下命令需要管理员身份才能执行）
　　添加端口转发的命令
netsh interface portproxy add v4tov4 listenport=新开的监听端口 listenaddress=新开端口的绑定地址 connectaddress=要转发的地址 connectport=要转发的端口 protocol=tcp

　　删除端口转发的命令
netsh interface portproxy delete v4tov4 listenport=新开的监听端口 listenaddress=新开端口的绑定地址

　　命令举例
　　比方说，俺本地已经运行了 TOR，端口是 8118，绑定在 127.0.0.1
　　如果俺希望建立一个新的端口，端口号是 12345（这个端口号是俺随手编的，你也可以用其它端口号），绑定在 0.0.0.0 上，那么就执行如下命令。然后，发往 12345 端口的数据流就会被转发到 8118 端口。
netsh interface portproxy add v4tov4 listenport=12345 listenaddress=0.0.0.0 connectaddress=127.0.0.1 connectport=8118 protocol=tcp

　　为了保险起见，再用前面介绍的 netstat 命令，看一下本机开启的端口。如果正常的话，你就可以看到如下一行
TCP  0.0.0.0:12345  0.0.0.0:0  LISTENING

　　如果要删除该端口转发，就执行如下命令
netsh interface portproxy delete v4tov4 listenport=12345 listenaddress=0.0.0.0
　　删除之后，再用 netstat 命令查一下，这个 12345 的监听端口就看不到了

**Comment by dou4cc** [comment]
@Asteroids89 少用蓝灯：
- https://twitter.com/dou4cc/status/910028205465141248
- https://twitter.com/dou4cc/status/909611057991348224

**Comment by jap33** [comment]
俺直接把ss改成88087就好了。

**Comment by MeABc** [comment]
如楼上，变通一下， 把 `uploader.py` 里面的代理端口改成目标代理所用的端正。

**Comment by jap33** [comment]
知道了原来代理端口就在眼前uploader.py中。

**Comment by Asteroids89** [comment]
把里面的HTTP端口全部替换就可以了么？

**Comment by MeABc** [comment]
可以的。

**Comment by dou4cc** [comment]
@Asteroids89 https://github.com/phuslu/goproxy/issues/2048#issuecomment-331066805
按如上方法搞一个端口转发比改脚本省事。

**Comment by jyuan15** [comment]
不知怎么回事，现在不能用uploader.bat上传了，闪退，只能用uploader.py上传。

**Comment by MeABc** [comment]
> 不知怎么回事，现在不能用uploader.bat上传了，

你用 windows 10 ？

**Comment by MeABc** [comment]
> 按如上方法搞一个端口转发比改脚本省事。

改几个数字不比敲一行字母简单？还有，这个还要管理员权限，还要改回来。。。吧啦吧啦一大堆。。

**Comment by jyuan15** [comment]
@MeABc xp和win7，都要闪退

**Comment by MeABc** [comment]
> `xp和win7，都要闪退` 

xp 和 win7 不清楚，但 win10 最新的 1703 起，cmd 环境已废，有一大堆问题，改用（学）powershell 。

**Comment by Asteroids89** [comment]
@dou4cc ,谢谢，一会我这个小白研究下

**Comment by Asteroids89** [comment]
修改uploader.py的端口，用蓝灯临时上传服务端，搞定！
