### ISSUE TITLE
非gop相关，19大最新消息

### ISSUE THREAD

**Issue by hyperdoit** [phuslu/goproxy#2053]
来自药丸时报
据消息人士透露，封网属于内部术语，即在重大社会事件期间封禁所有非必要对网络的操作，防止操作导致崩溃影响上网，称为封网。

就给大家报个平安，不要造成恐慌。
是直接断开，不是加高墙喔
#2017好消息不断
#这盛世如你所愿
我们从另一个渠道获得的消息说19大时期会封网。
据某ISP员工透露，源地址白名单已上线。哪天有目标地址白名单也不奇怪了。

**Comment by fuckGFW2015** [comment]
反正无法吐槽，未来可能更多人上街，直接断网绝不是一件好事

**Comment by carotin** [comment]
自信都去那儿了？

**Comment by socafield1993** [comment]
到底走北朝鲜还是新加坡模式啊？若前者，无法接受！

**Comment by phuslu** [comment]
这个“封网”不是只封锁外网，只是暂停一些网络操作,比如割切，升级等。
