### ISSUE TITLE
Windows amd64 1618 版本被 MSE（Windows Defender）报毒了

### ISSUE THREAD

**Issue by hyxxsfwy** [phuslu/goproxy#2054]
如题，下载后就被清理了，1617 都没有问题，这是什么情况？

**Comment by 1688pc** [comment]
多大点事，排除一下就可以，经常被卡巴斯基报毒的路过。

**Comment by fei5seven** [comment]
讲道理，卡巴还真的很少报毒，WD报毒在正常不过了，而且该杀的不杀，不该的乱杀

**Comment by dou4cc** [comment]
gop的.7z有“不明”文件头，被报很正常

**Comment by 1688pc** [comment]
@fei5seven goproxy_windows_amd64-r1620.7z压缩包卡巴报毒，解压后7z重新压制不报毒。

**Comment by fei5seven** [comment]
64位我还真没去试过，我都是用32的

**Comment by fei5seven** [comment]
好吧，真的，这个版本卡巴也报，然而报毒并不能说明什么【摊手】

**Comment by fei5seven** [comment]
![1](https://user-images.githubusercontent.com/12988636/30779230-93058a1c-a11d-11e7-939b-68589695cf1b.jpg)
这个报毒方式。。。是云启发吧，没啥卵用，大概是打包方式的问题？胡乱猜测，溜

**Comment by yfdyh000** [comment]
打包是7z 命令行自解压包。
