### ISSUE TITLE
社长的内存占用有点猛

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#2056]
![image](https://user-images.githubusercontent.com/7764678/30769551-bea01f6e-a04d-11e7-9eb0-b4b2a5f244ef.png)
我只是把x大那边的20w+ip导进来、把level调到80、把dnsproxy接到gop上（一脸无辜

**Comment by SeaHOH** [comment]
启动时是多少？运行了多长时间？

**Comment by dou4cc** [comment]
上图就是刚启动时的样子：good_addrs还没几个就接到dnsproxy的一堆请求，只好返回错误，然后dnsproxy再不停地重试，内存就涨成这个样子了。
稳定之后如下：
![image](https://user-images.githubusercontent.com/7764678/30769881-a9cda000-a054-11e7-8809-42f858046598.png)

**Comment by MeABc** [comment]
goproxy 能用在 dnsproxy 上吗？

**Comment by dou4cc** [comment]
@MeABc DNS-over-HTTPS

**Comment by phuslu** [comment]
这个可以优化一下，把字符串的 ip 转成 `[4]byte`， 就可以减少三分之二的内存占用了。

不过需要对 ipv6 特殊处理，我琢磨下值不值做。

**Comment by SeaHOH** [comment]
不过启动时是怎么回事，那么大。

**Comment by phuslu** [comment]
刚启动时候 dnsproxy 重试太多 加上 level =80 导致的。

**Comment by phuslu** [comment]
我担心如果是家用路由器的话，100 块左右的，估计撑不住。

**Comment by dou4cc** [comment]
@phuslu 我倒是觉得gop不适合跑在路由器了，毕竟gaeproxy全是dirty hack，跑在路由器里高透明代理的应该是一些比较稳定的梯子。还有，让路由器做中间人会加大风险，毕竟路由器维护难度大，比电脑更招黑。

**Comment by MeABc** [comment]
能把 "level调到80" 的我都崇拜。。

**Comment by SeaHOH** [comment]
@phuslu 好像是 `json` 的锅，感觉 IP 配置可以独立出来。

**Comment by phuslu** [comment]
@dou4cc 我的意思是你在 PC 上这么用的话，路由器会先挂掉。。。所谓的并发过大导致“断流”

**Comment by phuslu** [comment]
@SeaHOH 不是。

**Comment by dou4cc** [comment]
@phuslu 我的建议是gop在good_addr很少控制一下并发，别来一个请求就发一个请求，排个队，然后队伍长度搞个上线，被踢出去的请求直接返回错误。
额，家里10年前的路由器确实死机好多次了，我现在是直接电脑pppoe，话说我家另一个住处的今年刚买的路由器刚好能承受这么多连接。

**Comment by SeaHOH** [comment]
控制端口监听队列就行

**Comment by phuslu** [comment]
考虑过，不合适。被动扫描+尽可能链接复用，这种方式下实现所谓“单程”(singleflight) 有两个缺点。
1. 干扰大的时候等待时间长，波动大。
2. 即使干扰不大，速度也不太稳

**Comment by MeABc** [comment]
只接丢 20w+ip 在 goproxy 里这种简直是特例。呃，就算调到 80 这种能正常用，但是要过一遍要多少时间，还不如用扫描工具扫一遍 IP 段“合算”。

**Comment by MeABc** [comment]
> 干扰大的时候等待时间长，波动大。 

+1

**Comment by dou4cc** [comment]
@phuslu 被动开太多连接会引来更强的干扰，控制并发说不准能改善。不过不是大问题，买个16g内存电脑一点也不卡

**Comment by phuslu** [comment]
@dou4cc 寄希望用链接复用了，我一直觉得这块做得还不错。大多数时间并没有所谓并发，可以用监控软件看下。

**Comment by MeABc** [comment]
> 买个16g内存电脑一点也不卡

你这话说得真轻松。。。

**Comment by SeaHOH** [comment]
16G 用了6 年了……

**Comment by masktao** [comment]
32g,表示没有压力
![image](https://user-images.githubusercontent.com/13614353/30770225-8786ec46-a05d-11e7-8474-136c04c19401.png)

**Comment by dou4cc** [comment]
@masktao 我16g是笔记本
。。。来来来，去卡吧我们秀个够！
