### ISSUE TITLE
关于ip.html的建议

### ISSUE THREAD

**Issue by xiaomage2000** [phuslu/goproxy#2063]
现在的ip.html只支持将原来的ip覆写为要导入的新ip。在扫到可用新ip后，若想要保留原有的ip，不能快捷的直接将这些新ip导入。建议加入一个按钮，能将新扫到的ip直接加在原来的ip后面，节省时间。希望社长采纳，谢谢社长！

**Comment by kirbyzhu** [comment]
稍微多动一步就行了 
先把原来的放进ip.html
然后再把新的放进来 没必要再搞个按钮吧

**Comment by 94oiio** [comment]
@kirbyzhu  很多东西都可以手动操作，但是一个按钮能解决的事不是更方便快捷么，毕竟懒是人类进步的真正动力，当然如果实现起来太麻烦就另说了

**Comment by e2889e** [comment]
实现很简单...

**Comment by inkdie** [comment]
嗯，页面里面加一个选项，覆盖或增加。有了很方便，没有也能用，属于锦上添花的

**Comment by dou4cc** [comment]
这功能实现起来没有成就感，直接改json又很方便，就拖到现在了。

**Comment by xiaomage2000** [comment]
@kirbyzhu 在手机上操作不是很方便，电脑还好。但这样可以提高效率。

**Comment by kirbyzhu** [comment]
哦哦 这么多人在手机上用啊

**Comment by cnrip** [comment]
一直都是手动添加
