### ISSUE TITLE
【VIP 福利】gae-meek-heroku （socks5）

### ISSUE THREAD

**Issue by MeABc** [phuslu/goproxy#2064]
前言：这不是什么新技术，我只是搬运工。
说明：如果你看不懂，说明你还不是本社充值会员 :) 这是 VIP 用户福利。。。。

相关链接：
https://trac.torproject.org/projects/tor/wiki/doc/meek
https://scutlaoyi.github.io/webTool005-speed-up-network-by-gae.html

python
https://github.com/yinghuocho/meeksocks-py
https://github.com/yinghuocho/gsocks

golang
https://git.torproject.org/pluggable-transports/meek.git

--

已测试和验证可用。

heroku 服务端要自己部署。

--
计划：
1. 整合到 goproxy 服务端。（已完成。目的：一个帐号多用。）
2. 用 golang 改写。（目标：整合到 goproxy ，如果搞不定就独立出来（客户端独立）。。。）
（第二点参考：https://github.com/yinghuocho/firefly-proxy ）
3. 整合到  goproxy-vps 。

然后就没有然后了。。。

**Comment by qwerttaa** [comment]
速度咋样？

**Comment by MeABc** [comment]
还没有进行所谓的测速。这个速度上依赖 gae 。我只是进行“可行性”测试。

**Comment by 94oiio** [comment]
看不懂，先mark

**Comment by fei5seven** [comment]
先围观，目前配合主任的修改大法QUIC用的很舒服，等后续的故事。_(:з」∠)_

**Comment by wz7465** [comment]
感觉现在速度没啥优势，早两年，这个办法不错

**Comment by hcym** [comment]
不太懂，老老实实还是ip加quic
heroku不用混淆吧，非高峰满满当当
高峰时段用gce，还行

**Comment by MeABc** [comment]
@wz7465 需求第一，速度第二。如果 gae 速度不错的话，这个应该不会太差。
@hcym 这不是混淆，你可以把这个理解成是 xx-net 的 X-Tunnel ，还是就是 `Firefly 萤火虫` 。顶楼第二个链接说明了这个需求。

**Comment by MeABc** [comment]
gae 的痛点的什么，socks！这个就是解决这个的。

**Comment by MeABc** [comment]
我现在感兴趣的是这种技术（meek），配合 https://github.com/phuslu/goproxy/issues/2030 就可能有 N 种玩法来实现我的需求。

**Comment by wz7465** [comment]
gae现在干扰厉害，gop是社长做了很多优化的，改善了http连接性能，单靠meek的自身连接性能，恐怕难以胜任。但就socks而言，只部署在heroku，绑个域名，cloudflare加速，速度不比之差

**Comment by MeABc** [comment]
@wz7465 

> gae现在干扰厉害

gae 我这速度不错的。

> 但就socks而言，只部署在heroku，绑个域名，cloudflare加速，速度不比之差

嗯。这里是改成 gae 加速了，且不用绑域名。
这里只是多个选择而已，不是比谁“历害”：如，gae 被封，用 cloudflare 加速；cloudflare 被封，用 gae 加速。 #2030

**Comment by e2889e** [comment]
我一年多前想到过了类似的方法.

但是,这么搞,如果再用洋葱,那速度...

**Comment by kirbyzhu** [comment]
@hcym 我前面部署了一个gce的SSR，手机用的，突然ip被封。只好换个地区重新整了一个。

**Comment by hcym** [comment]
@kirbyzhu
我部署的两个都断过，换区也不行，正好是重灾时期，只能用6to4的gop苟活
现在又好了有两个月没动
