### ISSUE TITLE
今天quic模式不能用了，改为false可以用

### ISSUE THREAD

**Issue by doracl** [phuslu/goproxy#2065]
1、帝都电信
2、windows 10 r1620
3、很多IP，还有一部分是刚刚用quic-scan扫出来的
4、禁用quic 后就可以用了。。。

**Comment by phuslu** [comment]
是的，我之前也观测到，似乎 TLS 和 Quic 是跷跷板的关系。

请到 https://github.com/phuslu/goproxy/issues/2026 反馈。

**Comment by dou4cc** [comment]
@doracl 扫完ip要重新拨号。我这边不管怎么跷跷板，quic一直能用（虽然有时很卡），tls就不好说了。

@phuslu 一天半不见，你还活着，真好。

**Comment by doracl** [comment]
@dou4cc 公司网，不能重新拨号。。。
