### ISSUE TITLE
quic直连google时能否不搞中间人？

### ISSUE THREAD

**Issue by dou4cc** [phuslu/goproxy#2067]
毕竟gfw还不能识别quic中的证书，servername无需和host不一致。@phuslu

**Comment by phuslu** [comment]
不会做。之前在 goagent TLS 实现过，不过最后取消了。 
1. 不能重复复用
2. 速度下降(因为筛选不够）
3. 抗干扰不够

这三个缺点其实是纠缠在一起的，所以为了效率不会做这样的"优化"。
