### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#21]
```
e:\Backup\go\src\github.com\phuslu\goproxy\goproxy>go build
can't load package: E:\Backup\go\src\github.com\phuslu\goproxy\goproxy\main.go:19:2: local import "../httpproxy" in non-local package
```

这个跟 #3 的问题一样，查了一下，用go build main.go以后不报错了。
http://stackoverflow.com/questions/10687627
但又出现了下面的错误，如何解决？貌似要修改代码？
http://stackoverflow.com/questions/24767707

```
e:\Backup\go\src\github.com\phuslu\goproxy\goproxy>go build main.go
# _/e_/Backup/go/src/github.com/phuslu/goproxy/httpproxy
..\httpproxy\handler.go:9: can't find import: "github.com/golang/glog"
# _/e_/Backup/go/src/github.com/phuslu/goproxy/httpproxy/filters/auth
..\httpproxy\filters\auth\auth.go:12: can't find import: "github.com/cloudflare/golibs/lrucache"
```

**Comment by phuslu** [comment]
在月底之前，我会完成文档的工作，详细描述如何编译。

第二个错误需要你执行
```
go get github.com/XXXX
```

**Comment by CNMan** [comment]
go get github.com/phuslu/http2
go get github.com/miekg/dns
go get github.com/juju/ratelimit
go get github.com/golang/groupcache
go get github.com/golang/glog
go get github.com/cloudflare/golibs/lrucache
都已经go get了

**Comment by phuslu** [comment]
那把 goproxy 文件夹弄到 GOPATH 以外的目录，然后在 goproxy/goproxy 目录下执行 go build -v
成功后就再这个目录直接运行 goproxy.exe 试下？

**Comment by CNMan** [comment]
```
d:\Downloads\goproxy-master\goproxy>go build -v
_/d_/Downloads/goproxy-master/httpproxy/filters
_/d_/Downloads/goproxy-master/storage
golang.org/x/net/publicsuffix
_/d_/Downloads/goproxy-master/httpproxy
_/d_/Downloads/goproxy-master/httpproxy/filters/auth
_/d_/Downloads/goproxy-master/httpproxy/filters/autoproxy
_/d_/Downloads/goproxy-master/httpproxy/filters/direct
_/d_/Downloads/goproxy-master/httpproxy/filters/gae
_/d_/Downloads/goproxy-master/httpproxy/filters/iplist
_/d_/Downloads/goproxy-master/httpproxy/filters/php
_/d_/Downloads/goproxy-master/httpproxy/filters/stripssl
_/d_/Downloads/goproxy-master/goproxy
```

可以了，谢谢！

**Comment by phuslu** [comment]
其实应该先用 https://godoc.org/github.com/cloudflare/go 编译出 go 环境，然后再用这个 go 环境编译 goproxy.

原因请见 https://blog.cloudflare.com/go-crypto-bridging-the-performance-gap/

**Comment by CNMan** [comment]
Go 1.5 编译器和运行时去C以后不知道效率有没有提升？
https://tip.golang.org/doc/go1.5

**Comment by phuslu** [comment]
应该会有。 但是 cloudflare 的这些 patch 还是必须要移植到 go 1.5 才行。 否则 https 的性能是无法接受的。

**Comment by CNMan** [comment]
```
------------------------------------------------------
GoProxy Version    : @VERSION@ (go/go1.5beta1 windows/amd64)
Listen Address     : 127.0.0.1:8000
RoundTrip Filters  : autoproxy,auth,gae,php,direct
Pac Server         : http://127.0.0.1:8000/proxy.pac
------------------------------------------------------
```

自己编译的话版本号获取不到:(

**Comment by phuslu** [comment]
恩，需要执行 make 以后再 build 目录下的才会有版本信息。

**Comment by johnsonz** [comment]
用了pluslu的 go build -v方法我这也是不成功。

D:\goproxy\goproxy>go build -v
main.go:21:2: local import "./filters" in non-local package
main.go:23:2: local import "../../../storage" in non-local package
main.go:24:2: local import "../../../httpproxy" in non-local package
main.go:25:2: local import "../../../httpproxy" in non-local package
main.go:26:2: local import "../../../httpproxy" in non-local package
main.go:27:2: local import "../../../httpproxy" in non-local package
main.go:28:2: local import "../../../httpproxy" in non-local package
main.go:29:2: local import "../../../httpproxy" in non-local package

D:\goproxy\goproxy>go env
set GOARCH=amd64
set GOBIN=
set GOCHAR=6
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Go\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

D:\goproxy\goproxy>go version
go version go1.4.2 windows/amd64

苦于没linux系统，虚拟的ubuntu跑不起来啊，电脑配置跟不上啊

**Comment by CNMan** [comment]
@johnsonz 
D:\goproxy\goproxy>go get -u
D:\goproxy\goproxy>go build -v

**Comment by johnsonz** [comment]
@CNMan 

D:\goproxy\goproxy>go get -u
package _/D_/goproxy/goproxy: unrecognized import path "_/D_/goproxy/goproxy"

是不是我们的环境不一样
