### ISSUE TITLE
2015年中秋反审查软件盘点 十全大补丸

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#212]
del

更新

**Comment by yeahwu** [comment]
几千万？呵呵

**Comment by aOJzQT** [comment]
中秋大合集，不收月饼只收软体

**Comment by BigJiJi** [comment]
而昂而昂

**Comment by somebird** [comment]
又见jasonli兄，老朋友问好！

**Comment by somebird** [comment]
不知道红蛙兄，warmingf兄在哪

**Comment by aOJzQT** [comment]
@somebird 前一阵子看到红蛙大大在这儿发过言

**Comment by BigJiJi** [comment]
楼上的孙子，通过15天的教育，你的红蛙大爷虽然端不成党给的饭碗了，但再也不会骂党了。他正积极努力改造自己扭曲的人生观和价值观。

**Comment by xxnet** [comment]
各位活跃的贡献者，大家要保护好自己的匿名。

红蛙兄似乎被定位了，如果不知道怎么匿名，可以去看看编程随想的博客，里面有防止跨省

在 2015年9月23日 上午12:02，BigJiJi <notifications@github.com>写道：

**Comment by BigJiJi** [comment]
楼上的简直不入流，咀嚼phuslu的排泄物还津津有味，还有脸叫别人给你的xx内蹄捐款，你倒是自己开发一个啊，你这种人属于投机分子，见人说人话见鬼说鬼话，只要有利可图，你把你老娘卖了都有可能，你在你的杂交xxnet安个后门，把使用者的信息卖给感兴趣的组织和人也是可能的，因为你没本事，phuslu不会这么干是因为它不需要靠这个赚钱，他还要顾及自己的名头，你个不入流的角色那就不一定了

**Comment by breakwa11** [comment]
摊手
