### ISSUE TITLE
今天惊奇发现SS更新了

### ISSUE THREAD

**Issue by YoungPix** [phuslu/goproxy#215]
今天SS刚连上，发现SS更新2.5.8版本。心想C大不是不再更了吗？

翻到：https://github.com/shadowsocks/shadowsocks-windows/releases

发现是 @icylogic  更的，希望作者平安。THX Very Much

**Comment by Yamazaki-wu** [comment]
据说早已不是原作者了，只是加入到这个分支而已。

**Comment by alresvor** [comment]
@Yamazaki-wu 这是原版

**Comment by CNMan** [comment]
https://github.com/shadowsocks/shadowsocks-windows/graphs/contributors
是原来的contributors在更新，clowwindy是原创和主要的contributor，但不是唯一的contributor，放心使用吧，开源力量大:)
