### ISSUE TITLE
福利

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#218]

**Comment by goldbergpping** [comment]
very good ,thank you!!

**Comment by hijklmn** [comment]
@CNMan 请问同样用checkip，为什么我这边扫不到你那么多ip？有什么技巧吗？

**Comment by xyuanmu** [comment]
首先谢谢！个人觉得还是分享ip段较好，各地区封锁情况不同，例如柬埔寨咱这里只有115.178.26.4这一个可以用的。

**Comment by ARwMq9b6** [comment]
“[广厦千万间](https://www.youtube.com/watch?v=fKfb3NIIxUA)”！俺这 6 段能用。

果断添加到　ｘｘ－ｎｅｔ　弹药库　https://github.com/XX-net/XX-Net/blob/master/gae_proxy/local/ip_range.txt　。

https://github.com/CNMan/GoogleIPRange/commit/445aa90f17d996b34ea02d84a7effdf18f358e39

https://github.com/CNMan/GoogleIPRange/commits/master

https://github.com/CNMan/GoogleIPRange/tree/master/ip_tmpok

**Comment by zj3** [comment]
1.255.22.0/24这段韩国ip有很多可用

**Comment by jasonliul** [comment]
175.28.1.153 我也只有一个, lz应该是万恶的联通.
电信的鬼子进村更凶残.

**Comment by sundaqing1969** [comment]
@CNMan ，https://goo.gl/mpzLgx这个链接里的东东怎么用？稍微提示一下，感谢！

**Comment by jasonliul** [comment]
216.58.196.192,216.58.196.198,216.58.196.201,216.58.196.202,216.58.196.210,216.58.196.193,216.58.196.218,216.58.196.206,216.58.196.203,216.58.196.205,216.58.196.209,216.58.196.214,216.58.196.222,216.58.196.211,216.58.196.223

添加hosts可用, 不然不稳定

**Comment by CNMan** [comment]
@hijklmn 没啥技巧，多是因为在国外VPS上扫的，还要拿回来在本地二次扫，只是起个精准缩小范围的作用
@xyuanmu 直接IP不更好？IP段的话里面有好多没用的IP，浪费时间
@jasonliul 我是电信，早上更新的那些我这里有近60个可用

**Comment by sundaqing1969** [comment]
楼主不给偶提示，新手我摸索扫你提供的ip段，扫出100左右好ip，谢谢

**Comment by bygloam** [comment]
Thanks

**Comment by jasonliul** [comment]
210.2.185.92|210.2.185.98|210.2.185.79|210.2.185.87|210.2.185.97|210.2.185.115|210.2.185.119|210.2.185.120

**Comment by luffy83** [comment]
谁能够教下我怎么用

**Comment by CNMan** [comment]
@xyuanmu 合并了你的[整合IP段](https://groups.google.com/forum/#!topic/fqlt/l7AJqW6ytgY)，但只保留了在国外VPS上扫描含GOOGLE证书的段

**Comment by xyuanmu** [comment]
@CNMan 谢谢，有VPS就是好，IP范围又可以进一步缩小了。

**Comment by jasonliul** [comment]
@xyuanmu
VPN也是扫描方案, 得到的ip+hosts, 只是ping值不确定.

**Comment by CNMan** [comment]
@xyuanmu 我的VPS配置不高，24小时才能扫描1700万左右IP，效率太低了
最主要是GoogleIP基本都被封了

**Comment by xyuanmu** [comment]
@CNMan 那也相当不错了，咱的破机100线程一天只能扫2百万，开高了CPU热得受不了，现在都是用整理的IP段在xx-net里慢慢扫 :smile: 。

**Comment by jasonliul** [comment]
我还是愚人摸奖, 一次就搞到3个字段, 但是贪心还想再多, 结果后面的基本就是白摸

**Comment by CNMan** [comment]
@jasonliul 目前能用的IP有限，摸奖太困难了...
之前策略失误，一直在VPS扫描5亿+的IP库，每次ip_tmperror.txt到快700MB（4000万）的时候内存就用光了，只能从头来过，累积的IP数量达到了1.5亿左右。。。
最近开始按国别扫描，IP库控制在3500万以下，就不会重复扫描了，估计需要一个月时间才能扫完亚洲地区剩余的IP
IN 37313536
RU 45568384
AU 48609792
KR 112363264
JP 202959616

**Comment by jasonliul** [comment]
208.65.155.50,
103.11.30.0/24,
103.11.28.0/24

**Comment by CNMan** [comment]
@xyuanmu @jasonliul 添加了一大批新的:)

**Comment by xyuanmu** [comment]
@CNMan 谢谢，增加了20W+，辛苦啦

**Comment by jasonliul** [comment]
gws 现在会被自动识别,加入屏蔽.
正好补充hosts, 有劳有劳. :)

**Comment by jasonliul** [comment]
@CNMan 终于新增了ip, 但只有5枚<300ms.
而且全部是小强. :)

**Comment by CNMan** [comment]
这两天会把以前的存货都在VPS上验证一遍公开出来，边验证边增加吧:)

**Comment by jasonliul** [comment]
好呀, 今年朝廷例假基本结束了.

**Comment by CNMan** [comment]
@xyuanmu  @jasonliul  @ARwMq9b6 今年就先更新这么多吧，8369x256个IP在VPS上跑了2遍，应该没有遗漏了
![2015-10-15_195656](https://cloud.githubusercontent.com/assets/8692234/10513023/50d8e70e-7377-11e5-9a7b-5f725df5be95.png)

除了已经公开的近2000个/24段，手上还有近4000个含google证书的/24段，明年有机会再更新吧:)

**Comment by xxnet** [comment]
感谢CNMan，GAE 坚挺到现在，不容易啊

在 2015年10月15日 下午8:02，CNMan <notifications@github.com>写道：

**Comment by CNMan** [comment]
@xxnet 彻底切断估计不太可能，但是速度没优势了
两组从VPS扫描得到的ok IP 117652（95%以上已公开）+82918（10%左右已公开）在本地检测大概能剩2000个，只有1%的存活率而已，情况不容乐观

**Comment by jasonliul** [comment]
@CNMan 5只小强又死了3只.
现在ip模式已经过时, 不过遗老们坚持遛狗, 墙管也懒得理睬.

**Comment by xxnet** [comment]
Never give up!




2015-10-17 0:29 GMT+08:00 Jason Liu <notifications@github.com>:

**Comment by CNMan** [comment]
今天根据最新的VPS扫描结果集中更新一次，添加了nogoogleip.txt相当于个黑名单吧，如果有人能从里面扫到google IP麻烦提交issue或pull request
