### ISSUE TITLE
Windows 下载 checkgoogleip 之后用记事本打开checkip.py之后不能批处理了

### ISSUE THREAD

**Issue by jglimmers** [phuslu/goproxy#219]
\checkgoogleip-master\python27.exe"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
请按任意键继续. . .

求解....

**Comment by hjolin** [comment]
没看懂你要干什么。在windows下安装了python之后，想要扫描ip直接双击checkip.py就好了

**Comment by jglimmers** [comment]
我先用记事本打开了 check.py,然后再双击就是记事本了,不能用python

**Comment by hijklmn** [comment]
@jglimmers 你打开的文件不对，应该是在local文件里的checkipwindows批处理文件。你打开的文件是错的，你的目录是local\checkgoogleip-master,多打开了一个文件夹，不知道你明白不明白？

**Comment by alresvor** [comment]
仔细看看作者的说明
https://github.com/moonshawdo/checkgoogleip#使用方法

**Comment by CNMan** [comment]
要解压到goagent的local目录运行，你就地运行当然不行了

**Comment by jglimmers** [comment]
对的 我是解压到 local 下 但是因为之前用记事本打开过 并且让 .py 文件都是默认记事本打开 所以在gae_proxy/local 下双击 checkip.py 之后会显示
\gae_proxy\local\python27.exe"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
请按任意键继续. . .

**Comment by alresvor** [comment]
>  可以放在把checkip.py与checkip.bat放在goagent/local目录下面

仔细读，你看你是放到了哪里

**Comment by jglimmers** [comment]
@alresvor  可是我用的是 XX-NET，用的是 gae_proxy， 只有gae_proxy文件夹。

**Comment by alresvor** [comment]
这两个又不一样，能乱放吗
下载个 https://github.com/phuslu/pybuild 把 checkgoogleip 的那些文件直接放这里面，运行

**Comment by xyuanmu** [comment]
说白了，checkgoogleip需要python环境，xx-net 的local目录下没有所需的python，如果你有goagent的话，直接复制local目录下的 python27.dll，python27.exe，python27.zip 三个文件到checkgoogleip目录即可，我就是这样的，就不用放在local目录里弄混文件了。

**Comment by jerry011235** [comment]
哈哈，我也是这样干的，就是不知道 python27.dll，python27.exe，python27.zip 这三个文件 在哪里下载啊？
我在 <https://www.python.org/downloads/windows/>没有找到啊？

**Comment by xyuanmu** [comment]
@jerry011235 goagent 里就有，是 phuslu 提取精简的没有单独下载，版本是2.7.8

**Comment by jglimmers** [comment]
@alresvor  谢谢
@xyuanmu  @jerry011235  谢谢.
