### ISSUE TITLE
如果我原来有3000个IP,我导入3000个IP之后系统会不会自动检测IP的有效性?

### ISSUE THREAD

**Issue by jglimmers** [phuslu/goproxy#220]
就是系统自动替换新的3000个ip 还是会根据速度重新从这6000个IP中筛选出速度最快的3000个?

**Comment by CNMan** [comment]
传说xx-net有优选机制，但我没用过
goagent和goproxy都没有优选

**Comment by xyuanmu** [comment]
说的是 xx-net 吧，会自动检测并排序，不过需要些时间。

**Comment by jglimmers** [comment]
谢谢。
