### ISSUE TITLE
checkip 9 revisions不错

### ISSUE THREAD

**Issue by hijklmn** [phuslu/goproxy#221]
发现gwsip和gvsip都在ip_tmpok那个文件里，不需要再在ip_tmpno里面找gvsip了，非常不错。这个软件最大的不方便是格式转换问题，扫出来很多ip，怎么快速自动转换为“----|----|----”格式或jason格式？@cnman

**Comment by hijklmn** [comment]
我总是一个个排版，很麻烦。万能网友有没有好办法？

**Comment by xyuanmu** [comment]
复制下面这串代码到记事本，另存为 bindip.py，然后放到 checkgoogleip 目录，拖动到 python27.exe 上打开即可获取 ip_bind.txt 而且是按照延时排好序的，**int(x[1]) < 6000** 表示获取6000ms以内的ip。

```python
iplist = []
with open('ip_tmpok.txt') as ip_tmpok:
    for x in ip_tmpok:
        sline = x.strip().split(' ')
        iplist.append(sline)
with open('ip_bind.txt', 'w') as ip_bind:
    iplist.sort(key=lambda x: int(x[1]))
    out = '|'.join(x[0] for x in iplist if int(x[1]) < 6000)
    # print(out)
    # print(iplist)
    ip_bind.write(out)
```

或者这个简单代码，这个是不排序的而且获取所有ip，如果扫描完毕 ip_tmpok.txt  里的ip是排好的。
```python
open('ip_bind.txt','w').write('|'.join(x.split(' ')[0] for x in open('ip_tmpok.txt')))
```

**Comment by CNMan** [comment]
@hijklmn 
标题改了吧，checkgoogleip你更新到最新版就是gws和gvs都在ip_tmpok.txt里，跟我没关系
https://github.com/moonshawdo/checkgoogleip/

**Comment by rongwutw** [comment]
xyuanmu, 谢谢你的排序文件,好用.

**Comment by hijklmn** [comment]
@xyuanmu 多谢。我发现多了一个“ip”记事本，上面是直接排好的，以前我一直用“ip_tmpok”来找ip。
