### ISSUE TITLE
用SSH做前置？？

### ISSUE THREAD

**Issue by c21xdx** [phuslu/goproxy#223]
我这几天用SSH翻墙，IP今天用的好好的，第二天起来就被墙了。这种情况2次了。我今天用新的SSH做Goagent的前置代理，翻过去了，但是油管速度明显不如直接SSH翻。用SSH做前置是不是对IP更安全，不容易被墙？？

**Comment by jasonliul** [comment]
没有这一说, ip已经是明牌游戏. 例如103.11.28.0/24
SSH照样定点封杀的, 不过新节点很多直接可用.

如果用前置, 目前最好是免费ssl.更新很快, 不可能完全封杀.
例如
220.255.3.170:80
168.63.24.174:8120
175.209.128.110:3128

**Comment by c21xdx** [comment]
感谢LS的回答，不过我有点不大明白。用SSH的IP做前置使用goagent，这个IP会因为频繁访问google.com而被封吗？goagent不是有加密功能吗？
另外做前置用免费ssl做前置是什么意思啊？ 前置IP加上https?你的例子我看不大明白

**Comment by thundery1** [comment]
难道你的ssh是国产的么??用ssh你都翻出去了,访问谷歌咋能出错了,只有可能是你的ssh收到干扰的缘故

**Comment by jasonliul** [comment]
SSH 现在并不是干扰, 但是夜间会试图过滤破解, 而变得很慢.
FastSSH 已经被盯防, 最好加前置. 其他的免费ssh多半是玩票的.
