### ISSUE TITLE
飞马 Pegasus VPN 1.2.7.0

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#225]
主页
https://pegasusvpn.com/en/

下载
https://pegasusvpn.com/Pegasus-Installer.exe

免安装
http://rghost.net/private/6T46YjxHx/4f5d1a0c51dd3df0ef164eee5c30c7f5

你有旧版 .NET Framework 3.51,删除PegasusVPN.exe.config.
你有新版 .NET Framework 4/4.6, 保留PegasusVPN.exe.config 与主文件在一起

**Comment by hijklmn** [comment]
很快，多谢！

**Comment by xyuanmu** [comment]
这速度真感人，谢谢！

**Comment by sundaqing1969** [comment]
节点连不上

**Comment by sundaqing1969** [comment]
我这里所有节点都连不上

**Comment by jasonliul** [comment]
@xyuanmu, 临时文件目录还有两个. :)
单文件, 没有net framework 3.51,使用新版net 4.6 也可以.

<?xml version="1.0"?>
<configuration>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/></startup>
  <system.net>
    <settings>
      <httpWebRequest useUnsafeHeaderParsing = "true"/>
    </settings>
  </system.net>
</configuration>
保存为PegasusVPN.exe.config, 与主文件放在一起就ok.

**Comment by alresvor** [comment]
速度快的飞起 :rocket:

**Comment by sundaqing1969** [comment]
j大，麻烦搞个教程，行不？

**Comment by xyuanmu** [comment]
@sundaqing1969 
* 首先到官网注册一个帐号。
* 退出其他代理软件，不然有时会登录失败。
* 下载软件运行后，点右下角图标 - Locations - 选择一个服务器，等待连接。
* 接着打开浏览器不用做任何设置就能FQ了，有用Proxy Switch插件的选择直接连接。

**Comment by sundaqing1969** [comment]
@xyuanmu 我再安装一篇，看如何，谢谢你

**Comment by sundaqing1969** [comment]
试用报告，湖南电信接不通，湖南联通可以接通

**Comment by jzp820927** [comment]
![default](https://cloud.githubusercontent.com/assets/5740066/10117639/87152c6a-6490-11e5-9609-ce3b3e79d0d6.png)

有谁有这情况麽？

**Comment by xyuanmu** [comment]
@jzp820927 退出其他代理软件，包括goproxy或goagent

**Comment by jzp820927** [comment]
什么软件都没运行，就开了这一个软件。

**Comment by rongwutw** [comment]
谢谢  jasonliul ,速度飞快,
虽然,只有一个 "莫斯科" 可连上,
谢谢 xyuanmu,
你的教程,简明,好用.

**Comment by jzp820927** [comment]
@xyuanmu 重启了一下系统，OK了，估计是什么残留的进程没清除。谢谢！

**Comment by rongwutw** [comment]
免安装版,chrome 报恶意程序,直接删除,
我只好使用,安装版的.

**Comment by hijklmn** [comment]
经实验，英国、加拿大和俄国可以正常使用，速度很快。

**Comment by rongwutw** [comment]
经实测，提取 PegasusVPN.exe 确实,即可变成 "免安装版" 了

**Comment by toobed** [comment]
好像有使用时间的限制？

**Comment by Yamazaki-wu** [comment]
苦逼的上海电信用户，选哪个国家都是一卡一顿，除非只是用来搜索。

**Comment by zhanxiage233** [comment]
我这里速度还好，并不算特别快，没有以前的蓝灯快

**Comment by zhanxiage233** [comment]
提示修改Rasphone.pbk，不会有问题吧

**Comment by thundery1** [comment]
新加坡和美国的连不上,其他正常

**Comment by bhxbjzx** [comment]
我的怎么显示633：0一个也连接不上

**Comment by bhxbjzx** [comment]
求指导？

**Comment by bhxbjzx** [comment]
@jzp820927我的怎么显示（633：0）一个也连接不上。

**Comment by jzp820927** [comment]
@bhxbjzx 退出其他代理软件，包括goproxy或goagent

**Comment by palesaint** [comment]
可以连上，倒是好像看不了youtube

**Comment by bygloam** [comment]
Thanks

**Comment by ARwMq9b6** [comment]
满速！！！！！！！！！！！

**Comment by zhanxiage233** [comment]
@ARwMq9b6 连哪个国家的？来张测速图吧，我这都试了一下，速度能看网页，视频不行

**Comment by ARwMq9b6** [comment]
回楼上 ( @zhanxiage233 ),  既然能连上，速度应该因各网友的网络环境不同而不同，比如 [中国电信](https://zh.wikipedia.org/zh-cn/%E4%B8%AD%E5%9B%BD%E7%94%B5%E4%BF%A1) 宽带的国际出口网络拥塞，晚上尤甚。

**Comment by zhanxiage233** [comment]
@ARwMq9b6 我的正好就是中国电信

**Comment by jasonliul** [comment]
@zhanxiage233
噗哈哈, 星岛测速才90几kb, 我正在看视频.

**Comment by wzdnzd** [comment]
@ARwMq9b6 windows reported an error while trying to establish the connection （628:0），请问是什么原因。goproxy和goagent都没运行。。。

**Comment by alresvor** [comment]
这个软件的代理方式并不是改IE代理设置，而是在系统中新建VPN
所以如果连接有问题，也是系统连接错误，系统的连接错误都是有序号的，例如楼上的 628
这些都是可以在网上搜到的。

**Comment by wzdnzd** [comment]
@alresvor 看了各种关于vpn 628的错误，还是解决不了啊。。。

**Comment by hijklmn** [comment]
好像挂掉了，没有办法登陆了，不知各位怎样？

**Comment by xyuanmu** [comment]
@hijklmn 刚才试了下，一样没法登录

**Comment by toobed** [comment]
被和谐了

**Comment by hijklmn** [comment]
@jasonliul 有没有办法修复不能登陆的问题？

**Comment by jasonliul** [comment]
http://downforeveryoneorjustme.com/pegasusvpn.com

**Comment by xyuanmu** [comment]
悲哀～

**Comment by pgz123** [comment]
悲哀

**Comment by toobed** [comment]
悲哀

**Comment by jasonliul** [comment]
飞马5月下旬上线测试, 某成员曾说计划运行4年.
估计迟早会回来的.

**Comment by jasonliul** [comment]
飞马回归.

**Comment by hijklmn** [comment]
@jasonliul 令人感动，感谢楼主。

**Comment by thundery1** [comment]
嘿嘿，是能登录了。。感谢！！

**Comment by xyz12810** [comment]
是PPTP的而已

**Comment by thundery1** [comment]
不过我这儿啥服务器都不能登录了呢。。提示网络未连接？？。。

**Comment by pgz123** [comment]
每次都开机自启动

**Comment by xinews** [comment]
我这所有服务器都不能登录，提示服务器拒绝用户名或密码

**Comment by jzp820927** [comment]
C:\WINDOWS\system32>tracert 8.8.8.8

通过最多 30 个跃点跟踪
到 google-public-dns-a.google.com [8.8.8.8] 的路由:

  1   296 ms   297 ms   295 ms  192.168.46.1
  2  192.168.46.1  报告: 无法访问目标协议。

跟踪完成。

**Comment by jasonliul** [comment]
**Pegasus VPN 1.2.7.0**
https://pegasusvpn.com/Pegasus-Installer.exe

**Comment by jzp820927** [comment]
有更新新服务器麽
