### ISSUE TITLE
港媒哀悼黄狗

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#227]
https://theinitium.com/article/20150828-china-greatfirewall1/

社长看来散席着草去咧~~
:)

**Comment by redfrog999** [comment]
有啥好哀悼的，用蓝灯或者ss做前置，goa用起来比gop还要爽，autorange设置好，速度刷刷刷，帮主估计要为生计奔忙，有空来看看就不错啦。

**Comment by toobed** [comment]
从GFW多年封锁的结果来看，由于语言门槛，以及庞大的中国互联网用户基数，中国政府施行的“内联网”化策略是成功的。

**Comment by toobed** [comment]
中国政府强化升级GFW目的，是成功抬高中国用户自由访问互联网的门槛，让中国境内自由不受限制访问互联网的人数保持在极小的群体之内
