### ISSUE TITLE
赛风99 全新界面

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#228]
https://s3.amazonaws.com/irw7-3wt4-sic4/en/download.html
终于可以最小化到托盘了.

**Comment by sundaqing1969** [comment]
感谢

**Comment by wenliyang** [comment]
试了下，支持多国语言界面了，确实方便不少

**Comment by sundaqing1969** [comment]
速度太快了

**Comment by hijklmn** [comment]
赛风一直没有能正常工作过，江苏电信

**Comment by wenliyang** [comment]
浙江电信，正常工作，速度也不慢

**Comment by hijklmn** [comment]
@jasonliul 怎么用，下载的exe文件直接打开就可以还是需要某些设置？

**Comment by xyuanmu** [comment]
赛风还是不给力啊，广东电信，速度一般，而且经常中断重连，不如荷兰的飞马。

**Comment by zhanxiage233** [comment]
炒鸡好用，1080p毫无压力，这次进化太给力

**Comment by Yamazaki-wu** [comment]
上海电信表示和蓝灯、GOA差不多。而且为什么设置页面什么都点不了？

**Comment by Yamazaki-wu** [comment]
重启客户端好了。

**Comment by zj3** [comment]
北京联通 速度慢 连接缓慢 连上后不到一分钟就自动重连

**Comment by rongwutw** [comment]
谢谢楼主,好用.

**Comment by toobed** [comment]
一如既往的难用，连接困难，速度慢

**Comment by ARwMq9b6** [comment]
大神 NirSoft 的 NirCmd 能在命令行和 Window 批处理中隐藏赛风的窗口：

```dos
nircmdc.exe win hide process Psiphon3.exe
```

**Comment by thundery1** [comment]
老掉线啊。。貌似速度不行了，连上了也翻不了墙哪

**Comment by bhxbjzx** [comment]
效果不好

**Comment by jang-u** [comment]
电信宽带，很难连上，连上很快断
