### ISSUE TITLE
蓝灯 lantern 2.08

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#231]
https://github.com/getlantern/lantern/releases

这版终于修复了一些问题, 之前日本节点始终<200kb/s

Kisesy大大的补丁
https://goo.gl/zNDSUy

蓝灯主创亚当·费斯克访谈
http://cn.nytimes.com/china/20150401/c01censor/

**Comment by hijklmn** [comment]
不知道Github的版本怎么用，直接到官网下载了，可以安装。

**Comment by xyuanmu** [comment]
2.08是上月以来最流畅的版本，希望嫑是回光返照，啊弥豆腐，啊弥豆腐。

**Comment by jasonliul** [comment]
@xyuanmu 我这里已经封杀3个灯塔了.

**Comment by auiny** [comment]
WIN10下无法运行就我一个？

**Comment by lr95692** [comment]
这个补丁需要解压密码

**Comment by jasonliul** [comment]
蓝灯主创亚当·费斯克访谈
http://cn.nytimes.com/china/20150401/c01censor/

**Comment by alresvor** [comment]
话说，你们那的蓝灯会不会自动更新云配置文件

**Comment by alresvor** [comment]
个人修改版
https://groups.google.com/forum/#!topic/fuckfang/bBjBInO2CGU

**Comment by ARwMq9b6** [comment]
楼上你好，俺这 IP 变动频繁，写了一个 Windows 批处理文件检测 IP 变化并备份新增的 IP 及其对应的配置文件，用到到第三方工具有 NirCmd ( nircmdc 命令 ) 和 cygwin ( grep 和 cp 命令 ) ，非常粗糙。

> check_lantern_yaml.bat

```dos
cd /d C:\Users\Administrator\AppData\Roaming\Lantern

:Find_Lantern_Yaml_Name
ls -1|FINDSTR /R /C:"lantern-.*\.yaml" > %~dp0Lantern_Yaml_Name.txt||GOTO NoLanternYamlFile
GOTO Get_Lantern_Yaml_Name

:NoLanternYamlFile
nircmdc infobox "No Lantern yaml file" "Warning!"
GOTO Find_Lantern_Yaml_Name

:Get_Lantern_Yaml_Name
FOR /F %%i IN (%~dp0Lantern_Yaml_Name.txt) DO SET Lantern_Yaml_Name=%%i

:Find_If_Proxyall
findstr /C:"proxyall: true" "%Lantern_Yaml_Name%"||GOTO Proxyall_Is_Flase
GOTO Find_Get_New_IP

:Proxyall_Is_Flase
nircmdc infobox "Please set proxyall to true" "Warning!"
GOTO Find_If_Proxyall

:Find_Get_New_IP
grep -P -o "fallback\-.+[^\:]" "%Lantern_Yaml_Name%">%~dp0ip_new.txt
FOR /F %%A IN (%~dp0ip_new.txt) DO set ip_new=%%A

FINDSTR /C:"%ip_new%" "%~dp0ip_list.txt"||GOTO Found_New_IP
GOTO End

:Found_New_IP
"*********************\Babun\cygwin\bin\echo.exe" -e %ip_new%>>%~dp0ip_list.txt
cp "%Lantern_Yaml_Name%" "****************\Backups\Configurations\%ip_new%_%Lantern_Yaml_Name%"

:End
```

**Comment by alresvor** [comment]
真巧，我也写过这种代码，但我这里的IP从不变动，一直都是日本的，想找别的IP还得挂代理才行
如果不挂代理得到的就是日本服务器，只要挂代理就是荷兰服务器
挂不同国家的代理给的IP也是不一样

**Comment by jasonliul** [comment]
我这里是新泽西最多.
其次是日本, 荷兰, 新加坡.

**Comment by lefantian** [comment]
@alresvor 什么云配置文件，你是说 yaml 文件？反正官方不管是 lantern.exe还是 yaml文件好像都会自动更新，kingtopest编译的 lantern.exe 好像不会自动更新，但是 yaml 好像会。
另外，你是要出那个绿色化、去PAC、去弹窗的补丁？

**Comment by alresvor** [comment]
@jasonliul 原来有这么多服务器啊，我这里只有日本和荷兰。。。
也是，以前有地图的时候，服务器就挺多的，嘿嘿

**Comment by jasonliul** [comment]
@alresvor 
奇怪, 星岛的节点刚刚被封杀, 这个节点很少出现. 
我都是205版本才抓到的,

**Comment by jasonliul** [comment]
209 更新

**Comment by alresvor** [comment]
更新这么快，不会又像以前一样，只是想把版本补全吧

**Comment by alresvor** [comment]
现在的蓝灯还能匿名吗
在这里的 http://ipaddress.com/ 的 Proxy 一栏显示为 Transparent Proxy 并且能直接看到真实IP
以前的版本也是显示 Transparent Proxy 但是 IP是127.0.0.1

**Comment by Kashgar-Castle** [comment]
有些网站是根据你访问的IP显示不同内容的，而且不能自己手动设置所在地区，之所以用代理就是为了跳出大陆看到更丰富的内容。蓝灯改成现在这个样子就满足不了这个要求了。

**Comment by jasonliul** [comment]
@alresvor 反审查软件本身就不追求高匿名,这种软件分类都是今年才有的, 瓦伦西亚国际反审查节之后.
除了洋葱, Jondo其他都不是真正的匿名.

蓝灯也能帽子前置,

**Comment by ARwMq9b6** [comment]
@alresvor 关于 **Transparent Proxy**

http://ipaddress.com/ 上的 Transparent Proxy 一项的值和 Header 里的 `X-Forwarded-For` 有关，客户端（如浏览器）中能够自定义这个值。一款 Firefox 扩展 [Random Agent Spoofer](https://github.com/dillbyrne/random-agent-spoofer/releases) 能轻松实现自定义或每次访问网页随机一个 X-Forwarded-For IP 地址。

效果如图 ![https://i.imgur.com/0788bUM.jpg](https://i.imgur.com/0788bUM.jpg)

更多介绍： <https://code.google.com/p/goagent/issues/detail?id=21851>

```header
GET / HTTP/1.1
Host: ipaddress.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.8
Accept-Encoding: gzip,deflate,sdch
DNT: 1
X-Forwarded-For: 1.1.1.1
Via: 1.1 1.1.1.1
If-None-Match: cnnoa2o
Connection: keep-alive
```

**Comment by alresvor** [comment]
@ARwMq9b6 嗯，昨天我看开发者在 issues 说到了
最新版还加了个header，"Client-Ip"

**Comment by ARwMq9b6** [comment]
@alresvor 感谢！果然这个 Client-Ip 会暴露用户的 IP ，求编译一个发送真实 Client-Ip 的版本。

**Comment by jasonliul** [comment]
@ARwMq9b6 
这是国内翻墙明星的作秀. :)

反审查的目的是自由浏览, 匿名模式不是自由的, 不能视频或下载, 拒绝cookie, 不登录[当然你搞定论坛不活跃用户的帐号密码,用人家的就可以]

海盗湾也赶时髦做了一个浏览器, 只是取消了Tor的匿名性.

隐私和匿名不同, 例如我们知道是你, 但你衣冠楚楚, 不知道你的私处风光. 这是隐私. 匿名的意思是根本搞不清这是谁.

匿名通过软件是无法实现的, 你在网上的一切活动, 会形成一份侧写profile, 在数据库里模糊搜索, 也就几十人, 加上人脑分析生活细节, 网络促进行为科学进化到令人发指的程度 :)

吹嘘软件匿名, 那是掩耳盗铃.

**Comment by alresvor** [comment]
@jasonliul 
这倒不是匿名不匿名的关系，我们用蓝灯本来就只是为了翻墙

但是修改header头，会造成很多意外的情况
例如：使用 GoAgent 时，GAE 会默认自行修改UA，造成很多网站拒绝访问
再例如 youtube ，即使我们用日本的IP，用没cookies的浏览器，打开，它也能显示为中文
这种网站很多，有的是判断IP有的是判断header头，这种情况可以结合 Kashgar-Castle 所说
所以我们并不期望蓝灯能匿名，只要它不主动暴露我们的信息就行

**Comment by jasonliul** [comment]
@alresvor 
这倒是, 2.08没有这问题, 可惜我升级了

**Comment by thundery1** [comment]
为毛我这儿的蓝灯竟然不能运行了。。好几个版本都是这样。。。貌似只有那个防ddos的版本能运行，但是连不上了。。。晕了，，，
