### ISSUE TITLE
反审查软件: 圣斗士十二宫

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#232]
1.白羊
GoProxy 黄狗GoAgent升级版"狗屁"
https://github.com/phuslu/goproxy

网民心中的成龙大哥, 虽然今年成了替罪羊, 不过还在准备新狗屁.:) 老白羊不能武打, 但还能放响屁. :)

2.金牛
Alkasir 绕行者
https://alkasir.com/
https://github.com/alkasir/alkasir﻿
直连已经被封杀, 最高效利用前置带宽的方式.
新版2.0已经内测.

*Alkasir, 阿拉伯语"绕行, 有意避开", 原作者是一个也门的学生, 受到国际人权组织支持奖学金,背后的boss是欧盟人权理事会.AK基本总是满速.

新版交由瑞典人开发,新节点也在瑞典.会是浏览器插件的形式.已经是会员可能被邀请参与测试.

有钱就是能耐, 绕行者并不限制无墙国家公众使用, 带宽好得惊人. 即使现在使用帽子前置, 前置半死不活, 绕行者依然力保2M.其他基本就跑不动.

3.双子
赛风 Psiphon3
https://s3.amazonaws.com/irw7-3wt4-sic4/en/download.html
每两天需要更新文件.
有些节点不时满速, 但是不可能稳定.

蝴蝶穿花, 善变的一夜情高手.而且赛风是双模式,SSH+/VPN

4.巨蟹
纸飞机 Shadowsocks
https://github.com/shadowsocks/shadowsocks-windows/releases
变种很多, 免费小社区提供帐户.

高智商少爷兵的玩具, 不时闹情绪好比月经.不过纸飞机的铠甲足够厚硬.

5.狮子
飞马VPN
https://pegasusvpn.com/en/

西欧匿名IT年轻富豪们的大手笔,月底其他免费服务精尽人亡, 飞马一次性注资4年, 即使月底也是速度惊人.

Boss们自视为<黑客帝国>的利奥, Leo狮子座.

6.处女
Jondo 无名
https://anonymous-proxy-servers.net/en/jondo.html

一丝不苟的精品匿名服务, 完全可以媲美洋葱, 今年免费服务器增至6个, 速度限制也改为100kb/s

7.天平
蓝灯 Lantern
https://github.com/getlantern/lantern/releases
https://s3.amazonaws.com/lantern/lantern-installer-qa.exe
蓝灯有日本, 美国,荷兰, 新加坡节点, 玩家可以留意.

蓝灯旧版需要邀请, 当然要玩交情. 2.0版本表现摇摆不定, 那只有天平.

8.天蝎
Tor browser 洋葱
https://www.torproject.org/projects/torbrowser.html.en
最知名的匿名软件, 但其实就像天蝎座, 功利至上, 意图明显. 使用帽子前置掩饰意图, 才是正确的方式.

9.射手
MxTunnel 梭鱼
https://barracudadrive.com/MxTunnel.lsp

射手是爱说大话的庸才, 所谓理论家.梭鱼是高效的https代理,需要VPS配布. 但是推出却是远在VPS普及之前.

平庸也是福气, 监控所有https连接, 恐怕是妄想.

10.水瓶
SoftEther VPN Client + VPN Gate Client
http://www.softether-download.com/files/softether/
http://www.vpngate.net/cn/download.aspx
日本鬼才, 之前世人都以为日本人不会做软件. 现在作者还是闷葫芦, 既不出名, 也不张扬.列国高手赞不绝口.

11.山羊
免费SSH
https://www.fastssh.com/page/secure-shell-servers/continent/asia/

软件BitviseSSHClient
http://tp.vbap.com.au/download
最简单方便的组装纸飞机, 最蟑螂的老不死方式.

老政委, 老资格还有谁? 老家伙团结群众, 支持帽子前置最好.

12.双鱼
GranGorz 鸡鸡
https://grangorz.org/download
实际上不再更新, 直连被封杀, 使用亚洲前置也可用. 欧美前置速度上不去.

眼高手低的家伙, 美称策划者,想法太多实践很少.

**Comment by hijklmn** [comment]
飞马已经挂了，主页都打不开了

**Comment by wenliyang** [comment]
好些不知道的，楼主太有才了

**Comment by xyuanmu** [comment]
这么多，难得整理了，国庆期间丝般润滑

**Comment by cnshinchan** [comment]
收藏了

**Comment by lele2010lele** [comment]
听不懂，感觉楼主很厉害

**Comment by bsfmig-a** [comment]
IPv6 Shadowsocks+国内服务器中转（我自己控制的服务器），速度嗖嗖的。
IPv6的好处是带宽真TM大（10+MB/s），我有时候下载国外软件也走这个通道（即使没有被墙）。

**Comment by blob2015** [comment]
把别人整理出来的，然后搞个文艺的星座，这样好吗？

**Comment by UltraDWS** [comment]
有才！相当的6！
