### ISSUE TITLE
蓝灯突然变得很慢

### ISSUE THREAD

**Issue by hijklmn** [phuslu/goproxy#236]
无锡有线通，突然速度很慢，google网站打不开了，只能打开推特，有没有什么好办法解决？之前一直蓝灯一直非常稳定且速度很快。

**Comment by xyuanmu** [comment]
因为有人把IP都暴露出去了

**Comment by angle1895** [comment]
最近两个月蓝灯变成烂灯

**Comment by jasonliul** [comment]
我本来有十几个ip, 现在剩下一个

**Comment by jasonliul** [comment]
lantern 2.0.10
https://s3.amazonaws.com/lantern/lantern-installer-qa.exe

**Comment by hijklmn** [comment]
@jasonliul 多谢！

**Comment by thundery1** [comment]
俺这儿也不好使了

**Comment by qianluqin** [comment]
贱人太多，害人不浅。

**Comment by Lrevor** [comment]
https://github.com/getlantern/lantern/issues/3237
官方人员好像重启了服务器?

**Comment by hijklmn** [comment]
@Lrevor 目前已经可以用，速度恢复正常了。

**Comment by LittleNewton** [comment]
不知道为什么，同局域网下，笔记本很好，但是台式机就很慢。我连系统都重组装了。还是不见起色。不知道是哪里设置错了。
