### ISSUE TITLE
SoftEther VPN Client + VPN Gate Client 4.19 r9582

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#237]
SoftEther VPN Client + VPN Gate Client 4.19 r9582
http://download.vpngate.jp/common/cd.aspx/vpngate-client-2015.10.06-build-9582.133716.zip

**Comment by hijklmn** [comment]
这个基本上都连不上。

**Comment by jasonliul** [comment]
Free SoftEther account
https://www.fastssh.com/page/softether-servers

俄国远东也有一些私设服务器.

**Comment by xzchina** [comment]
已经放弃...

**Comment by lg560852** [comment]
楼主，你的那个类似tracert那样持续检测到目的IP整条线路所有跳响应时间的那个工具叫什么名字来着？好像是用来检测VPS速度的，图标是个delphi程序的图标。
![qq 20151008121134](https://cloud.githubusercontent.com/assets/3312506/10357552/f135c5b8-6db5-11e5-9fc3-c95eba849dc9.jpg)

**Comment by jzp820927** [comment]
莫非是 mtr ?

**Comment by lg560852** [comment]
感谢！@jzp820927
好像是它  http://winmtr.net/
这个确实有这个功能！

**Comment by jasonliul** [comment]
[B]SoftEther VPN Client + VPN Gate Client 4.19 r9599[/B]
http://download.vpngate.jp/common/cd.aspx/vpngate-client-2015.10.19-build-9599.133820.zip
