### ISSUE TITLE
r152版本测试反馈

### ISSUE THREAD

**Issue by ydq** [phuslu/goproxy#24]
goproxy对比goagent（mac osx下）
* **纯PHP模式**下，goproxy访问一段时间后出现**Service Unavailable**，不知道是什么原因，必须重新加载goproxy。
* goproxy体积明显比goagent要大很多（难道是因为osx自带python的原因？）
* goproxy启动速度明显比goagent慢很多，同样的双击command之后启动终端界面，goagent几乎是秒开，而goproxy还要等上三四秒才弹出notify，显示启动。
* goproxy默认生成的证书导入到系统，默认状态是个红色的叉叉提示“此根证书不被信任”，而goagent生成的证书导入到系统默认状态仅仅只是黄色感叹号提示“此证书尚未经过第三方验证”
* **[goagent bug]**php模式下goproxy完美，但是goagent访问部分页面（如google、youtube）时标签栏会一直转啊转啊转啊转，实际上网页已经加载完毕，这样会导致在osx下登录chrome浏览器的窗体一直显示不出来，一直在那转啊转的仿佛在加载中（当我关掉goagent时，已经加载好的登录界面立马显示出来了。chrome应该是判断要等不再转动才会显示出来）

**Comment by phuslu** [comment]
证书问题应该已经解决了。

其他问题正在陆续解决。
