### ISSUE TITLE
goproxy 常规（gae）配置教程

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#243]
本文不涉及php、vps等稍高级的用法:)

1、goproxy与goagent的区别与联系可参考 #205
同一作者不同语言的实现。

2、服务器端
继续沿用goagent 3.2.x版本的服务器端即可。部署方法参考[图文教程](https://github.com/phuslu/goproxy/blob/wiki/InstallGuide.md)
[GoAgent(python)最后一个版本备份](https://github.com/phuslu/goagent/archive/985cbd55e232833a859e7f2940b54f7dcb6cdb14.zip)

3、客户端下载
最新正式版：[https://github.com/phuslu/goproxy/releases](https://github.com/phuslu/goproxy/releases)
最新測試版：[https://github.com/phuslu/goproxy-ci/releases](https://github.com/phuslu/goproxy-ci/releases)
Mac：	goproxy_macosx_386-r328.tar.bz2
32位Linux：	goproxy_linux_386-r328.tar.xz
64位Linux：	goproxy_linux_amd64-r328.tar.xz
ARM Linux：	goproxy_linux_arm-r328.tar.xz
32位Windows：	goproxy_windows_386-r328.7z
64位Windows：	goproxy_windows_amd64-r328.7z

4、客户端配置
复制一份gae.json，重命名为gae.user.json
对照下面几图分别修改appid、password、iplist等部分：
![gae user json](https://i.imgur.com/9rev4xb.png)

5、以管理员身份运行goproxy-gui.exe启动，一般会自动生成证书文件GoProxy.crt并导入到系统受信任的根证书里，没自动导入的话，手动导入一下

```golang
------------------------------------------------------
GoProxy Version    : r331 (go/go1.6 windows/amd64)
Listen Address     : 127.0.0.1:8087
Enabled Filters    : stripssl,autorange|autoproxy,gae,direct|autorange
Pac Server         : http://127.0.0.1:8087/proxy.pac
------------------------------------------------------
I0402 15:37:29.444953    4008 rootca.go:49] Generating RootCA for GoProxy.crt
E0402 15:37:33.235416    4008 rootca.go:110] Import RootCA([]string{"certmgr.exe", "-del", "-c", "-n", "GoProxy", "-s", "-r", "localMachine", "root"}) error: exit status 4294967295
I0402 15:37:33.306430    4008 rootca.go:112] Import RootCA(GoProxy.crt) OK
I0402 15:37:33.414521    4008 autoproxy.go:148] start updater for &autoproxy.GFWList{URL:(*url.URL)(0xc08220eb80), Filename:"gfwlist.txt", Encoding:"base64", Duration:86400000000000}
I0402 15:37:33.806879    4008 main.go:185] ListenAndServe on 127.0.0.1:8087
```

6、浏览器可以用插件也可以用PAC：一般代理设置服务器127.0.0.1，端口8087，PAC的话填http://127.0.0.1:8087/proxy.pac

**Comment by ARwMq9b6** [comment]
谢谢，*.json 配置们修改前后的对比图。直观生动。

**Comment by hijklmn** [comment]
楼主能不能更新一下goproxy，感觉没有goagent稳定，另外看视频不够流畅。

**Comment by zj3** [comment]
目前goproxy相对于goagent有什么优势？只是由于开发语言不同就会速度快吗？

**Comment by CNMan** [comment]
@zj3 可以去原goagent code看看phuslu的一些回复
https://code.google.com/p/goagent/issues/list?can=2&q=commentby%3Aphuslu.bot

**Comment by TangBaohua** [comment]
还是goagent好用多了，至今都还在用

**Comment by thundery1** [comment]
password是指哪个密码？？

**Comment by CNMan** [comment]
@TangBaohua 其实我也是还在用goagent:) 也希望goproxy尽早把goagent的功能都移植过来

@thundery1 部署GAE服务器端时设置的密码，防止appid的流量被盗用。默认部署是没密码的，没设置过的话保持留空就行了

**Comment by thundery1** [comment]
@CNMan 谢谢啦。。goproxy确实还不太行。。看视频不流畅。。我用gae模式还经常连不上。。同样的ip在goagent里就是很正常的使用。。不过这两天goagent老是报一堆乱糟糟的错误，不晓得咋回事，像是bug爆发了一般。。

**Comment by ncmon** [comment]
楼主你这个客户端配置直接修改原来3个文件不是更简单吗为什么非要改成suer，还有文件夹里面的goagent.exe和goproxy.exe有什么区别吗是不是功能一样的

**Comment by CNMan** [comment]
@ncmon 
1、可以直接修改原文件，user.json的好处是可以只留修改过的部分，类似以前goagent的user.ini
2、不一样

**Comment by shoujiao** [comment]
请问在哪里加ipv6的参数？其他ip几乎都是timeout

**Comment by plgkm6** [comment]
请问这个goproxy不能用Google application了吗？

**Comment by xrwz007** [comment]
借宝地问下，原来部署过老版的黄狗，上传过appid。部署这款goproxy，需要再重新上传吗？配置文件都改好了

**Comment by mouseroser** [comment]
不需要

**Comment by jzp820927** [comment]
3.2以上版本的服务端不需要，低于这个版本，就说不清楚了，试试就知道了

**Comment by mouseroser** [comment]
应该只能用3.2以上的版本部署

2016-03-20 19:16 GMT+08:00, 天朝猪 <notifications@github.com>:

**Comment by fredericky123** [comment]
最新版本的没有iplist.json啊 怎么设置

**Comment by fredericky123** [comment]
哦哦 搞定了 统一在gae.json里

**Comment by shindaren** [comment]
haha

**Comment by KwToPA** [comment]
感谢

**Comment by TonnyTonny** [comment]
教程詳細，謝分享。

**Comment by yuli6800** [comment]
请问IPlist填的IP怎么获得，要对应未变前的域名吗，还是只要是IP就可以填进去

**Comment by mouseroser** [comment]
特殊阶段，自力更生

2016-04-02 8:29 GMT+08:00 yuli6800 <notifications@github.com>:

**Comment by CNMan** [comment]
更新一下：）

**Comment by jasonliul** [comment]
@CNMan 

有些厚颜无耻. :)

大大的VPS何时再来一次强搜? 只要每次发布一丁点就好.

**Comment by CNMan** [comment]
@jasonliul 有能用的就行了，我也是1个IP在跑：）
![img](https://i.imgur.com/tq4xKsS.png)

**Comment by jasonliul** [comment]
@CNMan 

俺本来两个残兵跑满速, 贪心加多了一些ip,
现在只有400左右了 LOL

**Comment by laozhu999** [comment]
谢谢了，好久没用了，结果原来的goagent因为电脑没有权限而废了，旧版goaproxy的设置还和新版的不一样。对于我们这种门外汉你的介绍至少可以让我站在门外也能看。。。。。现在问题还是回到找IP上了。

**Comment by blob2015** [comment]
@CNMan 
老兄，能不能更新一下？
现在支持//注释了
还有其他一些东西

**Comment by CNMan** [comment]
@blob2015 https://github.com/phuslu/goproxy/blob/wiki/ConfigIntroduce.md
现在教程在这里：）
