### ISSUE TITLE
自动前置 HTTP Tunnel Genius 1.0

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#245]
https://sites.google.com/a/wongsk.twbbs.org/wongsk/image/httptunnelgenius-1.png

主页
http://www.httptunnel.ge/

下载
http://www.mediafire.com/download/mcssxezd6mjema5/HTTP+Tunnel+Genius+by+ABDO+ELHOMMANI%254thepf.com.rar

推介
http://www.techgravy.net/http-tunnel-genius-hide-ip-address-and/

古老的小工具,自动下载搜寻测试http前置,转换为本地代理127.0.0.1:1978.
只需要设置黄狗proxy段就行了.

该网站免费滚动测试可用http代理, 直到今天也可用.

如果默认设置不好用,也可以自选http代理.远比MeoW更符合黄狗的要求.

**Comment by thundery1** [comment]
是要比meow智能些，可以自动找代理。。哎，就是免费代理速度堪忧啊。。看个网页还行吧。。

**Comment by jasonliul** [comment]
@thundery1 作者是希腊人, 基本是测试欧洲代理.
可以自己选择亚洲美洲代理.

例如
133.130.112.169:3128
69.168.242.44:8080
69.168.242.46:8080
