### ISSUE TITLE
chrome配置问题

### ISSUE THREAD

**Issue by yeahwu** [phuslu/goproxy#25]
火狐配置一切正常，但是轮到chrome配置goproxy，老是提示“你的连接不是私密连接”。求解？
还有youtube暂停缓冲也停止，不知道是youtube本身的原因？还是goproxy的问题？
最后就是不能自动切换appid？

**Comment by tianlichunhong** [comment]
这个应该是证书问题，添加证书，应该就可以了。

**Comment by wujiaqian** [comment]
谢谢回复！
证书导入导出好多次了，就是不成功。是不是应为我的chrome是便携版的原因？

**Comment by gao995996** [comment]
我也同問？據說要刪除goagent的證書？但這樣不會影響到goagent、和xxnet？？？求答？
