### ISSUE TITLE
三只小强晒太阳

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#250]
电信:
211.181.65.11|61.238.203.11|202.248.248.6

**Comment by pug908** [comment]
修复ip的方法已经搞定，以后会有大量的ip复活

**Comment by pug908** [comment]
修复ip的方法已经搞定，以后会有大量的ip复活

**Comment by pug908** [comment]
修复ip的方法已经搞定，以后会有大量的ip复活

**Comment by pug908** [comment]
可惜扫ip工具没有代理功能

**Comment by immeman** [comment]
谢谢，这三只比我现役的要稳定不少，不知道能挺多久

**Comment by thundery1** [comment]
被封的ip还能修复么？？不是gfw漏网解封？

**Comment by xyuanmu** [comment]
@thundery1 偶尔会有一部分复活，如国庆期间复活的110.164高速IP段，不过都是昙花一现。

**Comment by jasonliul** [comment]
大风起兮云飞扬, 三只小强兮晒秋阳, 安得ip兮遛阿黄.
:)

**Comment by pug908** [comment]
中国已经进入秘密警察时代，匿名上网是第一

**Comment by TangBaohua** [comment]
这三个IP能用 延时也比较低
