### ISSUE TITLE
Youtube 强制html5

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#253]
狗粮质量已经不高, Youtube容易卡顿.

现在的浏览器基本都支持html5, youtube也支持. 建议使用html5播放, 远比adobe flash player快速.
检查: https://www.youtube.com/html5

Html5的缺点是不能全屏, 

强制使用html5的小把戏, 是在url后面加上
?html5=1 或
?html5=true

例如
https://www.youtube.com/watch?v=ebXbLfLACGM
改为
https://www.youtube.com/watch?v=ebXbLfLACGM?html5=1

**Comment by pug908** [comment]
从来不用浏览器看U兔

**Comment by xyuanmu** [comment]
现在Y2B不是默认HTML5的么，不过虽然在线看不给力，下载速度还是很可观的。

**Comment by redfrog999** [comment]
HTML5我用 Magic Actions 配合FF最新版，可以全屏，速度非常不错哦，用蓝灯随便跑720p。在线视频，我觉得这个分辨率已经很好了。

**Comment by NKUCodingCat** [comment]
在学校用goagent上u2b能1080p全程无压力所以用不上=。=

**Comment by jasonliul** [comment]
@NKUCodingCat 
唔制!
一定是墙监会的狗奴才, 光顾偷窥男女同学的艳照自拍, 玩忽职守.
统统应该捉去操场打靶.

**Comment by NKUCodingCat** [comment]
@jasonliul 什么鬼wwwww
