### ISSUE TITLE
各国IP段[每日更新]

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#261]
http://www.ipdeny.com/ipblocks/data/aggregated/

前段时间挂掉了，今天发现又恢复服务了

**Comment by TonnyTonny** [comment]
感謝分享

**Comment by sundaqing1969** [comment]
感谢！

**Comment by bygloam** [comment]
thanks

**Comment by zhhzq** [comment]
能问下怎么使用吗？好像不能直接GG测试，要死机的样子！

**Comment by lxok89** [comment]
IP量太大了，还是如以往发goodip txt不更好？

**Comment by CNMan** [comment]
@lxok89 Google IP段今年就不再更新了，里面还有好多可用的呢:)

**Comment by imyhxy** [comment]
扫了了两晚，把日本和韩国的都扫了了，设置800ms延时，一个都没有扫到，一个都没有扫到！！
