### ISSUE TITLE
Barba Tunnel 8.3 胡须隧道

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#272]
万能反审查软件前置, 可以伪装VPN或者其他反审查软件的流量为正常普通, 消除流量特征. 
简单说, 破墙不知道你飞跃长城.

家中常备, 如果反审查软件速度变慢, 胡须哥帮你搞掂.

主页
https://barbatunnel.codeplex.com/

下载
https://barbatunnel.codeplex.com/releases/view/119123

详解教程
https://barbatunnel.codeplex.com/documentation

**Comment by ren2014311** [comment]
可以让openvpn复活吗？

**Comment by pgz123** [comment]
英文教程看不懂

**Comment by zuntisaha** [comment]
可惜同时要服务器开着这个软件才可以。

**Comment by zuntisaha** [comment]
要求

BarbaTunnel需要.NET框架4.5“巴尔巴监控”和“巴尔巴服务”，但BarbaTunnel.exe并不需要.NET框架，这样你就可以在客户端和服务器端没有.NET框架上手动运行它。
配置服务器

登录到您的Windows Server。
下载BarbaTunnel并解压缩。
打开“barbatunnel.ini在BarbaTunnel文件夹”，并设置“ServerMode = 1”
进入BarbaTunnel文件夹，打开“配置\服务器”文件夹，然后打开“HTTP-Retunnel.ini”文件。
设置“ServerAddress”到你的服务器的IP地址（必填）。
运行“Install.vbs”
运行“Run.Vbs”
服务器已配置为特定的端口，支持自定义配置请参见“config.ini 文件 ”。
配置客户机

登录到您的Windows客户端。
下载BarbaTunnel并解压缩。
复制“配置”文件夹，你已经创造了他们在服务器计算机的配置文件。
运行“Install.vbs”
运行“Run.Vbs”
尝试建立VPN连接到您的服务器
备注

建议改名“服务器名”文件夹到您的服务器名称或服务器IP（可选）。
确保BarbaServer的主要版本和BarbaClient是一样的。这种1.0和1.1
确保两个服务器的配置文件和客户端配置文件是一样的。
确保企业防火墙不会阻止隧道端口。
确保你的本地防火墙，例如Windows防火墙没有阻止隧道端口或BarbaTunnel。
请确保您可以访问重新引导系统，如果你失去连接到您的服务器之前，运行BarbaTunnel您可以创建一个定时器的工作重新启动服务器，如果你有有限的访问您的服务器重新启动。

**Comment by pgz123** [comment]
怎么样把飞马加进去

**Comment by somebird** [comment]
jasonli兄，好久不见了，请教一下，搬瓦工Debian 6.0 x86 用ss-r版，如何使用胡须遂道？

**Comment by jasonliul** [comment]
@somebird 这个不大方便, 还是等木偶.

**Comment by somebird** [comment]
@jasonliul 好的，非常感谢，顺便问一下木偶是啥？

**Comment by jasonliul** [comment]
搬家
https://github.com/BarbaTunnelCoder/BarbaTunnel/

给折腾党, 免费平台不知道能否搭建胡须服务器?

**Comment by kirbyzhu** [comment]
服务端要安装是硬伤啊
