### ISSUE TITLE
Stunnel 5.41 / Simurgh 复活

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#273]
Https隧道, 申请免费帐号

Puff 大大
https://puffstore.com/squid/test.php

主页
https://www.stunnel.org/index.html

下载
https://www.stunnel.org/downloads/stunnel-5.26-installer.exe

Stunnel不需要安装, 直接解压
先到config目录修改stunnel.conf

添加
[https]
client = yes
accept = 127.0.0.1:xxxx[随便你, 不与其他软件冲突就行]
connect = 服务器:443

设置浏览器
Http  localhost:xxxx
Ssl    localhost:xxxx

运行bin下面的stunnel.exe, 检查Show log windows, 显示正常.
OK喇, 该去哪去哪.

**Comment by TonnyTonny** [comment]
感謝分享

**Comment by rongwutw** [comment]
请问楼主 ,stunnel-5.26-installer.exe 如何直接解压 ?

**Comment by jasonliul** [comment]
Universal Extractor, 或者7-zip

**Comment by yeahwu** [comment]
我是来感谢楼主的，我的大火狐终于用上了，另外最后一步设置浏览器，可通过插件aotuproxy调用。
http  localhost：xxxx

**Comment by jasonliul** [comment]
@yeahwu 10月份我的乌克兰乌贼Squid欠费停机.
Puff这个来得正好. :)

**Comment by rongwutw** [comment]
请问楼主 ,
Chrome ，在那里可以
设置浏览器
Http localhost:xxxx
Ssl localhost:xxxx

**Comment by toobed** [comment]
同问

**Comment by caofengzi** [comment]
楼主能否把用户名，密码添加进stunnel.conf文件里面，这样如果能够可行就不用每次都输入密码了。

**Comment by jasonliul** [comment]
@caofengzi 浏览器不都有密码管理器?
你可以试试
connect = http://user:password@服务器:443

**Comment by jasonliul** [comment]
Stunnel 5.41
https://www.stunnel.org/downloads/stunnel-5.41-win32-installer.exe

Puff 大大的节点复活

另外,

**Comment by kirbyzhu** [comment]
非常好用，可以和社长的vps联系起来用。感谢J大！

**Comment by wpyok500** [comment]
mark

**Comment by kirbyzhu** [comment]
在puff里面申请了一个免费的试用

HTTPS PROXY
*******************************************
server: sfo.sandcity.club
port: 443
username: hs44172989
password: bcc53f
*******************************************
Valid untill: 2017-06-13 17:28:53

但是不管是在chrome里面用switchyomega设置，还是使用stunnel客户端 都无法链接 不知道是因为干扰还是因为设置问题 放出来给大家测试一下
chrome无法弹出用户名密码对话框 stunnel里面设置了但是会提示Error resolving "https://hs44172989:bcc53f@sfo.sandcity.club": Non-recoverable failure in name resolution (EAI_FAIL)

另外 stunnel可以使用在arukas、Openshift和heroku上部署的goproxy-vps,gost(http模式)nghttpx-tinyproxy等。速度飞快

**Comment by jasonliul** [comment]
failure in name resolution

域名污染
72.52.124.133 sfo.sandcity.club
加入hosts文件

**Comment by kirbyzhu** [comment]
谢谢J大指点

**Comment by jasonliul** [comment]
@kirbyzhu 
有木有人分享过tinyproxy节点?

**Comment by kirbyzhu** [comment]
@jasonliul 没 不过我用wangyi2005的镜像nghttpx-tinyproxy 分别在openshift和arukas上部署了 
都可以作为stunnel的服务器使用

**Comment by jasonliul** [comment]
**twfcc** 大大是stunnel的真玩家
https://twitter.com/twfcc?lang=en
https://victor-notes.blogspot.hk/
https://github.com/twfcc

之前有发现U网的ip, 也支持stunnel.
其实现在也一样, 不过你得加挂袜子.

**Comment by jasonliul** [comment]
![screenshot 1](https://user-images.githubusercontent.com/2461165/27015543-5fed54ac-4f42-11e7-9600-31b132feec98.jpg)
example
[https]
client = yes
accept = 127.0.0.1:1989
connect = 112.105.74.36:443
;connect = dt.nacgroup.com.au:443

**Comment by jasonliul** [comment]
connect = 175.181.114.60:443
;connect = 36.226.0.81:443
;connect = 118.170.138.125:443

刚刚去李大师那里捞的..........

**Comment by jasonliul** [comment]
112.105.220.107:443
112.105.74.4:443
61.227.3.173:443

老李的香油ip, 显示Freegate的ip地址, 大约13M带宽~

![screenshot 1](https://user-images.githubusercontent.com/2461165/27344814-3abd7b24-561a-11e7-8da7-0c6d825ea806.jpg)

**Comment by AndyLau2017** [comment]
好像这东东是别人用VPS搭建的啊？
