### ISSUE TITLE
Streisand 土耳其全能VPS方案

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#274]
Streisand sets up a new server running L2TP/IPsec, OpenSSH, OpenVPN, Shadowsocks, sslh, Stunnel, and a Tor bridge. It also generates custom configuration instructions for all of these services. At the end of the run you are given an HTML file with instructions that can be shared with friends, family members, and fellow activists. 

新墙友土耳其高手的反审查软件套组, 支持Shadowsocks, SSH, HTTPS等
是傻瓜式VPS配布脚本, 而且同时生成客户端配置文件.
菜鸟玩VPS必备的大炮.

介绍
http://www.makeuseof.com/tag/fighting-censorship-streisand-secure-server/

项目
https://github.com/jlund/streisand

作者主页
https://missingm.co/

讨论
https://news.ycombinator.com/item?id=8082444

**Comment by cdseoo** [comment]
之前玩过一回史翠珊~

**Comment by lxok89** [comment]
翻墙只需一种，无需太多手段。精一方式即可。

**Comment by sundaqing1969** [comment]
楼上不要打击知识分享的热情！

**Comment by jasonliul** [comment]
@cdseoo 
像puff那种https代理, 自己很容易搭建. 而且不担心被墙
