### ISSUE TITLE
俄国超网 SuperNET VPN

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#276]
主页
https://supernet.io/

目前只支持谷歌,火狐插件, 以及安卓

苹果, PC版本会稍迟

完全免费无限制, 不过有一点广告

提意见
https://supernet.io/
https://www.facebook.com/supernet.io

**Comment by hijklmn** [comment]
为什么只有在“You are not secured”状态下可以正常使用？

**Comment by pgz123** [comment]
不能用、无法连接

**Comment by jzp820927** [comment]
我也测试不能用！

**Comment by jasonliul** [comment]
https://supernethelp.zendesk.com/hc/en-us/requests/new
https://www.facebook.com/supernet.io

VPN协议, VPN节点位置, 作者正在征求意见.
