### ISSUE TITLE
可以用官方的go编译了

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#280]
@phuslu [cloudflare](https://github.com/cloudflare/go)的改进都已经加到go官方trunk了
https://github.com/cloudflare/go/issues/12

**Comment by ren2014311** [comment]
能发个编译好的goproxy vps版吗？

**Comment by Lrevor** [comment]
@ren2014311 https://github.com/phuslu/goproxy/releases
https://github.com/phuslu/goproxy/releases/download/goproxy/govps_linux_amd64-r169.tar.bz2

**Comment by ren2014311** [comment]
@Lrevor 这个我知道，是官方发布的169版本，又有修改没有发布的，得自己编译。

**Comment by jasonliul** [comment]
@ren2014311 卢社长抛弃我们咧, 天天只在洋妞身上勇攀乳峰. :(
