### ISSUE TITLE
GranGorz 高兹大人[高兹--暗黑使者]复活

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#281]
作者已经充值一个节点, 37.x.x.x, 而且现在用户少, 是满速的. 连接时需要多试几次, 因为其他5个节点都废了

主页
https://grangorz.org/download
https://www.facebook.com/theGranGorz

Old soldiers never die, they just fade away.
老兵不死，只是凋零。

**Comment by rongwutw** [comment]
试了多次，始终无法连上

**Comment by jzp820927** [comment]
同楼上！

**Comment by jasonliul** [comment]
可能是节点被封, 
应该加入帽子族了
