### ISSUE TITLE
新工具:CacheBrowser

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#291]
https://www.cachebrowser.info/
https://github.com/CacheBrowser/cachebrowser
CacheBrowser has been designed and developed by the SPIN research group at UMass Amherst.

**Comment by jasonliul** [comment]
马萨诸塞大学的新玩具, 
我不大喜欢插件类型.

**Comment by zaang** [comment]
请问chrome的插件怎么安装呢？
下载下来的zip直接改后缀好像不行，在设置中用开发者模式加载已解压的扩展程序也不行。

**Comment by johnsonz** [comment]
Unlike regular circumvention systems, CacheBrowser is not a generic circumvention system: it can only browse censored pages that are

Hosted on a shared CDN (such as Akamai, Fastly, CloudFlare, etc.)
Support HTTPS

**Comment by xxnet** [comment]
刚看了，是python 写的，明天研读一下源码

2015-11-24 17:14 GMT+08:00 johnsonz <notifications@github.com>:

**Comment by yeahwu** [comment]
@zaang 下载后解压，然后进入chrome设置，扩展程序，加载已解压的扩展程序，完事。

**Comment by jdfq** [comment]
怎么用啊？
