### ISSUE TITLE
IP 牙祭

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#292]
编辑掉

**Comment by jasonliul** [comment]
203.233.126.197
203.133.72.41

**Comment by jasonliul** [comment]
58.123.102.74
203.233.126.197

178.45.251.82|178.45.251.116|178.45.251.117|178.45.251.115

这次来个奶水多的
103.11.28.15|103.11.28.22|103.11.28.34|103.11.28.25|103.11.28.4|103.11.28.45|103.11.28.16|103.11.28.32|103.11.28.44|103.11.28.47|103.11.28.39|103.11.28.51|103.11.28.19|103.11.28.87|103.11.28.5|103.11.28.88|103.11.28.93|103.11.28.79|103.11.28.76|103.11.28.94|103.11.28.14|103.11.28.48|103.11.28.102|103.11.28.101|103.11.28.23|103.11.28.92|103.11.28.105|103.11.28.69|103.11.28.68|103.11.28.86|103.11.28.91|103.11.28.43|103.11.28.58|103.11.28.83|103.11.28.104|103.11.28.112|103.11.28.33|103.11.28.98|103.11.28.113|103.11.28.56|103.11.28.106|103.11.28.97|103.11.28.123|103.11.28.118|103.11.28.117|103.11.28.110|103.11.28.121|103.11.28.120|103.11.28.108|103.11.28.115|103.11.28.133|103.11.28.143|103.11.28.144|103.11.28.145|103.11.28.149|103.11.28.147|103.11.28.109|103.11.28.160|103.11.28.151|103.11.28.164|103.11.28.162|103.11.28.134|103.11.28.157|103.11.28.152|103.11.28.173|103.11.28.169|103.11.28.175|103.11.28.179|103.11.28.186|103.11.28.156|103.11.28.181|103.11.28.185|103.11.28.158|103.11.28.177|103.11.28.187|103.11.28.166|103.11.28.184|103.11.28.167|103.11.28.155|103.11.28.216|103.11.28.207|103.11.28.228|103.11.28.219|103.11.28.183|103.11.28.204|103.11.28.172|103.11.28.150|103.11.28.221|103.11.28.210|103.11.28.222|103.11.28.211|103.11.28.224|103.11.28.235|103.11.28.231|103.11.28.230|103.11.28.226|103.11.28.239|103.11.28.176|103.11.28.249|103.11.28.170|103.11.28.236|103.11.28.205|103.11.28.215|103.11.28.248|103.11.28.244|103.11.28.208|103.11.28.241|103.11.28.234|103.11.28.251|103.11.28.246|103.11.28.245|103.11.28.242

**Comment by jasonliul** [comment]
117.102.117.0/24

**Comment by jasonliul** [comment]
118.98.111.75,118.98.111.68,118.98.111.132,118.98.111.135,118.98.111.139
118.98.106.71,118.98.106.132,118.98.106.133,118.98.106.197,118.98.106.200,118.98.106.201
118.98.110.137
118.98.30.73
118.98.76.68
203.133.72.41
58.123.102.74
45.64.20.136,
202.78.113.101

**Comment by jasonliul** [comment]
203.133.72.41|203.133.72.43|203.233.126.197

**Comment by jasonliul** [comment]
103.11.30.4|103.11.30.56|103.11.30.50|103.11.30.12

118.98.111.68|118.98.111.75|118.98.111.139|118.98.111.135|118.98.111.132

210.187.25.198|1.9.24.5

**Comment by xyuanmu** [comment]
虽然延时有点高不过还是很不错的

**Comment by jasonliul** [comment]
@xyuanmu 关键是长字段, 一个字段居然有这么多.
过了几个月,这是第一回

**Comment by xyuanmu** [comment]
@jasonliul 嗯，目前我就用着某些长字段的IP，尤其是那个103打头的，有100多个，估计是觉得封大量IP段不实际，只把高速的封了。

**Comment by jasonliul** [comment]
103那个我这里不能用.

确实主要是封亚洲,但是一旦开始限速, 下午4点到凌晨1点. ping值会增加70,80ms或更多, 外带高丢包率.
欧美的字段就很难用了.

**Comment by jasonliul** [comment]
103.11.28.14|103.11.28.16|103.11.28.19|103.11.28.23|103.11.28.25|103.11.28.34|103.11.28.39|103.11.28.32|103.11.28.33|103.11.28.68|103.11.28.86|103.11.28.87|103.11.28.48|103.11.28.76|103.11.28.109|103.11.28.110|103.11.28.108|103.11.28.112|103.11.28.69|103.11.28.114|103.11.28.121|103.11.28.120|103.11.28.134|103.11.28.143|103.11.28.145|103.11.28.149|103.11.28.156|103.11.28.157|103.11.28.169|103.11.28.173|103.11.28.118|103.11.28.179|103.11.28.183|103.11.28.186|103.11.28.205|103.11.28.215|103.11.28.207|103.11.28.219|103.11.28.226|103.11.28.236|103.11.28.241|103.11.28.242|103.11.28.248|103.11.28.204|103.11.28.231

印尼经典

**Comment by xyuanmu** [comment]
上次我说有100多的就是这个，貌似我这边扫到的多一些：
103.11.28.4|103.11.28.5|103.11.28.13|103.11.28.14|103.11.28.15|103.11.28.16|103.11.28.19|103.11.28.22|103.11.28.23|103.11.28.25|103.11.28.32|103.11.28.33|103.11.28.34|103.11.28.39|103.11.28.43|103.11.28.44|103.11.28.45|103.11.28.47|103.11.28.48|103.11.28.51|103.11.28.56|103.11.28.58|103.11.28.68|103.11.28.69|103.11.28.76|103.11.28.79|103.11.28.83|103.11.28.86|103.11.28.87|103.11.28.88|103.11.28.91|103.11.28.92|103.11.28.93|103.11.28.94|103.11.28.97|103.11.28.98|103.11.28.101|103.11.28.102|103.11.28.104|103.11.28.105|103.11.28.106|103.11.28.108|103.11.28.109|103.11.28.110|103.11.28.112|103.11.28.113|103.11.28.114|103.11.28.115|103.11.28.117|103.11.28.118|103.11.28.120|103.11.28.121|103.11.28.123|103.11.28.133|103.11.28.134|103.11.28.143|103.11.28.144|103.11.28.145|103.11.28.147|103.11.28.149|103.11.28.150|103.11.28.151|103.11.28.152|103.11.28.155|103.11.28.156|103.11.28.157|103.11.28.158|103.11.28.160|103.11.28.162|103.11.28.164|103.11.28.166|103.11.28.167|103.11.28.169|103.11.28.170|103.11.28.172|103.11.28.173|103.11.28.175|103.11.28.176|103.11.28.177|103.11.28.179|103.11.28.181|103.11.28.183|103.11.28.184|103.11.28.185|103.11.28.186|103.11.28.187|103.11.28.197|103.11.28.204|103.11.28.205|103.11.28.207|103.11.28.208|103.11.28.210|103.11.28.211|103.11.28.215|103.11.28.216|103.11.28.219|103.11.28.221|103.11.28.222|103.11.28.224|103.11.28.226|103.11.28.228|103.11.28.230|103.11.28.231|103.11.28.234|103.11.28.235|103.11.28.236|103.11.28.237|103.11.28.239|103.11.28.241|103.11.28.242|103.11.28.244|103.11.28.245|103.11.28.246|103.11.28.248|103.11.28.249|103.11.28.251

**Comment by jasonliul** [comment]
@xyuanmu 我这里很长时间不能用.
检测没有问题,运行就不时变成bad ip.

**Comment by jasonliul** [comment]
66.96.224.198,66.96.224.205,66.96.224.222,66.96.224.227,66.96.224.228,66.96.224.231
