### ISSUE TITLE
不错的全球DNS

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#293]
http://www.bestdns.org/

这个是精选版, 基本是ISP提供商的DNS.
可以用作缓存DNS工具.

**Comment by xxnet** [comment]
不错，收藏了。

可以做个工具，解析各DNS 服务返回的ip，然后看能否直连，能直连的就直连，
配合白名单之类的，可以替代hosts。

最后都不行再走代理，可以实现PAC更好的效果。

在 2015年11月23日 上午10:14，Jason Liu <notifications@github.com>写道：

**Comment by jasonliul** [comment]
@xxnet 
现在没人去摸奖Google ip咧, 不过要摸的话, 这个成功率会高得多.
因为没有收录私架的DNS, 那些都是照搬别家的数据

**Comment by ARwMq9b6** [comment]
发丝露! 俺的精神支柱。如今俺也成为了一名程序员。

**Comment by xxnet** [comment]
之前有想过用Tor去解析ip，这样可以去解析各个国家地区的ip，应该会有不同。
不过发现Tor太复杂了，要搞稳定工程太大，不如自己架设一个域名解析来得轻松。

以后在墙外自己架设一个域名解析的服务器，把可能的ip结果用http返回回来，墙内再逐个ip尝试连接。
借gae 代理去访问这个域名解析，就不怕域名服务器被封了。

2015-11-23 12:21 GMT+08:00 ARwMq9b6 <notifications@github.com>:

**Comment by fengixng** [comment]
http://public-dns.tk/
秒杀你提供的网站

**Comment by xxnet** [comment]
这个厉害，继续收藏

2015-11-25 3:12 GMT+08:00 fengixng <notifications@github.com>:

**Comment by fengixng** [comment]
@xxnet 如果想要远程解析的话，dig命令就可以，可以模拟远程的IP解析DNS

**Comment by xxnet** [comment]
dig 还是用DNS协议吧，这种太容易过滤了

2015-11-25 19:03 GMT+08:00 fengixng <notifications@github.com>:

**Comment by fengixng** [comment]
@xxnet 亲测用dig+8.8.8.8使用远程解析，已经分析出全球绝大部分的IsP的GGC。当然某些ggc数量巨大的国家我并没有扫出来全部，毕竟IP太多了，抽查毕竟会有漏的

**Comment by xxnet** [comment]
DNS解析协议可以自己写代码发UDP包，goagent原来的代码里有，如果使用这全球DNS服务器，应该可以做到解析IP。
GFW其实也不好封杀全部的DNS服务器和通信，目前是采用污染和假冒的方式，暂时可以解决的。

在 2015年11月26日 下午7:15，fengixng <notifications@github.com>写道：
