### ISSUE TITLE
印尼墙友免费SSH

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#298]
https://fastssh.com/
http://create.sshgoogle.com/
http://www.mytunneling.com/ssh-server-new
https://white-vps.com/
https://www.highssh.com/
http://go-ssh.com/sshserver/ssh-server.html
http://godssh.com/
http://www.sshagan.net/
http://skyssh.com/

近来欧洲节点比较少

**Comment by xyuanmu** [comment]
其实现在xx-net已经相当稳定了，不折腾其他的工具
![y2blive](https://cloud.githubusercontent.com/assets/12442896/11583287/eaff27c0-9a92-11e5-9ac4-4b9aca3134ea.png)

**Comment by jasonliul** [comment]
@xyuanmu 黄狗也一样, 

我换了新装备. 可以在线获取指定国家100个DNS解析结果, 再从中摸奖
现在有7个好字段, 勉强恢复三妻四妾的小康.

**Comment by xyuanmu** [comment]
现在坚持遛狗的人应该不是很多了，用xx-net后懒了许多也不怎么找IP，不过还是挑优秀的IP段来用:smile:

**Comment by xxnet** [comment]
自动化让人变懒，去年这个时候还是各种找ip，经常发现各种神奇的方式，现在都没有了，只能自己摸索。

找100个国家各种dns解析，还是非常有前途的，实现得好可以做到去年hosts的效果。

在 2015年12月4日 下午10:48，xyuanmu <notifications@github.com>写道：

**Comment by jasonliul** [comment]
@CNMan 大大什么时候再放出一些收藏品? :)

@xyuanmu @xxnet 
其实我最多试过一次获取300个DNS服务器的结果, 但是也是验证CNMan大大的结果, 现在DNS基本出来的都是官方字段, 主要国家都是, 三四流国家勉强还有非官段.

有不少零星可用节点, 俄国最多.但是浮动性很大, 时有时无. 
因此xxnet 大大的叉烧狗, 基本就是唯一的遛狗方式了.

没有摸奖的乐趣, 我都很少遛狗.

越南墙友搞了个小程序, 快速检查SSH可用性. 不过列表就得去黑客社区自己寻找.
这样可以使用很多完全免费, 免注册的ssh. 只是不大可能大众化.

**Comment by xxnet** [comment]
你DNS获取是在墙内跑还是在墙外跑？

总觉得墙真要封墙外DNS是不难的，不过目前还没有，猜测原因有2个：
上传检测是旁路的方式：
   所有包都检查再放行的话，墙的负担和延迟都太高了。

下传阻断，似乎目前并没有做，估计也是成本太高。

像DNS这种请求，因为是旁路检测，所以上传是来不及阻止的。
下传是没有阻断机制（从现象猜测），所以只能污染。

至于完全封ip，影响太大，不知道哪些正常业务就被影响了.

当然这些只是实现上的限制，哪天墙疯了，来个全过滤处理的话，就难说了。
不过全过滤也无法解决目前主流的翻墙工具，所以从性价比上看，目前的策略是最好的。

纯属娱乐猜测。

在 2015年12月5日 上午10:56，Jason Liu <notifications@github.com>写道：

**Comment by CNMan** [comment]
@jasonliul 存货大部分都已经放出来了，10月份以后也没再发掘新IP段，而且现在可用IP还很多啊，就不更新了

**Comment by jasonliul** [comment]
@xxnet 当然是外面的网站服务

**Comment by linhua55** [comment]
@xxnet
主要是没有轻简的论坛。用GAE做“P2P”论坛怎么样？主GAE只做查询（空闲GAE）、协调、跳转（到空闲GAE），提供负载均衡，由其它GAE提供服务。

**Comment by xxnet** [comment]
p2p 去中心化，最好是没有主和控制概念，论坛这种形式不适合p2p吧，失去控制的论坛就太乱了。
去控制的社区最好是twitter，p2p的是twister，不需要担心失控，不好的内容不follow就好了。

如果GAE作为twister的辅助，那么可靠性和体验会好很多。

在 2015年12月6日 上午12:01，linhua55 <notifications@github.com>写道：
