### ISSUE TITLE
CyberGhost VPN 5 圣诞特惠 1年免费

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#300]
CyberGhost VPN 5 圣诞特惠 1年免费

申请注册码
http://www.cyberghostvpn.com/de_de/campaign/chip_christmas_2015

下载
http://www.chip.de/downloads/CyberGhost-VPN-5-Special-Edition_84137913.html?ref=adventskalender

手快者得

**Comment by yeahwu** [comment]
过期了？
