### ISSUE TITLE
科学上网第一步：DNS 国内、国外分流解析/抗污染、抗劫持/屏蔽广告、恶意软件

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#302]
https://github.com/CNMan/unbound.conf

unbound.forward-zone.China.conf 中的114.114.114.114和223.5.5.5可以用你的运营商DNS替换
unbound.local-zone.hosts.conf 中的216.58.221.17可以用你的高速Google IP替换

欢迎使用，有问题请反馈:)

goagent的ini中也可以用

```
[dns]
servers = 127.0.0.1
```

**Comment by xxnet** [comment]
想整一个python的版本到xx-net里，包括域名解析、直连，还有cachebrowser 的技术

2015-12-09 0:10 GMT+08:00 CNMan <notifications@github.com>:

**Comment by Chu2koi** [comment]
现在这类工具好多，比如pcap_dnsproxy，这个还受到dnscrypt的推荐；还有dnsforwarder，不过这个不支持加密就是了，支持tcp查询

**Comment by wenliyang** [comment]
在用pcap_dnsproxy，作者是国人，更新比较勤快

**Comment by xxnet** [comment]
恩，找时间体验下效果

2015-12-09 17:12 GMT+08:00 wenliyang <notifications@github.com>:
