### ISSUE TITLE
号外:纸飞机加入帽子党

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#309]
https://github.com/breakwa11/shadowsocks-csharp/releases/
换这个就方便一点.

直连缓慢已经有段时间了, 电信.

**Comment by TonnyTonny** [comment]
謝分享

**Comment by Chu2koi** [comment]
我这边电信也是，日了狗了，只能再加个国内中转

**Comment by lg560852** [comment]
这玩意出现好久了，而且作者更新很勤

**Comment by jasonliul** [comment]
@Chu2koi 看起来是针对某些VPS提供商的, 印尼人的免费SSH节点跟SS接近.一道死翘翘.

**Comment by jasonliul** [comment]
这厮的版本, 对去广告软件很不友好.
还不如官版

**Comment by yeahwu** [comment]
@jasonliul 明白人。

**Comment by breakwa11** [comment]
@jasonliul 去广告软件？指哪些？

**Comment by lg560852** [comment]
基于浏览器的去广告插件未发现异常，我用ublock和ublock origin。
估计jasonliul童鞋说的是阿呆喵或者奶牛之类全局过滤的软件吧，之前用过这些，后来发现跟迅雷有冲突，而且资源占用，还是ublock更少，就换了。未测试SSR是否与这两款软件有冲突。

**Comment by breakwa11** [comment]
ublock肯定是没有问题的，我自己也用的这个。而且不管是SSR还是原SS，都没有针对广告过滤软件做任何处理，行为是应该完全一样的
