### ISSUE TITLE
FQ大大搜寻的纸飞机 三木

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#314]
www.godie.info
邀请码 3252

目前表现还行.

免费只有星岛2, 美国1.

**Comment by yeahwu** [comment]
pro节点可以用，提醒一下。

**Comment by jzp820927** [comment]
初始流量 10G 到是还不错，就是签到流量太少了，我昨天签到才 22MB。

**Comment by jasonliul** [comment]
@yeahwu 不懂, 先吃再买单?

**Comment by jasonliul** [comment]
@jzp820927 无所谓, 很多签到换流量, 就意味着某天跑路.
这个初始流量还不错.

**Comment by yeahwu** [comment]
@jasonliul 哈哈，那个页面连个买单的按钮都没有，能吃就行。

**Comment by jasonliul** [comment]
@yeahwu 印尼的SSH基本都是免费, 最多网赚, 下载配置文件时有广告.
赞助少的时候, 节点就少. 那是真正的公益.

国内的纸飞机, 邀请, 注册, 签到, Q群, 微信, G组....
比讨个黏糊的老婆还麻烦. :)

不过我基本是用冰河纪的SSH.

**Comment by jzp820927** [comment]
冰河纪的SSH？是神马SSH？

**Comment by jasonliul** [comment]
@jzp820927 中国基本不用FTP方式, 但是满世界都用.
提供FTP服务的网站,论坛, 基本都提供免费SSH, 因为是保证文件传输安全目的, 带宽速度通常都不错.

就算依据协议, 也没有谁限制这些ssh做别的用途, 因此下九流网民, 墙友们就凑合.

**Comment by yeahwu** [comment]
@jasonliul  兄弟果然淫才呀！
>国内的纸飞机, 邀请, 注册, 签到, Q群, 微信, G组....
比讨个黏糊的老婆还麻烦. :)

**Comment by jzp820927** [comment]
说的还是挺有代理，老外的免费都是 纯粹的免费，公益性的，国内的，不是要注册码，就是要邀请人，把人整点累死，还不一定能用到。

**Comment by jasonliul** [comment]
@jzp820927 我基本就是玩纸飞机, 签到的流量从来用不了, 
结果却是商家跑路了.

**Comment by jzp820927** [comment]
还是自己有个 VPS 比较靠谱
