### ISSUE TITLE
德国 ZenMate VPN Premium 免费3个月

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#316]
https://zenmate.com/promotion/share/?utm_source=crm&utm_medium=de12m&utm_campaign=%5BC%7CALL_en%5D12mchristmas&utm_term=cta&utm_content=massmail

手快者得

**Comment by yeahwu** [comment]
抢到鸟，谢谢

**Comment by jzp820927** [comment]
We're sorry, something went wrong. Please try again later

提示这个，不晓得啥原因！

**Comment by jasonliul** [comment]
@jzp820927 已经过了时效

**Comment by jasonliul** [comment]
@jzp820927 特惠依然有效, 再试

**Comment by jzp820927** [comment]
@jasonliul 谢谢，第二天已经拿到码了，估计是第一天注册的人太多，服务器繁忙导致！

**Comment by bygloam** [comment]
Thanks

**Comment by cundi** [comment]
多谢分享，圣诞节走运啊，拿了半年，Your ZenMate Premium will expire on July 1, 2016.

**Comment by jasonliul** [comment]
https://zenmate.com/promotion/share/?utm_source=crm&utm_medium=de12m&utm_campaign=%5BC%7CALL_en%5D12mchristmas&utm_term=cta&utm_content=massmail

再次特惠~~

**Comment by jzp820927** [comment]
之前领过的，还可以继续领么？

**Comment by jzp820927** [comment]
Your ZenMate Premium will expire on June 27, 2016.
说话，好像是生效了？
