### ISSUE TITLE
圣诞黄狗狂奔

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#319]
黄狗终于回来了, 比对叉烧狗搜罗的字段, 
俺还有5个没曝光的, 可以放心鸟.

现在的字段不稳定, 不时闪回bad ip.
不过旧论坛, 有达人提出用谷歌中国字段, 作为伪军协从.

这个方法还能用, 而且下载速度提升. 韩日菲澳都有>300kb/s

http://i081.radikal.ru/1512/84/fc002f5739fa.png

**Comment by cnshinchan** [comment]
怎样用谷歌中国字段, 作为伪军协？

**Comment by jzp820927** [comment]
我也想问这个问题，难道中国IP段，也可以用于GAE？

**Comment by jasonliul** [comment]
设置google_cn = 自选ip.
我发现连号的只需要4个, 但是不连号的...不知道, 总说列表太短.

启动Goagent, 先连接HK设定的ip, 打开github, 中国谷歌会很快加入, 原因我也不明白.

这个用法我之前试过, 没有特别之处. 不过近期总能启动"影子ip". 真正快的原因是这个.

Cn我加入4个, HK加3个, 打开界面, 好ip却是8个. 多的那个就是影子ip.
如果当前服务器表现不佳, 谷歌会用其他的协助处理用户请求. 之前总是时有时无.

现在加入谷歌中国, 基本总是有影子ip, 所以我这里去到4300kpps, 之前通常是2000多.

**Comment by jzp820927** [comment]
第一次听说这么高级的黑科技，你说的“不过旧论坛, 有达人提出用谷歌中国字段, 作为伪军协从.”，中的"旧论坛"是指对，google code 的 goagent issues 吗？这个我以前天天都看，没看到过有讲这个的帖子。

**Comment by jasonliul** [comment]
@jzp820927 我也搜了一下, 不是主贴, 是相互讨论时提到的.
而且连号只需要4个, 那是俺的版权.

好想把撸帮主揪出来暴打.

**Comment by jzp820927** [comment]
好吧，既然找不到原贴了，就不深究了，有时间测试一下，看看效果怎么样，谢谢！

**Comment by jasonliul** [comment]
@jzp820927 对.

**Comment by jzp820927** [comment]
知道了，谢谢！

**Comment by xyuanmu** [comment]
只要合理设置，1080P直播完全无压力，大家可以试试：https://www.youtube.com/watch?v=XxJKnDLYZz4
![qq](https://cloud.githubusercontent.com/assets/12442896/12000755/4c470004-ab17-11e5-9e20-d3d6c22709c3.jpg)

**Comment by jasonliul** [comment]
@xyuanmu 俺的意思是黄狗进化藏獒, 稳保3000kbps, >300kb/s下载.

**Comment by lsnmx** [comment]
@xyuanmu 逛扫了一个月，43* 1000W ip，还是有不少好IP的

**Comment by xyuanmu** [comment]
@lsnmx 看来收获不浅啊，现在用着xx-net本着够用就行一直都没去找新的IP段。

**Comment by lsnmx** [comment]
43* 1000W ip已经覆盖了亚洲90%IP了，我看了一下真没多少能用的了。1000W ip扫出来的也就10到20个理想点的IP

**Comment by lsnmx** [comment]
@xyuanmu

**Comment by xyuanmu** [comment]
也许是你线程开的比较大所以漏掉了些，我一般是开100线程扫完一个IP段，然后就将扫出的IP所在IP段用50或者30线程再扫一遍。
这份就是前段时间整理的：[ip_range.txt](https://gist.githubusercontent.com/xyuanmu/80cbe8bbb9f926f10889/raw/ip_range.txt)

**Comment by jasonliul** [comment]
@lsnmx 差不多, 我直接从几百个某国dns记录里面,选择眼生的用摸摸脚本,
得到的基本都是零散残兵

**Comment by blob2015** [comment]
只能说，很强大

**Comment by blob2015** [comment]
@xyuanmu 看了一眼老兄的ip_range.txt，里面有216。现在216又可以了？

**Comment by xyuanmu** [comment]
@blob2015 216有问题的是这两段：
216.58.196.0/24
216.58.208.0/20

**Comment by LGA1150** [comment]
@xyuanmu 
补充： 216.239.32.0/19

**Comment by xyuanmu** [comment]
@LGA1150 OK

**Comment by blob2015** [comment]
谢谢 @xyuanmu @LGA1150
---------------
提到了GVS的速度波动，其实响应速度也是波动挺大的，so，如果一个波段里面，某个看着特别慢，甚至7000/8000，但是如果有其他较好的同波段，也不妨暂时收着。
---------------
插问：现在电信的IP还是比较难搞？

**Comment by jasonliul** [comment]
@blob2015 
GVS和GWS不同, GVS属于当前热门服务, 
我这里选择的字段, 很多属于临时字段, 属于GVS备胎.

本质上, GVS是封不完的, 因为它是按需添加

**Comment by blob2015** [comment]
@jasonliul 
电信太tmd变态了，怪不得老是转圈圈
谢谢解惑
