### ISSUE TITLE
IP 摸摸乐, <300MS, 探索与发现

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#320]
del

**Comment by ncmon** [comment]
楼主GVS的IP能用什么工具测速吗

**Comment by jasonliul** [comment]
@ncmon GVS浮动性很大, 测速没有价值.

**Comment by jasonliul** [comment]
92.46.70.57,92.46.70.10,92.46.70.5,92.46.70.12,92.46.70.27,92.46.70.32,92.46.70.40,92.46.70.34,92.46.70.52,92.46.70.45,92.46.70.26,92.46.70.6,92.46.70.4,92.46.70.7,92.46.70.9,92.46.70.8,92.46.70.11,92.46.70.16,92.46.70.13,92.46.70.15,92.46.70.20,92.46.70.19,92.46.70.23,92.46.70.22,92.46.70.21,92.46.70.25,92.46.70.31,92.46.70.28,92.46.70.30,92.46.70.18,92.46.70.35,92.46.70.36,92.46.70.17,92.46.70.37,92.46.70.38,92.46.70.43,92.46.70.33,92.46.70.42,92.46.70.46,92.46.70.50,92.46.70.48,92.46.70.39,92.46.70.58,92.46.70.51,92.46.70.56,92.46.70.53,92.46.70.59,92.46.70.54,92.46.70.47,92.46.70.41

**Comment by xyuanmu** [comment]
大财主，看来是攒了不少好IP开始散货了。

**Comment by lsnmx** [comment]
@jasonliul @xyuanmu 现在不好扫啊，我扫了一个月了

**Comment by jasonliul** [comment]
@lsnmx 我比较过强扫的效率, 还不如我现在的投机摸奖.

我现在有国外论坛的应用, 一次可以直接获得指定国家200个左右dns, 部分dig记录.
然后买菜一样, 找眼生的收集, 让摸摸脚本自己工作.

可惜论坛的dns记录很旧而且不全面.

**Comment by jasonliul** [comment]
58.176.217.5
42.112.8.74

203.133.72.41|203.133.72.43

114.4.4.223|114.4.4.230|114.4.4.214|114.4.4.226|114.4.4.228|114.4.4.235|114.4.4.237|114.4.4.242|114.4.4.241|114.4.4.240|114.4.4.239|114.4.4.236|114.4.4.234|114.4.4.238|114.4.4.243|114.4.4.244|114.4.4.248|114.4.4.227|114.4.4.250|114.4.4.231|114.4.4.246|114.4.4.249|114.4.4.232|114.4.4.251|114.4.4.245|114.4.4.247

58.69.77.86|58.69.77.90|58.69.77.93|58.69.77.89|58.69.77.92|58.69.77.83|58.69.77.82|58.69.77.91|58.69.77.85|58.69.77.76

黄金越南
42.112.10.68|42.112.10.88|42.112.10.81|42.112.10.155|42.112.10.132|42.112.10.144|42.112.10.133|42.112.10.141|42.112.10.149|42.112.10.134|42.112.10.137|42.112.10.146|42.112.10.148|42.112.10.152|42.112.10.209|42.112.10.204|42.112.10.210|42.112.10.198|42.112.10.197|42.112.10.205|42.112.10.208|42.112.10.214|42.112.10.212|42.112.10.199|42.112.10.201

**Comment by ARwMq9b6** [comment]
摸了这么多好狗仔。

**Comment by jasonliul** [comment]
66.96.224.0/24
110.50.81.0/24
58.69.77.0/24
203.211.8.0/24
103.11.28.0/24
103.11.30.0/24
59.18.49.0/24
45.64.20.0/24
42.112.10.0/24

较好的字段

**Comment by xyuanmu** [comment]
收获极好IP段一枚，加上手头两段，怎一个溜字了得。
![y2b](https://cloud.githubusercontent.com/assets/12442896/12013232/405e028c-ad4d-11e5-915c-8ddca93c42e2.png)

**Comment by lsnmx** [comment]
@jasonliul 不折腾了，现在直接强扫，反正PC24小时开机

**Comment by jasonliul** [comment]
@xyuanmu 叉烧狗还是方便, 很多浮动零散的ip都能用.
越南这段, 我用原版得加hosts, 表现不比当年的香港ip差. 如果直接用, 容易失联.

**Comment by jasonliul** [comment]
113.171.18.0/24
113.171.239.0/24
113.171.243.0/24
113.171.251.0/24
125.234.53.0/24
125.234.54.0/24

**Comment by jglimmers** [comment]
感谢楼上几位分享

**Comment by Yamazaki-wu** [comment]
谢谢大家无私分享

**Comment by jasonliul** [comment]
103.1.139.0/24
119.40.97.0/24
163.28.116.0/24
49.231.56.0/24
61.91.9.0/24
27.123.17.0/24

泰国黄金 61.91.161.0/24

先就这么多, DNS方式不能过分频繁, 不然总是重复.

**Comment by xyuanmu** [comment]
哥们儿太热心了，分享还@我一下，谢谢 :hamster: 。

**Comment by jasonliul** [comment]
@xyuanmu 
现在玩ip的人太少了

**Comment by lsnmx** [comment]
@jasonliul goproxy都 不更新了

**Comment by jasonliul** [comment]
@lsnmx 那本来就是社长拿来玩票的.

**Comment by ARwMq9b6** [comment]
@jasonliul :

作者最近有 [关注](https://github.com/phuslu?tab=activity) Let's Encrypt 证书（被认为和 goproxy 项目息息相关）
相信他会选择在未来的某一天回来： <https://github.com/phuslu/goproxy/issues/116>

---

之所以“那一天”不是今天或许基于如下原因或动机：

+ **Let's Encrypt 证书方面遇到麻烦**

	可能的麻烦有：

	- 技术难题（在下小白，纯属猜测）
	- 现阶段 Let's Encrypt 在大陆不是很流行，此时用于 goproxy 有可能会导致其被直接封锁（在下小白，纯属猜测）

+ **作者精力遇到瓶颈**

	这方面可能性应该很低，作者经常在深夜提交代码

+ **洗粉**

	基于一些原因……

+ **其他**

**Comment by lsnmx** [comment]
@ARwMq9b6 给Let's Encrypt 科普一下啊，大神

**Comment by lsnmx** [comment]
@ARwMq9b6 https证书，明白了等这玩意啊

**Comment by ARwMq9b6** [comment]
@lsnmx 我对证书一窍不通，这方面只是猜测： https://github.com/phuslu/goproxy/issues/299 。
另外感觉作者对（实现 （在线路糟糕的情况下依旧 “1080P 无压力”））感兴趣。

此外还发现社区内一些爱好者正在学习或使用 Go 语言，说不定以后就有新人提交代码了。

我之前学了 PHP, 然后研究了 [index.php](https://github.com/phuslu/goproxy/blob/master/fetchserver/php/index.php) 这个服务端的代码，那感觉真好。最近几天在学 Go, 希望能够以此改变命运。

**Comment by jasonliul** [comment]
印尼长字段 114.4.4.0/24

**Comment by jasonliul** [comment]
58.69.77.82|58.69.77.85|58.69.77.76|58.69.77.86|58.69.77.88|58.69.77.92|58.69.77.89|58.69.77.87|58.69.77.91|58.69.77.90|58.69.77.93|58.69.77.83

GA字段

**Comment by jasonliul** [comment]
110.50.81.198|110.50.81.197|110.50.81.196|110.50.81.208|110.50.81.219|110.50.81.218|110.50.81.206|110.50.81.222|110.50.81.204|110.50.81.234|110.50.81.227|110.50.81.237|110.50.81.233|110.50.81.241|110.50.81.248|110.50.81.214|110.50.81.216|110.50.81.225|110.50.81.213|110.50.81.250|110.50.81.210|110.50.81.211|110.50.81.246|110.50.81.217|110.50.81.229|110.50.81.247|110.50.81.235|110.50.81.221|110.50.81.231|110.50.81.209|110.50.81.251|110.50.81.205|110.50.81.230|110.50.81.232|110.50.81.215|110.50.81.228|110.50.81.224|110.50.81.226|110.50.81.239|110.50.81.212|110.50.81.207|110.50.81.243|110.50.81.238|110.50.81.245|110.50.81.240|110.50.81.244|110.50.81.223|110.50.81.236|110.50.81.220|110.50.81.242|110.50.81.249

**Comment by jasonliul** [comment]
36.37.218.5|36.37.218.42|36.37.218.57|36.37.218.58|36.37.218.14|36.37.218.33|36.37.218.32|36.37.218.12|36.37.218.53|36.37.218.56|36.37.218.39

**Comment by xyuanmu** [comment]
一直伸手，今天也来一发：45.64.34.0/24
话说你上次说的那个bestdns真的很不错，今天用自己弄的小工具[dig](https://github.com/xyuanmu/dig)随便找了泰国和台湾的CDN一dig就得到这段IP了。

**Comment by jasonliul** [comment]
@xyuanmu 哇靠, 白金级.

**Comment by xyuanmu** [comment]
新捕获日本IP一段，没早上的好：43.245.144.0/24

**Comment by jasonliul** [comment]
@xyuanmu 这一段我摸到, 其实很稳定, 是谷歌香港撤出的机器.
因此连号4个, 也能形成谷歌的盾阵, 就像中国谷歌.

早期的谷歌玩家提到过, 一组谷歌的机器,如果连号谷歌会自动指定一个最好的机器, 作为小父主机.而且拥有更高权限.

对这组ip的任何机器的请求, 同时也会送给小父主机协调, 原理基本就是古代的盾阵.

现在很明确, 盾阵最少需要4个连号. 
4个ip的盾阵, 比7,8个零散ip还要高效.

**Comment by xyuanmu** [comment]
@jasonliul 哇塞，这组真的有连号，看来IP质量还有一个指标，学习了。

**Comment by jasonliul** [comment]
@xyuanmu 只有谷歌自家的才有盾阵.其他的连号没意义.
我试过很多组了... 贪婪是一种罪恶. :)

也就是把cn段, hk段都用这个字段的连号4个, 不仅运行良好, 也能出现+1 ip.

没有盾阵, 死活就没有+1. 而且作为一个指标, 下载速度不变.

有了盾阵可以满速, 我这里就算没有+1 IP, 下载也已经470kb/s了.
删除CN段, 就回到230kb或者更小.

**Comment by xyuanmu** [comment]
103.233.37.0/24
114.108.207.0/24
125.234.50.0/24
125.235.31.0/24
125.235.36.0/24
203.113.161.0/24
216.58.199.0/24
晚上的一些收获，暂时就这样吧！

**Comment by jasonliul** [comment]
@xyuanmu 爽爽爽.
这段216我发过, 又取消.

原因是测试没有问题, 用的时候经常掉线.

**Comment by jzp820927** [comment]
官方字段稳定性还是没有第三方GGC好，干扰也厉害！

**Comment by xyuanmu** [comment]
@jasonliul 刚才在xx-net单独测试了216这段IP，发现Y2B看720完全没问题，1080不稳定。

**Comment by jasonliul** [comment]
@xyuanmu 
这段做hosts都不行, 谷歌地图动辄停住.
我只好用回泰国61长段.

**Comment by xyuanmu** [comment]
看来xx-net真是兼容百态，只要连得上GAE就能用。

**Comment by jasonliul** [comment]
@xyuanmu 
xx-net的确可以用非常不稳定的ip,手动旧版就不行.

**Comment by ARwMq9b6** [comment]
@xyuanmu { 

在下发现 216 段稳定，看视频能满带宽；
值得加入 https://github.com/XX-net/XX-Net/pull/1956 。

![](https://i.imgur.com/qjAStJ8.jpg)
}

**Comment by xyuanmu** [comment]
@ARwMq9b6 216段原本就包含在之前的IP库里，也许是没扫描到而已[ip_range.txt#L1503](https://github.com/XX-net/XX-Net/blob/master/gae_proxy/local/ip_range.txt#L1503)。

**Comment by ARwMq9b6** [comment]
@xyuanmu 懂了！谢谢。（逃……）

**Comment by Lrevor** [comment]
@jasonliul 厉害啊，IP连号还有这种NB的作用？

**Comment by Lrevor** [comment]
你分享的IP里有个柬埔寨的，在我这里从12一直连到59，一点没断

**Comment by jasonliul** [comment]
@Lrevor 
旧版某达人的发明, 我只是发现了连号4个的特殊之处. 之前还可以直接连接中国谷歌的时候.
现在加入连号中国谷歌, 是先连接Hk字段, 回头再激活中国谷歌.

只有谷歌自家的机器连号才行, 形成盾阵的4个ping值也不能差距过大.
中国谷歌之外, 其他第三方的连号也没有用, 仅仅泰国有一段43是谷歌家的.

例如我有3个19ms, 1个37ms, 迟一些才能形成盾阵. 不过如果这个是76ms, 就不是盾阵, 仅仅是4个ip.看下载速度就知道了, 形成盾阵就突破了下载的限制.

一般谷歌ip下载只有100多kb, 好的是230kb左右, 最好的是300KB多一点.
但是有了盾阵, 就是满速下载. 我测试过不同线路, 确实是突破了下载的局限.
而且u2b基本接近3000kbps.

**Comment by xyuanmu** [comment]
还是台湾：103.224.194.0/24
