### ISSUE TITLE
支持TCP的免费DNS

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#321]
需要的自己测试

203.86.167.106
103.21.217.89
202.137.15.233
202.137.15.253
202.162.219.170
202.77.96.194
42.156.32.8
202.78.134.5
217.24.251.69
82.114.90.118
93.159.192.145
80.78.65.99
82.114.70.1
46.19.224.186
213.207.45.218
202.69.164.51
202.69.164.52
222.127.108.96
93.153.252.103
122.154.0.1
110.164.197.125
103.10.231.224
123.25.9.148
118.70.128.177
113.160.57.242
175.29.184.18
114.129.8.6
202.168.255.139

**Comment by jzp820927** [comment]
现在 53 端口的 TCP 好像也被干扰了：

root@ubuntu:~# dig twitter.com +tcp @8.8.8.8
;; communications error to 8.8.8.8#53: connection reset
root@ubuntu:~# dig twitter.com +tcp @208.67.222.222
;; communications error to 208.67.222.222#53: connection reset

这是我的情况，不晓得你们是什么情况？

**Comment by Chu2koi** [comment]
53端口的tcp查询被干扰了，现在我只能用非标准端口的dns了

**Comment by jasonliul** [comment]
@jzp820927 @Chu2koi 
真是变态无极限.

**Comment by jzp820927** [comment]
这个是最近才发现的，之前 TCP 的 53 端口没有任何问题！
