### ISSUE TITLE
iodine 0.70 TCP方式DNS方案

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#322]
主页
http://code.kryo.se/iodine/

http://analogbit.com/2008/07/27/tcp-over-dns-tunnel-software-howto/
超赞的文章,解释用户没有自己的服务器怎么用.

注意这里的红字
http://freedns.afraid.org/

居然有这么多免费资源
http://freedns.afraid.org/domain/registry/

有些麻烦, 玩家可以试试.

**Comment by jzp820927** [comment]
这个好像要有自己的服务器才行吧？
