### ISSUE TITLE
IPInfoOffline v1.42 ip快查, 新强扫选择

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#323]
还是以色列尼尔, 不过这个离线版适合天朝, 下载MaxMind城市数据, 放在同一目录.
http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
每月只更新一次.

主页
http://dev.maxmind.com/geoip/legacy/geolite/

我的意思是, 如果有可用的优秀ip, 这个IPInfo会列出该公司的ip段. 如果不长的话, 抓出这个段落, 使用强扫.

这个办法对于印尼, 菲律宾, 这类众多小公司ISP商的国家, 非常有效.

118.98.111.
118.98.106.
118.98.110.
118.98.30.
118.98.76.

强扫比达人分享的多了两个字段

**Comment by linhua55** [comment]
谢谢分享，收藏了

**Comment by jasonliul** [comment]
强扫这两个公司段, 必有惊喜
202.240.0.0-202.255.255.255
66.96.224.0-66.96.255.255

**Comment by pug908** [comment]
强扫ip没问题，直接就用等于枪毙ip
帮你修复了一个ip段

**Comment by meergod** [comment]
怎么用？怎么查找IP段？？

**Comment by Yamazaki-wu** [comment]
那请问怎样用法才是不是直接用？

**Comment by pug908** [comment]
扫到冷门ip段后，通知我即可，我来修复，修复后过一个礼拜，这段ip就金刚不坏鸟!

**Comment by xyuanmu** [comment]
@pug908 ip段还能修复？这么神奇。

**Comment by pug908** [comment]
没错，就这么神奇!

**Comment by ARwMq9b6** [comment]
强势关注！

**Comment by LGA1150** [comment]
@xyuanmu 不会是墙的卧底吧？

**Comment by xyuanmu** [comment]
@LGA1150 是啊，:hamster: 你怎么知道的？话说你这个插槽的CPU我家一枚都没有。

**Comment by jasonliul** [comment]
@pug908 神功护体, 刀枪不入.
这又是青山病院偷跑的. :)

**Comment by pug908** [comment]
傻逼五毛

2016-01-05 21:20 GMT+08:00 Jason Liu <notifications@github.com>:
