### ISSUE TITLE
OkayFreedom VPN Premium 1年免费

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#324]
OkayFreedom VPN Premium 1年免费

https://www.okayfreedom.com/specials/chip0216/of

老规矩, 手快者得

**Comment by jzp820927** [comment]
已经到手，谢谢！

**Comment by pgz123** [comment]
谢谢！

**Comment by wz7465** [comment]
xp不能用

**Comment by pgz123** [comment]
怎么用.,昨天能用,今天打不开

**Comment by meergod** [comment]
谢谢楼主分享

**Comment by meergod** [comment]
@jasonliul 
请问楼主,goproxy怎么自定义端口，如GAE，PHP，VPS用不同端口

**Comment by jzp820927** [comment]
自己可以改配置文件

**Comment by meergod** [comment]
@jzp820927 
怎么配置，能否详细点

**Comment by pgz123** [comment]
连不上服务器

**Comment by jzp820927** [comment]
main.user.json

**Comment by meergod** [comment]
@jzp820927 
"Addr": "127.0.0.1:8000"  这个GAE端口 假如切换PHP代理，走的端口也是8000
能不能像goagent那样，GAE走8000，让PHP走其他端口如10000  或者其他方法

**Comment by jzp820927** [comment]
我看配置文件，目前好像只有设计的一个端口，没有把端口分开，而且昨天现在也没开发了，这个估计没戏啊

**Comment by meergod** [comment]
@jzp820927 
感谢您的回复，请问php配置文件能否放多个url网址，若能格式是什么，试了几次都不成功

**Comment by Lrevor** [comment]
{
        "fetchservers": [
            {
                "url": "xxxxxxxxxxx",
                "password": "123456",
                "sslverify": false
            },
            {
                "url": "xxxxxxxxxxx",
                "password": "123456",
                "sslverify": false
            },
            {
                "url": "https://xxxxxxxxxxx",
                "password": "123456",
                "sslverify": false
            }
            
        ],
        "sites": [
            "*"
        ],
        "transport": "direct"
    }

**Comment by fifth5** [comment]
这个是不是要自己编译的

**Comment by meergod** [comment]
@Lrevor 
@jzp820927 
非常感谢您，顺便请问同一家平台多个应用是不是比一个有很大优势？？
是不是越多越好，还是几个效果最好？？

**Comment by jzp820927** [comment]
这个只有你测试看看了，不晓得目前的版本有没有实现 负载均衡，昨天没开发了，只能自己测试了！

**Comment by meergod** [comment]
@jzp820927 
感谢您的耐心解答，若在实现 负载均衡 的情况下，是越多越好么？？？

**Comment by jzp820927** [comment]
那肯定了，如果有负载均衡，会自动分配流量
