### ISSUE TITLE
PIA VPN 两年破解

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#328]
PIA VPN 两年破解

主页
https://www.privateinternetaccess.com/

破解 两年
http://www.mediafire.com/download/6koi4whc7w06hx4/PIAVPNCracked.rar

**Comment by jzp820927** [comment]
Dangerous File Blocked
The file you attempted to download was determined to be dangerous. For your protection, MediaFire does not enable distribution of dangerous files.

Still have questions, or think we've made a mistake? Please contact support for further assistance.

打开下载地址，提示这个，这是被屏蔽啦么？

**Comment by jasonliul** [comment]
@jzp820927 
这是被举报.

**Comment by jzp820927** [comment]
好吧，看来来晚了，没戏了！

**Comment by jasonliul** [comment]
@jzp820927 
我一般只贴原发点, 其他镜像没有这么快.

**Comment by jzp820927** [comment]
话说，这动作也太快了点，难道以后要蹲点才行麽？

**Comment by jasonliul** [comment]
@jzp820927 这是一些弱智, 自己下载查毒, 然后跑去举报.
谁都知道风险自负.

**Comment by jzp820927** [comment]
@jasonliul 我也是这么想的，不管你信不信，反正我是信了。。。
