### ISSUE TITLE
HideMyAss VPN Pro 无限

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#329]
HideMyAss VPN Pro 

主页
https://www.hidemyass.com/

1.打开仿真

2.修改hosts文件, 加入
127.0.0.1 privax.com
127.0.0.1 auth.privax.com
127.0.0.1 vpn.hidemyass.com
127.0.0.1 hidemyass.com

3.安装HideMyAss VPN Pro 

4.使用如下登录
Login User: Bruker80
Login Password: CrackedByTT

5.如果不成功, 以管理员权限启动仿真, 再来一遍

仿真
http://www43.zippyshare.com/v/WYAuLfvM/file.html

安装文件 [其他版本不可用]
http://www43.zippyshare.com/v/WYAuLfvM/file.html

**Comment by sishentibu** [comment]
http://i4.tietuku.com/e502dba6f2de48fb.png
连接不上，都还没到用账号登陆这一步
设置问题？

**Comment by jzp820927** [comment]
仿真 是啥咚咚？

**Comment by cnshinchan** [comment]
登不上账号

**Comment by jzp820927** [comment]
好像也登录不上！

**Comment by jasonliul** [comment]
@jzp820927 仿真合法用户的机器特征, 不过看来已经无效, 或天朝搞掂了

**Comment by jzp820927** [comment]
估计是无效了，反正登录不上。
