### ISSUE TITLE
还是黄狗坚挺，GP大家用得怎么样？

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#331]
rt

**Comment by diggerdu** [comment]
黄狗是什么 GP是什么

**Comment by jzp820927** [comment]
GP问题多，而且也不更新了，依旧黄狗！

**Comment by jasonliul** [comment]
狗屁毕竟还是气....

黄狗比当初IP几亿的时候, 表现得还要好.

**Comment by jzp820927** [comment]
现在IP比较稳定了，波动比较小了，所以表现比较好

**Comment by meergod** [comment]
@jzp820927 
@jasonliul 
请问怎样将goproxy.exe自启动并缩小到托盘 win10？？？

**Comment by jzp820927** [comment]
这个真不知道，没在win10下面用过

**Comment by yeahwu** [comment]
https://github.com/phuslu/goproxy/raw/master/assets/gui/goagent.exe
下载后用这个替换goagent.exe

**Comment by 5sq** [comment]
GP现在也不错，关键是有ip就能很好表现

**Comment by jasonliul** [comment]
GP 其实更平稳, 可惜不能像黄狗那样添加伪军.

**Comment by yeahwu** [comment]
用gae模式真不如用goagent，比较成熟。GP用来折腾“拍黄片”模式比较好。

**Comment by jasonliul** [comment]
我现在是也用GP, 使用IP长字段,相对稳定. 省得换ip.

黄狗用残兵或短ip字段, 现在响应最好的就是这些. 而且奇怪的就是, 不限速的白天, 是单个几个残兵表现好.
一旦限速, 还是大家都知道的那几个短字段表现好. 总之不是那么稳定.

**Comment by jzp820927** [comment]
GP确实表现不错，只可惜没人维护了！

**Comment by blob2015** [comment]
@jzp820927 真没人维护了啊？
@jasonliul 老兄的爆料向来有技术含量

**Comment by jzp820927** [comment]
要是有人能接受GP继续开发，那也挺好的，就像 SS 哪样！
