### ISSUE TITLE
SocksCap64 2.8

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#333]
国产帽子架, 刚升级, 支持http帽子了.

下载
http://sourceforge.net/projects/sockscap64/files/?source=navbar

**Comment by jasonliul** [comment]
[B]SocksCap64 3.1[/B]
https://sourceforge.net/projects/sockscap64/files/SocksCap64-setup-3.1.exe/download

portable
https://sourceforge.net/projects/sockscap64/files/SocksCap64-Portable-3.1.zip/download

2016-03-18 3.1
1, 加入代理备注功能.
2, 支持通过未经BASE64的SS加接加入节点.
3, 优化UDP传输.
4, 优化代理测试,代理测试更快速.
5, 改进SS出错重连机制.
6, 改进SS代理 JSON格式, 兼容其它客户端版本.
7, 解决在最新的SS 服务器端LIBEV版本连接异常的问题.
8, 解决高DPI下界面图标错位的问题.
9, 解决SS节点密码中含有@字符无法通过SS,JSON,二维码加入的问题.
10, 修改可能存在无法提升新版本的问题.

**Comment by jzp820927** [comment]
不错，升级挺快的

**Comment by jasonliul** [comment]
[B][U]SocksCap64 3.2[/U][/B]
[url]https://sourceforge.net/projects/sockscap64/files/SocksCap64-setup-3.2.exe/download[/url]

portable
[url]https://sourceforge.net/projects/sockscap64/files/SocksCap64-Portable-3.2.zip/download[/url]

2016-04-03 3.2
1, user requirements should be: add command-line arguments --hideicon hide tray icon
2, resolve to add to the program guide SS node error problem through JSON format.
