### ISSUE TITLE
优网VPN Betternet 3.5.1 

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#334]
优网VPN Betternet 3.5.1 

Betternet VPN is absolutely free. No need for Registration. No login, No Limits.

使用OpenVPN, 不确定天朝可用

主页
https://www.betternet.co/

下载
http://betternet.co/bn-download/betternetInstaller.exe

**Comment by jzp820927** [comment]
危险啊，据说只有经过混淆流量的 OpenVPN 才能在天朝正常使用！

**Comment by jasonliul** [comment]
@jzp820927 哪有这事,
SocksCap64加帽子就是

**Comment by jzp820927** [comment]
@jasonliul 那我去试试行不行

**Comment by pgz123** [comment]
怎么用

**Comment by jzp820927** [comment]
试了几次，好像连接不上！加帽子还没测试

**Comment by jasonliul** [comment]
Betternet VPN 3.6.0
http://betternet.co/bn-download/betternetInstaller.exe

Betternet is completely redesigned with new icon.
