### ISSUE TITLE
大家的checkip正常？帮忙看看出了啥问题

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#336]
![Uploading 0262.png…]()

谢谢

**Comment by blob2015** [comment]
C:\Program Files\GoAgent\local>"C:\Program Files\GoAgent\local\python27.exe" "C:\Program F i1es\GoAgen t\1oca1\c hec k i p.py"
[Thread-1 ]begin to get ratndotn ip
[MainThread]need create max threads count: 128
[Thread-1]load extra ip ok.line:1642.load default ip: 0
Exception in thread Thread-1:
Traceback (most recent call last):
File "C:\Program Files\GoAgent\local\python27.zip\threading.py". line 810. in__bootstrap_inner
File "C:\Program Files\GoAgent\local\checkip.py". line 836. in run
File "C:\Program Files\GoAgent\local\checkip.py". line 749. in ramdomip
File "C:\Program Files\GoAgent\local\checkip.py". line 884. in splitip
UalueError: too many ualues to unpack

**Comment by blob2015** [comment]
运行黄狗没有问题

**Comment by jasonliul** [comment]
load default ip: 0
没有ip, ip格式有问题

**Comment by blob2015** [comment]
多谢 @jasonliul
IP格式跟之前没有更改，都是类似于1.1.1.0/24这样的格式，之前运行都没有问题，googleip.txt依然是gb2312编码
不过，确实入jasonliul所说，如果是输入单个的ip，并且单独一行，运行起来确实没有问题

**Comment by blob2015** [comment]
我减小了，用了很久之前的ip，确实运行起来了，是因为加入了某些ip？我再看一眼，查一查

**Comment by blob2015** [comment]
@jasonliul 
查到了，靠，不知道是谁，或者我自己前阵子整理的时候，放了三个不合格式的ip进去……
谢谢！

**Comment by jasonliul** [comment]
IP 池其实不用太大, 
我基本是用较好的残兵, 短字段. 
eip文件只有160-170个

**Comment by blob2015** [comment]
@jasonliul 
两个ip池，这个比较全，但一般不用，在1000多
另外一个不时加减，目前在180左右
再次感谢

**Comment by jasonliul** [comment]
@blob2015 可恶, 故意多过俺. LOL

**Comment by blob2015** [comment]
@jasonliul 
质量没你高啊，质量才是生命，lol

**Comment by jasonliul** [comment]
@blob2015 你又知道?
现在残存的就那么多, 其实大家都一样.

只是使用策略不同,俺还是老办法, 每次只用4个ip

**Comment by blob2015** [comment]
@jasonliul
我不知道啊，都是瞎折腾，要求也不高，反正也不怎么看yt，就是有些网站，尤其是whois网站，屏蔽google ip，还得在profile里面加注几个direct?
还是感谢老兄提供的一些iprange以及伪军胁从方法

**Comment by jasonliul** [comment]
@blob2015 伪军起作用是圣诞附近的事, 应该是谷歌自家的调整.
有了伪军, 下载速度基本是满速, 之前死活就是230K/s.

whois那是屏蔽代理吧, 很多黑客, 代理列表网站禁止使用代理访问.
不过通常这种站点, 强制追踪cookie, 本身也是有害网站.
