### ISSUE TITLE
推荐个查找谷歌IP的工具

### ISSUE THREAD

**Issue by xyuanmu** [phuslu/goproxy#337]
Dig工具模拟IP查询谷歌Google Global Cache IP，原理来自自：[goagent(issues)](https://code.google.com/p/goagent/issues/detail?id=20389)
工具地址：https://github.com/xyuanmu/dig

使用方法很简单：

1. 方法一：
  1. 到 [Best DNS](http://www.bestdns.org/) 首页 **Where do you need a DNS from?** 下方选一个地区的网址进行复制。
  2. 或者到 [Ungefiltert surfen](http://www.ungefiltert-surfen.de/) 选择 **Öffentliche Nameserver nach Ländern** 下方的地区网址进行复制。
  3. 运行 debug.bat，右键，粘贴网址，按下回车，之后会自动获取网页内的IP并使用dig工具获取返回的IP段。
2. 方法二：
  1. 在 debug.bat 所在目录新建一个 ip.txt，将自己收集IP地址复制进去，一行一个。
  2. 运行 debug.bat 自动使用dig工具获取返回的IP段。
3. 方法三：
  1. 在 debug.bat 所在目录新建一个 url.txt，复制 [Best DNS](http://www.bestdns.org/) 站点的网址进去，一行一个。
  2. 或者新建一个 url2.txt，复制 [Ungefiltert surfen](http://www.ungefiltert-surfen.de/) 站点的网址进去，一行一个。
  3. 运行 debug.bat 自动下载所有网页并使用dig工具获取返回的IP段。
4. 生成 ip_range.txt 后将里面的IP段导入扫描工具如 [checkiptools](https://github.com/xyuanmu/checkiptools) 进行扫描和管理。

如果只需要dig单个IP，可以根据系统选择32位（dig-32bit）或64位（dig-64bit）目录，运行 check.bat，如果是IPv6用户运行 check-ip6.bat。输入IP按下回车查看结果 **ANSWER SECTION** 下方的IP，如果不是谷歌官方IP段，则是GGC。

:smile: 有任何使用问题欢迎反馈!

**Comment by jasonliul** [comment]
推推先~

**Comment by xyuanmu** [comment]
@jasonliul 谢谢！

**Comment by lsnmx** [comment]
@xyuanmu 能找到好IP不？

**Comment by xyuanmu** [comment]
@lsnmx 这个要看情况的，最好用泰国、印度尼西亚这些东南亚国家的DNS，今天就找到两段新的。

**Comment by blob2015** [comment]
谢谢，很好很强大 :smile: :coffee:

**Comment by jasonliul** [comment]
韩日台港澳, 基本已经被搞死, 摸奖也已经彻底.
星加坡, 越南现在是重点干扰.

比较好的是菲律宾, 印尼, 泰国, 柬埔寨, 老挝. 
奇怪的是马来西亚不多.
蒙古,哈萨克斯坦有一些, 但带宽不好.

俄国, 纽西兰, 澳大利亚需要筛选, 但肯定有.

改版内联网以后, 相当于物理距离增加了一倍, 比2014年. 而且丢包率大了很多.
南亚的不用考虑, 印度,孟加拉基本就不能连接.中亚的阿塞拜疆, 亚美尼亚也不能.

**Comment by blob2015** [comment]
@xyuanmu @jasonliul 
感谢两位，重点进攻方向都给标出来了 :grinning: 

>奇怪的是马来西亚不多

这个也好奇

**Comment by lsnmx** [comment]
@xyuanmu 我还是强扫吧

**Comment by xyuanmu** [comment]
103.233.37.0/24
114.108.207.0/24
125.234.50.0/24
125.235.31.0/24
125.235.36.0/24
203.113.161.0/24
216.58.199.0/24
晚上的一些收获，暂时就这样吧！
其实手头IP已经够多了，总觉得自己像仓鼠:hamster: 。

**Comment by lsnmx** [comment]
@xyuanmu  大神你的神作checkiptools经常卡住了如何，解决啊，谢谢！
[Thread-90]SSL Exception(120.97.251.108): [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:
certificate verify failed, times:771 ms
[Thread-175]129 ip timeout
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Goagent X\CheckIptools\python27.zip\threading.py", line 810, in __bootstrap_inner
  File "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py", line 833, in run
  File "D:\Program Files (x86)\Goagent X\CheckIptools\checkip.py", line 812, in ramdomip
MemoryError

[Thread-74]129 ip timeout
[Thread-122]SSL Exception(120.113.168.205): [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICAT
E:certificate verify failed, times:940 ms
[Thread-77]129 ip timeout
[Thread-203]SSL Exception(120.96.47.113): [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:
certificate verify failed, times:724 ms
[Thread-61]SSL Exception(120.97.253.172): [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:
certificate verify failed, times:704 ms
[Thread-144]129 ip timeout
[Thread-356]Catch IO Exception(120.119.31.63): [Errno 10061] , times:2575 ms
[Thread-172]129 ip timeout
[Thread-353]SSL Exception(120.97.248.195): [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE
:certificate verify failed, times:950 ms
[Thread-447]Catch IO Exception(120.110.7.88): [Errno 10061] , times:2229 ms
[Thread-251]129 ip timeout
[Thread-496]Catch IO Exception(120.126.195.173): [Errno 10061] , times:1922 ms
[Thread-489]129 ip timeout
[Thread-332]129 ip timeout

**Comment by xyuanmu** [comment]
怎么还会报MemoryError，会不会是你进程太大的原因，看到489都出来了起码有500线程了。
这个报错会影响正常使用吗？说实话我不懂网络协议那些东西，原版checkip的代码我并不是很明白所以能做的很有限。

**Comment by lsnmx** [comment]
@xyuanmu 开的就是500线程

**Comment by lsnmx** [comment]
@xyuanmu 原版checkip的大神抱女朋友了吧都不折腾了，潜水了

**Comment by sishentibu** [comment]
请问下，强扫指的是多扫几遍，还是一个ip一个ip的扫？

另外，扫出来的ip，怎么确定是不是连号的？总不会是人工查看吧？因为听说连号的效果好。

**Comment by lsnmx** [comment]
@jasonliul 不摸了，老子强扫了亚洲IP估计有6E以上了，扫出来的真的很少，够用了，开500线程整整扫了3个月24小时开机

**Comment by blob2015** [comment]
@lsnmx 扫出来多少？据说，线程开得高，容易扫不到，也不知道是真是假。我一般挂一夜，某个国家，然后第二天看一下，挑几个，再集中火力攻击重点ip段。

**Comment by lsnmx** [comment]
@blob2015 4000W也就100来个IP能用理想点速度的自己想想吧有些区域完全物理断网了

**Comment by xyuanmu** [comment]
@lsnmx 看样子还是用dig更快找到IP段，这两天新增的IP个数近800个，checkip 500ms以下的200多。

**Comment by lsnmx** [comment]
@xyuanmu 找DNS的时间跟精力我强扫算了，反正由于你懂的原因PC24小时开机，500线程狂扫

**Comment by blob2015** [comment]
@xyuanmu 
循循善诱，好人 :grinning:

**Comment by rahmanaidadebeers** [comment]
[Window Title]
C:\Users\mo\dig_win_32bit_v1.0\dig-32bit\dig.exe

[Content]
C:\Users\mo\dig_win_32bit_v1.0\dig-32bit\dig.exe

应用程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。


[确定]


Microsoft Windows 7 旗舰版
6.1.7601 Service Pack 1 Build 7601

装了 vcredist_x86 也不行,请教原因 @xyuanmu ,谢谢

**Comment by xyuanmu** [comment]
@rahmanaidadebeers 你是32位系统吗？不能混用的。

**Comment by rahmanaidadebeers** [comment]
@xyuanmu 是的,32位win7,下的dig工具也是32位的

**Comment by xyuanmu** [comment]
@rahmanaidadebeers 你下载歌64位的试下，我在64位系统运行32位的跟这个提示相同。

**Comment by rahmanaidadebeers** [comment]
@xyuanmu 看来现在用32位系统的人不多了啊,就我一人遇到这

[Window Title]
C:\Users\mo\dig_win_64bit_v1.0\dig-64bit\dig.exe

[Content]
此文件的版本与正在运行的 Windows 版本不兼容。请检查计算机的系统信息以了解需要 x86 (32 位)还是 x64 (64 位)版本的程序，然后联系软件发布者。

[确定]

**Comment by jzp820927** [comment]
现在都是大内存，用32位，就太亏了

**Comment by xyuanmu** [comment]
刚才专门找了个32位系统，可以使用啊。
要不你到这里下载 **BIND**：https://www.isc.org/downloads/ ，解压出来试试。

**Comment by CNMan** [comment]
https://ftp.isc.org/isc/bind9/9.10.3-P3/BIND9.10.3-P3.x86.zip
https://ftp.isc.org/isc/bind9/9.10.3-P3/BIND9.10.3-P3.x64.zip

**Comment by blob2015** [comment]
我也32位

**Comment by rahmanaidadebeers** [comment]
@xyuanmu 谢谢，我现在在返乡路上，回家了试试看

**Comment by yuan18** [comment]
@xyuanmu仓鼠老兄，你分享的这些ip103.233.37.0/24
114.108.207.0/24
125.234.50.0/24
125.235.31.0/24
125.235.36.0/24
203.113.161.0/24
216.58.199.0/24有点太慢了

**Comment by xyuanmu** [comment]
@rahmanaidadebeers 我今天遇到和你一样的问题了，查看了事件查看器，发现是 vc++ 2005 没有打更新补丁的问题，因为我的系统更新是关闭的，卸载原有的 vc++ 2005，安装这个版本就好了：https://www.microsoft.com/zh-CN/download/details.aspx?id=26347

**Comment by xyuanmu** [comment]
复活的两段IP
120.28.26.0/24#菲律宾
218.253.0.0/24#中国香港

**Comment by jasonliul** [comment]
@xyuanmu 
菲佣这段, 之前抛弃过

**Comment by jasonliul** [comment]
120.89.6.0/24
49.231.60.0/24

响应比较慢

**Comment by jasonliul** [comment]
43.245.144.0/24
103.25.178.0/24
103.224.194.0/24 
223.27.237.0/24
222.251.134.0/24  
219.124.146.0/24  
218.253.0.0/24 
210.92.119.0/24  
210.94.153.0/24 
210.143.70.0/24 
210.158.146.0/24 
210.242.127.0/24 
209.85.201.0/24 
203.233.126.0/24 
203.233.63.0/24 
203.233.10.0/24 
203.248.210.0/24 
203.233.88.0/24 
203.121.59.0/24  
203.211.8.0/24 
203.113.161.0/24  
203.66.155.0/24 
203.146.98.0/24 
202.248.248.0/24 
202.28.85.0/24 
202.69.185.0/24 
202.248.151.0/24  
202.86.162.0/24 
188.43.69.0/24   
66.96.224.0/24 
1.255.22.0/24 
188.43.64.0/24

**Comment by c6132a1** [comment]
很想得到谷歌ip，就是没有办法弄，能不能再详细点

**Comment by c6132a1** [comment]
“xyuanmu大哥，帮兄弟一把吧，详细点告诉我这个菜鸟一样的技术，怎么运行debug，还有怎么用dig得到谷歌的ip段，2042674524@qq.com

**Comment by jasonliul** [comment]
推推, 免沉

**Comment by jasonliul** [comment]
@CNMan 
FindMeGoogleIP, 这个工具居然不支持直接拷贝到Goagent目录下使用...
大大不能添加支持文件, 做个整合便携版?

**Comment by Lynchie** [comment]
@xyuanmu 大大，你的工具怎么将零散的IP变成所在的IP段呀
比如
202.75.147.34
202.75.148.55
导出
202.75.147.0/24
202.75.148.0/24
谢啦

**Comment by jzp820927** [comment]
看工具说明里面好像有提取IP段功能。

**Comment by xyuanmu** [comment]
@Lynchie 结束的时候会自动提取IP段，建议用 [checkiptools](https://github.com/xyuanmu/checkiptools)，已添加pydig，速度比这个快N次方倍。

**Comment by c6132a1** [comment]
这个工具不会用那，谁能帮帮慢

**Comment by c6132a1** [comment]
xyuanmu兄弟，安装BIND9.10.3  dig还是打不开

**Comment by c6132a1** [comment]
dig' 不是内部或外部命令，也不是可运行的程序 或批处理文件

**Comment by jzp820927** [comment]
你安装在什么路径的，先 cd 到那个路径，然后再运行试试

**Comment by CNMan** [comment]
@c6132a1 dig.exe所在目录添加到系统path里
[dig安装与使用](https://github.com/CNMan/unbound.conf/issues/6)

**Comment by c6132a1** [comment]
兄弟们，path里已经添加;C:\Program Files\ISC BIND 9\bin
就是dig' 不是内部或外部命令，也不是可运行的程序 或批处理文件
我的计算机VC++ 05/08/10/12/13 都有了，事件查看器是什么，发现是 vc++ 2005 没有打更新补丁的问题

**Comment by jzp820927** [comment]
已经解决了？

**Comment by c6132a1** [comment]
jzp820927 老兄，国外知名大学的网址，它的谷歌ip怎么用dig弄。

**Comment by jzp820927** [comment]
国外知名大学的网址，和谷歌ip，有什么关系麽？

**Comment by c6132a1** [comment]
有很多国外知名大学，谷歌有ip分给它们用，速度非常快，我在网上搜索ip找的，用dig解释网址得到ip

**Comment by c6132a1** [comment]
用www. 开头的网址好像都有ip,其他开头的网址好像都没有ip,不知怎么弄。

**Comment by jzp820927** [comment]
那你直接 google 搜索学校的网址不就行了

**Comment by c6132a1** [comment]
学校的网址可以弄到，把网址放到dig里面没有它的谷歌ip
我看一个网友说，日本的早稻田大学它的谷歌ip速度非常快，结果被封了

**Comment by jzp820927** [comment]
这个估计没有什么特征可以用来找 IP 吧。看能不能找到相关学校的 IP 段范围，直接去扫了。

**Comment by hcym** [comment]
最近ip不是问题。现在都强制http2

偶尔用python3版的xx-mini扫一下gws

感觉比python2的好用😜

**Comment by blob2015** [comment]
@hcym 
我这边一http2，就一堆错误……

**Comment by hcym** [comment]
一定要官方的，最好是加州本部

怕麻烦还是关了http2吧，吃粗粮健康
😊😃

**Comment by c6132a1** [comment]
我还是觉的台湾的203.66那几个ip速度不快了2000kB都不到，韩国的1000多一点，日本的都是谷歌官方ip
香港的还没找估计也好不到那。

**Comment by jzp820927** [comment]
感觉延时低的IP，带宽都不高，也有可能是用的人多，所以平均带宽较低

**Comment by c6132a1** [comment]
好IP难找

**Comment by blob2015** [comment]
@c6132a1 
牵扯视频，尤其是720/1080，还有下载，才有些麻烦，只是网页的话，还好

**Comment by jzp820927** [comment]
估计都是些 有土鳖的 1080P用户。

**Comment by yuan18** [comment]
谁给点新的可用good ip段赛

**Comment by c6132a1** [comment]
怎么更新ip，更新后速度是否快点。jzp820927

**Comment by jzp820927** [comment]
@yuan18 打开 XX 的 google_ip.txt 文件，IP 一大堆。
@c6132a1 更新IP要自己手动更新，没有自动化方案。

**Comment by yuan18** [comment]
@jzp820927 你说的是哪个 XX是蓝灯还是什么？

**Comment by jzp820927** [comment]
XX-NET: https://github.com/XX-net/XX-Net/
你没用过麽？

**Comment by yuan18** [comment]
@jzp820927 真没有用过，如何扫，有教程链接吗？一直用goproxy和原来的go

**Comment by jzp820927** [comment]
自动运行，他会自动扫描，是个全自动化软件。打开就能用

**Comment by c6132a1** [comment]
jzp820927  怎么更新ip

**Comment by jzp820927** [comment]
不用你手动更新，都全自动化的

**Comment by c6132a1** [comment]
jzp820927兄弟，proxy怎么大流量传输，漏两手吧

**Comment by c6132a1** [comment]
jzp820927 兄弟，360带宽测试6.60MB/S, youtube视频是500kbps,怎么回事，我是50m浙江电信，弄不懂

**Comment by jzp820927** [comment]
360测试是用的国内的服务器测试，ytb 的服务器是在国外，完全没有可比性吗

**Comment by c6132a1** [comment]
更新ip和更换ip是否一样

**Comment by jzp820927** [comment]
你这是在考验我的语文么？我觉得是一样的

**Comment by c6132a1** [comment]
不是考验你，那只有换ip了

**Comment by jzp820927** [comment]
更新不就是换IP嘛，有什么区别麽

**Comment by c6132a1** [comment]
那你用proxy它的流量有多大，能不能很快就接收完成。

**Comment by jzp820927** [comment]
什么很快接受完成

**Comment by c6132a1** [comment]
进度条

**Comment by jzp820927** [comment]
不太懂，你什么意思

**Comment by c6132a1** [comment]
jzp820927兄弟，ip竖着设置，跟横着设置是否一样。

**Comment by jzp820927** [comment]
横竖无所谓，只要格式正确，就行了。http/2，不是所有的服务器都支持的。

**Comment by c6132a1** [comment]
那怎么开启http2，谢谢啦

**Comment by jzp820927** [comment]
默认配置就是会自动检测 http/2 的，如果你想强制使用 http/2 ，那就 "ForceHTTP2": true, 不过要保持 IP 支持 http/2 ，不然会报错。

**Comment by c6132a1** [comment]
jzp820927老兄，#853，#799  我按照这两个设置，自己找ip还是不行，能否帮帮忙。

**Comment by jzp820927** [comment]
你是想用 sni 加速？这个的话，按照原贴的内容设置就行了。sni 的话，只能用 hostname 不能用IP

**Comment by c6132a1** [comment]
ForceHTTP2": true,这个出现红色，没反应 ，什么样的服务器才能可月。

**Comment by jzp820927** [comment]
如果要用 http/2 就要全部用 gwsip

**Comment by c6132a1** [comment]
"ServerName": [
            "sin11s01-in-f25.1e100.net",
            "sin11s01-in-f0.1e100.net",
	    "sin10s02-in-f31.1e100.net",
	    "sin10s02-in-f86.1e100.net",
	    "sin10s02-in-f68.1e100.net",
	    "sin10s02-in-f88.1e100.net"
ip全部是gws,  ForceHTTP2": true还是不行。

**Comment by jzp820927** [comment]
sni 和 http/2 不能同时用。

**Comment by c6132a1** [comment]
jzp820927兄弟，goproxy你月那个版本。

**Comment by jzp820927** [comment]
好久没用了，最新版吧

**Comment by c6132a1** [comment]
jzp820927 ， http/2开启了，我只月2个台湾ip, gws  谢谢兄弟。

**Comment by c6132a1** [comment]
jzp820927 兄弟，进度条走到一定的位置它不走了，走了也蛮多的，我拉它一下又开始走了，怎么回事。

**Comment by jzp820927** [comment]
这个只能问 P大了吧，目前视频是存在一些问题。

**Comment by c6132a1** [comment]
jzp820927老兄，按照#853楼顶的说法，它的设置是这样了
"ServerName": [
// "hkg12s09-in-f4.1e100.net"
另外它的ip是普通的香港ip,不是谷歌的。

**Comment by jzp820927** [comment]
不管是哪儿的IP，只要是 gws 的IP 就可以。

**Comment by c6132a1** [comment]
那上面的设置是否正确。

**Comment by jzp820927** [comment]
你是想用 sni 吗？差不多就是这样，// "hkg12s09-in-f4.1e100.net" 前面的注释“//”要去掉。

**Comment by c6132a1** [comment]
谢谢老兄。

**Comment by c6132a1** [comment]
jzp820927老兄，高速ip哪里找哦，很难找。

**Comment by jzp820927** [comment]
这个自己扫吧，我也没办法
