### ISSUE TITLE
社长, 高手快现身: 俺要谷歌赠品+1 IP

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#338]
INFO - [Jan 19 15:02:53] 127.0.0.1:1530 "STRIP CONNECT api.github.com:443 HTTP/1
.1" - -
WARNING - [Jan 19 15:02:53] "OPTIONS https://api.github.com/_private/browser/sta
ts" not supported by GAE, please enable PHP mode!
INFO - [Jan 19 15:02:53] ssl good_ipaddrs=8, bad_ipaddrs=0, unknown_ipaddrs=0
INFO - [Jan 19 15:02:53] ssl good_ipaddrs=8, bad_ipaddrs=0, unknown_ipaddrs=0
INFO - [Jan 19 15:02:53] ssl good_ipaddrs=8, bad_ipaddrs=0, unknown_ipaddrs=0
INFO - [Jan 19 15:02:53] ssl good_ipaddrs=8, bad_ipaddrs=0, unknown_ipaddrs=0
INFO - [Jan 19 15:02:54] 127.0.0.1:1496 "GAE GET https://github.com/phuslu/gopro
xy/issues/337?_pjax=%23js-repo-pjax-container HTTP/1.1" 200 8160
INFO - [Jan 19 15:02:54] ssl good_ipaddrs=9, bad_ipaddrs=0, unknown_ipaddrs=0
INFO - [Jan 19 15:02:54] ssl good_ipaddrs=9, bad_ipaddrs=0, unknown_ipaddrs=0
INFO - [Jan 19 15:02:54] ssl good_ipaddrs=9, bad_ipaddrs=0, unknown_ipaddrs=0
INFO - [Jan 19 15:02:54] ssl good_ipaddrs=9, bad_ipaddrs=0, unknown_ipaddrs=0

每次出来这行绿字
WARNING - [Jan 19 15:02:53] "OPTIONS https://api.github.com/_private/browser/sta
ts" not supported by GAE, please enable PHP mode!

就得到谷歌赠品+1 IP, 速度提升明显.
旧论坛大家好像是当成bug的, 现在需要总是重现这个bug, 有什么好办法?

**Comment by johnsonz** [comment]
我也是当bug的。。。

**Comment by lsnmx** [comment]
@jasonliul  goproxy 几个月不更新了

**Comment by jzp820927** [comment]
又出影子IP了？

**Comment by jasonliul** [comment]
@johnsonz 
这个自己增加的ip很猛的, 我这里一般是油管2000,3000kbps.

有了+1这个, 4600kbps也是常事, 电信, 长宽4M

**Comment by blob2015** [comment]
只求稳定些用用 :grinning:

**Comment by mixool** [comment]
直到现在都还没有用上goproxy的泪过

**Comment by johnsonz** [comment]
长宽不能指望这些ip，即使没这道墙，油管的速度最快也不会超过1500kbps

**Comment by jasonliul** [comment]
@johnsonz 
我也用长宽, 长宽是倒卖, 之前倒联通, 好得很.
现在倒电信就差远了, 电信就是官妓.

不过依然可以4000kbps, 4M下

**Comment by jasonliul** [comment]
当初社长临别时, 故作玄虚, 口吐偈语

"只在乳峰间, 云深不知处"

果然现在死活都不现身了

**Comment by blob2015** [comment]
:grinning:
