### ISSUE TITLE
怎样更新社长的蛋蛋文件 packages.egg

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#341]
packages.egg其实就是zip格式, 不过还是需要命令行工具.
打开看看, 全是2014年的旧货. 加密相关的第三方文件.

有木有办法可以更新这个蛋蛋?

**Comment by linhua55** [comment]
解压出来到一个文件夹也是可以用的，像xx-net那样

**Comment by jasonliul** [comment]
@linhua55 
试了一下, 提示gevent需要安装, 原来好麻烦.

直接pass

**Comment by jzp820927** [comment]
要是专门有人更新这些库文件就好了

**Comment by blob2015** [comment]
那位 @cxjava 行不行？

**Comment by jasonliul** [comment]
哪位高手来下蛋?
天灵灵地灵灵

**Comment by CNMan** [comment]
不要更新里面的gevent和pyopenssl，其他的可以更新

**Comment by jasonliul** [comment]
@CNMan 
这样的话, 就只是更新pycrypto 2.6.1
https://pypi.python.org/pypi/pycrypto

greenlet, pyuv不知道怎么更新

**Comment by jasonliul** [comment]
新蛋蛋
http://rghost.net/private/6Bd6mHhHw/574259637f3f77021d5e1765a7076d8e

只更新了pycrypto , paramiko

大概是心理作用, 俺觉得新蛋蛋感觉不如社长下的蛋蛋好

**Comment by CNMan** [comment]
@jasonliul python(2.7.11)+gevent(1.0.1)+pyopenssl(0.13.1)+dnslib(0.9.6)+pygeoip(0.3.2)就可以用了，其他的不装也没关系

**Comment by jasonliul** [comment]
@CNMan 
python27.dll, python27.zip 
python(2.7.11) 应该只需要更新这两个吧?

**Comment by CNMan** [comment]
@jasonliul 对，可以用 https://github.com/phuslu/pybuild 更新
我系统上别的东西也要用python环境，所以就把goagent自带的全删掉了

**Comment by blob2015** [comment]
@jasonliul 
老兄更新后，能不能发一份 :smile: 
这个是用来更新dns的吧？还是？

**Comment by jzp820927** [comment]
哪个高手来写一份更新相关库文件的教程，我们这些小白也可以学习一哈！

**Comment by jasonliul** [comment]
@blob2015 
http://rghost.net/private/6s4qmZMhf/910c34e5342526c96f83eebfef0077c2

其实就3个支持库文件更新

**Comment by blob2015** [comment]
@jasonliul 
谢谢老兄解惑 :grinning:
