### ISSUE TITLE
新愚公摸奖 冬狩季

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#342]
xyuanmu 大大的新锅铲
https://github.com/phuslu/goproxy/issues/337

猎场
http://www.bestdns.org/
http://public-dns.info/

**Comment by xyuanmu** [comment]
原来之前那个public-dns的德国镜像站是这个。

**Comment by jzp820927** [comment]
确实，经过验证，就是这个

**Comment by jasonliul** [comment]
@xyuanmu 

德语这个才是主站
http://www.digineo.de/team/

他家的其他工具也很有用, email安全检查, 心淌血漏洞检测...
https://de.ssl-tools.net/

**Comment by jasonliul** [comment]
101.100.190.199|101.100.190.200|101.100.190.201

这次没手气

**Comment by xyuanmu** [comment]
台湾兄弟连，强扫/16段果然有收获：
45.64.29.0/24
45.64.30.0/24
45.64.31.0/24

**Comment by jasonliul** [comment]
@xyuanmu 

黄狗已经彻底摆脱粮食危机, 重新开始狗强精壮.
可喜可贺!

**Comment by sundaqing1969** [comment]
感谢分享

**Comment by jzp820927** [comment]
除了官方IP以外，好像第三方IP基本上都复活了，官方的都复活不少！

**Comment by xyuanmu** [comment]
@jasonliul 的确，昨晚扫描IP库竟扫出6400枚IP，以前都是2、3K的。

**Comment by blob2015** [comment]
@jzp820927 @xyuanmu 
不是吧，怕怕，每次high的时候，往往就接着要来点事 :1234:

**Comment by xyuanmu** [comment]
@blob2015 将近春节了，不过就算来点事问题应该也不大，自从会扫IP后就没断粮过。

**Comment by yeahwu** [comment]
![6b98ca8065380cd7fc898ce7a644ad345882810f](https://cloud.githubusercontent.com/assets/13328328/12504323/2a455ea4-c117-11e5-9ff0-5b1fe51b4962.jpg)

**Comment by jasonliul** [comment]
@blob2015 
@xyuanmu 

现在重点是所谓限速, 其他专用封杀基本都取消了.

我找到一种估算方式, 现在的网络白天就已经相当2014的两倍物理距离. Yandex的翻译或DNS很明显.

所谓限速, 大概标准是确保丢包率40%, 再加上ping值暴增而且不稳定, 使用乌克兰的一个测距应用.
现在限速时段, 等于白天的3-5倍物理距离. 就算很多越南ip,ping值都飚到600, 700ms, 因此很多国外地区等于砍掉光缆了.

而且这个同样影响国内网站, 使用旧内容没有问题, 但是像影视网站刚更新的, 无论西瓜吉吉百度盘, 都是龟速. 本质上就是剩饭网, 没有新陈代谢能力. 比当年网通铁通还不如.

限速时段, 根本不是内联网, 那是自撸网. 朝廷叫嚣"确保互联网做爱中的内联网自撸权", 就是这么个玩意.

**Comment by blob2015** [comment]
:wine_glass: :wine_glass:

**Comment by pug908** [comment]
学会使用失联ip才是王道

**Comment by jzp820927** [comment]
啥时候出个关联IP的教程，看的云里雾里的

**Comment by mixool** [comment]
你就是我的指路明灯啊，一直在普及姿势，学会了这个方法 再也不怕饿了。

**Comment by pug908** [comment]
本人只对GGC ip和I2P ip有兴趣，修复谷歌ip纯属个人爱好，从而发现GFW并非铜墙铁壁。
为什么GGC ip能修复？完全是个人和GFW的实战获得点滴经验累计而成，条件是至少有2个不同的网络环境。
GFW就和中共一个德性，外强中干，人格分裂，逻辑混乱。
使用失联ip的方法非常简单：用低版本的黄狗给3.2.3版本做前置(貌似那个混吃等死的XX-Net-2.8.10也可以）。做前置的黄狗放2个ip足以，例如（61.238.203.11|74.125.171.248），3.2.3版本使用失联ip，例如（149.3.177.56|149.3.177.58|149.3.177.39|149.3.177.106|149.3.177.57|149.3.177.26|149.3.177.84|149.3.177.91|149.3.177.36|149.3.177.89|149.3.177.122|149.3.177.7|149.3.177.40|149.3.177.25|149.3.177.23|149.3.177.27|149.3.177.121|149.3.177.49|149.3.177.6|149.3.177.45|149.3.177.12|149.3.177.88|149.3.177.15|149.3.177.42|149.3.177.55|149.3.177.100|149.3.177.102|149.3.177.48|149.3.177.110|149.3.177.9|149.3.177.24|149.3.177.105|149.3.177.107|149.3.177.5|149.3.177.4|149.3.177.108|149.3.177.41|149.3.177.43|149.3.177.10|149.3.177.120|149.3.177.101|149.3.177.104|149.3.177.103|149.3.177.90|149.3.177.8|149.3.177.14|149.3.177.86|149.3.177.16|149.3.177.109|149.3.177.13|149.3.177.59|149.3.177.54|149.3.177.87|149.3.177.46|149.3.177.47|149.3.177.38|149.3.177.85|149.3.177.44|149.3.177.123|149.3.177.119|149.3.177.20|149.3.177.22）。
再附送2个GWS，已经修复过。
可以做DNS，也可以做hosts（不能用在前置的黄狗）：
216.239.38.124
216.239.38.125
这个ip段还有2个，实战中被GFW枪毙鸟。

**Comment by pug908** [comment]
呵呵，再送个DNS工具，经常被DDoS的推荐使用 ：DnsJumper
谷歌云盘&YT观客，推荐使用：SMPlayer

**Comment by xyuanmu** [comment]
很早就发现216段的IP段可以hosts，216.239.38.125这个IP用来做hosts已过半年，不过用来访问developers会出现403所以还是混合这工具一起用。
@pug908 顺便把那几段台湾的修复下呗。

**Comment by jasonliul** [comment]
残段
61.205.127.0/24
101.100.190.0/24
111.90.117.0/24
120.28.12.0/24
120.28.53.0/24
120.28.12.0/24
42.112.8.0/24

**Comment by pug908** [comment]
61.205.127.51|61.205.127.34|61.205.127.5|61.205.127.6|61.205.127.12|61.205.127.32|61.205.127.44|61.205.127.92|61.205.127.50|61.205.127.41|61.205.127.99|61.205.127.105|61.205.127.87|61.205.127.88|61.205.127.42|61.205.127.46|61.205.127.49|61.205.127.91|61.205.127.97|61.205.127.86|61.205.127.96|61.205.127.76|61.205.127.107|61.205.127.85|61.205.127.93|61.205.127.56|61.205.127.75|61.205.127.38|61.205.127.94|61.205.127.79|61.205.127.47|61.205.127.39|61.205.127.73|61.205.127.40|61.205.127.71|61.205.127.72|61.205.127.58|61.205.127.80|61.205.127.95|61.205.127.81|61.205.127.98|61.205.127.37|61.205.127.82|61.205.127.90|61.205.127.36|61.205.127.59|61.205.127.78|61.205.127.83|61.205.127.84|61.205.127.70|61.205.127.77|61.205.127.118|61.205.127.54|61.205.127.69|61.205.127.55|61.205.127.35|61.205.127.52|61.205.127.53|61.205.127.29|61.205.127.30|61.205.127.68|61.205.127.7|61.205.127.20|61.205.127.9|61.205.127.16|61.205.127.33|61.205.127.57|61.205.127.89|61.205.127.45|61.205.127.74|61.205.127.8|61.205.127.43|61.205.127.10|61.205.127.17|61.205.127.14|61.205.127.25|61.205.127.19|61.205.127.27|61.205.127.21|61.205.127.4|61.205.127.22|61.205.127.23|61.205.127.24|61.205.127.104|61.205.127.117|61.205.127.101|61.205.127.106|61.205.127.108|61.205.127.112|61.205.127.102|61.205.127.31|61.205.127.103|61.205.127.100|61.205.127.26|61.205.127.13|61.205.127.114|61.205.127.18|61.205.127.28|61.205.127.15|61.205.127.11|61.205.127.120|61.205.127.109|61.205.127.110|61.205.127.111|61.205.127.122|61.205.127.113|61.205.127.116|61.205.127.123|61.205.127.48|61.205.127.115|61.205.127.119

**Comment by pug908** [comment]
101.100.190.207|101.100.190.220|101.100.190.199|101.100.190.213|101.100.190.233|101.100.190.196|101.100.190.198|101.100.190.217|101.100.190.208|101.100.190.224|101.100.190.249|101.100.190.250|101.100.190.212|101.100.190.215|101.100.190.211|101.100.190.251|101.100.190.248|101.100.190.244|101.100.190.205|101.100.190.209|101.100.190.210|101.100.190.206|101.100.190.247|101.100.190.221|101.100.190.239|101.100.190.223|101.100.190.214|101.100.190.201|101.100.190.219|101.100.190.222|101.100.190.242|101.100.190.243|101.100.190.229|101.100.190.200|101.100.190.218|101.100.190.204|101.100.190.228|101.100.190.227|101.100.190.237|101.100.190.240|101.100.190.234|101.100.190.232|101.100.190.235|101.100.190.225|101.100.190.226|101.100.190.230|101.100.190.245|101.100.190.197|101.100.190.241|101.100.190.216|101.100.190.231|101.100.190.236|101.100.190.238

**Comment by pug908** [comment]
111.90.117.107|111.90.117.104|111.90.117.102|111.90.117.120|111.90.117.242|111.90.117.220|111.90.117.103|111.90.117.250|111.90.117.225|111.90.117.240|111.90.117.93|111.90.117.199|111.90.117.243|111.90.117.123|111.90.117.114|111.90.117.75|111.90.117.203|111.90.117.71|111.90.117.116|111.90.117.73|111.90.117.111|111.90.117.115|111.90.117.84|111.90.117.215|111.90.117.82|111.90.117.106|111.90.117.118|111.90.117.121|111.90.117.196|111.90.117.117|111.90.117.68|111.90.117.211|111.90.117.81|111.90.117.88|111.90.117.217|111.90.117.78|111.90.117.80|111.90.117.85|111.90.117.87|111.90.117.229|111.90.117.86|111.90.117.249|111.90.117.74|111.90.117.202|111.90.117.207|111.90.117.247|111.90.117.251|111.90.117.226|111.90.117.197|111.90.117.248|111.90.117.210|111.90.117.227|111.90.117.77|111.90.117.206|111.90.117.92|111.90.117.101|111.90.117.222|111.90.117.83|111.90.117.113|111.90.117.209|111.90.117.200|111.90.117.239|111.90.117.212|111.90.117.228|111.90.117.223|111.90.117.100|111.90.117.218|111.90.117.105|111.90.117.201|111.90.117.244|111.90.117.91|111.90.117.122|111.90.117.79|111.90.117.204|111.90.117.112|111.90.117.69|111.90.117.119|111.90.117.72|111.90.117.234|111.90.117.97|111.90.117.221|111.90.117.236|111.90.117.219|111.90.117.214|111.90.117.231|111.90.117.110|111.90.117.230|111.90.117.198|111.90.117.76|111.90.117.96|111.90.117.95|111.90.117.213|111.90.117.89|111.90.117.233|111.90.117.94|111.90.117.232|111.90.117.98|111.90.117.109|111.90.117.208|111.90.117.224|111.90.117.90|111.90.117.241|111.90.117.237|111.90.117.108|111.90.117.70|111.90.117.99|111.90.117.205|111.90.117.238|111.90.117.216|111.90.117.235|111.90.117.245|111.90.117.246

**Comment by pug908** [comment]
120.28.12.162|120.28.12.134|120.28.12.182|120.28.12.174|120.28.12.186|120.28.12.140|120.28.12.157|120.28.12.149|120.28.12.144|120.28.12.146|120.28.12.154|120.28.12.160|120.28.12.138|120.28.12.145|120.28.12.161|120.28.12.168|120.28.12.137|120.28.12.187|120.28.12.7|120.28.12.185|120.28.12.152|120.28.12.156|120.28.12.153|120.28.12.169|120.28.12.184|120.28.12.20|120.28.12.176|120.28.12.183|120.28.12.143|120.28.12.159|120.28.12.167|120.28.12.139|120.28.12.150|120.28.12.135|120.28.12.147|120.28.12.23|120.28.12.165|120.28.12.95|120.28.12.5|120.28.12.148|120.28.12.180|120.28.12.177|120.28.12.24|120.28.12.27|120.28.12.178|120.28.12.14|120.28.12.72|120.28.12.88|120.28.12.86|120.28.12.22|120.28.12.93|120.28.12.85|120.28.12.106|120.28.12.75|120.28.12.92|120.28.12.108|120.28.12.112|120.28.12.70|120.28.12.102|120.28.12.104|120.28.12.122|120.28.12.97|120.28.12.100|120.28.12.68|120.28.12.110|120.28.12.120|120.28.12.87|120.28.12.109|120.28.12.79|120.28.12.99|120.28.12.74|120.28.12.71|120.28.12.78|120.28.12.89|120.28.12.12|120.28.12.91|120.28.12.81|120.28.12.121|120.28.12.84|120.28.12.119|120.28.12.116|120.28.12.113|120.28.12.82|120.28.12.114|120.28.12.76|120.28.12.105|120.28.12.80|120.28.12.98|120.28.12.115|120.28.12.141|120.28.12.132|120.28.12.142|120.28.12.171|120.28.12.164|120.28.12.8|120.28.12.155|120.28.12.13|120.28.12.10|120.28.12.133|120.28.12.73|120.28.12.111|120.28.12.90|120.28.12.77|120.28.12.123|120.28.12.6|120.28.12.21|120.28.12.4|120.28.12.16|120.28.12.17|120.28.12.69|120.28.12.151|120.28.12.15|120.28.12.11|120.28.12.25|120.28.12.101|120.28.12.19|120.28.12.9

**Comment by pug908** [comment]
120.28.53.165|120.28.53.168|120.28.53.183|120.28.53.142|120.28.53.149|120.28.53.160|120.28.53.187|120.28.53.184|120.28.53.146|120.28.53.166|120.28.53.148|120.28.53.147|120.28.53.141|120.28.53.164|120.28.53.153|120.28.53.133|120.28.53.139|120.28.53.185|120.28.53.135|120.28.53.150|120.28.53.155|120.28.53.174|120.28.53.167|120.28.53.176|120.28.53.179|120.28.53.154|120.28.53.181|120.28.53.178|120.28.53.171|120.28.53.173|120.28.53.161|120.28.53.152|120.28.53.140|120.28.53.172|120.28.53.132|120.28.53.137|120.28.53.169|120.28.53.156|120.28.53.170|120.28.53.186|120.28.53.145|120.28.53.163|120.28.53.177|120.28.53.175|120.28.53.162|120.28.53.143|120.28.53.136|120.28.53.180|120.28.53.138|120.28.53.134|120.28.53.182|120.28.53.144|120.28.53.159|120.28.53.157|120.28.53.151|120.28.53.158

**Comment by pug908** [comment]
42.112.8.231|42.112.8.230|42.112.8.30|42.112.8.107|42.112.8.45|42.112.8.112|42.112.8.19|42.112.8.119|42.112.8.79|42.112.8.4|42.112.8.78|42.112.8.97|42.112.8.115|42.112.8.7|42.112.8.221|42.112.8.14|42.112.8.103|42.112.8.25|42.112.8.109|42.112.8.198|42.112.8.26|42.112.8.11|42.112.8.59|42.112.8.108|42.112.8.71|42.112.8.93|42.112.8.105|42.112.8.91|42.112.8.218|42.112.8.102|42.112.8.82|42.112.8.83|42.112.8.206|42.112.8.27|42.112.8.99|42.112.8.106|42.112.8.199|42.112.8.208|42.112.8.33|42.112.8.47|42.112.8.101|42.112.8.89|42.112.8.37|42.112.8.41|42.112.8.203|42.112.8.70|42.112.8.94|42.112.8.10|42.112.8.197|42.112.8.38|42.112.8.229|42.112.8.92|42.112.8.85|42.112.8.36|42.112.8.40|42.112.8.69|42.112.8.81|42.112.8.22|42.112.8.46|42.112.8.50|42.112.8.96|42.112.8.88|42.112.8.211|42.112.8.95|42.112.8.116|42.112.8.76|42.112.8.214|42.112.8.18|42.112.8.32|42.112.8.74|42.112.8.200|42.112.8.210|42.112.8.249|42.112.8.246|42.112.8.216|42.112.8.35|42.112.8.58|42.112.8.227|42.112.8.29|42.112.8.24|42.112.8.217|42.112.8.87|42.112.8.31|42.112.8.90|42.112.8.48|42.112.8.212|42.112.8.122|42.112.8.123|42.112.8.226|42.112.8.207|42.112.8.215|42.112.8.42|42.112.8.219|42.112.8.244|42.112.8.20|42.112.8.57|42.112.8.213|42.112.8.117|42.112.8.225|42.112.8.75|42.112.8.68|42.112.8.236|42.112.8.224|42.112.8.220|42.112.8.110|42.112.8.240|42.112.8.77|42.112.8.111|42.112.8.223|42.112.8.43|42.112.8.234|42.112.8.80|42.112.8.209|42.112.8.52|42.112.8.51|42.112.8.121|42.112.8.53|42.112.8.118|42.112.8.238|42.112.8.202|42.112.8.84|42.112.8.222|42.112.8.15|42.112.8.55|42.112.8.201|42.112.8.98|42.112.8.44|42.112.8.114|42.112.8.242|42.112.8.72|42.112.8.205|42.112.8.241|42.112.8.28|42.112.8.13|42.112.8.86|42.112.8.34|42.112.8.100|42.112.8.204|42.112.8.245|42.112.8.6|42.112.8.243|42.112.8.247|42.112.8.9|42.112.8.228|42.112.8.73|42.112.8.235|42.112.8.49|42.112.8.120|42.112.8.39|42.112.8.239|42.112.8.250|42.112.8.21|42.112.8.232|42.112.8.23|42.112.8.17|42.112.8.16|42.112.8.5|42.112.8.56|42.112.8.8|42.112.8.233|42.112.8.54|42.112.8.113|42.112.8.237|42.112.8.12|42.112.8.248

**Comment by pug908** [comment]
以上ip段帮你明文。。。呼呼

**Comment by blob2015** [comment]
@pug908
>以上ip段帮你明文。。。呼呼
这个是说，这些ip段，所有信息都是明文？还是？小白不懂，问问。谢谢。

**Comment by pug908** [comment]
明文即可用，放心使用，绝对安全（推荐反共人士使用 ）～啦啦啦

**Comment by jasonliul** [comment]
61.91.160.0/24
61.91.161.0/24

泰国双星

**Comment by blob2015** [comment]
@jasonliul
谢谢
这里顺带嘀咕一句，棒子的ip，变化起来真快。午夜一两点扫到的，到了下午就用不来了……
