### ISSUE TITLE
ChrisPC DNS Switch 3.20

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#344]
轻松测试更改DNS, 内置DNS库

主页
http://changedns.how/

下载
http://www.chris-tv.com/chrisdownload.php?action=count&id=33

    Change your computer DNS with just 1 click.
    Set your favorite DNS or select one from the software's DNS Database.
    The DNS Database contains presets grouped by type: Regular DNS, Secure DNS, Family Safe DNS, Anonymous DNS and Custom DNS.
    DNS Benchmark lets you find the fastest DNS with one click.
    Protect your online experience by using a Secure DNS server that filters out websites that are potentially threats to your PC (avoiding viruses, malware, trojans etc.)
    Block adult websites or those that encourage violence, drugs and/or indecent behavior by selecting a Family Safe DNS.
    Import DNS server lists from text file.
    Improve your privacy while you surf the internet by using an Anonymous DNS.
    Gain access to websites that are blocked or restricted in your country/area using a Regular or Anonymous DNS.
    Saves your initial DNS settings so you can safely restore them back at any time.
    Easy add and edit your own DNS address in the Custom DNS preset list.
    Fast Switch your DNS from systray popup menu.
    Multi language interface: English, Romanian.
    Launch software on Windows boot.
    Minimize ChrisPC DNS Switch to systray.

**Comment by jzp820927** [comment]
挺不错的小工具

**Comment by sishentibu** [comment]
感觉跟dnsjumper差不多啊

**Comment by jap33** [comment]
有中文？

**Comment by normalhh** [comment]
都是win的。没有mac的

**Comment by blob2015** [comment]
pro版可以测试dns的响应时间，但是免费版，只能测试四组匿名dns，转换的话，也不比手工方便多少。

**Comment by jasonliul** [comment]
@blob2015 
罗马利亚程序很精致, 但是人气不佳.
破解自己去找罢

**Comment by blob2015** [comment]
@jasonliul 
 :grinning:

**Comment by blob2015** [comment]
先继续用一下Jumper
