### ISSUE TITLE
蓝灯 lantern 2.0.11

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#345]
https://s3.amazonaws.com/lantern/lantern-installer-qa.exe

终于新版了

**Comment by jzp820927** [comment]
都几个月过去了，终于出了1个新版，不容易啊

**Comment by ARwMq9b6** [comment]
Goood, 灭弹窗，杀 PAC 补丁开启： https://github.com/Kisesy/Tools/releases

**Comment by ARwMq9b6** [comment]
用 [NirCmd](http://www.nirsoft.net/utils/nircmd.html) 启动的 Lantern 不会出现两个进程，感觉不错。（Windows 系统）

```dos
nircmdc exec show "lantern.exe"
```

在 Lantern 目录下新建 *.bat 文件，填入上面的命令，再将这个文件加入开机启动。

**Comment by xyuanmu** [comment]
囧，昨天Gary12才发一个[版本](https://groups.google.com/forum/#!topic/fqlt/tWXW5kFwvfw)，今天就出新版。
不过话说回来最近蓝灯速度都还不错。

**Comment by jasonliul** [comment]
@xyuanmu 跟这里同步
https://github.com/getlantern/lantern/releases

**Comment by tmh8964** [comment]
这个2.0.11版本怎样？好不好用？

**Comment by xyuanmu** [comment]
@tmh8964 挺不错的，我电信网络都非常流畅。

**Comment by jzp820927** [comment]
看来现在蓝灯是越来越完善了，连电信这么垃圾的网，都不流畅

**Comment by jasonliul** [comment]
电信白天的意淫时段, 蓝灯满速很久了.

**Comment by jzp820927** [comment]
电信网，主要是晚上，超高掉包率，白天基本上没事！

**Comment by jasonliul** [comment]
@jzp820927 
就像鸡瘟, 俺下载电影也得用袜子, 国内节点.

**Comment by lefantian** [comment]
好灯！！！！！！！！

**Comment by jasonliul** [comment]
灯二其实是蓝灯和谷歌合作的, 亚当确认过这一点.

是把uProxy整合到灯一.
https://www.uproxy.org/

推介
https://www.rt.com/usa/google-uproxy-uncensored-encrypted-internet-524/

uProxy需要国外友人安装, 然后分享给你, 这个其实很难实现, 毕竟有时差.
蓝灯利用自家网络架构, 设置灯塔调度, 就好简单了.

2.1之后, 基本整合完成, 也就是维护一下.

**Comment by ARwMq9b6** [comment]
加持 P2P 就无敌了。

**Comment by jasonliul** [comment]
蓝灯 lantern 2.0.12

**Comment by jasonliul** [comment]
https://github.com/getlantern/lantern/releases
2.0.13

**Comment by jzp820927** [comment]
我去，蓝灯之前沉寂啦好长一段时间没动静，这几天怎么有开始飞速发布升级版了！

**Comment by jasonliul** [comment]
蓝灯 lantern 2.0.14
https://github.com/getlantern/lantern/releases

**Comment by canalist** [comment]
2.0.15也出来了。查看数字指纹，就是之前的2.0.10。仓促更新的13、14，用户十分不满。

**Comment by jzp820927** [comment]
我去，又往回开发类？

**Comment by canalist** [comment]
2.0.16也还是2.0.10。

**Comment by jzp820927** [comment]
太疯狂了，这是在往回开发的节奏啊

**Comment by jasonliul** [comment]
蓝灯 lantern 2.1.0
