### ISSUE TITLE
伊朗绿凤凰 Simurgh e-sabz , 居然还在

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#346]
Simurgh e-sabz
http://simurghesabz.net/

官网版本被投毒, 得用旧版
https://docs.google.com/file/d/0B2lH3w7DOYknRjJZMkVadVRtLVE/edit?usp=sharing
https://mega.nz/#!PUR3DCib!agjU0F1AeEnWhV1f2gCRWAsCcgtmngBt-daKWogu3qg

http://citizenlab.org/2012/05/iranian-anti-censorship-software-simurgh-circulated-with-malicious-backdoor-2/

能用, 不是太快.
IE, 谷歌不用设置, 火狐设置http代理, 端口2048

**Comment by ARwMq9b6** [comment]
Alkasir 2 近日有动静！ https://github.com/alkasir/alkasir/issues/4

**Comment by jasonliul** [comment]
@ARwMq9b6 
旧服务器11月就没钱了, 4个新服务器保留做2.0内测.
AK现在很奇怪

**Comment by ARwMq9b6** [comment]
@jasonliul 辛苦！

**Comment by jasonliul** [comment]
@ARwMq9b6 
绿凤凰可以到<280kb/s, 基本能够640视频.

这个玩意有点奇怪, 只支持https帽子

**Comment by xyuanmu** [comment]
J珍藏的翻墙工具可以开博物馆了，多少年后不知会不会成为历史。

**Comment by jzp820927** [comment]
确实， goproxy 的 issue，基本上都是他分享的工具！

**Comment by jasonliul** [comment]
@xyuanmu 
这也是伊朗网友提醒的, Simurgh最高就是这个版本, 其实从来没有正式版.

之后就是投毒, 而且讽刺的是, 投毒版在一些安软社区, 居然还拆解出 erights.net制作字样.
看起来像是puff打击竞争制作木马版.

两个老朽古国, 猥琐腌臜, 令人称奇!

**Comment by yeahwu** [comment]
这才叫江湖，哈哈 puff 哈哈
