### ISSUE TITLE
Ultrasurf和Freegate, 如何设置成英文?

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#347]
两个老家伙...

Ultrasur
http://ultrasurf.us/index.html
Freegate
http://dit-inc.us/freegate.html

FG可以设置为英文, 不过Ultrasurf总是自选简中,看起来很妖气, 有没有办法设置为英文?

这两个玩意已经沦为帽子党, 因为是标准http代理, 使用socks前置表现一流.

因为GranGorz只剩一个节点, 而且限速120KB/s, 使用U/FG搭配袜子前置也是不错的.

洋用户经常这样设置u.ini, 多选前置
ProxyMode=1
ProxyHost=10.102.61.46 @ 2002:0:0:0:0:0:808:404 @ 2002:0:0:0:0:0:208.67.222.222 @ 2002:0:0:0:0:0:208.67.220.220
ProxyPort=8080,443,52,9201,80,8091,8081,8008,8888, 3124,3127,3128​

**Comment by blob2015** [comment]
@jasonliul 
小白每怎么用过前置，问一下：加了这个顺畅与速度会上去？

**Comment by jasonliul** [comment]
@blob2015 

免费匿名代理非常多, 唯独中国人用得很少. 伊朗的绿凤凰, 白俄的洋葱, 基本都是依靠前置使用.根本就没有办法墙.

通常亚洲的中速代理, U/FG都能去到300kb左右.
关键在于, 有了前置, 破墙等于不存在. 匿名代理严重影响墙的侦测能力.
