### ISSUE TITLE
2016, 新春翻乐年

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#349]
全线飘绿,

纸飞机是国内中转的节点表现好, 赛风近期不太稳定.
黄狗, GP全满速.

恭喜列位同仁..

**Comment by ARwMq9b6** [comment]
恭喜反制裁胜利！以下全满速： 自建服务器类 (Shadowsocks, v2ray 等)、 GAE 类（GoAgent, XX-Net 等) 、非电信网络下的 Lantern 、加持 CDN 的 Psiphon 。

**Comment by jasonliul** [comment]
GP 538KB/s
GA 557KB/s

看来测速网站被忽悠了, 我只有4M

**Comment by jzp820927** [comment]
形势一片大好啊！

**Comment by ARwMq9b6** [comment]
楼主推荐的 [飞马 VPN](https://github.com/phuslu/goproxy/issues/225) 也是满速顺滑！
它的全局 VPN 有时会造成不便，借助 [虚拟机](https://program-think.blogspot.com/2013/01/cross-host-use-gfw-tool.html) 可变成常见代理的形式。

**Comment by jasonliul** [comment]
@ARwMq9b6 
飞马是俺推介给俄圈的, n年里面唯一所有大腕评介全给五星的软件.
免安装, 前置支持良好.

我知道的是这样, 出资方是德法的IT行业年轻富豪, 但是他们托管美国一家很小的软件方案公司, 叫做飞马科技. 后者请人做了客户端, 命名飞马. 问题是, 没法确认真假.

所有信息都是匿名的, 就连软件里面的作者email, 都是一家家具商城提供的, 节点, dns也是防追踪的.
大家有讨论过安全问题, 结论是匿名党的免费服务更值得信赖. :)
