### ISSUE TITLE
AK 即将回归

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#350]
Alkasir moving to a new server
Mon, 02/08/2016 - 17:28 — alkasir

We're glad to inform you that we are moving to a new server very soon to launch the next generation of Alkasir (Alkasir 2.0).

The format and content will change drastically, but the software and its vision will continue as they are with the hope of introducing a more reliable, open-source solution that you could use to overcome Internet censorship.

Stay tuned.

Alkasir team

**Comment by blob2015** [comment]
@jasonliul 
过年还在啊
新年好
