### ISSUE TITLE
2014墙奴新花样, 全面封杀境外DNS

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#357]
我的线路4省电信, 一省移动近两天境外DNS已经无用.
包括港澳.

**Comment by lsnmx** [comment]
https://github.com/holmium/dnsforwarder/wiki/%E9%A6%96%E6%AC%A1%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95 无压力

**Comment by lsnmx** [comment]
@jasonliul

**Comment by jzp820927** [comment]
标准 53 端口的 TCP+UDP 全部被封，非标准的可以正常使用。

**Comment by jasonliul** [comment]
@jzp820927 

俺觉得这是好事, 现在国外网站基本只能代理访问, 
内外分明 LOL

**Comment by jzp820927** [comment]
好吧，看来 DNS 也是终极武器啊

**Comment by lxok89** [comment]
近几天确实如此。各类翻墙手段速度明显缓慢到不能用。午夜之后，情况有好转。

**Comment by jasonliul** [comment]
DNS记录是最简单的监控, 模糊搜索记录就能侦测翻墙方式.
设定触发规则, 可以所谓的智能封堵. 如果搜索上网记录, 那得超级计算机才行.

中国是唯一几乎不使用前置的墙国,现在国外的匿名前置提供商伸手中国, 而且上海也有了几枚真正的国产前置 [差别是, 能否通过前置连接谷歌]. 

纸飞机的国内中转, 会成为标准方式.
大体上, 傻瓜式直连翻墙, 已经成为过去式.

**Comment by pug908** [comment]
玩不了共匪，就玩GFW

**Comment by mixool** [comment]
看来又得学习新姿势了，还好我是移动网，目前还稳当。
