### ISSUE TITLE
 蓝灯 lantern 2.3.0 beta

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#359]
蓝灯 lantern 2.1.0
https://s3.amazonaws.com/lantern/lantern-installer-qa.exe

@ARwMq9b6
旧补丁失效, 不能去除随机启动, PAC设置

**Comment by ARwMq9b6** [comment]
@jasonliul `lantern-pac-patch.exe` 失效，`lantern-patch.exe` 正常，求 [作者](https://github.com/Kisesy/Tools/releases) @Kisesy 救火。

**Comment by jasonliul** [comment]
@ARwMq9b6 
lantern-patch.exe这个也不正常, 每次都添加随机启动

**Comment by Kisesy** [comment]
关于 PAC，这个在新版可以设置了
还有便携大家真的需要吗，我是因为用的影子系统，我才改的便携
其实现在的蓝灯就需要个去弹窗吧

**Comment by jasonliul** [comment]
@Kisesy 
去掉随机启动. 每次都会添加. 便携也很好

**Comment by Kisesy** [comment]
嗯。。也许还缺个单进程

**Comment by jasonliul** [comment]
http://127.0.0.1:16823/
新版灯2设置页面, 俺从来没有打开过, 全是蓝灯不再运行,
其实用得好好的. 所以有去PAC也不错

**Comment by Kisesy** [comment]
@jasonliul 不需要，你打开 settings.yaml 文件
把下面的配置粘进去，关PAC，关开启启动

	version: development
	builddate: ""
	revisiondate: now
	autoreport: false
	autolaunch: false
	proxyall: false
	rwmutex: {}

**Comment by Kisesy** [comment]
https://github.com/Kisesy/Tools/releases
更新了一下补丁，等会改个单进程

**Comment by Kisesy** [comment]
@jasonliul PAC补丁也做了一个

**Comment by jasonliul** [comment]
@Kisesy 

有劳提醒, 没有留意多了个配置文件.

**Comment by Kisesy** [comment]
代码修改。。。。还是放这里好
前几天整个硬盘被格式化了，什么都没了，发上来就不怕没了，妈的

```asm
; 2.1.0 以上去弹窗

00404358   .  E8 E3860000          CALL 0040CA40
0040435D   .  803D D5B0B500 00     CMP BYTE PTR [0B5B0D5],0
00404364   .  74 17                JE SHORT 0040437D
00404366   .  8B1D 685A0B01        MOV EBX,DWORD PTR [10B5A68]
0040436C   .  0FB61B               MOVZX EBX,BYTE PTR [EBX]
0040436F   .  80FB 00              CMP BL,0
00404372   .  75 09                JNE SHORT 0040437D                       ; JMP
00404374   .  E8 F7391500          CALL 00557D70
00404379  />  83C4 30              ADD ESP,30
0040437C  \.  C3                   RETN
0040437D   >  C70424 20917A00      MOV DWORD PTR [ESP],007A9120
00404384   .  E8 97350100          CALL 00417920                            ; [lantern.00417920
00404389   .  8B5C24 04            MOV EBX,DWORD PTR [ESP+4]
0040438D   .  83FB 00              CMP EBX,0
00404390   .  0F84 BD000000        JE 00404453


0F B6 1B 80 FB 00 75 09


; 单进程

8B 4C 24 ?? 8B 5C 24 ?? 83 FB 00 0F 84 ?? ?? ?? ?? 89 84 24 ?? ?? ?? ??
8B 4C 24 ?? 8B 5C 24 ?? 83 FB 00 90 E9 ?? ?? ?? ?? 89 84 24 ?? ?? ?? ??


00552E3A      8B4C24 58     mov ecx,dword ptr [esp+58]
00552E3E      8B5C24 54     mov ebx,dword ptr [esp+54]
00552E42      83FB 00       cmp ebx,0
00552E45      0F84 F7030000 je lantern_.00553242
00552E4B      898424 C80000>mov dword ptr [esp+C8],eax
00552E52      8943 38       mov dword ptr [ebx+38],eax
00552E55      898C24 CC0000>mov dword ptr [esp+CC],ecx
00552E5C      803D BCBE0301>cmp byte ptr [103BEBC],0



00552E3A   > /8B4C24 58     mov ecx,dword ptr [esp+58]
00552E3E   . |8B5C24 54     mov ebx,dword ptr [esp+54]
00552E42     |83FB 00       cmp ebx,0
00552E45     |90            nop
00552E46     |E9 F7030000   jmp lantern_.00553242
00552E4B   > |898424 C80000>mov dword ptr [esp+C8],eax
00552E52   . |8943 38       mov dword ptr [ebx+38],eax
00552E55   . |898C24 CC0000>mov dword ptr [esp+CC],ecx
00552E5C   . |803D BCBE0301>cmp byte ptr [103BEBC],0

; 去掉pac

0F B6 5C 24 ?? 80 FB 00 0F 84 ?? ?? ?? ?? E8 ?? ?? ?? ?? BB
0F B6 5C 24 ?? 80 FB 00 90 E9 ?? ?? ?? ?? E8 ?? ?? ?? ?? BB

00404323   .  0FB65C24 04   movzx ebx,byte ptr [esp+4]
00404328   .  80FB 00       cmp bl,0
0040432B      0F84 29010000 je lantern.0040445A
00404331   .  E8 DA140000   call lantern.00405810
00404336   >  BB F4889700   mov ebx,lantern.009788F4

```

**Comment by jasonliul** [comment]
@Kisesy 
蓝灯新出DC版, 干掉了你的补丁.

便携不成功, 而且单进程也不是必须的, 蓝灯资源占用很小

**Comment by jasonliul** [comment]
@Kisesy 
蓝灯今天的DC版本又取消了 settings.yaml 文件,
朝三暮四, 不过速度已经恢复

**Comment by Kisesy** [comment]
是吗，我还没见过DC版

**Comment by jasonliul** [comment]
@Kisesy 
版本号不变, 重编译, 2.1.0已经有3个DC版本了
https://s3.amazonaws.com/lantern/lantern-installer-qa.exe

**Comment by Kisesy** [comment]
嗯，这个版本合并了区段，文件小了不少

**Comment by jasonliul** [comment]
@Kisesy 
DC0305, 几乎每天一版

**Comment by Kisesy** [comment]
@jasonliul 我觉得现在的蓝灯应该是一向默认分支提交代码，这个地址的蓝灯就会自动更新
今天终于换服务器了，我这里的速度才快点。。

**Comment by jasonliul** [comment]
@Kisesy 
应该是自动编译. 

之前DC版本很少, 现在这玩法, 跟赛风一样. 去年瓦伦西亚国际反审查节, 这帮作者喝酒搞基, 
应该还是蛮多交流的

**Comment by jasonliul** [comment]
蓝灯 2.1.1
https://github.com/getlantern/lantern/releases

**Comment by jasonliul** [comment]
Lantern 2.1.2 beta
https://s3.amazonaws.com/lantern/lantern-installer-qa.exe

**Comment by jasonliul** [comment]
2.20 beta
https://s3.amazonaws.com/lantern/lantern-installer-qa.exe

**Comment by hcym** [comment]
速度咋样

手机都不用代理直接推

性趣了了

**Comment by Kisesy** [comment]
新版基本不能用。。。太慢了

**Comment by jasonliul** [comment]
@Kisesy 
不慢, 蓝灯每次升级, 都得手动删除lantern.log,
让新版建立新链路

**Comment by yeahwu** [comment]
lantern，不好玩鸟

**Comment by jzp820927** [comment]
现在的蓝灯，没有以前的速度了。
我就说嘛，除了 google ，没有哪个能经得起天朝网民的折腾，这么大的基数，也只有 google 顶得住，只是时间问题

**Comment by Kisesy** [comment]
也就备用了，放俩IP段，嘿嘿
58.26.8.0/24 203.252.15.0/24

**Comment by yeahwu** [comment]
收鸟，好人哪，一生平安，1024
图像威武

**Comment by yeahwu** [comment]
为什么你们都有极品ip，老是拿你们的也不好意思，俺也来借花献佛
203.233.96.0/24
45.64.76.0/24
185.119.13.0/24
217.18.145.0/24

**Comment by jasonliul** [comment]
[U][B]Lantern Stable 2.2.3[/B][/U]
https://github.com/getlantern/lantern/releases/download/2.2.3/update_windows_386.bz2

**Comment by xyuanmu** [comment]
这货怎么突然更新这么快

**Comment by Kashgar-Castle** [comment]
用过一次就默认随机启动这一点真的很烦人。

**Comment by hcym** [comment]
@随机启动

linux下还好，不用安装版，单文件版本没这麻烦

就是默认走ipv6线路不知如何设置

**Comment by jasonliul** [comment]
@Kashgar-Castle 
CCleaner或者Msconfig都可以去掉. 仅仅首次运行添加.

做个纯文本, 改名CCleaner
`version: 2.2.3
autoreport: false
autolaunch: false
proxyall: false
systemproxy: false
rwmutex: {}

改名settings.yaml, 放到蓝灯目录下.
这是某个测试版添加的, 还可以用`

**Comment by Kashgar-Castle** [comment]
要不是因为这个问题我都不会用Msconfig删除启动项。后来才发现在CCleaner里就能改。还是觉得这个问题会影响用户对这个软件的观感。
最开始用过蓝灯的一个测试版，结果卸载之后，蓝灯还是在火狐浏览器上留下了图标，重装火狐都没用。后来把C盘所有带"lantern"的新近文件全都手动删除，图标才消失。这件事让我很久没再碰蓝灯。

**Comment by jasonliul** [comment]
2.3.0 beta
https://s3.amazonaws.com/lantern/lantern-installer-qa.exe

**Comment by Kisesy** [comment]
下载速度只有1，20K ![I](http://tb2.bdstatic.com/tb/editor/images/face/i_f25.png)

**Comment by yeahwu** [comment]
最新源码编译了个去pac，去弹窗的lantern，可以试试
https://github.com/yeahwu/recycle-bin/files/264503/lantern-5.14.tar.gz

**Comment by yeahwu** [comment]
刚看了下版本号是lantern_2.3.0版
