### ISSUE TITLE
不更新就恐慌症

### ISSUE THREAD

**Issue by mixool** [phuslu/goproxy#362]
目前goproxy用起来挺好的，但是没有更新就感到心慌。
203.211.8.28 348 *.googlevideo.com gvs 1.0
203.211.8.39 353 google.com gws
45.64.28.36 355 *.googlevideo.com gvs 1.0
210.92.119.33 367 *.googlevideo.com gvs 1.0
210.92.119.36 367 *.googlevideo.com gvs 1.0
203.211.8.77 370 *.googlevideo.com gvs 1.0
61.62.98.143 382 *.googlevideo.com gvs 1.0
203.211.8.27 383 *.googlevideo.com gvs 1.0
61.62.98.238 396 google.com gws
172.217.24.98 416 *.g.doubleclick.net gws
45.64.34.119 432 google.com gws
61.62.98.208 441 google.com gws
172.217.24.120 455 *.google.com gws
45.64.31.42 466 google.com gws
210.94.153.27 467 *.googlevideo.com gvs 1.0
45.64.28.19 467 *.googlevideo.com gvs 1.0
210.92.119.53 512 *.googlevideo.com gvs 1.0
210.92.119.58 515 *.googlevideo.com gvs 1.0
203.211.8.82 525 *.googlevideo.com gvs 1.0
222.251.134.110 532 *.googlevideo.com gvs 1.0
59.18.46.31 544 *.googlevideo.com gvs 1.0
45.64.31.40 557 *.googlevideo.com gvs 1.0

**Comment by playnetcn** [comment]
好东西都是被这样玩坏的，google就是这样被玩死的。哎......
