### ISSUE TITLE
如何使用 google 的 ipv6 地址？

### ISSUE THREAD

**Issue by wangjiezhe** [phuslu/goproxy#367]
类似 goagent 中 ipv6=1 的选项

**Comment by blob2015** [comment]
首先，你的isp必须支持 :grinning:

**Comment by wangjiezhe** [comment]
我在教育网，ipv6 的连接是没有问题的。

**Comment by pug908** [comment]
用前置的方法，可以使用ipv6 GGC ip（ipv4环境）不需要isp支持。

**Comment by blob2015** [comment]
@pug908 前置还有这好处啊

**Comment by wangjiezhe** [comment]
@pug908 你说的前置是指什么？

**Comment by pug908** [comment]
前置就是可用GGC IP（ipv4）链接失联GGC IP（IPV4、IPV6一样），我称为推墙策略。

**Comment by rayfine** [comment]
@pug908
能说得详细些吗？具体怎么搞？
是在前置代理中填写ipv4，在iplist中填写ipv6吗？

**Comment by Yamazaki-wu** [comment]
同样也想知道，不需要ISP支持情况下，使用IPV6.
是IPV6做前置还是怎样？如果这样设置成功后对速率有提升么？

**Comment by liush000** [comment]
貌似goproxy不支持使用ipv6地址，目前。
还是只能用goagent，都提示我客户端需要更新好久了……

**Comment by phuslu** [comment]
现在 r292 版之后应该都可以了。

**Comment by wangjiezhe** [comment]
@phuslu 成功了！Thx！

**Comment by wangjiezhe** [comment]
@phuslu 现在的 ipv6 基本上用不了，刷新一两次之后就变成了 `net/http: Transport.DialTLS returned (nil, nil)`。
另外，除了打开 `IPv6Onl=true` 之外，还用在调整其他的设置吗？（比如 `HostMap` 或 `DNSServers` 等）

**Comment by phuslu** [comment]
@wangjiezhe HostMap->google_hk 填上一些 google ipv6 的服务器地址即可。

**Comment by c6132a1** [comment]
pug908兄弟，goproxy的接收速度能否调快点，兄弟我先谢谢啦

**Comment by phuslu** [comment]
@c6132a1 别顶老帖子

**Comment by pug908** [comment]
从来不用goproxy，最近修复了不少官方GGC IP，呼呼～

**Comment by c6132a1** [comment]
pug908 哥们，修复ip你是行家，了不起。你从来不用goproxy？那天澳门ip段怎么弄我只看一眼你就收了，拜托了好兄弟，绝活让我看一看，邮箱  lipangbo123@163.com  我再次谢谢啦。
