### ISSUE TITLE
纸飞机 3.0

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#368]
Update Privoxy to 3.0.24
    Replace Choose by Total Packet Loss with Choose by Statistics
    Support Onetime Authentication
    Support chacha20-ietf
    Optional checking updates
    Download updates automatically
    Improve log viewer
    Minor fixes
    Other improvements
https://github.com/shadowsocks/shadowsocks-windows/releases/download/3.0/Shadowsocks-3.0.zip

**Comment by playnetcn** [comment]
SSR已经停止开发，低调，请关闭此贴，谢谢。

**Comment by CNMan** [comment]
@playnetcn 这不是ssr

**Comment by mixool** [comment]
楼上老是低调，关贴，谢谢?  暴力温柔?

**Comment by playnetcn** [comment]
@mixool 低调些好，自己用就好，不要给作者添麻烦。

**Comment by jasonliul** [comment]
@playnetcn 关闭有什么不同吗?
250.

**Comment by jzp820927** [comment]
我也觉得，只要开启了 未读提醒，关不关没啥区别

**Comment by wenliyang** [comment]
新版本一出，早传开了，关不关，没区别
