### ISSUE TITLE
Socks5 前置新皇帝 墨西哥

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#371]
墨西哥已经成为免费socks5皇帝, 提供的优质节点超过美加俄欧的总和.
前置难找, 已成历史

**Comment by jzp820927** [comment]
具体在哪儿找啊？

**Comment by sleeplesshermit** [comment]
同问 - 可以提供Socks5 前置网页链接 或google搜索关键字吗？

**Comment by Yamazaki-wu** [comment]
楼主能否透露一些信息啊？比如google关键字什么的。谢谢了！

**Comment by jasonliul** [comment]
Proxy list socks
旧版俺已经列出主要那些.

这么多找不着, 可以回去申请幼稚园再教育

**Comment by jasonliul** [comment]
http://sockslist.net/list/proxy-socks-5-list/

入门级, 更多更好自己想办法
