### ISSUE TITLE
Klephon

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#375]
印尼人改版的赛风, 比较简明, 容易设置.
大幅优化CPU和内存占用, 而且支持前置好得多.

下载
https://sourceforge.net/projects/klephon/

介绍
http://www.internetgratisan.ga/2015/12/download-klephon-for-windows.html

跟MyEnTunnel一样, 
这个也需要Plink

http://www.chiark.greenend.org.uk/%7Esgtatham/putty/download.html
更新下载0.67 plink.exe,自带的是0.65, 改名ssh.exe, 设置只读, 拷贝到你的临时文件目录,覆盖同名文件.
其实也是变相玩玩经典的Putty.

Klephon右下角有检查ip, 显示NO的话, 只能侦听http端口.
这是赛风的问题, 很多时候赛风显示连接, 但如果使用socks5端口转接, 就没有反应.

另外, 克风对中国用户, 可用节点会多一些, 因为赛风使用meek域名欺诈, 但是有些服务器是用谷云做前台, 因此中国用户用不了.

克风等于赛风的精简版, 精简了一些赛风特色, 华而不实的功能, 并且也能使用普通SSH.
类似MyEnTunnel, 但多了赛风的节点

**Comment by jzp820927** [comment]
还是没有 Linux 版本，不晓得赛风啥时候能出 Linux 版本

**Comment by sundaqing1969** [comment]
感谢J大分享

**Comment by jasonliul** [comment]
跟MyEnTunnel一样, 
这个也需要Plink

http://www.chiark.greenend.org.uk/%7Esgtatham/putty/download.html
更新下载, 改名ssh.exe, 设置只读, 拷贝到你的临时文件目录,覆盖同名文件.
其实也是变相玩玩经典的Putty.
