### ISSUE TITLE
SSH超经典客户端 PuTTY 0.67

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#376]
http://www.chiark.greenend.org.uk/~sgtatham/putty/

2016-03-05 PuTTY 0.67 released, fixing a SECURITY HOLE

PuTTY 0.67, released today, fixes a security hole in 0.65 and before: vuln-pscp-sink-sscanf. It also contains a few other small bug fixes.

Also, for the first time, the Windows executables in this release (including the installer) are signed using an Authenticode certificate, to help protect against tampering in transit from our website or after downloading. You should find that they list "Simon Tatham" as the verified publisher. 

下载
http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html

**Comment by jzp820927** [comment]
这个版本开始支持签名了，不错。

**Comment by yeahwu** [comment]
帐号？帐号？

**Comment by jasonliul** [comment]
@yeahwu 
https://fastssh.com/
http://create.sshgoogle.com/
http://go-ssh.com/sshserver/ssh-server.html
http://godssh.com/
http://www.sshagan.net/
http://www.mytunneling.com/ssh-server-new
https://white-vps.com/
https://www.highssh.com/
http://skyssh.com/

**Comment by yeahwu** [comment]
赞，以后怀旧就直接找@jasonliul了，都是经典中的经典

**Comment by somebodyj** [comment]
请教：使用Bitvise SSH登录，原来使用正常，但现在不能正常登录了，老是显示
ListeningSocket::StartListening() failed: Windows error 10048: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次
同样的设定，同的账号（之前多个能正常使用的账号都是如此），现在都不能正常了，寻求解决方法，谢。

**Comment by jasonliul** [comment]
@somebodyj 
http://www.nirsoft.net/utils/cports.html
检查其他程序, 是否占用了ssh的端口

**Comment by somebodyj** [comment]
感谢你的回答，我先看看，有什么回头再请教，谢。

**Comment by somebodyj** [comment]
果然我是一个大头虾，端口的确被占用了，长时间关注你的信息收获很大，感谢你！
