### ISSUE TITLE
Putty 衍生KiTTY + MyEnTunnel

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#377]
1.KiTTY 增强版

主页
http://kitty.9bis.net/

下载
http://www.fosshub.com/KiTTY.html

Putty增强版, 比对BitviseSSH Client同等功能, 但是轻巧很多, 只是竖列的设置栏, 不如BitviseSSH Client的横列看得舒服.

2.MyEnTunnel 简化版

主页
http://nemesis2.qx.net/pages/MyEnTunnel

开发版, 稳定版自选, 记得更新Plink到最新
http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html

MyEnTunnel实际上是Plink的前端界面程序,

3.ExtraPuTTY 增强版
也不错, 只有win版本
http://www.extraputty.com/

**Comment by hcym** [comment]
请教一下，Putty上传路由器

怎么指定xp的本地路径？

scp D:\luci-app-macvlan_all.ipk root@192.168.1.1:/tmp
scp host:D/luci-app-macvlan_all.ipk root@192.168.1.1:/tmp
scp luci-app-macvlan_all.ipk root@192.168.1.1:/tmp
都是
No such file or directory

sftp还没有，所以winscp的图形界面用不了

**Comment by jzp820927** [comment]
你命令是不是打错了？应该是 pscp 吧？ scp 是linux 下面的命令，win 下面是 pscp 你用的什么系统？

**Comment by hcym** [comment]
pscp也试过，也是路径不对

XP系统，winscp集成了pscp和scp

关键是路由固件奇葩，缺相关软件还不许更新

算了，已经涮回原厂，不折腾

谢谢

**Comment by jasonliul** [comment]
WinSCP 5.7.7
http://sourceforge.net/projects/winscp/files/WinSCP/5.7.7/winscp577setup.exe

WinSCP也是刚刚更新过的.

**Comment by wan-qy** [comment]
winscp可是好东西winscp+putty比linux下ssh+vi+git操作openshift方便多了。只是如意云（联想）新固件貌似不允许ssh、scp了，只好上Pandorabox
