### ISSUE TITLE
SoftEther VPN Client + VPN Gate Client v4.19-9605

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#379]
SoftEther VPN Client + VPN Gate Client v4.19-9605
http://download.vpngate.jp/common/cd.aspx/vpngate-client-2016.03.07-build-9605.134933.zip

继续更新

**Comment by jzp820927** [comment]
可用的 服务器 太难找了

**Comment by jasonliul** [comment]
@jzp820927 
VPN支持前置, 还有专属VPN/SSH的乌贼代理, Squid proxy

需要的只是前置节点

**Comment by fletchere** [comment]
有前置还要这个干嘛，真是脱了裤子放屁，呵呵！

**Comment by jasonliul** [comment]
@fletchere 
前置只够塞你屁眼, 不够翻墙. :)

**Comment by Laizmf** [comment]
@jzp820927 
编程随想 的博客有专门介绍VPN Gate 的使用方法，或许对你有启发

**Comment by jzp820927** [comment]
@Laizmf 行，那我去编程随想看看

**Comment by jasonliul** [comment]
[B][U]
SoftEther VPN Client + VPN Gate Client v4.20-9608[/U][/B]
http://download.vpngate.jp/common/cd.aspx/vpngate-client-2016.04.18-build-9608.135270.zip

**Comment by jasonliul** [comment]
[U][B]SoftEther VPN Client + VPN Gate Client v4.21-9613[/B][/U]
[url]http://download.vpngate.jp/common/cd.aspx/vpngate-client-2016.04.25-build-9613.135325.zip[/url]

**Comment by Kisesy** [comment]
忍不住试了下，还是不好用
这个下载地址真是那啥，不支持断点续传，直接干翻GAE类代理

**Comment by evoxu** [comment]
自己建一个服务器
