### ISSUE TITLE
r201在火狐浏览器下无法使用

### ISSUE THREAD

**Issue by PvCDp** [phuslu/goproxy#381]
安全连接失败

连接 mail.google.com 时发生错误。 对等端的证书有一个无效的签名。 （错误码： sec_error_bad_signature） 。
其他浏览器没有问题。请帮忙提供解决方案。

**Comment by zhhzq** [comment]
1、删除浏览器证书
2、删除cert8.db
3、删除本地证书文件
4、重新运行程序生成证书
5、进入浏览器导入本地证书机构

Done！

**Comment by jzp820927** [comment]
火狐浏览器 的证书 是独立于系统证书，和其他浏览器证书的，不晓得你有没有单独给 火狐安装证书

**Comment by PvCDp** [comment]
多谢，还是搞不定，不用火狐了，改用傲游搞定。

**Comment by jasonliul** [comment]
@PvCDp 
火狐的安全性不是谷壳可比的. 何况火狐的流水线(pipelining)大大增加代理的稳定性.

导入新证书, 把GoAgent下面的crt文件全部拷贝过来.
新版crt一直有问题, Goagent不能删除
