### ISSUE TITLE
goproxy对视频播放支持不好。

### ISSUE THREAD

**Issue by playnetcn** [phuslu/goproxy#385]
goproxy对youtube支持比较好，但是对脸书上的短视频支持不好，有很多不能播放（例如东森新闻，tvbs，美国之音等）有的能播放，还有其它视频网站，也是支持的不好，视频播放不了，使用ss软件就没有这类问题，都可以播放，个人觉得是程序哪有问题。
以下是一段日志：
I0309 10:28:55.569188    6812 gae.go:145] 127.0.0.1:6348 "GAE GET https://video-
ord1-1.xx.fbcdn.net/hvideo-xft1/v/t42.1790-2/12836985_1139091589454729_151241899
0_n.mp4?efg=eyJybHIiOjMyMCwicmxhIjo1MTIsInZlbmNvZGVfdGFnIjoic3ZlX3NkIn0%3D&rl=32
0&vabr=178&oh=868cf370dad0ecd35ea09e352bfeae89&oe=56DFB514 HTTP/1.1" 200 1180297

I0309 10:28:55.852205    6812 stripssl.go:140] 127.0.0.1:9158 "STRIP CONNECT vid
eo-ord1-1.xx.fbcdn.net:443 HTTP/1.1" - -
E0309 10:28:55.901207    6812 handler.go:113] IoCopy &http.bodyEOFSignal{body:(*
http.body)(0x135cc930), mu:sync.Mutex{state:0, sema:0x0}, closed:false, rerr:err
or(nil), fn:(func(error) error)(0x51c3c0), earlyCloseFn:(func() error)(0x51c360)
} return 86016 write tcp 127.0.0.1:12015->127.0.0.1:6348: wsasend: An establishe
d connection was aborted by the software in your host machine.
I0309 10:28:59.293401    6812 stripssl.go:140] 127.0.0.1:9169 "STRIP CONNECT vid
eo-ord1-1.xx.fbcdn.net:443 HTTP/1.1" - -
I0309 10:29:00.079446    6812 gae.go:145] 127.0.0.1:4667 "GAE POST https://www.f
acebook.com/ajax/photos/logging/session_logging.php?__s=1&__pc=EXP1%3ADEFAULT&dp
r=1 HTTP/1.1" 200 1132
I0309 10:29:00.132449    6812 stripssl.go:140] 127.0.0.1:9190 "STRIP CONNECT vid
eo-ord1-1.xx.fbcdn.net:443 HTTP/1.1" - -
I0309 10:29:03.875180    6812 gae.go:145] 127.0.0.1:7556 "GAE GET https://2-edge
-chat.facebook.com/pull?channel=p_100005519136341&seq=3&partition=-2&clientid=37
c495be&cb=jtd5&idle=6&qp=y&cap=8&pws=fresh&msgs_recv=3&uid=100005519136341&viewe
r_uid=100005519136341&sticky_token=356&sticky_pool=atn2c06_chat-proxy&state=acti
ve HTTP/1.1" 500 323

**Comment by angle1895** [comment]
goproxy该如何设置?相同ip在goagent 1080无鸭梨,但在goproxy 480勉强可以.

**Comment by fhzyfjy** [comment]
视频播放问题一直没有解决
