### ISSUE TITLE
能否修改Goagent 使用Openssl?

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#388]
近来短暂的ssl握手失败多了不少, CheckGoogleIP也是这样.

有趣的是, CheckGoogleIP可以选择openssl或gevent, 改用openssl好得多.
短暂的ssl握手失败比较少, 也不会中途卡顿一下.

俺记得GoAgent有些旧版本是直接用openssl的, 不清楚现在是否还有简单的方法, 可以修改Goagent 使用Openssl?

**Comment by jasonliul** [comment]
gevent现在是黄狗的病虫害, 俺用CheckGoogleIP连测三次, 只取4个, 居然还经常有bad ip.这是近期才有的. 黄狗除了无事超时, 好坏ip也变来变去.

换成openssl模式CheckGoogleIP, 起码ip好一些了
终于回到4000kbps [4M电信]
[img]http://s020.radikal.ru/i719/1603/a3/7bdd7c1cfd5b.png[/img]

**Comment by angle1895** [comment]
期待大神们出小白攻略
