### ISSUE TITLE
破墙升级, IP遭殃

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#392]
白天破墙暂开, 可以搜索完整字段.
夜间清点, 俺的800多壮士, 只剩下少于300.

看来黄狗余威犹在. :)

**Comment by angle1895** [comment]
我的ip基本死光光了

**Comment by jzp820927** [comment]
这几天IP变动很快

**Comment by blob2015** [comment]
要团灭的节奏？

**Comment by fletchere** [comment]
目前为止我这里还没有受影响。

**Comment by wangbingqian** [comment]
1.255的有6个，现在还剩2个

**Comment by jzp820927** [comment]
亚洲的死了一大片

**Comment by sishentibu** [comment]
goproxy能看出可用ip是多少吗

**Comment by jzp820927** [comment]
只能看到数量，看不到具体IP

**Comment by sishentibu** [comment]
@jzp820927 

I0316 22:24:06.267713    5524 gae.go:145] 127.0.0.1:62648 "GAE GET http://tietuk
u.com/favicon.ico HTTP/1.1" 200 589
I0316 22:24:07.404778    5524 gae.go:145] 127.0.0.1:62661 "GAE GET http://tietuk
u.com/upload HTTP/1.1" 200 586
I0316 22:25:07.156197    5524 iplist.go:200] 127.0.0.1:62614 "IPLIST GET https:/
/groups.google.com/forum/var?inc=idle-timeout-active:1 HTTP/1.1" 204

这个难道说可用的由145个，总数200个？

另，这个图片怎么贴的，或是有什么可用外链图片的网站？

**Comment by jzp820927** [comment]
看错了，我说的是 goagent ，goproxy 好像不显示 IP 信息。现在还在开发阶段，估计以后会加上吧

**Comment by sishentibu** [comment]
也是用着gae的吗？我也是今天刚试了下gop，以前试了几次都看不了视频，今天用了下gray重新编译的貌似可以了 @jzp820927

**Comment by jzp820927** [comment]
主要还是看IP质量

**Comment by sishentibu** [comment]
现在是先dig，在checkip
能用先用着吧

**Comment by wangbingqian** [comment]
为什么扫出来的IP一会儿就挂了？间歇性封锁？

**Comment by jzp820927** [comment]
这几天IP变动很快，可能是某会有关系吧

**Comment by jasonliul** [comment]
@wangbingqian 
使用CheckGoogleIp, 把checkip.py改为使用openssl

#SSL 连接：0使用 OpenSSL，1使用 gevent
g_usegevent = 0

**Comment by wangbingqian** [comment]
@jasonliul 我试试

**Comment by blob2015** [comment]
@jasonliul 
这里面一共有10个【g_usegevent】，只是改最前面的？
> g_useOpenSSL = 1
> g_usegevent = 1【改这个就行了？】
---------------
之前也没在意这个快速失效问题。
在GA里面不用修改？只是查找出来使用openssl的ip就行了？
---------------
谢谢

**Comment by jasonliul** [comment]
@blob2015 

用SeaHOH改版, 有注释

#SSL 连接：0使用 OpenSSL，1使用 gevent
g_usegevent = 0

**Comment by jasonliul** [comment]
#388
黄狗里面怎么改, 俺也不知道

@社长, 社长把头埋进乳峰里不鸟俺, 所以答案应该是不能.

使用OpenSSL检测ip, 其实已经解决问题了, 几天前检测的4个, 现在依然全部是好的.
不过速度原本是430kb/s, 现在下跌到170kb/s

**Comment by xrwz007** [comment]
我也是这个情况唉，尼玛的，黄狗里的.py文件里有10个ssl字段，都改0-1吗

**Comment by jasonliul** [comment]
@xrwz007 

不能乱改, 还是聚众把社长揪出来暴打, 比较实在.

**Comment by xrwz007** [comment]
@jasonliul 原来如此，现在新扫的上百ip都是mmf下测过的有效ip，加进去一会就只剩个位数了，感觉是gfw有机器识别学习功能了，一会儿就发现并封锁了。艹

**Comment by vcteps** [comment]
@xrwz007 同

**Comment by blob2015** [comment]
@jasonliul 

> 还是聚众把社长揪出来暴打, 比较实在.

这个提议好

**Comment by jasonliul** [comment]
@xrwz007 
电信线路16:00-1:00 属于鸡瘟时段.

俺觉得是继续"旁路"思维, 之前DNS污染用的, 进入鸡瘟期, 把"旁路"变成必经, 这样显著增加你到达国际出口的时间, 方便层层垃圾审查.

有一个令人发笑的解决, 寻找一个真正https的网站
1.严格意义的https
2.页面元素花俏复杂
3.使用网站压缩, 例如Gzip技术.

这种网站直连的话, 会明显停顿片刻, 然后腹泻一样拼命发数据给你.
不限黄狗, 所有代理首先访问这类网站, 都能让速度跑起来, 然后破墙没辙.

这个方式提速, Gogo Heroku最快, 其次黄狗, 狗屁最慢. 速度跑起来以后, 狗屁表现最好, 稳稳当当直冲3000kbps.

GoGo Heroku
http://www.gogotunnel.com/

**Comment by jzp820927** [comment]
@jasonliul 能给个真正https的网站，满足你说的那3点要求的？

**Comment by jasonliul** [comment]
@jzp820927 
No, 天助自助者.
俺是基督徒, 不是上帝
