### ISSUE TITLE
r235, 配置文件眼花缭乱

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#396]
这版配置文件精简, 填写真的麻烦.

**Comment by jzp820927** [comment]
一般都是填写一次，以后升级的时候，直接备份，恢复。

**Comment by Kisesy** [comment]
还行，新版不错，看来代码基本重构完了，要添加autorange了，蛮期待的

**Comment by jzp820927** [comment]
一直在等 autorange，这个才是最重要的

**Comment by yeahwu** [comment]
@Kisesy 头像好评，autorange完成了再升级。

**Comment by Kisesy** [comment]
![aaaaaa](https://cloud.githubusercontent.com/assets/5843694/13878089/e8ff77d6-ed49-11e5-953c-cd13c2cfac16.png)

![201603-2](https://cloud.githubusercontent.com/assets/5843694/13878111/000b0918-ed4a-11e5-8934-cfe18332629e.png)

新版可以上6000了，但还是被goagent吊打

**Comment by yeahwu** [comment]
花样炫富，赶紧交出ip，缴枪不杀。

**Comment by Kisesy** [comment]
@yeahwu http://tieba.baidu.com/p/2960830129 头像

**Comment by Kisesy** [comment]
几个星期前的了
96.43.49.242|58.69.77.85|194.44.4.84|189.194.54.93|192.122.185.151|193.229.108.241|172.217.17.224|49.231.60.220|104.237.190.80|193.229.108.219|203.211.8.107|193.229.108.215|185.2.108.209|125.234.52.233|188.43.64.214|27.100.64.215|193.229.108.214|104.237.190.182|193.90.147.28|85.187.222.55|80.202.12.160|193.229.108.218|27.106.94.13|213.163.23.93|212.188.49.250|193.229.108.211|186.68.154.40|24.220.112.174|85.187.222.30|24.220.112.151|89.47.210.117|164.40.244.83

**Comment by vcteps** [comment]
@Kisesy 敢问兄台黄狗是怎么救活的？我这边不管填多少ip都是死，匪畜电信

**Comment by yeahwu** [comment]
@Kisesy 感谢，你这样让俺很惆怅呀，这要往goproxy一个一个填。

**Comment by Kisesy** [comment]
"96.43.49.242","58.69.77.85","194.44.4.84","189.194.54.93","192.122.185.151","193.229.108.241","172.217.17.224","49.231.60.220","104.237.190.80","193.229.108.219","203.211.8.107","193.229.108.215","185.2.108.209","125.234.52.233","188.43.64.214","27.100.64.215","193.229.108.214","104.237.190.182","193.90.147.28","85.187.222.55","80.202.12.160","193.229.108.218","27.106.94.13","213.163.23.93","212.188.49.250","193.229.108.211","186.68.154.40","24.220.112.174","85.187.222.30","24.220.112.151","89.47.210.117","164.40.244.83"

**Comment by yeahwu** [comment]
感谢kisesy兄，俺也来复活goproxy鸟。

**Comment by jasonliul** [comment]
@Kisesy 
居然还有你这等ip阔佬

**Comment by Kisesy** [comment]
@vcteps 电信难啊

**Comment by vcteps** [comment]
@Kisesy 悲剧了，头像（滑稽）

**Comment by yeahwu** [comment]
goproxy的性能果然不俗，居然轻易上3000kbps，

**Comment by Kisesy** [comment]
前几天硬盘格式化，什么都没了，不然IP应该更好点，现在扫出来的都不好用

**Comment by jasonliul** [comment]
@yeahwu 
早就习惯3000了, 下载速度也比较满.

这次损失最好的那些ip,只能用略差的. 狗屁依然坚挺, 黄狗有些下滑.

**Comment by vcteps** [comment]
@Kisesy 有没有重要文件，试试数据恢复

**Comment by yeahwu** [comment]
@jasonliul 最近一直在用xx-mini，速度也尚可。就是这几天被封了好多优质ip，速度有下滑。其实好久没用黄狗了，该淘汰了。感谢kisesy慷慨解囊。

**Comment by Kisesy** [comment]
@vcteps 真正重要的没有，我电脑上没有特别重要，就是我收集了好多年的资料什么的都没了，主要也是放的太碎了，恢复了一些，主要可惜了我以前写的代码，和一些网上也很难找到的东西
唉，钥匙只有一把，配都配不来

**Comment by jasonliul** [comment]
@yeahwu 
俺不舍得中国伪军, 不过最近也干扰了, ping值仅仅10几ms, 却很难被激活成为好ip.
电信白天还行, 总是有+1 ip, 下载AV满速而且不担心流量. 晚上就没意思了.

**Comment by Kisesy** [comment]
"189.215.200.31","61.91.161.165","189.194.54.107","216.68.10.160","24.220.112.154","96.43.49.250","193.229.108.213","104.237.190.189","203.211.8.106","193.229.108.243","193.229.108.229","216.68.10.178","193.229.108.251","193.229.108.242","104.237.190.175","96.43.49.245","24.220.112.182","203.211.8.76","216.58.194.180","203.211.8.105","45.64.30.25","164.40.244.76","212.188.49.225","189.194.54.113","193.229.108.212","193.229.108.225","96.43.49.240","193.229.108.224","192.232.16.114","193.229.108.217","201.157.30.12","58.69.77.88","206.80.249.119","203.211.8.100","203.211.8.79","23.228.130.23","78.11.253.226","192.232.16.104","192.122.185.154","61.91.161.142"

还有一些，不知好不好，我现在都不扫IP了

**Comment by yeahwu** [comment]
@Kisesy 重要资料全部放云端，俺就是这么干滴！呵呵，可惜仓老湿，啵多等，太大鸟！
@jasonliul +1 ip，俺也弄过，45开头的，那速度正是感人，可惜阵亡鸟。

**Comment by yeahwu** [comment]
@Kisesy 也不管好不好全部加进去鸟。感谢

**Comment by jasonliul** [comment]
@yeahwu 
仓老湿，啵多等, 果然是行家

俺现在+1的时候, 最好也就3400kbps, 以前基本都在4300以上

**Comment by thundery1** [comment]
上面的ip俺只有一个好使。。
