### ISSUE TITLE
Ip扫描新问题, 方案

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#408]
俺的方案是
1.放弃Gogotest, 使用CheckgoogleIP, 改用 OpenSSL模式
2. 电信用户必须白天正常时段测试ip. 瘟鸡时段16:00-凌晨1:00, 测试的结果相当水.
俺的意见是白天多测几次, 做成几个备用组.万一速度下降明显再换.

另一种意见:
cixi666 commented 2 hours ago

我想我可能已经知道了为什么扫好的ip.放进去马上就死掉，好像这次防火墙升级主要是对ssl_sock加密算法方法的干扰阻断，换个加密方式就行了.反正我这里换了这个加密方式之后，连接就正常了，再没有出现过马上死掉的现象。把ECDHE-RSA-AES128-SHA方式改成AES128-SHA方式，以goagent-3.23最后哪个版本为例，用notepad++打开proxylib.py文件，找到ciphers='ECDHE-RSA-AES128-SHA'，应该在1771行和1773行，然后改写成ciphers='AES128-SHA'，大家试试看。

**Comment by rothen80** [comment]
cixi666的方法暂时可用 ip复活大半 不过因为现在是半夜 不知道白天会怎样 总之感谢各位

**Comment by lsnmx** [comment]
@jasonliul 牛逼啊，PM一下社长直接支持吧

**Comment by Alvin9999** [comment]
按照cixi666 提供的方法测试了一下。如果是新的ip，改加密方法后确实bad ip很少（只有1个）。但这批ip一旦不改加密方法后，又会失效很多。失效了的ip再改加密方法就没用了。

**Comment by wangbingqian** [comment]
你改了别人不改，IP总是要挂的

**Comment by cixi666** [comment]
@Alvin9999 是这样，但死的ip过一段时间又会复活。

**Comment by jap33** [comment]
XX-Net 不知道什么时候都改了。用作还不错。但ip还是少了狠多。

**Comment by jasonliul** [comment]
@Alvin9999 
俺本来就改过加密方式, 
看起来是测试IP, 俺们需要新工具.

**Comment by xyuanmu** [comment]
我发现我这里改了也不行，很快还是会挂，不过刚才试用了下 OpenSSL 扫描IP发现CPU占用低了好多，更新到 checkiptools 了，有使用的赶紧更新吧！Linux下的OpenSSL需要自己安装。

**Comment by xrwz007** [comment]
改好了加密，用了一段时间，ip又不行了。看来是gfw针对的很厉害。goproxy现在能改加密方式吗

**Comment by phuslu** [comment]
@xrwz007 现在加密方式在 r275 以后已经改了.

**Comment by jasonliul** [comment]
@phuslu 

277 应该ok, 俺换了几组ip.

**Comment by Tubunu** [comment]
第二种方法成功复活，感谢
