### ISSUE TITLE
黄狗没死, 来点喜气

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#411]
http://s010.radikal.ru/i312/1603/9b/167712828604.png

怒扫ip Angry IP Scanner
#407

以及
@xyuanmu
https://github.com/xyuanmu/checkiptools

都可以搞定.

电信瘟鸡切换时段最糟糕, 16:00-17:00. 
所以狗照跑, 立照存念 LOL

**Comment by xyuanmu** [comment]
我黄狗差不多了，不过goproxy越来越好，今天下午用gop测试视频速度已经稳定的多了。

**Comment by jasonliul** [comment]
@xyuanmu 
那是因为你始乱终弃, 改玩XX狗.

黄狗一直没有死.

**Comment by lsnmx** [comment]
@jasonliul 黄狗容易假死，无奈换GP稍微好一点点

**Comment by xyuanmu** [comment]
不是这样的，黄狗现在IP挂得太快，出现这现象已经好几个月了，昨天改了加密方式也不奏效。不过→_→改了XX-Mini后就作为主力了，效果不错。

**Comment by jasonliul** [comment]
@lsnmx @xyuanmu 
俺强烈建议尝试Openssl检查ip, 或者Angry IP Scanner.

另外就是, **打开黄狗或GP, 首先连接一个严格的https网站, 而且页面元素复杂.**
俺能肯定破墙对于压缩数据,例如ssh, 或者网站压缩技术gzip是无能的, 或者网页超复杂, 数据传输很快.
一旦真正连接上, 你就已经被放行.

https://adblockplus.org/ 这种不是严格的https.

**Comment by liweitd** [comment]
@jasonliul 
能不能将checkiptools里的googleip导入到Angry IP Scanner？
或者说其他办法确定ip扫描范围？
谢谢！

**Comment by yeahwu** [comment]
坚持玩黄狗的，都是值得致敬的，毕竟上古时候的物件。应该改称“老狗”
xx-mini向你们致敬，简称“狗崽子“
xx-net "叉烧狗”
goproxy “狗屁”
下面欢迎@jasonliul补充

**Comment by lsnmx** [comment]
@xyuanmu 用你的神器狂扫几个EIP，现在3百个IP坚持了3个月还能用，向大神致敬

**Comment by jasonliul** [comment]
@yeahwu 
还有狗蛋
GoGo
http://www.gogotunnel.com/
