### ISSUE TITLE
希望大神出手改成8080端口 pac和全局的切换最好支持win10并且对宽带连接和局域网同时生效

### ISSUE THREAD

**Issue by 5fu** [phuslu/goproxy#414]
电脑配置低不想再安装扩展。希望大神出手修改一下。

有些时候需要8080端口，而默认是8087的连接不上，8000也连接不上。8080就可以连接。现在只能手动全局8080。

pac和全局的切换在win10下面只能对局域网生效，对宽带连接不生效，希望能同时生效。像shadowsocks客户端那样同时生效。我也知道shadowsocks客户端是用.net4.5编译。goproxy不是用.net 4.6编译的，但还是希望能实现这样的功能。

**Comment by jzp820927** [comment]
真没看懂是什么意思

**Comment by ARwMq9b6** [comment]
监听端口在配置文件里可以改。 ![]( https://i.imgur.com/h02qlcm.png )

**Comment by 5fu** [comment]
晕倒，goproxy默认的pac和全局代理的切换是端口8087的。我想大神改成8080的。而且在win10下，pac和全局代理的切换只对IE11设置里面的局域网生效，无法对IE11设置里面的宽带连接生效(就是ADSL拨号用户无法使用goproxy自带的pac和全局代理切换功能进行切换)

**Comment by 5fu** [comment]
监听端口是可以改，但切换的时候还是默认的8087.不是8080的。

**Comment by sishentibu** [comment]
虽然我也没看懂
然后猜改这个能不能达到效果
main.json中的第三行
	"Addr": "127.0.0.1:8087",
改为	"Addr": "127.0.0.1:8080",  
不清楚是否可行，反正试试也没事。。

**Comment by ARwMq9b6** [comment]
我这里右键托盘“设置 IE 代理”后，拨号栏和局域网栏都同时生效。 ![]( https://i.imgur.com/7BkUqwh.png )

**Comment by jzp820927** [comment]
你是说 switchy 插件导入的 bak 配置文件，里面的端口设置麽？

**Comment by ARwMq9b6** [comment]
关于端口更改，明白了，这个需手动修改 goagent.exe 这个启动包装器。方法是用 ResHacker 之类的软件修改。

**Comment by 5fu** [comment]
@ARwMq9b6 好像win7是没有问题的。win10下面的ie11就不行啊。我不知道你的什么系统

**Comment by ARwMq9b6** [comment]
#5fu 我的是 Win7...

**Comment by 5fu** [comment]
@jzp820927 不是switchy 插件导入的 bak 配置文件。goproxy本身就可以切换使用pac还是全局代理的，右键右下角的goproxy图标可以选择的

**Comment by 5fu** [comment]
@ARwMq9b6 改好了 谢谢指教！IE11设置里面的宽带连接好像没有内容，但好像也生效了。暂时顶一下先。

结贴！
