### ISSUE TITLE
海少改版checkgoogleip 新玩法

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#419]
海妞改版checkgoogleip 新玩法
https://github.com/SeaHOH/checkgoogleip

这个改版带中文注释, 最方便修改设置

当前的玩法, 
1. 预先筛选50个好ip, 作为eip.txt

修改checkip.py
2. 线程开50个,跟ip个数一致.
g_maxthreads = 50
3.使用openssl
g_usegevent = 0

4.其他
保留tmpok
g_autodeltmpokfile = 0

白天还是老一套, 从ip.txt挑选.
晚上瘟鸡时间, 从tmpok.txt里面挑选, 这个是依据**"线路连通性"**排序的, 挑选靠前响应快的ip.

老狗识途, 不要哭丧.

**Comment by sishentibu** [comment]
怎么自动排列tmpok里面的ip ？
我现在是再放到checkiptool 里排的

**Comment by hcym** [comment]
ip不缺

缺http2

**Comment by sishentibu** [comment]
从实际使用来看，ip_tmpok.txt 里面的ip不会再扫描的？

**Comment by jasonliul** [comment]
@sishentibu 
#需要得到的可用IP数量
g_maxhandleipcnt = 
把这个改小一些.

**Comment by jasonliul** [comment]
@SeaHOH
海少, 这个也该升级修补一下了.

**Comment by SeaHOH** [comment]
其实两个月前重新写了一个，不过在进行读取和保存部分时停工了（因为网络突然变得奇好）。
还有，这几天热起来了，懒癌发作~

不过按现在的形式，只要有大量 IP 就行了，反正 GoProxy 会自动筛选。
扫 IP 时把可用延时和超时稍微调大点就是了，不再是为了快速 IP 而扫描。

**Comment by jasonliul** [comment]
@SeaHOH 
你居然夏天养膘, 打pat~~

**Comment by SeaHOH** [comment]
养啥，咋没闻到好吃的呢~ :pig_nose: 
话说 pm 扩展修改也停了几天了，哪天凉快了继续。
