### ISSUE TITLE
绿色狗粮新标准 GB2016

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#422]
绿色狗粮新标准 GB2016

TTL 生存时间:
TTL初始值是64/128/256, 每转手一次, 它就自动减一. 差值最小的那些才是通连性高的.
-TTL: 俺新造的名词, ttl差值, 从网站到你处的中转次数, 越小越好.

随便找一把国外不涉政治的网站, 保留20个完全ping通的, 夜晚电信瘟鸡时段再ping, 被严重干扰的ip大概是1/3-40%的比例, 甚至更高.
俺怀疑这是墙监的所谓控制标准, 这是针对所有境外网站, 不是黄狗.

老朽没落民族, 最有力量的就是惯性与惰性. 利用这一点, 墙监也值得一赞!

现在需要首先考虑-TTL, 因为人为增加延时/丢包率, -TTL>30?[俺瞎猜的]的字段等于不存在, 即使你搜索ip, 它们也像星星一样闪烁.一旦填写进去, 立刻变成bad ip.目前大家的日韩字段-TTL基本都>30.

考虑人为增加的ping值, 俺觉得-TTL<30, ping<300ms的ip属于绿色狗粮. 是时候走出亚洲, 侵略欧洲ip了. 俺们要扶清灭洋, 榨干谷歌.

怀念一下近来被墙监致死的ip, 举烛默哀一下.

韩国 1.255.22.0/24 -TTL原来是4, 现在是63, 凭空增加中转59次.
澳门 202.86.162.0/24 -TTL原来是3, 现在是54.
日本 202.248.151.0/24 -TTL原来是6, 现在是54.

Add 达人mouseroser 警告
用的是魔都的电信，个人的感觉就是ip地址绝对不要放多，5个左右就可以了，绝对不要超过6个，不然有多少死多少！！！no zuo no die！！！

现在的情形, 过多bad ip只会浪费你的时间.

**Comment by yeahwu** [comment]
然而俺有扫ip神器叉烧狗，ip死了再扫嘛，多大的事。“叉烧狗”ip填入“狗屁”，妥妥的720p

**Comment by jasonliul** [comment]
@yeahwu 
你真邪恶,俺也从叉烧狗搞ip. 噗哈哈

**Comment by hcym** [comment]
TTL倒是没注意过

但是ip不一定要ping通也能用

尤其ubuntu 1604几乎都是ok，很可能openssl版本所致

同样的ip，1404最多ok一半

xp活的比较惨，勉强用用

**Comment by jasonliul** [comment]
@hcym 

因为1.255.22.0/24现在的TTL=1, 可见墙监们的怨妇情绪.
LOL

**Comment by hcym** [comment]
还有各位墙友

新的go版gae端怎么不能用？

lu老大没弄好还是我的配置问题

**Comment by phuslu** [comment]
@hcym 貌似是我没弄好. :(

**Comment by hcym** [comment]
谢谢老大

老的服务端也不错

**Comment by vcteps** [comment]
确实有用，“5个左右就可以了，绝对不要超过6个”，究竟放几个最好，我笨，看不懂

**Comment by yeahwu** [comment]
@vcteps 这就像上厕所，你是抽5张，还是6张纸，随便鸟

**Comment by vcteps** [comment]
@yeahwu 蛤蛤

**Comment by jasonliul** [comment]
@yeahwu 
俺cn4个, hk4个, 看来屁屁大, 木办法. LOL

**Comment by yeahwu** [comment]
原来你还有精品呀，俺这边吃粗粮的，300ms以内，胡乱抓了一把就往里面塞。
另外“狗屁”不能持久哇！干两下就萎鸟，得重新再上几粒“伟哥”才能再战！

**Comment by jasonliul** [comment]
@yeahwu 
最近电信夜间的丢包率太高, 西瓜吉吉都跑不动,还有百度盘.

俺有一个乌克兰的趣味程序, 根据ping值, 丢包率估算距离, 夜间上海->基辅, 居然估算9800公里.
看来东航宰俺的里程数. :)

**Comment by yj34306511** [comment]
@yeahwu 
叉烧狗是个什么扫ip软件？？？

**Comment by yeahwu** [comment]
@yj34306511 叉烧狗=XX-Net

**Comment by yj34306511** [comment]
@yeahwu 
明白
