### ISSUE TITLE
关于DNS黑名单配置这块作者写的有误

### ISSUE THREAD

**Issue by playnetcn** [phuslu/goproxy#425]
直接上配置，正确的黑名单配置。联通和电信通用，平时udp解析就这几个地址，特殊情况才会随机投放地址。所以这块建议改成这种。谢谢。
	"IPBlackList": [
     "159.106.121.75",
      "203.98.7.65",
      "243.185.187.39",
      "37.61.54.158",
      "59.24.3.173",
      "46.82.174.68",
      "78.16.49.15",
      "8.7.198.45",
      "93.46.8.89" 
	],

**Comment by phuslu** [comment]
希望能直接提个 pull request，很简单的哦。

**Comment by playnetcn** [comment]
@phuslu 我就是个小白，不是搞开发的，会的少，主要还是佩服你既了解网络通信技术原理，还会开发代码，这方面人还是比较少的。呵呵。

**Comment by phuslu** [comment]
呃, 你这太抬举了. 我是这个意思: 如果你提交 pull request 的话, 这样你的名字就会出现在 https://github.com/phuslu/goproxy/graphs/contributors 里面啦.

**Comment by jzp820927** [comment]
出现在 https://github.com/phuslu/goproxy/graphs/contributors 里面，有什么好处麽？

**Comment by phuslu** [comment]
r289 已经更新了

**Comment by jzp820927** [comment]
https://github.com/shadowsocks/ChinaDNS/blob/master/iplist.txt

这个是比较完整的 IPBlackList，就是不知道能不能添加这么多

**Comment by phuslu** [comment]
@jzp820927 gae.json 支持数量没有上限。 不过为了便于维护， 建议使用通配符形式来配置。

**Comment by jzp820927** [comment]
这些IP好像都是挺散的，看不出有什么关联，又不在一个段上，通配符，还挺不好弄得
