### ISSUE TITLE
珍稀前置

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#427]
212.21.56.255:1080
袜4/5, 显示为卫星提供商Satellite Provider, 也就是洋葱节点.

这类很罕见, 也不长命, 也有基于洋葱的ssh节点.

**Comment by sundaqing1969** [comment]
感谢提供

**Comment by yeahwu** [comment]
放个ssh帐号嘛，俺感觉ssh帐号比ip还难找

**Comment by yeahwu** [comment]
![2016-03-25](https://cloud.githubusercontent.com/assets/13328328/14041736/c64bc18a-f2ae-11e5-8a16-c8be4b995167.png)

**Comment by jasonliul** [comment]
@yeahwu 
俺之前几个洋葱ssh也死了, 不长命.

俺的主打一直是SSH, 巴林的你都用不完.
凡是巴林的节点, 基本都可以用admin/admin, 或者guest/guest, 1/3在天朝是满速的.

巴林等于网络摩洛哥, 很多船只都注册在它旗下.
俺另外偏爱的是哥斯达黎加, 基本都是满速, 比美加墨还要好.

**Comment by yeahwu** [comment]
你说的这些话都相当于socks5加密，GFW都解不开
```
俺之前几个洋葱ssh也死了, 不长命.

俺的主打一直是SSH, 巴林的你都用不完.
凡是巴林的节点, 基本都可以用admin/admin, 或者guest/guest, 1/3在天朝是满速的.

巴林等于网络摩洛哥, 很多船只都注册在它旗下.其实等于没人管的.
俺另外偏爱的是哥斯达黎加, 基本都是满速, 比美加墨还要好.
```

**Comment by lsnmx** [comment]
想长命就自己组个VPS装种神器吧

**Comment by jasonliul** [comment]
@yeahwu 
SSH不属于公益代理资源, 之前有些墙国的所谓大佬分享过, 结果是被政府堂而皇之地抓捕.

SSH属于范围分享, 例如俺注册一些软件, 视频网站就有公用ssh, 这个不能所谓"分享", 可以带来严重的法律问题.

**Comment by yeahwu** [comment]
@jasonliul 其实，俺就是说说，j兄不要介意。了解鸟

**Comment by jasonliul** [comment]
@yeahwu 
扫描端口自己玩的软件很多,自己动手不难.
但是ssh不可以公开分享的.这和http/袜子代理不同.

政府可以侵犯你的人权, 但是你分享ssh等于国际通用的黑客罪名, 反而政府可以抓你,
所以很少能见到分享, :)
