### ISSUE TITLE
关于autorange文件配置交流

### ISSUE THREAD

**Issue by playnetcn** [phuslu/goproxy#429]
以下是我日常使用时候的配置，"maxsize": 1048576和"bufsize": 16384个人觉得这个值比较适合，播放视频缓存较流畅，threads这个值个人觉得配置3至8之间，sites不会配置使用默认就可以或者根据实际来配置。suffixs就把常用的格式加了上去。

	"autorange": {
		"threads": 6,
		"maxsize": 1048576,
		"bufsize": 16384,
		"sites": [
             根据实际需求来写或者使用作者默认配置],
		"suffixs": [
			"*.avi",
			"*.dmg",
			"*.f4v",
			"*.flv",
			"*.hlv",
			"*.iso",
			"*.m4v",
			"*.mp3",
			"*.mp4",
			"*.ogg",
			"*play*",
			"*.mov",
			"*.mpeg4",
			"*.wmv",
			"*.mpegps",
			"*.3gpp",
			"*.webm",
			"*.mkv",
			"*.zip",
			"*.rar",
			"*.exe",
		]
	}
}

**Comment by jzp820927** [comment]
autorange 不是还没做完么

**Comment by phuslu** [comment]
亲，还未做完， 肯定 bug 一堆， 性能也还不够，请给点时间。 :)

**Comment by playnetcn** [comment]
@phuslu和@jzp820927我说的是旧版本goproxy和goagent里面配置，当时我反复测试过这个配置，这个区间的值播放视频效果好。

**Comment by yuan18** [comment]
留个记号。。。。。。

**Comment by luonavy** [comment]
phuslu commented 17 hours ago
亲，还未做完， 肯定 bug 一堆， 性能也还不够，请给点时间。 :)

想不到社长也有这么亲和的一面，一直以为社长是一个比较严肃的人。

**Comment by cixi666** [comment]
好期待完整版的发布.
