### ISSUE TITLE
GWS ip貌似不能扫到了，突然全体被封了

### ISSUE THREAD

**Issue by sundaqing1969** [phuslu/goproxy#433]
只能扫到GVS ip了，这是什么情况？现在可以扫到10000多ip，什么情况？特此报告

**Comment by angle1895** [comment]
ga证书？
![qq 20160327203741](https://cloud.githubusercontent.com/assets/4709543/14065441/d68e58ce-f45b-11e5-855e-6fa37bbccbe6.png)

**Comment by sundaqing1969** [comment]
楼上兄，推荐一下你的扫描工具

**Comment by angle1895** [comment]
https://github.com/azzvx/gogotester

**Comment by sundaqing1969** [comment]
感谢

**Comment by pug908** [comment]
测试一下击穿GFW而已

**Comment by yqy6611** [comment]
gvs也可以用啊
