### ISSUE TITLE
一堆IP复活

### ISSUE THREAD

**Issue by jkng** [phuslu/goproxy#434]

**Comment by jkng** [comment]
![Uploading QQ图片20160327210123.png…]()

**Comment by jasonliul** [comment]
奇怪, 估计现在玩狗的太少, 搞得部门裁员.
为了养寇自重, 特意放粮三天 :)

**Comment by jap33** [comment]
一堆IP复活多的又死了

**Comment by CNMan** [comment]
抽风而已
https://www.google.com/transparencyreport/traffic/explorer/
![img](https://i.imgur.com/FgN4bxX.jpg)

**Comment by jasonliul** [comment]
@CNMan 

俺觉得前阵打狗太多, 破坏了生态平衡,
这次墙监所是故意放水, 巴不得狗友奔走相告.

重新恢复"遛狗形势严峻"

**Comment by yeahwu** [comment]
嗯，不过是丢你一个枣，后面还有一巴掌呢！

**Comment by jasonliul** [comment]
答案揭晓, 破墙的新筛选规则, 可以过滤掉更多ip.
存活者ping值也有增加.
