### ISSUE TITLE
SSH 玩家闲聊

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#437]
一.工具

普通用户
基于Putty套装Plink, 仅仅是前台界面
Klephon 使用赛风的OSSH节点, 带流量混淆
https://sourceforge.net/projects/klephon/files/?source=navbar
MyEnTunnel 
http://nemesis2.qx.net/pages/MyEnTunnel

注意及时更新plink
Plink
http://www.chiark.greenend.org.uk/%7Esgtatham/putty/download.html

高手瘾大者
Putty
http://www.chiark.greenend.org.uk/%7Esgtatham/putty/download.html
KiTTY 
http://kitty.9bis.net/
ExtraPuTTY
http://www.extraputty.com/
Putty功能远不止ssh, 大材小用, 配置麻烦.

BitviseSSHClient 
https://www.bitvise.com/ssh-client-download
现在最值得一提的是两点, 自身支持便携.
添加了流水线pipelining, 之前火狐才有, 流水线并不能真正提高什么速度.
但是可以大幅增加代理的连接稳定性.

二. 节点
Free SSH [印尼墙友]
https://fastssh.com/
http://create.sshgoogle.com/
http://go-ssh.com/sshserver/ssh-server.html
http://godssh.com/
http://www.sshagan.net/
http://www.mytunneling.com/ssh-server-new
https://white-vps.com/
https://www.highssh.com/
http://skyssh.com/

更改关键词, 还能搜索到更多, 包括印尼语网站.

三. 提示
1.大部分都有注册3天/7天, 注意选择7天, 不过得看点广告.

2.开启ssh客户端压缩传输, 当今很难找到不支持压缩的ssh服务器.
使用压缩传输那是超速, 不只是满速. 俺的4M电信, 测速可以是700-800k/s.

3.有些免费ssh, 已经提供乌贼前置[Sqiud], 一定要留意.
这类乌贼只支持ssh/vpn客户端, 而且有各种个性限制, 因此普通proxy搜索技术, 根本就找不到.

设置在客户端, 万一破墙干扰ssh, 开启乌贼就ok. 破墙要定点清除, 其实很费事. 俺个人认为破墙不会再公开干扰ssh/vpn, 这类国际通用隐私工具.

四, 其他合法免费ssh
只要带有ftp功能的国外软件, 视频, 个人作品分享的网站, 尤其是有很多upload上传的, 大多数会提供免费ssh保障文件传输安全, 只需要注册一次, 带宽大无限制.

五. 无限ssh, 地下网络

ssh来源主要是三种
付费网络服务, 例如建站, 赠送ssh.
网站的上传型ftp, 主流的ssh服务器只有7,8种, 通用帐号很多不会改, 方便用户匿名上传.
旅游国家的网咖, 简单帐号,方便游客.

发布破解ssh帐号, 是国际通用黑客罪名, 而且被侵权方一定会动用法律手段, 这是标准版的侵害他人互联网隐私和安全.

破解ssh是地下网络的"专属免费"资源, 很初级的知识, 大家都会玩. 没有人会容忍有人大规模拿这些"专属免费"晒太阳. 或者组团滥用.

说白了,这是黑道白道都痛恨的玩意. 5,6年几个爱沙尼亚黑客破解过一次50万精品ssh[最杰出的ssh破解]并且发布, 被捕坐牢还真是神速. 印尼, 越南也曾有过这种案例. 

现在印尼都是合法免费ssh, 越南收集各种袜子, http前置, 本来是方便墙友翻墙用途, 现在也发展成很廉价的付费前置服务, 每月几块人民币, 保证随时提供不低于几百条可用袜子.

无限ssh, 自己玩玩就好. :)

**Comment by jzp820927** [comment]
不错，涨见识了

**Comment by yeahwu** [comment]
Linux上的putty客户端很精美，配置也不算复杂。只是ssh帐号是真不好找，然后以前有人提取过赛风内置的ssh帐号。
窃以为ssh这玩意不适合大众把玩，算是文物。配置复杂，帐号难寻。

**Comment by jasonliul** [comment]
纸飞机出现, ssh在天朝不可能流行的

**Comment by yeahwu** [comment]
纸飞机主要是全平台，大家接受度好得多，即使付点小钱。

**Comment by CHN008** [comment]
嗯 先了解一下 等需要了去研究一下
