### ISSUE TITLE
粮荒恶化, 老狗犹勇

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#439]
http://s018.radikal.ru/i512/1603/52/020d8785844f.png

老黄狗果然犀利...
最近狗粮危机严峻

**Comment by hcym** [comment]
没有吧

东南亚东北亚许多IP都恢复了

没必要担心，土匪寿命肯定比谷歌段

就怕谷歌GAE下线，和googlereader下线一样

比共匪还缺德

**Comment by mixool** [comment]
如果GAE下线 好可怕！ 现在我的主力武器就是goproxy。

**Comment by xc1988** [comment]
最近能扫出来一堆IP，但是一用就被封掉

**Comment by yeahwu** [comment]
一不小心打开叉烧狗扫出的ip，延时300ms以内的2000个，一看就是老方直肠又赌鸟！

**Comment by jasonliul** [comment]
@xc1988 
这倒不是, 不过这些ip很不稳定.
转眼又会消失.

**Comment by me-dos** [comment]
你开玩笑，欧盟我都扫到几个gws、gvsip段。延时300ms以内

**Comment by me-dos** [comment]
80.239.174.0/24
80.239.229.0/24
64.233.178.0/24

可以备用

**Comment by angle1895** [comment]
狗始终老的辣
