### ISSUE TITLE
r305, Goproxy持续OK

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#441]
跟GoAgent不一样, 新版出来, 多少有些bug.
看起来go语言好得多, 一路平顺

**Comment by phuslu** [comment]
谢谢鼓励。

goproxy 算是我的反思之作，两点不同吧
1. 架构比较解耦， 新功能基本上不会 break 现有功能
2. 使用 go 语言，编译期就能检验很多弱智的编程错误。

**Comment by fletchere** [comment]
306也持续不错，赞。

**Comment by pgz123** [comment]
好期待正式版。再次感谢社长

**Comment by pug908** [comment]
技术只是手段，观察解析GFW才是王道

**Comment by KwToPA** [comment]
请问在哪里能下载r305 r306，我在release上只看到goproxy r278  谢谢
Where I can find the release r305 or r 306 ? I can only download  goproxy r278 in release. Thanks very much

**Comment by jzmswe** [comment]
点击每日构建版的右边。

**Comment by zhhzq** [comment]
https://github.com/phuslu/goproxy-ci/releases

**Comment by playnetcn** [comment]
@phuslu  r306测试了一下，效果不错。
最近几天包括整个主域名 Google.com 和 google-analytics.com 等在内的域名在国内被污染，我发现我省的联通除了那几个固定的IPBlackList，有的还会将IPBlackList指到本省的ip地址或者国外IP，当然固定几个。其它省不知道是否有这种情况，如果有就需要各自根据自己的省的情况来配置IPBlackList里面的IP了。

**Comment by KwToPA** [comment]
@zhhzq  @jzmswe  谢谢
我用的r278  找不到gogagent-osx.command   而且 报错
[https://github.com/phuslu/goproxy/issues/443](url)

**Comment by phuslu** [comment]
@playnetcn 是的，所以当初我就选择了通配符来作为配置项
