### ISSUE TITLE
GoAgent 终于可以退休了

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#449]
同样的ip组, GoProxy直奔3400kbps, GoAgent已经获得+1 ip, 却依然只在2400左右徘徊.

**Comment by angle1895** [comment]
r323？用之前版本下载速度和股市一样开始基本满速20秒左右后落至个位数又升回1-2m之后就只有几百k。

**Comment by Lynchie** [comment]
R323是不是正式版呢？

**Comment by phuslu** [comment]
一方面是 go 语言比较高效， 另一方面是 goagent 针对恶劣条件做了很多错误处理。

两方面造成这个表象。

**Comment by mixool** [comment]
Goagent现在就只用来部署服务端了。

**Comment by drg78rgjui** [comment]
好奇GoProxy有没有对高延时ip做优化200-300ms，如果可以澳洲和俄罗斯的ip真是取之不尽天下无敌

**Comment by phuslu** [comment]
@drg78rgjui 从原理上说， goproxy 更愿意 keepalive 链接，所以应该支持不错。

**Comment by blob2015** [comment]
反正听不懂，是不是大概就是在说，要开始抛弃黄狗，而是要开始GP新生活了？
