### ISSUE TITLE
Some correspond to massless particles like the photon

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#452]
is a function defined on a subset I of the set R of real numbers. This subset I is referred to as the domain of f. Some possible choices include I=R, the whole set of real numbers, an open interval
A function from the set of real numbers to the real numbers can be represented by a graph in the Cartesian plane; such a function is continuous if, roughly speaking, the graph is a single unbroken curve with no "holes" or "jumps".

**Comment by lsnmx** [comment]
"RoundTrip": [
			"autoproxy",
			// "auth",
			// "vps",
            // "php",
			"gae",
			"direct"

**Comment by MeABc** [comment]
看日志提示 filters.GetFilter("gae") failed
这应该是 gae.json 文件出错,而不是 main.json 文件出错.

Err:"|"  这个应是格式不对.  看 #243

**Comment by caofengzi** [comment]
这样设置。

       "RoundTrip": [
        "autoproxy",
        // "auth",
        // "vps",
        //"php",
         "gae",
        "direct"

**Comment by phuslu** [comment]
r332 版本以后就不需要非常严格的 json 格式了， 末尾带不带逗号都可以。
