### ISSUE TITLE
高匿名https前置, 狗族新玩法

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#457]
高匿名https前置, 狗族新玩法

216.220.165.62:8080
193.49.43.206:8080
128.199.150.146:1080
52.37.191.225:3128
149.202.249.227:3128
168.63.24.174:8118
178.62.129.215:80
178.155.14.10:8080
91.242.44.251:80
38.83.105.194:8118
158.69.217.163:3128
92.46.122.98:3128
61.7.149.69:8080
8.26.61.69:8080
110.77.141.82:3128
8.26.61.70:8080
1.179.201.18:3128
8.26.61.71:8080
222.124.145.194:3128
91.221.61.242:3128
202.69.40.173:8080
193.39.118.19:3128
80.70.75.13:3128
200.94.17.244:8080
113.53.255.242:3128
185.12.60.81:80
51.254.119.191:3128
81.192.217.52:8080
5.56.27.175:3128
203.194.109.142:3128
200.94.75.212:3128
128.199.205.169:3128
181.143.229.122:3128
181.211.253.14:8080
76.122.144.58:21320
190.144.114.2:3128
201.90.120.194:3128
186.27.126.130:80
189.111.183.125:3128
190.202.116.101:3128
190.52.39.238:80

黄狗可以修改ini, 采用默认域名, 不要填写ip.
GoProxy可以试用SocksCap64运行, 其他代理程序其实都可以用. 

前置是反审查软件的保护伞.

俺无法保证你的线路这些都可用, 你还得自行检查

在线速查
http://www.checker.freeproxy.ru/checker/

精细检查
https://www.proxifier.com/proxychecker/
这个可以检查丢包率, 精选优质前置必备.

**Comment by meooxx** [comment]
502 错误 怎么情况 填写之后

**Comment by meooxx** [comment]
这个 怎么用的 作用是什么

**Comment by Yamazaki-wu** [comment]
作为SSR前置不知道能不能用，在线筛选出一些，一个复制粘贴效率好低。

**Comment by Yamazaki-wu** [comment]
一个一个复制粘贴，筛选出的多半在SSR上都可以使用，但是速度很不理想。

**Comment by jasonliul** [comment]
@Yamazaki-wu 
代理猎手(Proxy Hunter) 很早就有, 而且是天朝的

**Comment by Yamazaki-wu** [comment]
@jasonliul 谢谢！

**Comment by blob2015** [comment]
代理就是需要不停扫 :grinning:
