### ISSUE TITLE
精英GIP列表阵亡, IP还是有的

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#458]
@CNMan @xyuanmu
两位大大的精英GIP列表阵亡, 感谢有劳!

不在这名单的字段还是有, 不过看来狗族进入自力更生时代. LOL

各位叉烧狗XX Net用户, 以及从精英列表沾光的人士.
可以列队默哀送行了

**Comment by panpeach** [comment]
从未舍弃过黄狗，现在凑合着还能用。

**Comment by drg78rgjui** [comment]
免惊，200ms-500ms内的ip几乎是无限的。

你用ZoomEye搜一下就知道，俄罗斯有两万个gws，还不算gvs，加拿大都有七千个

**Comment by jasonliul** [comment]
俺只剩两枚

**Comment by jzp820927** [comment]
@drg78rgjui 高延时的，不晓得视频效果怎么样

**Comment by panpeach** [comment]
https://lh3.googleusercontent.com/1qyvkm-MfMw7FF3l_KVsuSjp6skQZTdNsDpCX4K3ho_jzPmB6cgKFTgvr57azcV07VbnaOsZlEJW9rTc-ZJy-2a7L__cqo3PXcR3nANXL4_FPa2eb5TXhuBT9M8sXnFHUWYCHs5v7mWUT9Ad-cHrGaHkL_NFoR8QU5lEMLuBi0ydE80p6zaASEUWmSOPuYrkSSLTnvho_M1XL4rvs_TFaUWqBhsCZp3FdE-aaumeB82M8kW1l0KM3EBdDaKUwzl8RRlA2CYcuZvgaTLX2NWAx8-OGvh5dW0yOcGOg6iO04gUFeg20wJy8qjAo__SmjIU8tzvyto8VcCw7mcbbIvyPEkqde2VP-s2Pbsr-5JLQdwzhivG13JbNNz5ITSbZImREPyW_NcH-YywlOCuhc6vXAkoOztJ_l36knWDXEQR29sQK8Ifo4ORLuu29VEaQW-7PgABysTMefHL4pXSN6QdZF8Xb0_FXRK6VO87RI3nCGuMJhbEzbtuw4jEnYkyYyQkiJd7cs5GC80U7_QCHPlFduF410eGg8onY10rrgc10KP5mmermqQoAmox7YdLnJNEmY8=w759-h581-no

**Comment by hcym** [comment]
全面V6

岁月静好现世安稳

**Comment by xyuanmu** [comment]
目前还有几段残存的，这次封锁好比去年gvs刚问事那次，不过手头多几个工具还是很有帮助的，根据以往经验，IP慌只是暂时的，祝大家愚人节快乐。

**Comment by yeahwu** [comment]
大家有ip就赶紧甩出来，俺先来，凑合凑合大家就都能用鸟
https://github.com/XX-net/XX-Net/files/199536/ip_range.txt﻿

**Comment by xyuanmu** [comment]
@yeahwu 这份IP看着好眼熟。另外问下怎么上传这种文件，直接可以下载的？

**Comment by yeahwu** [comment]
这份ip就是你那份ip，然后俺另外添加了一些ip段。直接点selecting them上传就好鸟。

**Comment by xyuanmu** [comment]
原来还可以上传txt，谢谢。

**Comment by yeahwu** [comment]
不客气，私货，啥的甩出来哦

**Comment by yj34306511** [comment]
收到了 谢谢 哈哈

**Comment by yj34306511** [comment]
@drg78rgjui 
请教ZoomEye怎么搜google ip

**Comment by cixi666** [comment]
http://www.zoomeye.org/vision/map/gws

**Comment by yj34306511** [comment]
@cixi666
怎么提取是个问题

**Comment by fletchere** [comment]
@cixi666 感谢，又可以摸奖了！

**Comment by jzp820927** [comment]
这么大的数据流，怕是摸奖要把手摸断哟

**Comment by drg78rgjui** [comment]
@fletchere 
现在摸奖没有什么意义，前50页的ip九成被封。
这个唯一的作用是让你看到一个国家有多少ip，然后开高延时，扫描俄罗斯的全部ip

**Comment by jasonliul** [comment]
@drg78rgjui 

俄国也是严重干扰区域, 俺之前有290条远东袜4节点,  平时总是30几条高中速, 
被墙监增加丢包率/ping值, 现在仅仅几条可用.

**Comment by drg78rgjui** [comment]
@jasonliul 波兰怎么样？在欧洲国家中拥有最多的gwsip
我之前查是5000个

**Comment by jasonliul** [comment]
@drg78rgjui 
可以强搜, 这两天俺使用在线应用摸奖, 情况很不乐观.

破墙封杀是依据服务器类型的, 说什么依靠证书属于扯淡.
之前破墙已经封杀GWS, GFE, 基本上谷歌前台, 公开合作的GCC的Gip就死光光了.

这次明显加入了sffe类型, 俺们现在能用的全部是这类. 属于谷歌内部或者中间商的gip. 
欧洲一些小国家国家, 比利时, 安道尔之前的那些sffe, 现在能检测, 但是全部端口被封.

俺比较倾向中美洲, 例如哥斯达黎加, 那些岛国比较乱, 类似亚洲之前的菲律宾.

**Comment by drg78rgjui** [comment]
@jasonliul 此外，也可以考虑非洲了，之前看地图，马来西亚有海底光缆直通马达加斯加。
我这里ping南非350+ms 中美洲速度反而不行

**Comment by jzp820927** [comment]
IPV6 都只有教育网用，有必要封麽

**Comment by hcym** [comment]
邪教立国

东西朝鲜还不定谁先挂
