### ISSUE TITLE
php模式速度稳定 自动720P

### ISSUE THREAD

**Issue by mixool** [phuslu/goproxy#460]
以前部署的 在这个时间点都没这么快 这是autorange的特效么？
移动网络。
版本正式版 328.

**Comment by mixool** [comment]
好吧，运行一会后速度又恢复300kbps了，还有中断现象，看来刚才的2200kbps是短暂的幸福。

**Comment by jkng** [comment]
![Uploading QQ图片20160402005000.png…]()
