### ISSUE TITLE
70残兵, 继续遛狗

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#461]
盘点一下, 还有70多残兵.

无事, 继续遛狗.r328

**Comment by HF-Enigma** [comment]
全体阵亡了，是时候学习其他技术了

**Comment by pug908** [comment]
IPV4网络环境下开始启用IPV6&DTLS

**Comment by mouseroser** [comment]
这两天疯狗开始乱咬人了，看来上面斗得越来越厉害了，no zuo no die ！！！

**Comment by dannymtseng** [comment]
checkgoogleip还能扫出一些
https://github.com/moonshawdo/checkgoogleip

**Comment by yeahwu** [comment]
无奈，唤醒php的路过

**Comment by drg78rgjui** [comment]
压箱底货也贡献出来了。。。。ip没了大不了再扫过。翻过的人都知道，有什么可失去的？

印尼
66.96.226.0/24

马来西亚
202.75.141.0/24
202.75.147.0/24

泰国

61.91.161.0/24

**Comment by jasonliul** [comment]
http://www.blackhatworld.com/blackhat-seo/youtube/640431-thousands-youtube-google-ips-proxies.html

透明代理现在没有用, 但是这些字段不是谷歌家, 也不是合作方.
而是租给谷歌用.

俺的残兵基本都从这里扫到的.

**Comment by dannymtseng** [comment]
贡献。。
74.125.0.60 2000 *.c.docs.google.com gvs 1.0
210.2.185.105 3453 *.googlevideo.com gvs 1.0
74.125.1.38 2079 *.c.docs.google.com gvs 1.0
84.54.161.32 2719 *.googlevideo.com gvs 1.0
61.91.18.108 4156 google.com gws
103.233.37.18 2156 *.googlevideo.com gvs 1.0
210.2.185.96 2687 *.googlevideo.com gvs 1.0
101.78.13.25 1016 *.googlevideo.com gvs 1.0
222.165.163.90 2953 google.com gws
115.254.121.233 3407 *.googlevideo.com gvs 1.0
189.58.99.184 16516 *.googlevideo.com gvs 1.0
210.2.185.93 2938 *.googlevideo.com gvs 1.0
115.254.106.244 1547 *.googlevideo.com gvs 1.0
115.254.121.239 2125 *.googlevideo.com gvs 1.0
173.194.77.117 6282 upload.video.google.com gws
222.165.163.84 3406 google.com gws
49.231.60.40 4829 *.googlevideo.com gvs 1.0
110.164.14.45 16594 *.googlevideo.com gvs 1.0
173.194.67.116 1375 upload.video.google.com gws
103.233.37.87 2234 *.googlevideo.com gvs 1.0
200.3.21.223 8500 *.googlevideo.com gvs 1.0
119.9.76.67 5172 *.google.com gws
177.136.113.204 1515 *.googlevideo.com gvs 1.0
1.255.33.155 8000 *.googlevideo.com gvs 1.0
223.196.4.62 1344 *.googlevideo.com gvs 1.0
74.125.1.43 1406 *.c.docs.google.com gvs 1.0
115.254.106.227 2360 *.googlevideo.com gvs 1.0
208.65.153.223 11641 *.googlevideo.com gws
173.194.151.19 2328 *.c.docs.google.com gvs 1.0
173.194.67.123 4437 wifi.google.com gws
36.83.12.56 2000 google.com gws
103.233.37.14 2250 *.googlevideo.com gvs 1.0
103.233.37.112 1672 *.googlevideo.com gvs 1.0
115.254.106.228 1734 *.googlevideo.com gvs 1.0
210.2.185.94 2344 *.googlevideo.com gvs 1.0
115.254.121.206 2750 *.googlevideo.com gvs 1.0
173.194.67.191 1406 *.blogger.com gws
210.2.185.108 5797 *.googlevideo.com gvs 1.0
115.254.121.243 3454 *.googlevideo.com gvs 1.0
115.254.97.114 1172 *.googlevideo.com gvs 1.0
104.237.172.36 1438 *.googlevideo.com gvs 1.0
115.254.121.234 1906 *.googlevideo.com gvs 1.0
201.157.30.24 1579 google.com gws
103.233.37.12 2172 *.googlevideo.com gvs 1.0
115.254.121.225 1219 *.googlevideo.com gvs 1.0
115.254.121.207 1234 *.googlevideo.com gvs 1.0
103.233.37.92 2437 *.googlevideo.com gvs 1.0
115.254.121.246 1969 *.googlevideo.com gvs 1.0
210.2.185.122 3563 *.googlevideo.com gvs 1.0
74.125.1.25 1156 *.c.docs.google.com gvs 1.0
177.136.113.206 2109 *.googlevideo.com gvs 1.0
173.194.16.89 2062 *.c.docs.google.com gvs 1.0
222.165.163.85 2734 google.com gws
36.37.218.14 1719 *.googlevideo.com gvs 1.0
222.165.163.91 7938 google.com gws
74.125.1.46 2282 *.c.docs.google.com gvs 1.0
177.136.113.243 2703 *.googlevideo.com gvs 1.0
66.96.224.222 2531 google.com gws
210.2.185.114 2687 *.googlevideo.com gvs 1.0
173.194.67.145 1297 *.fr.doubleclick.net gws
210.2.185.89 2625 *.googlevideo.com gvs 1.0
24.226.16.150 19656 *.googlevideo.com gvs 1.0
95.154.114.79 5125 *.googlevideo.com gvs 1.0
210.2.185.77 2375 *.googlevideo.com gvs 1.0
202.248.151.98 3891 *.googlevideo.com gvs 1.0
210.2.185.118 2235 *.googlevideo.com gvs 1.0
74.125.26.98 9047 *.google.com gws
101.78.13.51 641 *.googlevideo.com gvs 1.0
115.254.106.236 1891 *.googlevideo.com gvs 1.0
210.2.185.119 6359 *.googlevideo.com gvs 1.0
173.194.151.30 2156 *.c.docs.google.com gvs 1.0
74.125.1.39 1125 *.c.docs.google.com gvs 1.0
210.2.185.78 2219 *.googlevideo.com gvs 1.0
210.2.185.79 2485 *.googlevideo.com gvs 1.0
173.194.151.16 10360 *.c.docs.google.com gvs 1.0
212.20.34.185 12875 *.googlevideo.com gvs 1.0
101.78.13.52 734 *.googlevideo.com gvs 1.0
101.78.13.32 922 *.googlevideo.com gvs 1.0
210.2.185.92 3265 *.googlevideo.com gvs 1.0
173.194.67.152 1234 tpc.googlesyndication.com gws
177.43.235.46 13609 *.googlevideo.com gvs 1.0
115.254.121.210 1703 *.googlevideo.com gvs 1.0
204.186.215.54 14203 *.googlevideo.com gvs 1.0
115.254.121.221 5453 *.googlevideo.com gvs 1.0
173.194.151.15 1859 *.c.docs.google.com gvs 1.0
210.2.185.116 2765 *.googlevideo.com gvs 1.0
74.125.1.23 1890 *.c.docs.google.com gvs 1.0
103.233.37.15 1578 *.googlevideo.com gvs 1.0
115.254.121.245 1375 *.googlevideo.com gvs 1.0
173.194.2.72 2031 *.c.docs.google.com gvs 1.0
173.194.151.13 2016 *.c.docs.google.com gvs 1.0
210.2.185.81 3203 *.googlevideo.com gvs 1.0
74.125.1.22 1031 *.c.docs.google.com gvs 1.0
173.194.151.17 1907 *.c.docs.google.com gvs 1.0
74.125.1.15 1000 *.c.docs.google.com gvs 1.0
173.194.67.81 1188 sandbox.google.com gws
173.194.151.1 2547 *.c.docs.google.com gvs 1.0
222.165.163.83 4109 google.com gws
124.248.162.54 6656 *.googlevideo.com gvs 1.0
173.194.67.219 3953 *.googleapis.com gws
210.2.185.98 2813 *.googlevideo.com gvs 1.0
101.78.13.56 921 *.googlevideo.com gvs 1.0
103.233.37.93 1687 *.googlevideo.com gvs 1.0
115.254.121.219 2203 *.googlevideo.com gvs 1.0
115.254.121.223 1813 *.googlevideo.com gvs 1.0
103.233.37.84 1797 *.googlevideo.com gvs 1.0
220.255.2.153 1844 google.com gws
101.78.13.21 1016 *.googlevideo.com gvs 1.0
210.2.185.120 4516 *.googlevideo.com gvs 1.0
101.78.13.35 1562 *.googlevideo.com gvs 1.0
103.233.37.13 2047 *.googlevideo.com gvs 1.0
115.254.106.209 1750 *.googlevideo.com gvs 1.0
115.254.121.224 1296 *.googlevideo.com gvs 1.0
173.194.67.164 1172 *.googleadservices.com gws
115.254.121.220 2000 *.googlevideo.com gvs 1.0
173.194.151.32 2047 *.c.docs.google.com gvs 1.0
210.2.185.97 2578 *.googlevideo.com gvs 1.0
210.2.185.103 3016 *.googlevideo.com gvs 1.0
173.194.31.184 1437 *.c.docs.google.com gvs 1.0

**Comment by yeahwu** [comment]
感谢大家，俺也来整理一下ip段，让大家都用上

**Comment by xyuanmu** [comment]
刚入手的，大家看看有木有合适的：
111.95.240.0/24
123.108.252.0/24
188.43.68.0/24
217.18.145.0/24

**Comment by yeahwu** [comment]
@xyuanmu 给力

**Comment by ARwMq9b6** [comment]
@dannymtseng @xyuanmu 谢谢，用上了，重新起飞。

**Comment by dannymtseng** [comment]
继续贡献。。。
210.2.185.104 3765 *.googlevideo.com gvs 1.0
210.2.185.115 6953 *.googlevideo.com gvs 1.0
222.165.163.87 3078 google.com gws
113.171.244.209 1610 *.googlevideo.com gvs 1.0
173.194.67.115 1718 checkout.google.com gws
173.194.57.176 2594 *.c.docs.google.com gvs 1.0
210.2.185.87 3750 *.googlevideo.com gvs 1.0
36.68.115.158 6141 google.com gws
173.194.57.146 4328 *.c.docs.google.com gvs 1.0
173.194.205.165 1375 *.googleadservices.com gws
115.254.121.227 1313 *.googlevideo.com gvs 1.0
101.78.13.41 2187 *.googlevideo.com gvs 1.0
101.78.13.42 1313 google.com gws
173.194.150.17 3047 *.c.docs.google.com gvs 1.0
115.254.121.222 3141 *.googlevideo.com gvs 1.0
210.2.185.82 2859 *.googlevideo.com gvs 1.0
115.254.121.212 1688 *.googlevideo.com gvs 1.0
115.254.106.239 1829 *.googlevideo.com gvs 1.0
173.194.151.2 2328 *.c.docs.google.com gvs 1.0
103.233.37.116 2078 *.googlevideo.com gvs 1.0
115.254.106.240 1140 *.googlevideo.com gvs 1.0
115.254.97.55 1860 *.googlevideo.com gvs 1.0
210.2.185.83 2687 *.googlevideo.com gvs 1.0
103.16.205.25 1953 google.com gws
115.254.106.211 1438 *.googlevideo.com gvs 1.0
115.254.106.212 2188 *.googlevideo.com gvs 1.0
173.194.151.21 2375 *.c.docs.google.com gvs 1.0
115.254.106.243 1968 *.googlevideo.com gvs 1.0
201.157.30.53 2297 google.com gws
222.165.163.89 1765 google.com gws
103.233.37.126 2235 *.googlevideo.com gvs 1.0
210.2.185.111 4860 *.googlevideo.com gvs 1.0
209.116.150.219 8172 *.googlevideo.com gvs 1.0
220.255.2.164 3719 *.googlevideo.com gvs 1.0
104.237.172.23 5250 *.googlevideo.com gvs 1.0
61.91.161.217 2000 google.com gws
173.194.31.185 2016 *.c.docs.google.com gvs 1.0
104.237.172.24 2672 *.googlevideo.com gvs 1.0
74.125.1.42 1516 *.c.docs.google.com gvs 1.0
115.254.106.215 1156 *.googlevideo.com gvs 1.0
212.142.160.251 13969 google.com 
186.68.154.33 1609 *.googlevideo.com gvs 1.0
115.254.121.241 1328 *.googlevideo.com gvs 1.0
63.96.4.45 6843 *.googlevideo.com gvs 1.0
115.254.121.205 1735 *.googlevideo.com gvs 1.0
173.194.151.36 1922 *.c.docs.google.com gvs 1.0
210.2.185.76 2797 *.googlevideo.com gvs 1.0
210.2.185.85 2640 *.googlevideo.com gvs 1.0
81.10.128.36 9641 *.googlevideo.com gvs 1.0
173.194.151.4 2609 *.c.docs.google.com gvs 1.0
189.14.52.77 6453 *.googlevideo.com gvs 1.0
66.44.205.114 5719 *.googlevideo.com gvs 1.0
118.98.36.232 17906 google.com 
219.117.33.77 10032 *.googlevideo.com gvs 1.0
173.194.205.149 1141 *.doubleclick.net gws
182.248.204.97 8984 *.googlevideo.com gvs 1.0
218.253.0.233 9016 *.googlevideo.com gvs 1.0
173.194.151.18 2328 *.c.docs.google.com gvs 1.0
89.47.210.117 3610 google.com gws
173.194.151.5 7859 *.c.docs.google.com gvs 1.0
115.254.97.96 4703 *.googlevideo.com gvs 1.0
173.194.151.27 2422 *.c.docs.google.com gvs 1.0
202.86.162.172 5578 google.com gws
220.255.2.142 1485 *.googlevideo.com gvs 1.0
115.254.121.213 2781 *.googlevideo.com gvs 1.0
173.194.136.219 12390 *.c.docs.google.com gvs 1.0
189.194.54.113 1937 google.com gws
220.255.2.150 1859 *.googlevideo.com gvs 1.0
103.233.37.85 6859 *.googlevideo.com gvs 1.0
208.117.228.105 2157 *.googlevideo.com gvs 1.0
74.125.1.24 1312 *.c.docs.google.com gvs 1.0
74.125.24.157 10734 *.g.doubleclick.net gws
74.125.1.45 3672 *.c.docs.google.com gvs 1.0
173.194.57.134 2625 *.c.docs.google.com gvs 1.0
173.194.151.9 2906 *.c.docs.google.com gvs 1.0
74.125.1.48 2000 *.c.docs.google.com gvs 1.0
173.194.151.10 2391 *.c.docs.google.com gvs 1.0
173.194.151.11 4484 *.c.docs.google.com gvs 1.0
184.150.153.95 4000 *.googlevideo.com gvs 1.0
173.194.149.100 14172 *.c.docs.google.com gvs 1.0
74.125.1.51 2031 *.c.docs.google.com gvs 1.0
208.117.228.106 1516 *.googlevideo.com gvs 1.0
173.194.151.33 1968 *.c.docs.google.com gvs 1.0
208.117.228.107 1563 *.googlevideo.com gvs 1.0
173.194.151.12 2453 *.c.docs.google.com gvs 1.0
173.194.205.191 1593 *.blogger.com gws
208.117.228.104 2110 *.googlevideo.com gvs 1.0
173.194.57.148 1594 *.c.docs.google.com gvs 1.0
173.194.151.23 5000 *.c.docs.google.com gvs 1.0
173.194.151.28 2359 *.c.docs.google.com gvs 1.0
74.125.0.57 2265 *.c.docs.google.com gvs 1.0
173.194.151.25 1984 *.c.docs.google.com gvs 1.0
173.194.151.26 3875 *.c.docs.google.com gvs 1.0
27.90.141.57 9578 *.googlevideo.com gvs 1.0
74.125.1.41 1938 *.c.docs.google.com gvs 1.0
74.125.1.17 1344 *.c.docs.google.com gvs 1.0
64.233.162.83 1844 mail.google.com gws
173.194.2.76 3766 *.c.docs.google.com gvs 1.0
74.125.1.18 2484 *.c.docs.google.com gvs 1.0
173.194.202.167 5938 *.googleadservices.com gws
74.125.1.195 1453 *.c.docs.google.com gvs 1.0
173.194.57.171 2016 *.c.docs.google.com gvs 1.0
64.233.162.84 1781 accounts.google.com gws
74.125.1.55 2078 *.c.docs.google.com gvs 1.0
173.194.57.168 1328 *.c.docs.google.com gvs 1.0
74.125.0.58 1672 *.c.docs.google.com gvs 1.0
74.125.1.19 1875 *.c.docs.google.com gvs 1.0
173.194.57.151 1844 *.c.docs.google.com gvs 1.0
173.194.2.73 2500 *.c.docs.google.com gvs 1.0
64.233.162.81 1469 sandbox.google.com gws
64.233.162.82 1718 *.googlecode.com gws
74.125.1.8 1828 *.c.docs.google.com gvs 1.0
173.194.2.78 2062 *.c.docs.google.com gvs 1.0
173.194.2.74 1953 *.c.docs.google.com gvs 1.0
74.125.1.7 1828 *.c.docs.google.com gvs 1.0
173.194.2.75 1985 *.c.docs.google.com gvs 1.0
173.194.128.56 2750 *.c.docs.google.com gvs 1.0
173.194.136.25 1562 *.c.docs.google.com gvs 1.0
173.194.205.17 1172 mail.google.com gws
74.125.0.59 1532 *.c.docs.google.com gvs 1.0
173.194.205.176 1078 *.vp.video.l.google.com gws
173.194.57.145 1860 *.c.docs.google.com gvs 1.0
173.194.2.79 1953 *.c.docs.google.com gvs 1.0
74.125.0.55 1688 *.c.docs.google.com gvs 1.0
173.194.57.175 1875 *.c.docs.google.com gvs 1.0
173.194.2.80 1984 *.c.docs.google.com gvs 1.0

**Comment by sundaqing1969** [comment]
贡献ip的朋友，请提交Goagent可用格式，谢谢

**Comment by angle1895** [comment]
66.96.224.222 google.com gws 271 0
101.78.13.34 google.com gws 439 0
104.166.32.17 *.googlevideo.com gws 480 0
92.226.2.186 *.googlevideo.com gws 490 0
190.113.97.217 *.googlevideo.com gws 512 0
190.113.97.213 *.googlevideo.com gws 513 0
190.113.97.228 *.googlevideo.com gws 516 0
190.113.97.206 *.googlevideo.com gws 516 0
190.113.97.248 *.googlevideo.com gws 519 0
190.113.97.225 *.googlevideo.com gws 546 0
190.113.97.247 *.googlevideo.com gws 546 0
109.245.221.43 *.googlevideo.com gws 552 0
201.157.30.53 google.com gws 553 0
190.113.97.239 *.googlevideo.com gws 553 0
109.245.221.14 *.googlevideo.com gws 562 0
45.64.76.52 *.googlevideo.com gws 569 0
92.87.11.31 *.googlevideo.com gws 569 0
45.64.76.51 *.googlevideo.com gws 578 0
200.77.139.80 google.com gws 579 0
179.6.255.32 *.googlevideo.com gws 583 0
101.78.13.44 google.com gws 583 0
109.245.221.21 *.googlevideo.com gws 589 0
200.77.139.90 google.com gws 590 0
109.245.221.48 *.googlevideo.com gws 594 0
181.49.182.56 *.googlevideo.com gws 595 0
109.245.221.16 *.googlevideo.com gws 598 0
109.245.221.52 *.googlevideo.com gws 599 0
45.64.76.33 *.googlevideo.com gws 619 0
109.245.221.55 *.googlevideo.com gws 630 0
115.254.106.236 *.googlevideo.com gws 634 0
115.254.106.232 *.googlevideo.com gws 635 0
190.113.97.237 google.com gws 638 0
62.209.24.43 *.googlevideo.com gws 648 0
189.194.54.113 google.com gws 666 0
190.113.97.215 google.com gws 680 0
201.64.241.55 *.googlevideo.com gws 687 0
115.254.121.219 *.googlevideo.com gws 694 0
115.254.121.209 *.googlevideo.com gws 700 0
222.165.163.91 google.com gws 703 0
220.255.2.164 *.googlevideo.com gws 708 0
92.246.12.240 *.googlevideo.com gws 710 0
92.246.12.247 *.googlevideo.com gws 710 0
89.47.210.117 google.com gws 710 0
92.246.12.239 *.googlevideo.com gws 717 0
109.245.221.40 *.googlevideo.com gws 720 0
115.254.121.208 *.googlevideo.com gws 720 0
92.246.12.205 *.googlevideo.com gws 722 0
222.165.163.89 google.com gws 723 0
222.165.163.90 google.com gws 724 0
190.113.97.231 *.googlevideo.com gws 726 0
92.246.12.206 *.googlevideo.com gws 726 0
220.255.2.142 *.googlevideo.com gws 726 0
115.254.97.98 *.googlevideo.com gws 730 0
92.246.12.218 *.googlevideo.com gws 730 0
181.49.182.225 *.googlevideo.com gws 730 0
190.113.97.221 google.com gws 733 0
103.233.37.85 *.googlevideo.com gws 736 0
103.233.37.83 *.googlevideo.com gws 744 0
92.246.12.231 *.googlevideo.com gws 745 0
103.15.244.160 *.googlevideo.com gws 745 0
92.246.12.220 *.googlevideo.com gws 747 0
190.113.97.220 *.googlevideo.com gws 750 0
92.246.12.246 *.googlevideo.com gws 754 0
92.246.12.224 *.googlevideo.com gws 754 0
109.245.221.47 *.googlevideo.com gws 754 0
177.136.113.204 *.googlevideo.com gws 755 0
109.245.221.32 *.googlevideo.com gws 760 0
103.233.37.116 *.googlevideo.com gws 770 0
45.64.76.13 *.googlevideo.com gws 782 0
109.245.221.26 *.googlevideo.com gws 795 0
92.246.12.235 *.googlevideo.com gws 842 0
103.21.169.248 google.com gws 855 0
201.64.241.90 *.googlevideo.com gws 866 0
201.64.241.43 *.googlevideo.com gws 878 0
220.255.2.150 *.googlevideo.com gws 883 0
190.113.97.207 google.com gws 900 0
190.113.97.249 google.com gws 900 0
92.246.12.212 *.googlevideo.com gws 911 0
201.64.241.51 *.googlevideo.com gws 936 0
123.176.0.149 *.googlevideo.com gws 1043 0
115.254.97.55 *.googlevideo.com gws 1065 0
154.126.74.54 *.googlevideo.com gws 1118 0
92.246.12.251 google.com gws 1169 0
103.29.146.123 google.com gws 260 1
222.165.163.84 google.com gws 1275 0
92.246.12.226 google.com gws 1296 0

**Comment by Kisesy** [comment]
可怕

**Comment by fatwin** [comment]
好人一生平安

**Comment by cixi666** [comment]
@jasonliul 我发现你把以前的发的ip段都删掉了，可是在这个千钧一发的时刻，带着同舟共济出发点，有些壮士把私藏的，鲜为人知的ip都发了出来，有些ip段可能gfw还没发现，如果gfw铁了心了要禁掉,这里发的这些ip段可能给他们提供了很好的线索。

**Comment by dannymtseng** [comment]
用MotherFuckerFang_Modify.exe可以转checkgoogleip的格式

**Comment by sundaqing1969** [comment]
感谢楼上，抱歉哈，谢谢ip提供者

**Comment by sundaqing1969** [comment]
感觉gfw不会全封死ip的，养寇自重嘛。感谢壮士提供ip，我对他们的敬仰之情如滔滔江水绵绵不绝

**Comment by jasonliul** [comment]
@cixi666 

俺刚好怀疑破墙就是定点清除. XX Net的列表, 就是来自CNMan+xyuanmu.

**Comment by sundaqing1969** [comment]
不过有个别高速ip顽强存活，不知该怎么解释

**Comment by jasonliul** [comment]
@sundaqing1969

俺只剩两枚, 新近搜到分享的日韩字段全没了.
存活的居然是GWS, 看起来这次是针对gvs捣鬼.

**Comment by yeahwu** [comment]
@jasonliul 你说的没错，俺感觉这次就是针对叉烧狗的内置ip段，清除的。要不然根据叉烧狗的ip容量不会死的这么彻底。

**Comment by jasonliul** [comment]
@yeahwu 
俺刚分享的几段日韩也被清除, 这些字段感觉很生, 应该是很近期新出的.
没有可能被什么"智障筛选""全部干掉.

**Comment by Kisesy** [comment]
@yeahwu 是的，抛除xx自带列表其他都没啥事，毕竟很难封完，我扫了一会，快500IP了

**Comment by jasonliul** [comment]
@Kisesy 

http://www.blackhatworld.com/blackhat-seo/youtube/640431-thousands-youtube-google-ips-proxies.html
俺很早前故意搁置的ip池, 这部分是把谷歌当客户的网商.

随便摸奖, 就有70个了. 不过ip质量还是大不如从前.

**Comment by cixi666** [comment]
阴阳怪气的向大家问个问题，这个google ip 203.94.3.107是国内的，ping一下大概10ms延时左右 ,为什么用gogo扫一下显示有400ms的左右的延时，很奇怪。

**Comment by Kisesy** [comment]
@jasonliul 嗯，IP质量确实比较低，我这有些IP youtube 速度能到20000多，但是进度条根本不走

**Comment by phuslu** [comment]
插一句， @jasonliul 你要的输出 good_addrs/bad_addrs 在r334 已经可用了。

**Comment by hcym** [comment]
呵呵老大现身

ipv6也有+1的效果，用334试试

也搞个宙斯盾

**Comment by drg78rgjui** [comment]
@jasonliul 你感觉墙有没有可能已经开始封锁欧洲的ip？

我刚才用zoomeye，查了冰岛、捷克、爱沙尼亚、瑞典等地的gws，GoGoTester一个也没有

**Comment by jasonliul** [comment]
@phuslu

正在探索.
密密麻麻, 木有找到在哪里.

**Comment by jasonliul** [comment]
@Kisesy 
这几个比俺现役的好得多, 有劳有劳.
现在速度是很假, html5测试大约400k, 下载才160k, 不时还会卡死.

**Comment by jkng** [comment]
![Uploading QQ图片20160403071436.png…]()

**Comment by jkng** [comment]
![qq 20160403071436](https://cloud.githubusercontent.com/assets/12867321/14229679/469e321e-f96c-11e5-8e50-81d91a70ea22.png)
r334  200ms

**Comment by angle1895** [comment]
@hcym 网络只有ipv4能开ipv6吗？在ga上试过无效

**Comment by caofengzi** [comment]
@angle1895ipv6得所在地的網絡運營商支持才能用，國內好象是除校園網絡以外普通網絡用戶沒有開通v6的運營商。

**Comment by phuslu** [comment]
@caofengzi 很多二线城市的电信和联通都支持 IPv6 了。

https://www.google.com/search?q=ipv6+%E7%94%B5%E4%BF%A1&newwindow=1&safe=off&source=lnt&tbs=qdr:y&sa=X&ved=0ahUKEwiYp6X1wPLLAhXDjpQKHV1KB10QpwUIFQ&biw=1280&bih=699

**Comment by hcym** [comment]
电信的IPv6 很早很早就有

不过是6to4，缓慢然稳定

据说也开始有原生，我这没弄出来

刚刚搞好个100m双拨，狗日的来这手

**Comment by jzp820927** [comment]
不晓得我们这些小城市的屁民，啥时候能用上 IPV6

**Comment by LGA1150** [comment]
@phuslu @hcym @jzp820927 
那其实是ISP提供公网IP、he.net提供6to4隧道服务器和Windows系统自动建立6to4隧道的功劳

**Comment by jzp820927** [comment]
哦，能有个详细教程就好了

**Comment by LGA1150** [comment]
网线不经过路由器，直接连电脑

**Comment by blob2015** [comment]
电信，很虐
联通用得还是挺爽

**Comment by arigadou** [comment]
http://honglingjin.ga/
