### ISSUE TITLE
请问谁有MFF_1.0.8_v8_.net4.6.rar  ？

### ISSUE THREAD

**Issue by jerry011235** [phuslu/goproxy#472]
http://www.mediafire.com/download/x6ezywy5c6xp7ed/MFF_1.0.8_v8_.net4.6.rar
这个下载地址下载出来的htm网页文件，要么下载了解压缩错误。
希望传一个在google网盘或github的下载地址，谢谢了！
源地址：[修改后的MFF(2015-11-30更新v8) #239](https://github.com/phuslu/goproxy/issues/239)

**Comment by ARwMq9b6** [comment]
通过楼主所给的连接把它下载下来了：http://rghost.net/65Bct52bz

**Comment by jerry011235** [comment]
感谢！能正常使用！
