### ISSUE TITLE
怀旧 原版GoGo Tester

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#482]
https://bitbucket.org/bygreencn/gogo-tester

下载
https://bitbucket.org/bygreencn/gogo-tester/raw/0773fd24b0ed4eacaf58fb473b4f1091b5e689c1/GoGo%20Tester/bin/Release/GoGo%20Tester.exe

居然还有些少更新

**Comment by lsnmx** [comment]
@jasonliul 更新啥了

**Comment by minorisprit** [comment]
@jasonliul 
总是停止工作怎么破？

**Comment by jasonliul** [comment]
@minorisprit 

禁用去广告软件, 非常容易有冲突.
升级net45以上, 需要做一个GoGo Tester.exe.config, 放在同一目录.
`<?xml version="1.0"?>
<configuration>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/></startup>
  <system.net>
    <settings>
      <httpWebRequest useUnsafeHeaderParsing = "true"/>
    </settings>
  </system.net>
</configuration>`

**Comment by minorisprit** [comment]
@jasonliul
我禁用了去广告插件，好使了一次，然后继续停止工作，这个.config文件如何制作？我是这方面完全的小白，可以麻烦做一个上传么？

**Comment by jasonliul** [comment]
@minorisprit 
复制文本, notepad, 保存为GoGo Tester.exe.config

**Comment by minorisprit** [comment]
@jasonliul 
多谢指导

**Comment by jzp820927** [comment]
这个工具确实不错，一直在用

**Comment by minorisprit** [comment]
@jasonliul 
我安装了4.5.2，禁用了反广告软件，依旧停止运行，这是按照你说的做的文件，你看一下有错误的地方么
[http://i4.piimg.com/540e5f62c7b28fa1.jpg](url)

**Comment by jzp820927** [comment]
我这边扫描都没安装，正常运行，2008 server 的系统

**Comment by minorisprit** [comment]
@jzp820927 
我昨天还正常，今天就挂了

**Comment by jzp820927** [comment]
估计是你系统有问题吧，你换个系统试试就知道了

**Comment by jap33** [comment]
这个干什么用？

**Comment by caofengzi** [comment]
俺這裡也是點擊就能啟動。

**Comment by jzp820927** [comment]
@jap33 扫 IP 的工具，你别给我说，你没用过

**Comment by jap33** [comment]
@jzp820927 哦哪我是最新的。

**Comment by jasonliul** [comment]
@minorisprit 
这个程序在4.5下面经常无端死翘翘.
内存占用高达200M.
与所有注入进程的程序冲突, 例如奶牛, 纸飞机, Proxifier.

也是一个少爷小姐气的程序

**Comment by jasonliul** [comment]
#654 

大大重出江湖
代码https://github.com/cannanlly/gogotester

这是release https://github.com/cannanlly/gogotester/releases
