### ISSUE TITLE
飞飞跑路了, 谁有推荐免费纸飞机

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#484]
有一阵不用纸飞机, 断炊了.
http://free.feifeiss.com/

飞飞改成这么个玩意.

谁还有好的纸飞机站点推介?

**Comment by dannymtseng** [comment]
这个还不错了。
https://github.com/breakwa11/shadowsocks-csharp/releases

**Comment by Yamazaki-wu** [comment]
@jasonliul 
http://www.tfboys.cf/user 原名布泡泡现在叫tfboys，可以去G+找找邀请码。注册送很多流量，签到送的也不少。有10来个节点吧，消耗费率正常计算。加群看公告还有隐藏节点，消耗费率按2倍计算。

**Comment by jasonliul** [comment]
@Yamazaki-wu 

G+在哪?

**Comment by Yamazaki-wu** [comment]
怎么PM你？我看看能否生成邀请码

**Comment by yeahwu** [comment]
看到跑路，俺就想到，温州老板和小姨子……
需翻墙   http://www.gfw.press

**Comment by yeahwu** [comment]
基本上都是送的流量还没用完，就tm挂了

**Comment by jasonliul** [comment]
@yeahwu 
有劳, 成功.

@Yamazaki-wu 
俺一般仅仅测速, 玩玩而已. :)

**Comment by jap33** [comment]
https://shadowsocks.trade/
1869 	ulbRsPzjEwNOpd16klYEqSTeM02xm3tK 	可用
1870 	9PbXgRSBgx8EJUVMKrP7oCrRBIklgtLR 	可用
1871 	QBU6ezcczzEUcxCFoR4XOATo6afrlzA2 	可用
1872 	BWBNfG6Nug8APD4my6K8GI7RVG7jDM32 	可用
1873 	nyVYF3us5INA6wuTF2LcE03ER5AEXSF9

**Comment by jap33** [comment]
0 	91WJkNWM4NzhjNTUwZGE2YWM1Z 	可用
子霖ss  http://ss.linblog.net/user/index.php
1 	91iMjJmYjY5NGQ1MTNlZGNmNTU 	可用
2 	911NmVhOGFlMGJlOGI1MzA2OTc 	可用
3 	91iNGNiZWQ1YmVhZTg0N2E3ZmY 	可用
4 	91iYTlmMmE2OTc2NTcwYjAzNTM 	可用
5 	91c1YzkzNGRhZGEyMTc3MTJkNz 	可用
6 	91BlNTk4NTZiNGRlNThhMjE5Ym 	可用
7 	91GRmNTUyY2VhMmYzNjk5MThjN 	可用
8 	91kOWMwZWMwYTE4NDFiM2IzNzI 	可用
9 	91M5MmE4NTFiMDAxNjQ0MmFiNj

**Comment by jap33** [comment]
SSNODE - Fixing
https://mjj.re/user/invite.php                生成了一个给大家了
4670U3ZTFiY2FhY2VkOWE1NGYxZT

**Comment by jap33** [comment]
http://ss.supra.tw/user/invite.php
0 	92zYTVmNDY0Mzc1NWE3OWVlNWY 	可用
1 	92MmY1ZmY2OGUzZTI1YjkxMTQy 	可用
2 	92zhmZTZlZjMzMGMxM2EwNWEzZ 	可用
3 	92UxYzc3M2YzZjhkYzhiNGJlOD 	可用
4 	92YWQwNDU2NGJmYjkwZGI5ZTMy 	可用
5 	92I4MjdiNzAzZTZhY2Y5YzcyNj 	可用
6 	92zZiYTU0M2FlNDRiMjJiZDExM 	可用
7 	92E1N2I0YTQwYjc4MTMyZjFlNz 	可用
8 	92hYWMzMGVhZTYyZjQxNDAzMjV 	可用
9 	92GU5NmZjYzRiNGNlNzJkNzczO 	可用
10 	92TJhOGNlNjYzNThlYjU3NmI4O 	可用
11 	92TRlMTI3YjkyZjVkOThkM2M3O 	可用
12 	92MDY1M2ZlYTEzZjkxYmYzYzQ4 	可用
13 	92U5ZGRmMTFjNThlNzQ0NmM5ZG 	可用
14 	92E1Mjg2YmExMDA3YWJmYmI4ND 	可用
15 	921OWUzYmIxMmQyMDNmNDVhOTE 	可用
16 	922NWQwN2RhNGE3NzYyMTQ1MGF 	可用
17 	923NTg2NDA5NGUzOTA2YTRhMGI 	可用
18 	92iOTI5ZWFlN2E0OTllNTAyNDh 	可用
19 	92kZWJiNmU4NzJmNTM5YmVmOGM 	可用
20 	92WQyNjViYzkwM2E1YTA5N2Y2M 	可用

**Comment by Yamazaki-wu** [comment]
@jap33 赶脚邀请码好多啊！

**Comment by Yamazaki-wu** [comment]
@jap33 
http://ss.linblog.net/user/index.php
这个怎么登录不了啊？显示错误如下。
Warning: Cannot modify header information - headers already sent by (output started at /home/wwwroot/ss.linblog.net/user/index.php:1) in /home/wwwroot/ss.linblog.net/user/_check.php on line 17

**Comment by jap33** [comment]
@Yamazaki-wu 
http://ss.linblog.net/

**Comment by jzp820927** [comment]
果然是码王啊

**Comment by jasonliul** [comment]
@jap33 

原来阁下就是潜伏在狗社的纸飞机党代表, 失敬失敬

**Comment by jap33** [comment]
@jasonliul 
其实阁下贡献不小，东洋美鲍俺还记得。

**Comment by yeahwu** [comment]
@jap33  东洋美鲍就是他呀？哎呀，这里面卧虎藏龙

**Comment by jasonliul** [comment]
@jap33 @yeahwu 
喔~~
都是咸湿同好. :)

**Comment by imimi2008** [comment]
咦，怎么一刷新就没了？？？


我也来一发
----------------------------------------------------------------------
https://shadowsocks.trade/

###	邀请码(点右键复制链接)	状态
1914	MsQNO2WNsktTueM3YrNUmXmRg8g4IJmj	可用
1915	24Pam5gswbQxtlCi646uzBFT3Exlf5hy	可用
1916	dPFH1uq9BsM9u818dcLpW1HackcLoFuu	可用
1917	hqZVFBFOtg8iZc7REUIosSaCTshMtG1D	可用
1918	f0cBPXGv76SeH4Lm2QppD4ghXnRnjCtv	可用

**Comment by nqzhang** [comment]
现在才看到，这是免费站点，呵呵，收费站点，www.feifeiss.com.要是我收了你什么，你说我跑路我认，但这个免费站你说跑路我就有点冤了，况且我还没跑路，免费站始终坚持着两条线路

**Comment by yeahwu** [comment]
站长不必认真，俺们就是开玩笑滴，呵呵

**Comment by jasonliul** [comment]
@nqzhang 
春秋笔法 . :)

**Comment by pgz123** [comment]
@jasonliul 新版382狗屁出现462怎么破？

**Comment by snk100** [comment]
现在还有推荐吗，最近高度太高了。

**Comment by snk100** [comment]
现在还有推荐吗，最近高度太高了。

**Comment by snk100** [comment]
现在还有推荐吗，最近高度太高了。

**Comment by snk100** [comment]
现在还有推荐吗，最近高度太高了。

**Comment by snk100** [comment]
现在还有推荐吗，最近高度太高了。

**Comment by nqzhang** [comment]
@snk100  www.feifeiss.com 不地道的做个广告..

**Comment by snk100** [comment]
@nqzhang 居然名字都跟这个差不多....

**Comment by jasonliul** [comment]
其实不时可以换换口味

**Comment by zhaofuyun** [comment]
http://ss.zfuyun.top  免费科学上网
