### ISSUE TITLE
愚公摸小强

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#487]
完整字段已成历史, 现在摸奖, 基本就是孤胆小强.

俺只要4只小强, 所以足够.

上菜
5.22.190.183 塞尔维亚
201.175.77.83 墨西哥
173.194.122.237 俄罗斯
178.168.3.101 摩尔多瓦
87.245.196.140 俄罗斯
5.44.5.77 俄罗斯
5.102.167.20 德国
64.233.189.137 台湾

**Comment by yeahwu** [comment]
毫不客气地收鸟，这些都是可用的哦，俺也懒得测试鸟，直接丢到xx里跑。

**Comment by drg78rgjui** [comment]
第一个尤其有趣，TraceRoute测试它是连往欧盟的ip段。
偶也有两个欧盟的官方字段64.233.178.125|64.233.178.188 但是无法使用

**Comment by yeahwu** [comment]
感觉俺都快发狂了，看到字段就收藏，也不管他能不能用鸟。

**Comment by jasonliul** [comment]
@yeahwu 

小强才是精品. LOL

**Comment by yeahwu** [comment]
@jasonliul 原来是这样，多谢

**Comment by jasonliul** [comment]
@yeahwu 

现在有些ip开放443端口, 但是检测不到sffe类型.
这种可以用, 但是闪烁不定. 所以俺全部砍掉

**Comment by yeahwu** [comment]
俺说你呀，这伟大的党教育俺们要勤俭节约，还有亿万劳苦大众等着俺们去拯救呢。
非常时期嘛，就算是根骨头也得舔一舔，扔掉多可惜呀！

**Comment by jasonliul** [comment]
@yeahwu 
叉烧狗可以用. 不过狗屁/黄狗还是算了, 
忽然变两个bad ip, 速度立刻仆街.

**Comment by yeahwu** [comment]
@jasonliul 兄还是把你那些吃完的，扔掉的骨头发出来吧，俺来舔一舔，扭一扭

**Comment by yeahwu** [comment]
然而，俺还是放一段吧，你没看错，就是这段，打不死的小强
45.64.29.0/24
45.64.30.0/24
45.64.31.0/24
这一段谁敢来战？

**Comment by jzp820927** [comment]
这是要复活的节奏

**Comment by drg78rgjui** [comment]
中国移动香港182.239.也是小强，可能考虑到香港用户来大陆要翻
总是检测到一两个

**Comment by jasonliul** [comment]
120.28.12.0/24 +8
120.28.26.0/24 +8
118.98.111.0/24 +10
115.88.207.0/24 +13
114.108.207.0/24 +14
114.120.192.0/24 +14
114.4.4.0/24 +14
49.98.24.0/24 +15
49.98.25.0/24 +15
110.50.81.0/24 +18
45.64.20.0/24 +19
45.64.29.0/24  +19
45.64.30.0/24  +19
45.64.31.0/24  +19
45.64.34.0/24  +19
61.238.203.0/24 +3
124.153.255.0/24  +4
59.18.49.0/24  +5
59.18.46.0/24  +5
59.18.45.0/24  +5
58.123.220.0/24 +6
58.123.102.0/24 +6
58.176.217.0/24 +6
120.89.6.0/24 +8
120.89.12.0/24 +8
61.238.239.0/24 +3
61.219.131.0/24 +3
122.154.76.0/24 +6
122.154.244.0/24 +6
120.28.5.0/24 +8
120.28.53.0/24 +8
43.245.144.0/24 +21
42.112.10.0/24 +22
103.25.178.0/24 +25
103.224.194.0/24  +25
223.27.237.0/24 +33
222.251.134.0/24  +34
219.124.146.0/24  +37
218.253.0.0/24 +38
210.92.119.0/24  +46
210.94.153.0/24  +46
210.143.70.0/24 +46
210.158.146.0/24 +46
210.242.127.0/24 +46
203.233.126.0/24 +53
203.233.63.0/24 +53
203.233.10.0/24 +53
203.248.210.0/24 +53
203.233.88.0/24 +53
203.121.59.0/24  +53
203.211.8.0/24 +53
203.113.161.0/24  +53
203.66.155.0/24 +53
203.146.98.0/24 +53
202.248.248.0/24 +54
202.28.85.0/24 +54
202.69.185.0/24 +54
202.248.151.0/24  +54
188.43.69.0/24    +68
1.255.22.0/24 +63
188.43.64.0/24  +68

后面的注释不用管

**Comment by minorisprit** [comment]
用dig ip法把亚洲几个靠谱的dig了一遍才找到俩GAE IP其中一个还死了

**Comment by jzp820927** [comment]
摸奖已经不适应现在恶劣的网络环境了，现在只能强扫

**Comment by hcym** [comment]
瞎折腾

弄个ipv6，慢是慢点，安逸

这次是和谷歌卯上了，不用代理hosts跑推特和github都是飞快

**Comment by blob2015** [comment]
ipv4，终究奄奄一息了
dns好像都有干扰？在东亚几国里面测了500个，得到百来个，然后陆续好像还会阵亡

**Comment by yeahwu** [comment]
用xx省心，活了死，死了活，管它呢
![2016-04-06 18 46 37](https://cloud.githubusercontent.com/assets/13328328/14318370/1784c544-fc3f-11e5-8957-7e8cb62ed10d.png)

**Comment by blob2015** [comment]
xx，这一点还是比较省心的

**Comment by jasonliul** [comment]
@jzp820927 

刚好相反, 只有极少的小强, 强扫实在不划算.
不如大家赌赌运气, 每人奉献3只小强.

小赌怡情养性, 俺觉得天朝人骨子里都是赌徒.

**Comment by yeahwu** [comment]
@jasonliul 美鲍同鞋，俺对你的敬仰如滔滔江水，你先来

**Comment by panpeach** [comment]
我现在每次只放一个有效IP，总能激活多个，而且寿命也长

![Uploading ggg.png…]()

**Comment by jzp820927** [comment]
@panpeach 你的意思，你 google_hk 里面只放 1个IP，但日志信息，goodip 是好几个？不可能吧？难道有 幽灵 IP？就算是顿正，也只可能多 1个啊

**Comment by jasonliul** [comment]
@yeahwu 

你这是赤裸裸坑俺, 今日已摸, 来日再摸

**Comment by panpeach** [comment]
3.8亿里面摸奖还是有惊喜地，^_^

**Comment by angle1895** [comment]
3.8亿....

**Comment by minorisprit** [comment]
讲道理我今天还从gogotester自带的90W里面摸出来12个GAE IP

**Comment by jzp820927** [comment]
今天开始，IP在慢慢开始复活了，能摸出IP也正常

**Comment by minorisprit** [comment]
个人感觉还是定向dig靠谱，即便是半手动，也比从几十万甚至几亿IP段里摸奖快多了

**Comment by angle1895** [comment]
dig方便得多只是时间长

**Comment by yeahwu** [comment]
找路边算命大爷算一卦，也比3.8亿里摸靠谱

**Comment by drg78rgjui** [comment]
奇怪，难道是我高估墙了....
还没有封透就开始恢复了，难道墙的技术能力真不足以封锁全世界的googleip？

**Comment by jasonliul** [comment]
185.119.13.14|185.119.13.12|185.119.13.13|109.173.137.89|109.173.137.94
波兰

**Comment by yeahwu** [comment]
感谢，既然是打赌，先出拳的肯定是要吃亏的，说好的三段
66.96.224.222|66.96.226.210|61.91.161.217

**Comment by vcteps** [comment]
@jzp820927 试过，黄狗不知道什么时候开始，放入几个goodip，goodip总数会变多，不知道为什么

**Comment by vcteps** [comment]
@jzp820927 试过，黄狗不知道什么时候开始，放入几个goodip，goodip总数会变多，不知道为什么

**Comment by yeahwu** [comment]
@jasonliul 实在是丢人哪，因为延时300ms以下的就这三个段。

**Comment by lvtuobai** [comment]
@jasonliul  大神求goproxy教程啊！有软件完全不会使啊 ！网站里的教程是goagent的！

**Comment by yeahwu** [comment]
教程到这里面找，有gae和php教程
https://plus.google.com/collection/M6RqCB

**Comment by jzp820927** [comment]
@vcteps 你这种情况我也遇到过一次，4个hk，4个cn，goodip 一共是 10个

**Comment by jasonliul** [comment]
@jzp820927 

Kisesy 大大已经发现, 多出来的是带有谷歌分析的网站, 例如Github.
也就是可以把不是谷歌家的ip, 也变成可用的伪军.

**Comment by lvtuobai** [comment]
@yeahwu @jasonliul 这个网站打不开啊！之前一直用的goagent后来想用goproxy一直没有详细的教程！本人小白只适合想goagent那种白痴教程只要识字就会用的那种！大神们有没有？

**Comment by drg78rgjui** [comment]
@jasonliul 有没有可能，用1个400ms的真gaeip，加n个50ms的伪军....速度是伪军的速度

**Comment by jzp820927** [comment]
@lvtuobai https://github.com/phuslu/goproxy/issues/243 看这个

**Comment by lvtuobai** [comment]
@jzp820927  谢谢啊

**Comment by jasonliul** [comment]
172.217.4.219,172.217.4.213

**Comment by yeahwu** [comment]
谢谢鲍兄…不能更赞鸟，鸟，鸟，🐦，🐦
Jason Liu <notifications@github.com>于2016年4月10日 周日12:48写道：

**Comment by jzp820927** [comment]
已经失效1个，真快
