### ISSUE TITLE
玩狗? 必须调低谷歌安全设置

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#502]
Gmail, 谷壳浏览器都是, 先调低测试, 再发问不迟.

上传的问题
https://www.google.com/settings/security/lesssecureapps
选择Turn On.

谷歌现在不允许第三方app直接访问谷歌相关账户, 必须设置更低安全设置.

谷壳浏览器也是一样.

**Comment by hcym** [comment]
这可怪不到谷歌，都不是正常ip，人家也是为你负责

猪圈里根本没有正常ip登录，都是用第三方代理

我在台湾登录谷歌app，顺利的很

回来后同步一次就要问东问西

**Comment by yeahwu** [comment]
鲍鱼哥真贴心

**Comment by phuslu** [comment]
谢谢，我加在简易教程里面了。

**Comment by inkdie** [comment]
补充一下，上传完了可以再调回来。

当时为了上传，我把二次验证、应用专用密码什么的全关了。上传完了再恢复正常也不影响使用的。

**Comment by jzp820927** [comment]
我用应用专业密码上传的，没啥问题

**Comment by boycc1974** [comment]
我一直用ga，如果用gp也还要上传一次吗？

**Comment by jzp820927** [comment]
@boycc1974 不用，服务端都是兼容的

**Comment by Gzxhwq** [comment]
用专用密码也传不上去，老的GAE都可以用专用密码传……

**Comment by jzp820927** [comment]
那你用老的传不就行了，反正服务端都是兼容的

**Comment by Gzxhwq** [comment]
我知道可以啊，一直都在用。今天传个新的想试试看，发现传不了而已。

**Comment by jzp820927** [comment]
反正我上次直接用 goproxy 服务端自动档 upload 传的，不晓得你为什么传不了
