### ISSUE TITLE
这牛逼吹得俺禁无言以对，不过人家网站是真的完全免费

### ISSUE THREAD

**Issue by yeahwu** [phuslu/goproxy#507]
![cfkzofbw8aacjco](https://cloud.githubusercontent.com/assets/13328328/14402493/00a60fe0-fe6a-11e5-8f94-9cb039c9a888.jpg)

**Comment by phuslu** [comment]
这个网站我也看过，「广告词」是有点夸张搞笑，不过应该是有意为之的。

无论如何，掏出真金白银助人翻墙还是要赞👍

**Comment by mixool** [comment]
这个可以可以。

**Comment by 935352** [comment]
自愿捐献不错了

**Comment by yeahwu** [comment]
是的，石斑鱼大爷的风格，在推上很活跃。

**Comment by mixool** [comment]
"HostMap" : {
		"google_hk": [
			"220.255.x.164",
			"220.255.x.153",
			"220.255.x.150",
			"220.255.x.142",
			"61.x.161.217",
			"61.62.x.208",
			"61.62.x.152"
		],
		"google_talk": [
			"talk.google.com",
			"talk.l.google.com",
			"talkx.l.google.com"
		],
		"google_cn": [
			"www.g.cn",
			"www.google.cn"
		]
	},
借这个帖子问一下，上面的配置运行一阵子后现在居然有goodip 17个，多出来的谷歌中国的Ip么？

**Comment by fredericky123** [comment]
可是gfw节点里的网速很慢啊

**Comment by hcym** [comment]
多的就是翻墙红利
慢说明是小奖

**Comment by fredericky123** [comment]
可是不是一般的慢 实在影响科学体验 看到每天20G 还以为很大的福利

**Comment by hcym** [comment]
说不清
我用的挺快
还是得找ip快的

**Comment by hcym** [comment]
每天20g什么情况？

app用满25g啊

**Comment by yeahwu** [comment]
其实嘛，免费ss，要的是稳定，慢就慢一点。
像飞飞一样10g流量没用完，带小姨子跑路了。就好了？

**Comment by jasonliul** [comment]
@yeahwu 

你你你...
人家就叫飞飞, 放你飞机. 哪有欺骗你?

**Comment by yeahwu** [comment]
@jasonliul 看来取名字还是有学问滴，这个叫“GFW，怕死”，应该靠谱
还有……
“狗屁”怎么说？
“叉烧狗”怎么说？
“狗崽子”怎么说？

**Comment by pug908** [comment]
256位会是高强度加密?
