### ISSUE TITLE
周末忙线, 鸡瘟时段, 垃圾ip, 狗屁照响

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#508]
http://i4.imageban.ru/out/2016/04/09/afa85263b1accd4f54ddee3ba918ef0e.png
服务端, 客户端都是最新, +垃圾ip [区区4M电信超薄]
实际下载速度>440KB/S

俺也要披挂擂鼓, 疾呼:
人民狗社好! 
社长大人, 威~~~武~~~

**Comment by hcym** [comment]
怀念韩国ip

不过谷歌境内ip也非常了得

无论何时，下载chrome安装包都超过电信签约带宽

阿里云百度云真的差好几点

**Comment by phuslu** [comment]
这两天改动都在 ci 上了，已经不用 go1.6 编译了，改用 go 最新版编译 (注意到 goproxy-gui.exe 启动标题栏上有显示。)

好处就是 go 最新版的有任何性能提升都能立刻用上。

**Comment by jasonliul** [comment]
@phuslu 
变通之道.

@hcym 
俺也怀念韩澳泰菲, 老部下纷纷阵亡.
清明一嚎 烧纸

**Comment by phuslu** [comment]
服务端的问题，还在看。。。

**Comment by jzp820927** [comment]
这个必须支持，go 发展更新还是挺快的，每次都能用最新版go 还是挺不错的

**Comment by yeahwu** [comment]
吓得俺赶紧下了最新版尝尝鲜，结果打死都超不过500kbps
当然其他的gae类这段时间也都这样

**Comment by hcym** [comment]
十个go服务端

相当满意

**Comment by jasonliul** [comment]
@yeahwu 
你的伪军ip有问题

**Comment by yeahwu** [comment]
没用过伪军，就叉烧狗里抓了一把ip丢到狗屁里，速度一直提不起来，最近墙内网站也慢，应该是俺电信线路问题

**Comment by jzp820927** [comment]
现在丢包严重，速度很难提起来

**Comment by jasonliul** [comment]
@jzp820927 
最差的时候50%, ISP服务器响应时间109ms, 
正常<20ms

**Comment by somebird** [comment]
DNS污染而已，国内网都上不了

**Comment by jasonliul** [comment]
@somebird 

国内的百度盘, 西瓜/吉吉就像发瘟的母鸡

**Comment by yeahwu** [comment]
应该不是dns的原因，本地缓存dns，10ms以内

**Comment by jasonliul** [comment]
墙奴现在是短斤少两, 借机克扣带宽赚小费.

去年开始, 墙不再增高. 但是增加你到达城墙的难度.
家庭用户距离城墙, 还有4000公里, 于是就八千里路云和月了.

**Comment by xrwz007** [comment]
@jasonliul 請問，gae裡的ip，hk和cn是兩邊填一樣，還是cn填國內的幾個谷歌服務ip好，（ps：國內的谷歌ip ping很好 10ms以內）？我目前兩邊填一樣

**Comment by jzp820927** [comment]
国内的IP不能用于连接 GAE
