### ISSUE TITLE
你以为你是谁啊，乱锁别人的东西，自以为多了不起

### ISSUE THREAD

**Issue by vcteps** [phuslu/goproxy#509]

**Comment by vcteps** [comment]
以后不来你这就是，自以为多了不起

**Comment by phuslu** [comment]
呵呵，这位兄台估计没看我回应你的文章，再贴一遍，看完再骂 http://www.ruanyifeng.com/blog/2009/07/live_not_by_lies.html

**Comment by phuslu** [comment]
``Why should cattle have the gifts of freedom?
"为什么要给畜牲自由？"
``Their heritage from generation to generation is the belled yoke and the lash.''
"它们一代代的命运就是套上枷锁，接受鞭挞。"

**Comment by jasonliul** [comment]
俄语原文链接在哪里?

**Comment by phuslu** [comment]
维基词条的第一个参考链接里面有 https://ru.wikipedia.org/wiki/%D0%96%D0%B8%D1%82%D1%8C_%D0%BD%D0%B5_%D0%BF%D0%BE_%D0%BB%D0%B6%D0%B8!

**Comment by jasonliul** [comment]
@phuslu 
斯拉夫语是简洁语系, 会省略很多单词, 自行补足.
转译英语...正好牛肉注水. :(

**Comment by phuslu** [comment]
呃，这有点吹毛求疵了，这文章别人也翻过。

http://www.aisixiang.com/data/2707.html 
http://www.washingtonpost.com/wp-dyn/content/article/2008/08/04/AR2008080401822_pf.html

是在不行还可以用谷歌翻译机器翻译来校验啊。

**Comment by phuslu** [comment]
多说几句个人看法吧，（强行装一波）

党国气数未尽，而且我们民族的气运还在。所以即使现在人心思变，但离天翻地覆还早。

所以稍稍放下个人情绪，静待历史进程吧。有朝一日大厦将倾，无论你准备只手补天，还是重开人间，只要问心无愧即可。

**Comment by phuslu** [comment]
这诗不错，聊做宽慰

```
日出扶桑一丈高，人间万事细如毛。野夫怒见不平处，磨损胸中万古刀。
```

**Comment by jasonliul** [comment]
当年鲁迅先生, 既不看好国党, 也不看好共党, 但是寄望青年人进化.

历史悠久的民族, 印度, 伊朗, 天朝, 等同六十老朽耳顺. 闭目塞听, 自守心墙. 这并不是政府的问题, 而是整个民族的. 文明不总是进化, 也会退化与异化.

天朝从明代开始把闭关锁国政策化, 以后一路沿袭至今. 这是陶瓷民族做出的选择, 不单是政府的.

单纯看翻墙, 关心墙外世界努力进化的是新人类, 天朝的新希望.
不过一心趴在墙头秀姿势, 秀花裤衩, 博墙内人膜拜掌声的也不少. :)

**Comment by jzp820927** [comment]
支持 @phuslu 老大的观点与看法，不可感情用事，不可意气用事，冲动94魔鬼。

**Comment by yeahwu** [comment]
哈哈，社长，这语气较以前收敛不少……
俺倒是另有看法，这个民族就是少了“意气”，少了“冲动”
俺倒是希望现在的年轻人个个锋芒毕露，个个张牙舞爪，而不必理会老朽们的“谆谆教诲”
那样或许还有生机

**Comment by ARwMq9b6** [comment]
又见社长吟诗，备受鼓舞。

**Comment by phuslu** [comment]
工作略微有点不顺心，issue 也没时间看了。

哎，业余做这玩意断断续续也 5， 6 年了，说句自夸的话，各位翻墙社区的贡献者参与者的心路历程我都可能经历过了。

借这贴稍微吐下槽，勉励自己


> 不忘初心，方得始终。
>  凛冬将至，吾血尚温。

**Comment by yeahwu** [comment]
```
吾血尚温
```
这句可算社长的名言了，俺是从这句开始关注您的，呵呵

**Comment by phuslu** [comment]
是啊，本来应该乘着党国还算“客气”的情况下，就此销声匿迹。
可惜心中块垒难消，只能再作冯妇了。

**Comment by yeahwu** [comment]
社长是条汉子，溜须拍马的话不多讲了，
俺最实在能做的，带好头，讲真话，敢讲话。
希望有生之年能看到裆国倒下，然后能睹社长真容
