### ISSUE TITLE
IP例假 日用型/夜用型

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#522]
应该是电信特有

白天所谓正常期, 没死的ip完整, 但是很多小强死去.
下午3,4时---凌晨0,1时, 鸡瘟蔓延, 没死的ip大量减少, 但是会多出许多侧漏的小强. 看起来很像破墙也感染鸡瘟所致. 哈哈.

**Comment by yeahwu** [comment]
是滴，有这种情况，叉烧狗感觉明显，所以俺要回收那些刚死不久的ip嘛

**Comment by yeahwu** [comment]
还有你的ip不是经常怀孕生崽子，哪里来的例假呀？

**Comment by hcym** [comment]
明明是方老师调戏

别瞎琢磨

**Comment by jasonliul** [comment]
刚才飚过5000kbps了,
现在稳在4785.

狂笑

**Comment by yeahwu** [comment]
会早泄的，笑嘛笑

**Comment by xyuanmu** [comment]
现在白天基本不用担心，各种IP，速度杠杠的，晚上家人时间刚好不用去理会。
![Y2B](https://cloud.githubusercontent.com/assets/12442896/14449097/28f02168-00a2-11e6-99cc-ff8108e921d6.png)

**Comment by yeahwu** [comment]
始终都只有你们的一个零头，这日子没法过鸟

**Comment by xyuanmu** [comment]
@yeahwu 也许我这边比较偏僻吧，刚入手的IP，还热乎：203.233.96.0/24

**Comment by yeahwu** [comment]
看这ip段是香港滴吧？必须给赞

**Comment by xyuanmu** [comment]
@yeahwu 我查的是韩国的，香港基本死绝了吧。

**Comment by yeahwu** [comment]
上次有个人想分享这段，但没有给出具体段，结果一转眼就删了。果然是奇货可居啊

**Comment by jasonliul** [comment]
@xyuanmu 
你居然还有韩国ip.
俺在用仅存的俄国ip, 响应>250ms, 不过新狗不挑食

**Comment by xyuanmu** [comment]
@jasonliul 有的，203.233.96.0/24，阅后告知一声。

**Comment by jasonliul** [comment]
@xyuanmu 
OK, 烧纸

**Comment by drg78rgjui** [comment]
@xyuanmu 屌！这种完全没被动过的段 全亚洲有没有20个？

**Comment by jasonliul** [comment]
@drg78rgjui 
现在剩下的属于小商家, 检查IPInfo, 一般他们总共就几十个字段.

也就是通常数据库里面没有的.

这次破墙已经添加所有谷歌服务器类型+数据库, 包括不支持GAE的, ghs, GoaHead.
完整字段应该超过30枚/字段, 这种应该不复存在.

**Comment by hcym** [comment]
方老师专用段
不知道老不死的啥时候对ipv6动手

**Comment by jasonliul** [comment]
119.40.97.226,202.179.1.57,46.134.208.31,185.48.9.105,185.48.9.164,212.179.154.224,92.87.156.89

愚人摸奖依然管用, 本来4枚就足够, 随便也能摸中 :)

**Comment by yeahwu** [comment]
@jasonliul 这几段，新鲜，水灵。楼主好淫！1024

**Comment by jasonliul** [comment]
电信现在15:00准时月经,
俺换成夜用巾先.

**Comment by drg78rgjui** [comment]
@jasonliul 顺便一提，墙现在又对akamaiip进行监测封锁
只是不像google那样封到欧洲，北美、南美  只限东亚ip，到印尼就已经避开了。
偶真的很好奇墙的能力 akamai全球ip比google还要多啊 且不说还要封其他cdn的ip

**Comment by yeahwu** [comment]
感谢 @jasonliul  @xyuanmu 兄不定期提供的ip段，让叉烧狗得以残喘。
https://github.com/XX-net/XX-Net/issues/2853

**Comment by jasonliul** [comment]
@drg78rgjui 
akama节点没有封杀, 即使是谷歌字段.
不过亚洲有些字段就通杀, 全部封掉443端口.

俺觉得是通过检测服务器类型+谷歌域名来搞的.
现在采用白名单制, 疑似谷歌字段的话, 仅允许Akamai, MS, 阿婆车几种类型, 其他都被连坐.

俺推测现在真正可用稳定的ip, 只有几万.
外加增加ping值, 丢包率, 等于数倍真实的物理距离, 因此夜间>400ms的ip实际不可用.
夜间活跃ip应该<2万

**Comment by yeahwu** [comment]
@jasonliul 这种情况用goproxy的话很受罪，换ip能烦死

**Comment by jasonliul** [comment]
长宽现在是倒卖电信. 是不同省市的大杂烩.

看起来是分4级, 都会, 省会, 大城市, 小城市/乡村. 可用ip会有不小的差别.
单一线路, 即使通信狂扫, 应该也不会超过1万[包括闪烁节点]

**Comment by jasonliul** [comment]
@yeahwu
现在ip池已经有些厚度, 可以放心一阵子. :)

**Comment by yeahwu** [comment]
都被俺给收了，不过俺还是保留了一部分，呵呵

**Comment by TonnyTonny** [comment]
@yeahwu 感谢 @jasonliul @xyuanmu 兄不定期提供的ip段，让叉烧狗得以残喘。
XX-net/XX-Net#2853

謝謝

**Comment by yeahwu** [comment]
@TonnyTonny 不客气

**Comment by hcym** [comment]
仅仅针对谷歌ip封的死，也可能下面人使坏

恐怕不是针对翻墙哦

twitter，github都不要代理，hosts跑的飞快

尤其推上都是巴拿马奥玛萨，怎么不封

比谷歌也容易封

**Comment by jasonliul** [comment]
@hcym 
这个不是针对黄狗, 而是针对谷歌的.
朝廷拿来表态驱逐鞑虏, 天朝人关门自摸, 所谓梦遗中国.

**Comment by Chu2koi** [comment]
放弃用ip了，直接用php，反正是家里电脑用的，需求不大，自己电脑有ss

**Comment by CongZeng** [comment]
@xyuanmu 韩国IP段是多少
