### ISSUE TITLE
gae.json这里面有一个地方好像写的有问题

### ISSUE THREAD

**Issue by playnetcn** [phuslu/goproxy#528]
r385版本里面
	"ForceGAE": [
		"translate.googleapis.com",
		"domains.google.com",
	],

domains.google.com后面没有逗号吧？

**Comment by mixool** [comment]
据说是做了什么处理有无逗号都可以。

**Comment by jzp820927** [comment]
现在对 json 做了宽松匹配处理，也就是说，格式不用这么严格，末尾有逗号，没逗号都可以
