### ISSUE TITLE
上传最新版客户端时，输入了错误的授权码后怎么办？

### ISSUE THREAD

**Issue by baoziwan** [phuslu/goproxy#535]
@phuslu 
我的APPID不是主账号申请的，但是在升级最新版客户端时，一时粗心，用主账号允许了权限，并把授权码应用到了最新版客户端，得到返回结果“You do not have permission to modify this app”。

现在我重新用正确的账号授权得到授权码，但无论怎么操作新版客户端，都都没有输入新的授权码的步骤，只返回“You do not have permission to modify this app”。

现在我应该怎么操作呢？

**Comment by phuslu** [comment]
重新下载一次，最新的服务端上传工具已经把授权码保存到当前目录了。

以后要是输入错误，删除当前目录的 .appcfg_oauth2_tokens 即可。

**Comment by baoziwan** [comment]
搞定了，谢谢。
