### ISSUE TITLE
请问 php fetchserver 哪里可以下载？

### ISSUE THREAD

**Issue by losywee** [phuslu/goproxy#548]
请问 php fetchserver 哪里可以下载？ 谢谢！

**Comment by phuslu** [comment]
https://github.com/phuslu/goproxy/tree/server.php
https://github.com/phuslu/goproxy/tree/server.php-go

**Comment by caofengzi** [comment]
社長，已經部署了goproxy的php，客戶端還需要下載什麼嗎？

**Comment by phuslu** [comment]
先配置 php.user.json 然后在 httpproxy.json 打开 enable php 即可。

**Comment by caofengzi** [comment]
社长好，俺部署goproxyPHP登录php时提示这个错误。咋弄？

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by jzp820927** [comment]
@caofengzi 好像部署好了以后，打开页面也不会有什么显示的，你可以试试能不能用。我部署没遇到过问题。

**Comment by losywee** [comment]
@phuslu 谢谢，谢谢，已部署 OK

**Comment by caofengzi** [comment]
俺是头一次弄php，虽然社长这个是傻瓜式的可俺还是一头雾水不明白，希望哪个朋友们给个详细的教程，另外php模式还需要添加appid吗？谢谢朋友们。

**Comment by losywee** [comment]
@caofengzi   不需要的，只要设置密码

**Comment by losywee** [comment]
@caofengzi  PHP的干不了啥，看看网页还差不多

**Comment by caofengzi** [comment]
谢谢朋友回答，那样俺还是消消停停的用gae模式吧。

**Comment by jzp820927** [comment]
PHP 只是作为 GAE 失效时候的应急用，别指望速度能有多快。确实是只能看网页

**Comment by losywee** [comment]
@jzp820927  楼上专业

**Comment by caofengzi** [comment]
如果社长能够加入xx的自动搜索ip就更好了，俺现在是hk, cn各3个ip，有时候goodip有11-12个。

**Comment by jzp820927** [comment]
扫描功能，早就有人提出来，社长的意见社，观察一段时间，看看 XX 的扫描功能，会不会造成什么大影响，如果没什么影响的话，后期会考虑加入，只能期待了。目前的固定配置模式，确实很难适应现在的网络环境了。
