### ISSUE TITLE
php fetchserver 配置后

### ISSUE THREAD

**Issue by losywee** [phuslu/goproxy#549]
浏览器的返回数据。

malformed HTTP response "\x1f\x8b\b\x00\x00\x00\x00\x00\x04\x00\xed\xbd\a`\x1cI\x96%&/m\xca{\u007fJ\xf5J\xd7\xe0t\xa1\b\x80`\x13$ؐ@\x10\xec\xc1\x88\xcd\xe6\x92\xec\x1diG#)\xab*\x81\xcaeVe]f\x16@\xcc흼\xf7\xde{\xef\xbd\xf7\xde{\xef\xbd\xf7\xba;\x9dN'\xf7\xdf\xff?\\fd\x01l\xf6\xceJ\xdaɞ!\x80\xaa\xc8\x1f?~|\x1f?\"Ζ\x97YY\xccҗY\xd3\\U\xf5l\xfc\xff\x00\xbdH\xea\xcb\x11\x00\x00\x00"

**Comment by jzp820927** [comment]
没看到啥咚咚

**Comment by losywee** [comment]
已解决，故关闭

**Comment by zhanggangbz** [comment]
请教一下，是如何解决的?

**Comment by losywee** [comment]
@zhanggangbz  抱歉，有点久了，记得不是很清楚了，好像是我的密码错了吧
