### ISSUE TITLE
r385一直碰到这个问题怎么破？

### ISSUE THREAD

**Issue by 1978ccbu** [phuslu/goproxy#550]
![image](https://cloud.githubusercontent.com/assets/15637595/14578559/8321139a-03bd-11e6-919f-50bab410202e.png)

之前一直用r169很稳定，今天尝试用新版，就一直碰到这个问题，求大神解决
main文件：
![image](https://cloud.githubusercontent.com/assets/15637595/14578568/dc9cefa2-03bd-11e6-9f52-d162bf0e9533.png)
证书也导入了，不知道怎么办

**Comment by jap33** [comment]
都r392了

**Comment by xyuanmu** [comment]
删除证书导入新证书。

**Comment by jzp820927** [comment]
你的证书，是老证书还原的，还是 新生成的

**Comment by 1978ccbu** [comment]
我又把老的删了重新导入了一下可以了
