### ISSUE TITLE
云基黄狗 GoGo 1.6.0

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#551]
二狗 GoGo 1.6.0 (2016-04-16)

```
支持配置服务端
优化内网、国内和国外IP的判断功能
新增留言功能
```

http://www.gogotunnel.com/

**Comment by jzp820927** [comment]
一年多没更新了，这个是支持自己部署服务端么

**Comment by xxx233** [comment]
@jasonliul 你这取的名字咋都这么难听呢？云基？干嘛不叫 “基基”或者“二狗”？
黄狗
狗屁
叉烧狗
狗崽子
都是你取的吧？你真是淫才

**Comment by yuan18** [comment]
干嘛用的？不懂

**Comment by asd3g2x** [comment]
已经可以下载了

**Comment by yeahwu** [comment]
二狗，好

**Comment by verygoogle** [comment]
我也顶二狗这个名称，有人自建服务端测试过速度吗，直接拿来可用，看视频怎么讲呢——仅仅可看

**Comment by boycc1974** [comment]
试了下，720没问题

**Comment by jasonliul** [comment]
@xxx233 
二狗, 好!

**Comment by verygoogle** [comment]
@boycc1974 是自建的还是默认的？我这边默认的只能144P

**Comment by yeahwu** [comment]
@jasonliul  二狗确实好，转走了，youtobe能跑到600kbs，很满足了

**Comment by verygoogle** [comment]
天理何在，你们都这么快

**Comment by yeahwu** [comment]
@jasonliul 还有日志里老是跳出HEROKU字样，你别告诉俺，公共服务是在玩heroku免费空间吧？

**Comment by boycc1974** [comment]
默认

**Comment by jzp820927** [comment]
才你知道，默认公共服务端一直用的 keroku
@verygoogle 如果是移动网，默认的 720P，应该没什么问题，移动网对 heroku 链接速度很好，电信就别想了

**Comment by yeahwu** [comment]
这样不太好吧，tmd，道德癖又犯了……

**Comment by jzp820927** [comment]
@yeahwu 不过，作者一直没提供 heroku 的搭建程序和方法，一个算是有所考虑吧，应该来说，影响不大，而且现在提供的 服务端，也是基于 VPS 的，也不是用于 paas 的。

**Comment by jasonliul** [comment]
@jzp820927 

只剩一个是GFW干的, 新版又搞回来了. :)

**Comment by jzp820927** [comment]
又回到4个app了？皆大欢喜啊。这个工具确实不错，速度和稳定性都很好，特别是移动网，用起来更爽，最主要的特色是原生证书，既安全，又方便。电信网，以后可以作为第一备胎用。移动网，我觉得可以作为主胎用了。

**Comment by verygoogle** [comment]
WHAT!电信网－－中标

**Comment by jasonliul** [comment]
@jzp820927 
俺以为作者自裁, 其实是GFW污染搞掉的,
一共5个app, freetunnel0--freetunnel4

**Comment by Kisesy** [comment]
更新了，不错，希望稳定

**Comment by jzp820927** [comment]
@verygoogle 电信网链接 heroku 的速度很慢，而且掉包也厉害，你问问他们移动网的就知道了，移动网链接 heroku 的速度很快。
@jasonliul 5个也差不多够用了，就是不太喜欢 java 环境，要是能开发 go语言 版本的就安逸了。我现在对 go 很钟情。对比 goagent 和 goproxy 就能明显看出 go 的网络性能了。

**Comment by jasonliul** [comment]
@jzp820927 
Java依然是最好的跨平台, 而且隐私安全性也高.
Jondo[欧版洋葱]依靠Java也是有考虑的

**Comment by yeahwu** [comment]
@jzp820927 linux不是自带java了吗？
@Kisesy 目前看来比狗屁的php，heroku空间要快。希望尽快出搭建heroku空间教程

**Comment by hcym** [comment]
heroku教程有啊

隔壁xx

heroku和openshift各弄了一个

就等gop前置加速

**Comment by hcym** [comment]
对公共服务端不感兴趣

就像女人，车子一样，不宜共享

**Comment by jzp820927** [comment]
@yeahwu 你要是知道原理，就知道 gogo 为什么比，普通 heroku 代理空间快了。因为 goog 和 XX 一样，有一个最核心的功能，就是扫描功能，这个是最核心，最重要的功能。

**Comment by yeahwu** [comment]
@hcym 俺说的是gogo的heroku搭建教程，狗屁早就有了

**Comment by jzp820927** [comment]
@yeahwu gogo 的 app 以前被 heroku 官方封过，所以估计不会出教程和代码，来大范围应用。

**Comment by yeahwu** [comment]
@jzp820927 拉到吧，在linux下你谈资源占用，俺在linux下随便什么翻墙软件乱跑，叉烧狗，ss，狗屁，lantern，一起跑，线程调到100，资源也不会占到50%，

**Comment by jzp820927** [comment]
虽然我自己用的是 linux，但我说的是 windows 下面的用户。我知道 linux 性能好。但用 linux 的毕竟是很少数，Windows 的用户基数还是非常大了。

**Comment by yeahwu** [comment]
win下的确麻烦，俺记得以前装过一次i2p，尼玛，那个java，麻烦

**Comment by jasonliul** [comment]
@hcym 

公厕... 从来不用吗?

**Comment by jzp820927** [comment]
@yeahwu Linux 的优势就是 网络性能好，系统稳定。而且集成很多常用的环境，比如 open java，python 等。

**Comment by yeahwu** [comment]
@hcym 你这货，看来是找不到女票鸟……   自带（乌鸦声）

**Comment by hcym** [comment]
罪过罪过

俺是喜欢独食，原来有个大侠cnman不是经常关闭ss服务器

就是有人拿来bt，一夜就搞光流量

自己搭建比较环保

**Comment by jdfq** [comment]
为什么要玩坏？

**Comment by Kisesy** [comment]
服务器可以搭成，但是用不了，大家试试能不能添加
http://gogo1.herokuapp.com 端口 1024

**Comment by Kisesy** [comment]
额，突然不明白搭载Heroku的意义了。。。这样只是个app啊

**Comment by yeahwu** [comment]
你能不能将明白点？这个端口是怎么回事？

**Comment by Kisesy** [comment]
用法：打开config 下的gogo.conf，把 gogo1 按下面这样写

	  "version" : "1.6.0",
	  "proxyOnlyForForeignIPs" : "true",
	  "apps" : [ {
		"app" : "gogo1",
		"platform" : "heroku"
	  }, {
		"app" : "freetunnel0",
		"platform" : "heroku"
	  }, {
		"app" : "freetunnel1",
		"platform" : "heroku"
	  }, {

**Comment by Kisesy** [comment]
这样只是添加一个app，并不是真正的服务器，感觉这个就跟gae一样，app就像是appid，ip就跟谷歌ip一样。。。

**Comment by yeahwu** [comment]
你这个能用，你是怎么搭建的，大概说说嘛

**Comment by Kisesy** [comment]
等会

**Comment by yeahwu** [comment]
谢谢，俺试试，

**Comment by jasonliul** [comment]
@Kisesy 
感觉像是黄狗的自动前置.

**Comment by Kisesy** [comment]
说实话部署过程倒是不复杂，但是这东西需要 pom.xml，我试了十几次都填不对，从网上抄了个才行

**Comment by pgz123** [comment]
@jasonliul解压出错

**Comment by yeahwu** [comment]
@Kisesy 搭建成功，谢谢

**Comment by jzp820927** [comment]
赶脚就是多了个 apps ，意义不大啊，对性能没有影响。

**Comment by yeahwu** [comment]
有意义呀，等到有一天公共的apps不能用了，俺自己部署的不是很牛逼了。
另外再求 @Kisesy 的图像，上次哪个换系统弄丢鸟，呵呵

**Comment by Kisesy** [comment]
@yeahwu 啥图啊，头像? http://tieba.baidu.com/p/2960830129

**Comment by yeahwu** [comment]
嗯，俺也要走功夫路线鸟，好评

**Comment by jzp820927** [comment]
移动网用这个还是挺爽的，像俺这种电信的，就很蛋疼了。

**Comment by Kisesy** [comment]
@yeahwu 头像不太清楚，可以到这里高清重置一下 http://waifu2x.udp.jp/
我把头像换成了面瘫系列，你看怎么样 http://pan.baidu.com/s/1qWjr3Jm

**Comment by yeahwu** [comment]
@Kisesy 嗯，挺好，俺来研究一下怎么把这图像弄清晰一点。

**Comment by yeahwu** [comment]
@Kisesy 你给的哪个图片转换好牛逼的说，直接把凤姐整成了小龙女

**Comment by verygoogle** [comment]
电信早空闲时段还行，720P尚可

**Comment by CHN008** [comment]
按照你们说的教程我用Gogo看Youtube速度:电信20M光纤也就200-600多Kb/s.看来电信的还真是受限制...

![gogo-1](https://cloud.githubusercontent.com/assets/16646697/14586041/60765cfa-04bd-11e6-9e6b-c5653feb7e42.jpg)

**Comment by yeahwu** [comment]
多嘴一句吖，尽量不要拿免费空间来看视频，要不真会玩坏……

**Comment by jasonliul** [comment]
@CHN008 

二狗和使用前置袜子的GP表现差不多, 不过前置都比较遥远.

**Comment by yeahwu** [comment]
@jasonliul 然而你换的这个 猪鸡兽  没有原来的哪个 中指 图片帅

**Comment by CHN008** [comment]
嗯 嗯,我只是测试一下,现在还是用xxnet.它速度慢还要安装JRE,麻烦.

**Comment by jzp820927** [comment]
这个不适合电信，移动还行。话说，除了 GAE，我还没用过其他代理看视频，包括蓝灯都没看过视频，且用且珍惜。

**Comment by CHN008** [comment]
蓝灯速度也还可以,不过看视频用Web Freer就好.

**Comment by jzp820927** [comment]
Web Freer  还不是 GAE 没啥区别。

**Comment by CHN008** [comment]
哦,不懂这些 我还是个小白.只是觉得这浏览器挺强大的,不用设置就可直接用.

**Comment by jzp820927** [comment]
Web Freer 就是 集成了 GAE 代理的 便携浏览器，和 yeahwu 做的是一样的。

**Comment by CHN008** [comment]
嗯, 谢谢你的科普,也感谢yeahwu的无私贡献!

**Comment by jasonliul** [comment]
@verygoogle 
俺也是电信, 其实可以跑到>1200-1500kbps.

关键二狗提速慢, 而且速度不稳定.要先玩玩别的, 等速度上来再视频, 也可以先暂停缓冲一下.

使用澳门, 韩国的dns解析域名, 直接加到hosts里面, 例如
54.243.42.115 gogo1.heroku.com

GFW其实是污染二狗域名的.

**Comment by verygoogle** [comment]
@jasonliul  哈哈，大侠也是电信的，突然幸福感爆棚，感觉有肉吃了，请多指点

**Comment by hcym** [comment]
移动没用过

除了广告劫持，电信线路一直不错

没遇过断线，翻墙也稳定，速度也能达到签约上限
