### ISSUE TITLE
手机端如何通过goproxy电脑的代理端口上网

### ISSUE THREAD

**Issue by mixool** [phuslu/goproxy#560]
改为0.0.0.0
但是会显示连接不是私密连接，电脑端显示证书错误，怎么解决

**Comment by jzp820927** [comment]
导入电脑端的 goproxy 证书

**Comment by mixool** [comment]
@jzp820927 需要Root么

**Comment by jzp820927** [comment]
不用，直接在浏览器导入就行了

**Comment by hcym** [comment]
手机上这怎么自动看最后一帖

猛刨爪子吃不消

**Comment by mixool** [comment]
@jzp820927 安卓手机，已经从手机安全选项导入，正常运行，感谢。
