### ISSUE TITLE
旧版的gae服务器段如何上传

### ISSUE THREAD

**Issue by sishentibu** [phuslu/goproxy#567]
在用xx-mini的时候遇到点问题，所以想测试下是否是服务器端的问题
但用旧版gae已经无法上传旧的服务器端了。
有什么方法吗？

在goproxy中ip挂掉的时候，用xx-mini用段时间，ip又有了，感觉挺好的。

**Comment by fengixng** [comment]
旧版能正常上传，你如果开启两步验证，用应用专属密码上传即可。

**Comment by jzp820927** [comment]
或者也可以用 XXNET 上传服务端

**Comment by sishentibu** [comment]
@fengixng 现在不行了。会提示错误
Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---

**Comment by sishentibu** [comment]
@jzp820927 可以部署，但是用这个部署怎么加密码？
就是旧gae上传的时候可以设个密码，不知道密码的话，就算知道appid也不能用

**Comment by sishentibu** [comment]
已参照这个解决
https://github.com/xyuanmu/XX-Mini/issues/54#issuecomment-212244539
