### ISSUE TITLE
goagent在fedora 20下全局代理设置

### ISSUE THREAD

**Issue by zjhxmjl** [phuslu/goproxy#569]
各位好，不知哪位兄台有goagent在fedora 20下全局代理设置的参考资料？谢谢

**Comment by jzp820927** [comment]
看你要代理什么流量，针对各种不同的应用，设置不一样

**Comment by zjhxmjl** [comment]
情况1:翻越GFW
情况2;翻译局域网网内和谐软件:深信服
不知有何好的意见？

**Comment by jzp820927** [comment]
如果是浏览器的话，肯定是考虑插件了，最方便。
如果是软件的话，肯定软件自身支不支持设置代理，如果不支持，就要第三方软件来转发到代理。
如果是 shell 命令，大部分都支持 http_proxy 代理变量

**Comment by zjhxmjl** [comment]
OK,我已经找到其它方法解决此问题了,thks！
