### ISSUE TITLE
最近用goproxy，appid老是跳转到这样的网页，怎么解决。

### ISSUE THREAD

**Issue by yeahwu** [phuslu/goproxy#57]
![_2015-08-01t17-25-43 154z](https://cloud.githubusercontent.com/assets/13328328/9022793/e775a21c-38b5-11e5-8086-c4122bded4d6.png)

**Comment by sundaqing1969** [comment]
报到

**Comment by wujiaqian** [comment]
ip的问题，经大家提点，删掉一些ip就好了。

**Comment by ChiehJang** [comment]
我下载了GProxy解压都不能用，翻不了墙，求解……

wujiaqian <notifications@github.com> 於 2015年8月2日週日 下午9:27 寫道：
