### ISSUE TITLE
陡线上扬, 狗族崛起,GP r411白金典藏版

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#574]
背景资料
全称: 大中华黄埔同学遛狗社
简称: 黄埔社
民间村姑讹传: 黄狗社

社长: phuslu [中文音译: 发死勒]
社长大头贴: 国防机密, 仅限盲人观赏[GBxxxx认证资质]
社长资历: 前"中华好色狼"季军得主, 首席天朝师奶杀手, AV地位等同台湾小马哥.
*附注: 师奶, 已婚/将婚妇女的美称, 参见辞海, 康典.

政治部主任: 现役phuslu's 师奶每夜版
训导处主任: @Kisesy,  @CNMan
国际知名教官:  @xyuanmu, @jzp820927,@yeahwu.... 群星云集
客座教授: @jap33 [纸飞机党代表]

GP r411行情分析
测试平台
你土包: 760k/s跳开, >45度角陡线上扬, 稳速, 收于4700kbps附近.
亚马逊下载: 满速

基准背景
HK IP: 二三流印尼/菲佣ip+GWS
CN: 有效, 连号4枚
带宽: 电信小区垃圾4代
服务端: 2016-04-16

GP r411实属狗族白金典藏版, 随着社长抽风升级, 或许反倒不如这一版经典, 敬请珍藏. 

阳寿也有涯, 升级也无涯, 经典永在, GP r411, 独家代理, 盗版必究.

@phuslu 
社长, 服务端更新没有提示? 至少加上日期吧.

**Comment by hcym** [comment]
说那么多废话，不如给个ip

**Comment by jasonliul** [comment]
@hcym 

伸手党痴懒, 不仅得喂饭, 还得拿个粪铲, 搞进食道...
比私生子女还麻烦. :)

**Comment by erichau** [comment]
一般要晚上好才是真的好

**Comment by jasonliul** [comment]
@erichau 

电信现在仅仅每天凌晨1:00重置, 然后每小时增加克扣, 
嘿咻战斗间隙, 也可以重搜ip. LOL

**Comment by erichau** [comment]
@jasonliul
有重新上传Appid吗？

**Comment by jzp820927** [comment]
我居然上榜了，好吧。看来任重而道远啊。。。

**Comment by jasonliul** [comment]
@jzp820927 
咖喱兄当仁不让. :)

**Comment by jzp820927** [comment]
服务端可以看 commit 记录啊，有时间的。

**Comment by hcym** [comment]
我这边电信都是深夜线路好转

白天不行

**Comment by jasonliul** [comment]
@hcym 
之前是1:00 Am/4:00pm, 一天两次好像大便.
近一周只有一次, 1:00过后搜索ip要多得多

**Comment by yeahwu** [comment]
@jasonliul 
```
民间村姑讹传: 黄狗社
```
这说的是谁？哈哈
最近好多了，ip又回来了

**Comment by hcym** [comment]
ip倒是和电信无关

白天多少晚上也差球不多

看油管软件下载区别大

**Comment by yeahwu** [comment]
还有“中华好色狼”冠军是谁呀？

**Comment by jasonliul** [comment]
@hcym 
俺用谷歌天朝, 下载满速很久了.
差别只在"你土包"

**Comment by jasonliul** [comment]
@yeahwu 
知道你不服, 俺特意从教官名单雪藏你,
哼哼~ :)

**Comment by yeahwu** [comment]
@jasonliul 俺实在不敢上榜，叛变份子那有资格。
其实俺最近想走性爱科学路线（淫秽路线），想要你的美鲍群地址？好歹以后也能靠冠军近一点嘛

**Comment by jasonliul** [comment]
东洋美鲍=Softether VPN
免费版是某年三八节发表的...
:)

**Comment by yeahwu** [comment]
@jasonliul 敲门ip俩枚，以示敬意
203.252.15.140
1.255.33.20

**Comment by yeahwu** [comment]
@jasonliul 大哥，你就不要给俺打哑谜了？就是那个天天穿紧身泳衣的g+群，以前不知道是你的，加上那段时间，斯文病犯了，勇敢退出来了。给链接，链接

**Comment by lsnmx** [comment]
全是闲人啊

**Comment by yeahwu** [comment]
@jasonliul 不会是那个群不是你的？:joy::joy:
一不小心暴露了自己淫荡的本质……

**Comment by lsnmx** [comment]
@yeahwu 你头像真Q

**Comment by yeahwu** [comment]
@lsnmx 大兄弟一看就是识货的人哪

**Comment by yeahwu** [comment]
背景资料
全称: 大中华黄埔同学遛狗社
简称: 黄埔社
民间村姑讹传: 黄狗社（其实就是副社长钦赐的）

社长: phuslu [中文音译: 发死勒]
社长大头贴: 国防机密, 仅限盲人观赏[GBxxxx认证资质]
社长资历: 前"中华好色狼"季军得主, 首席天朝师奶杀手, AV地位等同台湾小马哥.

副社长：jasonliul（中文名：鲍哥）
副社长大图贴：猪鸡兽 （ISO9001认证）
副社长资历：“中华好色狼”冠军得主，社长靠边站，美鲍团首席CEO，衍生产品AV+，对，多了个加号，AV的变种，以示更强。
副社长简介：社长修炼“中华好色狼”的日子，一直是副社长撑着狗社，才幸免被狗社兄弟坛团灭。
不时搞出点新鲜花样，比如ssh，putty，二狗，火凤凰……（虽然都没什么卵用）
已制定出多项标准  GB2016  TTL……
google ip官方发放机构发言人，断粮的童鞋找副社长，又称”ip地主“

**Comment by xyuanmu** [comment]
最近共匪解封了？
![y2b](https://cloud.githubusercontent.com/assets/12442896/14707656/5cf0af34-07f8-11e6-89c8-5d40394047ac.png)

@yeahwu 看你这头像胖呼的，差点人不出来了，我一般都是按头像认人的

**Comment by jzp820927** [comment]
6K+，我去，好久木有看到这么感人的速度了。

**Comment by boycc1974** [comment]
411，我怎么只看见402？

**Comment by yeahwu** [comment]
@xyuanmu 是的，最近两天ip复活了不少，你这是用的mini？为什么还是被你们远远甩在身后，俺刚刚突破2k的贫困线。然而你这图像叫人家怎么看？
@jasonliul 鲍哥，俺这简介还算客观，公正吧？

**Comment by jzp820927** [comment]
@boycc1974  https://github.com/phuslu/goproxy-ci/releases  在这儿，你就能看到 411 了

**Comment by boycc1974** [comment]
@jzp820927 谢谢

**Comment by hcym** [comment]
这两天gfw确实比较懒

**Comment by zxzxvic** [comment]
联通这边 白天”你土包“可以上1w5-1w8，到了晚上3k都无法突破。

**Comment by jasonliul** [comment]
@zxzxvic 
俺一直以为只有电信夜间鸡瘟, 看来联通也入伙.
同瘟同瘟, 干杯.

**Comment by yeahwu** [comment]
@jasonliul 江南地区，电信夜间突破不了1000kbs，白天3000kbs
今天破墙又反常了，大量ip复活，别tm到时又给全灭了。

**Comment by jasonliul** [comment]
@yeahwu 
所谓"复活", "放水"看起来像是一种测试, 前几天很多俄国字段出现残兵.
今天基本都消失了, 只剩少量>350ms的.

**Comment by yeahwu** [comment]
大哥，日韩周边的ip都活了，现在俺在用的基本上都是延时150ms以内的ip，
当然，俺在用狗崽子

**Comment by xrwz007** [comment]
可有人建立電報交流群？telegram小飛機 飛呀飛

**Comment by yeahwu** [comment]
有个g+群，欢迎大家及副社长莅临指导
https://plus.google.com/communities/101215702940766881013

**Comment by mixool** [comment]
看来移动是最幸福的了，基本都是6000+，下载满速度12000.

**Comment by jzp820927** [comment]
我早就说过了，移动的处境带宽是最好的

**Comment by drg78rgjui** [comment]
在广州深圳如果能用100m的移动宽带 连这两个已被封的移动香港ip段
182.239.95.0/24
182.239.127.0/24
有望达到gae类极限速度

**Comment by Kisesy** [comment]
这。。俺开始方了

**Comment by verygoogle** [comment]
你们晒的我越来越穷了

**Comment by jasonliul** [comment]
@Kisesy 
主任, 你方什么?
