### ISSUE TITLE
php服务端的小疑问

### ISSUE THREAD

**Issue by in-summer** [phuslu/goproxy#579]
[这里](https://github.com/phuslu/goproxy/blob/server.php/index.php)的214行
`header('Content-Type: ' . $__content_type__);`
是不是应该改一下, 比如这样?
`header('Content-Type: ' . $GLOBALS['__content_type__']);`

**Comment by jzp820927** [comment]
这个得问 P大了

**Comment by phuslu** [comment]
谢谢。马上改掉。
