### ISSUE TITLE
sequence is usually defined as a function whose domain is a countable totally ordered set

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#591]
sequence is usually defined as a function whose domain is a countable totally ordered set, although in many disciplines the domain is restricted, such as to the natural numbers. In real analysis a sequence is a function from a subset of the natural numbers to the real numbers.

**Comment by phuslu** [comment]
以我的计算机知识，客户端没有办法。ISP 决定的。

这也是基于 anycast 的CDN 技术在国内没有流行起来的原因。

**Comment by pug908** [comment]
[iplist]
google_hk = 可用IP
google_cn = 1.255.22.208|1.255.22.207|1.255.22.36|1.255.22.27|1.255.22.155|1.255.22.50|1.255.22.156|1.255.22.37|1.255.22.154|1.255.22.29|1.255.22.52|1.255.22.35|1.255.22.158|1.255.22.120|1.255.22.32|1.255.22.80|1.255.22.19|1.255.22.122|1.255.22.153|1.255.22.160|1.255.22.248|1.255.22.54|1.255.22.151|1.255.22.157|1.255.22.246|1.255.22.152|1.255.22.251|1.255.22.30|1.255.22.164|1.255.22.159|1.255.22.90|1.255.22.24|1.255.22.40|1.255.22.123|1.255.22.173|1.255.22.25|1.255.22.48|1.255.22.82|1.255.22.58|1.255.22.174|1.255.22.97|1.255.22.98|1.255.22.242|1.255.22.229|1.255.22.236|1.255.22.143|1.255.22.220|1.255.22.12|1.255.22.150|1.255.22.28|1.255.22.214|1.255.22.89|1.255.22.53|1.255.22.178|1.255.22.141|1.255.22.105|1.255.22.49|1.255.22.186|1.255.22.39|1.255.22.182|1.255.22.205|1.255.22.18|1.255.22.180|1.255.22.33|1.255.22.59|1.255.22.115|1.255.22.184|1.255.22.102|1.255.22.92|1.255.22.81|1.255.22.21|1.255.22.121|1.255.22.181|1.255.22.167|1.255.22.34|1.255.22.95|1.255.22.176|1.255.22.100|1.255.22.177|1.255.22.45|1.255.22.161|1.255.22.219|1.255.22.47|1.255.22.79|1.255.22.172|1.255.22.175|1.255.22.42|1.255.22.169|1.255.22.183|1.255.22.215|1.255.22.250|1.255.22.113|1.255.22.213|1.255.22.170|1.255.22.244|1.255.22.168|1.255.22.179|1.255.22.234|1.255.22.103|1.255.22.119|1.255.22.55|1.255.22.171|1.255.22.91|1.255.22.43|1.255.22.118|1.255.22.88|1.255.22.76|1.255.22.22|1.255.22.44|1.255.22.104|1.255.22.51|1.255.22.111|1.255.22.107|1.255.22.140|1.255.22.84|1.255.22.110|1.255.22.94|1.255.22.114|1.255.22.148|1.255.22.117|1.255.22.146|1.255.22.227|1.255.22.144|1.255.22.85|1.255.22.216|1.255.22.87|1.255.22.86|1.255.22.108|1.255.22.112|1.255.22.222|1.255.22.145|1.255.22.212|1.255.22.142|1.255.22.209|1.255.22.38|1.255.22.46|1.255.22.243|1.255.22.96|1.255.22.83|1.255.22.232|1.255.22.13|1.255.22.106

**Comment by jzp820927** [comment]
这就是传说中的 GAE 前置 GAE

**Comment by CHN008** [comment]
给大家一个图形化的带地图的路由追踪工具

http://cdn.ipip.net/17mon/besttrace.exe

![default](https://cloud.githubusercontent.com/assets/16646697/14761050/3a990e64-0987-11e6-9690-618a89fbdc97.jpg)
:

**Comment by hcym** [comment]
就等谷歌的天际路由

**Comment by pug908** [comment]
没错就是GAE前置GAE，当然是前置的配置。
google_hk中必须使用可用IP，它可以是任意GGC IP，中国大陆的除外（当然其中只有几个GWS勉强能用）；
google_cn必须使用失联IP，它有两个作用：
第一，安全性；
第二，激活性（同时激活同地区、同0.0.0.0/16的IP段或者关联的IP段）。

激活后的IP（也就是你扫到的IP），可通过访问谷歌云盘（或者其他谷歌服务，GMAIL除外）使其稳定；记得重启GAE。

**Comment by hcym** [comment]
激活失联IP

疗效如何

感觉这有点挑大神的味道

**Comment by jzp820927** [comment]
后置 可以用 goproxy 么？也就是 goa(前置) 前置 gop(后置) ？

**Comment by pug908** [comment]
只要证书没问题，应该没问题。

**Comment by lsnmx** [comment]
@pug908 google_cn =  修改自定有什么效果

**Comment by zxzxvic** [comment]
话说经常听你们说 前置，后置，失联ip，这三个分别代表什么意思呀？@jzp820927

**Comment by pug908** [comment]
google_cn相当于储备干部，前置中的作用主要是激活相关IP（也有混肴的效果），后置中使用才有流量（同时成为攻击源，目标：所有链接路上的防火墙，当然就包括GFW）。

**Comment by jzp820927** [comment]
@zxzxvic 前置就是类似你给一个软件设置一个代理；后置就是你设置代理的这个软件本身，也不过这个软件也是个代理，也就是说，给代理软件，再设置个代理，失恋IP，就是被封锁IP

**Comment by drg78rgjui** [comment]
@pug908 你这样做速度有变快吗

**Comment by jasonliul** [comment]
@CHN008 
没有付费版ip库?

**Comment by lsnmx** [comment]
@jasonliul  付费版4W RMB只有企业才有啊

**Comment by pug908** [comment]
用了几年速度一直在最高峰，主要为了操GFW～

**Comment by hcym** [comment]
搞定Dual-Stack Lite再试试激活失恋IP

请教@jasonliul@jzp820927一众大腕

用过没有，疗效如何?

再请问phuslu 

这发科gfw原理可行吗？

**Comment by ldtx** [comment]
我觉得ISP比GFW还有动力封IP，因为可以省网间结算费:)

**Comment by yuan18** [comment]
看看

**Comment by verygoogle** [comment]
@pug908 前置用哪个版本，可有地址。之前看到过你的这种用法，用某个版本尝试了下，出了问题不成功，具体是怎样想不起来了，想学新姿势，请指教

**Comment by pug908** [comment]
理论上所有3.2.3版本以前的都可以作为前置；
我就是关注这里自己学习的：
https://plus.google.com/app/basic/109136078508962444158/posts?cbp=1bsfhbcvggri&sview=26&cid=5&soc-app=115&soc-platform=1
