### ISSUE TITLE
关于php有问题咨询一下

### ISSUE THREAD

**Issue by playnetcn** [phuslu/goproxy#595]
现在IP不好找，我在不同的网站部署了几个php，现在想用goproxy的php功能，但是我遇到两个问题
一、php.json里面配置一个的网站的一个https方式的php的时候，速度非常快，看视频不卡（一直保持1000kbps至2000kbps）通过监测连接数能达到50左右。但是我用相同的方法加了另外一个网站的一个http方式的php的时候，非常慢，只能达到（500kbps左右，这个网址从国内ping延时100多）通过监测连接数能达到5个左右。想问一下这个是php网站限制了吗？
二、当在php.json里面配置多个网站的多个（http和https混合分别属于6个网站）的php时候，网速非常慢(500Kbps左右)，通过监测连接数，每个网站就连接了3个左右（我说的快的那个php连接数在配置多个的时候也是3个，不像单独配置那样能达到50左右），不能像gae.json配置并发连接数非常多，提高网速。想问一下这个是什么原因？有方法解决吗？

**Comment by jzp820927** [comment]
这个怕只有P大才知道了。
