### ISSUE TITLE
自填ip党 维护办法

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#602]
俺的方式, 比较麻烦, 懒人止步.

 狂扫ip器 Angry IP Scanner 3.4.1 #407 

1.添加服务器类型检测web detect[箱形图标], 检测端口设置443.
逐段检测你主要的字段, 只选择一次性同时sffe/443的那些ip, 不要心疼, 也不需要重测. 保存为Angry IP格式.

 怀旧 原版GoGo Tester #482 
2. Angry IP格式不方便, 用GoGo Tester 把ip搞出来, 保存为eip.txt.

 海妞改版checkgoogleip 新玩法 #419 
3. 有了eip.txt, 使用这个维护, 注意改为openssl检测.

俺现在的列表还是清明节的, 偶尔增补, 至今没有遇见ip闪烁或其他ip问题.
仍然建议hk4个, cn使用中国谷歌, 也是4个. 

IP多不是福音, 一个坏ip拖慢一堆好ip.

**CHN008 大大推荐**

图形化的带地图的路由追踪工具
http://cdn.ipip.net/17mon/besttrace.exe
可以更直观的检查ip质量, 绕路过多的ip, 即使ping值很小, 也不是高质量

令人吃惊的是, 有些ip段居然无法追踪到加州, 俄国, 泰国的两段

**Comment by yeahwu** [comment]
居然没有叉烧狗，全自动一体化，懒人必备 :smile: :smile:

**Comment by minorisprit** [comment]
一个IP路过，山东联通GFW干扰时间为每晚8-11点，今晚似乎提前结束，其余时间可以满速

**Comment by caofengzi** [comment]
@jasonliul 用checkgoogleip怎麼維護eip.txt？是把eip添加到checkgoogleip裡面掃描嗎？

**Comment by liweitd** [comment]
cn使用中国谷歌?不太明白。作用是什么？有什么要求吗，怎么找中国谷歌IP？

**Comment by yeahwu** [comment]
说辣么多，还不如给两个ip，哈哈哈哈

**Comment by drg78rgjui** [comment]
jasonliul 辛苦了

**Comment by jasonliul** [comment]
@drg78rgjui 

大大客气了, 你也是潜龙

**Comment by cnshinchan** [comment]
凿磨半天Angry还是木搞懂咋用，扫半天没见到sffe类型的服务器，怎样保存为Angry IP格式?大神能否上个图详细说说，谢谢。

**Comment by sishentibu** [comment]
请教下，我参照你的步骤，选择safe/443的ip，保存为x.x.x.x|x.x.x.x|……（单行）的格式用checkgoogleip扫描。
扫描出的结果，有gvs，gws的。我填了4个gvs的到goproxy的hk段，goproxy提示goodip=1，badip=3. 我再换用4个gws的就提示4个goodip了。不知道这个是偶然还是确实是gws要好点？
中国谷歌的没有1个是safe/443，是否直接用gogotester挑选就可以了？

另外，路由追踪工具选google dns，试了几个ip，几步之后各项都是*了。这种ip是不是也不好。那种能到达目标ip，且步数少的才是好ip ？

**Comment by jasonliul** [comment]
@sishentibu 
这种*就是破墙的陷坑路由, 凭空增加丢包率和延时.
俺的线路, 还会有局域网的5,6次空跳.

中国谷歌是不能直接激活的, 俺的理解是HK激活以后, 你的机器被识别为谷歌云主机, 中国谷歌才起作用.

之前澳港韩的ttl都是3-5跳, 现在远远不止.因此表现大不如从前. 像韩国的1/22, 俺这里要跳63次, 从前是4次.

**Comment by jasonliul** [comment]
![sffe](https://cloud.githubusercontent.com/assets/2461165/14821835/d125bf84-0bfe-11e6-95b4-d3fd1a989bac.png)

**Comment by sishentibu** [comment]
我挑的就是类似182.50.94.112 这种443/safe类型的。不过没看TTL。
我再用路由那个挑下

**Comment by jasonliul** [comment]
@sishentibu 
俺之前是用无图片的路由追踪, 更快
http://www.nirsoft.net/utils/country_traceroute.html

某些字段无法追踪到加州, 估计这是最黄金, 最难封的ip段.

**Comment by sishentibu** [comment]
@jasonliul 这个速度真的是快了好多倍
数据库是这个吧？http://geolite.maxmind.com/download/geoip/database/GeoLiteCity_CSV/GeoLiteCity-latest.zip  Geolite-city 的。我这下载好慢，几十k

无法追踪到，不是那种全是*的情况？我怎么感觉就是一个意思的样子

**Comment by jasonliul** [comment]
@sishentibu 
谷歌相关的字段, 通常都能追踪到, 中间会有一跳通往谷歌.
不过奇怪的是, 居然也有追踪不到, 仍然可用的ip字段.

**Comment by sishentibu** [comment]
我试的第二个   210.94.153.39  ，60跳了还没到。

**Comment by jasonliul** [comment]
@sishentibu 
120.28.26.0, 120.28.5.0,120.28.12.0
这几个跳数很少, 不过这次破墙把ping值增大了很多.

之前俺用过, 不逊色韩日ip

**Comment by sishentibu** [comment]
@jasonliul 谢谢赠送的ip
http://i4.piimg.com/a07f8a1d922d21f2.png
这个路由，是不是到3个time都有数值才停？明明都已经到那个ip了。

先睡觉了。88

**Comment by sishentibu** [comment]
@jasonliul 感觉是不是我操作的姿势不对，关软件前试了下你给的第一个ip也是路由不到终点。。

**Comment by jasonliul** [comment]
@sishentibu 
自己点停就是, 这个工具显示绿色才是通连性好, 黄色是不大稳定.

**Comment by Kisesy** [comment]
好麻烦啊，不过强扫也确实管用
我扫到的IP段 177.55.62.0/24 213.105.64.0/24

**Comment by sishentibu** [comment]
@jasonliul 我原先预想的是，在一定步骤之内，从我电脑ip能到目标ip。这种结果才是理想的。
但实际试了一些ip之后，感觉这种好难碰到。都是前面能绿，一定数目之后，后面全红，还到不了目标ip。
难道是我理解偏差了？

**Comment by sishentibu** [comment]
@jasonliul 换上你的ip，被goproxy显示为badip，但实际效果确是，youtube的测速从我原来的500k上升到2M。
明天我再测试下是ip问题还是时间段问题

**Comment by yeahwu** [comment]
谢副社长和主任赠的ip，这才是正菜嘛

**Comment by jasonliul** [comment]
@sishentibu 
这是3段, 得你自己搜, 这家isp应该还有两段, 可以指定段落强扫.

**Comment by sishentibu** [comment]
@jasonliul そが、ありがどう

**Comment by sishentibu** [comment]
@jasonliul 刚才扫了下，这3段没找到443/safe的，只找到443/AkamaiGHost的。
这两段是不适合开篇的方法，但可以强扫出来？

**Comment by jasonliul** [comment]
@sishentibu 
那就是没有, 对于你的线路.
现在是分级的, 都会,省会, 大城市, 小城市/乡郊.

**Comment by yeahwu** [comment]
@jasonliul  副社长早，其实你的那三段ip不新鲜早封没鸟，给两个新鲜的呗

**Comment by caofengzi** [comment]
副社長以前給的185段有幾個很厲害現在還在用。

**Comment by fhzyfjy** [comment]
特意请假1天。折腾来折腾去还是没有找到速度快点IP。只怪自己是小白，大侠们说的都看不懂。

**Comment by sishentibu** [comment]
@jasonliul 这个貌似能持续存活，我再找些ip段去

**Comment by sishentibu** [comment]
我收回我的话。。4小时过去，全部挂了，然后重启goproxy后，复活了2个。。

**Comment by yeahwu** [comment]
ip不建议多，一两个就够了。俺发现你们填ip不麻烦吗？俺都是填了一个懒得填第二个，速度不也是1080p无压力。
goproxy的正确用法是，叉烧狗里打头的ip，看顺眼的填一个，然后就好了，哪有那么多道道哇！
愚蠢的人类……

**Comment by sishentibu** [comment]
填多个是想着，挂掉一个还能继续用。
你填一个，挂了就挂了

**Comment by sishentibu** [comment]
刚才填了4个，提示goodip8个，badip 1个，嘚瑟一下

**Comment by yeahwu** [comment]
告诉你吧，俺的一个两三天都没挂

**Comment by sishentibu** [comment]
这种羡慕啊
我的基本是中午换一次，晚上换一次
偶尔能坚持几天的

**Comment by yeahwu** [comment]
所以俺的结论是，填得越多死得越快

**Comment by sishentibu** [comment]
这几个ip挂了再试试
不过，虽然goodip挺多的，但是打开网页还是不顺畅。我把gae.user.json重建个试试。
不知道这个是不是就是你们说的badip起到的反作用

**Comment by yeahwu** [comment]
gae.user.json有个卵用，不过是个优先级的问题

**Comment by sishentibu** [comment]
升级的时候可以不用再填appid，密码，ip
刚试了一个ip，分分钟挂掉
我还是老老实实的放几个ip吧

**Comment by yeahwu** [comment]
一般的ip段都有一个存活周期，多观察叉烧狗的ip变化，你会找到小强滴。

**Comment by sundaqing1969** [comment]
youtube此刻速度过万

**Comment by 285571052** [comment]
狂扫IP使用方法:是不是这样,?
端口设置443和打开那个web detect,
然后设置random和count的数目,随机扫吗?那个IPmask设置成0.0.0.0?扫完把443端口的IP放入checkiptool检查是吗?我按这样弄,一个GAE的IP都没扫到,是不是扫的太少了,还是姿势不对,求教..

**Comment by xyuanmu** [comment]
今天貌似封锁加剧了，XX扫的IP延时全都加了一倍，Y2B基本只能玩720，反而go越来越优秀了，只用了两枚蒙古IP，Y2B直播1080

**Comment by sishentibu** [comment]
看来最重要的还是观察ip啊。
仅仅扫的话还是确定不了好ip啊。
@xyuanmu xx-mini启动后，会先扫描一遍goodip，再排序的吧？代码看不懂，但测试了几次貌似是这样的

**Comment by xyuanmu** [comment]
@sishentibu mini启动的时候是不会扫描一遍 googleip.txt 的，扫描一遍太费时了，只是读取一遍而已。

**Comment by sishentibu** [comment]
@xyuanmu 是good iP。
那里面的延时是不是也是在读取到那个iP的时候才更新。添加删除ip的时候也是以txt显示的结果为依据，移除最后一个ip？

**Comment by xyuanmu** [comment]
@sishentibu 是的。

**Comment by yeahwu** [comment]
选择ip要考虑字段，而不是单个ip，
比如俺填2个不同字段的ip，肯定比你填10个同一字段的ip，抗操

**Comment by yeahwu** [comment]
@xyuanmu 同样的ip，mini今天比昨天的延时增加100ms，什么鬼？

**Comment by jasonliul** [comment]
![47](https://cloud.githubusercontent.com/assets/2461165/14880041/55a98e78-0d5f-11e6-95cd-0881f1bc5185.png)

照旧.

**Comment by yeahwu** [comment]
上次大屠杀过后，俺这边gae就超不过2000kbs，不管是狗屁还是狗崽子，而且ip段都是优选的。
其实接近1000kbs就很满足了。#毕竟穷

**Comment by phuslu** [comment]
405/404 貌似是 gvs 的问题， 请试下 r434

**Comment by blob2015** [comment]
@jasonliul 
甚好
感谢
