### ISSUE TITLE
IDM不能代理下载，迅雷都可以而且飞快

### ISSUE THREAD

**Issue by Lynchie** [phuslu/goproxy#612]
不开代理能下载，但是需要开代理才能下载的站点又不能下载，不知道是我IDM的问题还是GP的问题

**Comment by Lynchie** [comment]
强制调用IDM之后，线程调到1之后显示 http/1.1 400 bad request

**Comment by jzp820927** [comment]
问题解决了？

**Comment by Lynchie** [comment]
应该是IDM的问题，IDM和chrome组合不太好-

**Comment by jzp820927** [comment]
好吧，如果找到更好的组合方案，记得共享下
