### ISSUE TITLE
404. That’s an error.  The requested URL / was not found on this server. That’s all we know.

### ISSUE THREAD

**Issue by doracl** [phuslu/goproxy#614]
404. That’s an error.

The requested URL / was not found on this server. That’s all we know.

请问是什么问题啊？

**Comment by doracl** [comment]
证书是：*.googlevideo.com，是不是这个原因呢，刚刚换了个google.com的证书好了，但*.googlevideo.com的昨天还能用呢。。

**Comment by doracl** [comment]
还有一个问题，我的ip里有多个，即有googlevide也有google但还是会报错，只剩google就的好了，不能把不能用的ip运行期过滤掉吗?

**Comment by wangbingqian** [comment]
换IP

**Comment by doracl** [comment]
我知道换ip,我的意思是我的ip集合里有能用的，有不能用的，为什么不用能用的，而是报错呢

**Comment by phuslu** [comment]
请试下 r434

**Comment by doracl** [comment]
@phuslu 换r434后好了，谢谢啊
