### ISSUE TITLE
社长, 俺们需要英文版.

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#628]
社长语录

前段时间花了不少精力折腾了 CI （每日构建），从 codeship 到现在的 travis， 目前比较满意了。

每次提交都会出一个新版，其中

    golang 编译器
    http2 库
    glog 库

都是用的最新的，自我感觉良好 :)

之前 goagent 虽然也是类似效果，但是没有像 https://github.com/phuslu/goproxy-ci/releases 保存了完整历史和构建日志 :)

其实纸飞机, puff proxy是国际化的.
其他墙国并没有脑残封杀谷歌, 而且很多重心在封杀视频[伊斯兰教义], 

社长不如趁美酒佳人春光好, 做个简明英文版, 尽量附图. 洋墙友比较简单, 根本不用搜ip.
虽然GAE刚出来就有一些简单的这类代理, 但是功能性能, GoProxy遥遥领先.

世人普遍认可中国是最变态代理软件试验场, 最具权威性.
是时候让世人认识你了, 中国"发死乐"哥. :)

**Comment by hcym** [comment]
人怕出名猪怕壮

但是还有句话

不出名毋宁死

难取舍啊

**Comment by phuslu** [comment]
噗，太逗了。幽默风趣，这捧得我都心花怒放啦。

谢谢抬举。

英文版的问题我考虑过，以下两点让我没啥动力

1. 我做 GAE 对名利看得很淡，如果说早期做 GoAgent 时候还有一些炫技心理，那么现在做 GoProxy 的话已经对所有这些无感了，唯一剩下的就是求个心安而已. 类似的心情在 https://github.com/phuslu/goproxy/issues/509#issuecomment-215109988 也表达过。
2. 还有一点，很多时候驱动我更新的动力是“移情作用”，但我对“洋墙友”的“痛苦”比较难以感受，所以动力就更不大了。

Anyway, 你这个给我了一些动力，我接下来会把 goproxy-gui.exe 先做成双语版的，也算一个交代吧。

**Comment by jzp820927** [comment]
XX-NET，都已经实现国际化了，中文，英文，波斯文。GP确实也可以考虑国际化。

**Comment by drg78rgjui** [comment]
其实是做英文说明吧，goproxy的gui、文件我没看过一个中文。（本来就是英文版）

**Comment by yeahwu** [comment]
Linux下的goproxy，除了“狗屁”是中文，还真没看到别的中文，当然还是原始的cd然后./

**Comment by jasonliul** [comment]
@phuslu 

说真的, 俺分享过印尼墙友的ssh节点, socks节点很多来自白俄达人.
俺们中国人也是礼仪之邦. :)

之前偶尔有无限制的纸飞机节点派发洋墙友...现在天朝人是铁公鸡, 人类蝗灾, 啃吃翻墙资源的害虫.
LOL

**Comment by phuslu** [comment]
r441 的 goproxy-gui.exe 已经“英文化”了，在非中文版的 windows 下启动，它的右键托盘菜单就是英文的了

效果图：
![2016-04-29_213930](https://cloud.githubusercontent.com/assets/195836/14917707/eed59878-0e52-11e6-86aa-bd9e5c457281.png)

目前启动提示还是中文，不过我觉得这个无伤大雅，而且也可以很容易用 reshack 修改成英文。

**Comment by jasonliul** [comment]
OK, 这就足够了, 剩下的他们自己也会折腾.

**Comment by phuslu** [comment]
继续碎嘴几句，

@jasonliul 你说 GoAgent 做得驳杂，的确如此。因为彼时我还免不了有点好胜炫技之心，所以成了一个大杂烩。

现在潜心养性之后，诸心尽褪，再做这玩意就有计划很多了。

后西游记有个回目很不错，http://www.my285.com/gdwx/xs/xus/hxyj/031.htm 附上。

**Comment by jasonliul** [comment]
@phuslu 
No, 社长不能太尘间, 还得"只在乳峰间, 云深不知处"
LOL

**Comment by phuslu** [comment]
做了一个略“没品”的改动，在项目首页加了一个谷歌翻译的图标，算是也有英文版的文档了。

虽然解决方式非常搞笑，但是就到此为止吧。

**Comment by jasonliul** [comment]
@phuslu 
其实这个方式很怀古, 最初网站的多语言很多使用谷歌翻译.
特别是俄圈, 西语葡语圈, 阿拉伯语圈, 有一阵子好像满世界玩谷歌翻译. 最起码这是友善接纳的态度.

但是后来经济萧条, 世人各建藩篱, 就很少见到这种世界大同的气象了.
俄圈, 以色列几乎全部清除了所有双语版里面的英文版.

**Comment by phuslu** [comment]
呃，为了避免固步自封的评价，我还是得声明一下，个人精力有限，目前不会时间花在国际化上面。

接下里把 GAE 优化优化好，就会开始 VPS 的工作了。

说句小觑天下英雄的话，我觉得目前基于 VPS 的种种实现还是有不少提升空间的。

**Comment by yeahwu** [comment]
社长终不能做到坦然，还在乎他人的评价？😄

人家等你的vps等到花都谢鸟……
广告词俺已经帮你想好了，就叫“大杀器”
Phus Lu <notifications@github.com>于2016年4月30日 周六14:05写道：

**Comment by phuslu** [comment]
蛤蛤，毕竟如果大家真这么看我的话，我良心难安的哦

**Comment by jasonliul** [comment]
@phuslu 
天朝人是草根平民阶层的来源, 没有必要小娘子情怀, 洋妞F杯? 照上.
VPS版本?俺会请突厥加入Streisand.

@yeahwu 
你这厮, 成日想把我等抬到庙里, 泥糊金塑, 只能看女香客的pat不能摸,
居心叵测, 妇人耍慧.
捧杀早就out了, 搞搞新意思罢.

**Comment by jasonliul** [comment]
@phuslu 
俺肯定社长读过春秋战国, 周天子就几亩地, 谁都能一袋烟把它给灭了, 但谁都没有这么做.
政治的游戏规则是"虚名可以护身", 除此之外屁用没有. 这不只是中国人, 而是世人, 大家都不能免俗.

即使是世界知名变态, 偷窃女人花内裤千条, 他的一生也不会有横祸.

社长, F杯的国际女粉丝会有的. :)

**Comment by yeahwu** [comment]
女香客还在那，你的手不也在你的身上，你只需要下来走两步就好了！无耻也要纯粹……
Jason Liu <notifications@github.com>于2016年4月30日 周六15:15写道：

**Comment by phuslu** [comment]
汗😓，怎么open了，还能不能愉快的吐槽啊😱？关了关了
