### ISSUE TITLE
Chrome与autorange的兼容问题

### ISSUE THREAD

**Issue by holyshawn** [phuslu/goproxy#629]
最新构建版和发布版在打开autorange之后，尝试下载chrome，
https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
chrome显示:
```
The server could not find the file.
https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg Failed to load resource: net::ERR_PROXY_CONNECTION_FAILED
Resource interpreted as Document but transferred with MIME type application/x-apple-diskimage: "https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg".
```
goproxy显示:
```
I0429 20:26:35.377372   18751 stripssl.go:134] ip:57653 "STRIP CONNECT dl.google.com:443 HTTP/1.1" - -
I0429 20:26:35.828908   18751 gae.go:313] ip:57653 "GAE FETCH GET https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg HTTP/1.1" 206 1572865
W0429 20:26:36.012544   18751 handler.go:122] IoCopy &helpers.multiReadCloser{readers:[]io.Reader{http2.transportResponseBody{cs:(*http2.clientStream)(0xc821915680)}, (*autorange.autoPipeReader)(0xc82002e060)}, multiReader:(*io.multiReader)(0xc821af4600)} return 31266 *net.OpError(write tcp ip:8087->ip:57653: write: broken pipe)
```
关闭http2选项恢复一段时间正常，然后又报错

奇怪的是Safari和手机上用没问题，就是Chrome有问题。。。Chrome最新稳定版。。。
感觉是不是autorange的实现有一些兼容性的问题？

**Comment by Kisesy** [comment]
![qq a](https://cloud.githubusercontent.com/assets/5843694/14914051/a7b68d8a-0e39-11e6-945f-8915feb128a2.png)

我这挺正常的，开不开autorange都是正常的

**Comment by holyshawn** [comment]
@Kisesy 
能不能把你的gae.json配置分享一下，我看看有什么问题

**Comment by Kisesy** [comment]
{
		"DisableHTTP2": false,
		"ForceHTTP2": true,
		"AppIDs": [
			"xxxxxxxxxx"
		],
		"Password": "",
		"Sites": [
			"*"
		],
		"Site2Alias": {
			"*.youtube.com": "google_hk",
		} 
	}

**Comment by holyshawn** [comment]
@Kisesy 
谢啦，好像就是Chrome有问题。。。。

**Comment by Kisesy** [comment]
额，我明白了
GAE DIRECT GET https://dl.google.com/chro........
dl.google.com 不需要代理就能下载，我这里是直连的

**Comment by phuslu** [comment]
autorange 的 bug， 已知问题。

优先修复这个。

**Comment by holyshawn** [comment]
@phuslu 静候佳音😄

**Comment by jzp820927** [comment]
希望设置尽快把这个问题弄好，然后就可以处理我的 auth 了。
