### ISSUE TITLE
搜索到多枚不是google证书，但可用GAE访问google系网站的ip

### ISSUE THREAD

**Issue by drg78rgpxd** [phuslu/goproxy#635]
搜索到多枚不是google证书，但可用GAE访问google系网站的ip，不知道能后利用或改cn盾阵？

例：103.207.68.131 虽然不是google证书，但用在goagent-3.2.0里可以访问google图片，而且本身也指向google域名。

	地址	延迟	证书	通过	带宽
	103.207.68.131	_OK 	 proxy.t4x.org	1	n/a

但访问其它网站立刻403报错。请问能否修改连接方式使其可用？或是其它cn盾阵？

还有两个，也是一样

	地址	延迟	证书	通过	带宽
	103.238.227.196	_OK 	 trace4me.com	1	n/a
	61.92.44.81	_OK 	 *.david.co	1	n/a

**Comment by drg78rgjui** [comment]
@jasonliul

**Comment by hcym** [comment]
curl -I -H "Accept-Encoding:gzip, deflate" http://103.207.68.131
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 30 Apr 2016 14:02:00 GMT
Content-Type: text/html
Content-Length: 69
Last-Modified: Thu, 10 Mar 2016 10:25:26 GMT
Connection: keep-alive
ETag: "56e14b96-45"
Accept-Ranges: bytes

curl -I -H "Accept-Encoding:gzip, deflate" https://61.92.44.81
curl: (51) SSL: certificate subject name '*.david.co' does not match target host name '61.92.44.81'

curl -I -H "Accept-Encoding:gzip, deflate" https://103.238.227.196
curl: (51) SSL: certificate subject name 'trace4me.com' does not match target host name '103.238.227.196'

看不懂，可能是isp临时做什么的

**Comment by jasonliul** [comment]
这是临时节点, 通常一段只有一个.
使用dig玩dns的话, 经常可以见到.

返回结果类似
; (1 server found) -->临时节点
; <<>> DiG 9.9.5-9+deb8u5-Debian <<>> @61.206.143.51 h9.google.com A +short +time=3
;; connection timed out; no servers could be reached
;; global options: +cmd

**Comment by drg78rgjui** [comment]
@jasonliul 也就是说，不可用于代理gae，最多做host？

**Comment by Kisesy** [comment]
我还以为是反代

**Comment by jasonliul** [comment]
@drg78rgjui 
这些节点相当不稳定, 缺乏实用价值

**Comment by drg78rgjui** [comment]
@jasonliul 不一定吧，我今天还能全部连通。
如果说不稳定，山景城ip比这些更不稳定，xx一样能跑
而且不稳定、变动快，墙更难封杀。
目前我想，有没有什么方法能让这些ip像正常ip一样使用？是不是goa连接方式、加密方式需要改动

**Comment by jasonliul** [comment]
@drg78rgjui 
这种是ISP商自订的定向透明代理, 应该不可用.

谷歌也有很多标准透明代理, 能够当成好ip用,
http://www.blackhatworld.com/blackhat-seo/youtube/640431-thousands-youtube-google-ips-proxies.html

很旧了, 只剩少许可用.
不过其实大家估计都用过, 之前泰国那些110字段, 几乎都是透明代理, 不是真正的GIP.

**Comment by drg78rgjui** [comment]
@jasonliul 

我有一个思路，如果gws已经有这么多的临时节点，gvs一定会有更多
临时gvs又是否可用呢？可否看YouTube时指向一个gvs临时节点呢？

**Comment by jasonliul** [comment]
@drg78rgjui 
好罢, 你把社长从乳峰间拎起来拷问便是.
Good luck!

**Comment by drg78rgjui** [comment]
@phuslu

**Comment by jasonliul** [comment]
@drg78rgjui 
俺比较好奇, 可用的中国ip你用什么检测, 证书/服务器类型都不OK?

**Comment by drg78rgjui** [comment]
@jasonliul 你是说那两枚国产小强吗。GoGoTester显示GWS证书啊
我反而在想临时gvs除了真的看YouTube还有什么方法检测

**Comment by jasonliul** [comment]
@drg78rgjui 
天!

我这里GoGoTester, 一个是NA, 一个是NN
但是可以用.

**Comment by drg78rgjui** [comment]
@jasonliul 

可能要去ipip.net，试下多地traceroute，说不定国内网络也是通时无
也可能那两枚小强不是标准gws，只是山寨货 没配置好

**Comment by jasonliul** [comment]
@drg78rgjui 
谷歌的透明代理本来就是山寨货, 俺没有想到中国也还有.

透明代理是谷歌购买的专用代理, 服务器配置很简单, 就是中间人作用. 服务器类型是其他: nginx, 阿婆车, 或者MS. 如果不被加入DNS解析, 破墙没有办法侦测到.

谷歌的透明代理, 通常只在中转区, 泰国印尼,或者中南美, 自身的服务器架设的不够的话. 直接购买透明代理服务最划算.

**Comment by drg78rgjui** [comment]
@jasonliul  所以，如果不考虑安全，真心想用这种类型的ip的话，我建议你扫描一遍cn的全部ip，这是唯一一网打尽的方式。
以我的推断，至少有五十个以上这种ip。

**Comment by jasonliul** [comment]
@drg78rgjui 
俺之前dig过中国dns, 谷歌临时字段非常活跃,也就是国内ISP商经常赚取谷歌的买路费. 俺收集测试过几回, 却是一枚都没有

如果不是你提供两枚, 俺都没有想到居然是俺网络太烂, 检测不正确.

Dig域名
www3-china.l.google.com

另外113.197.105.0 - 113.197.105.255, 也是原香港谷歌字段, 或许也有残兵

这些ip烦请你检测一下, 临时字段通常是一些固定的字段, ip也基本就一个, 但是会变的.

`58.255.35.212|222.73.165.25|58.248.146.97|110.83.50.73|58.248.146.39|101.231.205.22|101.231.38.3|116.247.87.179|180.166.11.86|183.131.15.141|27.115.8.42|27.36.136.58|27.36.142.128|58.23.127.206|101.231.110.1|101.231.120.97|101.231.162.49|101.231.38.2|101.231.54.185|101.231.86.37|116.247.112.217|116.247.97.42|180.166.191.254|180.166.214.94|58.241.21.138|58.248.81.118|101.230.0.157|101.231.218.50|180.166.104.198|180.166.26.130|180.166.26.132|180.166.76.228|180.168.116.170|220.160.112.86|58.253.64.7|116.247.112.169|117.40.156.168|58.248.29.188|115.236.23.184|222.125.13.224|27.115.49.86|58.248.151.63|60.175.168.46|101.231.201.1|183.136.160.201|27.36.130.37|58.16.8.22|58.246.102.104|58.249.83.135|58.251.102.241|58.252.20.217|58.252.48.95|58.255.238.208|60.173.84.254|110.86.74.236|218.6.52.140|221.4.205.158|222.184.54.82|27.36.137.53|27.37.226.239|36.36.9.68|58.16.24.2|58.240.115.82|58.251.116.203|58.252.21.69|60.12.171.190|60.12.80.178|61.167.36.204|124.74.71.210|36.248.26.249|58.210.30.166|58.246.6.106|58.249.72.170|58.251.100.216|58.251.126.203|60.13.141.52|61.177.19.171|61.28.22.220|110.84.1.228|218.98.32.70|58.17.104.67|58.20.128.59|58.210.163.101|58.247.9.66|58.249.77.37|58.252.48.135|60.13.219.20|218.28.180.2|218.28.213.138|58.247.179.146|58.251.118.117|60.210.169.163|111.199.252.194|123.120.66.71|123.15.34.14|123.185.41.39|123.6.90.94|125.33.248.168|125.39.24.132|125.41.102.120|182.124.192.191|218.24.105.162|218.28.52.6|218.29.39.19|221.192.211.210|221.4.164.114|222.128.120.188|222.128.59.44|222.139.152.47|223.241.233.201|27.115.100.30|27.36.137.203|36.250.77.66|60.170.30.27|60.220.197.143|60.28.63.211|60.29.185.162|60.6.207.5|60.8.219.150|61.160.101.92|61.53.235.197|110.252.224.104|110.80.44.222|119.251.235.176|123.114.47.59|123.117.84.107|123.121.133.137|123.130.40.166|123.7.110.113|123.7.117.125|114.80.217.170 `

**Comment by drg78rgjui** [comment]
@jasonliul 

我这里检测结果，只有十几枚是可连通的58.253.64.7|101.231.201.1|114.80.217.170|180.166.104.198|116.247.112.217|101.231.120.97|116.247.97.42|117.40.156.168|60.28.63.211|60.12.80.178|116.247.87.179|60.13.219.20|110.83.50.73|222.73.165.25

**Comment by jasonliul** [comment]
@drg78rgjui 
问题就在这里
103.238.227.196|61.92.44.81 这两个dig没有问题.
但是103.207.68.131. dig出来是103.207.68.250, 这个ip根本连不到.

**Comment by drg78rgjui** [comment]
@jasonliul 
jasonliul大大有没有尝试dig  googlevideo youtube 等域名 结果怎样？

**Comment by phuslu** [comment]
这类探索和先驱性质的尝试我了解的不多，不能提供什么非常好建议。
Issues 里面比我懂的人很多，不好意思。

**Comment by jasonliul** [comment]
@drg78rgjui 

我是用h9.google.com,
谷歌增值合作计划的统称, 基本覆盖所有合作类型, 包括透明代理字段.

**Comment by jasonliul** [comment]
@phuslu 
社长虚怀若谷, 所以黄狗越来越进化为藏獒. :)

**Comment by drg78rgpxd** [comment]
@jasonliul 

那理论上你应该已经dig到不限于gws的google其它服务临时节点 发几个出来研究下

**Comment by jasonliul** [comment]
@drg78rgpxd 
俺很久没有见过gws, gvs服务器类型了.

现在能用的清一色都是sffe[谷歌静态文件], 证书会是gws/gvs.

清明过后, 俺也不得已开始保留记录.
这些是最近dig的
1.179.251.0
1.179.252.0
2.127.251.0
101.96.118.0
103.21.169.0
103.233.37.0
103.233.38.0
103.28.94.0
108.177.14.0
109.195.105.0 
109.88.203.0
110.50.81.0
111.94.249.0
111.95.240.0
113.171.19.0
113.171.238.0
113.171.239.0
113.171.240.0
113.171.242.0
113.171.243.0
113.171.246.0
113.171.251.0
114.108.207.0
114.125.97.0
118.174.25.0
118.69.247.0
118.69.249.0
119.40.97.0
120.28.26.0
122.154.244.0
122.154.133.0
122.154.76.0
122.154.58.0
122.2.128.0
122.2.153.0
123.205.250.0
124.248.162.0
125.234.50.0
146.88.60.0
150.101.161.0
163.28.116.0
163.28.130.0
176.222.187.0
176.222.191.0
180.93.32.0
182.50.94.0
185.5.161.0
194.78.0.0
194.78.99.0
195.46.177.0
201.157.30.0
202.122.145.0
202.124.127.0
203.113.160.0
203.113.161.0
203.121.59.0
203.133.72.0
203.146.98.0
203.162.236.0
203.211.0.0
203.211.8.0
203.66.155.0
209.85.233.0
210.245.14.0
210.61.221.0
210.242.128.0
210.245.14.0
210.94.153.0
211.117.39.0
213.145.140.0
216.58.199.0
221.133.8.0
223.255.227.0
42.112.10.0
42.112.8.0
42.112.9.0
42.119.208.0
42.119.209.0
45.118.245.0
42.119.253.0
49.231.56.0
49.231.60.0
58.71.25.0
61.219.146.0
61.91.17.0
61.91.18.0
61.91.19.0
61.91.161.0
62.4.253.0
77.42.253.0
81.88.148.0
87.245.195.0
87.245.197.0
95.57.218.0

**Comment by jasonliul** [comment]
@drg78rgpxd 
你给的这两个ip, 我之前在柬埔寨找到过两枚.
服务器类型: sffe, 域名, 证书都是自家的, Gogo tester 显示为GA.

不过清明前, 俺几乎从不记录, 缺ip就直接现场摸奖, 好日子过去咧.

**Comment by drg78rgpxd** [comment]
@jasonliul 

可能你唔会了，我想要的是非googlevideo证书，但却在提供googlevideo服务的临时节点/透明代理。一个就够了，有一个这种ip就可以测试很多事了。

**Comment by jasonliul** [comment]
@drg78rgpxd 
http://www.blackhatworld.com/blackhat-seo/youtube/640431-thousands-youtube-google-ips-proxies.html
很旧, 上次清明俺拿来救急的.

你可以研究一下, 别抱太高期望, 
俺用h9是分不清透明代理的, Gogo tester在俺的win7 x64下, 经常无端死翘翘, 极少用.
