### ISSUE TITLE
r470, 4854kbps. 呔, 你等还不换GoProxy?

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#653]
![4854](https://cloud.githubusercontent.com/assets/2461165/14948787/a747bb78-1076-11e6-9e77-ba8ee6b03a58.png)
纪念截图, 全面超越旧狗的GoProxy.
4M电信, GWS4枚+中国gvs4枚+强制http2

Youtube 4854kbps 稳持.

旧狗俺在旧年圣诞附近, 开始突破4000, 需要4枚连号中国ip, 需要Github变成+1伪军.
需要在github点击若干帖子, 速度才能上来, 然后开始视频.

新版直接打开一个https网站, 再打开youtube, 不经意间, 已经突破旧狗 盾阵+1ip 的记录4600kbps.
不要抱残守缺, 做甚么旧狗遗老, 赶快喜新厌旧罢

**Comment by wangbingqian** [comment]
迭代太快，跟不上节奏啊！

**Comment by jasonliul** [comment]
@phuslu 
1. Let’s Encrypt
https://letsencrypt.org/
2. HTTPS2 support.

俺只加了两句广告, 现在俄国的免费软件推介圈, 还蛮有人气.

GAE代理一直有安全性问题, 社长的新版, 努力修正这一点, 不仅是得意之作.
也是GAE类代理的新阶段.

**Comment by jzp820927** [comment]
@jasonliul 这是要社长解决证书问题麽

**Comment by hcym** [comment]
别忽悠

水桶理论看短板

短板还是ip质量，3.0.4的python3版goagent一样跑hdtv

**Comment by zhajjqq** [comment]
这才叫速度吧！
![default](https://cloud.githubusercontent.com/assets/19146257/14950301/43471bf2-1083-11e6-8e0f-1124a22ffb9a.PNG)

**Comment by hcym** [comment]
GoProxy Version    : r470 (go/devel+e50346d linux/amd64)
GoProxy Profile    : Default
Listen Address     : 127.0.0.1:8087
Enabled Filters    : stripssl,autorange|gae,direct|autorange
GoProxy Profile    : PHP
Listen Address     : 127.0.0.1:8088
Enabled Filters    : stripssl|php|

470不错，下午原准备换453的，看来可以继续

**Comment by hcym** [comment]
视频稳定1970Kbps

下载可以6.9M的

看来IP质量不行啊啊啊

**Comment by drg78rgpxd** [comment]
求教，无法使用http2，出现这样的提示

W0502 16:43:35.716994    3132 handler.go:122] IoCopy http2.transportResponseBody
{cs:(*http2.clientStream)(0x11ad1cc0)} return 3776 *net.OpError(write tcp 127.0.
0.1:8087->127.0.0.1:1146: wsasend: An established connection was aborted by the
software in your host machine.)

**Comment by jzp820927** [comment]
你要先测试你这个 IP 是否支持 http2 才能开启 http2，不然就用自动默认的模式就行
不同地区，不同ISP，是封锁状况都不一样，明显 移动网，比电信网，好很多，这个不能比较。

**Comment by xyuanmu** [comment]
我觉得关闭http2速度快一点，这样设置是关闭吧：
```json
	"DisableHTTP2": true,
	"ForceHTTP2": false,

**Comment by phuslu** [comment]
@xyuanmu 是的

**Comment by xyuanmu** [comment]
之前用的是443版本，刚才换了470，发现关闭和开启速度都差不多，试了下面三种设置，IP全是gws的。
```json
    "DisableHTTP2": true,
    "ForceHTTP2": false,

	"DisableHTTP2": false,
	"ForceHTTP2": false,

	"DisableHTTP2": false,
	"ForceHTTP2": true,

**Comment by jzp820927** [comment]
估计晚上才试得出效果吧，白天的网络基本上没什么干扰，也就比较不出差别了

**Comment by drg78rgpxd** [comment]
@jzp820927 ip就是202那个澳门小强 只有一个 没开cn

**Comment by jzp820927** [comment]
刚刚试了一下，你说的那个IP，是支持 http2 的，==我再goproxy 测试一下

**Comment by sishentibu** [comment]
还是看ip吧。最近换了些ip，用youtube测试基本都是四五百k，偶尔上M

**Comment by jzp820927** [comment]
四五百k 连720 都看不了，之类太低了

**Comment by sishentibu** [comment]
@jzp820927 确实是，基本就是480p的水平。

不过刚才换了个ip，直接上3M了，不知道的ip的效果还是时间缘故，还要继续看 
[url=http://www.kekaoyun.com/4198ca0c9f6ffc6b][img]http://i3.piimg.com/4198ca0c9f6ffc6b.png[/img][/url]

**Comment by jzp820927** [comment]
你的图片链接挂了，不过 从  四五百k  到 3M， 人生也太大起大落了吧

**Comment by sishentibu** [comment]
我这边就是起伏很大，说不定过个几个小时 又降下来了

**Comment by jzp820927** [comment]
你测试下，你用的IP，延时，和掉包情况怎么样，还有，你开没开 http2 ？

**Comment by sishentibu** [comment]
又降到1M多了
http://i3.piimg.com/1db9997d684122c9.png
不知道下面的那个buffer health 是什么
默认配置，http2应该没开，Filter RoundTrip *gae.Filter error: http2: timeout awaiting response headers
6个ip，3个一直能ping通，3个一次都不通。。通的都在100以下

**Comment by jzp820927** [comment]
估计还是 IP 的稳定性问题。掉包，延时变动。

**Comment by sishentibu** [comment]
不管了，可以用就行了 
更新到471，稳定在goodip 4，badip 2
猜测有个ping不通的goodip

**Comment by jasonliul** [comment]
@sishentibu 
没理由阿, 我的网络一直比大家烂, 同样的ip字段, 搜出来少很多.
但是新版视频一直还算不错.

**Comment by sishentibu** [comment]
![qq 20160502224221](https://cloud.githubusercontent.com/assets/13832182/14957311/3b16a02c-10b7-11e6-9350-30bb7adfd563.png)
刚刚是的。同样的ip，471竟然没有多出来的ip。不知道是哪里不一样了
我退回470试试

**Comment by jzp820927** [comment]
我去，200k+，太烂了吧。挺多人普遍反映，纯 http2 对 y2b 效果很好，要不你试试，但是要全部换成 gws，然后开启 强制 http2 模式

**Comment by sishentibu** [comment]
@jzp820927 我这波动大啊，晚上都上过4M啊，现在就这么点了。
我先换个版本试试。明天再找下ip

**Comment by xyuanmu** [comment]
刚才挑时间段测试Y2B，发现强制HTTP2速度确实稳定，直播720没任何问题：
![y2b](https://cloud.githubusercontent.com/assets/12442896/14957532/60b6176c-10b8-11e6-9b15-a43967e0ed7c.png)

设置用的这两个：
```json
    "DisableHTTP2": false,
    "ForceHTTP2": false,

    "DisableHTTP2": false,
    "ForceHTTP2": true,

**Comment by jasonliul** [comment]
@xyuanmu 
俺怀疑破墙还没有能力干扰http2. :)

**Comment by sishentibu** [comment]
W0502 22:56:16.698422    1780 gae.go:312] GAE: request "https://i.ytimg.com/vi/na_xv5iFt2Y/0.jpg" timeout: http2: timeout awaiting response headers, *gae.Transport.CloseIdleConnections()
E0502 22:56:16.699420    1780 handler.go:79] 127.0.0.1:53547 Filter RoundTrip *gae.Filter error: http2: timeout awaiting response headers
W0502 22:56:18.924416    1780 gae.go:312] GAE: request "https://i.ytimg.com/vi/98MngruRenY/hqdefault.jpg?custom=true&w=196&h=110&stc=true&jpg444=true&jpgq=90&sp=68&sigh=n36GkZ3iYjnEMnOSkeOydkaV-y8" timeout: http2: timeout awaiting response headers, *gae.Transport.CloseIdleConnections()
E0502 22:56:18.925417    1780 handler.go:79] 127.0.0.1:53561 Filter RoundTrip *gae.Filter error: http2: timeout awaiting response headers
W0502 22:56:19.119049    1780 gae.go:312] GAE: request "https://r8---sn-vgqs7ne7.googlevideo.com/videoplayback?mm=31&fexp=9408207%2C9416126%2C9416891%2C9422596%2C9425352%2C9426686%2C9428398%2C9428656%2C9429161%2C9431012%2C9431117%2C9432076%2C9432603%2C9432807%2C9432972%2C9433045%2C9433096%2C9433405%2C9433671%2C9433946%2C9434210%2C9434289%2C9434755%2C9434765%2C9435253%2C9435604&keepalive=yes&id=o-AOvwUbo5RU2K-fum5lTFMqdNl4LE7lnv93kalsWLP9hv&ipbits=0&pl=27&mv=m&ms=au&source=youtube&ip=107.178.194.83&sver=3&sparams=clen%2Cdur%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&itag=243&upn=AD5x7svdbZc&expire=1462222544&mime=video%2Fwebm&gir=yes&key=yt6&initcwndbps=15147500&requiressl=yes&mt=1462200735&lmt=1449552149321471&dur=226.000&clen=9597000&mn=sn-vgqs7ne7&cpn=IwTjkzoNjuiZv9U6&alr=yes&ratebypass=yes&signature=813DD8693EAF9936E5248AE9C8591B97771C0EBE.280DF8F4FD9E2A75804E593B651AF0EA46D18373&c=WEB&cver=1.20160428&range=85678-197971&rn=16&rbuf=68" timeout: http2: timeout awaiting response headers, *gae.Transport.CloseIdleConnections()
W0502 22:56:19.533075    1780 gae.go:312] GAE: request "https://i.ytimg.com/vi/OyWegP5aiIw/hqdefault.jpg?custom=true&w=196&h=110&stc=true&jpg444=true&jpgq=90&sp=68&sigh=Pl-1cw034kdJrl5gOpR8SMhhXGA" timeout: http2: timeout awaiting response headers, *gae.Transport.CloseIdleConnections()
I0502 22:56:19.813147    1780 gae.go:327] 127.0.0.1:53441 "GAE FETCH GET https://i.ytimg.com/vi/OyWegP5aiIw/hqdefault.jpg?custom=true&w=196&h=110&stc=true&jpg444=true&jpgq=90&sp=68&sigh=Pl-1cw034kdJrl5gOpR8SMhhXGA HTTP/1.1" 304 0
W0502 22:56:20.277259    1780 gae.go:312] GAE: request "https://i.ytimg.com/vi/IxM1tjTvFAc/hqdefault.jpg?custom=true&w=196&h=110&stc=true&jpg444=true&jpgq=90&sp=68&sigh=IRL2KtlhTSlALP0-2PZd9ekUHJM" timeout: http2: timeout awaiting response headers, *gae.Transport.CloseIdleConnections()

一片红字跟黄字。u2b显示又是1M多了。怀疑是坏ip的影响

**Comment by jasonliul** [comment]
@sishentibu 
试试马来字段202.75.147.0/24

**Comment by sishentibu** [comment]
@jasonliul 谢谢。明天再试下，先睡觉了

**Comment by sishentibu** [comment]
估计是badip的干扰。
简单的把6个ip用mff扫了下，留下3个好的。u2b测试马上又2M了。

**Comment by jzp820927** [comment]
@sishentibu 现在的情况，主要是一个段内变动比较频繁，绝对稳定的就比较少了，所以要频繁更新IP
@jasonliul 干扰http2 的最好方法，就是直接对IP丢包。效果还很好

**Comment by drg78rgpxd** [comment]
@jasonliul 想请问如何查看是否成功开启HTTP2

**Comment by jasonliul** [comment]
@drg78rgpxd 
使用gws    "ForceHTTP2": true,
没有坏ip就是成功的.

**Comment by jzp820927** [comment]
xx看http2挺方便的，gop确实不方便

**Comment by phuslu** [comment]
@jzp820927 没办法，xx 的 web 界面很强大，这点没得比啊。

**Comment by jzp820927** [comment]
我觉得性能最重要，UI 可有可无的，我基本上从来没用过 web 界面，而且现在我还比较喜欢用 goproxy 和 XXMINI（精简过 web 的 XX）web 一般比较适合新人使用。

**Comment by phuslu** [comment]
呃，有无 UI 和性能没关系，和适合专家小白关系其实也不大。

适合专家小白的的区别：

1. 暴露足够多的配置参数
2. 方便的进行二次开发

第一点 goproxy 可能稍微好些，但是第二点 goproxy 恐怕要落后于大部分 python 实现的代理的。

毕竟熟悉 golang 的人不多，编译型语言做二次开发也不友好。

不过怎么说，使用 golang 开发 goproxy 是我深思熟虑过的，且行且珍惜吧😄

**Comment by jzp820927** [comment]
好吧，明天还上班，我就先休息了，社长也早点休息，身体是革命的本钱，要保重好啊。

**Comment by sishentibu** [comment]
@jzp820927 只能是看视频的时候再找下ip了。看网页倒是还好

**Comment by blob2015** [comment]
@jasonliul 
网络再烂也不可能比我更烂 :grimacing: 

一帮人来刺激大家 :grin:

**Comment by jasonliul** [comment]
@blob2015 
俺晚间下个美剧, 西瓜吉吉都不跑,得用中国的袜子做前置,通常中途还要熄火几次.

**Comment by xrwz007** [comment]
剛剛更新了484，表示效果滿意，對於如今這樣的周邊惡劣情況來說！～
