### ISSUE TITLE
有没有其他批量检测证书的工具, gogo tester之外

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#659]
gogo tester 对x64很不友好, 无事都要死一死.
其他的.net framework程序都OK.

**Comment by jzp820927** [comment]
其实我也有这个需求。同求。

**Comment by fengixng** [comment]
我强烈推荐checkiptools

**Comment by hcym** [comment]
checkiptools应该够用吧
高级玩家看看
https://github.com/nimia/public_drown_scanner

**Comment by hcym** [comment]
Angry IP Scanner的Java

https://github.com/angryziber/ipscan

都没用过，因为讨厌用pip安装第三方依赖

**Comment by yeahwu** [comment]
不是高级玩家表示不看了，还是信赖俺们的主任
https://github.com/xyuanmu/checkiptools

**Comment by hjolin** [comment]
我自己刚写了一个小程序，用golang写的，可能还有bug，但我用着没有问题。最大的好处是可以大幅度提高并发数，比checkgoogleip等基于python的实现能快扫ip，有兴趣的可以看看
[https://github.com/hjolin/go-checkip](url)

**Comment by hcym** [comment]
Go

好。明天试试

.net麻烦。怕用xp

**Comment by fengixng** [comment]
@hjolin 没有编译好的版本?

**Comment by jasonliul** [comment]
http://securityxploded.com/sslcertscanner.php
这个不错, 但不支持批量处理

**Comment by hjolin** [comment]
@fengixng 我明天研究下怎么发release后就上传可执行文件，还有使用说明。

**Comment by jasonliul** [comment]
@hjolin 
期待一下.

不过希望能设定模式
单纯GWS或混合gws/gvs

**Comment by hjolin** [comment]
@jasonliul 嗯，这个很好加，只要在最后结果里挑出想要的就行了。不过我今天下午用这个工具扫出几百个gvs，一个gws都没有，不知道什么原因，可能是我的ip段不好吧。

**Comment by jasonliul** [comment]
@hjolin 
这不可能, 看来程序有bug.
尝试这段109.195.105.0/24, 有不少gws

**Comment by yqy6611** [comment]
checkiptools，同时获得GAE与Akamai ip

**Comment by cnshinchan** [comment]
期待

**Comment by hjolin** [comment]
@fengixng @jasonliul @cnshinchan 
初步上传了一个，可以试试看
https://github.com/hjolin/go-checkip/files/246662/go-checkip.zip

**Comment by jasonliul** [comment]
@hjolin 
速度确实不错.

不过很奇怪, 混合搜出来全是GWS, 
而且iprange.txt比较单一, 不支持逗号分隔, 或者多行.

**Comment by senninl** [comment]
go-checkip 還不錯啊 中途停止也能輸出IP checkgoogleip可以退休了

**Comment by hjolin** [comment]
@jasonliul 
为啥我混合模式下搜出来的都是gvs呢？我现在手里有1000多gvs，只有可怜的几个gws

**Comment by hjolin** [comment]
这工具目前有个不太影响使用的问题，就是对某些需要redirect的服务器，在okip.txt结果中的延迟显示不正确，即按延迟排序不正确，但基本不影响使用。我目前还不知道该怎么解决这个问题。

**Comment by jasonliul** [comment]
@hjolin 
1.179.251.0/24
1.179.252.0/24
.....

这个不支持, 而且俺搜出来只有gws.

**Comment by hjolin** [comment]
@jasonliul 
这种cidr的是支持的。
你这两个段我扫了，在我的网络情况下没有扫出可用ip。
我这随便都能扫出很多gvs出来，应该是我们的网络差异，不是软件的问题。

**Comment by drg78rgpxd** [comment]
@hjolin 求一个32位版
还有最重要的 希望能够增加暂停扫描的功能（别的扫描器都没有）
这对以各国ip为单位 千万级别的ip扫描太实用了

**Comment by jap33** [comment]
![default](https://cloud.githubusercontent.com/assets/15140842/14982883/44d43448-116c-11e6-9d3c-24fe8854618c.JPG)
怎么不支持32位。

**Comment by hjolin** [comment]
@jap33 
马上加32位
@drg78rgpxd 
暂停功能我还得研究下，尽快吧。

**Comment by hjolin** [comment]
@jap33 @drg78rgpxd 
https://github.com/hjolin/go-checkip/releases/download/v1.0/go-checkip-winows.zip
这里面包含了64位和32位。

**Comment by hcym** [comment]
ubu也要编译吗

./ip.go不行

**Comment by hjolin** [comment]
@hcym 
我编译一份linux版上传吧，稍等。

**Comment by hcym** [comment]
64的

谢谢

**Comment by hjolin** [comment]
@hcym 
https://github.com/hjolin/go-checkip/releases

**Comment by hcym** [comment]
good

谢过

**Comment by jzp820927** [comment]
最好是写个编译教程。不知道是不是最简单的那种
go get https://github.com/hjolin/go-checkip

**Comment by fengixng** [comment]
@jzp820927 绝大部分人电脑上没有编译环境，有编译环境的估计不用教学也会用
还不如直接用编译好的

**Comment by hjolin** [comment]
@jzp820927 
是的，你那样get之后可执行文件在$GOPATH/bin下面。
最好还是自己编译，因为原则上你不应该相信任何人。

**Comment by drg78rgpxd** [comment]
@hjolin 
我试用了一下，如果要完善应该要参考gscan
这个软件目前设计还是很有限，最多取代GoGo Tester 的功能，还不能像mff一样由于千万级ip的搜索中。
有几个缺点是特别明显的：
输出窗口显示当前在测试哪个ip，对搜索一个16段以上的ip来说，实用性极低。何况没人会一直盯着这个窗口吧？就算一直盯着窗口，扫描成功的信息也一闪而过，根本看不清。建议做个选项可以关闭。
还有，按顺序扫描ip。应该是乱序扫描ip才对。乱序扫描，更有机会ip段。

**Comment by hjolin** [comment]
@drg78rgpxd 
是的，这个程序离完善还很远，使用体验很不好，而且现在还有我不知道怎么解决的bug，希望我能有动力把它做好吧。

**Comment by jzp820927** [comment]
一个人的力量有限，还要靠大家发 PR

**Comment by pug908** [comment]
建议加入自定义域名和代理的功能。

**Comment by jasonliul** [comment]
@hjolin 
偷懒的话, 大家会群殴你的,哼哼~  :)

**Comment by hjolin** [comment]
重构了下代码，不发送http request，只凭借tls证书来判断ip类型
https://github.com/hjolin/go-checkip/releases/download/v1.0/go-checkip-win.zip

**Comment by jasonliul** [comment]
@hjolin 
哈哈

**Comment by hjolin** [comment]
@jasonliul 
你觉得这样行吗，只凭借tls证书里面的字段可以判断google服务器类型吧

**Comment by hjolin** [comment]
因为我觉得这样会大大优化网络负载，才这样做的

**Comment by jasonliul** [comment]
@hjolin 
很不错,
不过输入ip这里还是有问题.

试试
109.195.105.0/24
92.226.2.0/24
连续中途熄火, 单独一段就可以, 比Gogo tester好得多.

**Comment by hjolin** [comment]
@jasonliul 
你说的中途熄火是指的console里信息滚动速度不均匀吧，这个是正常现象，不是bug

**Comment by hjolin** [comment]
最好还是把这两个ip段删了，以防万一。

**Comment by jasonliul** [comment]
@hjolin 
中途停止响应.

**Comment by jasonliul** [comment]
Go Check 检出18个
Angry检出20个, +3霓虹ip

Gogo tester检出11个, 淘汰!

**Comment by hjolin** [comment]
@jasonliul 
这个版本是要Ctrl+C退出的，你不会没看到最后那行字吧:)

**Comment by jasonliul** [comment]
@hjolin 
直接停止响应了. 关闭后没有okip.txt
Win7 x64

**Comment by hjolin** [comment]
@jasonliul 
奇怪了，我也是win7 64，没遇到这个问题。是每次都这样吗，还是偶尔？

**Comment by sishentibu** [comment]
@hjolin win10 64 同样有停止的情况。
还有中途自动退出的情况

**Comment by jasonliul** [comment]
@hjolin 
是  "tlstimeout" : 5000,的问题.

如果测试多段, 这个值要设置得大一些.

**Comment by sishentibu** [comment]
@hjolin ip段中，3种格式混合，同时中间有空行。程序直接闪退。

**Comment by hjolin** [comment]
@sishentibu 
我大概知道原因了，尽快fix。

**Comment by sishentibu** [comment]
@hjolin 我到时候再试试。辛苦了

**Comment by jasonliul** [comment]
@hjolin 
"tlstimeout" : 5000, 俺建议7000, 推荐测试两段ip,不要太多.
结果基本跟AngryIP一致, 速度奇快, 而且可以区分gws/gvs.

**Comment by hjolin** [comment]
@jasonliul 
线程数你要是愿意可以调成2000左右没问题。
