### ISSUE TITLE
关于xx-net与goproxy的几点疑问！

### ISSUE THREAD

**Issue by liweitd** [phuslu/goproxy#667]
1、看u2b，goproxy已经比较流畅，连接速度在几千左右。xx-net3.13稳定版，速度竟能达十倍以上，能够到几万，但xx打开网页却有问题。
2、将xx-net的ip导入goproxy(竟有一千多），u2b连接速度依然只有几千左右，并且goodip数并不多。
3、想两个工具同时使用的话，应该怎么设置，端口和pac模式该怎么修改？
希望得到各位技术达人的指点。

**Comment by hcym** [comment]
照猫画虎，自己改一下呗

xx-net端口goproxy端口各自定义，何况他们端口也不能相同，否则启动不了

pac里再根据域名各自定义

我说的是单独的本地pac

自动代理的pac需要在各自文件里改，我没用过goproxy的内置pac

这就不懂了，应该雷同

**Comment by hcym** [comment]
xx-net能够到几万?

那是不错，不过视频需求不大，安心用goproxy吧

**Comment by jzp820927** [comment]
表示，y2b 从来没上W过

**Comment by phuslu** [comment]
视频这块还未开始优化，请关注接下来的每日构建版。

**Comment by xyuanmu** [comment]
刚才升级到xx-net最新版本，经过对比并不觉得xx的速度比gop快。如果你说的速度是Y2B的话只能说那个速度是虚高的，我这里网速只有8M，理论上最高也就8192，可测试时却达到1.2W。
我对比了xx和gop，可以看到gop的 Buffer Health（缓冲时间）明显高于xx，而且看下面的帧数（Dropped Frames）xx是1500帧（约播放50秒）左右截图，gop在1100帧（约36秒）就已经缓冲了86秒：
xx-net:
![2](https://cloud.githubusercontent.com/assets/12442896/15004079/3f317d9c-11e5-11e6-845e-f63f7cb6d99d.png)
gop:
![4](https://cloud.githubusercontent.com/assets/12442896/15004096/72a24ef4-11e5-11e6-9a95-6542046de4e3.png)
