### ISSUE TITLE
社长需努力解决gvs出现的unexpected EOF问题

### ISSUE THREAD

**Issue by drg78rgpxd** [phuslu/goproxy#671]
最新的r492版用gvs，还是报错，几乎无法使用
W0504 16:13:58.825580    3380 gae.go:312] 127.0.0.1:6284 "GAE DIRECT GET https:/
/www.youtube.com/watch?v=* HTTP/1.1" error: *errors.errorString(unexpe
cted EOF)
gws也偶尔出现unexpected EOF

**Comment by caofengzi** [comment]
gvs好像是不支持http2，現在搜索的ip，gvs比gws多很多。

**Comment by jzp820927** [comment]
应该可以自适应的，除非开启 强制 http2

**Comment by phuslu** [comment]
估计你打开了 ForceHTTP2 导致。
