### ISSUE TITLE
Simple DNSCrypt 0.31

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#676]
![standard png](https://cloud.githubusercontent.com/assets/2461165/15021600/5e2439d6-125a-11e6-95e8-b424bfd9c433.png)

这是原来opendns开发的加密dns软件的图形界面

原版
https://dnscrypt.org/

Simple DNSCrypt 0.31 中文版
https://simplednscrypt.org/

**Comment by jzp820927** [comment]
不错。

**Comment by cnshinchan** [comment]
确实不错

**Comment by pgz123** [comment]
@jzp820927怎么用？

**Comment by cnrip** [comment]
解析速度有点慢

**Comment by jap33** [comment]
![default](https://cloud.githubusercontent.com/assets/15140842/15036497/38d97e58-12c2-11e6-98ca-5efd8a68c749.JPG)
跟这个比如何？

**Comment by hjolin** [comment]
Wow, 这个真不错，感谢分享！

**Comment by jzp820927** [comment]
@pgz123 不就是下载，解压，双击，打开麽，还能怎么用

**Comment by jasonliul** [comment]
@jap33 

不看贴, 打pat, 
这是原来opendns开发的加密dns软件的图形界面

**Comment by blob2015** [comment]
这个，怎么download list？resolver list。
试了一下，好像更新不能成功

**Comment by pgz123** [comment]
打不开界面
