### ISSUE TITLE
推荐hjolin 大大新作: 狗搜粮 Go Checkip

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#680]
https://github.com/hjolin/go-checkip

基本OK了
速度奇快, 能区分gws/gvs, 自动排序.

**Comment by liweitd** [comment]
试用了一下，32位和64位均运行数秒后闪退
调高tlstimeout后问题依然存在

**Comment by hjolin** [comment]
@liweitd 
我再想想可能的bug，因为闪退的情况我还没有遇到过，看不到log，所以比较难fix

**Comment by jasonliul** [comment]
@hjolin 
应该是旧版win的原因.
XP或者x86

**Comment by liweitd** [comment]
刚才还以为是加载的ip数太少了
分别加载7000、70000左右的ip数，还是中途闪退
是64位win10的系统
不知道是什么情况

**Comment by hjolin** [comment]
@liweitd 
是已经开始扫描ip之后闪退还是执行之后立即闪退？

**Comment by sundaqing1969** [comment]
还是改良MMF吧，加入测试GVS的代码，那个方便

**Comment by sundaqing1969** [comment]
我这里是执行后立即闪退

**Comment by liweitd** [comment]
已经开始扫描，扫描没超过1分钟即发生闪退。
只加入两个ip段，能顺利扫描，并得到okip文件。

**Comment by sundaqing1969** [comment]
测试几百个ip不会闪退

**Comment by hjolin** [comment]
执行后立即闪退的应该是某一行ip段的格式写错了，这个程序没有完善的ip段格式纠错机制，所以在添加ip段的时候一定要仔细检查。

**Comment by blob2015** [comment]
@hjolin 
是的，以前我遇到过一次，然后细细看着，确实是自己里面有写错了。
@sundaqing1969 
建议，挑几个看着确实没错的，试试

**Comment by hcym** [comment]
老大

linux64也编译个吧，毕竟github也算是李纳厮创办的啊

**Comment by phuslu** [comment]
诸位编译可以用这个网站 cloud-gox 在线编译 http://gox.jpillora.com/
填入 github.com/hjolin/go-checkip 就可以了。

BTW: goproxy 略复杂一些，所以用的是 travis-ci 来编译

**Comment by jap33** [comment]
试了下同一ip段同样10线程mff能扫出60多个，这个才扫岀4个。

**Comment by hcym** [comment]
在线编译

哈哈，不错

**Comment by jasonliul** [comment]
社长献花, 好玩具.
:)

**Comment by jasonliul** [comment]
@liweitd 
#659
"tlstimeout" : 5000, 俺建议7000, 推荐测试两段ip,不要太多.
结果基本跟AngryIP一致,

**Comment by hcym** [comment]
现在找ip动力不够

强制http2，下载能有7M

视频只有3000k，纳闷

**Comment by hjolin** [comment]
@phuslu 
社长如果能指导下代码质量就再好不过了，我刚学golang，很多地方还不那么idiomatic，求社长指导。
还有，tls版本我是放在tlscheckip branch下了，不知道上面那个网站能不能识别branch。

**Comment by jasonliul** [comment]
202.75.147.0/24 马来西亚
109.195.105.0/24 俄罗斯

俄国这段ping值很大, 不过GP并不怎么挑剔.

**Comment by mixool** [comment]
compile error 'github.com/phuslu/goproxy': failed to get dependencies github.com/phuslu/goproxy (exit status 1)

**Comment by phuslu** [comment]
@hjolin 加油。我也刚入门，一起进步 :) 

@mixool goproxy 不是太容易编译的，它依赖一些定制过的东西。具体请看
https://github.com/phuslu/goproxy/blob/wiki/HowToBuild.md

**Comment by cnrip** [comment]
稳定性很差,扫几秒就闪退.

**Comment by jzp820927** [comment]
刚入门就这么牛B，2位也可以算得上是  程序猿里面的战斗机了。

**Comment by hcym** [comment]
jasonliul别放ip了，都是渣，丢人

还是xy偶尔放的ip管用

**Comment by jasonliul** [comment]
@hcym 
那是你人品烂, 俺这里是满速

**Comment by caofengzi** [comment]
@jasonliul提供的那個185段的幾個ip是非常厲害的，質量不好應該和自己所在地方的網絡有關係。

**Comment by jasonliul** [comment]
@caofengzi 

欧洲字段, 近期夜间表现最好的是比利时
62.4.253.0/24
109.88.203.0/24
194.78.0.0/24

**Comment by hcym** [comment]
玩笑了

电信原声v6已经搞定，现在基本不找ip

xy的几段还用着，也就是压压惊，看看gfw的行情

**Comment by blob2015** [comment]
@hcym 
怎么搞定v6的？你江苏电信，我浙江电信，好像都没有支持v6的吧？

**Comment by hcym** [comment]
路由器折腾，刷固件

要看看恩山，koolshare.cn，forum.anywlan.com这一路的论坛

简单验证，就是不用路由器，电脑直接拨号

最早是湖北电信

浙江上海电信肯定有原生v6，江苏的还是欠发达

**Comment by blob2015** [comment]
@hcym 
多谢

**Comment by jasonliul** [comment]
ip v6也只是秀.

清明过后, 谷歌帮开始反弹, 很多国家, 马来, 日本... 之前挖dns是没有收获的, 现在很容易.
谷歌相关ip在重新洗牌.

俺个人反对不缺ip的时段, 盲目"分享"博膜拜的幼稚园超龄儿童秀.
等破墙折腾完, 咱们再玩新字段. :)

**Comment by hcym** [comment]
额

这玩意和ssd一样，用过就别想戒

不过以后不好说，gfw目前还没照顾到

isp解析的都是谷歌香港，大不了找韩日的节点呗

**Comment by jasonliul** [comment]
Dig DNS, 中国的谷歌临时字段比谁都活跃.
买路钱还是要赚的.

就像交警, 真正整治好交通, 每年的罚款定额指标怎么完成?

"不过以后不好说，gfw目前还没照顾到."
这样思维的只可能还是学生.
