### ISSUE TITLE
来来来, 雌雄色狼齐测试

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#682]
以下是全球主要免费色情网站, 涵盖各种视频格式. 
之前是视频下载工具猎鹰EagleGet的赞助商, 俺怂恿迈耶做成标准免费软件的, 其实他损失银子不少.

大家看看GP不能正确处理哪些网站, 统一交给社长处理. 
这些视频网站是最具代表性的, 因为利益保护的驱动.

**能够完全正确, GP将不再有任何视频相关问题.**

OK, 旷男欲女们, 是时候你们为GoProxy挺胸而出了

一 http://www.youporn.com/search/relevance/?query=japanese&page=8
二 http://www.sunporno.com/search/japanese/
四. http://www.pornhub.com/video/search?search=japanese
六 http://www.bangyoulater.com/porn-search/?search=japanese
7. http://www.empflix.com/categories/watched-asian-1.html
8. http://www.drtuber.com/search/videos/japanese
9. http://www.perfectgirls.net/search/japanese/
10. http://www.keezmovies.com/video?search=japanese
11. http://www.videos.com/categories.html
12. http://www.xhamster.com/channels/new-japanese-1.html
13. http://www.redtube.com/redtube/asian
14. http://www.tube8.com/cat/asian/12
15. http://video.xnxx.com/c/Asian%20Woman-32
16. http://www.spankwire.com/categories/Straight/Asian/Submitted/40
17. http://www.xvideos.com/?k=japanese
18. http://www.xtube.com/videos.php?cid=3
19. http://www.pornmd.com/straight/japanese?orientation=straight#2
20. http://www.extremetube.com/category/asian
21. http://video-one.com/popular/Japanese/1.html
22. http://gonzoxxxmovies.com/search/?q=Asian&amp;kwid=5465&amp;c=1
23. http://www.youngpornvideos.com/categories/asian_porn-tube.php
24. http://dtvideo.com/popular/Asian/1.html
25. http://www.porn.com/videos/asian.html
26. http://enlaces.muyzorras.com/asiaticas
27. http://www.hardsextube.com/video/3528503/

GP有问题
3. http://www.tnaflix.com/
5. http://www.nastyvideotube.com/categories/japanese1.html

**Comment by Lynchie** [comment]
嘿嘿，我只想问猎鹰好用不，

**Comment by hjolin** [comment]
@jasonliul 
从url来看你喜欢japan的，哈哈。

**Comment by jasonliul** [comment]
@hjolin 
No, 俺喜欢俄妞.

这是找人要回来的, 俺懒得存底.

**Comment by blob2015** [comment]
: sweat:

**Comment by jap33** [comment]
r502
http://www.tnaflix.com/这个只能放一点点。

**Comment by yeahwu** [comment]
这个叫俺说啥好呢？转走吧

**Comment by drg78rgpxd** [comment]
社长要支持dmm吗

**Comment by fengixng** [comment]
@drg78rgpxd dmm.co.jp访问需要日本IP，gae的出口IP是美国，所以应该是没法支持的

**Comment by jasonliul** [comment]
@blob2015 
你思春了.
视频相关软件, 使用porn站点测试, 是很通用的做法.

**Comment by boycc1974** [comment]
我看看就是

**Comment by verygoogle** [comment]
这么好的贴，不顶不行

**Comment by wukent** [comment]
唯一保留的欧洲自助站
http://m.eroprofile.com/p/photos?pnum=1
http://www.eroprofile.com/m/videos/home?text=jap&pnum=121

**Comment by hcym** [comment]
唯一看的就是photos

pinterest.com
twitter.com
tumblr.com
photosugar.com
nuttit.com
reddit.com
smutty.com
fantasti.cc

**Comment by playnetcn** [comment]
www.tokyo-hot.com
goproxy在线不行，goagent可以正常播放
