### ISSUE TITLE
In addition to its applications to theoretical problems in quantum gravity

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#683]
The currently accepted theory describing elementary particles and their interactions is known as the standard model of particle physics. This theory provides a unified description of three of the fundamental forces of nature

**Comment by jzp820927** [comment]
XX 的 wiki 上不是说，facebook 上传需要特殊处理嘛

**Comment by TangBaohua** [comment]
很久以前甚至还出现Google搜图无法上传的情况，不过现在可以了

**Comment by phuslu** [comment]
r513 修复了。

这次修复默认对所有网站启用 FakeOptions, 这样对有 OPTIONS 依赖的网站都能登陆或者上传了。
比如 facebook, soundcloud, tweetdeck

**Comment by xxnet** [comment]
原来这样解决，学习了

**Comment by CHN008** [comment]
刚用这个地址: https://www.facebook.com/  发布照片不成功.

![16 05 08 1234_1](https://cloud.githubusercontent.com/assets/16646697/15096036/b7b83f6c-1519-11e6-977b-5570046615ee.jpg)


**还是用https://upload.facebook.com/ 才能成功.**
