### ISSUE TITLE
狗屁不响了，帮忙看看

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#686]
**已经搞定了**
从头开始一遍：重新上传客户端，重新填入数据在服务端，好了。
谢谢诸位，谢谢 @hjolin 

---------------

~~在vpn之下upload【GP 497还是5xx，忘记了】，GA 3.2.3运作依然正常，但是GP【503，504之下】亮了红牌，见图
![hs0003](https://cloud.githubusercontent.com/assets/12381704/15063766/4729ff88-137f-11e6-8f03-46f19df42951.png)
![hs0004](https://cloud.githubusercontent.com/assets/12381704/15063774/5c77732a-137f-11e6-8bab-f4237937f12c.png)~~

~~有改监听ip与端口，有设置密码【服务器里面有填入】~~

---------------

~~最要命的，是在GA之下，google无法登陆了，每次登陆，就出现“Unsupported Media Type”，“Error 415”~~

**Comment by blob2015** [comment]
@phuslu 
@其他诸位
谢谢！

**Comment by hcym** [comment]
还是ip吧，gop应该比较完美了
------------------------------------------------------
GoProxy Version    : r504 (go/devel+5031518 linux/amd64)
GoProxy Profile    : Default
Listen Address     : 127.0.0.1:8087
Enabled Filters    : stripssl,autorange|gae,direct|autorange
------------------------------------------------------
I0506 11:42:22.975183    3821 httpproxy.go:82] ListenAndServe("Default") on 127.0.0.1:8087
W0506 11:42:51.904290    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "chinarypto.appspot.com:443") with good_addrs=0, bad_addrs=0
W0506 11:42:51.906963    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "chinarypto.appspot.com:443") with good_addrs=0, bad_addrs=0
W0506 11:43:42.665996    3821 handler.go:130] IoCopy http2.transportResponseBody{cs:(*http2.clientStream)(0xc823fbea00)} return 31898 *net.OpError(write tcp 127.0.0.1:8087->127.0.0.1:58158: write: connection reset by peer)
W0506 11:43:43.486356    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "clients1.google.com:443") with good_addrs=7, bad_addrs=0
W0506 11:44:01.668604    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "dhinarypto.appspot.com:443") with good_addrs=9, bad_addrs=0
W0506 11:44:02.196838    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "chinaryptp.appspot.com:443") with good_addrs=10, bad_addrs=0
W0506 11:44:05.439323    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "ehinarypto.appspot.com:443") with good_addrs=13, bad_addrs=0
W0506 11:45:17.336199    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "dhinaryptp.appspot.com:443") with good_addrs=15, bad_addrs=0
W0506 11:45:19.226489    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "ehinaryptp.appspot.com:443") with good_addrs=17, bad_addrs=0
W0506 11:45:19.233959    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "ehinaryptp.appspot.com:443") with good_addrs=17, bad_addrs=0
W0506 11:46:14.845925    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "ssl.gstatic.com:443") with good_addrs=18, bad_addrs=0
W0506 11:46:17.067612    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "inputtools.google.com:443") with good_addrs=18, bad_addrs=0
W0506 11:49:32.557392    3821 multidialer.go:245] MULTIDIALER DialTLS("tcp", "clients2.google.com:443") with good_addrs=18, bad_addrs=0

**Comment by liweitd** [comment]
怎么做到badip为0的？

**Comment by hcym** [comment]
我的偶尔会bad很多

再重启一下就好

**Comment by blob2015** [comment]
@hcym 
跟GA一样的ip，ga正常啊，gp不比ga挑食？

**Comment by hcym** [comment]
那就不懂了

同样的ip我这边goa根本没法用，gop表现稳定，深夜好的时段下载有6－7M

线路是江苏电信，签约带宽不过50m，国内下载一般4－5M

只有用ubuntu的科技大源和常州电信机房的源同步更新才会超过5M

http2是个好东西

**Comment by yeahwu** [comment]
信息量太少，目前的建议是删除客户端和浏览器里的证书，重新生成，重新导入一下
监听还是改为127.0.0.1试试

**Comment by blob2015** [comment]
@yeahwu 
谢谢，我试一下

**Comment by hjolin** [comment]
第一个图片是私钥错了，第二个图片是已经有程序在占用tcp端口。

**Comment by blob2015** [comment]
@hjolin 
多谢，果然是专业人士 :open_mouth: :stuck_out_tongue: :sparkles: :beers:

**Comment by caofengzi** [comment]
嘿嘿

**Comment by blvezym** [comment]
我也有用样的问题，部署完以后现在的情况就是xxnet 登录谷歌也出现这个错误了。

**Comment by blob2015** [comment]
@blvezym 
新版客户端暂时与黄狗的不兼容，据说以后会试着兼容
