### ISSUE TITLE
Google搜索，经常要求输入验证码，能破不？

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#687]
这个问题，在我这边，一直存在，不知道诸位怎么样？

---------------

我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认这些请求是由您而不是自动程序发出的。为什么会这样？
IP 地址：x.x.x.x
时间：2016-05-06T04:45:11Z
网址：https://www.google.com/search?q=XXX

---------------

@phuslu 
谢谢

**Comment by yeahwu** [comment]
这个能破滴。phuslu会叫你关注新版滴 :smiley:

**Comment by blob2015** [comment]
@yeahwu 
谢谢
可能：登陆了帐号来搜索？搜索框跳转的搜索比较多？搜索次数比较多？老兄rp比我好？其他？ :grinning:

**Comment by zxzxvic** [comment]
请强制https

**Comment by jzmswe** [comment]
楼主不会用GP打开Google搜索吧，在HOSTS中指定即可。

**Comment by blob2015** [comment]
@zxzxvic 
俺试试，谢谢
@jzmswe 
都用ga，然后要开始全面过渡到gp，hosts，终究麻烦，而且也容易波动，丢个百来个ip在gp，可以太平好一段日子
谢谢

**Comment by jasonliul** [comment]
@blob2015 
主要是证书的问题.
早期的GP, 俺与GA一起用, 证书也是拷贝的GA下面的crt目录.

用新版的话, 旧的东西不如一把删除, 包括删除GA证书的信任, 不然很容易搞乱.

**Comment by blob2015** [comment]
@jasonliul 
好，听老兄的
谢谢

**Comment by wenfengmsn** [comment]
换IP
我以前遇到过，更换IP后就没了。

**Comment by LGA1150** [comment]
请给出IP的前两个数

**Comment by caofengzi** [comment]
輸入驗證碼基本上都是更換ip地址引起的。

**Comment by yeahwu** [comment]
看社长这个，google.com走的是直连，理论上是不会出现这个问题的。

**Comment by phuslu** [comment]
是的，应该是 IP 问题。

**Comment by blob2015** [comment]
@LGA1150 
122.245.x.x
是我的本地ip，浙江电信
与我是否用搜索框【Firefox的】有关联不？
另外，基本上我都是登陆了google的帐号来搜索【可以设置一些搜索习惯】
谢谢

**Comment by jasonliul** [comment]
@blob2015 
这是你还在使用GA的假证书才有的, 退出谷歌帐号,清除浏览器缓存, 清除cookie.
删除GP的证书, 重新生成一个导入浏览器证书管理.

新版GP的证书其实没有问题, 无论谷歌或Yandex.

**Comment by blob2015** [comment]
@jasonliul 
上次服务端上传遇到麻烦，就从头开始搞了一遍，一切都删除，firefox清除cookie【其实还重装了，因为折腾的时候，不小心误伤了 :grimacing:  】
GP的证书是新的

**Comment by jasonliul** [comment]
@blob2015 
奇怪, 新版我没有遇见过这问题, GA才有.

**Comment by caofengzi** [comment]
gp使用的ip沒有遇到過提示輸入驗證碼的事情，xx有時候到是經常提示。
![emoji_u1f31e](https://cloud.githubusercontent.com/assets/13650252/15100214/6877adb8-159e-11e6-86d5-6099612df5a2.png)

**Comment by blob2015** [comment]
@phuslu 
昨天656看中天，144还会断【跟3000k那是没法比 :grinning: 】，现在能360稳定了
开始对autorange开刀了？
社长那天有心情，有精力的话，也看看这个验证码的问题啊【books.google可能也会一起搞定了】 :grinning: 
验证了，不登陆帐户【可能与帐户注册的所在地也有关系？】，没有这个问题，登陆了就有了

**Comment by MkAnaio** [comment]
是用相同IP的GP同一时间请求GOOGLE服务器次数过多造成的吧。

**Comment by yeahwu** [comment]
google books
试试下面的网址，真是为你们着急
https://books.google.com/

**Comment by MeABc** [comment]
@blob2015 

google的提示已很明白了，是相同的IP同一时间请求GOOGLE服务器次数过多造成的

看到你说你用电信且用路由器，我突然想到，是不是电信给你分配了内网IP，你可以查看路由器上电信给你分配的IP，和你百度IP的地址是不是一样。（我猜你是属于这种情况）

**Comment by hcym** [comment]
用tor遇过，比较烦

**Comment by yeahwu** [comment]
用tor的话用代理搜索，就不会有验证情况
比如tor浏览器默认的Disconnect，
在别的浏览器上，只需要一个Disconnect插件就可以搞定

**Comment by hcym** [comment]
噢

试试谢谢

6.0速度堪比蓝灯，不知道能撑几天

还是GAE类的体验最爽

**Comment by blob2015** [comment]
@MkAnaio 
这样啊，那试试看。谢谢
@MeABc 
谢谢，去看一下

**Comment by blob2015** [comment]
@yeahwu 
books.google.com，搜索正常，一点击查看，就会成了books.google.cn，然后就歇菜了，502错误，手动更改cn为com，或者com.hk，就可以看了……

**Comment by yeahwu** [comment]
还有这奇葩问题？俺用的火狐，从没你说的这种问题！
个人问题，自己找原因。

**Comment by yeahwu** [comment]
你可能要手动把 https://books.google.com/ 这个地址加入代理

**Comment by Kisesy** [comment]
@blob2015 不要改动 "google_cn" 里的网址

**Comment by blob2015** [comment]
@Kisesy 
靠谱，谢谢

**Comment by benetjiao** [comment]
会不会和用户登陆有关，我在公司的电脑上google一直没有问题，可是回到家中，经常的让输入严重码，用的是同一个账号登陆的

**Comment by jzp820927** [comment]
不好说，这种问题产生的原因挺多的，总之一句话，就是大量用户使用同一个IP连接GOOGLE，造成 google 认为是非正常连接，从而产生验证码。

**Comment by MeABc** [comment]
> 经常的让输入验证码

xx-net 用户这个反馈最多。我是理解是，很简单，他们基本上都是在用同一个IP库，结果是有很大机率在用同一个IP。我个人（上面也有人说了）解决方法是，自已扫IP，即换IP，增加自已的IP库，这样在一定程度上能减少出现这种情况的机率，我现在很久就没有碰到了。

还有一个是宽带分配内网IP的情况。这个解决方法是分配公网IP就可以了。

**Comment by blob2015** [comment]
@MeABc 
除了ip库问题——这个确实是一个基础因素——，还有浏览器的插件，我停用了某个SEO扩展里面的google相关设置，也大大降低了这一问题。
