### ISSUE TITLE
关于扫描出来IP格式转换

### ISSUE THREAD

**Issue by PvCDp** [phuslu/goproxy#689]
有没有什么软件可以把：
40.136.3.112 1099 *.googlevideo.com gvs 1.0
41.187.111.27 2287 google.com gws
格式转换成：
“40，136.3.112”或40.136.3.112|41.187.111.27？

**Comment by cnshinchan** [comment]
用checkiptools可以转换

**Comment by PvCDp** [comment]
@cnshinchan 用的就是这个软件，能告诉我怎么转换吗？

**Comment by PvCDp** [comment]
@cnshinchan 看到了，多谢！

**Comment by blob2015** [comment]
@phuslu 
老兄，啥时候改成ini？
之前可以横放，现在也可以不用单独一列了吧？
放了500左右的ip，一个一列，更改的时候，还是要拉好一会儿 :grinning: 

---------------

EmEditor，Ultra Editor，以及其他支持正则的编辑软件，然后，就很简单了

**Comment by Lynchie** [comment]
可以横放，不用一个一列
