### ISSUE TITLE
巴西即将成为头号墙国

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#698]
巴西总统已经否决智能ID上网卡的动议, 不过议会毫无疑问还会坚持动议.
巴西"智能网络良民卡"需要就近在警察局办理, 扫描指纹, 视网膜等个人信息, 成为个人上网的唯一凭据.

天哪, 俺们天朝, 波斯这些老牌墙国脸往哪搁?

**Comment by hcym** [comment]
也就古巴朝鲜超越墙国

巴西不够格

**Comment by tunnelode** [comment]
应该不一样吧。我国网民属闷骚型，稍有压制就逆来顺受。巴西网民属于豪放型，胆敢有墙，会造反。你看他们的足球和舞蹈。所以这个可能是巴西犯罪率太高，为防止毒品、枪支交易的吧，不是要设墙不如出国，性质不一样吧。

**Comment by drg78rgpxd** [comment]
头号强国不是伊朗、土耳其、印尼、沙特吗、大马那个巫统最近也有恶化的迹象
http://bowenpress.com/news/bowen_63586.html
可惜了土耳其，如果不是墙，距离近本来可以提供几百好ip

**Comment by jasonliul** [comment]
@drg78rgpxd 

良民证很陌生? 这是邪恶政府把公民作为准罪犯待遇.
什么翻墙技术, 不就是个扯淡.

**Comment by rothen80** [comment]
最怕天朝听到这新闻后产生学习国外先进管理经验的想法

**Comment by xxnet** [comment]
​韩国好几年前做过类似的事，后来出现一次个人信息数据库泄露的安全事件。
现在不知道还有没有实行

**Comment by AhernWalker** [comment]
顺便提一下，巴西的谷歌ip一直没有被屏蔽过，hosts用了一年多也没问题过。速度不是很快，查阅资料很适合

**Comment by jzp820927** [comment]
巴西的 IP 延迟怕有 几百吧
