### ISSUE TITLE
小建议：gfwlist能否不直接放在软件里面？

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#703]
看见有几次的更新版本号，就是更新gfwlist，能否交给使用者使用的其他软件？为 phuslu 减一丁点的负。
Firefox里面， FoxyProxy好像可以设置gfwlist的订阅。
而且，gfwlist似乎不怎么收录一些提供翻墙软件的地址，比如cyberghost【已经很难使用了，在墙内】，还有其他，往往需要手工添加。
当然，可以随软件附送一份，心情好、精力足的时候，隔了年许的话，也可以稍微更新下 :grin:

**Comment by phuslu** [comment]
谢谢好意 :smile: 

更新 gfwlist.txt 是有 autoproxy filter 自动完成的，我每次只要 git commit && git push 发布就可以了。

**Comment by cicku** [comment]
@blob2015 如果您认为 gfwlist 有未收录的内容，请提交给我们而不是在这里抱怨。

**Comment by jasonliul** [comment]
@cicku 
揪住, 暴打pat,
反正都是大大~~

**Comment by blob2015** [comment]
@cicku 
竟然引来大鱼，抱怨还有这功效，神奇 :grimacing: 
到时候，把遇到的一些，提交一下 :grimacing:

**Comment by hcym** [comment]
平生最怕编译，一地鸡毛

他们都会玩码，commit一下git一下简单

我是不用内置pac，因为广告第一，翻墙第二

还讨厌插件，所以一直用pac挡广告

**Comment by phuslu** [comment]
@hcym goproxy 内置 pac 如果不喜欢 gfwlist 的内容的话，直接  disable 就可以了，这样 http://127.0.0.1:8087/proxy.pac 就是一个纯净的 pac 的文件。

**Comment by hcym** [comment]
@phuslu 
我是浏览器指定本地
--proxy-pac-url=file:///home/wallproxy/ssa.pac

用http://127.0.0.1:8087/proxy.pac指定效率更高吗

那我再调整一下试试
