### ISSUE TITLE
543会自动失效

### ISSUE THREAD

**Issue by PvCDp** [phuslu/goproxy#705]
大概半个小时左右就不能打开网页，重启后一切又恢复正常，请社长看看。

**Comment by PvCDp** [comment]
一直有这个问题，一段时间后就断线了，必须重启gop

**Comment by caofengzi** [comment]
俺沒有遇到過這樣的問題。

**Comment by PvCDp** [comment]
100m宽带，，播放美国之音学英语视频总是断断续续，缓冲条已经领先很多，但是还是断断续续，各位大神看看是什么问题，多谢。

**Comment by caofengzi** [comment]
voa視頻播放沒有問題流暢。
![emoji_u1f60a](https://cloud.githubusercontent.com/assets/13650252/15103134/48763d36-15da-11e6-83b3-d52c0861b038.png)

**Comment by immeman** [comment]
我这里偶尔也会出现过楼主这样的问题，浏览器是火狐38.0.6，我有点怀疑是浏览器和GOP有兼容问题，还有推特的小视频会中途断掉

**Comment by hjolin** [comment]
你试试只放入gvs ip关闭http2，或者只放入gws ip强制开启http2.

**Comment by phuslu** [comment]
有这个可能，我这边也注意观察一下。复现了以后再修复。

**Comment by xrwz007** [comment]
@hjolin 我都試了，似乎差不多，油管晚高峰，電信。緩衝10秒後就變慢然後不動，ip是新鮮掃出的mmf2和checkgoogleiptools最新版掃的，總的來說gvs強制關閉http2更堅挺，gws 強開http2會斷流

**Comment by xrwz007** [comment]
初步懷疑是高峰期isp對海外帶寬出口限流，流量一大就斷開或干擾

**Comment by jzp820927** [comment]
所以还是 480 靠谱，什么高清，很容易高流量然后出现干扰

**Comment by baoziwan** [comment]
@xrwz007 其实很容易验证怀疑的。我昨天做了验证，答案是否定的。 
可见[https://github.com/phuslu/goproxy/issues/694](url)

**Comment by xrwz007** [comment]
@baoziwan 鏈接失效了哦 404

**Comment by baoziwan** [comment]
@xrwz007 不知道为什么直接点击打不开，复制链接在浏览器新窗口就可以打开了。似乎有人刚刚帮我改了一下？
链接地址再发一遍：https://github.com/phuslu/goproxy/issues/694
这只是我一时一地的测试结果，希望其他人也能测试一下看看结果是否相同。
