### ISSUE TITLE
need more than 2 values to unpack 错误

### ISSUE THREAD

**Issue by johnsonz** [phuslu/goproxy#706]
GP r520
win 10 x64
最近启用了GP，上传服务端一切正常，但是dropbox客户端不能代理，提示无效的代理。切换回goagent，客户端正常了，但是打开网页出现need more than 2 values to unpack错误，facebook也是这个错误。请问他们的服务端会互相影响吗？？还是我哪里设置错了？

![capture](https://cloud.githubusercontent.com/assets/2533629/15102964/7ba85d08-15d8-11e6-967c-6dd4092d6940.PNG)

**Comment by cnrip** [comment]
GOAGENT客户端连GOPROXY就会出现这情况,以前版本没这状况.

**Comment by johnsonz** [comment]
请问怎么解决？总不能换回goagent吧
