### ISSUE TITLE
The Bekenstein entropy is proportional to the black hole mass squared

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#709]
An important feature of anti-de Sitter space is its boundary (which looks like a cylinder in the case of three-dimensional anti-de Sitter space). One property of this boundary is that, within a small region on the surface around any given point, it looks just like Minkowski space

**Comment by hcym** [comment]
一样啊

isp出口带宽，据说移动的稍好

**Comment by jzp820927** [comment]
晚上是重点干扰时段，一杯证明。

**Comment by fuckGFW2015** [comment]
出口带宽，服务器负载，IP干扰程度都有可能

**Comment by hcym** [comment]
高峰时段明显，过山车一样

**Comment by xrwz007** [comment]
據說，gfw的機器學習能力掃到類似gae服務的ip後 會模仿客戶端去鏈接 而且是非常龐大密集的鏈接 這樣會同時造成gae的負載過大，以及isp海外出口帶寬的擠占，真是邪惡啊，艹～！！！！

**Comment by hcym** [comment]
目前还行，白天有2000，也稳定
