### ISSUE TITLE
Windows哪个本地播放器能播放g drive视频？

### ISSUE THREAD

**Issue by okgoogle** [phuslu/goproxy#712]
我想先获取google drive上的视频下载链接，然后用本地播放器打开视频的下载链接，以达到在线看视频的目的，但是potplayer和vlc貌似都不行的，也可能是我不会设置。
我想这样做的原因是下载速度比在G drive在线看会快很多，用网页看G drive视频时缓存的速度一般。

请各位不吝指教。或许你们有更好的方案***

**Comment by caofengzi** [comment]
不是播放器不支持吧，應該是google雲盤鏈接播放也得用代理才能播放吧。

**Comment by okgoogle** [comment]
设置了代理也没法播放，各位不妨上传一个小视频测试一下。如果能成功的，请详细讲解一下设置方法，谢谢！

**Comment by caofengzi** [comment]
你發一個g雲盤視頻鏈接試試。

**Comment by cnrip** [comment]
发个链接来试试

**Comment by jzp820927** [comment]
求测试视频链接

**Comment by pug908** [comment]
https://lh3.googleusercontent.com/unvmiyziHL6agq3E5_8QThE5MN7TIUCcFjrT_zBEBk4ZNTf4baWY_jhvhzWeSb5mvqE=m22

**Comment by baoziwan** [comment]
我去，怎么弄了个小黄片。你好歹也提示一下啊。

**Comment by okgoogle** [comment]
@caofengzi @cnrip @jzp820927 
提供个微软的测试视频，G drive的，楼上那个应该不是G drive。（每个Gmail账号都有G drive）
https://drive.google.com/file/d/0B_hVzXWRG1A_QXNsSlM3aEpXMUU/view?usp=sharing

**Comment by sishentibu** [comment]
为什么我这边 @pug908 的视频自动重定向到https://r5---sn-i3b7kner.googlevideo.com/videoplayback?id=16b3503192b8e9db&itag=22&source=picasa&begin=0&requiressl=yes&mm=30&mn=sn-i3b7kner&ms=nxu&mv=u&nh=IgpwcjAzLmhrZzAxKgkxMjcuMC4wLjE&pl=20&mime=video/mp4&lmt=1449844099075882&mt=1462881933&ip=123.97.83.253&ipbits=8&expire=1462911376&sparams=ip,ipbits,expire,id,itag,source,requiressl,mm,mn,ms,mv,nh,pl,mime,lmt&signature=B55D72CC106AA8725BECC4D16FA19FE1D5A6C15A.96D62B97477BD16FDBB0A9015B108EE725C28F58&key=ck2

@okgoogle 的视频提示 An erroe has occured.Please try again later.

**Comment by okgoogle** [comment]
@sishentibu
goproxy想在网页在线看G drive视频需要对goproxy做一些设置：
gae.user.json里的 ForceGAE 里加上这两行
              "drive.google.com",    
               "*.c.docs.google.com",
强制走GAE性能会下降吧，所以我在“一楼”的问题是，怎样用本地播放器播放G drive视频的下载链接。

**Comment by sishentibu** [comment]
@okgoogle 添加了之后还是一样。r527. 我等会更新下再看看

**Comment by okgoogle** [comment]
我这里添加后重新载入是可以的。r497
补充：播放第一个视频可以在ForceGAE 里加上
"*.googleusercontent.com",

**Comment by sishentibu** [comment]
@okgoogle 按照我的理解，ForceGAE的效果，不是跟全局使用 goproxy 的效果一样的吗？

**Comment by okgoogle** [comment]
@sishentibu 是不一样的，尤其是对于google网站而言。
技术细节我并不知道。但是可以这样猜一下。我们要找到可用IP才能用goproxy吧，我们用这些IP链接gg的服务器，gg的服务器是能知道我们的真实IP的。通过goproxy上其他网站我们的IP地址变为美国。
ForceGAE的效果，相当于翻出去后重新向gg的服务器发出请求，使gg的服务器和网站以为我们的真实IP是美国的。
目前G drive可能并不允许国内IP在线播放，会提示错误。

**Comment by sishentibu** [comment]
@okgoogle 这样解释的通了。不过我需要再扫下ip，goodip badip 都为0，不知道什么回事

**Comment by okgoogle** [comment]
@pug908 大大你在上面贴出的地址原来是可以在播放器播放的，请问该地址是怎样获取的呢，谢谢
https://lh3.googleusercontent.com/..........
