### ISSUE TITLE
请问 DNS 服务器，你们用哪个？？

### ISSUE THREAD

**Issue by littlebigdream** [phuslu/goproxy#716]
请问 DNS 服务器，你们用哪个？？

**Comment by hcym** [comment]
默认isp提供

翻墙的都是直接ip地址，所以没必要为DNS 服务器操心

无非多找几个谷歌ip

**Comment by mixool** [comment]
腾讯云学生机，自己搭建[https://github.com/zyqf/DNS](url)，可以访问google,播放youtube,

**Comment by mixool** [comment]
[https://github.com/phuslu/goproxy/issues/url](url)

**Comment by mixool** [comment]
[github.com/phuslu/goproxy/issues/url](url)
