### ISSUE TITLE
goproxy无法播放部分youtube频道的FLASH视频

### ISSUE THREAD

**Issue by drg78rgpxd** [phuslu/goproxy#717]
类似这种
https://www.youtube.com/watch?v=Y5YutODgC0k

https://www.youtube.com/watch?v=pWkAi3Vz-48

都无法播放

**Comment by jap33** [comment]
视频本身的问题，用ss、蓝灯都放不了。

**Comment by baoziwan** [comment]
VPN可播。

**Comment by jzp820927** [comment]
是不是有区域限制

**Comment by 821938089** [comment]
flash播放器是无法进入代理的，即使设置本地代理也没用，除了vpn，试试使用扩展或插件强制替换成html5播放器

**Comment by drg78rgpxd** [comment]
@821938089 使用多个强制html5扩展，依然出现错误

**Comment by lifly** [comment]
好像是DRM，估计无解

**Comment by 821938089** [comment]
用vpn看吧，这个播放地址不是一般的https协议，而是rtmp协议，xx不支持，由于rtmp协议特性导致这种视频是无法下载的，用在线解析下载都会报错（This video is RTMP(E) encrypted. Sorry, we cannot download it!）

**Comment by fuckGFW2015** [comment]
@821938089 rtmp协议可用rtmpdump下载

**Comment by p1956** [comment]
rtmp协议得用socks代理或vpn
