### ISSUE TITLE
求大神来教怎么纯手动上传到app引擎

### ISSUE THREAD

**Issue by cannanlly** [phuslu/goproxy#724]
用bat文件上传总是先卡几分钟然后死掉

**Comment by blob2015** [comment]
#720 
关键词：夜深人静，good ip【ga，gp，还不要改端口？】/ good vpn

**Comment by masktao** [comment]
用蓝灯全局模式任何时候都可以正常上传成功,比较稳定

**Comment by cannanlly** [comment]
晚上1点试，不行，3点还是不行，早上7点8点都不行。lantern一样会卡，然而访问网页没啥问题

**Comment by blob2015** [comment]
lantern的版本？

**Comment by masktao** [comment]
Lantern version 2.2.3 (20160512.140332)

**Comment by cannanlly** [comment]
看来我需要去研究google app engine sdk 了
