### ISSUE TITLE
为啥youtube只能看几秒钟就自动跳转到下一个视频了?

### ISSUE THREAD

**Issue by masktao** [phuslu/goproxy#726]
自定义的ip,打开很流畅,但只能看几秒钟就自动跳下一个视频了,用xx-net没这个问题,但xx-net没法自定义ip

**Comment by panpeach** [comment]
我和你相反，gop，火狐浏览器能完整流畅看youtube视频。而voa（美国之音 ）却只能观看几秒。
（goa，xxnet观看voa视频没为题）

**Comment by masktao** [comment]
下了最新的服务器版,5.12 10点更新版本,重新上传依然只能看几秒,下载只能32M, xx-net可以完整看,下载也只有32M

**Comment by masktao** [comment]
下了最新的服务器版,5.12 10点更新版本,重新上传依然只能看几秒,下载只能32M, xx-net可以完整看,下载也只有32M
看youtube不是所有只能看几秒,有的还是可以看到后面的,多数看几秒就跳了

**Comment by blob2015** [comment]
关闭自动跳转到下一个视频试试？
这边俺观看正常。
这个好像在更新计划的后面，等着按部就班地来吧。

**Comment by masktao** [comment]
那只有等了,发现更新的服务端后,用xx-net只用google搜索永远只跳转到主页面,没有搜索结果,但用goproxy就可以搜索,但youtube只有几秒钟
