### ISSUE TITLE
“Your Name committed 6 hours ago”是怎么回事？我明明啥也没做啊？

### ISSUE THREAD

**Issue by fletchere** [phuslu/goproxy#73]
我的以fh0205zhou开头的gmail账户被黑了，难道有人以我的名义提交代码？

**Comment by phuslu** [comment]
和  You Name 没有关系， 那个是我在 vps 里面没有制定名字，所以显示为 You Name

**Comment by fletchere** [comment]
谢谢phuslu，刚刚还吓我一跳。
