### ISSUE TITLE
3proxy 0.8.6

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#733]
3proxy 0.8.6
Lite 32-bit
[url]https://github.com/z3APA3A/3proxy/releases/download/3proxy-0.8.6/3proxy-0.8.6-lite.zip[/url]
64-bit
[url]https://github.com/z3APA3A/3proxy/releases/download/3proxy-0.8.6/3proxy-0.8.6-x64.zip[/url]

! Fix: random 00012 errors in some configurations

**Comment by cannanlly** [comment]
thanks!

**Comment by jzp820927** [comment]
专门给赛风用的

**Comment by TheCalling** [comment]
怎么个用法？ @jzp820927

**Comment by jzp820927** [comment]
google 搜一下就知道了，很早以前看到，记不得地址了
