### ISSUE TITLE
雨季防漏水, 请协助破墙局

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#734]
香港主字段
61.238.203.0
61.238.239.0
58.176.217.0

其他
103.233.96.0
103.24.93.0
103.30.71.0
118.143.88.0
122.152.175.0
124.248.212.0
182.239.127.0
182.239.95.0
202.40.221.0
203.135.128.0
203.210.2.0
203.210.4.0
203.78.32.0
203.78.36.0
218.189.25.0
218.253.0.0

澳门
202.86.162.0
45.64.20.0

雨季了, 请协助检查侧漏问题.

**Comment by sishentibu** [comment]
这是要扫一扫这些段？

**Comment by jasonliul** [comment]
@sishentibu 
不时会有小强, 但是跟线路有关.

只用3,4个ip的话, 始终就足够了

**Comment by jzp820927** [comment]
一个都没有，全部是香港IP段，基本上都封死了

**Comment by jasonliul** [comment]
@jzp820927 
小城市, 乡村线路其实有一些.
都会, 省会估计就一枚澳门.

**Comment by sishentibu** [comment]
@hjolin 就检测这些ip段也会闪退，go-checkip是不是还是哪里有问题？

**Comment by Kisesy** [comment]
就找到澳门一个
我还有个台湾的，64.233.189.0/24 这个很有意思

**Comment by hjolin** [comment]
@sishentibu 
我前几天又重新上传了一个版本，你再重新下载下试试
https://github.com/hjolin/go-checkip/releases/download/v1.0/go-checkip-win.zip

**Comment by darkwolf99** [comment]
请教个问题，ping不通的IP是不是不代表这个IP就不能是good IP用在gop里？

**Comment by hjolin** [comment]
ping不通的ip基本上就不能用了，gae应该不会过滤icmp包。

**Comment by sishentibu** [comment]
@hjolin 试了下这个版本，没闪退，不过又卡住了。。
http://img02.imgland.net/uH_Ef84.png

刚才试了下checkiptool，只扫出来一个

**Comment by darkwolf99** [comment]
@hjolin 多谢社长解答。刚用go-checkip-win.zip找出来的两个gws，ping了一下，都超时，这个正常吗

**Comment by cannanlly** [comment]
@sishentibu 用源代码自己编译debug就好

**Comment by sishentibu** [comment]
@cannanlly 不会。。
话说，我现在不闪退，卡住了。。

**Comment by jasonliul** [comment]
@Kisesy 
你就是伸手党三高肥胖症的罪魁祸首. :)

**Comment by Kisesy** [comment]
# 黎巴嫩
	77.42.249.0/24
	212.40.135.0/24
	# 哥斯达黎加
	186.177.66.0/24
	190.113.97.0/24
	201.191.202.0/24
	# 丹麦
	92.246.12.0/24
	# 爱尔兰
	213.233.154.0/24
	# 瑞士
	173.194.16.0/24
	193.135.3.0/24
	195.112.88.0/24
	# 摩尔多瓦
	95.65.15.0/24
	# 塞尔维亚
	79.101.110.0/24
	79.101.111.0/24
	109.245.221.0/24

**Comment by sundaqing1969** [comment]
# 黎巴嫩
77.42.249.0/24
212.40.135.0/24
# 哥斯达黎加
186.177.66.0/24
190.113.97.0/24
201.191.202.0/24
# 丹麦
92.246.12.0/24
# 爱尔兰
213.233.154.0/24
# 瑞士
173.194.16.0/24
193.135.3.0/24
195.112.88.0/24
# 摩尔多瓦
95.65.15.0/24
# 塞尔维亚
79.101.110.0/24
79.101.111.0/24
109.245.221.0/24

备忘

**Comment by jasonliul** [comment]
@Kisesy 
还来? 你是麦当劳的吧. LOL

**Comment by jasonliul** [comment]
1.9.24.0
1.9.57.0
1.179.251.0
1.179.252.0
101.100.190.0
101.96.118.0
101.99.2.0
103.21.169.0
103.233.38.0
103.28.94.0
108.177.14.0
109.88.203.0
110.50.81.0
111.94.249.0
113.171.18.0
113.171.19.0
113.171.239.0
113.171.243.0
113.171.246.0
113.171.251.0
116.212.147.0
118.174.25.0
118.69.247.0
118.69.249.0
119.15.80.0
119.40.97.0
122.154.133.0
122.154.244.0
122.154.58.0
122.154.76.0
122.2.128.0
122.2.129.0
122.2.153.0
122.255.117.0
123.205.250.0
124.248.162.0
125.234.50.0
146.88.60.0
150.101.161.0
163.28.116.0
163.28.130.0
176.222.191.0
180.93.32.0
182.50.94.0
185.5.161.0
193.134.255.0
193.135.3.0
194.78.0.0
194.78.99.0
195.176.255.0
195.46.177.0
2.127.251.0
201.157.30.0
202.122.145.0
202.124.127.0
202.169.175.0
202.69.185.0
202.78.113.0
202.90.156.0
203.113.160.0
203.113.161.0
203.121.59.0
203.133.72.0
203.133.8.0
203.146.98.0
203.162.236.0
203.211.0.0
203.211.8.0
203.217.98.0
203.66.124.0
203.66.155.0
209.85.233.0
210.242.128.0
210.245.14.0
210.61.221.0
210.94.153.0
211.117.39.0
212.73.69.0
216.58.199.0
220.255.6.0
221.133.8.0
223.27.237.0
27.123.130.0
27.123.17.0
37.152.2.0
42.112.10.0
42.112.8.0
42.112.9.0
42.119.208.0
42.119.209.0
42.119.253.0
45.118.245.0
49.231.56.0
49.231.60.0
58.71.25.0
61.219.146.0
61.91.161.0
61.91.17.0
61.91.18.0
61.91.19.0
62.4.253.0
77.42.253.0
79.101.111.0
81.88.148.0
82.148.124.0
87.245.195.0
87.245.197.0
95.57.218.0

最近摸奖记录

**Comment by hjolin** [comment]
@darkwolf99 
我不是社长。这种ip就是极不稳定的，不能用。不过也不排除某些gws服务器会过滤icmp，我对这个不太了解，你放进去试试就知道了。

**Comment by hjolin** [comment]
@Kisesy 
我去，你可真牛逼。随着goproxy的性能越来越好，大家已经可以尽情享受欧洲ip啦。

**Comment by sishentibu** [comment]
@Kisesy 你这几段搜出了百多个

**Comment by hjolin** [comment]
@sishentibu 
我搜出来288个

**Comment by jasonliul** [comment]
俺也放一段经典
91.149.162.0/24 白俄

**Comment by hjolin** [comment]
@sishentibu 
如果程序卡住了，你就直接ctrl+c退出，不会遗漏可用ip。卡住的原因是超时的ip导致tcp连接不自动断开连接，windows的默认tcp timeout是3分钟左右，我想想怎么解决这个问题。

**Comment by caofengzi** [comment]
@jasonliul 這個都是gvs的91.149.162.0/24。

**Comment by jzp820927** [comment]
版本 gvs 就比 gws 多的多，这个很正常。

**Comment by jzp820927** [comment]
太牛了，欧盟的可用 IP 挺多的，http2 以后就是核心力量了。

**Comment by drg78rgpxd** [comment]
@jzp820927 欧盟的我扫过（不是欧盟国家，是属于EU），我这里全部不可用。

64.233.178.0/24 欧盟
80.239.229.0/24 欧盟
80.239.174.0/24 欧盟

**Comment by cnrip** [comment]
回复备个底

**Comment by cnrip** [comment]
试了下,搜出来的IP,很容易出现404,

**Comment by Kisesy** [comment]
这些IP适合测试，用的话就算了

**Comment by sishentibu** [comment]
@hjolin 这个问题好像挺明显的。我出去2个多小时，回来后发现就没测几个。
试了几次都卡住了，然后也是只扫出一个

**Comment by yeahwu** [comment]
这是开仓放粮的节奏吗？
感谢，全收了！

**Comment by blob2015** [comment]
只能说你们太强大了
我的向来都是乱放一堆ip，让他们慢慢跑，能打开就行

**Comment by Lynchie** [comment]
我也来送几段，延迟比较高，扫不扫的出来看人品咯
181.49.184.0/24	哥伦比亚
208.168.228.0/24	开曼群岛
91.106.51.0/24	伊拉克
80.76.174.0/24	卡塔尔
172.217.21.0/24	美国
128.74.248.0/24 	俄罗斯
196.249.76.0/24 	非洲地区
182.79.254.0/24 	印度
194.90.196.0/24 	以色列
37.239.119.0/24 	伊拉克
95.66.10.0/24   	科威特
182.50.68.0/24  	孟加拉

**Comment by Kisesy** [comment]
不知道GFW的极限是多少，能看出来的只有在上次禁封大批量IP段的时候，解封了一些无关紧要的网站

**Comment by jasonliul** [comment]
@Kisesy 
俺不担心这个, 现在摸奖保留记录.
清明那次是摸奖太容易, 只保留最好的几段, 结果中枪

**Comment by jzp820927** [comment]
太猛了，高延时IP，真是一大片，取之不尽啊

**Comment by jasonliul** [comment]
92.226.2.0  德国
95.66.10.0 科威特
103.40.227.0 孟加拉
103.48.113.0 印度
176.222.187.0 哈萨克
189.247.147.0 墨西哥
213.145.140.0 塔吉克

试试GP表现

**Comment by jasonliul** [comment]
俄国远东字段, 少量独联体字段
108.177.14.0 

109.70.190.0 
109.110.33.0
109.163.221.0 
109.167.228.0 
109.194.105.0 
109.194.121.0
109.194.137.0 
109.194.169.0 
109.194.185.0
109.194.201.0 
109.195.9.0 
109.195.41.0 
109.195.89.0 
109.195.105.0 
109.226.232.0 

128.0.86.0  
128.0.90.0
128.74.248.0 
128.74.249.0 
128.74.251.0 

164.215.74.0

178.45.253.0 
178.45.249.0 
178.130.15.0 
178.88.163.0
178.236.130.0 

185.5.161.0 
185.13.132.0
185.34.20.0 
185.59.195.0 
185.54.255.0 

188.234.130.0
188.234.153.0 
188.244.8.0
188.43.61.0 
188.43.64.0 
188.43.65.0
188.43.66.0
188.43.68.0 
188.43.69.0 
188.35.142.0 

195.12.176.0 
195.46.107.0  
195.46.177.0
195.64.213.0 
195.72.240.0 
195.94.233.0 
195.162.39.0 

209.85.233.0

212.1.249.0 
212.1.250.0 
212.104.78.0 
212.109.17.0 
212.122.6.0 
212.122.14.0 
212.188.7.0 
212.188.10.0 
212.188.15.0
212.188.49.0 
212.20.34.0 
212.33.231.0
212.57.191.0 
212.112.124.0
212.96.83.0

213.24.121.0 
213.59.210.0 
213.59.237.0 
213.158.11.0 
213.145.140.0 
213.30.114.0 

217.116.143.0 
217.14.201.0 
217.64.139.0 

31.132.191.0
31.132.224.0 
31.210.208.0 
31.211.30.0

37.8.144.0 
37.29.1.0 
37.29.18.0 
37.44.42.0
37.60.16.0 

46.48.32.0
46.61.155.0 
46.165.2.0 

5.17.192.0 

62.78.83.0  

77.50.2.0
77.37.250.0
77.94.164.0 
77.235.7.0

78.37.100.0 

79.136.239.0 

80.64.175.0 
80.70.231.0 
80.254.96.0 

81.88.148.0
81.163.63.0 
81.177.123.0 

83.142.166.0
83.169.197.0
83.174.198.0 

84.244.62.0 

85.112.116.0 
85.112.121.0 
85.113.32.0 
85.114.182.0 
85.172.1.0

87.225.45.0 
87.245.196.0
87.245.197.0
87.245.198.0
87.245.200.0

88.87.68.0
88.204.142.0

89.221.200.0 
89.250.0.0
89.218.72.0

90.150.4.0 
90.160.195.0
90.189.105.0 

91.144.134.0 
91.144.138.0 
91.144.157.0 
91.144.165.0 
91.149.162.0
91.202.206.0 
91.204.176.0 
91.246.119.0
91.230.210.0 

92.226.2.0 S
92.244.237.0
92.246.12.0
92.126.123.0 
92.126.155.0 
92.62.75.0
92.46.70.0

93.88.163.0
93.186.108.0 
93.191.15.0 

94.137.63.0 
94.228.205.0 
94.231.112.0
94.231.129.0
94.31.189.0

95.57.218.0
95.59.126.0
95.154.114.0 
95.161.237.0 
95.189.102.0 
95.30.216.0

**Comment by Lynchie** [comment]
这么多存货，不过我发现最近IP速度普遍都降级了--

**Comment by jzp820927** [comment]
应该是出境带宽限制了吧

**Comment by jasonliul** [comment]
@Lynchie 
那是因为跳数增加, 很多陷坑路由.

以前港澳, 韩日主字段, 基本都只有3-5跳, 现在甚至高达60几跳的都有, 这是人为增加的.

**Comment by CHN008** [comment]
这两天扫到的有效IP数量会自动减少呢,这个不错

**Comment by jasonliul** [comment]
俄国ip是破墙的噩梦, 即使封杀最严那几天.
很多字段都还有零星残兵.

是时候打开潘多拉的匣子 :)

**Comment by jzp820927** [comment]
这个帖子不错，资源丰富，值得珍藏

**Comment by senninl** [comment]
@jasonliul
聽你說了，馬上用windows的 tracert -d 測試了下 的確有這個問題
發現第一個過後直接跳到國外IP（即使測試114.114.114.114也是這樣）的路由上後，在跳回到中國路由上 在慢慢的正常經過20多個路由後到達目標

**Comment by blob2015** [comment]
好路由不容易找，之前用了一些，发现打开国内网站，尤其是微博之类的封闭、半封闭的，容易出错。
感谢 @jasonliul 又发大水，连带着几位也发小水。
谢谢。

**Comment by jasonliul** [comment]
中国的互联网, 连接美国远好于欧洲.

现在破墙玩岗村宁次的"坚壁清野", 港澳韩日台星之后, 
肯定是搞死东南亚.

可以划掉的区域:
南极, 非洲, 中东, 南美
南亚, 中亚线路差+干扰, 也划掉
欧洲, 迟早.

剩下就是墨西哥, 俄国东北, 加拿大.以及官方字段拣侧漏.

怪咖们会玩临时字段, 每个字段就一个ip,需要新程序收集检测. 因为何时可用未知. 当然破墙更头大

影子区域, 其实还有中美洲, 互联网唯一IP大量富余的区域.
例如他们的ssh, 前置代理, 不少都只有200ms左右, 因为主机并不在当地. 星加坡的ping值通常都>250ms.那是最后的阵地.

**Comment by jasonliul** [comment]
@blob2015 

俺是抛砖引玉, 别光看砖头. :)

**Comment by cnshinchan** [comment]
多谢各位弹药

**Comment by lsnmx** [comment]
@Kisesy 你头像就是潮啊

**Comment by yeahwu** [comment]
人家是胖虎版“刺客信条”好吧，简直是潮得一逼……
