### ISSUE TITLE
速度不错，不过有点占内存

### ISSUE THREAD

**Issue by wzdnzd** [phuslu/goproxy#738]
![n6ydgf 1fv9 zbzb50e](https://cloud.githubusercontent.com/assets/8565764/15282521/6b0a712c-1b76-11e6-822c-f7d5e8d1ef6c.png)

![image](https://cloud.githubusercontent.com/assets/8565764/15282627/228c4690-1b77-11e6-89ca-502309cbc1a7.png)

大赞，速度不错，不过有点占内存，基本上90M以上，用XX-mini在30M左右，好评！

**Comment by playnetcn** [comment]
最新版本同时升级服务端和客户端，速度快，耗内存。

**Comment by wzdnzd** [comment]
嗯

**Comment by sundaqing1969** [comment]
怎么升级最新服务端

**Comment by wzdnzd** [comment]
https://github.com/phuslu/goproxy/archive/server.gae.zip  重新部署一下

**Comment by sundaqing1969** [comment]
谢谢

**Comment by wzdnzd** [comment]
太客气，应该谢大大才对

**Comment by xiangcoolk** [comment]
小白求问：本来一直在用goagent3.2.3，用同一组appid上goa和gp都可以。现将appid上传gp，发现不能用goa了，现在想用回goagent，如何处理？

**Comment by sundaqing1969** [comment]
用goagent3.2.3自带的部署程序重新上传，应该可以

**Comment by xiangcoolk** [comment]
无论是新申请appid还是用旧的上传，都是以下画面。
===============================================================
 GoAgent服务端部署程序, 开始上传 gae 应用文件夹
 Linux/Mac 用户, 请使用 python uploader.py 来上传应用
===============================================================

请输入您的appid, 多个appid请用|号隔开
注意：appid 请勿包含 ios/android/mobile 等字样，否则可能被某些网站识别成移动设备
。
APPID:xxx
Application: xxx
Host: appengine.google.com
Rolling back the update.
Email: xxx@gmail.com
Password for xxx@gmail.com: ********
Error 404: --- begin server output ---
https://developers.google.com/accounts/docs/AuthForInstalledApps
--- end server output ---
请按任意键继续. . .

**Comment by wzdnzd** [comment]
@xiangcoolk 用XX-net吧  貌似google app engine sdk改了 goagent部署不了了，反正之前我从goa换成gop又换回去时怎么都部署不成功  后来就用xx-net部署  现在我有5个appid是go服务端，5个是python，gop为主，xx-mini助攻

**Comment by xiangcoolk** [comment]
@sundaqing1969 @wzdnzd 明白了，多谢二位解答。

**Comment by xiangcoolk** [comment]
@sundaqing1969 @wzdnzd 明白了，多谢二位解答。各位手头还有goa可用的要珍惜啊。

**Comment by xiangcoolk** [comment]
@sundaqing1969 @wzdnzd 明白了，多谢二位解答。各位手头还有goa可用的要珍惜啊。

**Comment by xiangcoolk** [comment]
@sundaqing1969 @wzdnzd 明白了，多谢二位解答。各位手头还有goa可用的要珍惜啊。

**Comment by sundaqing1969** [comment]
可以这样尝试，先把其它翻墙程序都关闭，只开goproxy，然后重新上传，类似故障我是这样排除的

**Comment by wzdnzd** [comment]
@xiangcoolk 其实gop真的很不错，只是还存在一点点瑕疵需要等社长慢慢修复

**Comment by wzdnzd** [comment]
@sundaqing1969 他是要从gop换回goa，用xx-net部署一下就好

**Comment by sundaqing1969** [comment]
不好意思，我亲自试了一下，用goagent重新部署服务端果然不行

**Comment by sundaqing1969** [comment]
https://github.com/phuslu/goproxy/archive/server.gae.zip 这个不可以部署goagent的服务端吗？

**Comment by wzdnzd** [comment]
用这个部署以后，服务端是go，在goa上也能用，但是容易出问题，像gmail什么的都上不了，Unsupported Media Type  我之前老是出这个问题，最后又去申请了5个appid，把服务端换成python，之后又能愉快地玩耍了

**Comment by sundaqing1969** [comment]
xx-net里的服务端部署程序闪退，无法完成部署

**Comment by wzdnzd** [comment]
你下载的是哪个版本，好像说3.16部署存在问题，3.17修复了，你可以多试几次，或者试试靠前一点的版本。还有，你是在web-ui里部署还是在cmd里？web-ui里方便些

**Comment by sundaqing1969** [comment]
3.1.17版

**Comment by wzdnzd** [comment]
xx-net的变更日志里是这么写的
![image](https://cloud.githubusercontent.com/assets/8565764/15293570/30915732-1bbb-11e6-98a7-ffd28ff4b0f2.png)
你可以去那边的issues里看看情况

**Comment by xiangcoolk** [comment]
这个跟gop服务器端里的upload一样。能用gop，goa还是不行。

**Comment by sundaqing1969** [comment]
谢谢，在web-ui里部署成功了

**Comment by xiangcoolk** [comment]
我部署gop就是用这个，部署完就用不了goa。
------------------------
https://github.com/phuslu/goproxy/archive/server.gae.zip 这个不可以部署goagent的服务端吗？
试了一下上面的部署程序重新可以为goagent部署服务端，xx-mini的核心程序就是goagent的核心

**Comment by sundaqing1969** [comment]
![default](https://cloud.githubusercontent.com/assets/13601611/15293725/ee683046-1bbb-11e6-95b6-56273264409c.PNG)

**Comment by xiangcoolk** [comment]
![image](https://cloud.githubusercontent.com/assets/19389760/15298227/dc5a60da-1bd0-11e6-8f16-2993e1cf7577.png)

**Comment by jzp820927** [comment]
XXNET部署的服务端应该是兼容 goa 的

**Comment by sundaqing1969** [comment]
我这里兼容

**Comment by darkwolf99** [comment]
我这里部署的gop，goa也还能用，昨天刚上传过一遍

**Comment by hcym** [comment]
新版内存小多了

基本100上下，毛毛雨

老版是大一点，300－600不等

**Comment by jasonliul** [comment]
![gp](https://cloud.githubusercontent.com/assets/2461165/15314468/8e3ce1c4-1c44-11e6-8fd9-426be86affbb.png)

不知道你们怎么测试的, 
新版GP最初是60M, 现在基本没变

**Comment by kang000feng** [comment]
@xiangcoolk  你好兄台，我在用goagent3.2.3版的服务端和客户端，看你上面写道“用同一组appid上goa和gp都可以”，我的那组appid也可以用goproxy客户端连接吗？这样会增加破墙能力还速度更快？求解惑？谢谢！

**Comment by jzp820927** [comment]
服务端通用的，可以
