### ISSUE TITLE
App Engine support SSL (HTTPS)?

### ISSUE THREAD

**Issue by okgoogle** [phuslu/goproxy#743]
不久前才从goagent转到goproxy的，速度有提升，感谢社长。
goagent使用了几年了，只记得初始使用时，goagent的作者说因为google app engine不支持SSL，所以只好伪造证书使其支持SSL。

而这天登陆了google账号随意翻了一些帮助页面，发现了这个页面：
https://cloud.google.com/appengine/kb/#https
页面中说App Engine 支持 SSL (Java | Python | Go)。

那么为什么现在的goproxy还是伪造证书呢？
究竟是什么时候支持SSL的我并不清楚，我说了是这次随意翻到的这个资料了。
请懂行的朋友解释一下，或许以后不需伪造证书？还是一切照旧呢？

**Comment by hcym** [comment]
一切照旧

**Comment by jzp820927** [comment]
好像是2个意思吧，你说的 App Engine support SSL，是说的 GAE 支持 https 协议访问，但是代理 https 流量，和这个不是一回事

**Comment by okgoogle** [comment]
@jzp820927 点进去后有这句话：The development web server does not support HTTPS connections.
或许你说的是对的。

**Comment by jzp820927** [comment]
但是 付费的 google cloud 是支持 透明代理 https 的吧，不知道你看到是不是付费版本说明，免费的确实不支持

**Comment by phuslu** [comment]
呃，
> goagent的作者说因为google app engine不支持SSL

我就 goagent 作者，开了新坑 goproxy, 所以总得有点长进吧，比如速度啥的。

但是原生 SSL 转发，的确做不到。GAE 目前和可以预见的将来，应该都不支持的。

**Comment by linhua55** [comment]
可参考 https://github.com/XX-net/XX-Net/issues/1977#issuecomment-174481434
付费(绑定信用卡)GAE支持Sockets, 但有局限性
1. 不能监听, 只能用x_tunnel的方法, 把TCP流量封装成http请求包,
2. 不能访问Google IP.  因此Google的服务只能用原来的方法(直接访问,或通过GAE http转发,两者都需要导入证书)访问 
这里有两个未知的问题:
1. 不知道付费GAE如果没超过免费的限额,会不会扣费
2. 不知道Google IP是否包含GCC IP.

**Comment by phuslu** [comment]
说实话，我不看好 TLS over TLS 这种方案。
易被识别和干扰 http://weibo.com/p/1001603945665913854240

我如果做 vps 版本的话，计划采用 TLS over encrypted h2c 的方案。

**Comment by okgoogle** [comment]
@phuslu 不好意思，对社长失礼了。以前不怎么逛讨论区所以我甚至不知道作者是谁。
多谢楼上各位讨论，我对这个问题就像是小白那样，没法参与讨论。
如果能长久使用，上一些不敏感的网站，或只是用google查资料或看一些视频，就可以了~

**Comment by yeahwu** [comment]
哈哈，都是老熟人，原来大坑在这里呀！
期待社长的vps版本，呃，俺还得去整个vps
