### ISSUE TITLE
社长可能又要改进连接握手方式，ip几十秒就变bad ip

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#745]
用203.233.0.0这段优质韩国ip，已经在mff里测试了100次成功
注意，是100次都成功！没有1次丢包！
结果一上goproxy，几十秒内就变bad ip，GoGoTester已经NN了

**Comment by hcym** [comment]
我这里不是

这段高峰时不通，夜里都ok，非常ok

快一个月了一直这样，怀疑是电信问题

有政企网的可以验证一下

**Comment by caofengzi** [comment]
俺這裡也沒有這樣的情況。

**Comment by jzp820927** [comment]
是不是 TTL 问题

**Comment by blob2015** [comment]
可能别人也在用这个段？
感觉最近没有特别快的失效。俺也是电信的。

**Comment by drg78rgpxd** [comment]
@jzp820927 跳数正常 15-18跳 延时正常 不超过200ms

**Comment by hcym** [comment]
这段ip白天根本不通，据说政企网不受影响

夜里一旦通，也就30－70ms之间，清晨几乎20ms不到

**Comment by minorisprit** [comment]
曾经的告诉IP在非视频环境下依旧是高速的，用GP代理github的下载基本都是秒下，目前最大的问题就是视频，每个IP仅能以高速状态存活不到5S，实在是很蛋痛这次墙的升级

**Comment by jzp820927** [comment]
也就是说，这是专门针对 y2b 的封杀？

**Comment by minorisprit** [comment]
应该是的，之前我发过一个疑问贴，大神回答了这个问题，找IP的成本增加了，等于封杀

**Comment by phuslu** [comment]
没有太好的办法，试下打开 gae.json
```
"DisableKeepAlives": true
```
