### ISSUE TITLE
算了，自己

### ISSUE THREAD

**Issue by jzmswe** [phuslu/goproxy#746]
和谐

**Comment by hcym** [comment]
习大大只怕被人取而代之，不怕什么恐怖分子

你是五毛吧，要不就是轮子

**Comment by jzmswe** [comment]
“王某峰多次非法登录境外网站，观看并下载割头、ISIS打仗场面等涉暴恐音视频。”属于违反《反恐法》第八十条第二款“制作、传播、非法持有宣扬恐怖主义、极端主义的物品”的行为。按照本法本条规定：参与该类活动情节轻微，尚不构成犯罪的，由公安机关处十日以上十五日以下拘留，可以并处一万元以下罚款。
——————————————————————————————————————————
只要不传播、下载，就没问题。

**Comment by phuslu** [comment]
不要乱下断言。issue 目前有封人锁帖的功能，遇到真正来捣乱五毛我会留意的。
