### ISSUE TITLE
奇怪的错误提示

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#757]
"software": "Google App Engine/1.9.37",
    "error": "API error 8 (urlfetch: CLOSED)"

**Comment by caofengzi** [comment]
上這裡可能找到答案。https://cloud.google.com/appengine/downloads#Google_App_Engine_SDK_for_Python

**Comment by Kisesy** [comment]
Go 的服务端偶尔会出，有时还会出 `EOF`，还会出 超配额，Py 端没这些问题

**Comment by jasonliul** [comment]
@Kisesy 
看来是谷歌抽风

**Comment by phuslu** [comment]
go 的服务端逻辑是“快速出错”，所以不会像 py 在服务端重试。

这样的好处是可以分辨干扰和超时，不会出现假死的情况，尤其在 http2 的时候是非常必要的。

但带来了额外的工作，就是要在客户端加上那个重试逻辑，比如捕捉顶楼的这个错误然后重试。
接下来会继续这个工作。

**Comment by phuslu** [comment]
更新： r591 捕捉了这个错误并重试了 https://github.com/phuslu/goproxy/commit/0786f413772540f1c444d596140201ba48776357

**Comment by jasonliul** [comment]
哈哈, 终于找到bug折腾社长一番了.

**Comment by hcym** [comment]
老大辛苦了
