### ISSUE TITLE
为什么有些https无法正常打开

### ISSUE THREAD

**Issue by yangchangyz** [phuslu/goproxy#760]
@phuslu 为什么有些https无法正常打开，我把这个网址抓stripssl.json的sites里面，stripssl默认开启但是无效啊，请问社长该怎么做？

**Comment by phuslu** [comment]
贴网址吧

**Comment by yangchangyz** [comment]
我把这个网址抓stripssl.json的sites里面,但无效

**Comment by phuslu** [comment]
什么网址？
