### ISSUE TITLE
twitter的选项、主页点击后没有反应

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#761]
twitter的设定、选项主页、都无法点解，能显示焦点，但点击后没有反应。

goproxyr590、r572都出现这个问题 配置一切正常 浏览器是chrome 40

例：点击回复没有反应
![360 20160521191746746](https://cloud.githubusercontent.com/assets/15207080/15448083/11c069c0-1f89-11e6-9206-a68b5e03c3e5.png)

**Comment by hcym** [comment]
每天都推一下油，没问题

不过我是只看，不推不转推啥的

设定、选项、退出都可以

**Comment by phuslu** [comment]
未能重现，应该是个案。
