### ISSUE TITLE
books.google.com 520

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#767]
可以进入首页，可以搜索，可以看到搜索结果，但是点击搜索结果，就会出现下面的提示

**502. That’s an error.
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds. That’s all we know.**

---------------

> 发现点击搜索结果的时候，从books.google.com变成了books.google.cn，然后就出现这问题了，手动改为com【darkwolf的是hk，好像也可以】，就可以看到结果了，是否开启全局，没有用。

> **刚才在ie11**【没有任何插件，基本上都禁用了】**复现：**不登录帐号，就会跳转到com.hk，登陆后，就会跳转到cn【大概老是跳出来验证码，也跟这个有关？因为对方记录了ip？】

> 把之前加的伪军ip【cn地方一直用的是伪军ip】改成hk的ip，就可以打开了，不过网页也转成了com.hk
但是com.hk的内容，似乎不如com的，related books里面，好像hk经常没有？

**Comment by caofengzi** [comment]
的確有這個問題。

**Comment by johnsonz** [comment]
我这没问题

**Comment by blob2015** [comment]
@johnsonz 
老兄那个版本？
忘记说版本了，俺这个是609

**Comment by johnsonz** [comment]
win 10 x64
goproxy r569

**Comment by darkwolf99** [comment]
我这里ok，r609 64位版
win10 x64

难道和good IP有关？

![default](https://cloud.githubusercontent.com/assets/19298093/15466907/5b8dba9a-210e-11e6-818f-d21a8456875b.PNG)

**Comment by blob2015** [comment]
@phuslu @johnsonz @darkwolf99 
发现点击搜索结果的时候，从books.google.com变成了books.google.cn，然后就出现这问题了，手动改为com，就可以看到结果了，是否开启全局，没有用。

**Comment by phuslu** [comment]
不能重现，怀疑是其他问题（比如某个 chrome 插件）引起的。

**Comment by blob2015** [comment]
@phushu 
谢谢关注 :grinning: 
Win7 32，FF 35，**有登陆帐号**
刚才在ie11【没有任何插件，基本上都禁用了】复现：不登录帐号，就会跳转到com.hk，登陆后，就会跳转到cn【大概老是跳出来验证码，也跟这个有关？因为对方记录了ip？】

**Comment by jzp820927** [comment]
https://www.google.com/ncr

**Comment by blob2015** [comment]
@jzp820927 
这个都没有问题，是books的cn域名的问题

**Comment by blob2015** [comment]
@phuslu 
把之前加的伪军ip改成hk的ip，就可以打开了，不过网页也转成了com.hk
但是com.hk的内容，似乎不如com的，related books里面，好像hk经常没有？

**Comment by yoker** [comment]
这个问题我这里也是存在的，重现很困难，昨天同样的情况出现过多次，但是刷新一下，基本就正常了。看日志，也没看出所以然来。

**Comment by blob2015** [comment]
@phuslu @yoker 
让google_cn保持原貌，就没有问题了，如果填入ip，然后ip又……就会这样
#687 
此问题搞定
再次感谢 @Kisesy
