### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by cannanlly** [phuslu/goproxy#770]
打开这个地址出现乱码 http://www.serv-u.com/   使用的 r609

**Comment by Kisesy** [comment]
这个应该和百度百科一个毛病，不知道是不是跟蛋疼的deflate有关

**Comment by jasonliul** [comment]
不能重现.

**Comment by Kisesy** [comment]
需要全局代理才能重现

**Comment by phuslu** [comment]
多谢 @Kisesy 提供的线索，r611 已修复。

**Comment by phuslu** [comment]
多谢 @Kisesy 提供线索，r612 已经修复。
