### ISSUE TITLE
google搜索跳出来这个，是为啥？

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#772]
概率较低，是长久不用之后？还是？未知。先在这里挂个号，仅供 @phuslu 等参考

---------------

This page cannot be loaded using Chrome Data Saver. Try reloading the page.
Debug info: GET CK-F1P-B8swCFWTkddAdkwQOSg==

没有红，没有黄，F5无效，关闭gp，重新打开，继续正常了

**Comment by xc1988** [comment]
上次好像解释过了

**Comment by jzp820927** [comment]
IP问题，你这个是无效IP

**Comment by blob2015** [comment]
这样啊，谢了
@xc1988 @jzp820927

**Comment by xc1988** [comment]
[https://github.com/phuslu/goproxy/issues/486](url)

**Comment by xc1988** [comment]
#486 我以前问过

**Comment by blob2015** [comment]
@xc1988 
谢谢
