### ISSUE TITLE
这个地址打开后无任何显示，难道是因为gfe的原因？

### ISSUE THREAD

**Issue by cannanlly** [phuslu/goproxy#773]
http://bbs.pcbeta.com/viewthread-1692587-1-1.html
使用的r614

**Comment by jzp820927** [comment]
怎么都喜欢用代理访问国内网站呢？就不怕 gFW 劫持为 大炮攻击者

**Comment by phuslu** [comment]
调试了一下，pcbeta 应该封锁了 GAE 的访问。
