### ISSUE TITLE
［废弃］which fixes mac? OX系统要下载呢个？

### ISSUE THREAD

**Issue by Lewous** [phuslu/goproxy#78]
Linux的吗？Linux的三个有什么区别？谢谢

**Comment by xyuanmu** [comment]
下载 goproxy_darwin_amd64 那个。至于Linux不同版本应该是对应不同处理器吧，猜的。

**Comment by johnsonz** [comment]
应该是不同的处理器架构

**Comment by Lewous** [comment]
随后后来直接用了shadowsocks，，总之谢谢应答
