### ISSUE TITLE
培正学院的反向代理失效了？（已经恢复服务了）

### ISSUE THREAD

**Issue by sundaqing1969** [phuslu/goproxy#784]
能够ping通，但是不能用了     211.66.248.136-139

**Comment by hcym** [comment]
那就不用呗

**Comment by sundaqing1969** [comment]
一直稳定，速度也比较快，失效了可惜

**Comment by jzp820927** [comment]
速度很快么？我记得谁说过速度不怎么样

**Comment by sundaqing1969** [comment]
测速500kbt左右

**Comment by jzp820927** [comment]
500 kb，是 youtube 右键，详细信息，那个测速显示的速度？

**Comment by drg78rnvgh** [comment]
@sundaqing1969 教育网肯定不止培正学院的ip。
应该把全cn的几亿ip扫描一遍。是教育网的就可用

**Comment by sundaqing1969** [comment]
youtube测速高峰有3000kbt，一般可以稳定在1000kbt多 @jzp820927

**Comment by jzp820927** [comment]
如果是 y2b 自己测试有 1000多kb，720P应该没问题，我就说，y2b 显示的 500多kb 肯定看不了720

**Comment by hcym** [comment]
境内的还是不靠谱，毕竟乌纱帽比自由重要

香港澳门极少，韩日的多些

**Comment by LGA1150** [comment]
你们这样一声不吭跑别人流量真的好吗？

**Comment by jzp820927** [comment]
我也建议，国内IP，是属于很珍惜的资源，还是不要跑大流量的好，其实现在可用IP也蛮多的，没必要用国内IP

**Comment by sundaqing1969** [comment]
没有这么跑那个反向代理，培正学院的这几台服务器在其它论坛早就公布好久了

**Comment by sundaqing1969** [comment]
这几台服务器恢复服务了

**Comment by jzp820927** [comment]
看来是服务器 在维护，短暂失效
