### ISSUE TITLE
在edge浏览器上使用pac代理时谷歌搜索打不开，其他都能用，请问有没人也遇到这种情况

### ISSUE THREAD

**Issue by wzdnzd** [phuslu/goproxy#785]
好奇怪，只有域名带google的都不能访问，比如google scholar等，其他都能
y2b:
![2016-05-27_090528](https://cloud.githubusercontent.com/assets/8565764/15594722/e2ed983c-23ea-11e6-838b-24486515794d.png)
google hk:
![2016-05-27_090615](https://cloud.githubusercontent.com/assets/8565764/15594723/e2ee0416-23ea-11e6-9c54-290584a11dc4.png)

在控制台看了一下，访问google.hk时都没有代理请求。。。顺便说一下，chrome上用的插件，一切正常，怀疑是不是pac的问题

**Comment by jzp820927** [comment]
应该是 pac 没有 google 域名的规则吧，你打开 pac 看看就知道了

**Comment by wzdnzd** [comment]
之前是直接打开127.0.0.1：8087/proxy.pac查看，刚才打开了本地的pac文件才发现以前我修改过pac，现在好了，谢谢咯
