### ISSUE TITLE
gae url fetch 限制一分钟22mb，都不知道怎么吐槽好了，收费的还限制740 MB/minute

### ISSUE THREAD

**Issue by cannanlly** [phuslu/goproxy#787]
20秒就达到限制值了，蛋疼啊。可惜了google钱包居然不让中国大陆用，FxxK

**Comment by hcym** [comment]
脑子有问题

百度可以治病

**Comment by jzp820927** [comment]
有什么影响麽?

**Comment by cannanlly** [comment]
影响就是下片很慢啊

**Comment by jzp820927** [comment]
我看好多人用 gae 测试 youtube 都是 2，3万kb，应该不会受这个影响吧，不然能到这么高速度

**Comment by linhua55** [comment]
那就多部署几个APPID

**Comment by jzp820927** [comment]
难道这是受到 autorange 的影响，下载也应该可以支持 autorange 吧

**Comment by cannanlly** [comment]
@phuslu  社长大大，goproxy好像在一个appid的每分钟url fetch满22mb后没有去切换其他appid，还是说google限制了一个google账号每分钟url fetch是22mb？

**Comment by phuslu** [comment]
多放些 appid 试试。

goproxy 对于静态资源，如视频，图片，js，css 等都会随机化选取 appid，所以appid越多，免费限额的影响越小。

推荐5个以上，用 goproxy 的 go 服务端的效率还会更好些。

**Comment by boycc1974** [comment]
以前一直用4个appid,听社长的建议又申请了8个，现在12个感觉效果提升了，晚上看YouTube都不卡了，就2个ip

**Comment by cannanlly** [comment]
appid 我放的10个，只是想知道谁有没有什么好的思路方法能让它传输比如大于10mb文件的时候去使用多个appid多线程分段传输，学习p2p思想

**Comment by baoziwan** [comment]
建议通过购买VPS，自建Shadowsocks解决。
不觉得限额有什么问题，本来就是免费薅谷歌的羊毛，谷歌为了避免滥用也应该限额。
