### ISSUE TITLE
https cert

### ISSUE THREAD

**Issue by seventhking** [phuslu/goproxy#789]
hi, i found a cert in root dir, but when i add it to chrome, it show me the cert lose private key. how should i do if i want to visit google?

**Comment by HF-Enigma** [comment]
you don't have to add the cert files manually for chrome, it will be added automatically when you run it as aministrator

**Comment by blob2015** [comment]
wow, a king? :grinning:

**Comment by cannanlly** [comment]
same issue here,win7 has this issue but win10 works well
