### ISSUE TITLE
请使用客户端和GAE之间使用的是哪种安全协议？

### ISSUE THREAD

**Issue by johnsonz** [phuslu/goproxy#79]
请问GOP用的哪种安全协议？还是之前的SSL吗？要是TLS的话，之前搜到的IP放到GOP还能用吗？

**Comment by xyuanmu** [comment]
协议我不知道，但是ip通用

**Comment by thundery1** [comment]
我都没用自己的id,我很奇怪咋翻墙的..

**Comment by SunJiaGG** [comment]
查看goagent  3.2.3配置文件，有这么一行
sslversion = TLSv1
所以，，，，，，

**Comment by johnsonz** [comment]
之前的版本中有用到openssl，不过现在移除了。应该用的是go TLS协议。
