### ISSUE TITLE
希望出个更新日志

### ISSUE THREAD

**Issue by aoscn** [phuslu/goproxy#791]
记得以前用goagent的时候，每次更新都会有个更新日志，让用户知道到底更新了什么
现在goproxy更新很频繁，每次都不知道更新了什么，关键是在用户体验上没感觉有大的区别

**Comment by cannanlly** [comment]
直接看commit的东西不就知道改了啥了

**Comment by darkwolf99** [comment]
https://github.com/phuslu/goproxy-ci/releases

这里有

**Comment by blob2015** [comment]
都有啊，即便是服务端，其实也能看到，就是没有客户端那么直接罢了
