### ISSUE TITLE
还是不明白php代理如何设置

### ISSUE THREAD

**Issue by MkAnaio** [phuslu/goproxy#794]
请问GP可以用php代理吗，看了FAQ之后，按照其中的设置，并无效果。
我只是把index.php那几个文件上传到了根目录。
客户端用的是636，只是把配置中的php.json中servers中url和password替换，并且删除了gae.json中的IP。
然后就没有效果了。
请问具体如何设置呢。

**Comment by hcym** [comment]
httpproxy.json

也要配置下，其它没有了

**Comment by jzp820927** [comment]
httpproxy.json 中开启 PHP 代理，默认是关闭的

"PHP": {
                "Enabled": true,

**Comment by blob2015** [comment]
这些天，好像都在搞vps，php的好像最近动静少些

**Comment by Asteroids89** [comment]
同问，坛子里的这些大神如何设置？

**Comment by jzp820927** [comment]
php.json 中添加 PHP 地址，
httpproxy.json 中开启 PHP 
就可以了

**Comment by MkAnaio** [comment]
非常感谢，已经测试成功。
但是部署在heroku上面的。
请问，如何在vps上部署呢，我把goproxy-server.php中的三个文件拖入到vps php根目录，
可是打开后无效果，一直提示500错误。
@jzp820927 @hcym
