### ISSUE TITLE
用广东移动服务器中转，速度杠杠

### ISSUE THREAD

**Issue by LGA1150** [phuslu/goproxy#799]
只要这样修改gae.json就行了  
```
"google_hk": [
	"120.198.243.3",
	"120.198.243.14",
	"120.198.243.15",
	"120.198.243.34",
	"120.198.243.35",
	"120.198.243.48",
	"120.198.243.50",
	"120.198.243.51",
	"120.198.243.52",
	"120.198.243.53",
	"120.198.243.54",
	"120.198.243.82",
	"120.198.243.86",
	"120.198.243.113",
	"120.198.243.114",
	"120.198.243.115",
	"120.198.243.116",
	"120.198.243.118",
	"120.198.243.130",
	"120.198.243.151"
],
```

```
"FakeServerNames": [
	"li-in-f81.1e100.net",
	"li-in-f82.1e100.net",
	"li-in-f83.1e100.net",
	"li-in-f84.1e100.net"
],
```
更新：如果找不到FakeServerNames就修改ServerName字段

**Comment by hcym** [comment]
能用

不知其它类推行不行，不然带宽太小了

**Comment by drg78rnvgh** [comment]
这几个ip是不是国内的临时字段，透明代理？

**Comment by phuslu** [comment]
原来移动还有能过墙的 sni 代理，楼主有心了，👍👍👍

**Comment by hcym** [comment]
靠山吃山吧

中南海还直通白宫了，电信也有草榴的镜像

**Comment by drg78rnvgh** [comment]
是不是直连这个ip？172.217.25.81
http://172.217.25.81.ipaddress.com/

IP Lookup Result for 172.217.25.81
IP Address:	172.217.25.81
Host of this IP:	nrt13s50-in-f17.1e100.net
Organization:	Google
ISP/Hosting:	Google
Updated:	05/25/2016 01:17 AM
City:	Mountain View
Country:	United States 
State:	California
Postal Code:	94043
Timezone:	America/Los_Angeles
Local Time:	05/30/2016 07:48 AM
 Top of the Page

**Comment by cnshinchan** [comment]
不能用是那里出问题呢
W0530 23:00:22.843750    3604 multidialer.go:251] MULTIDIALER DialTLS2("tcp", "c
lients3.google.com:443") with good_addrs=5, bad_addrs=0

浏览器显示
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>Ref A: 1A39645A4E214591836DD61F28FFE120 Ref B: E11A265D6877A2F3C864FBDB9132C253 Ref C: Mon May 30 07:57:22 2016 PST

**Comment by blob2015** [comment]
@LGA1150 
老兄不时带来好东西 :grinning: 
不过俺看看就好 :grinning:

**Comment by LGA1150** [comment]
@cnshinchan 
FakeServerNames里只能留我给的4个

**Comment by Kisesy** [comment]
这个是真心厉害

**Comment by yeahwu** [comment]
就适合像俺这样的懒人，感谢楼主

**Comment by hotbbs** [comment]
尝试了一下，不能用啊，打开网站，地址后加了/_gh/

**Comment by yeahwu** [comment]
然后俺想问一下社长，新版生成的证书文件，怎么都跑到goproxy文件夹外面去了？

**Comment by phuslu** [comment]
啊，是 windows 还是 linux ? 应该和 r649 https://github.com/phuslu/goproxy/commit/66178d8483f0905f5b382dd45222a667ae927ee1 这个改动有关。

**Comment by yeahwu** [comment]
linux amd64

**Comment by phuslu** [comment]
我看下，估计是在目录外运行 goproxy 引起的。我看下。

**Comment by erichau** [comment]
能用，电信居然速度还不错

**Comment by sypopo** [comment]
速度真不错！

**Comment by phuslu** [comment]
@yeahwu r656 给 stripssl.json 添加了一个 portable 参数，控制证书生成的位置是否和 goproxy 所在文件夹保持一致。

**Comment by yeahwu** [comment]
656版正常了，只是会在goproxy文件夹外多一个空Cache文件夹，使用正常

**Comment by blob2015** [comment]
@phuslu 
额外插一句，社长，改一下图标？如果一时间要找到一个喜欢的，估计也难，可以先改一下图标的颜色？比如蓝色改成“青色？”【青出于蓝？】，或者把蓝色与黄色都换了，红与黑？ :grinning: 或者？
主要是估计很多人还是留着GA备用，有时候感觉容易混淆 :grinning:

**Comment by phuslu** [comment]
@yeahwu r657 把 Cache 空文件夹也干掉了
@blob2015 暂时没有换的打算，这个图标我挺中意的。目前还没发现更美观的。

**Comment by drg78rnvgh** [comment]
@phuslu 就换成go语言的图标吧
也符合现在萌的潮流

**Comment by yeahwu** [comment]
@phuslu 社长真迅速！图标嘛，看俺图像中意啵？要不考虑一下换成俺头像

**Comment by blob2015** [comment]
@phuslu 
说实话，这个图标还是有点韵味的。
联通网络，还有太极的感觉【纯瞎联想】，蓝色与黄色，也不错。就是跟GA的一模一样啊 :grinning: 
不过如果社长觉得还是继续，那就继续跟GA一起，“安能辨我是雄雌” :grinning:

**Comment by yeahwu** [comment]
不要在意这些细节，图标嘛，随便搞一个嘛，多大的事！

**Comment by blob2015** [comment]
@yeahwu 
社长这种人啊，对有些东西，向来不随便的 :grinning:

**Comment by phuslu** [comment]
@blob2015 取笑了。

有时候我有点审美强迫症，一个东西反复改来改去，可惜受限于自身的品味，最后还是不甚满意。
拿项目首页来说吧，这几天改了 N 次，最后才这样，勉勉强强吧。

**Comment by panpeach** [comment]
能用，速度还可以，不知道能用多久，管他去用一天是一天。

**Comment by blob2015** [comment]
@phuslu 
已经不错了。没有点强迫症，怎么做出好东西，没有强迫症的，大多是纯粹的流水线工人，或者站街的，他们只会说，快快快 :grinning:

**Comment by yeahwu** [comment]
@phuslu xx-net的首页差不多也被俺改了10遍了，最后改得面目全非，也是轻微强迫症的节奏哇
https://github.com/XX-net/XX-Net

**Comment by playnetcn** [comment]
@LGA1150感谢您发的内容，我觉得还是删除了吧，用的人多了就废了。

**Comment by blob2015** [comment]
@playnetcn @LGA1150 
这么说啊，有点以XX之心度lga之腹了
估计这是抛砖引玉罢了 :grinning: 
真要一个人独自爽，买个vps什么的，估计就成了 :grinning:

**Comment by darkwolf99** [comment]
这个电信的用不了吧

**Comment by jzp820927** [comment]
目测要被挤爆的节奏，还说不凑热烈了。

**Comment by sundaqing1969** [comment]
只要这样修改gae.json就行了

"google_hk": [
    "120.198.243.50",
    "120.198.243.51",
    "120.198.243.52",
    "120.198.243.53",
    "120.198.243.54",
    "120.198.243.82"
],
"FakeServerNames": [
    "nrt13s50-in-f17.1e100.net",
    "nrt13s51-in-f17.1e100.net",
    "nrt12s11-in-f17.1e100.net",
    "nrt12s12-in-f17.1e100.net",
    "nrt12s13-in-f17.1e100.net",
    "nrt12s14-in-f17.1e100.net"
],

**Comment by missmuxixi** [comment]
显示"405 Not Allowed"

**Comment by jzp820927** [comment]
@FakeServerNames里只能留给的6个

**Comment by missmuxixi** [comment]
@jzp820927 原配置文件里面并没有找到FakeServerNames 直接添加了一段

**Comment by sypopo** [comment]
@missmuxixi 改ServerName

**Comment by wdyxian** [comment]
这些IP怎样弄到？速度确实OK,

**Comment by jzp820927** [comment]
这还用问麽，肯定是强扫出来的撒

**Comment by jzp820927** [comment]
估计用不了多久，就会和蓝灯一样了。想用的，得抓紧时间了。

**Comment by cnrip** [comment]
广东电信用不了.

**Comment by hcym** [comment]
就这几个ip肯定架不住群狼啊

只有找出其他国内的才有实际意义

最近网络不错，汉堡伦敦和美国东岸都可以

ping值100-200

就是出口带宽头大

**Comment by jzp820927** [comment]
带宽才是关键，ping 值都啥意义。

**Comment by github-xx** [comment]
I0531 11:59:59.262380   19376 gae.go:255] GAE EnableDeadProbe "GET https://clients3.google.com/generate_204" error: Wrong certificate of 120.198.243.52:443: Issuer={[US] [Microsoft Corporation] [Microsoft IT] [Redmond] [Washington] [] []  Microsoft IT SSL SHA2 [{2.5.4.6 US} {2.5.4.8 Washington} {2.5.4.7 Redmond} {2.5.4.10 Microsoft Corporation} {2.5.4.11 Microsoft IT} {2.5.4.3 Microsoft IT SSL SHA2}] []}, AuthorityKeyId=[]byte{0x51, 0xaf, 0x24, 0x26, 0x9c, 0xf4, 0x68, 0x22, 0x57, 0x80, 0x26, 0x2b, 0x3b, 0x46, 0x62, 0x15, 0x7b, 0x1e, 0xcc, 0xa5}
W0531 12:00:06.265046   19376 multidialer.go:253] MULTIDIALER DialTLS2("tcp", "clients3.google.com:443") with good_addrs=6, bad_addrs=3
I0531 12:00:06.660689   19376 gae.go:255] GAE EnableDeadProbe "GET https://clients3.google.com/generate_204" error: Wrong certificate of 120.198.243.82:443: Issuer={[US] [Microsoft Corporation] [Microsoft IT] [Redmond] [Washington] [] []  Microsoft IT SSL SHA2 [{2.5.4.6 US} {2.5.4.8 Washington} {2.5.4.7 Redmond} {2.5.4.10 Microsoft Corporation} {2.5.4.11 Microsoft IT} {2.5.4.3 Microsoft IT SSL SHA2}] []}, AuthorityKeyId=[]byte{0x51, 0xaf, 0x24, 0x26, 0x9c, 0xf4, 0x68, 0x22, 0x57, 0x80, 0x26, 0x2b, 0x3b, 0x46, 0x62, 0x15, 0x7b, 0x1e, 0xcc, 0xa5}
提供证书问题吧？不能用。

**Comment by LGA1150** [comment]
@github-xx @cnrip 
看楼上，FakeServerNames字段只能留我给的6个，如果找不到就修改ServerNames字段

**Comment by jasonliul** [comment]
@LGA1150 
僧多粥少, 死翘翘. :)

**Comment by jzp820927** [comment]
其实我是来围观的。

**Comment by sundaqing1969** [comment]
其它的移动服务器可以这样用吗

**Comment by cnrip** [comment]
公布IP出来绝对不好使,想想原来论坛经常公布IP,不到一天就挂掉,后来论坛关闭,自己扫IP,一两个月都不用换.ZF那班人,都是衣来张手,饭来张口的混蛋.你们把IP公布出来,他还可以拿着IP向领导讨赏,厚颜无耻的跟领导说我又找到一段IP,你们每天公布,他们就可以每天向领导炫耀.你让他们自己扫,别开玩笑了,他们懒得跟猪一样.

**Comment by jasonliul** [comment]
@cnrip 

好有生活感~~

**Comment by jzp820927** [comment]
黑科技的力量果然强大。

**Comment by LGA1150** [comment]
@jasonliul 加了更多IP，请查收

**Comment by sundaqing1969** [comment]
goagent怎么用楼主提供的ip

**Comment by hcym** [comment]
现在速度还是刚刚的吗

移动不会哭晕吧

**Comment by LGA1150** [comment]
@sundaqing1969 用不了

**Comment by panpeach** [comment]
楼主，等IP失效了再来更新 ^_^ ^_^ ^_^

**Comment by jasonliul** [comment]
@LGA1150 
你不要这么嚣张嘛, 马上就64

**Comment by hcym** [comment]
别鬼嘘

这也可给老大拓展思路

64肿么了，赵家私事

本质还是狗咬狗g宫廷戏

政府都不好意思提

**Comment by yangchangyz** [comment]
有效，但速度不稳定，起伏很大，不为贪，只是好奇，本来吗············都是这样！

**Comment by jzp820927** [comment]
刚刚我无聊也测试了一下，速度确实挺牛B的，直接面上8k+，而且很稳定。现在没用了。

**Comment by hcym** [comment]
移动ip能上8k？，我这不行，离得远

刚刚凑巧找到扶桑ip

白天稳定7-8k，看看能活几天

**Comment by jasonliul** [comment]
@jzp820927 
我这里也是时好时坏, 还不如直接用.

另外把中国ip的袜子做前置, 也是随便实现"国内"中转.
不过那些大部分主机不在国内, 可以直连谷歌的.

**Comment by hcym** [comment]
移动服务器可以哦

也能4-5k

**Comment by hcym** [comment]
泪

终于看到 1440s

2160s 还不行

**Comment by jzp820927** [comment]
@hcym 忘记说了，我是最垃圾的电信网。移动和联通就不摆了，issues 里不是有个 G友 发了他的联通 ytb 截图嘛，直接上 32000+ kbps，望尘莫及。。。
@jasonliul 恩，前置其实也差不多，都是在国内中转，不过 socks 怕没有这种IP 稳定哦，应该失效挺快的。

**Comment by jasonliul** [comment]
@jzp820927 
帽子程序, 这些中国ip的袜子是洋人掏钱逆向翻墙用的, 相当稳定.
例如360云盘, 没有这些袜子就是个废, 速度等于蜗牛.

**Comment by jzp820927** [comment]
GP可以配置前置 s5 代理？没看到哪个配置文件有配置前置代理的。你说说，gp 这么配置前面，我也去测试下前置速度

**Comment by hcym** [comment]
是kbps，也是电信线路

以前白天根本上不了2-3kbps

10000+ kbps太奢侈，也就偶尔看个台湾TV，非常知足

刚刚试的最高的4K油管不行，以下等级的都是秒播

**Comment by wzdnzd** [comment]
最近好东西太多，有点不知道用啥的感觉了☹ 也就不用了哈
之前捡到个好东西，速度还不错，宿舍6人8M的联通宽带。。。
![image](https://cloud.githubusercontent.com/assets/8565764/15669346/7cd2130a-2752-11e6-8252-c8e9676411b4.png)

**Comment by vmnet** [comment]
围观下

**Comment by jzp820927** [comment]
楼上的 3W+ 的说，这些都是浮云。

**Comment by hcym** [comment]
ip重要

好的gvs连号会生仔，就是不知道是不是http2

显示都是HTTP/1.1，夜里能爬起来再试试传说中的10000+ kbps

**Comment by jzp820927** [comment]
gvs 全部都不支持 http2，只有 gws 支持。

**Comment by xrwz007** [comment]
不錯不錯感謝老司機們

**Comment by hcym** [comment]
不支持 http2，但是带宽明显gvs占优，而且干扰小

白头看1080P没负担了，继续gvs

**Comment by jzp820927** [comment]
只要带宽好，不用 http2 也行

**Comment by cnrip** [comment]
用的垃圾电信100M光纤,能上3-5K已经是烧高香了.

**Comment by hcym** [comment]
不在乎光纤还是钢纤

ipipip重要的事说三遍

**Comment by jzp820927** [comment]
对于电信网来说，IP再好，作用也不大，亲测过，相同 IP，凌晨 2点以后的速度，是2点前的 10 倍。

**Comment by hcym** [comment]
以前也是这样，高低差距大

今天下午用的ip似乎没被电信节流

它们的限流策略主要是应对商业，不太管翻墙

而且国内网络基础肯定电信最好

联通移动都做不到带宽独立，公网ip也最多

这可是联通的人说的

但是出口带宽确实不占优，僧多粥少

今年本来是准备换网的，被联通的一劝就罢了

**Comment by jzp820927** [comment]
移动和联通的出境带宽肯定比电信好，电信网好，只能体现的天朝大大局域网里面，确实是最好的，但是国际带宽就不行了，你对比下，电信，联通，移动，晚上出境的掉包率，就知道了。

**Comment by playnetcn** [comment]
@jzp820927我用的是电信，可以切换到联通线路，这么说吧，晚高峰联通速度是电信的10倍

**Comment by laozhu999** [comment]
@LGA1150 麻烦介绍一下这是什么原理啊？我就想学学。。

**Comment by jzp820927** [comment]
原理就是透明转发 https 流量。

**Comment by jzp820927** [comment]
主要是电信宽带的用户基数大，用4个字形容，僧多粥少。再好的基础设施，也经不起折腾。

**Comment by hcym** [comment]
电信对老用户不厚道，只能加钱不能减

变着法筐钱，不过想想联通也用过，也是一丘之貉

广电更不能碰，套餐到期以后试试移动吧

**Comment by jasonliul** [comment]
俺长宽朋友的说法是, 现在家庭宽带都是内联网, 没有指定国际出口的, 无论哪一家.
一旦访问国外, 就在国内瞎蹦跶, 然后挤最近的国际出口.

因此是陆地国家的ip晚间坚挺得多. 海底光缆就是个塞车.

**Comment by drg78rnvgh** [comment]
@jasonliul 所以我想查陆缆的分布，不知道有没有这种网
海缆的一早有了 www.cablemap.info/

**Comment by blob2015** [comment]
插一句，社长好像开始对autorange开刀了，本来俺只能144【还不稳定】，这会儿能到稳定360了

**Comment by blob2015** [comment]
@jasonliul 
好像伪军开始出现了？又
好像多出来了6个ip，我这里，如果cn的ip不被算入的话【平常cn填的ip好像都不会计入】

**Comment by yangchangyz** [comment]
我是联通用户，总体感觉不错，况且三运营商都在争地盘，这两年联通大力推广，优惠让步很多

**Comment by jzp820927** [comment]
联通，移动都行，就是别用垃圾电信。

**Comment by dapao9999** [comment]
如何才能找到这种地址呢？

**Comment by jzp820927** [comment]
强扫，不过估计挺老火的，中国的IP，位居全球第二，也是几亿IP

**Comment by guestluo** [comment]
thanks.能用。虽然不太明白。意思就是国内版的gcc？
我一直是搁到360p看，可以了。本来也就是了解一下内容而已。何须那么高的清晰度？
再说资源有限，节约一点用，人就能多了，也能持久了。

**Comment by inkdie** [comment]
请问，执行过你的操作之后，YouTube无法打开了，我应该怎么恢复到原来的样子呢？重新解压了最新版本，只编辑appid和ip地址，也是不能打开。降级也是不能打开。

**Comment by hcym** [comment]
今天还继续移动吗

联通移动应该也有类似服务

扫描

**Comment by sundaqing1969** [comment]
以前的扫描工具不能扫这种ip吧

**Comment by jzp820927** [comment]
以前的不行，除非有人开发这个工具。

**Comment by sundaqing1969** [comment]
懂行的开发一个粗糙扫描工具也行啦

**Comment by sypopo** [comment]
现在我这里用不起了

**Comment by sundaqing1969** [comment]
楼主快出来，那20个ip全失效了

**Comment by blob2015** [comment]
@sundaqing1969 
这东西，就尝个鲜，就得了，还让lz继续提供、维护，那是折磨人啊

**Comment by jzp820927** [comment]
这么快就完了？比我想象中死的快，全部都用不了了？

**Comment by sundaqing1969** [comment]
全完蛋了

**Comment by jasonliul** [comment]
Ipscan.exe 指示的服务器类型是 FC,
俺记得之前见过, 只是不清楚还有这等用法

**Comment by sundaqing1969** [comment]
@jasonliul，怎么扫这种ip？

**Comment by hcym** [comment]
等大码牛写呗

不过这类IP实际意义不大

毕竟属于私用，不希望被扫到

**Comment by hcym** [comment]
别和jason攀比牛角尖

常规IP更靠谱，今天白天都看到传说中的一万kpbs

但是不太稳

夜里应该更好

**Comment by jasonliul** [comment]
@hcym 

你这B, 阴阳怪气装女人, 有什么意见对俺?
:)

**Comment by LGA1150** [comment]
既然都说用不了了，我就close吧

**Comment by sundaqing1969** [comment]
楼主，这些ip只是间隙性失效，现在有可用了

**Comment by phuslu** [comment]
@LGA1150 嗯，咋咋唬唬伸手党是挺烦的，所以我昨天锁了贴好几个小时。

**Comment by sundaqing1969** [comment]
社长能不能给伸手党一个精确定义？

**Comment by hcym** [comment]
移动服务又上线了？

**Comment by jzp820927** [comment]
reopen 了，看来是要继续维护的节奏啊。

**Comment by sundaqing1969** [comment]
不稳定

**Comment by jzp820927** [comment]
这个东西，就那几台服务器，人越来越多，肯定速度就越来越慢了。偶尔用用可以，长期用，赶脚不现实

**Comment by sundaqing1969** [comment]
感谢楼主维护

**Comment by wukent** [comment]
还一些疑虑，要是共匪设的sni，会不会泄密？

**Comment by jzp820927** [comment]
@wukent https 没问题，因为私钥在 网站商手里，中间服务器解不了密

**Comment by NAVrasZ** [comment]
顶楼这些IP眼熟，平时下载一些热门资源就会被移动跳转到这些120开头的缓存服务器去
那么如何能知道自己地区ISP的这些地址呢？

**Comment by NAVrasZ** [comment]
好奇这些sni会不会给普通用户使用？去年的宽带上下对等时不需要代理轻松满速过墙，今年被坑成1MB/s之后访问极其困难（开着代理）。
怀疑移动对大带宽服务的用户有“特殊照顾”

**Comment by c6132a1** [comment]
楼上的兄弟们，我用go-sni扫移动ip就是扫不出来，到底怎么设置扫出来ip
