### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by cannanlly** [phuslu/goproxy#802]
r658 can not provide a proxy for TOR 6.0,log shows this:
*tls.Conn.Handshake() error: tls.RecordHeaderError{Msg:"first record does not look like a TLS handshake", RecordHeader:[5]uint8{0xf9, 0x1f, 0x5c, 0x3a, 0x3}}
*tls.Conn.Handshake() error: tls.RecordHeaderError{Msg:"oversized record received with length 27139", RecordHeader:[5]uint8{0xc8, 0x74, 0x80, 0x6a, 0x3}}

I'm not sure if this is a issue that come from golang,@phuslu thank you for checking it!

**Comment by phuslu** [comment]
GAE 自身的限制所致，不能充当 tor 前置。和 go 语言无关。

**Comment by jzp820927** [comment]
TOR 的代理需要原生支持 https 的代理，才行，gae 不是原生支持 https 的，所以不行。

**Comment by cannanlly** [comment]
I didn't kown that,thanks a lot!
