### ISSUE TITLE
goproxy 上传appid 上传不了？

### ISSUE THREAD

**Issue by Lemonjay** [phuslu/goproxy#804]
goproxy 上传appid 上传不了，能上传吗？

**Comment by Kisesy** [comment]
可以上传

**Comment by hcym** [comment]
说不清

有人可以，我用的不行，用goa传过，hosts也传过

**Comment by vmnet** [comment]
挂vpn试下

**Comment by blob2015** [comment]
@hcym 
端口与ip有没有改？没有上传成功的gp

**Comment by hcym** [comment]
端口没问题，和Goa一样

ip也是正常使用的，上传就是报错

最顺的还是hosts大法

Goa也是结结巴巴

**Comment by blob2015** [comment]
@hcym 
夜深人静＋99%以上的good ip？【或者已经轮一遍，即已经识别出了good与bad？】
ip是指没有改127.0.0.1这个吧？

倘若如此，看来还是hosts与vpn大法最省事

**Comment by masktao** [comment]
可以,首先要Ip能用质量好,再使用全局代理,每次都用goproxy上传,以前用蓝灯

**Comment by laozhu999** [comment]
我觉得你可以用pac在IE上google， 就可以上传。我今天刚发现P大的服务端更新了，就试了一把。 xxnet同理可以。
