### ISSUE TITLE
666 不会建证书?

### ISSUE THREAD

**Issue by lifly** [phuslu/goproxy#808]
W0601 22:58:05.356470    4936 rootca.go:166] Verify RootCA("GoProxy") error: x509: certificate signed by unknown authority, try import to system root

**Comment by phuslu** [comment]
右键管理员权限运行。

**Comment by lifly** [comment]
呃...什么时候变成这样了

**Comment by phuslu** [comment]
只要运行一次即可，以后可以随便什么权限启动。

**Comment by jap33** [comment]
r667右键管理员权限运行也不能生成证书，r666可以。

**Comment by phuslu** [comment]
667 和 666 没有区别

**Comment by jap33** [comment]
从r652起速度比r651速度慢了一半，大家试试。

**Comment by phuslu** [comment]
查了一下，有可能。谢谢反馈。

r652 做了一个优化，但是对于某些条件的确反而不好。

你把 gae.json 的 SocketReadBuffer 设置为 0 再测试一下呢。

**Comment by phuslu** [comment]
r668 已经改了回来，需要自定义的用户可以自设 gae.user.json

**Comment by jap33** [comment]
@phuslu 
在r652中把 SocketReadBuffer 设置为 0速度恢复了，但波动比较大。不改的话速度慢点速度较稳定波动很小。下面再试试最新版看看。

**Comment by jap33** [comment]
报告社长：r668正常了，起初望了把连续数从3改为6了，现在3也720p不卡了。扛扛的。
社长辛苦了谢谢！

**Comment by drg78rnvgh** [comment]
@phuslu 
反馈：668是自500版以来，我用的最快的一版
668之前，电信白天YouTube最高1000kbps，在300-800k之间波动 当时都以为这是墙进行了限速
668之后，同样ip，同样配置。720p最高6900kbps、1080p最高6000kbps。社长改对了。

**Comment by laozhu999** [comment]
@phuslu 报告P大，我是觉得620版真是给力，缓冲下载比668版快太多了。不知道是哪个参数改了？？稳定性差的。。

**Comment by phuslu** [comment]
@laozhu999 可能和这个改动有关。 https://github.com/phuslu/goproxy/commit/aa11cab4ea3256dc62b3d2d8b4d53805ce002e6a

我相信这一改动对大部分情况对会有提升，如果你那边有下降的话，尝试把 IdleTimeout 改回 180 再测试看看。

**Comment by zhajjqq** [comment]
高手看看這是什么ip!
![1](https://cloud.githubusercontent.com/assets/19146257/15753059/c518f746-2923-11e6-9dd8-6054b363bea3.PNG)

**Comment by lifly** [comment]
这楼要歪了...
话说,有些版本要右键管理员权限运行才会建证书(669),有些又不要需要(670)
