### ISSUE TITLE
Smart DNS Proxy + SmartVPN 半年特惠

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#816]
![lwwqhma png](https://cloud.githubusercontent.com/assets/2461165/15786086/38c58fb4-29ed-11e6-9251-eef63ca78e1b.png)

http://sharewareonsale.com/s/smart-dns-proxy-giveaway-sale
https://www.smartdnsproxy.com/SignUp?afid=df69e1764fc9

使用Smart DNS Proxy
https://www.smartdnsproxy.com/Setup?afid=bcbb23427a47

使用SmartVPN 
http://support.smartdnsproxy.com/customer/portal/topics/771448-vpn-instructions/articles?afid=bcbb23427a47

还有两天14小时

**Comment by jzp820927** [comment]
这个不错，就是不知道速度怎么样

**Comment by mixool** [comment]
DNS不能用，VPN方式，越南的给我跑满了！

**Comment by mixool** [comment]
移动网络对这个网址的网址有屏蔽，要在HOSTS里面写IP，访问才能绑定自己的本地IP.，开代理访问很尴尬。

**Comment by jzp820927** [comment]
我这边都用不了。

**Comment by jasonliul** [comment]
@mixool 
恭喜, 越南小妹也够辣
