### ISSUE TITLE
关于自动导入证书

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#82]
@phuslu 
今天重装了系统，运行原有的goproxy并没有自动导入证书
不过手动导入后，一切如故:)

**Comment by phuslu** [comment]
目前没有自动检测证书是否导入的机制，需要删除证书才能触发自动导入。

**Comment by thepromises** [comment]
先删除certs文件夹

**Comment by thepromises** [comment]
先删除certs文件夹
