### ISSUE TITLE
反馈：r683没r675速度好

### ISSUE THREAD

**Issue by sishentibu** [phuslu/goproxy#823]
晚上试了下，r683速度只有几百k（几百200-600k浮动）。换了几组ip速度都上不去。

但同样的ip，r675上1M的速度还是比较轻松的。r675这边的问题就是，开启时间久了后，速度会下降，只有几百k，但只要重启，速度一会就上去了。

速度都是用YouTube测的。主要也就是看视频的时候有影响，看网页的话，几百k也能看了

**Comment by phuslu** [comment]
已知问题，gae.go 你调整为 IdleConnTimeout 180 秒试下。

**Comment by sishentibu** [comment]
@phuslu 改gae.user.json 也可以的吧？这个版本默认的是300，我改了试试

**Comment by phuslu** [comment]
嗯，r686 改回来了，暂时先这样吧。等有人反馈 180 秒反而慢了，再说。

**Comment by phuslu** [comment]
看错了，r675 到 r683 没有任何性能相关的改动。那么应该是你的测试的问题了。

**Comment by sishentibu** [comment]
难道是我换的时候刚好碰到网络不好吗。
我明天再试试。
