### ISSUE TITLE
r686--pac模式下单单是youtube过不了?

### ISSUE THREAD

**Issue by MeABc** [phuslu/goproxy#824]
如题。pac模式下，测试的网址有 github 、google 、youtube，单单是youtube过不了， 
chrome 提示 ERR_PROXY_CONNECTION_FAILED

但在 gae(http)下全正常。或者说是全局模式下全正常。

又，
autoproxy.json 里 IndexFiles 现在这个参数有问题，即 IndexFiles Enabled = false ，
整个 pac （autoproxy）都不能用，浏览器表现为 proxy.pac 不能加载。感觉 IndexFiles 变成了 autoproxy 总开关。

-----
忘了，我说错了，自定义文件proxy.pac 里我有加 github ，包括原来的 google ，应该是pac模式下全都过不了。

**Comment by phuslu** [comment]
啊，是 bug, 请更新到 r687

目前的确是把 proxy.pac 的开关合并到 IndexFiles 里面了，既然不喜欢，下个版本会改回来的。

**Comment by MeABc** [comment]
不要改回来啊，总感觉为了个人喜欢改回来不太好，大局大局。。。。

**Comment by MeABc** [comment]
在不改回来的情况下，提个建议，能不能把 IndexFiles  放在顶部，一个总开关放在中间有点乱啊

**Comment by MeABc** [comment]
呃。。。。理解错了，不用放顶部了。明白了 IndexFiles  的作用了。。。
哎。。。。原谅我的智商。
