### ISSUE TITLE
封锁太严了

### ISSUE THREAD

**Issue by yangchangyz** [phuslu/goproxy#825]
封锁太严了，用什么都不快；手机上的蓝灯死了，好在以前在谷歌play上找了个免费vpn，挺好服务器多，720p完美。看来买个靠谱vpn势在必得，大家有什么心得吗

**Comment by wzdnzd** [comment]
虽然其他的速度变慢了，但是我这gp的速度好像没太大影响
![image](https://cloud.githubusercontent.com/assets/8565764/15847405/2d4c97ea-2cb8-11e6-8207-25f2049748ad.png)

**Comment by fredericky123** [comment]
求问哪个免费vpn

**Comment by TangBaohua** [comment]
不怎么严吧，要是Goproxy有手机版就好了
