### ISSUE TITLE
bugs!

### ISSUE THREAD

**Issue by cannanlly** [phuslu/goproxy#827]
https://download.skype.com/0bd9db07a3e38056159ec2cc1f49a6fa/SkypeSetupFull.exe下载这个只能读取32mb，它应该有40mb。
https://support.skype.com/en/faq/FA79/how-do-i-install-skype   这个网址打开乱码

**Comment by fuckGFW2015** [comment]
https://docs.google.com/uc?id=0B-DsU_zfRpvXNDZtVFVfQlJUakE&export=download我这个也下载不了

**Comment by Kisesy** [comment]
以现在的情况，遇到32M的问题，请自行往 autorange.json 添下载地址
还有这个网站根本不需要开代理

**Comment by drg78rnvgh** [comment]
@Kisesy 如何添加？

**Comment by jzp820927** [comment]
应该是家到  site 里面吧

**Comment by cannanlly** [comment]
skype 不开代理会被强转到TOM版，那可是监控啊

**Comment by jzp820927** [comment]
我去，原来你是想下载国际版啊

**Comment by phuslu** [comment]
乱码问题，在 r693 已经修复。

32M 限制请等待 autorange 重构完成。

**Comment by cannanlly** [comment]
thanks!
