### ISSUE TITLE
有关 gfwlist update 

### ISSUE THREAD

**Issue by MeABc** [phuslu/goproxy#828]
先上图
![2016-06-07_195303](https://cloud.githubusercontent.com/assets/18194126/15856725/feacc7e8-2ce9-11e6-8e63-8ad46084e018.png)

![2016-06-07_201937](https://cloud.githubusercontent.com/assets/18194126/15857304/38691f38-2ced-11e6-8efb-8dff3c664bc8.png)

![2016-06-07_195336](https://cloud.githubusercontent.com/assets/18194126/15856727/01f45f74-2cea-11e6-9499-52eec016a408.png)

社长，这是啥情况？是不是  [https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt) 这个地址被墙导致的连接中断？

在这里引出一个问题， 上面的这个网址（或者以后自定义的下载地址）走不走 gae ? 或者说，可不可以自定义走不走 gae 。

**Comment by phuslu** [comment]
会给 gfwlist 加个 useproxy 选项，指定它是否走自身代理

**Comment by MeABc** [comment]
还有一个问题， 关于 IdleConnTimeout 参数的。

想问的是，上述参数值时间一到就关闭连接，还是会发一个心跳包，
https://clients3.google.com/generate_204 这个是不是属于“心跳”检测。

呃，问这些是想确定一下，我想自定义这个参数，以适应我的网络环境。

**Comment by drg78rnvgh** [comment]
@phuslu 我想问，gfwlist对goproxy的效率是否有所降低，我能不能关闭它？我在介绍中没找到关闭的方法

**Comment by yeahwu** [comment]
关掉autoproxy就好了
httpproxy.json文件，注释掉autoproxy
```
		"RoundTripFilters": [
			// "autoproxy",
			// "auth",
			// "vps",
			// "php",
			"gae",
			"direct",
```

**Comment by MeABc** [comment]
关闭：
autoproxy.json ——》GFWList ——》Enabled -——》false

**Comment by phuslu** [comment]
autoproxy 本身的开销相对 gae/php/direct 可以看作 0。
autoproxy 里面的子项 gfwlist 不在关键路径上，和性能无关。

而且这些都和手动可以关闭，虽然不建议。（我自己从来不关闭）
go 语言的效率之高，完全可以忽略这些规则的匹配开销。

**Comment by hcym** [comment]
这玩意不会比app耗资源

就是量身定制麻烦一点

**Comment by yeahwu** [comment]
俺都是关掉的，浏览器上有插件autoproxy，感觉就没必要使用goproxy的autoproxy
其实嘛，一句话，不要在意这些细节

**Comment by phuslu** [comment]
多说几句，从 autoproxy.go 的规则匹配来看

https://github.com/phuslu/goproxy/blob/master/httpproxy/filters/autoproxy/autoproxy.go#L213-L224

在关键路径会经过三次判断。

1. SiteFiltersEnabled 默认关闭，是一个 bool 判断。
2. RegionFiltersEnabled 默认关闭， 同上
3. req.URL.Host == "" 只有直接访问 127.0.0.1:8087 才会命中，所以也不会影响性能。

综上，autoproxy 打开的话，对代理的性能影响可以看作是 0

**Comment by phuslu** [comment]
autoproxy 也不单提供 gfwlist pac 的功能。
比如 IndexFiles 可以用来下载证书。SiteFilters 用来解决一些疑难杂症 rarbg, slideshare, live.github.com 等。

**Comment by hcym** [comment]
正好请教一个问题，我的pac
var normal = "PROXY 127.0.0.1:8087; PROXY 127.0.0.1:8787; DIRECT";

主要是屏蔽广告，如何在var normal = ""加autoproxy端口来定义 normal

**Comment by phuslu** [comment]
@hcym 不太明白你的需求。

你原来的 pac 长什么样子？你期望 goproxy ”处理“ 以后的样子是什么？

**Comment by hcym** [comment]
就是代替DIRECT，其他都已经搞好

首先浏览器定义
--proxy-pac-url=file:///home/oem/wallproxy/ssa.pac

ssa里再定义，3421为黑洞路由，权重最大
var noadsver = "PROXY 127.0.0.1:3421";
var bypass = "PROXY 127.0.0.1:8088; PROXY 127.0.0.1:8787; DIRECT";
var normal = "PROXY 127.0.0.1:8087; PROXY 127.0.0.1:8787; DIRECT";

用蓝灯，它有内置pac，国内的自动旁路

用gop，似乎没这个效果

**Comment by hcym** [comment]
老大，这不急

前置比较急

**Comment by MeABc** [comment]
社长， pac文件最后不是由客户端（浏览器）来匹配的吗？ 难道同代理（GP）来做匹配的？
这里的代理不是指  SwitchyOmega 这种。

**Comment by phuslu** [comment]
@hcym 嗯，还请稍安勿躁。

@MeABc pac 的确是你说的这样。这里的 RegionFilters 是类似 APN 的那种功能。

**Comment by MeABc** [comment]
我说嘛，gfwlist 怎么会有影响性能一说。

**Comment by drg78rnvgh** [comment]
@MeABc 谢谢回复。毕竟是机子比较烂

**Comment by blob2015** [comment]
搬小凳子mark
