### ISSUE TITLE
好像应该是老问题：关于bad ip检测

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#829]
**系统消息：**695，Win7 32
**问题：**
俺没有打开默认联网【无线】，而且加载的程序会有点多，所以等俺连接上网络，早早自动开启的gp，已经有好些个bad ip，如果时间比较长【比如半小时】，那么这些bad ip不会回炉，然后就需要某位老兄提到的关gp，重启gp

**可否？**
1. 延迟开启gp——针对加载得好几圈的家伙，比如qq，skype，阿里，以及各种品牌电脑捎带的全家桶——，这样的话，减少good ip被认定为bad的概率。
2. 检测是否开通了网络，然后再测试ip？

看社长怎么处置了 :grinning: 
据说已经肉翻了，可能也未必喜欢粽子，还是送上端午小祝福 @phuslu 
可能jasonliul又要说，没干货，没诚意 :grinning:

**Comment by jzp820927** [comment]
按照社长的说法，badip 会每个 5分钟重检一次。

**Comment by MeABc** [comment]
我来说下吧，回答之前先说下，提问前要善用搜素。

1.
bad_addrs 这个问题社长已回复（我）过了，GP会重新判断。
https://github.com/phuslu/goproxy/blob/master/httpproxy/filters/gae/gae.go#L209

2.
一般来说，qq，skype，阿里这些是用不了 GP(GAE) 的，这是由于GAE 的 “先天不足” 决定的。像这些应用一般都是用socks（或原生https）代理。

当然，我没试过 上述这些 用在GAE上，不好确定，但，你可以查看日志的，看哪些在连。
所以还是那句话，日志日志日志

3.
如果你实在是担心，那不要设 gp 开机启动，可以这样，想 “出国” 时再打开。

可以参考我的作法：
  设开机启动，但不设IE代理，如下图
![2016-06-08_100507](https://cloud.githubusercontent.com/assets/18194126/15880500/a314dcbe-2d60-11e6-9ed6-0e1be72c0ed8.png)

**Comment by blob2015** [comment]
@MeABc 
老兄也进来了啊。谢谢。 :grinning: 
1. 其实也相关，也未必相关，是一个问题，可能也未必是一个问题。检测间隔是5分钟，那么如果休眠回来，或者断网接续，一般都是不可能等5分钟的。当然，这个应用场景，不是特别普遍的，有点强人所难 :grinning: 
2. 不是这些程序用gae，而是这些一堆的程序【应该加上杀软】，会阻隔机器的网络连接与程序的启动一定时间——阻隔5分钟，那倒是比较少见，但两三分钟，不算太少，尤其电脑还比较破烂什么的。这时候，一圈的ip都被判定为bad了【如果ip数量比较少的话】，需要等下一个轮回了——5分钟
3. 之前都是开机启动，现在调整成了手动开启了

**Comment by jasonliul** [comment]
@blob2015 
先把GP加入杀软白名单好了

**Comment by missmuxixi** [comment]
图标右键 重新载入 可否解决

**Comment by MeABc** [comment]
@blob2015 
看了半天也没看明白，你到底纠结哪种情况----间隔时间短？间隔时间不精确？怕 IP 会无故判成 bad_addrs (或者说，你怕找到的 IP 被封杀) ？

我们换个角度，假如你找了10个IP，你不用，过了一天，它们同样会被封杀。为什么呢，因为我在用，
哈哈。。。开个玩笑，原因你懂的。所以应该去找更多的 IP 。而不是纠结这些。

另一个，关于 企鹅 全家桶 等等这种，为什么你们都了解原因，但又要和代理（泛指）放在一起用，出了事（IP被封杀），结果只能你自已承担。

**Comment by jasonliul** [comment]
这是多ip党的杞人忧天.

俺只用4个, 最近不会死掉几个, 只是表现不稳定.
所以无聊的话, 还是CheckGip扫一把, 换一组.

**Comment by phuslu** [comment]
谢谢反馈，r696 做了优化，这样如果 good_addrs 不够的情况下，即使 bad_addrs 没到 5 分钟，也会去挑选了。

这个修复也让休眠恢复的电脑能够更快恢复，显得更“稳定”了。

**Comment by blob2015** [comment]
@MeABc 
这说明老兄与 @jzp820927 类似，可能机器比较好，设置比较好，网络也不差，可能还不是windows :grinning: 

~~间隔时间短？间隔时间不精确？怕 IP 会无故判成 bad_addrs (或者说，你怕找到的 IP 被封杀) ？~~

都不是啊。而是烂电脑碰上烂网络，然后还开启了一堆的开机自启【有几个是电脑自带的驱动管理程序】，gp一般都比较快就开启，然后开机大概两三分钟才会自动连接上网络【无线】。然后如果立马就会用到gp的话，就会发现没有ip可用了。
就是这个场景 :grinning: 

@jasonliul 
看见老兄更新了《2016 春天反审查武库大阅兵》到《夏天》 :grinning: 
这个与杀软白名单与多ip都无关，反而是少ip相对更加容易遇到 :grinning:

**Comment by blob2015** [comment]
@phuslu 
社长如此处理，也算以简奴繁 :grinning: 
谢谢
