### ISSUE TITLE
which is what the Cauchy integral theorem states. The values of such a holomorphic function inside

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#836]
ou may modify your copy or copies of the Program or any portion of it, thus forming a work based on the Program, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions

**Comment by blob2015** [comment]
被好多人说过，也有人提到过lz提到的做法，相对彻底地解决，只能等社长来重构autorange，还需要一些时间

**Comment by jasonliul** [comment]
Drg 也是干货郎~~

**Comment by masktao** [comment]
不知道要等多久才能解决

**Comment by xc1988** [comment]
火狐的插件YouTube Video and Audio Downloader 和 DownThemAll! 这两个就行啊

**Comment by Asteroids89** [comment]
期待社长尽快重构autorange

**Comment by Kisesy** [comment]
期待社长尽快重构autorange

**Comment by jzp820927** [comment]
好像 autorange 已经弄了很长时间了，估计还得等。

**Comment by phuslu** [comment]
已经完成一半了， 见 fragment.go 这个问题，接下来就用它来重新实现 autorange 了。

**Comment by Kisesy** [comment]
现在也基本能用，但有些地址会有问题
举个例子，配置里先添加

		"*.s3.amazonaws.com",

再配置

	"MaxSize": 1048576,
	"BufSize": 131072,
	"Threads": 8

然后再到 Gop 的 releases 里下个 Windows 版的
下完之后打开压缩包就是错误的，大小就是整1M，就不会再下后面的部分
如果 MaxSize 设置的大一点就没问题，这个地址也不是不支持断点续传
这个问题应该会顺便解决吧。。
