### ISSUE TITLE
Arch下goproxy无法启动

### ISSUE THREAD

**Issue by NKUCodingCat** [phuslu/goproxy#838]
[nkucodingcat@Nankai ~]$ '/home/nkucodingcat/goproxy/goproxy' 	
	------------------------------------------------------
	GoProxy Version    : r697 (go/devel+f0b9f7e linux/amd64)
	GoProxy Profile    : Default
	Listen Address     : 127.0.0.1:8087
	Enabled Filters    : stripssl,autorange|autoproxy,gae,direct|autorange
	Pac Server         : http://127.0.0.1:8087/proxy.pac
	------------------------------------------------------
	I0609 19:33:11.917016    8008 autoproxy.go:396] start updater for "https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt"
	panic: invalid argument to Intn	

	goroutine 6 [running]:
	panic(0x806120, 0xc42061fca0)
		/home/travis/goproxy.20160608.24474/go/src/runtime/panic.go:500 +0x1a1
	math/rand.(*Rand).Intn(0xc42000c2e0, 0x0, 0xc4201094b8)
		/home/travis/goproxy.20160608.24474/go/src/math/rand/rand.go:98 +0xd0
	math/rand.Intn(0x0, 0x0)
		/home/travis/goproxy.20160608.24474/go/src/math/rand/rand.go:214 +0x37
	_/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters/gae.NewFilter.func1(0x0, 0x0, 0x0, 0x0, 0xc42069e450, 0x0)
		/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters/gae/gae.go:158 +0x24d
	_/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters/gae.NewFilter(0xc420226ea0, 0xc420109a90, 0xc4207a0f00, 0xc4202e11e0, 0x0)
		/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters/gae/gae.go:178 +0x540
	_/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters/gae.init.1.func1(0x82a7c0, 0xc420014f00, 0xc4202dd849, 0x3)	
		/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters/gae/gae.go:97 +0x2	a
	_/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters.NewFilter(0xc4202dd849, 0x3, 0xc4202dd849, 0x3, 0xad3f20, 0xc420109b00)
		/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters/filters.go:57 +0x6a	
	_/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters.GetFilter(0xc4202dd849, 0x3, 0xc4202dd849, 0x3, 0xad3f20, 0x0)
		/home/travis/goproxy.20160608.24474/goproxy/httpproxy/filters/filters.go:66 +0x7e
	_/home/travis/goproxy.20160608.24474/goproxy/httpproxy.getFilters(0xc4202dd880, 0x7, 0xc4202dd820, 0xe, 0xc4202dd9c0, 0xa92fa0, 0xc4202ee340, 0x0, 0x0, 0x0, ...)
		/home/travis/goproxy.20160608.24474/goproxy/httpproxy/httpproxy.go:98 +0xbfa
	_/home/travis/goproxy.20160608.24474/goproxy/httpproxy.ServeProfile(0xc4202dd880, 0x7, 0xc42004bc88, 0x1)
		/home/travis/goproxy.20160608.24474/goproxy/httpproxy/httpproxy.go:66 +0x179
	created by main.main
		/home/travis/goproxy.20160608.24474/goproxy/main.go:64 +0xa71

所以说我应该自己编译一次么……

**Comment by jzp820927** [comment]
panic: invalid argument to Intn 
看提示说的是 无效的参数

**Comment by phuslu** [comment]
你的 gae.json 或者 gae.user.json 贴出来看看？

**Comment by NKUCodingCat** [comment]
{
	"AppIDs": [
		"cjtnku0", "cjtnku1", "cjtnku2", "cjtnku3", "cjtnku4"
	],
	"Password": "",
	"SSLVerify": false,
	"ForceIPv6": false,
	"DisableHTTP2": false,
	"ForceHTTP2": false,
	"EnableDeadProbe": true,
	"Sites": [
		"*"
	],
	"HostMap" : {
		"google_hk": [
			 "216.239.38.127", "216.58.200.192", "172.217.25.220", "216.58.200.201", "172.217.25.244", "216.58.200.187", "172.217.25.223", "172.217.26.36", "172.217.25.198", "172.217.25.210", "216.58.200.220", "216.58.200.212", "216.58.200.186", "172.217.25.72", "216.58.200.190", "172.217.25.235", "172.217.26.49", "115.164.12.166", "172.217.26.38", "172.217.25.82", "216.58.200.183", "172.217.25.90", "216.58.200.206", "172.217.25.237", "209.85.234.219", "74.125.132.194", "209.85.234.17", "23.228.130.240", "172.217.4.110", "172.217.4.98", "209.85.235.191", "209.85.235.18", "74.125.132.164", "209.85.234.104", "173.194.198.112", "209.85.234.95", "209.85.234.118", "209.85.235.239", "173.194.67.164", "113.171.252.187", "209.85.235.99", "173.194.67.167", "172.217.4.230", "209.85.234.84", "173.194.198.124", "74.125.132.181", "172.217.4.239", "173.194.198.147", "209.85.234.116", "209.85.144.18", "173.194.198.139", "74.125.132.191", "173.194.66.124", "209.85.235.141", "173.194.66.106", "172.217.4.221", "173.194.66.94", "209.85.144.189", "209.85.144.99", "173.194.66.18", "201.218.56.154", "177.36.3.55", "209.85.144.138", "172.217.28.239", "172.217.29.84", "157.157.135.59", "172.217.29.79", "172.217.29.67", "173.194.66.193", "201.218.56.153", "209.85.235.193", "172.217.29.25", "216.58.198.21", "172.217.21.203", "172.217.22.19", "172.217.21.191", "172.217.21.202", "172.217.20.235", "172.217.21.187", "172.217.22.23", "172.217.28.235", "172.217.21.250", "172.217.29.10", "172.217.28.231", "216.58.198.55", "172.217.28.245", "172.217.21.15", "172.217.21.131", "172.217.21.66", "172.217.21.217", "172.217.22.29", "172.217.21.113", "172.217.21.133", "172.217.21.168", "172.217.21.30", "172.217.21.134", "74.125.232.238", "203.207.55.215", "74.125.232.250", "216.58.198.13", "216.239.38.123", "172.217.25.71", "172.217.25.85", "172.217.25.123", "172.217.26.34", "172.217.25.229", "172.217.25.205", "216.58.200.196", "216.58.200.175", "172.217.26.45", "216.58.200.200", "216.58.200.210", "216.58.200.203", "216.58.200.166", "173.194.198.98", "74.125.132.166", "173.194.67.219", "74.125.132.105", "173.194.198.190", "172.217.4.233", "209.85.235.190", "172.217.4.254", "209.85.235.116", "172.217.4.123", "113.171.252.216", "201.157.30.53", "172.217.4.246", "172.217.4.239", "172.217.4.250", "209.85.234.137", "172.217.4.125", "173.194.198.112", "173.194.198.101", "173.194.198.165", "209.85.235.103", "173.194.198.81", "173.194.198.118", "209.85.235.124", "209.85.235.112", "209.85.235.198", "173.194.66.115", "172.217.4.213", "172.217.4.209", "172.217.4.210", "209.85.144.116", "209.85.144.198", "172.217.4.199", "209.85.144.104", "209.85.144.143", "177.36.3.50", "172.217.29.93", "173.194.66.142", "157.157.135.59", "201.218.56.149", "172.217.29.68", "172.217.29.14", "201.218.56.154", "172.217.21.197", "172.217.21.23", "172.217.21.8", "172.217.21.41", "172.217.21.227", "172.217.21.154", "172.217.21.90", "216.58.198.54", "172.217.21.241", "172.217.21.175", "172.217.21.169", "95.168.222.148", "172.217.29.24", "216.58.198.33", "172.217.21.95", "216.58.198.18", "172.217.21.114", "172.217.22.6", "172.217.21.133", "172.217.22.28", "113.171.247.99", "172.217.21.162", "172.217.20.250", "172.217.22.21", "173.194.66.148", "172.217.21.28", "172.217.21.135", "95.168.222.153", "172.217.21.152", "172.217.21.190", "172.217.20.247", "172.217.21.213", "172.217.21.158", "172.217.21.170", "89.47.210.117", "172.217.21.166", "203.176.178.45", "172.217.21.239", "74.125.232.247", "74.125.232.233", "173.194.66.18", "74.125.232.246", "203.176.178.42", "172.217.25.99", "172.217.26.38", "216.58.200.189", "172.217.25.221", "113.171.244.89", "113.171.247.24", "113.171.242.182", "113.171.244.93", "172.217.4.97", "209.85.235.199", "209.85.234.138", "209.85.234.105", "74.125.132.189", "209.85.235.166", "172.217.4.99", "172.217.4.246", "209.85.234.199", "74.125.132.101", "209.85.234.100", "209.85.235.124", "209.85.234.194", "209.85.234.82", "173.194.67.152", "209.85.235.103", "209.85.235.201", "209.85.144.200", "172.217.5.25", "172.217.28.239", "209.85.144.98", "209.85.144.84", "173.194.66.113", "172.217.28.232", "172.217.29.4", "172.217.21.107", "172.217.21.116", "172.217.29.26", "172.217.20.225", "172.217.21.127", "172.217.28.250", "74.125.232.246", 
			"googleapis.l.google.com",
			"cert-test.sandbox.google.com",
			"googlecode.l.googleusercontent.com",
			"maps.l.google.com",
			"code.l.google.com",
			"mail.l.google.com",
			"mail.google.com",
			"www.google.com.hk",
			"www.google.com.tw",
			"www.l.google.com",
			"www2.l.google.com",
			"www3.l.google.com",
			"www4.l.google.com",
			"www5.l.google.com",
			"www.google.com"
		],
		"google_talk": [
			 "216.239.38.127", "216.58.200.192", "172.217.25.220", "216.58.200.201", "172.217.25.244", "216.58.200.187", "172.217.25.223", "172.217.26.36", "172.217.25.198", "172.217.25.210", "216.58.200.220", "216.58.200.212", "216.58.200.186", "172.217.25.72", "216.58.200.190", "172.217.25.235", "172.217.26.49", "115.164.12.166", "172.217.26.38", "172.217.25.82", "216.58.200.183", "172.217.25.90", "216.58.200.206", "172.217.25.237", "209.85.234.219", "74.125.132.194", "209.85.234.17", "23.228.130.240", "172.217.4.110", "172.217.4.98", "209.85.235.191", "209.85.235.18", "74.125.132.164", "209.85.234.104", "173.194.198.112", "209.85.234.95", "209.85.234.118", "209.85.235.239", "173.194.67.164", "113.171.252.187", "209.85.235.99", "173.194.67.167", "172.217.4.230", "209.85.234.84", "173.194.198.124", "74.125.132.181", "172.217.4.239", "173.194.198.147", "209.85.234.116", "209.85.144.18", "173.194.198.139", "74.125.132.191", "173.194.66.124", "209.85.235.141", "173.194.66.106", "172.217.4.221", "173.194.66.94", "209.85.144.189", "209.85.144.99", "173.194.66.18", "201.218.56.154", "177.36.3.55", "209.85.144.138", "172.217.28.239", "172.217.29.84", "157.157.135.59", "172.217.29.79", "172.217.29.67", "173.194.66.193", "201.218.56.153", "209.85.235.193", "172.217.29.25", "216.58.198.21", "172.217.21.203", "172.217.22.19", "172.217.21.191", "172.217.21.202", "172.217.20.235", "172.217.21.187", "172.217.22.23", "172.217.28.235", "172.217.21.250", "172.217.29.10", "172.217.28.231", "216.58.198.55", "172.217.28.245", "172.217.21.15", "172.217.21.131", "172.217.21.66", "172.217.21.217", "172.217.22.29", "172.217.21.113", "172.217.21.133", "172.217.21.168", "172.217.21.30", "172.217.21.134", "74.125.232.238", "203.207.55.215", "74.125.232.250", "216.58.198.13", "216.239.38.123", "172.217.25.71", "172.217.25.85", "172.217.25.123", "172.217.26.34", "172.217.25.229", "172.217.25.205", "216.58.200.196", "216.58.200.175", "172.217.26.45", "216.58.200.200", "216.58.200.210", "216.58.200.203", "216.58.200.166", "173.194.198.98", "74.125.132.166", "173.194.67.219", "74.125.132.105", "173.194.198.190", "172.217.4.233", "209.85.235.190", "172.217.4.254", "209.85.235.116", "172.217.4.123", "113.171.252.216", "201.157.30.53", "172.217.4.246", "172.217.4.239", "172.217.4.250", "209.85.234.137", "172.217.4.125", "173.194.198.112", "173.194.198.101", "173.194.198.165", "209.85.235.103", "173.194.198.81", "173.194.198.118", "209.85.235.124", "209.85.235.112", "209.85.235.198", "173.194.66.115", "172.217.4.213", "172.217.4.209", "172.217.4.210", "209.85.144.116", "209.85.144.198", "172.217.4.199", "209.85.144.104", "209.85.144.143", "177.36.3.50", "172.217.29.93", "173.194.66.142", "157.157.135.59", "201.218.56.149", "172.217.29.68", "172.217.29.14", "201.218.56.154", "172.217.21.197", "172.217.21.23", "172.217.21.8", "172.217.21.41", "172.217.21.227", "172.217.21.154", "172.217.21.90", "216.58.198.54", "172.217.21.241", "172.217.21.175", "172.217.21.169", "95.168.222.148", "172.217.29.24", "216.58.198.33", "172.217.21.95", "216.58.198.18", "172.217.21.114", "172.217.22.6", "172.217.21.133", "172.217.22.28", "113.171.247.99", "172.217.21.162", "172.217.20.250", "172.217.22.21", "173.194.66.148", "172.217.21.28", "172.217.21.135", "95.168.222.153", "172.217.21.152", "172.217.21.190", "172.217.20.247", "172.217.21.213", "172.217.21.158", "172.217.21.170", "89.47.210.117", "172.217.21.166", "203.176.178.45", "172.217.21.239", "74.125.232.247", "74.125.232.233", "173.194.66.18", "74.125.232.246", "203.176.178.42", "172.217.25.99", "172.217.26.38", "216.58.200.189", "172.217.25.221", "113.171.244.89", "113.171.247.24", "113.171.242.182", "113.171.244.93", "172.217.4.97", "209.85.235.199", "209.85.234.138", "209.85.234.105", "74.125.132.189", "209.85.235.166", "172.217.4.99", "172.217.4.246", "209.85.234.199", "74.125.132.101", "209.85.234.100", "209.85.235.124", "209.85.234.194", "209.85.234.82", "173.194.67.152", "209.85.235.103", "209.85.235.201", "209.85.144.200", "172.217.5.25", "172.217.28.239", "209.85.144.98", "209.85.144.84", "173.194.66.113", "172.217.28.232", "172.217.29.4", "172.217.21.107", "172.217.21.116", "172.217.29.26", "172.217.20.225", "172.217.21.127", "172.217.28.250", "74.125.232.246", 
			"talk.google.com",
			"talk.l.google.com",
			"talkx.l.google.com"
		],
		"google_cn": [
			 "216.239.38.127", "216.58.200.192", "172.217.25.220", "216.58.200.201", "172.217.25.244", "216.58.200.187", "172.217.25.223", "172.217.26.36", "172.217.25.198", "172.217.25.210", "216.58.200.220", "216.58.200.212", "216.58.200.186", "172.217.25.72", "216.58.200.190", "172.217.25.235", "172.217.26.49", "115.164.12.166", "172.217.26.38", "172.217.25.82", "216.58.200.183", "172.217.25.90", "216.58.200.206", "172.217.25.237", "209.85.234.219", "74.125.132.194", "209.85.234.17", "23.228.130.240", "172.217.4.110", "172.217.4.98", "209.85.235.191", "209.85.235.18", "74.125.132.164", "209.85.234.104", "173.194.198.112", "209.85.234.95", "209.85.234.118", "209.85.235.239", "173.194.67.164", "113.171.252.187", "209.85.235.99", "173.194.67.167", "172.217.4.230", "209.85.234.84", "173.194.198.124", "74.125.132.181", "172.217.4.239", "173.194.198.147", "209.85.234.116", "209.85.144.18", "173.194.198.139", "74.125.132.191", "173.194.66.124", "209.85.235.141", "173.194.66.106", "172.217.4.221", "173.194.66.94", "209.85.144.189", "209.85.144.99", "173.194.66.18", "201.218.56.154", "177.36.3.55", "209.85.144.138", "172.217.28.239", "172.217.29.84", "157.157.135.59", "172.217.29.79", "172.217.29.67", "173.194.66.193", "201.218.56.153", "209.85.235.193", "172.217.29.25", "216.58.198.21", "172.217.21.203", "172.217.22.19", "172.217.21.191", "172.217.21.202", "172.217.20.235", "172.217.21.187", "172.217.22.23", "172.217.28.235", "172.217.21.250", "172.217.29.10", "172.217.28.231", "216.58.198.55", "172.217.28.245", "172.217.21.15", "172.217.21.131", "172.217.21.66", "172.217.21.217", "172.217.22.29", "172.217.21.113", "172.217.21.133", "172.217.21.168", "172.217.21.30", "172.217.21.134", "74.125.232.238", "203.207.55.215", "74.125.232.250", "216.58.198.13", "216.239.38.123", "172.217.25.71", "172.217.25.85", "172.217.25.123", "172.217.26.34", "172.217.25.229", "172.217.25.205", "216.58.200.196", "216.58.200.175", "172.217.26.45", "216.58.200.200", "216.58.200.210", "216.58.200.203", "216.58.200.166", "173.194.198.98", "74.125.132.166", "173.194.67.219", "74.125.132.105", "173.194.198.190", "172.217.4.233", "209.85.235.190", "172.217.4.254", "209.85.235.116", "172.217.4.123", "113.171.252.216", "201.157.30.53", "172.217.4.246", "172.217.4.239", "172.217.4.250", "209.85.234.137", "172.217.4.125", "173.194.198.112", "173.194.198.101", "173.194.198.165", "209.85.235.103", "173.194.198.81", "173.194.198.118", "209.85.235.124", "209.85.235.112", "209.85.235.198", "173.194.66.115", "172.217.4.213", "172.217.4.209", "172.217.4.210", "209.85.144.116", "209.85.144.198", "172.217.4.199", "209.85.144.104", "209.85.144.143", "177.36.3.50", "172.217.29.93", "173.194.66.142", "157.157.135.59", "201.218.56.149", "172.217.29.68", "172.217.29.14", "201.218.56.154", "172.217.21.197", "172.217.21.23", "172.217.21.8", "172.217.21.41", "172.217.21.227", "172.217.21.154", "172.217.21.90", "216.58.198.54", "172.217.21.241", "172.217.21.175", "172.217.21.169", "95.168.222.148", "172.217.29.24", "216.58.198.33", "172.217.21.95", "216.58.198.18", "172.217.21.114", "172.217.22.6", "172.217.21.133", "172.217.22.28", "113.171.247.99", "172.217.21.162", "172.217.20.250", "172.217.22.21", "173.194.66.148", "172.217.21.28", "172.217.21.135", "95.168.222.153", "172.217.21.152", "172.217.21.190", "172.217.20.247", "172.217.21.213", "172.217.21.158", "172.217.21.170", "89.47.210.117", "172.217.21.166", "203.176.178.45", "172.217.21.239", "74.125.232.247", "74.125.232.233", "173.194.66.18", "74.125.232.246", "203.176.178.42", "172.217.25.99", "172.217.26.38", "216.58.200.189", "172.217.25.221", "113.171.244.89", "113.171.247.24", "113.171.242.182", "113.171.244.93", "172.217.4.97", "209.85.235.199", "209.85.234.138", "209.85.234.105", "74.125.132.189", "209.85.235.166", "172.217.4.99", "172.217.4.246", "209.85.234.199", "74.125.132.101", "209.85.234.100", "209.85.235.124", "209.85.234.194", "209.85.234.82", "173.194.67.152", "209.85.235.103", "209.85.235.201", "209.85.144.200", "172.217.5.25", "172.217.28.239", "209.85.144.98", "209.85.144.84", "173.194.66.113", "172.217.28.232", "172.217.29.4", "172.217.21.107", "172.217.21.116", "172.217.29.26", "172.217.20.225", "172.217.21.127", "172.217.28.250", "74.125.232.246", 
			"www.g.cn",
			"www.google.cn"
		]
	},
	"Site2Alias": {
		"*.appspot.com": "google_hk",
		"*.ggpht.com": "google_hk",
		"*.google-analytics.com": "google_cn",
		"*.google.cn": "google_cn",
		"*.google.com": "google_hk",
		"*.google.com.hk": "google_hk",
		"*.googleapis.com": "google_hk",
		"*.googlecode.com": "google_hk",
		"*.googlegroups.com": "google_hk",
		"*.googletagmanager.com": "google_hk",
		"*.googletagservices.com": "google_hk",
		"*.googleusercontent.com": "google_hk",
		"*.gstatic.com": "google_hk",
		// "*.youtube.com": "google_hk",
		"*.ytimg.com": "google_hk",
		"dl.google.com": "google_cn",
		"fonts.googleapis.com": "google_cn",
		"talk.google.com": "google_talk",
		"talk.l.google.com": "google_talk",
		"talkx.l.google.com": "google_talk",
	},
	"ForceHTTPS": [
		"*.google.com",
		"*.google.com.hk",
	],
	"ForceGAE": [
		"translate.googleapis.com",
		"domains.google.com",
		"www.google.com/patents",
	],
	"FakeServerNames": [
		"appleid.apple.com",
		"assets-cdn.github.com",
		"download.windowsupdate.com",
		"github.com",
		"www.apple.com",
		"www.bing.com",
		"www.microsoft.com",
		// "ad.doubleclick.net",
		// "googleads.g.doubleclick.net",
		// "pubads.g.doubleclick.net",
		// "www.google-analytics.com",
	],
	"GoogleG2KeyID": "4add06161bbcf668b576f581b6bb621aba5a812f",
	"FakeOptions": {
		"*": [
			"Access-Control-Allow-Credentials: true",
			"Access-Control-Allow-Headers: Authorization, Content-Type, If-Modified-Since, X-Act-As-User-Id, X-B3-Flags, X-Contribute-To-User-Id, X-CSRF-Token, X-Guest-Token, X-TD-Iff-Mtime, X-TD-Mtime-Check, X-Twitter-Auth-Type, X-Twitter-Client, X-Twitter-Client-Version, X-Twitter-Polling, X-Twitter-UTCOffset",
			"Access-Control-Allow-Methods: GET, POST, HEAD, PUT, DELETE",
			"Access-Control-Allow-Origin: *",
			"Access-Control-Max-Age: 1728000",
		],
	},
	"DNSServers": [
		"114.114.114.114",
		"114.114.115.115",
		"168.95.1.1",
		"168.95.192.1",
		"178.79.131.110",
		"199.91.73.222",
		"2001:470:20::2",
		"2001:4860:4860::8844",
		"2001:4860:4860::8888",
		"208.67.220.220",
		"208.67.222.222",
		"209.244.0.3",
		"209.244.0.4",
		"223.5.5.5",
		"223.6.6.6",
		"8.8.4.4",
		"8.8.8.8"
	],
	"IPBlackList": [
		"159.106.121.75",
		"203.98.7.65",
		"243.185.187.39",
		"37.61.54.158",
		"59.24.3.173",
		"46.82.174.68",
		"78.16.49.15",
		"8.7.198.45",
		"93.46.8.89",
	],
	"Transport": {
		"Dialer": {
			"DNSCacheExpiry": 864000,
			"DNSCacheSize": 81920,
			"DualStack": false,
			"KeepAlive": 180,
			"Level": 4,
			"Timeout": 8,
		},
		"DisableCompression": false,
		"DisableKeepAlives": false,
		"IdleConnTimeout": 180,
		"MaxIdleConnsPerHost": 16,
		"ResponseHeaderTimeout": 16,
		"RetryDelay": 0.5,
		"RetryTimes": 3,
	}
}


我直接拿windows的配置文件贴进去的……嗯……所以似乎真的少了点什么？

**Comment by NKUCodingCat** [comment]
啊哈我用linux自带的gae.json改完就没事了……所以这两个json还不一样咩……
嗯感谢大大～

**Comment by jzp820927** [comment]
看样纸，win 和 linux 的 json 文件确实不一样。

**Comment by NKUCodingCat** [comment]
啊我终于想起来为什么了…………
我windows下的goproxy是r595……我就没升级过……

**Comment by jzp820927** [comment]
Linux 用户表示，完全不知情。
