### ISSUE TITLE
怎么那么慢

### ISSUE THREAD

**Issue by yangchangyz** [phuslu/goproxy#839]
怎么那么慢呢？从r165-r700,越用越慢，到底是什么问题·········如果是自己电脑问题，又摸不着边？

**Comment by phuslu** [comment]
改动都在每日构建版可查，我可以说变慢不是 goproxy 软件本身的问题。

**Comment by phuslu** [comment]
怀疑的话，可以把旧版拿出来比较一下。

**Comment by yangchangyz** [comment]
@不好意思，我清楚，因为我每个版本都是新建文件夹的，可以跳来跳去的用，就是我这边也不知道什么原因！

**Comment by phuslu** [comment]
建议你扫 500 个以上的 IP，填到 gae.user.json

**Comment by yangchangyz** [comment]
为什么要填那么多，这可是从来没有的事啊，社长！

**Comment by phuslu** [comment]
你所谓“慢”的问题，是因为你填进去的 IP 段的质量目前比较慢了

因为 IP 多起来话话，它们分布的 IP 段也比较丰富，“东边不亮西边亮”。

**Comment by yangchangyz** [comment]
喔，谢谢！不过我觉得ip质量应该不错，虽然不是捞ip高手，也不像那位使用SNI代理服务器的那么厉害~那我先试试吧，再次言谢

**Comment by ylg1024** [comment]
不慢啊，社长辛苦了，我的感觉同样的Ip 比xx快多了

**Comment by jasonliul** [comment]
@phuslu 

应该是网络问题, 俺的ssh全部降速.
今天gws/force http2没有变化.

但是混用gvs, 速度下跌很明显, 俺这里跌落到<200kb/s

**Comment by phuslu** [comment]
上午电信挂了一段时间 https://twitter.com/search?q=%E7%94%B5%E4%BF%A1

**Comment by phuslu** [comment]
不过我自己之前用 MFF 扫了 1K+ 的 IP 放到了 gae.user.json 里面。
一直很开心的用到现在。运行状况一般如下图
![2016-06-10_001854](https://cloud.githubusercontent.com/assets/195836/15937313/f0879dba-2ea0-11e6-82ff-6ce9f1130e99.png)

**Comment by jasonliul** [comment]
很奇怪的网络问题, 应该与破墙无关.
俺之前的CheckGip设定的规则, 很长时间都是70几个gws.

今天再搜, 死活不过40几个.

**Comment by panpeach** [comment]
这个时段的速度，就放入十几个IP，1080还能播放。
![7](https://cloud.githubusercontent.com/assets/13916352/15938068/154aa3d8-2ea4-11e6-970c-801d312c7eec.png)

**Comment by fengixng** [comment]
我只扫描了俄罗斯GGC，扫描出来了7kIP，全部扔进gae.user.json，现在可以随时流畅使用，youtube1080P完美使用

**Comment by jzp820927** [comment]
都是牛B人物啊/

**Comment by blob2015** [comment]
@fengixng 
电信？GVS+GWS？

**Comment by masktao** [comment]
看看楼主发帖的时间,是晚上8.9点左右,楼主怎么不想想这时候洗澡,水量也会变小,每天早上晚上都这样,但是大半夜2,3点洗澡水量却很足很猛,这为啥?
慢其实是出口带宽不足导致.同样的日本韩国ip,不同时段都会慢

**Comment by liweitd** [comment]
@fengixng  俄罗斯7kIP，怎么做到的？

**Comment by hcym** [comment]
一直韩日，就是变动大

白天断的ip晚上又通了

加几个东南亚的，也行

**Comment by jasonliul** [comment]
@fengixng 

揪出来, 仇富群众要求你雁过拔毛~~
哼哼

**Comment by fengixng** [comment]
@liweitd 俄罗斯几乎全部的GGC我手里都有，有二百多个/24的段，准确说全球的GGC我现在已经找到了99%，不过因为某些原因，我并不准备开源

**Comment by fengixng** [comment]
@blob2015 联通,GVS+gws

**Comment by drg78rnvgh** [comment]
@fengixng 我就怕你一下子开源，封的严重的时候发几个钓命是最好的。

**Comment by jasonliul** [comment]
@fengixng 

好罢, 每次路过撒一把米.
不用施粥
:)

**Comment by yangchangyz** [comment]
问题已解决，是电脑问题

**Comment by yangchangyz** [comment]
社长辛苦啦
