### ISSUE TITLE
CA证书问题

### ISSUE THREAD

**Issue by weiliang1216** [phuslu/goproxy#84]
请教各位大神，

我用goproxy r152作为本地客户端，在rhc上部署了php fetch server（go 1.4.2，通过https://github.com/phuslu/fetchserver/tree/golang直接部署的），在本地也导入了CA证书。

但是Chrome访问时一直报
Your connection is not private

Attackers might be trying to steal your information from www.google.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_AUTHORITY_INVALID

感觉证书配的不对，这个应该怎么改呢？

**Comment by weiliang1216** [comment]
奇怪的是，用firefox信任证书就没有问题，貌似windows自带的就有问题，已经把root证书放到了信任列表里了

**Comment by weiliang1216** [comment]
问题已经解决了，原来自动选择不行，必须手动选择受信任的根证书颁发机构

**Comment by johnsonz** [comment]
解决了就尽量把issue close掉，不过不能像以前那样随意灌水了。

**Comment by maryjeck** [comment]
我也是这个问题，firefox没有提示，只有chrome一直提示，什么情况啊
