### ISSUE TITLE
疑似Bug：无法显示谷歌地图街景和图片

### ISSUE THREAD

**Issue by baoziwan** [phuslu/goproxy#841]
@phuslu 
r700，无法显示谷歌地图的街景和图片，一片黑。图片就是类似下图这样的谷歌地图的图片：
![default](https://cloud.githubusercontent.com/assets/18445029/15956309/3ff201b4-2f1a-11e6-9e4b-67e38d154433.PNG)
我知道是否是我个人设置的问题，还请大家一起验证一下。

**Comment by blob2015** [comment]
浏览器，系统，这样便于大家来重现，如果刚好有类似的

**Comment by baoziwan** [comment]
@blob2015 chrome和edge表现都一样，这和系统没关系吧？
补充一下：地址带hl=zh-CN是正常的，带hl=en就不正常了。奇怪。

**Comment by baoziwan** [comment]
莫名其妙地又正常了，先观察一下再说吧。

**Comment by blob2015** [comment]
好像是有，在com后面加hk就可以，cn也行，但图片不一样
com，好像是容易变成黑色无显示了

**Comment by baoziwan** [comment]
@phuslu 
补充说明一下：比如下面是同一张照片的两个网址，不同之处在于一个以“.tw”结尾，一个是.com结尾。我这边第一个网址能显示照片，第二个不行。
https://www.google.com.tw/maps/@37.289385,-113.049381,3a,75y,90t/data=!3m8!1e2!3m6!1s48020712!2e1!3e10!6s%2F%2Flh3.googleusercontent.com%2Fproxy%2FknHl6KhlYC4Cw6yCJKnO8kihPWcgitNestcmE3g0Kfg7fj6j0Zv0blssFHGC0wDX7KiiKXCQThYqOQi7tj3wdJMOknbkLg%3Dw203-h135!7i3504!8i2336?hl=zh-CN

https://www.google.com/maps/@37.289385,-113.049381,3a,75y,90t/data=!3m8!1e2!3m6!1s48020712!2e1!3e10!6s%2F%2Flh3.googleusercontent.com%2Fproxy%2FknHl6KhlYC4Cw6yCJKnO8kihPWcgitNestcmE3g0Kfg7fj6j0Zv0blssFHGC0wDX7KiiKXCQThYqOQi7tj3wdJMOknbkLg%3Dw203-h135!7i3504!8i2336?hl=en
如果把第一个地址的“.tw”去掉，就变成不显示照片；如果把第二个网址“.com”后面加上“.tw”，就可以显示照片。很奇怪。

**Comment by jasonliul** [comment]
地图需要解析
maps.google.com
maps.googleapis.com
maps.gstatic.com

你用一些hosts文件强行指定, 才会有问题

**Comment by baoziwan** [comment]
请问 @jasonliul 可以正常打开那两个网址吗？
我这边hosts是系统默认的，没有修改过。

**Comment by jasonliul** [comment]
@baoziwan 
在我这里并没有被污染.

例如
http://www.ipfingerprints.com/

直连不能显示地图.

不过在hosts强行设定可用gws, 反倒会搞得其他代理显示不正常

**Comment by baoziwan** [comment]
@jasonliul 那就奇怪了。确实没有修改hosts，你给的网址我直连的话也是不显示地图。

**Comment by jasonliul** [comment]
俺这里谷歌地图, maps.google.com. ditu.google.cn, 使用GP都正常

**Comment by yangchangyz** [comment]
报告一下，无论直连还是gp都正常

**Comment by baoziwan** [comment]
@yangchangyz 你直连就能用谷歌地图？
用虚拟机搞了一个纯净的win7，试了一下还是不行。挠头。

**Comment by MeABc** [comment]
我这两个都正常显示。
偏向 @jasonliul   说的，疑似域名污染。

**Comment by baoziwan** [comment]
感谢上面诸位的回答。
我现在有点怀疑是IP的问题，接下来再观察一下看看。
