### ISSUE TITLE
win10睡眠唤醒问题

### ISSUE THREAD

**Issue by yangchangyz** [phuslu/goproxy#845]
最近几个版本在睡眠后唤醒很长时间无法恢复，日志里都是红黄字，以前较低版本时是不会@win10 64位。望修复，辛苦了，致谢！

**Comment by phuslu** [comment]
不能复现。不过可能和 https://github.com/phuslu/goproxy/issues/829 有关。

楼主你给的信息太少，我不能推测出什么有用的信息。

**Comment by yangchangyz** [comment]
![15](https://cloud.githubusercontent.com/assets/7754426/15984882/11d6b5a6-300d-11e6-9fd9-966bf4c2c2af.png)
![16](https://cloud.githubusercontent.com/assets/7754426/15984883/1bec45a6-300d-11e6-868e-b92ff35fd66c.png)

**Comment by phuslu** [comment]
看不出是因为最近版本的改动导致的异常，你现在切到旧版试试呢？

**Comment by yangchangyz** [comment]
![17](https://cloud.githubusercontent.com/assets/7754426/15984965/86e8b162-300f-11e6-8f9c-c5e4d9850a66.png)

**Comment by yangchangyz** [comment]
r540恢复很快，日志马上开始滚动

**Comment by yangchangyz** [comment]
这都是睡眠后唤醒时日志

**Comment by yangchangyz** [comment]
r702红黄很长分两次

**Comment by phuslu** [comment]
r695 是否有这个问题？

**Comment by yangchangyz** [comment]
我试一下

**Comment by yangchangyz** [comment]
R695因为自己嫌版本太多删掉了，您选择另一个吧

**Comment by phuslu** [comment]
我这边不能复现，不好定位啊，因为 r695 是关键版本，不然不能确定是那个改动导致的。

**Comment by yangchangyz** [comment]
那我重新下载，有必要吗？前天把很全面的版本和变化不大的版本删除

**Comment by yangchangyz** [comment]
![18](https://cloud.githubusercontent.com/assets/7754426/15985105/28d7b25c-3015-11e6-9d9a-e79321eca1f2.png)
R965正常

**Comment by phuslu** [comment]
呃，你是说 r695 吧。谢谢反馈，看来的确是和 r966 改动有关了。

我来看下。

**Comment by yangchangyz** [comment]
很抱歉，上次反馈速度慢是因为chrome此问题啦，我就知道是自己的问题，现在的chrome因为应用，扩展多，变得又笨又胖，不再是以前的轻巧，出问题了都不知道，卸载重装ok，1080p有余

**Comment by phuslu** [comment]
r706 已经修复

**Comment by yangchangyz** [comment]
谢谢

**Comment by phuslu** [comment]
也谢谢反馈，等 r706 每日构建版完成后，我把它也作为正式版发布。
