### ISSUE TITLE
电信, 移动, 联通... 手淫各有妙招

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#849]
&. 电信   **自撸[关闭出口]?**

俺肯定各地都不同, 没有所谓"电信好IP"的说法.
这里电信从16:00-凌晨1:00 是手淫状态.

很容易检查, Get File Size
http://www.browsertools.net/downloads/GetFileSizeSetup.exe

检查火锅播放器, 几乎每个工作日都更新.
http://117.52.4.235/beta/PotPlayerSetup.exe

白天可以下载最新版, 夜间直接下载, 反倒是几天前的.

到了手淫时段, 你输入的国外下载地址, 会自动加上跳转, 强制你从国内固定ip下载. 此前仅仅铁通, 网通, 以及一些有线电视的所谓宽带是这样. 也就是假宽带.

夜间检查GP的可用ip, 日韩台菲几乎消失, 清一色东南亚, 俄国.
俺怀疑夜间电信关闭了一些国际出口, 特别是沿海那些. 强制用户使用内陆出口, 人为造成塞车. 这也许能够解释为何日韩ip夜间疲软, 因为是从喜马拉雅山出的国际出口, 绕回来再用日韩.

不存在所谓干扰, 任何占用太多国际带宽的用户, 都会到一定时间就挂断你这刁民, 所以无所谓检测你是否用代理, 用什么代理.

&.移动 **自抠[关闭服务器]?**

俺以为会更好, 其实跟电信差不多. 不过移动没有假宽带的搞法. 

但是移动夜间, 更像选择性连接国外. 俺的ssh节点, 基本等于随机国外ip, 
突然就瘟鸡了, Ping值, 丢包率增加不少.
稳定性还不如电信.

直接检查一堆随机国外ip, ping值大大高于电信.
不管哪种代理, 其实测速没有问题, 但是速度的提升就....老太爬山, 一步三颠.

移动俺用得很少, 总归怀疑夜间是故意关闭部分服务器, 造成响应迟缓,拖慢服务速度.造成高丢包率,移动只是有时通.

&. 联通 **见花早泄[好歹有点料]**

果然好, 不过装联通太麻烦. 近些年电信移动扩张, 连工业区都不再是联通的地盘.

**Comment by jzp820927** [comment]
分析的很不错，电信应该是最垃圾的

**Comment by lsnmx** [comment]
前置代理加上，一了百了，社长都不加啊

**Comment by jasonliul** [comment]
@lsnmx 

本来就能用, 自己去玩

帽架 [自选一种即可]
Proxifier
https://www.proxifier.com/download.htm
ProxyCap
http://www.proxycap.com/download.html
SocksCap64
https://sourceforge.net/projects/sockscap64/files/

**Comment by jzp820927** [comment]
@lsnmx 我能说，社长一直在处理 aoturange 有1，2个月了嘛，已经完成一半了，估计你得等到 7，8月以后，社长才有可能考虑其他问题。

**Comment by jasonliul** [comment]
@jzp820927 
鬼扯

Linux 类
**RedSocks 红袜, 超经典**
http://darkk.net.ru/redsocks/

**Proxychains 代理链条,超经典**
http://proxychains.sourceforge.net/

tsocks
http://tsocks.sourceforge.net/download.php

Proximac 
http://proximac.org/

MacProxy 
http://www.tidalpool.ca/macproxy/

SSH
http://codinn.com/products/ssh-proxy/


安卓
Postern 
http://tunnel-workshop.com/home.html

SSH [使用红袜]
https://code.google.com/archive/p/sshtunnel/downloads

**Comment by blob2015** [comment]
上个网都这么难……

**Comment by jzp820927** [comment]
以前弄过 RedSocks ，没弄成功，后来就没弄了。Proxychains 也弄过，兼容性不是太好，好多代理都弄不了，当时就 goa 弄成功了，不过后来在另一台机子弄的时候，又不行了。

**Comment by jasonliul** [comment]
@jzp820927 
Linux下面, 程序开发积极还是红帽子,雪山时代.
后来就很少了.

经融危机过后的萧条, 对于整个自由开源免费软件, 都是灾难. 而linux类本来就依赖这些软件

**Comment by jzp820927** [comment]
你上面说的，我用过的，也就 RedSocks，Proxychains，tsocks (SSH，家喻户晓，就不说了)
这3软件好像也好多年没更新过了。

**Comment by jasonliul** [comment]
@jzp820927 
免费软件, 总体上, 多数作者已经放弃.
少量改为收费.

**Comment by lsnmx** [comment]
@jasonliul GP有前置代理 ？别无忧人，你发的哪玩意没用

**Comment by jasonliul** [comment]
![333](https://cloud.githubusercontent.com/assets/2461165/16066475/37636c48-32e6-11e6-863c-5edae5f88f39.png)

无能不要怪兵器. :)

SocksCap64 随意中国ip的袜子
这下忽悠到测速网站了, 俺只有4M带宽

**Comment by jasonliul** [comment]
直接用GP只是正常值
![22](https://cloud.githubusercontent.com/assets/2461165/16066622/7ee58faa-32e7-11e6-90b8-879a1822ed43.png)

**Comment by jzp820927** [comment]
上面那个测速，不会是袜子的带宽速度吧？

**Comment by jasonliul** [comment]
@jzp820927 
当然是袜子本身的速度, 不是俺的.
不过俺相对还是沾光, 速度更饱满.

国内通常吹嘘成加速器. :)

**Comment by jzp820927** [comment]
你这提速也太明显了。空了，俺也试试

**Comment by jasonliul** [comment]
@jzp820927 
这个链路, 前端袜子比后端客户快, 本质就是填鸭.
并不能真正提速多少.

但是例如俺的可压缩ssh节点, 就会很有必要.
能够保证实际上800-900k/s

**Comment by blob2015** [comment]
鱼哥真是会折腾，有活力 :wine_glass:

**Comment by jzp820927** [comment]
至少可以保持稳定性吧，可以保证满带宽吧，我家里是 10M 带宽，晚上 ytb 才 300 kbps，才实际带宽的 百分之几。

**Comment by jasonliul** [comment]
@jzp820927 
你可以试试, 今年中国ip的袜子稳定性很好.

不过socks4的检测度很低, 因为没有真正流行过, 很多代理评估网站不予理睬. 流行的代理检测工具没有太大作用.

需要Proxy Checker.
https://www.proxifier.com/proxychecker/
而且平时需要收集.

**Comment by jzp820927** [comment]
恩，这个工具以前看到过你的介绍。你之前分享的国产袜子，现在都还能用麽？
