### ISSUE TITLE
main.json中的roundtrip的问题

### ISSUE THREAD

**Issue by weiliang1216** [phuslu/goproxy#85]
"roundtrip": [
			"autoproxy",
			// "auth",
			// "iplist",
			// "vps",
			"php",
			// "gae",
			"direct"
		],
1. 这里面的这些模式有优先级么？是不是排越前面的优先级越高，前面的timeout才走后面的？

2. 如果我有2个php fetch server，是不是只要在里面加一个php2，然后创建一个php2.json就可以了？

3. 有没有办法把这些个模式做成并行访问（通过输出，感觉这些模式是串行的），哪个先返回就走哪条路，不过不知道在session上会不会有问题

最后弱弱的问iplist和gae是不是要开就一起开，似乎单独一个无法工作。

求大神指教

**Comment by ARwMq9b6** [comment]
+ 排越前面的优先级越高
+ 定义多个 php server 的格式：

	```json
	{
		"fetchservers": [
			{
				"url": "php_server_1",
				"url": "php_server_2",
				"url": "php_server_3",
				"password": "123456",
				"sslverify": false
			}
		],
		"sites": [
			"*"
		],
		"transport": "direct"
	}
	```

**Comment by weiliang1216** [comment]
@ARwMq9b6，感谢
顺便问一下GAE和iplist是个什么关系，感觉这两个都是原来Goagent的组成部分

**Comment by Kisesy** [comment]
"fetchservers": [
		{
			"url": "php_server_1",
			"password": "123456",
			"sslverify": false
		},
		{
			"url": "php_server_2",
			"password": "123456",
			"sslverify": false
		},
               {
			"url": "php_server_3",
			"password": "123456",
			"sslverify": false
		}
	],

多个服务器是这样定义的,如果按ARwMq9b6那样只会使用最后一个服务器

**Comment by ARwMq9b6** [comment]
@Kisesy 多谢指正。嘿嘿，丢人啊。

**Comment by ARwMq9b6** [comment]
@weiliang1216 不知道 gae 和 iplist 的关系，无地自容中。

**Comment by weiliang1216** [comment]
@ARwMq9b6 了解了
@Kisesy 多个服务器是不是也是按照先后顺序定义优先级的？Timeout的时间是多少，可以设定么？

**Comment by Kisesy** [comment]
我对这个不了解，这个得测试一下或者看一下源码
https://github.com/phuslu/goproxy/blob/master/httpproxy/filters/php/php.go
看这里应该是遇到某些后缀结尾的就会随机，例如视频和图片格式
遇到某些域名也会随机。。。可能吧。。。 我不会 Go 语言

**Comment by johnsonz** [comment]
看了源码 ，应该和@Kisesy说的差不多。

>1、如果请求的url地址扩展名是图片或者视频，随机选一个php服务器

>2、如果请求的url地址扩展名为空，就取url的最后一个元素，如果是“play”或者“video”，就随机选一个php服务器

>3、如果主机名中包含静态文件或缓存之类的，就随机选一个php服务器

否则就默认选取第一个
