### ISSUE TITLE
pac问题

### ISSUE THREAD

**Issue by yangchangyz** [phuslu/goproxy#851]
测试了windows下的lE、EDGE、CHROME三个浏览器的Pac代理，ie chrome设问题，edge的谷歌搜索结果不正常，把搜索结果链接当成不安全链接阻挡了，电脑方面似乎也没有办法绕过此过滤(其他搜索引擎可以，实际上全局代理也一样)。

**Comment by johnsonz** [comment]
我这正常，你是不是又上<font color="#FFFF00">huang</font >网了

**Comment by yangchangyz** [comment]
不是，是谷歌搜索页，您确定吗

**Comment by yangchangyz** [comment]
![22](https://cloud.githubusercontent.com/assets/7754426/16003043/5f67e76e-318d-11e6-9c70-c6db26482af5.png)
![23](https://cloud.githubusercontent.com/assets/7754426/16003067/7895657c-318d-11e6-873d-081bfed24152.png)
![24](https://cloud.githubusercontent.com/assets/7754426/16003075/7d5220fa-318d-11e6-804b-3f571afd0948.png)

**Comment by yangchangyz** [comment]
怎么破？

**Comment by yangchangyz** [comment]
这是gp的问题,比对了xx,ok

**Comment by johnsonz** [comment]
还是正常，你肯定又上huang网了

**Comment by yangchangyz** [comment]
@johnsonz 别开玩笑啦

**Comment by yangchangyz** [comment]
@johnsonz ，你有毛病啊，也没看到，是谷歌搜索页，搜索词哈哈大笑！

**Comment by blob2015** [comment]
@johnsonz 
john还是挺好的人……
人家跟你开个玩笑罢了……或者打趣一下……
