### ISSUE TITLE
现在还能上传goagent 3.11的appid吗？

### ISSUE THREAD

**Issue by jyuan15** [phuslu/goproxy#852]
手机上有个改版的安卓gae，一直能用（只能用gws的ip），用来刷g+和y2b，速度比什么ss、vpn之类的快多了。但最高只支持到3.1.1服务端。

当时我特意保留了大概4、5个appid停留在3.1.1，一直未升级。前两天在弄goproxy的时候，一时间忘了，就把这几个appid给上传了，现在手机端gae无法使用。

我试着重新用3.1.1上传，结果跳了几段字符就提示“按任意键继续”，然后就退出了。

我想问问现在究竟还能用goagent 3.1.1上传吗？

**Comment by yangchangyz** [comment]
可以啊，上个月上传24个，goa、xx、xx-mini通用

**Comment by lifly** [comment]
你还有goagent 3.1.1服务器端.可以试试
下载新的https://github.com/phuslu/goproxy/archive/server.gae.zip
把里面的gae文件夹,换成3.1.1服务器端再上传

**Comment by jzp820927** [comment]
确实 XXNET 的服务端就可以用于 goa 的 3 的所有版本

**Comment by jyuan15** [comment]
记错了，作者当时说最高是支持到3.1.11，但实际测试到3.1.13也可以，再高就不行了。

**Comment by jyuan15** [comment]
@lifly 多谢，等回家时试试～
