### ISSUE TITLE
新狗健康得没有话题

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#856]
![333](https://cloud.githubusercontent.com/assets/2461165/16036010/8d5d2192-324c-11e6-8645-9acfcf50ccf8.png)

狗儿一直在成长~~
4M对于欧洲标准, 还不算宽带. >5M才是

**Comment by caofengzi** [comment]
的確厲害，這是打開視頻一分鐘的結果。
![fireshot screen capture 002 - f16 _ 20160122-6 - youtube - www_youtube_com_watch_v 5dk-0gpl0](https://cloud.githubusercontent.com/assets/13650252/16036186/5a550a8e-324d-11e6-8425-6efa28accccb.png)

**Comment by jasonliul** [comment]
@caofengzi 

俺现在与时俱进, 接受社长训诫.
HK 12枚/CN 12枚 

俺也增兵, 预防折损兵员. LOL
现在的稳定程度大大高于从前, 特别是切换到下一视频的时候.

**Comment by yangchangyz** [comment]
现在gp对gvslP支持己经趋于完美了，我放了57个ip只有四五个gws的其它都是gvs，速度和状态远超楼上，当然我的宽带比你们快多了

**Comment by jzp820927** [comment]
我觉得你们应该晚上黄金时间测试，白天没什么可比性，白天本来就没啥干扰，上网的人也少，国际带宽充足的很。晚上好，才是真的好！

**Comment by blob2015** [comment]
俺从来在200-300k挣扎，给你们垫底 :grinning: 
看个视频，好的时候也就360 :grinning:

**Comment by caofengzi** [comment]
俺很少看視頻的，這個就是測試一下。
![emoji_u1f60a](https://cloud.githubusercontent.com/assets/13650252/16040961/7804609e-3265-11e6-99c2-528e5eda55bf.png)

**Comment by jzp820927** [comment]
我这儿白天，凌晨2点以后，5000+ kbps 没问题，晚上直接降到 500 kbps 以下。

**Comment by erichau** [comment]
![1](https://cloud.githubusercontent.com/assets/13231607/16045307/6df1fa0c-327a-11e6-8a52-ef61a6050f1f.jpg)
刚刚测的，垃圾电信网

**Comment by darkwolf99** [comment]
我只是来围观高速达人的

**Comment by drg78rnvgh** [comment]
@erichau 
这个已经左胶化，看myradio吧

**Comment by jzp820927** [comment]
@erichau 电信网，网上能到这个速度已经很不错了，我这儿晚上绝对不超过 500 kbps，不管用什么IP都一样。

**Comment by drg78rnvgh** [comment]
@jzp820927 
你应该测一下下载速度，下载速度正常那就是你的配置在作怪。

**Comment by jzp820927** [comment]
我是 10M带宽，迅雷下载，稳定在 1Mbps，配置就只改了 IP ，和 APPID，其他也没改什么，而且我相同的配置 凌晨，和白天，就能上到 5000 kbps

**Comment by drg78rnvgh** [comment]
@jzp820927 
建议手动加 "*.googlevideo.com",到autorange.json 
BufSize、Threads调大
如果还是不行，既然你有稳定的1m下载，我要是你就会添加"*.clipconverter.cc",
YouTube直接下载了看

**Comment by jzp820927** [comment]
其他办法我倒是晓得，我只是想把问题搞问题，究竟问题出在哪儿，是在 gp 上，还是 gfw ，还是 isp

**Comment by jasonliul** [comment]
@drg78rnvgh 
果然诡计百出

**Comment by blob2015** [comment]
drg也好强大

**Comment by xrwz007** [comment]
@drg78rnvgh 請問手動添加：“gv.com"到auto.json這一步怎麼實現？

**Comment by carotin** [comment]
@xrwz007 
"Sites": [
		
                "*.googlevideo.com",
	],

**Comment by xrwz007** [comment]
@carotin 感謝樓上

**Comment by jzp820927** [comment]
等 P 大把 autorange 做完善了，再试试吧。
现在开启 autorange 和没开启，没啥区别。

**Comment by lazureice** [comment]
@jasonliul CN也需要填IP吗？我试了一下HK12, CN8，good ip只有12.不是只有HK吗？
