### ISSUE TITLE
关于Zeronet

### ISSUE THREAD

**Issue by YoungPix** [phuslu/goproxy#861]
社长，最近才发现有zeronet这种东西。有没有考虑把项目迁移复制到到zeronet上？zeronet的安全性及隐匿性如何？

**Comment by jap33** [comment]
ssr现在就用这东西把好多人挡在外面，还是这样好。

**Comment by cannanlly** [comment]
这个东西并不是代码托管网站，比较适合搭建个人网站，而且有很高暴露ip的风险
