### ISSUE TITLE
gae.json 的 ipv6 dns 配置有问题

### ISSUE THREAD

**Issue by azzvx** [phuslu/goproxy#864]
比如使用[2001:470:20::2]作为首要dns的时候，会出现下列错误：
`W0616 08:56:18.734703   12844 multidialer.go:137] LookupHost2("mail.google.com", net.IP{0x20, 0x1, 0x4, 0x70, 0x0, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2}) error: dial udp: too many colons in address 2001:470:20::2:53
I0616 08:56:18.746709   12844 multidialer.go:148] LookupHost("mail.google.com") return []`
很明显最后的端口":53"被当成了ip的一部分。

在gae.json中在ipv6的dns左右加上方括号后问题解决，如："2001:470:20::2", 改成 "**[**2001:470:20::2**]**".

**Comment by cannanlly** [comment]
楼主最近都不更新gogotester了。。。。。。。

**Comment by jasonliul** [comment]
@azzvx 

雁过拔毛, 大大留下新版再走~

**Comment by phuslu** [comment]
谢谢反馈，久违了。

r702 已经修复了
