### ISSUE TITLE
goproxy 是不是 依旧不能上传YOUTUBE 

### ISSUE THREAD

**Issue by gnehcforever** [phuslu/goproxy#868]
goproxy 是不是 依旧不能上传YOUTUBE ,如题，上一次传一个视频到 YouTube，挂了 vpngate，将近一天时间，vpngate 非常不稳定，一会就断线了， 国内上传YouTube  可是一个老大难！！！

**Comment by jzp820927** [comment]
vpngate 不是不稳定，是被 协议识别，会被主动强制断开。所以能连上时间不上，能连上10分钟以上，估计都很难得了。如果不能通过 GAE 上传视频到 youtube，你也可以先上传视频到 google photos，然后再从 photos 转到 youtube

**Comment by phuslu** [comment]
如果 IP 质量比较稳定，可以正常上传。

**Comment by gnehcforever** [comment]
@phuslu   老大， 是么？  我去试试，白天200多GOOD IP , 晚上就几十个，我也是醉了

**Comment by yeahwu** [comment]
实在不能上传的话，把youtube改为直连，应该就没问题了

**Comment by gnehcforever** [comment]
@yeahwu  直连 不就挂了么？    不明白您意思，愿闻其详！

**Comment by yeahwu** [comment]
goproxy/gae.json
```
	// "*.youtube.com": "google_hk",
```
这一行前面的双斜杠去掉

**Comment by Hongnanjing** [comment]
@gnehcforever 想稳定上传视频，修改hosts比较稳定如https://github.com/cnAnonymous/hosts

**Comment by yeahwu** [comment]
道理是一样的，直连就是hosts

**Comment by gnehcforever** [comment]
谢谢 2位  仁兄，我去试试！

**Comment by gnehcforever** [comment]
@yeahwu  谢谢你，可以上传了，不过改了之后，还需不需要再次改回来呢？  gae.user.json  这个里面我没有修改，只是按照你说的 改了  gae.json ，可以上传了， P 大 说的质量好的稳定IP ，我也不知道我扫面的里面有没有， 只是没改之前， 一直停留在 0%，  现在可以了。

![33](https://cloud.githubusercontent.com/assets/17717504/16113487/f40b6478-33ee-11e6-8bc7-9a47ce65af83.png)

**Comment by phuslu** [comment]
你用的是那个版本？目前的正式版应该不用修改配置就能上传的。

**Comment by gnehcforever** [comment]
@phuslu   老大，看这里

![88](https://cloud.githubusercontent.com/assets/17717504/16114016/ad5549ba-33f1-11e6-9ac6-eea032396426.png)

**Comment by phuslu** [comment]
太老了，要 r702 版本以上 https://github.com/phuslu/goproxy-ci/releases/tag/r707

**Comment by gnehcforever** [comment]
⊙﹏⊙b汗，听指挥，我去更新！

**Comment by jzp820927** [comment]
跟着P大走，吃香的，喝辣的
