### ISSUE TITLE
goproxy无法访问卡提諾論壇 CK101.COM

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#872]
goproxy r713 访问卡提諾論壇 CK101.COM显示

403 Forbidden

You don't have permission to access the URL on this server. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

URL:	http://ck101.com/
Server:	www5.ck101.com
Date:	2016/06/16 
Powered by Tengine

**Comment by Kisesy** [comment]
以前好像有人说过这个，应该是屏蔽GAE类代理
往 autoproxy.json 添 "ck101.com": "php", 走php解决

**Comment by jzp820927** [comment]
这个是屏蔽 GAE 的网站

**Comment by masktao** [comment]
其实这个网站,用自由门或者赛风
