### ISSUE TITLE
社长，希望ServerName能够可以填IP，最好能支持多IP，现在ServerName成了性能瓶颈

### ISSUE THREAD

**Issue by tomb003** [phuslu/goproxy#875]
现在ServerName只能填域名，不够灵活，要是能填IP就好了。
另外，HostMap中可以填多IP，而ServerName只支持单IP，现在是多对一，结果ServerName成了性能瓶颈，要是ServerName能像HostMap一样支持多IP，就变成了多对多，速度应该可以大幅提升。

**Comment by phuslu** [comment]
实现不了。https://en.wikipedia.org/wiki/Server_Name_Indication
