### ISSUE TITLE
403  error     大神们， 帮帮忙吧！！！

### ISSUE THREAD

**Issue by gnehcforever** [phuslu/goproxy#883]
我用谷歌 新加坡搜索，有时候出现403 错误几率还是蛮高的。  可是直接输入网址， 就可以进入，

不知道是什么原因？  大神们， 帮帮忙吧！！！

![qq 20160618211457](https://cloud.githubusercontent.com/assets/17717504/16171128/5ceb3408-359a-11e6-9e89-f2252b983239.png)

**Comment by gnehcforever** [comment]
https://www.google.com.sg/  

 这个网址可以进去， 就是搜索时候，403 了，郁闷

**Comment by sishentibu** [comment]
可以用。试试更换ip

**Comment by gnehcforever** [comment]
@sishentibu   400+  IP , 如何更换呢？  ⊙﹏⊙b汗

**Comment by sishentibu** [comment]
挑几个ip试试。忘记上次是怎么处理的了
或者更新到最新版试试

**Comment by phuslu** [comment]
r732 应该修复了，请尝试。

**Comment by blob2015** [comment]
mark。这个，俺也经常出现。

**Comment by carotin** [comment]
"Site2Alias": {
          "*.google.com.sg/": "google_hk",
},

**Comment by gnehcforever** [comment]
@carotin   我是2个文件夹都改了，  首先改了gae.json， 测试发现问题依旧403，  继而改了gae.user.json， 问题依旧403.   

![qq 20160619091736](https://cloud.githubusercontent.com/assets/17717504/16174665/43d9377a-35ff-11e6-9eca-f19463e711bb.png)
![qq 20160619091721](https://cloud.githubusercontent.com/assets/17717504/16174666/43e1b2ba-35ff-11e6-80f3-941f2971cefa.png)

**Comment by caofengzi** [comment]
可以搜索這是截圖。
![2016-06-19_105454](https://cloud.githubusercontent.com/assets/13650252/16174902/a26b5450-360c-11e6-840f-0c2e3858f42c.png)

**Comment by gnehcforever** [comment]
有这样的403几率出现，我改了就 NG

**Comment by jzp820927** [comment]
@gnehcforever
![image](https://cloud.githubusercontent.com/assets/5740066/16175004/2ad2ace0-3611-11e6-86ec-38e21b8f214d.png)
大哥，你 sg 后面多了个 /

**Comment by gnehcforever** [comment]
@jzp820927    好了，给你点个赞！ O(∩_∩)O哈哈~
