### ISSUE TITLE
咨询一下autoproxy.json是否支持通配符配置

### ISSUE THREAD

**Issue by playnetcn** [phuslu/goproxy#884]
下面这段是否支持通配符配置
	"SiteFilters": {
		"Enabled": false,
		"Rules": {
			"live.github.com": "direct",
			"rarbg.to": "direct",
			"www.slideshare.net": "php",
		},
改成 “*.ltn.com.tw": "php",这种配法，只要是符合这种的都可以走php

**Comment by phuslu** [comment]
支持。

**Comment by carotin** [comment]
"Enabled": true,

**Comment by playnetcn** [comment]
@phuslu @carotin  OK,感谢
