### ISSUE TITLE
求助，只能打开google，打开其他网页时是以下信息

### ISSUE THREAD

**Issue by hangwoor** [phuslu/goproxy#886]
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "go/devel +c0cb0f1 Sat Jun 18 03:24:39 2016 +0000 windows/amd64",
    "filter": "*gae.Filter",
    "error": "unexpected EOF"
}

**Comment by caofengzi** [comment]
點擊刷新。

**Comment by hangwoor** [comment]
谢谢
