### ISSUE TITLE
r738 error:unexpected eof,why?

### ISSUE THREAD

**Issue by ghq200101** [phuslu/goproxy#890]
GoProxy Version    : r738 (go/devel+0130907 windows/386)
GoProxy Profile    : Default
Listen Address     : 127.0.0.1:8087
Enabled Filters    : stripssl,autorange|autoproxy,gae,direct|autorange
Pac Server         : http://127.0.0.1:8087/proxy.pac
------------------------------------------------------
I0620 13:28:54.453125    9780 autoproxy.go:399] start updater for https://raw.gi
thubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt, expiry=24h0m0s, duration
=1h0m0s
I0620 13:28:55.390625    9780 httpproxy.go:82] ListenAndServe("Default") on 127.
0.0.1:8087
I0620 13:29:01.640625    9780 multidialer.go:231] MULTIDIALER DialTLS2("tcp", "c
lients3.google.com:443") with good_addrs=0, bad_addrs=0
I0620 13:29:02.687500    9780 gae.go:300] GAE EnableDeadProbe "GET https://clien
ts3.google.com/generate_204" error: unexpected EOF
I0620 13:29:12.687500    9780 multidialer.go:231] MULTIDIALER DialTLS2("tcp", "c
lients3.google.com:443") with good_addrs=3, bad_addrs=1
I0620 13:29:13.468750    9780 gae.go:300] GAE EnableDeadProbe "GET https://clien
ts3.google.com/generate_204" error: unexpected EOF
I0620 13:29:22.468750    9780 multidialer.go:231] MULTIDIALER DialTLS2("tcp", "c
lients3.google.com:443") with good_addrs=4, bad_addrs=2
I0620 13:29:22.625000    9780 gae.go:300] GAE EnableDeadProbe "GET https://clien
ts3.google.com/generate_204" error: unexpected EOF
I0620 13:29:32.625000    9780 multidialer.go:231] MULTIDIALER DialTLS2("tcp", "c
lients3.google.com:443") with good_addrs=6, bad_addrs=2
I0620 13:29:32.750000    9780 gae.go:300] GAE EnableDeadProbe "GET https://clien
ts3.google.com/generate_204" error: unexpected EOF
I0620 13:29:40.750000    9780 multidialer.go:231] MULTIDIALER DialTLS2("tcp", "c
lients3.google.com:443") with good_addrs=8, bad_addrs=2
I0620 13:29:55.906250    9780 gae.go:300] GAE EnableDeadProbe "GET https://clien
ts3.google.com/generate_204" error: context deadline exceeded

**Comment by ghq200101** [comment]
![image](https://cloud.githubusercontent.com/assets/9986859/16184493/58b8ea14-36ef-11e6-8d43-b84c87a866bd.png)

**Comment by caofengzi** [comment]
刷新一下頁面。

**Comment by github-xx** [comment]
一般是gae.user.json修改有问题，我换了个原始的gat.json就好了
