### ISSUE TITLE
741, 社长, http2萎了

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#891]
很奇怪, 取消这个很容易满速.
启用的话, 只有100kb/s左右

**Comment by jzp820927** [comment]
这真是一个噩耗。

**Comment by phuslu** [comment]
貌似 google 服务器在调整，我先关了http 2再继续观察。

**Comment by fuckGFW2015** [comment]
![2016-06-20 19 34 58](https://cloud.githubusercontent.com/assets/10451070/16192888/6dd9eebe-371e-11e6-8d43-caeb6adfb0a4.jpg)
![2016-06-20 19 43 55](https://cloud.githubusercontent.com/assets/10451070/16193051/761c0bf6-371f-11e6-85d6-6275e870be8e.jpg)

720P可以流畅播放，速度上没发现什么异常

**Comment by jzp820927** [comment]
看来又是区域性差异

**Comment by phuslu** [comment]
暂时在 r742 关闭 http2 了，继续观察。

**Comment by hcym** [comment]
没有gws不会下仔

其他没发现什么异常

**Comment by jasonliul** [comment]
@phuslu 
今年谷歌的动作也蛮多...
唔

**Comment by MeABc** [comment]
报告老大，强制H2，效果很好。

![2016-06-20_230152](https://cloud.githubusercontent.com/assets/18194126/16199973/2567d3e2-373e-11e6-96b0-7def6785c51b.png)

**Comment by jasonliul** [comment]
@MeABc 
果然已经恢复.

新服务端, r743, 已经正常.
今天这是社长开发http2以来唯一一次抽风.
