### ISSUE TITLE
老大，发现一个问题

### ISSUE THREAD

**Issue by MeABc** [phuslu/goproxy#893]
发现一个问题，先上图，再作说明

![2016-06-20_231334](https://cloud.githubusercontent.com/assets/18194126/16200213/f36f1b1a-373e-11e6-9f2f-2f4f2b64e173.png)

如图，已确认 IP 不能用，但连接没有即时关闭。当然，最后是关闭了，有5分钟之久（没算时间，猜的），难道这关闭连接在“心跳”逻辑里？

IP 是 google 官方IP ，再次验证了老大说的 google 在调整 服务器。

**Comment by fengixng** [comment]
左图你使用的是什么软件啊

**Comment by phuslu** [comment]
是的，和心跳有关。目前还不能做到即时关闭，接下来会改进。

**Comment by phuslu** [comment]
需要对 go 标准库做些修改，已完成 net/http 部分。https://github.com/phuslu/go/commit/b01a658c558c9482f078daf8d6bc8b76dd446688
还需要 x/net/http2 部分。

**Comment by yuan18** [comment]
lz，你的左边那张图是怎么隆出来的？

**Comment by MeABc** [comment]
@phuslu  老大辛苦了！

@fengixng @yuan18  左图软件是 [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653)

**Comment by jasonliul** [comment]
Process Explorer, MS工具箱最有名的一个

**Comment by phuslu** [comment]
r753 应该已经修复。

**Comment by MeABc** [comment]
@phuslu 老大辛苦了！
