### ISSUE TITLE
自动换App id后无法使用

### ISSUE THREAD

**Issue by Kashgar-Castle** [phuslu/goproxy#894]
以前没试过在gae.user.json填写多个App id，今天第一个id流量用完，就试了一下。虽然可以自动跳转到下一个id，但是接下来访问各个网站都非常费劲，页面基本无法显示，永远在载入中。访问google搜索结果页面倒没什么问题。把下一个id放到另一个Goproxy文件夹的gae.user.json里独立使用，就一切正常。

我填写的格式，就是按照在别的帖子里看到的那样填的：
"AppIDs": [
"appid1","appid2","appid3"
],

请问问题出在哪里？

**Comment by cnrip** [comment]
一个ID一行吧

**Comment by jzp820927** [comment]
格式没啥问题，是不是是不是 gp 的 BUG，等 P 大来回复吧

**Comment by phuslu** [comment]
不能复现，升级到最新版本试试。

**Comment by blob2015** [comment]
最新版本？

**Comment by Kashgar-Castle** [comment]
今天又是同样的状况，日志是这样：

http://notepad.pw/share/6wwqyuxm

能否帮我看一下？谢谢。 @phuslu

**Comment by wenliyang** [comment]
目前最新版是r841，楼主升级再试
https://github.com/phuslu/goproxy/releases

**Comment by Kashgar-Castle** [comment]
这种一个App id不够用的情况在我这儿几周才出现一次，往往几个小时后就消失，因为第二天到了，App id重新计量了，我这儿也很难复现。

**Comment by MeABc** [comment]
我今天刚好有碰到和楼主类似的情况，可能楼主说的也是这个情况。但这不是什么大事，等一会儿刷新一下就好了。上图：
![get over quota](https://cloud.githubusercontent.com/assets/18194126/17083910/c77f7aa6-51e0-11e6-8531-842cb787cc13.png)

1. 如果你刚好碰到  over quota ，这时你又同是打开几个网页（看上图时间 xx:26:10 -- xx:26:11），那么这几个网会同时卡住。
2. 如果这时你在很短时间内再打开网页（看上图时间 xx:26:36），那么这个网页也会卡住。

综上总结：
并不是不会自动换 AppID ，而是在很短的时间内，打开的网页不会换 AppID，但这不是什么大事，等一会儿刷新一下就好了。

**Comment by blob2015** [comment]
@MeABc 
花得这么干净啊。
@phuslu 
在90%时候就转移？

**Comment by Kisesy** [comment]
在ToggleBadAppID函数中，有两次lock，很奇怪，不知道跟这个有没有关系
