### ISSUE TITLE
goproxy卡死的问题

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#899]
r731，win7
最小化输出窗口到任务栏上，看谷歌街景等大流量网的时候，很容易出现goproxy窗口卡死在任务栏里，用鼠标怎么点都没有反应。
这时必须右健通知栏图标隐藏-显示，才能回复正常
一天中最多遇到两次

**Comment by phuslu** [comment]
可能是 log 输出太频繁导致。我观察一下。

ps: 请尝试设置较大的屏幕缓冲区，如下图所示，看是否缓解。

![2016-06-22_010414](https://cloud.githubusercontent.com/assets/195836/16238960/4703d352-3815-11e6-93e1-470a150837f8.png)

**Comment by cnrip** [comment]
估计跟我说的差不多,随便复制下就能好.
