### ISSUE TITLE
配置json能不能合并在一个文件里？

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#9]
如题，感谢！

**Comment by phuslu** [comment]
设计上有意分开的。不同于 goagent 的实现， goproxy 的代码是真正高性能并且生产可用的。

所以配置做了两点改变：
1. 使用 json, 更严格的语法可以保证正确性
2. 使用多配置文件，每一个插件(filter)单独的配置文件，架构上更加灵活。

当然这些改动导致对最终用户不太友好，我还在琢磨如何改进。

初步打算是给所有 json 配置文件加上注释。
