### ISSUE TITLE
goproxy-vps 版现在稳定不？

### ISSUE THREAD

**Issue by dapao9999** [phuslu/goproxy#904]
RT，在同一VPS上速度比SS要快不少，稳定的话准备弄个证书当主力工具使用了。

**Comment by phuslu** [comment]
正在把它更新到最新的官方 http2 的库，弄完应该就能说稳定了。
请关注

1. https://github.com/phuslu/goproxy/commits/server.vps
1. https://github.com/phuslu/net/commits/master

**Comment by phuslu** [comment]
r756 已发布。包含了 goproxy-vps 了，目前应该比较稳定了。

推荐配置可信证书，证书参数见

```
./goproxy-vps -h
```

**Comment by liweitd** [comment]
@phuslu @dapao9999 
goproxy-vps该如何使用？服务端和客户端具体该怎么设置？社长能不能给个简易教程，谢谢！

**Comment by jzp820927** [comment]
看来 let's en 要发挥作用了。

**Comment by dapao9999** [comment]
@liweitd ./goproxy-vps -h

**Comment by jzp820927** [comment]
不知道 goproxy-vps_linux_amd64-r10.7z 是服务端？还是客户端？还是服务端，客户端都用这个？

**Comment by phuslu** [comment]
目前只是一个单纯的 http2 proxy. 可以和 chrome 一起使用。

接下来要它改造为 h2c proxy, 这样就可以和 goproxy 客户端一起使用了。

**Comment by jzp820927** [comment]
也就是目前是类似于 stunnel 的咚咚，在两端转发。

**Comment by phuslu** [comment]
比较 stunnel， 应该有相当大的性能优势哒。

**Comment by jzp820927** [comment]
哦，我只是说的原理，性能的话，http2 肯定比 tls 性能好，毕竟是基于 google 的 spdy 开发的协议，做了很多优优化。

**Comment by wz7465** [comment]
搞笑了，http2性能比http好还可以这么说，tls只是一套加密系统，http2和http都用它来构成https，实际使用中http2专指第二代https

**Comment by phuslu** [comment]
也不尽然，http2 还有一个小众模式叫 h2c ， 不依赖 tls

goproxy 打算用 h2c 加 pre share 的 passwd 来实现。

**Comment by wz7465** [comment]
现在表现也不错了，直接stunnel客户端连goproxy-vps也能用的爽了

**Comment by phuslu** [comment]
https://github.com/phuslu/goproxy/issues/1470
