### ISSUE TITLE
启动失败，之前一直很OK 

### ISSUE THREAD

**Issue by gnehcforever** [phuslu/goproxy#915]
开机启动goproxy, 发现问题来了： error： cannot execute！

![qq 20160625113505](https://cloud.githubusercontent.com/assets/17717504/16354569/90c2d5da-3aca-11e6-8173-27e3db54f1b2.png)

**Comment by phuslu** [comment]
当前目录找不到 goproxy.exe ，一般被国内软件偷偷摸摸删除了。

**Comment by phuslu** [comment]
测试发现至少奇虎和腾讯的软件会偷偷删除，无任何提示。

楼主你看下是不是这个问题。

**Comment by gnehcforever** [comment]
@phuslu   老大，我很讨厌360 ，包括浏览器，杀毒都不用，我用的是 avast， 不过每次启动都要check下， 很讨厌，腾讯的东西，我也只有QQ 这一个聊天工具罢了， 好吧， 我去avast的 隔离区看看，再来汇报。

**Comment by gnehcforever** [comment]
@phuslu    我觉得你简直就是  大神级别的人物， 完全被你的预言猜对，其实我一直很困惑， 难道是我中招了么？   一直配置好好的，怎么会cannot execute 呢？  我立马去avast的 病区隔离区看，果然在那里面，  难道是我再逼我 删掉 avast的， 就是因为国内的  杀软都有可能被  阉割甚至监控我们，所以才  用了国外的 杀软， 可是最近avast  误报， 让我很纠结要不要  删除它。

![qq 20160625130344](https://cloud.githubusercontent.com/assets/17717504/16354828/70ef58c6-3ad6-11e6-96c4-c26420b0c581.png)

**Comment by gnehcforever** [comment]
对了，   还原之后，  完美运行， 话说 到晚上  我看YouTube， 竟然600+  goodIP !

**Comment by blob2015** [comment]
加入白名单就是了……

**Comment by caofengzi** [comment]
avaset的確會把goproxy.exe列為病毒文件。
