### ISSUE TITLE
怎么增加新的google appid？

### ISSUE THREAD

**Issue by Lemonjay** [phuslu/goproxy#916]
新注册的google账号，怎样建立新的Appid，不会啊？求助？

**Comment by wenliyang** [comment]
https://github.com/XX-net/XX-Net/wiki/how-to-create-my-appids

**Comment by 5fu** [comment]
现在app engine改版了 新建appid可以，但好像不能自己定义appid名了，谷歌会自动生成10几位的appid名，当然你嫌谷歌的不好还是可以自己改的，但必须小写字母开头。我以前的appid都是数字开头的

**Comment by caofengzi** [comment]
可以自定義名字。

**Comment by caofengzi** [comment]
可以自定義名字。

**Comment by blob2015** [comment]
还有，以前最多25个，现在最多一拖20，其实只要不是视频党、下载党，能用到10%都难，如果20个全开的话。

**Comment by gnehcforever** [comment]
@caofengzi      如何自定义名名字，找了半天找不到办法。

**Comment by jzp820927** [comment]
新建 appid 的时候，就会让你输入 id名字

**Comment by caofengzi** [comment]
@gnehcforever 進入申請appid主頁，右上方有個建立轉案點擊選擇新建立轉案然後會彈出一個讓你輸入名稱的對話框。

**Comment by gnehcforever** [comment]
@caofengzi   ，我输入了，不过最后给我分配一个带有数字的 ID

**Comment by caofengzi** [comment]
后面都有数字的。

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.5.43&pv=4.4.4&source=email_footer_2] On Sun, Jun 26, 2016 at 9:54 AM, gnehcforever < notifications@github.com [notifications@github.com] > wrote:
@caofengzi [https://github.com/caofengzi] ，我输入了，不过最后给我分配一个带有数字的 ID

**Comment by jzp820927** [comment]
@gnehcforever 如果你输入了自己的 id ，还给你分配一个后面带数字的，那就说明，你这个 ID 已经被别人用过了，换一个就行了。

**Comment by Lemonjay** [comment]
生成新的Appid后，上传时，提示：该Appid没有权限，不知道什么原因？

**Comment by Lemonjay** [comment]
上传Appid，出现错误
Error 403: --- begin server output ---
You do not have permission to modify this app (app_id=u's~********').
--- end server output ---
请按任意键继续. . .
怎样打开权限

**Comment by WLZLCX** [comment]
我好久不用GAE了，SS路过

**Comment by jzp820927** [comment]
@Lemonjay 要不就是你的 appid 写错了，要不就是你登录的 google 账号，不是你现在这个 appid 的 goole 账号。

**Comment by Lemonjay** [comment]
@wenliyang 提供的教程很详细。
谢了
