### ISSUE TITLE
goproxy上传“新建的Appid”出现权限错误——Error 403

### ISSUE THREAD

**Issue by Lemonjay** [phuslu/goproxy#923]
上传Appid，出现错误
Error 403: --- begin server output ---
You do not have permission to modify this app (app_id=u's~********').
--- end server output ---
请按任意键继续. . .
怎样打开权限？
求助？

**Comment by thundery1** [comment]
谷歌弱安全没打开吧？？https://www.google.com/settings/security/lesssecureapps

**Comment by caofengzi** [comment]
1:首先啟用弱安全應用2:首先在默認瀏覽器登錄谷歌帳號，因為上傳id需要用默認瀏覽器登錄谷歌帳號授權。3:最好用chrome作為默認瀏覽器因為chrome在首頁直接能夠登錄帳號。

**Comment by jzp820927** [comment]
要不就是你的 appid 写错了，要不就是你登录的 google 账号，不是你现在这个 appid 的 goole 账号。

**Comment by Lemonjay** [comment]
按照上述所说：

1. 先打开弱安全，
2. 再在默认的浏览器中登入“要上传Appid的gmail账号，

问题解决了。
谢了 @thundery1 @caofengzi @jzp820927
