### ISSUE TITLE
希望ServerName能够支持多域名，使用国内的反代，现在ServerName只支持一个域名成了瓶颈

### ISSUE THREAD

**Issue by tomb003** [phuslu/goproxy#931]
goproxy为了减少特征现在只支持一个ServerName，但使用国内的反代不存在这个需求，都是加密流量，ServerName也不会暴露给gfw，所以希望能支持多ServerName，这样HostMap和ServerName就可以多对多，大幅提高带宽。
为了保留原来的功能，可以在配置文件加个选项，由用户自己选择是否开启多ServerName。

**Comment by jzp820927** [comment]
你的指的多线程并行传输吧

**Comment by phuslu** [comment]
没有证据支持这个观点，从原理上讲瓶颈不在这里。

**Comment by jzp820927** [comment]
瓶颈应该在 GFW 在出口进行 掉包 和限流。

**Comment by tomb003** [comment]
浏览网页时每个图片，或者浏览视频时的每个分段，是用不同的HostMap中的IP，但都会去连接同一个ServerName服务器，结果最终带宽就变成了ServerName服务器的带宽限额，我这样理解对吗

**Comment by fengixng** [comment]
ServerName服务器是google官方的服务器，你个人怎么糟蹋也不会达到服务器的带宽限额

**Comment by phuslu** [comment]
不是这样，这种情况下，ServerName 里面的地址本地不会直连，是 HostMap 里面的 IP 去链接。

**Comment by tomb003** [comment]
画了张图
![1](https://cloud.githubusercontent.com/assets/8785738/16458678/837b59ca-3e52-11e6-95a9-9f9ae1bf6515.JPG)

**Comment by phuslu** [comment]
嗯，如图所示，是这样的。

但是 ServerName 的服务器是 google 的，GAE 服务器也是 google 的，其实都是 GFE (google front server)
它们的负载能力是一样的，所以把 ServerName 的服务器随机化并没有什么好处。

**Comment by phuslu** [comment]
另外 ServerName 服务器 和 GAE 服务器可以看作内网通信。

**Comment by tomb003** [comment]
ServerName服务器我用的不是Google官方的，用的是GGC，现在所有反代都去连接这一个GGC，最终带宽和服务能力变成了取决于这个GGC和GAE服务器之间的带宽，如果能多ServerName服务器，则每个反代都可以连接一个GGC，每个GGC再连接GAE服务器，瓶颈就变成了GAE与目标网站之间的带宽，GAE服务器的带宽应该很大，所以GAE服务器不会成为瓶颈，这样整条线就没有了瓶颈

**Comment by phuslu** [comment]
多ServerName服务器 这个做不到，只能 “随机化” ServerName 服务器。

即是，每次发起一个 https 请求时候随机挑选一个 ServerName 服务器让 SNI Proxy 去连接。

**Comment by tomb003** [comment]
可以按顺序循环使用，比方说：5个HostMapIP，3个ServerNameIP，连接时，前3个HostMapIP可以连接3个ServerNameIP，第4个HostMapIP连接第1个ServerNameIP，第5个HostMapIP连接第2个ServerNameIP，以此类推。

**Comment by phuslu** [comment]
goproxy 会假设 hostmap ip 随时有可能失效，这个逻辑不易实现。

不过谢谢提供思路，我再琢磨一下，如果有了比较成熟的想法，我会更新上来

**Comment by tomb003** [comment]
谢谢社长，可以这样假设，一旦用户自己使用了反代，说明用户知道自己在做什么，这样就由用户自己确保反代和ServerName服务器的可用，这样就可以减轻社长的程序压力，可以在配置文件加个选项，由用户自己选择是否开启多ServerName，默认关闭。

**Comment by MeABc** [comment]
可以按顺序循环使用，比方说：5个HostMapIP，3个ServerNameIP，连接时，前3个HostMapIP可以连接3个ServerNameIP，第4个HostMapIP连接第1个ServerNameIP，第5个HostMapIP连接第2个ServerNameIP，以此类推。



我个人认为这种方案不好，有规律，容易成特征。还是目前方案好，从头到尾就一个。
随机也不好，随机就会变成社长说的“乱跳”，这也是一种特征。
---------

但使用国内的反代不存在这个需求，都是加密流量，ServerName也不会暴露给gfw，


ServerName是可以检测到的。不要说GFW，只要有工具，你自已也可以。

**Comment by hcym** [comment]
草，黑科技

从头到尾看不懂
😿

**Comment by jzp820927** [comment]
我的想法是这样，确实 servername 就是 google_hk 的另一种表现形势，能不能和 google_hk 一样的模式，由程序内部进行测试优选，和 google_hk 一种模式，也可以在输出日志显示 ，good servername=数字，bad servername=数字 。。。

**Comment by tomb003** [comment]
@MeABc 在使用国内反代的时候ServerName实际上就和，没有使用反代时的HostMapIP一样，你说的那些检测在这两种情况下是一样的，所以要真的能检测到，随机或单一ServerName都没用。
在使用反代加GGC的情况下ServerName的多少肯定影响带宽，我的图里已经画的很清楚了。

**Comment by MeABc** [comment]
@tomb003 

1。先来说画图问题，

你画的图只是说明了GP的工作原理，并不是说明ServerName （[Server Name Indication](https://en.wikipedia.org/wiki/Server_Name_Indication)）的工作原理，那个图也不是SNI的工作原理图。
我个人认为你对ServerName（应是 Server Name Indication ，简称SNI）的理解有偏差。

2。所以要真的能检测到，随机或单一ServerName都没用。

a。ServerName 能检测到光我一个说了不算，我们不说远的，你只要搜下 issues ，你会发现有人能检测。
b。去年 twitter 上就有人发推说这个事（证实这个事）。
c。你要看下 gae.json 里 ServerName 都写了哪些，就拿一个举例，download.windowsupdate.com ，如果GFW光检测 SNI ，windows 用户都升级不了。
d。SNI 只是和GFW 对抗的一种手段（技术），我这样简单举例吧，假如现在前面有警察叔叔设卡拦路，只看车牌是不是军车车牌，那SNI就是这个军车车牌，我们换上军车车牌就可以通过。

**Comment by tomb003** [comment]
@MeABc 反代->ServerName 和不用反代 google_hk->gae服务器，这两种模式对检测的抵抗力是一样的，多ServerName时，每个反代和固定的一个ServerName连接，比所有反代都去连接一个ServerName的特征还更少呢。

**Comment by MeABc** [comment]
1。这两种怎么会一样呢？她们使用的车牌（SNI）都不一样。请 google sinproxy 。或者请你详细说她们一样在哪。

2。多ServerName时，每个反代和固定的一个ServerName连接，比所有反代都去连接一个ServerName的特征还更少呢。

这名话本身就前后矛盾，“多ServerName时” 比 “一个ServerName” 特征还更少？

**Comment by tomb003** [comment]
@MeABc 你还是不明白，反代并不能增加安全性，不管用不用反代，都要连google的服务器，不管是官方的还是ggc。
在数据传输之前要进行证书验证，证书只是一段文本，只要跳转几次再进行一次文本比对就可以确定是不是google服务器，速度非常快，gfw要获得google服务器是很容易的，只要异步比对证书就行了，对原始数据的传输一点都不影响，确定是google的证书就可以自动加入黑名单，根本不需要自己去找，或是有的网友认为的来像这样的论坛蹲点。
比对证书简单、方便、高效、可靠，可以自动获得所有被连接过的google服务器，所以gfw没有全封google服务器不是不能而是不想。
你一直在纠结反代提供的安全，那就跟郭德纲的相声一样，撒谎和杀人，只关注撒谎，杀人那事就不提了，哪个轻哪个重啊，只要检测证书就行了，用得着绕一大圈去检测反代吗，就算退一万步，真的去写检测反代的代码，最后会发现还是落到检测证书。
你不明白这两者为什么一样，显然还是没弄懂GoProxy的工作原理，其实我图中已经画的很清楚了。

**Comment by MeABc** [comment]
@tomb003 

你要是这样说，这楼就歪了。。。。

我真是佩服你的理解能力和想象能力。你的话从头到尾都是自相矛盾。
1。我什么时候说过 "反代并不能增加安全性" ? 我只是说你提的那个SNI方案不好，SNI和反代是一回事？
2。我什么时候“一直在纠结反代提供的安全”？我只是说你提的那个SNI方案不好，SNI和反代是一回事？
3。“你不明白这两者为什么一样”，SNI和反代是一回事？
4。“显然还是没弄懂GoProxy的工作原理，其实我图中已经画的很清楚了。”你现在说不懂GoProxy的工作原理，那你画的图是想说明什么？

SNI和反代是一回事？SNI和反代是一回事？SNI和反代是一回事？

**Comment by jzp820927** [comment]
佩服楼上2位的毅力啊，都讨论一天一夜了，希望你们的讨论能为FQ事业做出一点贡献。

**Comment by phuslu** [comment]
别争了，我有空改一版请大家测试一下，看看是否能提速就知道了。

**Comment by tomb003** [comment]
看到他最后回的才确定他真的没搞懂GoProxy的工作原理，其实一开始就让他解释一下他说的“车牌”是什么？具体的在GoProxy哪用怎么用就行了，结果浪费两个人那么多口舌，其实是鸡同鸭讲，两个人说的都不在一个地上。哈哈
