### ISSUE TITLE
新情况 R776通过pac共享iPhone上网彻底失效。

### ISSUE THREAD

**Issue by inkdie** [phuslu/goproxy#936]
iPhone无线局域网设置页面最下方，HTTP代理有三个选项，分别是关闭、手动、自动

自动一栏填写ip：端口/proxy.pac，更新到最新版本后彻底失效。

手动一栏分别填写ip和端口，目前可以正常使用。但是，手动属于全局代理，不实用。

**Comment by inkdie** [comment]
使用pac自动代理的时候，Safari打开谷歌等可以自动代理的网站时，日志没有任何反应。

**Comment by phuslu** [comment]
监听地址

**Comment by phuslu** [comment]
你用 iphone 的 safari 能打开 http://<ip>:<port>/proxy.pac 吗？

**Comment by inkdie** [comment]
![Uploading AE85E01C13EA68755204C470C628F42E.png…]()
![Uploading 152A1C3D2AD94B4E91A00945319CCBD4.png…]()

**Comment by inkdie** [comment]
![ae85e01c13ea68755204c470c628f42e](https://cloud.githubusercontent.com/assets/13928468/16452716/77f448f2-3e3c-11e6-8e76-a5a7952a6c5c.png)
![152a1c3d2ad94b4e91a00945319ccbd4](https://cloud.githubusercontent.com/assets/13928468/16452719/7b60d5be-3e3c-11e6-8a52-7bc9dd23cf6e.png)

**Comment by inkdie** [comment]
上面的截图是打开pac地址后最前面和最后面的截图，中间是一长串的地址。

**Comment by inkdie** [comment]
成功: 已终止 PID 为 5768 的进程。


------------------------------------------------------
GoProxy Version    : r776 (go/20b4a63 http2/4c2ac5a windows/amd64)
GoProxy Profile    : Default
Listen Address     : 0.0.0.0:8087
Enabled Filters    : stripssl,autorange|autoproxy,gae,direct|autorange
Pac Server         : http://0.0.0.0:8087/proxy.pac
------------------------------------------------------
I0629 21:01:58.739113   13024 autoproxy.go:420] start updater for https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt, expiry=24h0m0s, duration=1h0m0s
I0629 21:01:58.891158   13024 httpproxy.go:82] ListenAndServe("Default") on [::]:8087

**Comment by inkdie** [comment]
手机自动代理的时候，就是这样，因为版本是用了半自动升级的，所以，证书什么的都还在。

这不是第一次使用半自动升级。之前升级完成后没问题。

**Comment by phuslu** [comment]
这个情况不对，端口怎么变成 :10 了，比较奇怪，你改了什么配置吗？

**Comment by inkdie** [comment]
印象中，自从开始通过pac给手机共享代理之后，从来没有再出现过127.0.0.1:62000 这类的日志

**Comment by inkdie** [comment]
端口是这样的，我为了自己用着方便，通过路由器进行转发到公网ip，对应的端口就是10，没错。

**Comment by inkdie** [comment]
一直使用这种方式，当iPhone使用手动代理的时候，使用这个10端口也是没问题的 。

**Comment by phuslu** [comment]
那么在 iphone 里面要么改 ip 地址改成内网，要么改端口为 10

**Comment by inkdie** [comment]
对啊，我iPhone里面的设置一直是用的公网ip：10

**Comment by phuslu** [comment]
怀疑你的这说法，之前没有问题应该是你的路由器有一些这些配置，现在估计这些配置丢了。

至少我觉得如果之前没有问题，那么现在这个问题不在 goproxy 上。

**Comment by inkdie** [comment]
路由器端口转发没问题，因为手动代理可以正常使用。

**Comment by inkdie** [comment]
iPhone的手动代理只需要填写ip和端口。跟电脑的全局代理性质一样。

**Comment by phuslu** [comment]
谢谢反馈，我看下

**Comment by phuslu** [comment]
貌似的确是 bug, 正在修复。

**Comment by inkdie** [comment]
谢谢社长，有需要我配合的，我一定尽力。

**Comment by phuslu** [comment]
谢谢，r778 已经修复。正在发布。

为这个问题辩解一下，这个问题是 https://github.com/phuslu/goproxy/commit/1692c7be28f71a0db55e579791b31afd20cdeb98 引入的，这是对 pac 文件一个效率比较明显的优化。
可以引入了这个 bug，所以 r778 修复了。

再次谢谢。

**Comment by inkdie** [comment]
别客气，我等下在使用“半自动升级”更新一下，然后反馈测试结果。

**Comment by inkdie** [comment]
对了，我之前一直反馈的，iPhone使用pac自动代理的情况下。可以打开tumblr网站、可以登录、可以正常看图片，唯独超过10秒的视频不能播放的问题，有办法解决吗？

**Comment by phuslu** [comment]
这个是 autorange 的问题，对移动播放器需要识别出来并做些特殊的优化。请等待修复。

**Comment by phuslu** [comment]
r778 已经发布为正式版，请升级。

**Comment by phuslu** [comment]
如果还有问题的话，请删除当前目录的 proxy.pac 然后再重新载入。

**Comment by inkdie** [comment]
现在的情况是这样的，我下载的全新的压缩包。
只保留了两个user文件，然后把r778版本新生成的证书导入进了手机（是先删除旧证书，然后安装新证书）。

依然是全局代理没问题，自动代理没反应。

跟之前不一样的是，我用Safari打开pac文件，居然在公网ip后面出现了内网端口

也就是你刚刚质疑的10端口，居然变成了8087端口。pac文件的首端和末端都是变成了这样。

**Comment by inkdie** [comment]
http://124.65.73.62:10/proxy.pac 为了方便测试，我先把自己的公网ip给你。测试完了，我再删除。

**Comment by inkdie** [comment]
我的两个user文件里面只有appid、密码、和hk ip地址一大串，第二个user文件里面只有修改为0.0.0.0的监听地址

**Comment by inkdie** [comment]
httpproxy.user.json
{
	"Default": {
		"Enabled": true,
		"Address": "0.0.0.0:8087",
	},
}

gae.user.json

{
	"AppIDs": [
		我的id
	],
	"Password": "我的密码",
	"HostMap" : {
		"google_hk": [
			我自己找的ip
		],
		"google_cn": [
			"www.g.cn",
			"www.google.cn"
		]
	},
}

**Comment by phuslu** [comment]
谢谢反馈，比较想象的复杂些。r779 正在发布

**Comment by inkdie** [comment]
电脑chrome使用的SwitchyOmega插件里面，GoAgent和GoAgent PAC里面都是按照路由器转发到后的外网ip:10端口来配置的，所以，现在chrome里的GoAgent还可以正常使用，但是GoAgent PAC跟手机一样，不能用了。

因为我的一个端口转发，给你带来这么多麻烦，非常抱歉。

虽然我现在还没测试，但是，我想，如果我内网ip转发到外网ip的时候，保持端口号一致，应该可以避免这种情况。如果这个问题实在不好修复，我可以尝试一下同意内外端口号。

**Comment by phuslu** [comment]
不用，这的确是 goproxy 需要解决的问题。

**Comment by inkdie** [comment]
好的，我会刷新页面到779发布成功再测试反馈

**Comment by inkdie** [comment]
最新反馈：R779，下载、解压，覆盖778，删除pac文件
管理员运行，重新生成了pac文件，现在pac文件里的端口号变成10了。电脑chrome和手机Safari打开pac文件查看，端口号一致都是10

pac代理，电脑正常，手机依然不行
全局代理，电脑和手机都正常

**Comment by inkdie** [comment]
I0629 22:29:04.161525   15312 autoproxy.go:233] 127.0.0.1:54019 "AUTOPROXY ProxyPac GET /proxy.pac HTTP/1.1" - -

日志里依然会出现127.0.0.1这个ip地址

**Comment by phuslu** [comment]
呃，刚刚发布的 r779 有个 bug, 我重新发布了一次。
你重试一下呢。

**Comment by inkdie** [comment]
function FindProxyForURL(url, host) {
    if (isPlainHostName(host) ||
        host.indexOf('127.') == 0 ||
        host.indexOf('192.168.') == 0 ||
        host.indexOf('10.') == 0 ||
        shExpMatch(host, 'localhost.*')) {
        return 'DIRECT';
    }

    proxy = MyFindProxyForURL(url, host)
    if (proxy != "DIRECT") {
        return proxy
    }

    var lastPos;
    do {
        if (sites.hasOwnProperty(host)) {
            return 'PROXY localhost:8087';
        }
        lastPos = host.indexOf('.') + 1;
        host = host.slice(lastPos);
    } while (lastPos >= 1);
    return 'DIRECT';
}


抱歉，刚刚发现
打开pac文件，末端出现了 return 'PROXY localhost:8087';

会不会跟这个有关系？

**Comment by phuslu** [comment]
嗯，请删除 proxy.pac/goproxy.exe ， 然后用 get-latest-goproxy.cmd 升级

**Comment by inkdie** [comment]
最新反馈，重新下载了779，覆盖、删除pac文件，重新生成

再次查看，上一楼反馈的 return 'PROXY localhost:8087';变成了外网ip:10
手机，依然不行。

**Comment by phuslu** [comment]
不对啊，你看 http://124.65.73.62:10/proxy.pac 这个 FindProxyForURL 里面依然是 PROXY localhost:8087

**Comment by inkdie** [comment]
社长：嗯，请删除 proxy.pac/goproxy.exe ， 然后用 get-latest-goproxy.cmd 升级

这个操作好像有问题啊。删除goproxy.exe之后， get-latest-goproxy.cmd不能运行啊。

**Comment by phuslu** [comment]
哦，我明白了，你在之前用本地 访问过一次。

那没啥好办法了，你现在手动编辑 proxy.pac 吧，把 PROXY localhost:8087 改成 PROXY localhost:10

**Comment by inkdie** [comment]
function FindProxyForURL(url, host) {
    if (isPlainHostName(host) ||
        host.indexOf('127.') == 0 ||
        host.indexOf('192.168.') == 0 ||
        host.indexOf('10.') == 0 ||
        shExpMatch(host, 'localhost.*')) {
        return 'DIRECT';
    }

    proxy = MyFindProxyForURL(url, host)
    if (proxy != "DIRECT") {
        return proxy
    }

    var lastPos;
    do {
        if (sites.hasOwnProperty(host)) {
            return 'PROXY 124.65.73.62:10';
        }
        lastPos = host.indexOf('.') + 1;
        host = host.slice(lastPos);
    } while (lastPos >= 1);
    return 'DIRECT';
}

我俩看到的不一样？我这边显示端口正常啊

**Comment by inkdie** [comment]
// User-defined FindProxyForURL
function FindProxyForURL(url, host) {
    if (shExpMatch(host, '*.google*.*') ||
       dnsDomainIs(host, '.ggpht.com') ||
       dnsDomainIs(host, '.gstatic.com') ||
       host == 'goo.gl') {
        return 'PROXY localhost:10';
    }
    return 'DIRECT';
}

我用notepad++打开pac文件，显示这样

**Comment by phuslu** [comment]
你打开 proxy.pac 看下呢

**Comment by phuslu** [comment]
那现在应该好了，你把手机 wifi 关闭再重连一下，应该就好了

**Comment by inkdie** [comment]
这样是不是逻辑有问题？  如果我直接打开pac文件显示return 'PROXY localhost:10';
那么这个localhost:10'实际是我的内网ip和端口 172.16.1.2:10

**Comment by phuslu** [comment]
不会，通过网路访问的时候，goproxy 会处理这个端口变成 公网 IP

**Comment by inkdie** [comment]
执行wifi关闭再打开之后，确实好了。

原理不是很懂，希望我没有误导到你。

**Comment by phuslu** [comment]
好说好说，多谢反馈。

让我知道我之前不了解 goproxy 的用法，帮助完善它。

**Comment by inkdie** [comment]
问一个外行的问题，如果我有两部手机，一部手机配置外网ip＋10端口，一部手机配置内网ip+8087端口，pac文件会变成什么样呢？

实际使用中，应该没人这么配置，仅仅是好奇。社长觉得我无厘头的话，可以不回复，时间不早了，非常感谢社长的耐心解答

**Comment by inkdie** [comment]
对了，我会在评论中改掉我的外网ip，社长的一个回复中出现了我的外网ip，希望设备配合修改一下。不想长时间暴露，谢谢啦

**Comment by phuslu** [comment]
已删除

**Comment by phuslu** [comment]
这个会继续完善，解决你这个担忧。
