### ISSUE TITLE
geometry of spacetime is described in terms of a certain vacuum solution of Einstein's equation

### ISSUE THREAD

**Issue by drg78rnvgh** [phuslu/goproxy#940]
Each interpreter goes through each phase only once, and the phases follow in a fixed sequence.Most of what happens in Perl's compile phase is compilation, and most of what happens in Perl's run phase is execution, but there are significant exceptions.

**Comment by hcym** [comment]
你用谷歌的服务器怎么不知道

就是不用gae，只用谷歌服务，时间久了

连你性癖好都一清二楚

脑子有病，翻来覆去问

**Comment by fengixng** [comment]
网络定位不是只根据IP定位的

**Comment by cannanlly** [comment]
tor i2p随便隐身

**Comment by gnehcforever** [comment]
2楼  好邪恶

**Comment by LGA1150** [comment]
默认情况下，使用gp访问Google搜索不会经过GAE

**Comment by maryjeck** [comment]
gp是直连google服务器，当然是显示你的真实IP啊，但是连其他网站，好像就是google服务器的IP
