### ISSUE TITLE
翻墙的严冬就要来临了！！！

### ISSUE THREAD

**Issue by fletchere** [phuslu/goproxy#942]
广东电信只要一翻墙就断网，整治网络跟帖效果显著啊，有没有其他的墙友有类似的感受？

**Comment by github-xx** [comment]
是你设置 问题吧，看新闻FASTER要来到中国吧。IP还是能找到可用的。

**Comment by fletchere** [comment]
@github-xx IP找得到有个屁用，人家直接断网。

**Comment by jzmswe** [comment]
何必争论，找个广东电信代理试一下，不就知道了。

**Comment by angle1895** [comment]
广东电信无异常

**Comment by fletchere** [comment]
@angle1895 可能是我的个案，现在又没问题了。

**Comment by fletchere** [comment]
@angle1895 可能是我的个案，现在又好了。
