### ISSUE TITLE
德国 Steganos Online Shield VPN 特惠1年/Windscribe VPN SE 特惠1年

### ISSUE THREAD

**Issue by jasonliul** [phuslu/goproxy#944]
https://www.steganos.com/specials/?m=chip0516&p=sos
每月限量5G.

主页
https://www.steganos.com/en/steganos-online-shield-vpn

**Comment by silversnow0-0** [comment]
@jasonliul 我英文比较蹩脚- -去主页如何怎么弄？

**Comment by jzp820927** [comment]
@jasonliul 话说，这个 SN 码该怎么输，半天没找到。

**Comment by jasonliul** [comment]
Windscribe VPN SE 特惠1年
http://sharewareonsale.com/s/windscribe-vpn-giveaway-coupon-sale

每月50G

节点
     US East
    US West
    United Kingdom
    Canada
    Hong Kong
    France
    Germany
    Luxembourg
    Netherlands

**Comment by sishentibu** [comment]
这种收费VPN，是不是相对来说比较靠谱的啊。速度、安全性来说

**Comment by jzp820927** [comment]
老外的都安全/

**Comment by sishentibu** [comment]
吼吼，
Windscribe VPN SE  这个我试了下只安装火狐扩展，没起作用。是不是要安客户端才行

**Comment by jzp820927** [comment]
我试过客户端，没问题，扩展还没测试

**Comment by sishentibu** [comment]
在虚拟机中试了下，速度极慢，远不如goproxy

**Comment by jzp820927** [comment]
肯定不能和 GAE 相比了，除了 akamai，谁有 google 的服务器多

**Comment by sishentibu** [comment]
看来，goproxy也是一种比较高级的代理方式啊

**Comment by jzp820927** [comment]
GAE 可以说是，永远不会死，也是承受能力最强的代理了。

**Comment by sishentibu** [comment]
前几天看到发出的issue，https://github.com/phuslu/goproxy/issues/941 不知道影响多大

**Comment by jzp820927** [comment]
目前反馈的人不多，但也不算个例，静观其变吧，看看会不会扩大

**Comment by jzp820927** [comment]
1,2个肯定不会有问题，10个以下应该都是安全的
