### ISSUE TITLE
请问服务端的php文件在哪？

### ISSUE THREAD

**Issue by burnegg** [phuslu/goproxy#949]
找了各个页面，并没有找到啊 。。

**Comment by jzp820927** [comment]
https://github.com/phuslu/goproxy/tree/server.php-go

**Comment by burnegg** [comment]
深夜回复啊，感动，这个是go语言实现的啊，想找php语言的。找到了，原来是在branch那里选，感谢

**Comment by jzp820927** [comment]
我能说，go 的性能比 PHP 高麽

**Comment by burnegg** [comment]
服务器go语言环境不好配置啊

**Comment by jzp820927** [comment]
不过一般支持 GO 的也很少，基本上只有 paas，普通空间一般都只能 PHP。
