### ISSUE TITLE
文档不太详细，新手完全无法学会  Invalid URL 什么问题

### ISSUE THREAD

**Issue by sbmzhcn** [phuslu/goproxy#952]
Invalid URL

The requested URL "[no URL]", is invalid.
Reference #9.6d1b8f7a.1467788861.b4a4e1a

**Comment by jzp820927** [comment]
说明不够详细，无法确认问题。

**Comment by caofengzi** [comment]
現在的gp配置文件已經非常寬鬆了。

**Comment by LGA1150** [comment]
你填错IP了

**Comment by sbmzhcn** [comment]
后来变好了，我找了一些ip之后。

**Comment by Lemonjay** [comment]
@LGA1150  ip填错了
