### ISSUE TITLE
goproxy在校外无法登入YouTube

### ISSUE THREAD

**Issue by Lemonjay** [phuslu/goproxy#958]
有谁知道怎么修改goproxy的ip吗？怎样配置goproxy。求助！

**Comment by Lemonjay** [comment]
对了，你们用hosts吗，racaljk/hosts很长时间都不能用了！求助！

**Comment by wenliyang** [comment]
https://github.com/phuslu/goproxy/blob/wiki/SimpleGuide.md
https://github.com/phuslu/goproxy/blob/wiki/ConfigIntroduce.md

写那么清楚，看完再来问

**Comment by jzmswe** [comment]
用HOSTS，自找IP。最近找了个IP，用了几个月都没事，速度还不错，爽。

**Comment by Lemonjay** [comment]
额，@wenliyang，谢了！
