### ISSUE TITLE
基础问题一：如何让一些网站使用GP？

### ISSUE THREAD

**Issue by blob2015** [phuslu/goproxy#965]
各种封锁，怎么单独添加、破，以"ccthere.com"为例

---------------

gfwlist里面添加，不怎么好用——gfwlist会不时更新、替换，个人编辑不容易。
然后，因为不懂，逐次在在gae.user.json的ForceGAE、ServerName、StieToAlias添加"ccthere.com"，都无效
如何编辑？
谢谢

@phuslu

**Comment by MeABc** [comment]
大哥，自定义 pac ，你搜一下。

**Comment by lazureice** [comment]
1.用浏览器插件,随意添加网站
2.到这里反馈https://github.com/gfwlist/gfwlist/issues
////
PS:
话说这个网站gfwlist里有:".ccthere.com"但我看不懂list的格式.
一般不是前面加"||"吗?

**Comment by MeABc** [comment]
哈哈， blob2015 刚好举了一个 gfwlist 里有的地址。。。

要不用浏览器插件，要不自定义 pac

**Comment by hcym** [comment]
自定义 pac

**Comment by jzp820927** [comment]
不懂就用全局，懂的话，就用 插件自定规则，或者自定 PAC

**Comment by fengixng** [comment]
如果使用chrome的话，我建议使用SwitchyOmega管理

**Comment by MeABc** [comment]
不知道你们有没有发现 SwitchyOmega 和 FoxyProxy 在解析 gfwlist 时有问题， 51cto 在这两个插件下都走代理， FoxyProxy 最差，连 duoshuo 等很多网站都走代理。对于这两个我是忍无可忍。

现在我也在自定义自已PAC文件。先把 gfwlist 转换成pac ，再添加自已常访问的网站，这样也差不多了。

**Comment by lazureice** [comment]
呃,这两个网站在gfwlist里?

**Comment by MeABc** [comment]
没有，在 gfwlist 的 issues 里也早就有人反应了，其作者猜测是由一些规则引起的触发。

**Comment by blob2015** [comment]
@MeABc @jzp820927 @lazureice @fengixng @hcym 
多谢老兄，**就是gfwlist有的** :grinning: 
诡异的地方就在这里 :grinning: 
**全局完全没问题**
FoxyProxy确实差劲，经常乱动……操作性也不好【快捷键垃圾，状态栏图标也不灵……】
试试pac

**Comment by yeahwu** [comment]
有一款插件叫autoproxy，不是gfwlist的原因，放出来给各位试试吧
https://github.com/XX-net/XX-Net/raw/master/SwitchyOmega/AutoProxy.xpi
然后修改一下里面的规则地址

**Comment by lazureice** [comment]
yeahwu大大自己修改的?
我记得火狐范也有个修改版,有什么区别吗

**Comment by jzp820927** [comment]
还是 PAC 方便，绿色无污染。

**Comment by yeahwu** [comment]
哦，这不是俺改的！俺只是分享出来。
天朝屁民 <notifications@github.com>于2016年7月19日 周二11:19写道：

**Comment by MeABc** [comment]
已收！非常感谢！

**Comment by blob2015** [comment]
@yeahwu 
多谢老兄，曾经也一直在用AP，还用过黑螃蟹的改版
