### ISSUE TITLE
求助：中文网站打不开

### ISSUE THREAD

**Issue by Alvin9999** [phuslu/goproxy#968]
昨晚和今天早上，使用goagent打开中文网站显示
Error: Not Found

The requested URL /_gh/ps/14684632879690.568698572922.gif was not found on this server.

**Comment by Alvin9999** [comment]
还想求助下，怎么用goagent使用gvs ip，之前的goagent是可以的，后来不行了。由于当时gws ip数目还客观，所以就凑合用了，但是现在好ip数目越来越少了。个人有点恋旧goagent。

**Comment by jzp820927** [comment]
明明有 goproxy 你不用，非要用过时的 goagent，都是社长的作品，难道你还信不过 goproxy

**Comment by wenliyang** [comment]
goproxy 速度明显比 goagent 要快
而且 goagent 不再维护，不明白还有啥继续使用它的理由

**Comment by Alvin9999** [comment]
换新ip后，可以看中文网站了。但YouTube视频无法播放，可以打开YouTube网站。

**Comment by Alvin9999** [comment]
有苦说不出

**Comment by Alvin9999** [comment]
问题已解决，ip的问题，即使是能用的ip，但还是有区别。谢谢楼上两位大哥的提醒，等时机成熟会换goproxy的。

**Comment by jzp820927** [comment]
如果确实对 goagent 情有独钟，也可以用 xxnet ，xxnet 的核心就是 goagent。
