### ISSUE TITLE
Google Code的GoAgent Issues备份

### ISSUE THREAD

**Issue by CNMan** [phuslu/goproxy#97]

**Comment by CNMan** [comment]
https://goo.gl/R6KJ9j
下载goagent_issues.tar.gz解压缩后给每个文件加上扩展名.html拖到浏览器就可以看了

**Comment by sundaqing1969** [comment]
如何批量加扩展名？

**Comment by ARwMq9b6** [comment]
https://code.google.com/export-to-github/request-export/goagent

看吧，删之前水那么多贴，不能导入了。

**Comment by xyuanmu** [comment]
提一下，楼主，板瓦工的邀请链接已经失效了。

**Comment by CNMan** [comment]
@sundaqing1969 处理过了，重新下载一下
@xyuanmu 不是失效，是被买没货了
@ARwMq9b6 能导到github来，需要是项目所有人才行

**Comment by ARwMq9b6** [comment]
申请成为项目所有人。

**Comment by xyz12810** [comment]
怎么下载不了了？

**Comment by sundaqing1969** [comment]
@CNMan谢谢

**Comment by yfdyh000** [comment]
重新压缩了一下，tar.gz 23MB变7z 11MB。https://goo.gl/XjBMeo 
附赠，前两天抓取的所有的问题摘要csv。https://goo.gl/cxDrtG

**Comment by xyuanmu** [comment]
话说要是文件名是标题的话就好了，现在都是ID要检索有很困难

**Comment by yfdyh000** [comment]
@xyuanmu 从那个csv搜索再找就可以了。

**Comment by xyuanmu** [comment]
@yfdyh000 太棒了，早上还没注意csv是什么
