### ISSUE TITLE
请帮助测试 r837 的 GAE 性能。

### ISSUE THREAD

**Issue by phuslu** [phuslu/goproxy#982]
r835~r837 引入了两个性能相关的改动: https://github.com/phuslu/goproxy/commit/cf32afe 和 https://github.com/phuslu/go/commit/f699e76e5b5231007c23a54a08f5388d5210c549

理想状态下上会让 GAE 打开网页更流畅。
但是由于干扰的存在，这一优化反而可能会比之前卡顿.

请大家和自己手头的版本测试一下 (r835 之前的版本）做个比较并反馈。
注意两点

- 使用同一 IP 集合
- 在相同的连续时间段比较。

谢谢！

**Comment by phuslu** [comment]
想了想，这个优化太冒险了，接下来会去除。

**Comment by phuslu** [comment]
r838 改得保守了一些了，这样虽然有优化，但是也补一点看得出来了。
见 https://github.com/phuslu/go/commit/53eb648855a0eb9188c979cfb6851b796d747bc3 和 https://github.com/phuslu/goproxy/commit/0ce8b3f9a310f7fbc75cd2f71d83a657b996ec0f

请随意吧。

**Comment by MeABc** [comment]
社长，不要去除这个优化啊。 优化很明显。

反馈一下我测试体会， r834 r837 r838 
（实际上就两个版本， r834和r838 。把 r838 的改为 "MaxIdleConnsPerHost": 64 可以说是 r837）

测试有5个网站。反复3-4次。强制 H2 。IP不变，同一浏览器。

如果说 r834 是正常情况，那 r837 就是秒开。最明显的是同时多开几个多图的网页（你懂的），那也是秒开。

再来说说 r837 和 r838 之间的区别。其它4个网站没看出来，就一个网站，https://twitter.com/  无登陆状态首页， "瀑布" 下拉， r837 和 r834 与 r838 区别就出来了， r834卡住( 不能下拉 )， r838 能下拉，但不稳定 (页面不全)， r837 很快，且页面齐全。

总结，个人倾向 还是把 "MaxIdleConnsPerHost" 改成 64 好点。

**Comment by cclu** [comment]
这个会不会触发GAE收费规则，我记得几年前有个规避选项，是把gae idle设置成1-2。

我建项目时，是手工锁定app engine max idle最大到2的

在 2016年7月20日 下午10:32，MeABc <notifications@github.com>写道：

**Comment by phuslu** [comment]
并不会。

这里只保持了 tcp 连接，并不会有一直存在或周期性的针对 gae 应用的 HTTP 请求。

所以不会。

**Comment by jzp820927** [comment]
期待更多不同地区，不同平台，不同时间段测试结果。
