### ISSUE TITLE
wallproxy-2.2.5 不能连接服务器，请大神给个修改可用gvsip的版本，谢谢大家的帮助

### ISSUE THREAD

**Issue by slulu164** [phuslu/goproxy#987]
我是用老板的wallproxy-2.1.18的服务端，客户端用的是wallproxy-2.2.5，ip是gws在go里可用
在wallproxy-2.2.5里使用不能连接，是设置问题，我只修改了我的appid 和cn hk 下面的ip,其他没动。
我看了#811的文章，请大神给个修改好的wallproxy-2.2.5版本和wp 的 proxy.py ，和 替换后的 服务端。
就是可用go上传wallproxy-2.2.5服务端的修改文件。谢谢各位老大！

**Comment by jzp820927** [comment]
现在 goproxy 已经很成熟了，没必要再去用老产品喇叭

**Comment by hcym** [comment]
goA用gws的ip还行啊

速度是不行，毕竟兼容好

老大一直担心老版抗干扰，我用的没感觉

三四个gws的ip，一直ok

**Comment by slulu164** [comment]
谢谢jzp820927 大大，我有许多旧版的appid 想利用下，go的换ip台麻烦了。
goproxy 我在用速度不错，就是不习惯换ip，感觉现在的变动很大

**Comment by jzp820927** [comment]
建议你把 旧 appid 重新部署下 服务端吧，改 wallproxy 挺麻烦的，服务端，客户端都要修改。如果真要修改 #811 已经说的很明白了，不知道你哪儿没看懂
