### ISSUE TITLE
Goproxy有办法在国内三大引擎(BAE,SAE,ACE)部署吗?

### ISSUE THREAD

**Issue by karas1999** [phuslu/goproxy#99]
首先说一下, Goagent php模式部署国内这三大引擎都是没有问题的. 唯一问题是大文件断流问题. 我部署这个主要是翻公司的墙去看视频, 一般的youku视频网站用goagent php都OK, 但是看百度云之类的, 或者一些山寨动漫网站, 会经常卡住. 由于目前我在用的国外翻墙是OpenShift+Goproxy, Youtube感觉很不错, 没有断流问题, 所以想如果能用Goproxy取代Goagent php, 想必不错. 
实际试部署以后, 发现goproxy部署在php空间完全没办法运行起来. 全部报403或404错. 我觉得应该是这几个引擎不支持Golang的问题吧? BAE好像有提到可以申请自定义Runtime来支持golang, 但配置比较麻烦, 没怎么看明白. 请教各位大大有没有在这三个引擎上部署成功的?

**Comment by lxl53535** [comment]
你去部署sivbe.net，免费域名去freenom.com注册，ml、cf什么的都不错

**Comment by lxl53535** [comment]
看youtube1280p无压力，像这种中国代理的日本空间 国内第一选择

**Comment by ARwMq9b6** [comment]
index.php 能部署应该能用，功能和 index.go 差不多吧。 
index.php 大文件断流确实有是个大问题，等 GoProxy 还未释出的 autorange 功能出来后就能解决了吧。

**Comment by ARwMq9b6** [comment]
@lxl53535 谢谢，先去爽爽。

**Comment by karas1999** [comment]
@lxl53535 谢谢回答. 但是我的问题主要是要翻公司的墙, 访问国内的网站, 比如youku, 土豆, 百度云网盘什么的. 不是访问Youtube. 
Youtube我现在用Openshift和Bluemix的服务已经非常快了. 
简单来说, 我用同时开两个代理服务器: 
一个国外的, 用来翻GFW, 这个我用的是OpenShift和Bluemix. 用Goproxy已经跑的很好了.
另一个国内的, 用来翻公司墙, 这个我用的是百度BAE和阿里ACE(新浪SAE现在比较贵, 不用了). 这个目前只能跑Goagent PHP, 不能跑Goproxy. 会有大文件断流问题.

**Comment by ARwMq9b6** [comment]
@karas1999 目前可用 index.php 的代理作 GoAgent gae 模式的前置代理，支持 autorange ，能解决断流的问题。

另外试试部署 index.js 或 index.py , 或许就没有断流的问题了。

**Comment by ARwMq9b6** [comment]
sivbe.net:

>因为最近删站删的手软(消耗资源的，违规的……)，虽然为免费空间，也请不要让真正需要的朋友无法获得资源，特改变策略如下：
申请前三日免费，续费为每日一毛（当然还可以通过抽奖获取免费时间）。

**Comment by karas1999** [comment]
@ARwMq9b6 谢谢. 你说的意思是, 本地用GAE模式, 然后GAE的IP指向一个国外的PHP Server, 用PHP Server做跳板去访问GAE的IP是吗? 这个我以前倒没想过. 回头我去试一下. 
不过这个应该也是解决访问国外网站的问题吧. 目前我国外网站用OpenShift+Goproxy已经没有断流的问题了. 
我目前只是翻公司墙访问国内网站有这个问题, 因为用国外服务器翻墙访问国内网站相当慢. 所以我都是用BAE或ACE去翻. 不过我都是用index.php, 没试过index.js或index.py, 这两个不知道怎么部署在服务器上, 是不是服务器要使用非php的支持环境呢? 比如服务器要支持Node.js或者Python? 
不过目前感觉goagent php其实也还挺好用的. 我用的还是很古老的2.11版本goagent. BAE代理打开自家的百度云网盘还是相当快的, 今天看了一个中午视频, 都没有什么卡顿了. 而且BAE还不限流量. 被公司封锁的朋友可以试一下.

**Comment by ARwMq9b6** [comment]
@karas1999 利用 GoAgent 的 autorange 分小段缓冲功能以解决大文件断流的问题：设置 GoAgent 的前置代理，可选择 Shadowsocks (127.0.0.1:1080), Lantern (127.0.0.1:8787) 或 GoAgent php (127.0.0.1:8088). 

服务器要支持Node.js或者Python, 目测 index.js 和 index.py 就算不使用 autorange 也没有大文件断流的问题。

**Comment by karas1999** [comment]
@ARwMq9b6 明白了, 谢谢回复.

**Comment by lg560852** [comment]
freenom.com的域名总是解析不出来，比如换个ISP就解析不了了
有好办法没？
