### ISSUE TITLE
r856 stripssl.go  tls.Conn.Handshake error

### ISSUE THREAD

**Issue by MeABc** [phuslu/goproxy#997]
![2016-07-28_021027](https://cloud.githubusercontent.com/assets/18194126/17186757/16dba6d0-5469-11e6-935e-5676038fc448.png)

社长，这是什么情况？

**Comment by MeABc** [comment]
URL: https://iplookup.flagfox.net/

**Comment by MeABc** [comment]
又，如果我在 autorange.json 里添加 "*.githubusercontent.com", 就会出现以下情况：
![2016-07-28_023628](https://cloud.githubusercontent.com/assets/18194126/17187613/91091976-546c-11e6-9746-5d3f5b7b1900.png)

**Comment by MeABc** [comment]
上述 https://github.com 和 https://iplookup.flagfox.net/ 我都设为走 gae(GP)

**Comment by MeABc** [comment]
上述图2，访问 youtube 或者 autorange.json 里相关网站时也会触发。

**Comment by jzp820927** [comment]
autorange 修复很久了，一直没修复好，而且最近的 commit 和 autorange 好像都无关。不知道社长有没啥计划。
